// JUDGE — composition-level laws that the other suites reach only indirectly: exact feed recording + deterministic replay
// (P03), the closed 1m bar history (J01 / J11: cold start over the public REST OHLC path, live continuation, a minute
// without trades stays a gap), bounded preparation slots and readiness records (J11), and the OBSERVE / replay CLI paths
// (a hypothetical account, no credentials, no private transport, the same recording twice -> the same state digest).
import test from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import { mkdtempSync, rmSync, writeFileSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';

const TEST_DATA = mkdtempSync(path.join(tmpdir(), 'cobra-judge-comp-')); process.env.COBRA_DATA_DIR = TEST_DATA;
const { createExecutionFeed } = await import('../execution/feed.js'); const { createFeedRecorder, readRecording, replayRecording, RECORDING_VERSION } = await import('../judge/recorder.js'); const { fakeReplayClock } = await import('../judge/replay-clock.js');
const { createBarHistory, KRAKEN_OHLC_URL } = await import('../judge/history.js'); const { BARS_REQUIRED, BAR_MS } = await import('../judge/features.js');
const { selectPreparation, readinessRecord, PREP_SLOTS_MAX } = await import('../judge/readiness.js');
const { runCli } = await import('../bin/judge.js'); const { composeJudge } = await import('../judge/composition.js'); const { createMemoryJournal } = await import('../execution/journal.js');
const { fakeClock, SPEC, T0 } = await import('./helpers/judge.js'); const { instrumentSpec } = await import('../execution/contract.js'); const { crc32 } = await import('../lib/crc32.js');

const PAPER_POLICY = path.resolve('judge/samples/policy.paper-reference.json');
const fmt = (v, d) => v.toFixed(d).replace('.', '').replace(/^0+/, ''); const crcFor = (asks, bids) => crc32([...asks.slice(0, 10), ...bids.slice(0, 10)].map(([p, q]) => fmt(p, 1) + fmt(q, 8)).join(''));
const bookMsg = (asks, bids, ts, type = 'update') => JSON.stringify({ channel: 'book', type, data: [{ symbol: 'XBT/USD', asks: asks.map(([price, qty]) => ({ price, qty })), bids: bids.map(([price, qty]) => ({ price, qty })), checksum: crcFor(asks, bids), timestamp: new Date(ts).toISOString() }] });
const tradeMsg = (price, ts, id, side = 'buy', qty = 0.05) => JSON.stringify({ channel: 'trade', type: 'update', data: [{ symbol: 'XBT/USD', side, price, qty, ord_type: 'market', trade_id: id, timestamp: new Date(ts).toISOString() }] });
const HANDSHAKE = [JSON.stringify({ channel: 'instrument', type: 'snapshot', data: { pairs: [{ symbol: 'XBT/USD', price_precision: 1, qty_precision: 8 }] } }), JSON.stringify({ method: 'subscribe', success: true, result: { channel: 'trade', symbol: 'XBT/USD' } })];
const specFor = (coin) => instrumentSpec({ venue: 'kraken', pairKey: `${coin}USD`, altname: `${coin}USD`, wsname: `${coin}/USD`, base: coin, quote: 'ZUSD', canonicalCoin: coin, status: 'online', priceIncrement: '0.01', qtyIncrement: '0.00000001', orderMin: '0.01', costMin: '0.5', priceDecimals: 2, qtyDecimals: 8, observedTs: T0, source: 'FIXTURE' });
test.after(() => rmSync(TEST_DATA, { recursive: true, force: true }));

// a scripted session: handshake, a snapshot, three updates and four trades, one disconnect / reconnect, then more books
function session(feed, clock, recorder = null) { const send = (raw) => { if (recorder) recorder.record(raw, clock.now()); feed.ingest(raw, clock.now()); }; feed.admit('XBT/USD', { priority: 'CANDIDATE', reason: 'test' }); if (recorder) recorder.record(null, clock.now(), { connect: true }); feed.onConnect(clock.now()); for (const h of HANDSHAKE) send(h); send(bookMsg([[100010.0, 5], [100020.0, 4]], [[99990.0, 5], [99980.0, 4]], clock.now(), 'snapshot')); let id = 0; for (let i = 0; i < 3; i += 1) { clock.advance(1000); send(bookMsg([[100010.0, 5 - i]], [[99990.0, 5 - i]], clock.now())); send(tradeMsg(100000 + i, clock.now(), ++id)); } clock.advance(500); if (recorder) recorder.record(null, clock.now(), { disconnect: true }); feed.onDisconnect(clock.now()); clock.advance(2000); if (recorder) recorder.record(null, clock.now(), { connect: true }); feed.onConnect(clock.now()); for (const h of HANDSHAKE) send(h); send(bookMsg([[100030.0, 5]], [[100000.0, 5]], clock.now(), 'snapshot')); clock.advance(1000); send(tradeMsg(100031, clock.now(), ++id)); }

test('P03/E11. exact recording + deterministic replay: the recorder keeps the accepted wire bytes and local receipt clocks (connect / disconnect markers included); replaying them through a fresh feed with the replay clock yields the same book digests, epochs, receipt sequences and trade identities; the file is versioned and bounded', async () => {
  const dir = path.join(TEST_DATA, 'rec'); const clock = fakeClock(); const feedA = createExecutionFeed({ clock: clock.now }); const rec = createFeedRecorder({ dir, clock: clock.now }); const seen = []; feedA.subscribe((e) => { if (e.kind === 'BOOK') seen.push(['B', e.snapshot.feedEpoch, e.snapshot.receiptSequence, e.snapshot.digest]); else if (e.kind === 'TRADE') seen.push(['T', e.trade.feedEpoch, e.trade.receiptSequence, e.trade.nativeTradeId, e.trade.price]); });
  session(feedA, clock, rec); rec.stop(); const st = rec.status(); assert.equal(st.state, 'COMPLETE', 'closeout R11: a clean stop seals the recording COMPLETE (a closed manifest), the old STOPPED label carried no inventory'); assert.ok(st.messages >= 12, `${st.messages} messages`); assert.ok(existsSync(path.join(dir, 'feed-000.jsonl')));
  const rows = [...readRecording(dir)]; assert.equal(rows.filter((r) => r.connect).length, 2); assert.equal(rows.filter((r) => r.disconnect).length, 1); assert.ok(rows.every((r) => Number.isSafeInteger(r.receiptTs)));
  const replayed = []; const rclock = fakeReplayClock(rows[0].receiptTs); const feedB = createExecutionFeed({ clock: rclock.now }); feedB.admit('XBT/USD', { priority: 'CANDIDATE', reason: 'replay' }); feedB.subscribe((e) => { if (e.kind === 'BOOK') replayed.push(['B', e.snapshot.feedEpoch, e.snapshot.receiptSequence, e.snapshot.digest]); else if (e.kind === 'TRADE') replayed.push(['T', e.trade.feedEpoch, e.trade.receiptSequence, e.trade.nativeTradeId, e.trade.price]); });
  const ticks = []; const r = await replayRecording({ dir, feed: feedB, clock: rclock, onTick: (t) => { ticks.push(t); } }); assert.equal(r.messages, st.messages); assert.deepEqual(replayed, seen, 'same bytes + same clocks -> same identities and digests'); assert.ok(ticks.length >= 10 && ticks.every((t, i) => i === 0 || t - ticks[i - 1] === 250), 'tick boundaries fire in order at the recorded cadence');
  const rows2 = [...readRecording(dir)]; assert.deepEqual(rows2, rows, 'reading is pure');
  const badDir = path.join(TEST_DATA, 'badrec'); rmSync(badDir, { recursive: true, force: true }); const { mkdirSync } = await import('node:fs'); mkdirSync(badDir, { recursive: true }); writeFileSync(path.join(badDir, 'feed-000.jsonl'), `${JSON.stringify({ header: 'judge-feed-recording-0' })}\n`); assert.throws(() => [...readRecording(badDir)], /recording version/); assert.equal(RECORDING_VERSION, 'judge-feed-recording-1');
});

test('J01/J11-history. the 1m bar history: a cold start through the public OHLC path keeps only COMPLETE bars with a receipt floor (the provisional last bar and rows after `last` are dropped); 61 contiguous bars are served or null; a minute without trades is a gap that names its start; live trades continue the series only under continuous coverage and never across an epoch gap; refresh is bounded and never re-entrant', async () => {
  const clock = fakeClock(); const end = Math.floor(clock.now() / BAR_MS) * BAR_MS; const rows = []; for (let k = 70; k >= 1; k -= 1) { const open = end - k * BAR_MS; rows.push([open / 1000, '100', '101', '99', '100.5', '100.2', k === 30 ? '0' : '1.5', k === 30 ? 0 : 12]); } rows.push([end / 1000, '100', '101', '99', '100', '100', '0.1', 1]); // the current (provisional) minute
  let calls = 0; const fetchImpl = async (url) => { calls += 1; assert.ok(url.startsWith(`${KRAKEN_OHLC_URL}?pair=XXBTZUSD&interval=1`)); return { text: async () => JSON.stringify({ error: [], result: { XXBTZUSD: rows, last: end / 1000 } }) }; };
  const h = createBarHistory({ clock: clock.now, fetchImpl, pairKeyOf: (s) => (s === 'XBT/USD' ? 'XXBTZUSD' : null) });
  assert.equal(h.needsRefresh('XBT/USD', clock.now()), true); const r = await h.refresh('XBT/USD'); assert.equal(r.ok, true); assert.equal(r.added, 70, 'the provisional minute is not a bar'); assert.equal(h.needsRefresh('XBT/USD', clock.now()), false);
  assert.equal(h.bars('XBT/USD', clock.now()), null, 'the empty minute (k=30) is a gap inside the last 61'); const st = h.status('XBT/USD'); assert.equal(st.missingOf61, 1); assert.deepEqual(st.missingStarts, [end - 30 * BAR_MS]); assert.equal(st.knownAtFloorTs, clock.now()); assert.equal(st.earliestReadyTs, end + BAR_MS);
  // 32 minutes later the gap has aged out of the block only if live continuation supplied the newer minutes
  const epoch = 1; let tid = 0; for (let m = 0; m < 32; m += 1) { const start = end + m * BAR_MS; for (let i = 0; i < 3; i += 1) h.onTrade({ symbol: 'XBT/USD', eventTs: start + 10_000 * (i + 1), receiptTs: start + 10_000 * (i + 1) + 5, price: '100.1', qty: '0.01', quoteNotional: '1.001', feedEpoch: epoch, nativeTradeId: String(++tid), fromSubscriptionSnapshot: false }); clock.setWall(start + BAR_MS); h.advance('XBT/USD', clock.now(), { coverage: { continuous: true, startTs: end - BAR_MS } }); }
  const block = h.bars('XBT/USD', clock.now()); assert.ok(block, JSON.stringify(h.status('XBT/USD'))); assert.equal(block.length, BARS_REQUIRED); assert.equal(block.at(-1).source, 'LIVE_TRADES'); assert.equal(block.at(-1).coverage, 'CONTINUOUS_TRADES'); assert.equal(block[0].source, 'REST_OHLC');
  h.onTrade({ symbol: 'XBT/USD', eventTs: clock.now() + 1000, receiptTs: clock.now() + 1000, price: '100', qty: '0.01', quoteNotional: '1', feedEpoch: epoch + 1, nativeTradeId: 'x', fromSubscriptionSnapshot: false }); h.onTrade({ symbol: 'XBT/USD', eventTs: clock.now() + 2000, receiptTs: clock.now() + 2000, price: '100', qty: '0.01', quoteNotional: '1', feedEpoch: epoch, nativeTradeId: 'y', fromSubscriptionSnapshot: false }); clock.setWall(clock.now() + BAR_MS); h.advance('XBT/USD', clock.now(), { coverage: { continuous: true, startTs: end } }); assert.equal(h.bars('XBT/USD', clock.now()), null, 'a minute straddling a feed epoch is a gap, never a bar');
  h.onTrade({ symbol: 'XBT/USD', eventTs: clock.now() + 1000, receiptTs: clock.now() + 1000, price: '100', qty: '0.01', quoteNotional: '1', feedEpoch: 3, nativeTradeId: 'z', fromSubscriptionSnapshot: true }); assert.equal(h.status('XBT/USD').live, 0, 'a subscription snapshot trade never builds a bar');
  const p1 = h.refresh('XBT/USD'); const p2 = h.refresh('XBT/USD'); assert.equal((await p2).reason, 'IN_FLIGHT'); assert.equal((await p1).ok, true); assert.equal(calls, 2);
  assert.equal((await createBarHistory({ clock: clock.now, fetchImpl: null, pairKeyOf: () => 'X' }).refresh('XBT/USD')).reason, 'NO_TRANSPORT'); assert.equal((await createBarHistory({ clock: clock.now, fetchImpl, pairKeyOf: () => null }).refresh('XBT/USD')).reason, 'NO_PAIR_KEY');
});

test('J11. preparation slots and readiness records: at most six warm candidates, newest nomination first, held assets never contest, expired nominations drop, a lost slot names PREEMPTED_BY_NEWER_NOMINATION or NOMINATION_EXPIRED with its prepared duration; readiness names each missing interval (BARS_61 with have / need, FLOW_21MIN with the earliest ready clock, BOOK_FRESH, BASELINE_BOOKS_30, CATALYST_CASE) and a veto / halted instrument is BLOCKED; readiness is never permission', () => {
  const now = T0; const nom = (assetId, ageMs, source = 'UNIVERSE') => ({ symbol: `${assetId}/USD`, assetId, source, nominationKnownAtTs: now - ageMs });
  const noms = [nom('BTC', 5000), nom('ETH', 4000), nom('SOL', 3000), nom('ADA', 2000), nom('DOT', 1000), nom('LTC', 900), nom('XRP', 800), nom('AVAX', 700), nom('OLD', 3_600_001), nom('HELD', 100)];
  const s1 = selectPreparation({ nominations: noms, held: new Set(['HELD']), remainingSlots: 99, nowTs: now }); assert.equal(s1.slots, PREP_SLOTS_MAX); assert.deepEqual(s1.selected.map((n) => n.assetId), ['AVAX', 'XRP', 'LTC', 'DOT', 'ADA', 'SOL']); assert.deepEqual(s1.preempted.map((p) => p.assetId), ['ETH', 'BTC']); assert.ok(!s1.selected.some((n) => n.assetId === 'OLD' || n.assetId === 'HELD')); assert.deepEqual(s1.held, ['HELD']);
  const previous = new Map(s1.selected.map((n) => [n.assetId, { ...n, preparedSinceTs: now - 30_000 }])); const later = now + 10_000; const s2 = selectPreparation({ nominations: [...noms.filter((n) => n.assetId !== 'SOL'), nom('NEW', 0)].map((n) => ({ ...n, nominationKnownAtTs: n.assetId === 'NEW' ? later : n.nominationKnownAtTs })), held: new Set(['HELD']), remainingSlots: 6, previous, nowTs: later });
  assert.deepEqual(s2.selected.map((n) => n.assetId), ['NEW', 'AVAX', 'XRP', 'LTC', 'DOT', 'ADA']); assert.equal(s2.selected[1].preparedSinceTs, now - 30_000, 'a kept candidate keeps its preparation clock'); assert.deepEqual(s2.lost, [{ assetId: 'SOL', reason: 'NOMINATION_EXPIRED', preparedMs: 40_000 }]);
  const bars = Array.from({ length: 60 }, (_, i) => ({ periodStartTs: now - (61 - i) * 60_000, periodEndTs: now - (60 - i) * 60_000, open: 1, high: 1, low: 1, close: 1, volumeQuote: 1, volumeBase: 1, closed: true }));
  const r1 = readinessRecord({ setupId: 'ABSORPTION_RECLAIM', bars, flowCoverage: { continuous: true, startTs: now - 600_000 }, bookHealth: { usable: true }, baselineBooks: 3, nowTs: now }); assert.equal(r1.state, 'HISTORY_WARMING'); assert.deepEqual(r1.missing.map((m) => m.id), ['BARS_61', 'FLOW_21MIN', 'BASELINE_BOOKS_30'], 'absorption needs the 30 baseline books; range ignition does not'); assert.deepEqual(readinessRecord({ setupId: 'RANGE_IGNITION', bars, flowCoverage: { continuous: true, startTs: now - 600_000 }, bookHealth: { usable: true }, baselineBooks: 3, nowTs: now }).missing.map((m) => m.id), ['BARS_61', 'FLOW_21MIN']); assert.equal(r1.missing[0].have, 60); assert.equal(r1.missing[1].earliestReadyTs, now - 600_000 + 21 * 60_000); assert.match(r1.note, /not permission/);
  const r2 = readinessRecord({ setupId: 'CATALYST_TRANSMISSION', bars: [...bars, { periodStartTs: now - 60_000, periodEndTs: now, open: 1, high: 1, low: 1, close: 1, volumeQuote: 1, volumeBase: 1, closed: true }], flowCoverage: { continuous: true, startTs: now - 30 * 60_000 }, bookHealth: { usable: true }, baselineBooks: 40, nowTs: now }); assert.equal(r2.state, 'CASE_REQUIRED'); assert.deepEqual(r2.missing.map((m) => m.id), ['CATALYST_CASE']);
  assert.equal(readinessRecord({ ...{ setupId: 'RANGE_IGNITION', bars, flowCoverage: null, bookHealth: null, nowTs: now }, controls: { vetoed: true, caged: false } }).state, 'BLOCKED'); assert.equal(readinessRecord({ setupId: 'RANGE_IGNITION', bars, flowCoverage: null, bookHealth: null, nowTs: now, instrumentOk: false }).missing[0].id, 'INSTRUMENT_SPEC'); assert.throws(() => readinessRecord({ setupId: 'MOON', nowTs: now }), /unknown setup/);
});

test('J11/E03. the composition bounds preparation to the policy slots (six of eight nominations, newest first; the loser is released, a held asset stays); OBSERVE composes a hypothetical memory account with the PAPER adapter, no credentials and no private transport; the same recording replayed twice through the CLI yields the same state digest; verify reads the recording; a LIVE policy cannot run-observe', async () => {
  const clock = fakeClock(); const coins = ['BTC', 'ETH', 'SOL', 'ADA', 'DOT', 'LTC', 'XRP', 'AVAX']; const specs = coins.map((c) => (c === 'BTC' ? SPEC : specFor(c))); let noms = coins.map((c, i) => ({ symbol: c === 'BTC' ? 'XBT/USD' : `${c}/USD`, assetId: c, nominationKnownAtTs: T0 - (coins.length - i) * 1000 }));
  const run = await composeJudge({ policyFile: PAPER_POLICY, mode: 'OBSERVE', accountId: 'obs-t', journal: createMemoryJournal(), clock: { now: clock.now, monotonic: clock.monotonic, observeWall: () => null, status: () => ({ trusted: true }), expired: (t) => clock.now() > t }, specs, nominations: () => noms, writeProjection: false, codeDigest: 'c'.repeat(64), log: () => {} });
  assert.equal(run.kind, 'PAPER'); assert.equal(run.adapter.kind, 'PAPER'); assert.equal(run.credentialsPresent, false); assert.equal(run.keyFingerprint, null);
  const prep = run.admitNominations(); assert.equal(prep.slots, 6); assert.deepEqual(prep.selected, ['AVAX', 'XRP', 'LTC', 'DOT', 'ADA', 'SOL']); assert.deepEqual(prep.preempted.map((p) => p.assetId), ['ETH', 'BTC']); assert.equal(run.judge.candidates().length, 6);
  clock.advance(10_000); noms = [...noms, { symbol: 'LINK/USD', assetId: 'LINK', nominationKnownAtTs: clock.now() }]; run.registerSpec(specFor('LINK')); const prep2 = run.admitNominations(); assert.deepEqual(prep2.selected, ['LINK', 'AVAX', 'XRP', 'LTC', 'DOT', 'ADA']); assert.deepEqual(prep2.lost.map((l) => [l.assetId, l.reason]), [['SOL', 'PREEMPTED_BY_NEWER_NOMINATION']]); assert.equal(run.judge.candidates().some((c) => c.assetId === 'SOL'), false, 'the preempted candidate is released'); assert.equal(run.projection().preparation.slots, 6); await run.stop();
  // the CLI: run-observe with an injected tape that replays a scripted session into the execution feed and records it; then replay twice
  const specsFile = path.join(TEST_DATA, 'specs.json'); writeFileSync(specsFile, JSON.stringify([SPEC])); const recDir = path.join(TEST_DATA, 'cli-rec'); const c2 = fakeClock();
  const tapeRunner = async ({ executionFeed }) => { const inner = createExecutionFeed({ clock: c2.now }); void inner; const send = (raw) => executionFeed.ingest(raw, c2.now()); executionFeed.onConnect(c2.now()); for (const h of HANDSHAKE) send(h); send(bookMsg([[100010.0, 5]], [[99990.0, 5]], c2.now(), 'snapshot')); for (let i = 0; i < 5; i += 1) { c2.advance(1000); send(bookMsg([[100010.0, 5 - i * 0.5]], [[99990.0, 5]], c2.now())); send(tradeMsg(100000 + i, c2.now(), i + 1)); } };
  const out = []; const code = await runCli(['run-observe', '--policy', PAPER_POLICY, '--pairs', 'XBT/USD', '--record', recDir], { env: {}, stdout: (s) => out.push(s), stderr: () => {}, clock: c2.now, tapeRunner, specsSource: () => [SPEC], cwd: process.cwd() }); assert.equal(code, 0, out.join('')); const res = JSON.parse(out.join('')); assert.equal(res.mode, 'OBSERVE'); assert.equal(res.projection.adapter, 'PAPER'); assert.equal(res.projection.credentialsPresent, false); assert.equal(res.projection.recorder.state, 'COMPLETE'); assert.ok(res.projection.recorder.messages >= 12);
  const rep = async () => { const o = []; const c = await runCli(['replay', '--policy', PAPER_POLICY, '--recording', recDir, '--pairs', 'XBT/USD', '--specs', specsFile], { env: {}, stdout: (s) => o.push(s), stderr: () => {}, cwd: process.cwd() }); assert.equal(c, 0, o.join('')); return JSON.parse(o.join('')); };
  const r1 = await rep(); const r2 = await rep(); assert.equal(r1.replayed.messages, res.projection.recorder.messages); assert.equal(r1.stateDigest, r2.stateDigest, 'same recording + policy + seed + code -> same state digest'); assert.equal(r1.accountId, 'replay-paper-reference-usd500'); assert.equal(r1.evaluation.calibrationState, 'UNVALIDATED_HYPOTHESIS');
  const v = []; assert.equal(await runCli(['verify', '--recording', recDir], { env: {}, stdout: (s) => v.push(s), stderr: () => {}, cwd: process.cwd() }), 0); assert.equal(JSON.parse(v.join('')).checks.recording.messages, res.projection.recorder.messages);
  const live = path.join(TEST_DATA, 'live.json'); const raw = JSON.parse((await import('node:fs')).readFileSync(PAPER_POLICY, 'utf8')); writeFileSync(live, JSON.stringify({ ...raw, mode: 'LIVE', execution: { ...raw.execution, adapter: 'KRAKEN' }, live: { allocationCeiling: '500', reinvestment: 'NONE', ownerLimits: null, armExpiryMs: 86_400_000, canaryMaxBuyConsiderationWithFees: null, keyEnv: 'K', secretEnv: 'S' } })); const e = []; assert.equal(await runCli(['run-observe', '--policy', live], { env: {}, stdout: () => {}, stderr: (s) => e.push(s), tapeRunner, cwd: process.cwd() }), 2); assert.match(e.join(''), /MODE_MISMATCH/);
});
