// C01 / C02 (focused completion §0 / §8): the fences this completion must not cross — no protected file changed, no new
// dependency, research configuration cannot reach a PAPER / LIVE composition, no PAPER / LIVE account is touched by the offline
// experiment, the legacy evidence / analysis v1 contracts and the intake input modes are untouched, no all-sensors gate returned,
// and the offline guard + gate are part of the test law (a denied attempt is a gate failure, not an application error).
import test from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import { readFileSync, readdirSync, existsSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';

const sha = (file) => createHash('sha256').update(readFileSync(file)).digest('hex');
const atHead = (file) => { try { return createHash('sha256').update(execFileSync('git', ['show', `HEAD:${file}`], { cwd: process.cwd(), maxBuffer: 64 * 1024 * 1024 })).digest('hex'); } catch { return null; } };
// the reviewed baseline hashes (§0): recorded before any production edit of this completion
const PROTECTED = { 'cobra.config.json': '68c16400fb0d776ce304cd97ae40ee742e32f2838d1b57f52bdefb0dd9c9c79a', 'package.json': '823094445a7070fe07987b19b33c4c6fa51e97df46bb54b4ee7d55b4634c4e87' /* SERPENT paper closeout: three paper scripts (paper, paper:preflight, paper:inventory); dependencies unchanged */, 'package-lock.json': '85ade4bd1ce094c37c89574a0adbe4e057e7d1a39358c45dcc3336925ee4ac6e' };
const NEW_MODULES = ['judge/experiment-bundle.js', 'judge/experiment-replay.js', 'judge/experiment-store.js', 'judge/experiment.js', 'judge/experiment-records.js', 'test/helpers/offline-guard.mjs', 'test/helpers/scripted-ws.js', 'tools/offline-gate.mjs'];

test('C01. protected bytes and dependencies: cobra.config.json, package.json and the lockfile carry the reviewed baseline digests; doctrine/MISSION.md, the sample policies, the legacy evidence / analysis v1 contracts and every migration before 9 are byte-identical to the committed tree; the new modules import only relative modules and node builtins (no new dependency); research configuration is refused outside REPLAY and the experiment replay never initializes a PAPER / LIVE account or reads credentials', async () => {
  for (const [file, digest] of Object.entries(PROTECTED)) assert.equal(sha(file), digest, `${file} is protected`);
  for (const file of ['doctrine/MISSION.md', 'judge/samples/policy.paper-reference.json', 'evidence/contract.js', 'socrates/contract.js', 'persistence/migrate.js']) { const h = atHead(file); if (h) assert.equal(sha(file), h, `${file} is unchanged from the committed tree`); }
  const { MIGRATIONS, SCHEMA_VERSION } = await import('../persistence/schema.js'); assert.equal(SCHEMA_VERSION, 9); assert.equal(MIGRATIONS.length, 9); assert.equal(MIGRATIONS[8].version, 9); assert.ok(MIGRATIONS[8].statements.every((s) => /CREATE (TABLE|INDEX) IF NOT EXISTS/.test(s)), 'migration 9 is additive'); assert.ok(!MIGRATIONS[8].statements.some((s) => /ALTER|DROP|UPDATE|DELETE/i.test(s)));
  for (const file of NEW_MODULES) { const src = readFileSync(file, 'utf8'); const specs = [...src.matchAll(/^import .* from '([^']+)';/gm)].map((m) => m[1]); for (const s of specs) assert.ok(s.startsWith('.') || s.startsWith('node:'), `${file} imports ${s}: no new dependency`); }
  const pkg = JSON.parse(readFileSync('package.json', 'utf8')); assert.deepEqual(Object.keys(pkg.dependencies ?? {}).sort(), Object.keys(pkg.dependencies ?? {}).sort()); assert.ok(!('judge/experiment-replay.js' in (pkg.dependencies ?? {})));
  const { composeJudge } = await import('../judge/composition.js'); const { createMemoryJournal } = await import('../execution/journal.js'); const { SPEC } = await import('./helpers/judge.js'); const PAPER = path.resolve('judge/samples/policy.paper-reference.json');
  for (const research of [{ armRule: { setups: [] } }, { exitPolicy: { plannedTarget: false } }, { verdictSink: () => {} }]) await assert.rejects(composeJudge({ policyFile: PAPER, mode: 'OBSERVE', accountId: 'fence', journal: createMemoryJournal(), specs: [SPEC], writeProjection: false, codeDigest: 'c'.repeat(64), log: () => {}, ...research }), /only a REPLAY composition/, `${Object.keys(research)[0]} is research-only`);
  const { createJudge } = await import('../judge/judge.js'); assert.throws(() => createJudge({ accountId: 'x', policy: { setups: { enabled: [] }, universe: { excludeBases: [] }, execution: {} }, policyDigest: 'a'.repeat(64), dispatcher: { state: () => ({}), ev: () => ({}), onCommit: () => {}, revision: () => 0 }, feed: null, clock: { now: () => 1, monotonic: () => 1 }, specOf: () => null, feeOf: () => null, mode: 'PAPER', armRule: { setups: [] } }), /only a REPLAY composition/);
  // the offline experiment: a database factory that must never be asked for a connection, an env without credentials
  const { recordExperimentFixture } = await import('./helpers/experiment-fixture.js'); const { runCli } = await import('../bin/judge.js'); const { mkdtempSync } = await import('node:fs'); const { tmpdir } = await import('node:os'); const dir = mkdtempSync(path.join(tmpdir(), 'cobra-fence-')); process.env.COBRA_DATA_DIR = dir;
  const fx = await recordExperimentFixture(path.join(dir, 'f', 'bundle')); let dbAsked = 0; const out = []; const code = await runCli(['replay-experiment', '--policy', fx.policyFile, '--bundle', fx.dir, '--experiment', 'exp-fence', '--arms', 'REF_COMBINED,CASH'], { env: {}, stdout: (s) => out.push(s), stderr: () => {}, cwd: process.cwd(), dbFactory: () => { dbAsked += 1; throw new Error('the experiment replay must not open the database'); } });
  assert.equal(code, 0, out.join('')); assert.equal(dbAsked, 0, 'no PAPER / LIVE authority is touched by the offline experiment'); const rep = JSON.parse(out.join('')); assert.ok(Object.values(rep.arms).every((a) => !a.accountId || a.accountId.startsWith('replay-')), 'every arm is a REPLAY account'); assert.match(rep.law, /no PAPER \/ LIVE account, provider, model or exchange/);
});

test('C02. semantics preserved and the gate is law: the three intake input modes keep their meaning, EXECUTION_SCORING needs no sensor beyond the feed / instrument / fee / history (no all-sensors gate), D2 / D3 / catalyst inputs are named capabilities, the legacy evaluateArms is labelled HISTORICAL_ATTRIBUTION, the offline guard names its version and the gate script fails a run with one unexpected attempt, and the documentation names the gate command', async () => {
  const { SETUP_INPUT_MODES, SETUPS } = await import('../judge/setups.js'); assert.deepEqual(SETUPS, ['RANGE_IGNITION', 'ABSORPTION_RECLAIM', 'TREND_PULLBACK_CONTINUATION', 'CATALYST_TRANSMISSION']); for (const s of ['RANGE_IGNITION', 'ABSORPTION_RECLAIM', 'TREND_PULLBACK_CONTINUATION']) assert.deepEqual(SETUP_INPUT_MODES[s], ['MARKET_DIRECT', 'CASE_ENRICHED'], `${s}: MARKET_DIRECT / CASE_ENRICHED preserved`); assert.deepEqual(SETUP_INPUT_MODES.CATALYST_TRANSMISSION, ['CATALYST_CASE']);
  const { CAPABILITY_REQUIREMENTS } = await import('../judge/experiment-bundle.js'); assert.deepEqual(CAPABILITY_REQUIREMENTS.EXECUTION_SCORING, ['FEED', 'INSTRUMENT', 'FEE', 'HISTORY'], 'no all-sensors / all-LLMs gate: scoring needs the market inputs only'); assert.deepEqual(CAPABILITY_REQUIREMENTS.D2_FLOW_EVENT_RESPONSE, ['WHALE']); assert.deepEqual(CAPABILITY_REQUIREMENTS.D3_RESIDUAL_IGNITION, ['PEER']); assert.deepEqual(CAPABILITY_REQUIREMENTS.CATALYST_EVIDENCE, ['CASE']);
  const { EXPERIMENT_ARMS } = await import('../judge/experiment-replay.js'); assert.equal(EXPERIMENT_ARMS.REF_COMBINED.needs, undefined, 'the reference arm needs no sensor'); const { evaluateArms } = await import('../judge/challengers.js'); const legacy = evaluateArms({ accountId: 'x', events: [], arms: ['CASH'], seed: 's' }); assert.equal(legacy.kind, 'HISTORICAL_ATTRIBUTION'); assert.match(legacy.limitation, /NOT a strategy comparison/);
  const { OFFLINE_GUARD } = await import('./helpers/offline-guard.mjs'); assert.equal(OFFLINE_GUARD.version, 'cobra-offline-guard-1'); assert.ok(existsSync('tools/offline-gate.mjs'));
  const doc = readFileSync('docs/JUDGE-EXECUTION.md', 'utf8'); assert.ok(doc.includes('tools/offline-gate.mjs'), 'the gate command is documented'); assert.ok(doc.includes('--import=') && doc.includes('offline-guard.mjs')); assert.ok(doc.includes('replay-experiment') && doc.includes('declare-experiment') && doc.includes('open-holdout') && doc.includes('lock-candidate') && doc.includes('evaluate-experiment'), 'every experiment command is documented');
  const checklist = readFileSync('docs/JUDGE-CLOSEOUT-ACCEPTANCE.md', 'utf8'); for (const id of ['N01', 'N02', 'I01', 'I02', 'I03', 'S01', 'S02', 'S03', 'S04', 'S05', 'S06', 'S07', 'S08', 'H01', 'H02', 'H03', 'H04', 'H05', 'H06', 'H07', 'H08', 'H09', 'H10', 'H11', 'H12', 'H13', 'D01', 'D02', 'C01', 'C02']) assert.ok(new RegExp(`\\| ${id} \\|`).test(checklist), `${id} has a checklist row`);
  const tests = readdirSync('test').filter((f) => f.endsWith('.test.js')); for (const f of tests) assert.ok(!readFileSync(path.join('test', f), 'utf8').includes('COBRA_OFFLINE_GUARD_RUN = \'selftest'), `${f}: no test file grants itself a self-test identity by name`);
});
