// JUDGE — the four Santiment large-transfer metrics (F01, F02, F05): registry -> owner routing -> provider (5m native
// interval) -> observation -> context -> packet -> exact broker satisfaction; entitlement-denied and delayed history;
// old 1h / 1d routes still supported; F04 is the existing market / Socrates suites staying green in the full gate.
import test from 'node:test';
import assert from 'node:assert/strict';
import { WHALE_METRIC_IDS, WHALE_METRIC_UNITS, ONCHAIN_METRIC_IDS, FAMILY_REGISTRY, familyMetricIds, WINDOWS, observationError } from '../market-lab/contracts.js';
import { SANTIMENT_METRICS, SANTIMENT_INTERVALS, createSantimentClient } from '../market-lab/providers/santiment.js';
import { createResearchOwner, NETWORK_NATIVE_IDS } from '../market-lab/owner.js';
import { buildContext, NETWORK_METRIC_OF, COMPONENT_FAMILY } from '../market-lab/context.js';
import { METRIC_MAP, buildResearchEvidenceV2 } from '../evidence/research-builder.js';
import { createBroker } from '../socrates/broker.js';
import { ENDPOINTS } from '../market-lab/registry.js';
import { loadPolicy } from '../market-lab/policy.js';
import { createHttpTransport } from '../market-lab/transport.js';
import { T0, tmp, json, btcOnly, includedPlan, H, SEALED_REF } from './helpers/market-closeout.js';
import { rmSync } from 'node:fs';

const santimentPolicy = () => loadPolicy(includedPlan(H.policyWith({ providers: ['SANTIMENT'] }), 'SANTIMENT'));
const series5m = (count = 4, endTs = T0) => ({ data: { getMetric: { timeseriesData: Array.from({ length: count }, (_, i) => ({ datetime: new Date(Math.floor(endTs / 300_000) * 300_000 - (count - 1 - i) * 300_000).toISOString(), value: 10 + i })) } } });
const req = (metricIds, over = {}) => ({ requestKey: 'Q1', requestKind: 'DETAIL', family: 'NETWORK_ACTIVITY', metricIds, subjectRef: 'BTC', windowStartTs: null, windowEndTs: null, requestedMaxAgeMs: null, hypothesisRefs: [], question: 'q', interpretationIfSupported: 'x', interpretationIfContradicted: 'y', ...over });
const OPTS = { analysisId: 'soc2-' + 'a'.repeat(40), caseSubject: { canonicalCoin: 'BTC', registeredRefs: [] }, asOfTs: T0, deadlineTs: T0 + 60_000 };

test('F01. every map carries the four exact ids and units: ONCHAIN_METRIC_IDS, the NETWORK_ACTIVITY family registry, owner native routing, the Santiment mapping with its 5m interval, the closed context binding and the packet / broker METRIC_MAP; the registry endpoint documents them; the >1m group is nested, never summed', () => {
  assert.deepEqual(WHALE_METRIC_IDS, ['whale_transaction_count_100k_usd_to_inf', 'whale_transaction_count_1m_usd_to_inf', 'whale_transaction_volume_100k_usd_to_inf', 'whale_transaction_volume_1m_usd_to_inf']);
  for (const id of WHALE_METRIC_IDS) { assert.ok(ONCHAIN_METRIC_IDS.includes(id), id); assert.equal(FAMILY_REGISTRY.NETWORK_ACTIVITY.metrics[id], WHALE_METRIC_UNITS[id]); assert.deepEqual(NETWORK_NATIVE_IDS[id], [id]); assert.equal(SANTIMENT_METRICS[id].family, 'NETWORK_ACTIVITY'); assert.equal(SANTIMENT_METRICS[id].unit, WHALE_METRIC_UNITS[id]); assert.deepEqual(SANTIMENT_METRICS[id].intervals, ['5m', '1h', '1d']); assert.equal(SANTIMENT_METRICS[id].entity, null, 'large transfers without entity attribution'); assert.equal(NETWORK_METRIC_OF[id], id); assert.equal(COMPONENT_FAMILY[id], 'NETWORK_ACTIVITY'); assert.equal(METRIC_MAP.NETWORK_ACTIVITY[id].kind, 'MARKET_NETWORK_CONTEXT'); assert.deepEqual(METRIC_MAP.NETWORK_ACTIVITY[id].native, [id]); }
  assert.ok(familyMetricIds('NETWORK_ACTIVITY').length === 9); assert.equal(SANTIMENT_INTERVALS['5m'].stepMs, 300_000); assert.equal(SANTIMENT_INTERVALS['5m'].window, 'five_minutes'); assert.ok(WINDOWS.includes('five_minutes'));
  assert.match(ENDPOINTS.find((e) => e.providerId === 'SANTIMENT').mapping, /whale_transaction_volume_1m_usd_to_inf/); assert.equal(SANTIMENT_METRICS.active_addresses.intervals, undefined, 'existing metrics keep 1d / 1h');
});

test('F05/F02. the 5m route end to end: owner acquisition requests interval 5m over a bounded window, the provider emits exact 300000ms periods labelled five_minutes with the incomplete current interval PARTIAL, the observation validates, the context binds the component, the packet carries it, and the broker satisfies the exact request; entitlement denied -> ACCESS_BLOCKED; delayed history -> stale / unmatched, never a real zero', async () => {
  const requests = []; const dir = tmp('whale-'); const now = Math.floor(T0 / 300_000) * 300_000 + 120_000; // 2 minutes into the current 5m interval
  const fetchImpl = async (url, init) => { const body = JSON.parse(init.body); requests.push(body); if (/whale_transaction_count_1m/.test(body.variables.metric)) return json({ errors: [{ message: 'Metric restricted for your plan' }] }); if (/whale_transaction_volume_1m/.test(body.variables.metric)) return json(series5m(4, now - 3 * 3_600_000)); return json(series5m(4, now)); };
  const own = createResearchOwner({ policy: santimentPolicy(), subjects: btcOnly(), env: { SANTIMENT_API_KEY: 'offline-fixture' }, clock: () => now, researchRoot: dir, fetchImpl });
  try {
    const r = await own.acquire('NETWORK_ACTIVITY', 'BTC', { metricIds: [...WHALE_METRIC_IDS, 'active_addresses'] });
    const whale = requests.filter((b) => /whale/.test(b.variables.metric)); assert.equal(whale.length, 4, 'all four routes are requested'); assert.ok(whale.every((b) => b.variables.interval === '5m'), 'never aliased to a day / hour'); assert.ok(whale.every((b) => now - Date.parse(b.variables.from) <= 6 * 3_600_000 + 1000), 'bounded lookback'); const aa = requests.find((b) => b.variables.metric === 'daily_active_addresses'); assert.equal(aa.variables.interval, '1d', 'the old daily route survives');
    const obs = r.observations.filter((o) => o.kind === 'ONCHAIN_METRIC'); const c100 = obs.filter((o) => o.payload.metricId === 'whale_transaction_count_100k_usd_to_inf'); assert.equal(c100.length, 4); for (const o of c100) { assert.equal(observationError(o), null); assert.equal(o.periodEndTs - o.periodStartTs, 300_000); assert.equal(o.payload.window, 'five_minutes'); assert.equal(o.payload.unit, 'COUNT'); assert.equal(o.payload.entitySet, null); }
    const current = c100.find((o) => o.periodEndTs > now); assert.ok(current); assert.equal(current.quality.state, 'PARTIAL'); assert.ok(current.quality.reasonCodes.includes('UNCOMMITTED_BAR'), 'the incomplete current interval is flagged'); const v100 = obs.filter((o) => o.payload.metricId === 'whale_transaction_volume_100k_usd_to_inf'); assert.equal(v100[0].payload.unit, 'USD');
    const denied = r.coverage.find((c) => c.state === 'ACCESS_BLOCKED'); assert.ok(denied, 'entitlement denied is ACCESS_BLOCKED coverage, not a zero'); assert.equal(obs.filter((o) => o.payload.metricId === 'whale_transaction_count_1m_usd_to_inf').length, 0);
    const ctx = buildContext({ canonicalCoin: 'BTC', asOfTs: now, observations: r.observations, coverage: r.coverage, captureRef: SEALED_REF }); const comps = ctx.context.families.NETWORK_ACTIVITY.components; const comp = comps.find((c) => c.metricId === 'whale_transaction_count_100k_usd_to_inf'); assert.ok(comp, 'context component bound'); assert.equal(comp.value.unit, 'COUNT'); assert.equal(comp.value.window, 'five_minutes'); assert.ok(comps.some((c) => c.metricId === 'whale_transaction_volume_100k_usd_to_inf'));
    const packet = buildResearchEvidenceV2({ marketContext: ctx.context, socialProjection: null, asOfTs: now, trigger: { kind: 'MARKET_RESEARCH', sourceEventId: null, observedTs: null }, mode: 'LIVE_OBSERVATION', entrances: ['MARKET_LED'], detailRequests: [{ family: 'NETWORK_ACTIVITY', metricId: 'whale_transaction_count_100k_usd_to_inf' }] }); assert.equal(packet.ok, true, JSON.stringify(packet.reasons ?? packet.reason)); const net = packet.packet.evidence.filter((e) => e.kind === 'MARKET_NETWORK_CONTEXT'); assert.ok(net.some((e) => e.state === 'KNOWN' && e.value.fields.metrics.some((m) => m.registeredMetric === 'whale_transaction_count_100k_usd_to_inf' && m.unit === 'COUNT' && m.periodEndTs <= now)), 'the packet carries the whale metric with its unit, from a COMPLETE 5m period, never the open interval');
    const broker = createBroker({ owner: own, policy: santimentPolicy(), clock: () => now }); const sat = await broker.resolve(req(['whale_transaction_count_100k_usd_to_inf']), { ...OPTS, asOfTs: now, deadlineTs: now + 60_000 }); assert.equal(sat.state, 'SATISFIED', JSON.stringify(sat.metrics)); assert.equal(sat.metrics.whale_transaction_count_100k_usd_to_inf.state, 'SATISFIED'); assert.deepEqual(sat.sourceIds, ['SANTIMENT']);
    const stale = await broker.resolve(req(['whale_transaction_volume_1m_usd_to_inf'], { requestKind: 'REFRESH', requestedMaxAgeMs: 900_000 }), { ...OPTS, asOfTs: now, deadlineTs: now + 60_000 }); assert.notEqual(stale.state, 'SATISFIED', 'three-hour-old history is not fresh 5m data'); const deniedReq = await broker.resolve(req(['whale_transaction_count_1m_usd_to_inf']), { ...OPTS, asOfTs: now, deadlineTs: now + 60_000 }); assert.notEqual(deniedReq.state, 'SATISFIED'); assert.equal(deniedReq.metrics.whale_transaction_count_1m_usd_to_inf.matched, 0, 'no invented whale identity or value');
  } finally { await own.stop({ seal: false }); rmSync(dir, { recursive: true, force: true }); }
  const client = createSantimentClient({ transport: createHttpTransport({ fetchImpl: async () => json(series5m()), clock: () => T0 }), clock: () => T0, log: () => {}, credential: 'offline-fixture' }); assert.equal((await client.series({ slug: 'bitcoin', canonicalCoin: 'BTC', metricId: 'active_addresses', fromTs: T0 - 3_600_000, toTs: T0, interval: '5m' })).ok, false, 'existing metrics do not accept 5m'); assert.equal((await client.series({ slug: 'bitcoin', canonicalCoin: 'BTC', metricId: 'whale_transaction_count_100k_usd_to_inf', fromTs: T0 - 3_600_000, toTs: T0, interval: '1m' })).ok, false, 'an undocumented interval refuses');
});
