// H06–H13 (holdout truth closeout HR01–HR10): the authoritative experiment path cannot qualify a one-shot holdout with a report
// that existed before the opening; opening and evaluation are distinct durable steps; selection is frozen under a declared
// temporal wall; development / validation looks are stage-scoped evidence; a report is admitted only through ONE closed,
// re-derived identity validator (complete, bound to experiment / policy / code / strategy / source / seed / bundle / arms);
// empty / pending / censored / unscorable holdouts consume the one shot but never qualify; the chain is bound to the exact
// release candidate; catalyst / source dependencies constrain episode eligibility whole with preserved arrival clocks; experiment
// records are semantically closed; every experiment-store mutator proves owner intent. Each test's FIRST assertion is the
// semantic loophole itself, so on the reviewed baseline it fails for that reason (logs kept outside the tree).
import test from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import { mkdtempSync, rmSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { Readable } from 'node:stream';

const TEST_DATA = mkdtempSync(path.join(tmpdir(), 'cobra-judge-truth-')); process.env.COBRA_DATA_DIR = TEST_DATA; delete process.env.DATABASE_URL;
const X = await import('../judge/experiment.js'); const { declareExperiment, assignGroups, groupsFromReport, evaluateSplit, persistDeclaration, persistEvaluation, lockCandidate, openHoldout, evaluateHoldout, holdoutChain, loadExperiment } = X;
const ST = await import('../judge/experiment-store.js'); const { createMemoryExperimentStore } = ST;
const R = await import('../judge/experiment-replay.js'); const { replayExperiment } = R; const reseal = (r) => (typeof R.reportDigestOf === 'function' ? { ...r, reportDigest: R.reportDigestOf(r) } : r);
const { releaseBlockers, prepareRelease, manifestSemanticsError } = await import('../judge/arming.js'); const { recordExperimentFixture, rewriteBundle } = await import('./helpers/experiment-fixture.js'); const { catalystPacket, analysisFor, verifiedCase } = await import('./helpers/case-fixture.js');
const { fakeClock, T0, SAMPLE_LIMITS } = await import('./helpers/judge.js'); const { loadJudgePolicy } = await import('../judge/policy.js'); const { digestOf } = await import('../execution/contract.js'); const { runCli } = await import('../bin/judge.js'); const { ownerAuditFile } = await import('../judge/owner.js'); const M = await import('../execution/money.js');
const DAY = 86_400_000; const HOUR = 3_600_000; const CODE = 'c'.repeat(64); const ACCT = 'fixture-observe'; const PW = 'truth-test-owner-password-2026';
const isCode = (code) => (e) => { assert.equal(e.code, code, `${e.code}: ${e.message}`); return true; }; const reasonOf = (e) => (e.reasons ?? [])[0] ?? e.message;
let FIX; let P; let FULL; let ENTRY; // one forward fixture recording, one full replay, the reference entry decision
const rep = (over = {}) => replayExperiment({ bundleDir: FIX.dir, policyFile: FIX.policyFile, arms: ['REF_COMBINED', 'CASH'], experimentId: 'exp-truth', codeDigest: CODE, ...over });
// a prospective declaration around the fixture: the entry (~T0 + 24 min) lands in the window named by `entryIn`
const decl = ({ experimentId = 'exp-truth', entryIn = 'HOLDOUT', selectionGraceMs = DAY, maxOutcomeMs = 4 * HOUR, publicationFloorMs = 0, embargoMs = 0, codeDigest = CODE, arms = ['REF_COMBINED', 'CASH'], nowTs = T0 - 1, seed = null, extra = {} } = {}) => {
  const durationMs = entryIn === 'HOLDOUT' ? 30 * 60_000 : entryIn === 'DEVELOPMENT' ? 60 * 60_000 : 20 * 60_000; // holdout [22.5, 30) / development [0, 30) / none (entry after the end)
  return declareExperiment({ experimentId, policyDigest: P.digest, codeDigest, strategyVersion: P.policy.strategyVersion, arms, seed: seed ?? P.policy.evaluation.seed, sourceBinding: { sourcePrefix: `journal:${ACCT}`, accountId: ACCT }, startTs: T0, durationMs, fractions: { developmentFraction: 0.5, validationFraction: 0.25 }, embargoMs, horizons: { lookbackMs: 0, decisionMs: 0, maxOutcomeMs, publicationFloorMs }, selectionGraceMs, nowTs, ...extra });
};
const stage = (d, s) => ({ stage: s, boundaryTs: s === 'DEVELOPMENT' ? d.windows.developmentEndTs : d.windows.validationEndTs });
const after = (d) => d.windows.endTs + d.horizons.maxOutcomeMs + 1;
// the corrected prospective walk up to the opening: dev look, validation look, lock inside the declared grace, opening after the window
async function walkToOpening(st, d, { runId = 'run-1', arm = 'REF_COMBINED' } = {}) {
  await persistDeclaration(st, d); const dev = await rep({ experimentId: d.experimentId, arms: d.binding.arms, evidenceScope: stage(d, 'DEVELOPMENT') }); const val = await rep({ experimentId: d.experimentId, arms: d.binding.arms, evidenceScope: stage(d, 'VALIDATION') });
  const t1 = d.windows.developmentEndTs + 1; const a1 = assignGroups(d, groupsFromReport(dev, d), { nowTs: t1 }); await persistEvaluation(st, d.experimentId, evaluateSplit({ declaration: d, assignment: a1, report: dev, split: 'DEVELOPMENT', nowTs: t1 }));
  const t2 = d.windows.validationEndTs + 1; const a2 = assignGroups(d, groupsFromReport(val, d), { nowTs: t2 }); await persistEvaluation(st, d.experimentId, evaluateSplit({ declaration: d, assignment: a2, report: val, split: 'VALIDATION', nowTs: t2 + 1 }));
  const lock = await lockCandidate(st, { experimentId: d.experimentId, arm, nowTs: t2 + 2 }); const opening = await openHoldout(st, { experimentId: d.experimentId, runId, nowTs: after(d) }); return { dev, val, lock, opening: opening.opening };
}
test.before(async () => { FIX = await recordExperimentFixture(path.join(TEST_DATA, 'fixture', 'bundle'), { accountId: ACCT }); P = loadJudgePolicy(FIX.policyFile); FULL = await rep(); ENTRY = FULL.arms.REF_COMBINED.decisions.find((x) => x.status === 'ENTRY_RESERVED'); assert.ok(ENTRY, 'the fixture enters'); });
test.after(() => rmSync(TEST_DATA, { recursive: true, force: true }));

test('H06 / HR01. the one-shot holdout cannot be qualified by a report that existed before the opening: a full report generated before the opening is refused by the holdout evaluation; open-holdout takes NO report and appends only HOLDOUT_OPENED (the chain stays HOLDOUT_NOT_EVALUATED); only a later evaluation bound to the opening digest consumes the one shot, once, under the opening run id', async () => {
  const st = createMemoryExperimentStore(); const d = decl(); const { opening } = await walkToOpening(st, d); const groups = groupsFromReport(FULL, d);
  await assert.rejects(evaluateHoldout(st, { experimentId: d.experimentId, runId: 'run-1', report: FULL, groups, nowTs: after(d) }), (e) => { assert.equal(e.code, 'REPORT_INADMISSIBLE', e.message); assert.equal(reasonOf(e), 'HOLDOUT_OPENING_UNBOUND'); return true; }, 'HR01 witness: the pre-opening full report qualified the holdout on the baseline');
  const chain0 = await holdoutChain(st, d.experimentId); assert.equal(chain0.ok, false); assert.deepEqual(chain0.blockers, ['HOLDOUT_NOT_EVALUATED'], 'opening alone leaves the chain blocked'); assert.equal((await loadExperiment(st, d.experimentId)).records.at(-1).kind, 'HOLDOUT_OPENED');
  const bound = await rep({ experimentId: d.experimentId, holdoutOpening: opening.digest }); assert.equal(bound.holdoutOpening, opening.digest); assert.notEqual(bound.reportDigest, FULL.reportDigest, 'the opening digest is part of the report identity');
  await assert.rejects(evaluateHoldout(st, { experimentId: d.experimentId, runId: 'run-2', report: bound, groups: groupsFromReport(bound, d), nowTs: after(d) }), isCode('RUN_ID_MISMATCH')); const ev = await evaluateHoldout(st, { experimentId: d.experimentId, runId: 'run-1', report: bound, groups: groupsFromReport(bound, d), nowTs: after(d) }); assert.equal(ev.kind, 'HOLDOUT_EVALUATED'); assert.equal(ev.record.reportDigest, bound.reportDigest); assert.equal(ev.record.openingDigest, opening.digest);
  await assert.rejects(evaluateHoldout(st, { experimentId: d.experimentId, runId: 'run-1', report: bound, groups: groupsFromReport(bound, d), nowTs: after(d) }), isCode('HOLDOUT_CONSUMED'), 'one time forever'); const chain = await holdoutChain(st, d.experimentId); assert.equal(chain.ok, true); assert.equal(chain.consumed, true); assert.equal(chain.qualified, true, JSON.stringify(chain.qualificationBlockers));
  // the real CLI: open-holdout has no --report and evaluates nothing; evaluate-holdout is the separate owner-authenticated door
  const cliStore = createMemoryExperimentStore(); const d2 = decl({ experimentId: 'exp-cli' }); await walkToOpening(cliStore, d2); let wall = after(d2); const reportFile = path.join(TEST_DATA, 'h06-full.json'); writeFileSync(reportFile, JSON.stringify({ ok: true, command: 'replay-experiment', ...FULL }));
  const run = async (args, stdinText = null) => { const out = []; const err = []; const code = await runCli(args, { env: { SERPENT_CONTROL_PASSWORD: PW }, stdin: stdinText === null ? null : Readable.from([stdinText]), stdout: (s) => out.push(s), stderr: (s) => err.push(s), clock: () => wall, cwd: process.cwd(), experimentStore: cliStore }); return { code, out: out.join(''), err: err.join(''), json: () => JSON.parse(out.join('')) }; };
  const withReport = await run(['open-holdout', '--policy', FIX.policyFile, '--experiment', 'exp-cli', '--run-id', 'run-x', '--report', reportFile, '--owner-stdin', 'true'], `${PW}\n`); assert.notEqual(withReport.code, 0, 'HR01 witness: open-holdout consumed a report on the baseline'); assert.equal((await loadExperiment(cliStore, 'exp-cli')).records.at(-1).kind, 'HOLDOUT_OPENED');
});

test('H07 / HR02 + HR05. selection has a declared temporal wall and stage-scoped evidence: a lock after the declared selection deadline is refused; a development / validation look computed from a FULL report (evidence beyond the stage boundary) is refused; a report stopped at an arbitrary sequence is not a stage artifact; the honest prospective walk passes and the stage artifact equals the replay of the exact admissible prefix, deterministically', async () => {
  const late = decl({ experimentId: 'exp-late', selectionGraceMs: 0 }); const st = createMemoryExperimentStore(); await persistDeclaration(st, late);
  const dev = await rep({ experimentId: 'exp-late', evidenceScope: stage(late, 'DEVELOPMENT') }); const val = await rep({ experimentId: 'exp-late', evidenceScope: stage(late, 'VALIDATION') }); const t = late.windows.validationEndTs;
  await persistEvaluation(st, 'exp-late', evaluateSplit({ declaration: late, assignment: assignGroups(late, groupsFromReport(dev, late), { nowTs: t }), report: dev, split: 'DEVELOPMENT', nowTs: t })); await persistEvaluation(st, 'exp-late', evaluateSplit({ declaration: late, assignment: assignGroups(late, groupsFromReport(val, late), { nowTs: t }), report: val, split: 'VALIDATION', nowTs: t }));
  await assert.rejects(lockCandidate(st, { experimentId: 'exp-late', arm: 'REF_COMBINED', nowTs: late.windows.validationEndTs + 1 }), isCode('SELECTION_DEADLINE_PASSED'), 'HR02 witness: a lock after the holdout evidence boundary succeeded on the baseline'); assert.equal(late.windows.selectionDeadlineTs, late.windows.validationEndTs);
  const d = decl({ experimentId: 'exp-scope' }); const a = assignGroups(d, groupsFromReport(FULL, d), { nowTs: after(d) });
  assert.throws(() => evaluateSplit({ declaration: d, assignment: a, report: FULL, split: 'DEVELOPMENT', nowTs: after(d) }), (e) => { assert.equal(e.code, 'REPORT_INADMISSIBLE'); assert.equal(reasonOf(e), 'EVIDENCE_SCOPE_NOT_DEVELOPMENT'); return true; }, 'HR05 witness: a full report reaching into the holdout was accepted for a development look');
  assert.throws(() => evaluateSplit({ declaration: d, assignment: a, report: FULL, split: 'VALIDATION', nowTs: after(d) }), (e) => reasonOf(e) === 'EVIDENCE_SCOPE_NOT_VALIDATION');
  const rows = [...(await import('../judge/experiment-bundle.js')).readBundle(FIX.dir, { validate: false })]; const mid = rows.find((x) => x.receiptTs >= d.windows.developmentEndTs).seq - 1; const stopped = await rep({ experimentId: 'exp-scope', stopAtSeq: mid }); assert.equal(stopped.outcome, 'STOPPED_AT_SEQ');
  assert.throws(() => evaluateSplit({ declaration: d, assignment: a, report: stopped, split: 'DEVELOPMENT', nowTs: after(d) }), (e) => reasonOf(e) === 'REPORT_NOT_COMPLETE', 'HR04 / HR05: an arbitrary stopped prefix is not the declared stage artifact');
  const devA = await rep({ experimentId: 'exp-scope', evidenceScope: stage(d, 'DEVELOPMENT') }); const devB = await rep({ experimentId: 'exp-scope', evidenceScope: stage(d, 'DEVELOPMENT') }); assert.equal(devA.outcome, 'COMPLETE_THROUGH_SCOPE'); assert.equal(devA.evidenceScope.stage, 'DEVELOPMENT'); assert.equal(devA.evidenceScope.boundaryTs, d.windows.developmentEndTs); assert.ok(devA.evidenceScope.lastAppliedReceiptTs < d.windows.developmentEndTs, 'no record at or after the boundary was consumed'); assert.ok(devA.evidenceScope.recordsBeyond > 0);
  assert.equal(devA.reportDigest, devB.reportDigest, 'same bytes + same boundary + same bindings -> same report'); for (const arm of ['REF_COMBINED', 'CASH']) assert.equal(devA.arms[arm].headDigest, devB.arms[arm].headDigest);
  const prefix = await rep({ experimentId: 'exp-scope', stopAtSeq: mid }); assert.equal(prefix.observation.arms.REF_COMBINED.headDigest, devA.arms.REF_COMBINED.headDigest, 'the stage artifact IS the replay of the exact admissible prefix'); assert.equal(prefix.observation.arms.REF_COMBINED.depletionDigest, devA.arms.REF_COMBINED.depletionDigest);
  const ok = createMemoryExperimentStore(); const w = await walkToOpening(ok, decl({ experimentId: 'exp-ok' })); assert.equal(w.lock.record.developmentEvaluation.reportDigest, w.dev.reportDigest); assert.equal(w.lock.record.validationEvaluation.reportDigest, w.val.reportDigest); assert.ok(w.lock.record.lockedTs <= (await loadExperiment(ok, 'exp-ok')).declaration.windows.selectionDeadlineTs);
});

test('H08 / HR03 + HR04. ONE closed re-derived report validator admits a report only when it is complete and bound: experiment id, policy, code (KNOWN), strategy, seed, source prefix, bundle binding (experiment / policy / code / strategy / source / seed), engine, bundle and tie-order versions, every funded arm binding and re-derived account id, declared-arm membership, and the report digest itself; STOPPED_AT_SEQ / INCOMPLETE / dirty-tree reports never qualify', async () => {
  const d = decl({ experimentId: 'exp-bind' }); const a = assignGroups(d, groupsFromReport(FULL, d), { nowTs: after(d) }); const base = await rep({ experimentId: 'exp-bind', holdoutOpening: null });
  const refuse = (mutate, reason) => { const m = reseal(mutate(structuredClone(base))); assert.throws(() => evaluateSplit({ declaration: d, assignment: a, report: m, split: 'HOLDOUT', nowTs: after(d) }), (e) => { assert.equal(e.code, 'REPORT_INADMISSIBLE', `${reason}: ${e.message}`); assert.ok((e.reasons ?? []).includes(reason), `${reason} expected in ${JSON.stringify(e.reasons)}`); return true; }); };
  refuse((r) => { r.codeDigest = 'd'.repeat(64); return r; }, 'CODE_DIGEST_MISMATCH');
  refuse((r) => { r.experimentId = 'exp-other'; return r; }, 'EXPERIMENT_ID_MISMATCH'); refuse((r) => { r.strategyVersion = 'other-strategy'; return r; }, 'STRATEGY_VERSION_MISMATCH'); refuse((r) => { r.sourcePrefix = 'journal:other'; return r; }, 'SOURCE_PREFIX_MISMATCH'); refuse((r) => { r.seed = 'other-seed'; return r; }, 'SEED_MISMATCH'); refuse((r) => { r.policyDigest = 'e'.repeat(64); return r; }, 'POLICY_DIGEST_MISMATCH');
  for (const k of ['experimentId', 'policyDigest', 'codeDigest', 'strategyVersion', 'sourcePrefix', 'seed']) refuse((r) => { r.bundleBinding[k] = `${r.bundleBinding[k]}x`; return r; }, `BUNDLE_BINDING_${k.toUpperCase()}_MISMATCH`);
  refuse((r) => { r.engine = 'judge-experiment-replay-0'; return r; }, 'ENGINE_VERSION_MISMATCH'); refuse((r) => { r.bundleVersion = 'judge-experiment-bundle-0'; return r; }, 'BUNDLE_VERSION_MISMATCH'); refuse((r) => { r.tieOrderVersion = 'judge-replay-tie-order-0'; return r; }, 'TIE_ORDER_VERSION_MISMATCH');
  refuse((r) => { r.arms.REF_COMBINED.binding.seed = 'other'; return r; }, 'ARM_BINDING_MISMATCH'); refuse((r) => { r.arms.REF_COMBINED.accountId = 'replay-0000000000000000-REF_COMBINED'; return r; }, 'ARM_ACCOUNT_ID_MISMATCH'); refuse((r) => { r.arms.REF_COMBINED = { ...r.arms.CASH, arm: 'REF_COMBINED' }; return r; }, 'ARM_BINDING_MISMATCH'); refuse((r) => { delete r.arms.CASH; return r; }, 'DECLARED_ARM_MISSING');
  refuse((r) => { r.arms.REF_COMBINED.closedNetPnl = '999'; return r; }, 'ARM_LEDGER_INCONSISTENT', /* a resealed report with an edited figure is caught by what the validator can re-derive from the report's own rows (the closed net IS the sum of its listed closes); the unedited seal catches it first: */); assert.throws(() => evaluateSplit({ declaration: d, assignment: a, report: { ...base, arms: { ...base.arms, REF_COMBINED: { ...base.arms.REF_COMBINED, closedNetPnl: '999' } } }, split: 'HOLDOUT', nowTs: after(d) }), (e) => (e.reasons ?? []).includes('REPORT_DIGEST_MISMATCH'), 'an edited figure under the old digest is refused');
  refuse((r) => { r.outcome = 'INCOMPLETE'; r.ok = false; return r; }, 'REPORT_NOT_COMPLETE'); refuse((r) => { r.outcome = 'STOPPED_AT_SEQ'; r.stoppedAtSeq = 5; return r; }, 'REPORT_NOT_COMPLETE'); refuse((r) => { r.codeIdentity = 'UNKNOWN_DIRTY_TREE'; r.codeDigest = null; return r; }, 'CODE_IDENTITY_UNKNOWN');
  const dirty = await rep({ experimentId: 'exp-dirty', codeDigest: null }); assert.equal(dirty.codeIdentity, 'UNKNOWN_DIRTY_TREE'); const dd = decl({ experimentId: 'exp-dirty', codeDigest: null }); assert.equal(dd.qualifiable, false, 'a declaration without code identity is research-visible but can never qualify'); assert.throws(() => evaluateSplit({ declaration: d, assignment: a, report: dirty, split: 'HOLDOUT', nowTs: after(d) }), (e) => (e.reasons ?? []).includes('EXPERIMENT_ID_MISMATCH') || (e.reasons ?? []).includes('CODE_IDENTITY_UNKNOWN'));
  const stopped = await rep({ experimentId: 'exp-bind', stopAtSeq: 200 }); for (const split of ['DEVELOPMENT', 'VALIDATION', 'HOLDOUT']) assert.throws(() => evaluateSplit({ declaration: d, assignment: a, report: stopped, split, nowTs: after(d) }), (e) => (e.reasons ?? []).includes('REPORT_NOT_COMPLETE'), `${split}: STOPPED_AT_SEQ is restart research, never qualification evidence`);
  const v = X.admissibleReport({ declaration: d, report: base, split: 'HOLDOUT' }); assert.equal(v.ok, true, JSON.stringify(v.reasons)); assert.ok(v.checked.length >= 20, 'the validator names every identity it checked'); assert.equal(v.checked.includes('REPORT_DIGEST'), true);
});

test('H09 / HR06. a consumed holdout that is empty, pending, censored or unscorable never qualifies: the one shot is durably consumed (a second look is refused) while the chain reports CONSUMED_BUT_UNQUALIFIED with named blockers; the release stays BLOCKED; only a SCORED locked arm with at least one eligible closed outcome, no pending and no censored holdout groups passes this layer', async () => {
  const qualify = async (id, d, { arm = 'REF_COMBINED', fixture = FIX, nowTs = null } = {}) => { const st = createMemoryExperimentStore(); const w = await walkToOpening(st, d, { arm }); const t = nowTs ?? after(d); const bound = await replayExperiment({ bundleDir: fixture.dir, policyFile: fixture.policyFile, arms: ['REF_COMBINED', 'CASH', 'D2_FLOW_EVENT_RESPONSE'], experimentId: id, codeDigest: CODE, holdoutOpening: w.opening.digest }); await evaluateHoldout(st, { experimentId: id, runId: 'run-1', report: bound, groups: groupsFromReport(bound, d), nowTs: t }); const chain = await holdoutChain(st, id); await assert.rejects(evaluateHoldout(st, { experimentId: id, runId: 'run-1', report: bound, groups: groupsFromReport(bound, d), nowTs: t }), isCode('HOLDOUT_CONSUMED')); return { st, chain, record: (await loadExperiment(st, id)).records.at(-1).record }; };
  const empty = await qualify('exp-empty', decl({ experimentId: 'exp-empty', entryIn: 'NONE' })); assert.equal(empty.chain.consumed, true); assert.equal(empty.chain.qualified, false, 'HR06 witness: an empty holdout qualified on the baseline'); assert.deepEqual(empty.chain.qualificationBlockers, ['HOLDOUT_EMPTY']); assert.equal(empty.record.qualification.status, 'CONSUMED_BUT_UNQUALIFIED'); assert.equal(empty.chain.ok, true, 'the historical fact of the consumption is preserved');
  const cand = { codeTreeDigest: CODE, policyDigest: P.digest, strategyVersion: P.policy.strategyVersion, evaluation: { paperAccountId: ACCT, forwardClosedTrades: 40, holdoutUntouched: true, netPnl: '12.5', drawdown: 0.03, feesAccounted: true, openPositions: 0, evaluationDigest: 'e'.repeat(64), source: 'FORWARD_PAPER' }, tests: { criticalSuitesPassing: true, evidenceFile: 'x' }, sourcePrefixes: [`journal:${ACCT}:0123456789abcdef`], acceptance: { independentReview: 'PASSED' }, proposedLimits: SAMPLE_LIMITS };
  assert.deepEqual(releaseBlockers({ ...cand, holdoutChain: empty.chain }), ['HOLDOUT_UNQUALIFIED:HOLDOUT_EMPTY']);
  // a PENDING holdout group cannot reach the look through the lifecycle (the opening waits for the window + outcome horizon, and a floor that reaches past the end PURGES the group); the qualification law still names it, and the floor case consumes without qualifying
  assert.deepEqual(X.qualificationOf({ qualifiable: true, armEval: { outcome: 'SCORED', closed: 0, censored: 0 }, holdoutGroups: 0, pending: 2 }).blockers, ['HOLDOUT_PENDING']); const floor = await qualify('exp-floor', decl({ experimentId: 'exp-floor', publicationFloorMs: 2 * DAY })); assert.equal(floor.chain.qualified, false); assert.deepEqual(floor.chain.qualificationBlockers, ['HOLDOUT_EMPTY']); assert.ok(floor.record.purged >= 1); assert.equal(floor.record.pending, 0);
  const open = await recordExperimentFixture(path.join(TEST_DATA, 'open', 'bundle'), { scenario: 'OPEN_AT_END', accountId: ACCT, policyFile: FIX.policyFile }); const censored = await qualify('exp-censored', decl({ experimentId: 'exp-censored', maxOutcomeMs: 4 * 60_000 }), { fixture: open }); /* an outcome horizon that ends inside the window: the position is still OPEN when the stream ends, so it is CENSORED, never assumed closed */ assert.equal(censored.chain.qualified, false); assert.deepEqual(censored.chain.qualificationBlockers, ['HOLDOUT_CENSORED']); assert.equal(censored.record.censored, 1); assert.equal(censored.record.closed, 0);
  const unscorable = await qualify('exp-unscorable', decl({ experimentId: 'exp-unscorable', arms: ['REF_COMBINED', 'CASH', 'D2_FLOW_EVENT_RESPONSE'] }), { arm: 'D2_FLOW_EVENT_RESPONSE' }); assert.deepEqual(unscorable.chain.qualificationBlockers, ['HOLDOUT_UNSCORABLE']);
  const cash = await qualify('exp-cash', decl({ experimentId: 'exp-cash' }), { arm: 'CASH' }); assert.deepEqual(cash.chain.qualificationBlockers, ['HOLDOUT_NO_CLOSED_OUTCOME'], 'a no-trade arm manufactures no evidence');
  const good = await qualify('exp-good', decl({ experimentId: 'exp-good' })); assert.equal(good.chain.qualified, true, JSON.stringify(good.chain.qualificationBlockers)); assert.equal(good.record.qualification.status, 'QUALIFIED'); assert.equal(good.record.closed, 1); assert.equal(good.record.censored, 0); assert.ok(M.isPositive(good.record.netPnl)); assert.deepEqual(releaseBlockers({ ...cand, holdoutChain: good.chain }), []);
});

test('H10 / HR07. the holdout chain is bound to the exact release candidate: a valid qualified chain used with another code tree, another policy, another strategy, another source account or another locked arm is blocked, and rehashing the manifest never cures the mismatch; verify --manifest --experiment still compares with the store', async () => {
  const st = createMemoryExperimentStore(); const d = decl({ experimentId: 'exp-rel' }); const w = await walkToOpening(st, d); const bound = await rep({ experimentId: 'exp-rel', holdoutOpening: w.opening.digest }); await evaluateHoldout(st, { experimentId: 'exp-rel', runId: 'run-1', report: bound, groups: groupsFromReport(bound, d), nowTs: after(d) }); const chain = await holdoutChain(st, 'exp-rel'); assert.equal(chain.qualified, true);
  const cand = { codeTreeDigest: CODE, policyDigest: P.digest, strategyVersion: P.policy.strategyVersion, evaluation: { paperAccountId: ACCT, forwardClosedTrades: 40, holdoutUntouched: true, netPnl: '12.5', drawdown: 0.03, feesAccounted: true, openPositions: 0, evaluationDigest: 'e'.repeat(64), source: 'FORWARD_PAPER' }, tests: { criticalSuitesPassing: true, evidenceFile: 'x' }, sourcePrefixes: [`journal:${ACCT}:0123456789abcdef`], acceptance: { independentReview: 'PASSED' }, proposedLimits: SAMPLE_LIMITS, holdoutChain: chain };
  assert.deepEqual(releaseBlockers(cand), []); assert.deepEqual(releaseBlockers({ ...cand, codeTreeDigest: 'd'.repeat(64) }), ['HOLDOUT_CHAIN_CODE_MISMATCH'], 'HR07 witness: a chain from another code tree qualified on the baseline');
  assert.deepEqual(releaseBlockers({ ...cand, policyDigest: 'e'.repeat(64) }), ['HOLDOUT_CHAIN_POLICY_MISMATCH']); assert.deepEqual(releaseBlockers({ ...cand, strategyVersion: 'other' }), ['HOLDOUT_CHAIN_STRATEGY_MISMATCH']); assert.deepEqual(releaseBlockers({ ...cand, evaluation: { ...cand.evaluation, paperAccountId: 'other-account' } }), ['HOLDOUT_CHAIN_SOURCE_MISMATCH']);
  assert.deepEqual(releaseBlockers({ ...cand, holdoutChain: { ...chain, binding: { ...chain.binding, arm: 'CASH' } } }), ['HOLDOUT_CHAIN_INVALID'], 'a chain whose binding was edited no longer re-derives'); assert.deepEqual(releaseBlockers({ ...cand, holdoutChain: { ...chain, binding: { ...chain.binding, experimentId: 'exp-other' } } }), ['HOLDOUT_CHAIN_INVALID']);
  const m = prepareRelease({ ...cand, policy: P.policy, coverage: { dataFamilies: ['BOOK'], latencySamples: 10 }, acceptance: { independentReview: 'PASSED', reviewer: 'r' }, nowTs: T0 }); assert.equal(m.state, 'CANDIDATE', m.blockers.join(',')); assert.equal(manifestSemanticsError(m), null);
  const moved = { ...m, code: { ...m.code, treeDigest: 'd'.repeat(64) } }; moved.manifestDigest = digestOf({ ...moved, manifestDigest: null }); assert.match(manifestSemanticsError(moved) ?? '', /BLOCKED|blockers/i, 'rehashing does not cure a moved code identity'); const other = { ...m, policy: { ...m.policy, policyDigest: 'e'.repeat(64) } }; other.manifestDigest = digestOf({ ...other, manifestDigest: null }); assert.ok(manifestSemanticsError(other));
});

test('H11 / HR08. catalyst / source dependencies constrain episode eligibility whole: two episodes sharing one canonical catalyst (or one canonical source) across a cutoff are purged together, never one in development and one in holdout; an episode without dependencies keeps its deterministic EPISODE-only behaviour; removing the canonical identity changes the grouping in a named way and never invents a source; real reports carry the canonical source of a consumed case; preserved arrival clocks surface late arrivals through the real CLI', async () => {
  const d = decl({ experimentId: 'exp-dep', entryIn: 'HOLDOUT' }); const w = d.windows; const dec = (episodeId, ts, over = {}) => ({ decisionId: `dec-${episodeId}`, episodeId, setupId: 'RANGE_IGNITION', status: 'ENTRY_RESERVED', reasonCodes: [], decisionKnownAtTs: ts, triggerTs: ts, inputMode: 'CASE_ENRICHED', caseRefs: { packetId: 'pk-1', analysisId: 'an-1', caseId: 'case-1', caseCompletionTs: ts - 60_000, caseReceiptTs: ts - 30_000, direction: 'UPWARD_PRESSURE', provenance: 'LIVE_MODEL', eventId: 'clm-shared', eventTaxonomy: 'LISTING_OR_INTEGRATION' }, dependencies: { caseId: 'case-1', catalystId: 'clm-shared', sourceId: 'src-shared' }, ...over });
  const pos = (episodeId, ts) => ({ positionId: `pos-${episodeId}`, decisionId: `dec-${episodeId}`, assetId: 'BTC', pair: 'XBT/USD', state: 'FLAT', realizedPnl: '1', firstFillTs: ts + 500, lastEconomicTs: ts + 60_000, exitReason: 'PLANNED_TARGET' });
  const DEP = await rep({ experimentId: 'exp-dep' }); const report = (decisions) => { const positions = decisions.map((x) => pos(x.episodeId, x.triggerTs)); return reseal({ ...DEP, arms: { ...DEP.arms, REF_COMBINED: { ...DEP.arms.REF_COMBINED, decisions, positions, closedNetPnl: M.sum(positions.map((p) => p.realizedPnl)) } } }); };
  const before = w.developmentEndTs - 10 * 60_000; const beyond = w.validationEndTs + 60_000; // one side of the development cutoff, one inside the holdout
  const shared = assignGroups(d, groupsFromReport(report([dec('ep-a', before), dec('ep-b', beyond)]), d), { nowTs: after(d) }); assert.equal(shared.assignment['ep-a'], 'PURGED', 'HR08 witness: two episodes sharing one catalyst across the cutoff were split on the baseline'); assert.equal(shared.assignment['ep-b'], 'PURGED'); assert.ok(shared.purged.every((p) => p.reasons.some((r) => r.startsWith('DEPENDENCY_'))), JSON.stringify(shared.purged)); assert.equal(shared.components.length, 1); assert.deepEqual(shared.components[0].members.sort(), ['ep-a', 'ep-b']); assert.deepEqual(shared.components[0].dependencies.catalysts, ['clm-shared']);
  const sourceOnly = assignGroups(d, groupsFromReport(report([dec('ep-a', before, { caseRefs: { ...dec('x', before).caseRefs, eventId: 'clm-1' }, dependencies: { caseId: 'case-1', catalystId: 'clm-1', sourceId: 'src-shared' } }), dec('ep-b', beyond, { caseRefs: { ...dec('x', beyond).caseRefs, eventId: 'clm-2' }, dependencies: { caseId: 'case-2', catalystId: 'clm-2', sourceId: 'src-shared' } })]), d), { nowTs: after(d) }); assert.equal(sourceOnly.assignment['ep-a'], 'PURGED'); assert.equal(sourceOnly.assignment['ep-b'], 'PURGED'); assert.deepEqual(sourceOnly.components[0].dependencies.sources, ['src-shared']);
  const independent = assignGroups(d, groupsFromReport(report([dec('ep-a', before, { inputMode: 'MARKET_DIRECT', caseRefs: null, dependencies: null }), dec('ep-b', beyond, { inputMode: 'MARKET_DIRECT', caseRefs: null, dependencies: null })]), d), { nowTs: after(d) }); assert.equal(independent.assignment['ep-a'], 'DEVELOPMENT'); assert.equal(independent.assignment['ep-b'], 'HOLDOUT'); assert.equal(independent.components.length, 2, 'without a shared identity the episodes stay independent: nothing is invented');
  const removed = assignGroups(d, groupsFromReport(report([dec('ep-a', before), dec('ep-b', beyond, { dependencies: { caseId: 'case-2', catalystId: null, sourceId: null } })]), d), { nowTs: after(d) }); assert.equal(removed.assignment['ep-a'], 'DEVELOPMENT'); assert.equal(removed.assignment['ep-b'], 'HOLDOUT'); assert.equal(removed.groups.find((g) => g.groupId === 'ep-b').dependencies.sourceId, null, 'a missing identity stays missing');
  const ev = evaluateSplit({ declaration: d, assignment: shared, report: report([dec('ep-a', before), dec('ep-b', beyond)]), split: 'HOLDOUT', nowTs: after(d) }); assert.equal(ev.arms.REF_COMBINED.decisions, 0, 'the closure decides eligibility: nothing of the purged dependency is scored'); assert.deepEqual(ev.arms.REF_COMBINED.eligibleEpisodes, []); const alone = assignGroups(d, groupsFromReport(report([dec('ep-b', beyond, { inputMode: 'MARKET_DIRECT', caseRefs: null, dependencies: null })]), d), { nowTs: after(d) }); assert.deepEqual(evaluateSplit({ declaration: d, assignment: alone, report: report([dec('ep-b', beyond, { inputMode: 'MARKET_DIRECT', caseRefs: null, dependencies: null })]), split: 'HOLDOUT', nowTs: after(d) }).arms.REF_COMBINED.eligibleEpisodes, ['ep-b'], 'the same episode without the shared dependency is eligible');
  // a real report: the consumed case's canonical source (the packet's PRIMARY_CONFIRMATION source id) rides with the decision
  const fx = catalystPacket({ observedTs: ENTRY.decisionKnownAtTs - 180_000, asOfTs: ENTRY.decisionKnownAtTs - 170_000 }); const analysis = analysisFor(fx.claim.claimId, 'UPWARD_PRESSURE', fx.packet); const vc = verifiedCase({ packet: fx.packet, analysis, coin: 'BTC', caseId: 'case-dep', finishedTs: ENTRY.decisionKnownAtTs - 120_000, verifiedTs: ENTRY.decisionKnownAtTs - 60_000, provenance: 'SYNTHETIC_FIXTURE' }); const verification = { ok: true, manifest: vc.manifest, analyses: vc.analyses, packets: vc.packets, verification: vc.verification, verifiedTs: vc.verifiedTs, reasons: [] };
  const withCase = path.join(TEST_DATA, 'dep', 'bundle'); rewriteBundle(FIX.dir, withCase, [{ receiptTs: ENTRY.decisionKnownAtTs - 60_000, kind: 'CASE', payload: { assetId: 'BTC', caseId: 'case-dep', packetId: fx.packet.packetId, analysisId: analysis.analysisId, completionTs: ENTRY.decisionKnownAtTs - 120_000, receiptTs: ENTRY.decisionKnownAtTs - 60_000, direction: 'UPWARD_PRESSURE', provenance: 'SYNTHETIC_FIXTURE', outcome: 'CONSUMED', reasons: [], packet: fx.packet, analysis, verification, verificationDigest: digestOf(verification) } }]);
  const real = await replayExperiment({ bundleDir: withCase, policyFile: FIX.policyFile, arms: ['REF_COMBINED'], experimentId: 'exp-dep', codeDigest: CODE }); const e = real.arms.REF_COMBINED.decisions.find((x) => x.status === 'ENTRY_RESERVED'); assert.equal(e.inputMode, 'CASE_ENRICHED'); assert.equal(e.dependencies.catalystId, fx.claim.claimId); assert.equal(e.dependencies.sourceId, fx.source.sourceId, 'the canonical evidence source id, never a provenance label'); assert.equal(e.dependencies.caseId, 'case-dep');
  const rg = groupsFromReport(real, d).find((g) => g.groupId === e.episodeId); assert.equal(rg.dependencies.sourceId, fx.source.sourceId); assert.equal(rg.arrivedTs, Math.max(e.decisionKnownAtTs, e.caseRefs.caseReceiptTs), 'the arrival clock is the preserved decision / case receipt clock');
  // the real CLI surfaces late[] from those clocks: a holdout window that closes between the trigger and the decision; lateness is a fact of the
  // bound holdout look (a stage artifact ends strictly before its boundary, so nothing in it can arrive after that boundary)
  const lateDecl = declareExperiment({ experimentId: 'exp-late-cli', policyDigest: P.digest, codeDigest: CODE, strategyVersion: P.policy.strategyVersion, arms: ['REF_COMBINED', 'CASH'], seed: P.policy.evaluation.seed, sourceBinding: { sourcePrefix: `journal:${ACCT}`, accountId: ACCT }, startTs: T0, durationMs: ENTRY.triggerTs + 1000 - T0, fractions: { developmentFraction: 0.5, validationFraction: 0.25 }, embargoMs: 0, horizons: { lookbackMs: 0, decisionMs: 0, maxOutcomeMs: HOUR, publicationFloorMs: 0 }, selectionGraceMs: DAY, nowTs: T0 - 1 }); assert.equal(lateDecl.windows.endTs, ENTRY.triggerTs + 1000); assert.ok(ENTRY.decisionKnownAtTs > lateDecl.windows.endTs, 'the decision became known after the window closed');
  const cliStore = createMemoryExperimentStore(); const wl = await walkToOpening(cliStore, lateDecl); const boundLate = await rep({ experimentId: 'exp-late-cli', holdoutOpening: wl.opening.digest }); const file = path.join(TEST_DATA, 'late-hold.json'); writeFileSync(file, JSON.stringify({ ok: true, command: 'replay-experiment', ...boundLate }));
  const out = []; const code = await runCli(['evaluate-holdout', '--policy', FIX.policyFile, '--experiment', 'exp-late-cli', '--run-id', 'run-1', '--report', file, '--owner-stdin', 'true'], { env: { SERPENT_CONTROL_PASSWORD: PW }, stdin: Readable.from([`${PW}\n`]), stdout: (s) => out.push(s), stderr: (s) => out.push(s), clock: () => after(lateDecl), cwd: process.cwd(), experimentStore: cliStore }); assert.equal(code, 0, out.join('')); const j = JSON.parse(out.join('')); assert.ok(j.late.includes(ENTRY.episodeId), `the decision known after the window end is late: ${JSON.stringify(j.late)}`); assert.equal(j.chain.qualified, false, 'a late, purged episode never qualifies'); assert.ok(j.chain.consumed);
});

test('H12 / HR09. experiment records are semantically closed, not merely rehashable: a malformed lifecycle record is refused on append and a malformed-but-rehashed row is refused on read for every kind (unknown key, missing key, null where required, wrong experiment id, wrong version, malformed digest, impossible clock order, mismatched referenced seq / digest, invalid arm / split / run id) and an illegal lifecycle order is refused', async () => {
  const st = createMemoryExperimentStore(); const d = decl({ experimentId: 'exp-rec' }); const w = await walkToOpening(st, d); const bound = await rep({ experimentId: 'exp-rec', holdoutOpening: w.opening.digest }); await evaluateHoldout(st, { experimentId: 'exp-rec', runId: 'run-1', report: bound, groups: groupsFromReport(bound, d), nowTs: after(d) }); const good = (await loadExperiment(st, 'exp-rec')).records; assert.equal(good.length, 6);
  await assert.rejects(st.append('exp-rec', 'SELECTION_LOCKED', { arm: 'REF_COMBINED', nonsense: true }), (e) => { assert.equal(e.code, 'RECORD_INVALID', `HR09 witness: a malformed lifecycle record was appended on the baseline (${e.code})`); return true; });
  const cases = { DECLARED: [(r) => { r.record.extra = 1; }, (r) => { delete r.record.windows; }, (r) => { r.record.binding.policyDigest = null; }, (r) => { r.record.experimentId = 'exp-other'; }, (r) => { r.record.experimentVersion = 'judge-experiment-0'; }, (r) => { r.record.declarationDigest = 'zz'; }, (r) => { r.record.windows.developmentEndTs = r.record.windows.validationEndTs + 1; }], EVALUATED: [(r) => { r.record.split = 'HOLDOUT'; }, (r) => { r.record.evaluationDigest = 'f'.repeat(64); }, (r) => { r.record.declarationDigest = 'f'.repeat(64); }, (r) => { r.record.evaluatedTs = null; }], SELECTION_LOCKED: [(r) => { r.record.arm = 'NOT_AN_ARM'; }, (r) => { r.record.developmentEvaluation.seq = 9; }, (r) => { r.record.validationEvaluation.digest = 'f'.repeat(64); }, (r) => { r.record.lockedTs = 1; }], HOLDOUT_OPENED: [(r) => { r.record.runId = 'bad run id!'; }, (r) => { r.record.lockDigest = 'f'.repeat(64); }, (r) => { r.record.lockSeq = 2; }, (r) => { r.record.openedTs = 1; }], HOLDOUT_EVALUATED: [(r) => { r.record.runId = 'run-9'; }, (r) => { r.record.openingDigest = 'f'.repeat(64); }, (r) => { r.record.arm = 'CASH'; }, (r) => { r.record.qualification = { status: 'MAYBE', blockers: [] }; }, (r) => { r.record.evaluatedTs = 1; }] };
  let n = 0; for (const [kind, muts] of Object.entries(cases)) { const seq = good.find((r) => r.kind === kind).seq; for (const mut of muts) { const copy = createMemoryExperimentStore(); copy._load('exp-rec', good); copy._retamper('exp-rec', seq, mut); await assert.rejects(copy.records('exp-rec'), (e) => e.code === 'RECORD_INVALID' || e.code === 'CHAIN_INVALID', `${kind} mutation ${n} must be refused on read`); assert.equal(ST.verifyRecordChain(copy._rows('exp-rec')).ok, true, 'the digest chain of the tampered store still rehashes: semantics, not hashing, refused it'); n += 1; } }
  const order = createMemoryExperimentStore(); order._load('exp-rec', [good[0], good[3]]); await assert.rejects(order.records('exp-rec'), isCode('RECORD_INVALID'), 'a lock without prior evaluations is an illegal sequence'); const twice = createMemoryExperimentStore(); twice._load('exp-rec', [...good, { ...good[4], seq: 7, prevDigest: good[5].digest }]); await assert.rejects(twice.records('exp-rec'), (e) => e.code === 'RECORD_INVALID' || e.code === 'CHAIN_INVALID', 'a second opening is illegal');
  assert.ok(n >= 20);
});

test('H13 / HR10. every experiment-store mutator proves owner intent before the append: evaluate-experiment and evaluate-holdout refuse a missing / wrong owner secret with no record written and an audit line, the correct proof appends exactly one record, declare / lock / open stay protected, and replay-experiment stays offline and non-mutating', async () => {
  const store = createMemoryExperimentStore(); const d = decl({ experimentId: 'exp-owner' }); await persistDeclaration(store, d); const dev = await rep({ experimentId: 'exp-owner', evidenceScope: stage(d, 'DEVELOPMENT') }); const file = path.join(TEST_DATA, 'owner-dev.json'); writeFileSync(file, JSON.stringify({ ok: true, command: 'replay-experiment', ...dev })); let wall = d.windows.developmentEndTs + 1;
  const run = async (args, { stdinText = null, env = { SERPENT_CONTROL_PASSWORD: PW } } = {}) => { const out = []; const err = []; const code = await runCli(args, { env, stdin: stdinText === null ? null : Readable.from([stdinText]), stdout: (s) => out.push(s), stderr: (s) => err.push(s), clock: () => wall, cwd: process.cwd(), experimentStore: store }); return { code, out: out.join(''), err: err.join(''), json: () => JSON.parse(out.join('')) }; };
  const unauthenticated = await run(['evaluate-experiment', '--policy', FIX.policyFile, '--experiment', 'exp-owner', '--report', file, '--split', 'DEVELOPMENT']); assert.equal(unauthenticated.code, 6, `HR10 witness: evaluate-experiment mutated the authority without owner intent on the baseline (exit ${unauthenticated.code})`); assert.equal((await loadExperiment(store, 'exp-owner')).records.length, 1, 'nothing appended');
  const wrong = await run(['evaluate-experiment', '--policy', FIX.policyFile, '--experiment', 'exp-owner', '--report', file, '--split', 'DEVELOPMENT', '--owner-stdin', 'true'], { stdinText: 'nope\n' }); assert.equal(wrong.code, 6); assert.match(wrong.err, /AUTH_FAILED/); assert.equal((await loadExperiment(store, 'exp-owner')).records.length, 1); const audit = readFileSync(ownerAuditFile(), 'utf8'); assert.ok(audit.includes('"action":"evaluate-experiment"') && audit.includes('"ok":false'), 'the refusal is audited');
  const ok = await run(['evaluate-experiment', '--policy', FIX.policyFile, '--experiment', 'exp-owner', '--report', file, '--split', 'DEVELOPMENT', '--owner-stdin', 'true'], { stdinText: `${PW}\n` }); assert.equal(ok.code, 0, ok.err); assert.equal((await loadExperiment(store, 'exp-owner')).records.length, 2, 'exactly one record'); assert.ok(readFileSync(ownerAuditFile(), 'utf8').includes('"action":"evaluate-experiment","ok":true'));
  const val = await rep({ experimentId: 'exp-owner', evidenceScope: stage(d, 'VALIDATION') }); const vfile = path.join(TEST_DATA, 'owner-val.json'); writeFileSync(vfile, JSON.stringify({ ok: true, command: 'replay-experiment', ...val })); wall = d.windows.validationEndTs + 1; assert.equal((await run(['evaluate-experiment', '--policy', FIX.policyFile, '--experiment', 'exp-owner', '--report', vfile, '--split', 'VALIDATION', '--owner-stdin', 'true'], { stdinText: `${PW}\n` })).code, 0);
  assert.equal((await run(['lock-candidate', '--policy', FIX.policyFile, '--experiment', 'exp-owner', '--arm', 'REF_COMBINED'])).code, 6); assert.equal((await run(['lock-candidate', '--policy', FIX.policyFile, '--experiment', 'exp-owner', '--arm', 'REF_COMBINED', '--owner-stdin', 'true'], { stdinText: `${PW}\n` })).code, 0); wall = after(d); assert.equal((await run(['open-holdout', '--policy', FIX.policyFile, '--experiment', 'exp-owner', '--run-id', 'run-o'])).code, 6); const opened = await run(['open-holdout', '--policy', FIX.policyFile, '--experiment', 'exp-owner', '--run-id', 'run-o', '--owner-stdin', 'true'], { stdinText: `${PW}\n` }); assert.equal(opened.code, 0, opened.err); assert.equal(opened.json().evaluation, undefined, 'the opening evaluates nothing');
  const bound = await rep({ experimentId: 'exp-owner', holdoutOpening: opened.json().opening.digest }); const hfile = path.join(TEST_DATA, 'owner-hold.json'); writeFileSync(hfile, JSON.stringify({ ok: true, command: 'replay-experiment', ...bound })); const records = async () => (await loadExperiment(store, 'exp-owner')).records.length; const before = await records();
  assert.equal((await run(['evaluate-holdout', '--policy', FIX.policyFile, '--experiment', 'exp-owner', '--run-id', 'run-o', '--report', hfile])).code, 6); assert.equal((await run(['evaluate-holdout', '--policy', FIX.policyFile, '--experiment', 'exp-owner', '--run-id', 'run-o', '--report', hfile, '--owner-stdin', 'true'], { stdinText: 'nope\n' })).code, 6); assert.equal(await records(), before, 'no append without owner intent');
  const held = await run(['evaluate-holdout', '--policy', FIX.policyFile, '--experiment', 'exp-owner', '--run-id', 'run-o', '--report', hfile, '--owner-stdin', 'true'], { stdinText: `${PW}\n` }); assert.equal(held.code, 0, held.err); assert.equal(await records(), before + 1); assert.equal(held.json().chain.qualified, true); assert.ok(readFileSync(ownerAuditFile(), 'utf8').includes('"action":"evaluate-holdout","ok":true'));
  const { MUTATING } = await import('../judge/commands.js'); for (const c of ['declare-experiment', 'evaluate-experiment', 'lock-candidate', 'open-holdout', 'evaluate-holdout']) assert.ok(MUTATING.includes(c), `${c} is a mutating authority command`); assert.ok(!MUTATING.includes('replay-experiment'));
  const research = await run(['replay-experiment', '--policy', FIX.policyFile, '--bundle', FIX.dir, '--experiment', 'exp-owner', '--arms', 'CASH'], { env: {} }); assert.equal(research.code, 0, research.err); assert.equal(await records(), before + 1, 'replay-experiment never touches the store');
});
