// JUDGE / EXECUTION — adapters (E01-E12) and paper realism (P01, P02, P09). Local transport doubles only: the Kraken REST
// path is exercised against a loopback function that records exact bodies; the authentication vector is Kraken's published
// one; no socket, no key, no venue.
import test from 'node:test';
import assert from 'node:assert/strict';
import { signRequest, createNonceStore, createKrakenAdapter, redactKeyInfo, specFromAssetPair, KRAKEN_ENDPOINTS, FORBIDDEN_ENDPOINT_RE } from '../execution/kraken-adapter.js';
import { createPaperAdapter, PAPER_LIMITATION } from '../execution/paper-adapter.js';
import { createExecutionFeed } from '../execution/feed.js';
import { feeContract, keyFingerprint } from '../execution/contract.js';
import { adapterEventError } from '../execution/adapter-contract.js';
import { crc32 } from '../lib/crc32.js';
import { fakeClock, tmp, cleanup, SPEC, TAKER_FEE, T0 } from './helpers/judge.js';

const VECTOR = { key: 'kQH5HW/8p1uGOVjbgWA7FunAmGO8lsSUXNsu3eow76sz84Q18fWxnyRzBHCd3pd5nE9qa99HAZtuZuj6F1huXg==', nonce: '1616492376594', path: '/0/private/AddOrder', params: { ordertype: 'limit', pair: 'XBTUSD', price: '37500', type: 'buy', volume: '1.25' }, expected: '4/dpxb3iT4tp/ZCVEwSnEsLxx0bqyhLpdfOpc6fn7OR8+UClSV5n9E6aSS8MPtnRfp32bAb0nmbRn6H8ndwLUQ==' };
const CRED = { key: 'SYNTHETIC-TEST-KEY-not-real', secret: VECTOR.key };
function transportDouble(routes) { const calls = []; const fn = async (url, init) => { const u = new URL(url); const body = init.body ? Object.fromEntries(new URLSearchParams(init.body)) : {}; calls.push({ path: u.pathname, body, headers: init.headers, raw: init.body }); const r = routes[u.pathname]; if (!r) return { status: 404, text: async () => 'not found' }; const out = typeof r === 'function' ? await r(body, calls.length) : r; if (out instanceof Error) throw out; return { status: out.status ?? 200, text: async () => (typeof out.text === 'string' ? out.text : JSON.stringify(out.json ?? { error: [], result: out.result ?? {} })) }; }; fn.calls = calls; return fn; }
const adapterFor = (transport, over = {}) => createKrakenAdapter({ accountId: 'live-t', clock: () => T0, credentials: CRED, nonceStore: { next: async () => '1616492376594', peek: () => '1616492376594' }, transport, allowPrivate: () => true, allowOrders: () => true, monotonic: () => 0, ...over });
const intent = (over = {}) => ({ intentId: 'i1', orderId: 'o1', clientOrderId: 'clord000000000001', reservationId: 'r1', positionId: 'p1', kind: 'ENTRY', side: 'buy', pair: 'XBT/USD', qty: '0.001', limitPrice: '100000', orderType: 'limit', timeInForce: 'IOC', protection: { ordertype: 'stop-loss', trigger: 'last', price: '99000' }, deadlineTs: T0 + 3000, feeDigest: TAKER_FEE.feeDigest, specDigest: SPEC.specDigest, snapshotDigest: null, createdTs: T0, ...over });

test('E01. Kraken published authentication vector reproduces byte-for-byte; the signed body IS the sent body; the nonce store is monotone across a backwards wall clock and a restart, and serialized across concurrent reads and orders', async () => {
  const s = signRequest({ path: VECTOR.path, nonce: VECTOR.nonce, params: VECTOR.params, secret: VECTOR.key }); assert.equal(s.signature, VECTOR.expected); assert.equal(s.postData, 'nonce=1616492376594&ordertype=limit&pair=XBTUSD&price=37500&type=buy&volume=1.25');
  const dir = tmp('nonce-'); try { let wall = 1_000_000; const ns = createNonceStore({ dir, fingerprint: 'kf-test', wall: () => wall }); const a = await ns.next(); wall -= 500_000; const b = await ns.next(); assert.ok(BigInt(b) > BigInt(a), 'backwards wall clock still advances'); const results = await Promise.all([ns.next(), ns.next(), ns.next(), ns.next()]); const sorted = [...results].sort((x, y) => (BigInt(x) < BigInt(y) ? -1 : 1)); assert.deepEqual(results, sorted); assert.equal(new Set(results).size, 4); const ns2 = createNonceStore({ dir, fingerprint: 'kf-test', wall: () => 1 }); const c = await ns2.next(); assert.ok(BigInt(c) > BigInt(results.at(-1)), 'restart with an older clock continues from the durable value'); } finally { cleanup(dir); }
  const t = transportDouble({ '/0/private/Balance': { result: { ZUSD: '500.00' } } }); const a = adapterFor(t); const r = await a.rest('Balance'); assert.equal(r.ok, true); const call = t.calls[0]; assert.equal(call.headers['API-Key'], CRED.key); assert.equal(call.raw, 'nonce=1616492376594'); assert.equal(call.headers['API-Sign'], signRequest({ path: '/0/private/Balance', nonce: '1616492376594', params: {}, secret: CRED.secret }).signature);
});

test('E02/E12. the REST IOC limit + conditional stop payload uses exact native names and lexemes; increments / minima / deadline / cl_ord_id length are validated before any request; unsupported forms refuse; trigger=last is recorded', async () => {
  const t = transportDouble({ '/0/private/AddOrder': { result: { txid: ['OABC-1'], descr: { order: 'buy 0.00100000 XBTUSD @ limit 100000.0', close: 'close position @ stop loss 99000.0' } } } }); const a = adapterFor(t);
  const r = await a.submitEntryWithProtection({ intent: intent(), spec: SPEC }); assert.equal(r.outcome, 'ACKNOWLEDGED'); assert.equal(r.nativeOrderId, 'OABC-1');
  const b = t.calls[0].body; assert.deepEqual(b, { nonce: '1616492376594', ordertype: 'limit', type: 'buy', volume: '0.001', pair: 'XBTUSD', price: '100000', timeinforce: 'IOC', cl_ord_id: 'clord000000000001', deadline: new Date(T0 + 3000).toISOString(), oflags: 'fciq', trigger: 'last', 'close[ordertype]': 'stop-loss', 'close[price]': '99000' });
  assert.equal(t.calls[0].raw.includes('close%5Bordertype%5D=stop-loss'), true, 'the signed body carries the documented close[...] fields');
  for (const [over, re] of [[{ qty: '0.00000001' }, /minimum/], [{ limitPrice: '100000.05' }, /increment/], [{ timeInForce: 'GTC' }, /IOC/], [{ protection: null }, /stop-loss/], [{ clientOrderId: 'x'.repeat(19) }, /18/]]) { const rr = await a.submitEntryWithProtection({ intent: intent(over), spec: SPEC }); assert.equal(rr.outcome, 'REJECTED', JSON.stringify(over)); assert.match(rr.reason, re); assert.equal(rr.guaranteesNoAcceptance, true); }
  assert.equal(t.calls.length, 1, 'refusals never reach the transport');
  const short = createKrakenAdapter({ accountId: 'x', clock: () => T0, credentials: CRED, transport: t, allowPrivate: () => true, allowOrders: () => true, deadlineMs: 1000, nonceStore: { next: async () => '1', peek: () => '1' } }); assert.match((await short.submitEntryWithProtection({ intent: intent(), spec: SPEC })).reason, /deadline/);
});

test('E03/A05. no credentials or private transport in OBSERVE / REPLAY / PAPER; a non-allowlisted endpoint, any withdrawal / transfer / margin path or a foreign URL is refused before a socket opens; orders need the armed permission, private reads the preflight permission', async () => {
  const t = transportDouble({}); const dark = createKrakenAdapter({ accountId: 'x', clock: () => T0, transport: t, nonceStore: { next: async () => '1', peek: () => '1' } });
  await assert.rejects(dark.rest('Balance'), (e) => e.code === 'CREDENTIALS_ABSENT'); const pre = await dark.preflight(); assert.equal(pre.ok, false); assert.equal(pre.reason, 'CREDENTIALS_ABSENT');
  const unarmed = createKrakenAdapter({ accountId: 'x', clock: () => T0, credentials: CRED, transport: t, allowPrivate: () => true, allowOrders: () => false, nonceStore: { next: async () => '1', peek: () => '1' } }); await assert.rejects(unarmed.rest('AddOrder', {}), (e) => e.code === 'ORDERS_NOT_PERMITTED');
  const noPriv = createKrakenAdapter({ accountId: 'x', clock: () => T0, credentials: CRED, transport: t, allowPrivate: () => false, nonceStore: { next: async () => '1', peek: () => '1' } }); await assert.rejects(noPriv.rest('Balance'), (e) => e.code === 'PRIVATE_NOT_PERMITTED'); assert.equal((await noPriv.preflight()).reason, 'PREFLIGHT_NOT_AUTHORIZED');
  for (const bad of ['Withdraw', 'WalletTransfer', 'WithdrawInfo', 'DepositAddresses', 'Staking', 'https://evil.example/0/private/AddOrder', '../private/Withdraw']) await assert.rejects(dark.rest(bad), (e) => e.code === 'ENDPOINT_DENIED', bad);
  assert.equal(t.calls.length, 0, 'nothing reached the transport'); for (const e of Object.values(KRAKEN_ENDPOINTS)) assert.equal(FORBIDDEN_ENDPOINT_RE.test(e.path), false);
  const noTransport = createKrakenAdapter({ accountId: 'x', clock: () => T0, credentials: CRED, allowPrivate: () => true, nonceStore: { next: async () => '1', peek: () => '1' } }); await assert.rejects(noTransport.rest('Balance'), (e) => e.code === 'NO_TRANSPORT');
});

test('E05/E10. an unknown AddOrder / Cancel / Amend result stays UNCERTAIN (timeout, 5xx, malformed, txid-less ack), rejections carry the no-acceptance guarantee only for documented invalid-order errors; 429 backs off entries while safety work keeps capacity', async () => {
  let n = 0; const t = transportDouble({ '/0/private/AddOrder': (body) => { n += 1; if (n === 1) return Object.assign(new Error('socket hang up'), { name: 'Error' }); if (n === 2) return { status: 502, text: 'bad gateway' }; if (n === 3) return { text: '<html>' }; if (n === 4) return { result: {} }; if (n === 5) return { json: { error: ['EOrder:Insufficient funds'] } }; return { json: { error: ['EService:Busy'] } }; }, '/0/private/CancelOrder': (body, i) => (i % 2 ? Object.assign(new Error('timeout'), { name: 'AbortError' }) : { result: { count: 0, pending: true } }), '/0/private/AmendOrder': { json: { error: ['EOrder:Unknown order'] } }, '/0/private/Balance': { status: 429, text: 'slow down' } });
  const a = adapterFor(t); const outcomes = []; for (let i = 0; i < 6; i += 1) outcomes.push(await a.submitEntryWithProtection({ intent: intent({ clientOrderId: `cl${i}` }), spec: SPEC }));
  assert.deepEqual(outcomes.map((o) => o.outcome), ['UNCERTAIN', 'UNCERTAIN', 'UNCERTAIN', 'UNCERTAIN', 'REJECTED', 'REJECTED']); assert.equal(outcomes[4].guaranteesNoAcceptance, true); assert.equal(outcomes[5].guaranteesNoAcceptance, false, 'EService:Busy is not proof of non-acceptance'); assert.match(outcomes[0].reason, /not proof/);
  assert.equal((await a.cancelOwnedOrder({ nativeOrderId: 'O1' })).outcome, 'UNCERTAIN'); assert.equal((await a.cancelOwnedOrder({ nativeOrderId: 'O1' })).outcome, 'UNCERTAIN', 'pending:true is not a confirmed cancellation');
  assert.equal((await a.amendProtection({ nativeOrderId: 'O1', requestedTrigger: '99500', amendId: 'am1' })).outcome, 'FAILED');
  const bal = await a.rest('Balance'); assert.equal(bal.status, 429); assert.ok(a.status().backoffUntil > T0, 'rate limit engages backoff'); assert.equal(a.status().counters.uncertain, 4);
});

test('E12/E08. GetApiKeyInfo redaction persists only allowlisted permission facts + a fingerprint (never the echoed key); unknown vocabulary is AMBIGUOUS, withdrawal permission is FORBIDDEN; paginated reconciliation dedups overlap, records external fills / withdrawals and reports an incomplete page as not flat', async () => {
  const fp = keyFingerprint(CRED.key); const info = { apiKey: CRED.key, apiKeyName: 'trade-bot', iban: 'XXXX', permissions: ['Query Funds', 'Query Open Orders & Trades', 'Query Closed Orders & Trades', 'Create & Modify Orders', 'Cancel & Close Orders'], validUntil: 0, nonceWindow: 0 };
  const red = redactKeyInfo(info, fp); assert.equal(red.assessment, 'OK'); assert.equal(JSON.stringify(red).includes(CRED.key), false); assert.equal(JSON.stringify(red).includes('trade-bot'), false); assert.equal(JSON.stringify(red).includes('XXXX'), false); assert.equal(red.keyFingerprint, fp);
  assert.equal(redactKeyInfo({ ...info, permissions: [...info.permissions, 'Withdraw Funds'] }, fp).assessment, 'FORBIDDEN_PERMISSION_PRESENT'); assert.equal(redactKeyInfo({ ...info, permissions: ['Trade', 'Query'] }, fp).assessment, 'PERMISSION_PROOF_AMBIGUOUS'); assert.equal(redactKeyInfo({ ...info, permissions: info.permissions.slice(1) }, fp).assessment, 'REQUIRED_PERMISSION_MISSING'); assert.equal(redactKeyInfo({}, fp).assessment, 'PERMISSION_PROOF_AMBIGUOUS');
  const pages = [{ count: 3, trades: { T1: { ordertxid: 'OABC-1', pair: 'XXBTZUSD', time: T0 / 1000, type: 'buy', vol: '0.00100000', cost: '100.00000', price: '100000.0', fee: '0.80000' }, T2: { ordertxid: 'OXYZ-9', pair: 'XXBTZUSD', time: T0 / 1000, type: 'buy', vol: '0.5', cost: '50000', price: '100000', fee: '400' } } }, { count: 3, trades: { T2: { ordertxid: 'OXYZ-9', pair: 'XXBTZUSD', time: T0 / 1000, type: 'buy', vol: '0.5', cost: '50000', price: '100000', fee: '400' }, T3: { ordertxid: 'OABC-1', pair: 'XXBTZUSD', time: T0 / 1000 + 1, type: 'buy', vol: '0.00050000', cost: '50', price: '100000', fee: '0.4' } } }];
  let p = 0; const t = transportDouble({ '/0/private/Balance': { result: { ZUSD: '349.20', XXBT: '0.0015' } }, '/0/private/OpenOrders': { result: { open: { 'OOPEN-7': { cl_ord_id: 'foreign', descr: {} } } } }, '/0/private/TradesHistory': () => ({ result: pages[Math.min(p++, 1)] }), '/0/private/ClosedOrders': { result: { closed: {}, count: 0 } }, '/0/private/Ledgers': { result: { ledger: { L1: { type: 'withdrawal', asset: 'ZUSD', amount: '-25.0', time: T0 / 1000 } }, count: 1 } } });
  const a = adapterFor(t); a.registerOrder('clord000000000001', { orderId: 'o1', positionId: 'p1', kind: 'ENTRY' }, 'OABC-1'); const events = []; a.subscribe((e) => { assert.equal(adapterEventError(e), null); events.push(e); });
  const rec = await a.reconcile({ scope: 'STARTUP', sinceTs: T0 - 60_000, maxPages: 2 }); assert.equal(rec.outcome, 'COMPLETE'); assert.equal(rec.executionsSeen, 3, 'overlapping T2 counted once'); assert.equal(rec.unmatched, 3, 'foreign open order, foreign fill, withdrawal'); assert.equal(rec.balances.quoteTotal, '349.2');
  const fills = events.filter((e) => e.type === 'EXECUTION_RECORDED'); assert.deepEqual(fills.map((e) => e.payload.execId), ['T1', 'T3']); assert.equal(fills[0].payload.quote, '100'); assert.equal(fills[0].payload.origin, 'REST_RECONCILIATION');
  const ext = events.filter((e) => e.type === 'EXTERNAL_ACTIVITY'); assert.deepEqual(ext.map((e) => e.payload.kind).sort(), ['FILL', 'ORDER', 'WITHDRAWAL']);
  p = 0; const rec2 = await a.reconcile({ scope: 'PERIODIC', sinceTs: T0 - 60_000, maxPages: 1, knownExecIds: new Set(['T1']) }); assert.equal(rec2.outcome, 'INCOMPLETE'); assert.equal(rec2.pageIncomplete, true);
  const t3 = transportDouble({ '/0/private/Balance': { json: { error: ['EGeneral:Temporary lockout'] } } }); const rec3 = await adapterFor(t3).reconcile({ scope: 'PERIODIC' }); assert.equal(rec3.outcome, 'FAILED'); assert.equal(rec3.pageIncomplete, true);
});

test('E04/E11-native. WebSocket v2 execution records: a partial trade before the order status, a contingent child (ord_ref_id) becomes PROTECTION_STATE not a parent fill, a sequence gap demands reconciliation, unknown statuses / unparseable amounts are RECONCILIATION_REQUIRED, foreign executions are EXTERNAL; quantities beyond safe integers stay exact', async () => {
  const a = adapterFor(transportDouble({})); a.registerOrder('clord000000000001', { orderId: 'o1', positionId: 'p1', kind: 'ENTRY' }, 'OABC-1'); const events = []; a.subscribe((e) => { assert.equal(adapterEventError(e), null); events.push(e); });
  a.onExecutionRecord({ order_id: 'OABC-1', cl_ord_id: 'clord000000000001', exec_id: 'E1', exec_type: 'trade', order_status: 'partially_filled', side: 'buy', order_type: 'limit', order_qty: '0.001', cum_qty: '0.0005', last_qty: '0.0005', last_price: '99999.9', fees: [{ asset: 'USD', qty: '0.4' }], fee_usd_equiv: '0.4', timestamp: '2026-09-08T12:00:00.123456Z', symbol: 'BTC/USD' }, T0 + 1);
  const fill = events.at(-1); assert.equal(fill.type, 'EXECUTION_RECORDED'); assert.equal(fill.payload.base, '0.0005'); assert.equal(fill.payload.quote, '49.99995'); assert.equal(fill.payload.nativeCumQty, '0.0005'); assert.equal(fill.payload.sourceTs, Date.parse('2026-09-08T12:00:00.123Z'));
  a.onExecutionRecord({ order_id: 'OABC-1', cl_ord_id: 'clord000000000001', exec_type: 'status', order_status: 'new', order_qty: '0.001', cum_qty: '0.0005', timestamp: '2026-09-08T12:00:00.100000Z' }, T0 + 2); assert.equal(events.at(-1).type, 'ORDER_STATE'); assert.equal(events.at(-1).payload.state, 'ACKNOWLEDGED');
  a.onExecutionRecord({ order_id: 'OSTOP-2', exec_type: 'new', order_status: 'new', order_type: 'stop-loss', side: 'sell', order_qty: '0.0005', ord_ref_id: 'OABC-1', triggers: { price: '99000.0', price_type: 'static', reference: 'last' }, timestamp: '2026-09-08T12:00:00.200000Z' }, T0 + 3); const prot = events.at(-1); assert.equal(prot.type, 'PROTECTION_STATE'); assert.equal(prot.payload.state, 'ACTIVE'); assert.equal(prot.payload.positionId, 'p1'); assert.equal(prot.payload.trigger, '99000'); assert.equal(prot.payload.qty, '0.0005'); assert.equal(prot.payload.nativeOrderId, 'OSTOP-2');
  a.onExecutionRecord({ order_id: 'OSTOP-2', exec_id: 'E7', exec_type: 'trade', order_status: 'filled', order_type: 'stop-loss', side: 'sell', order_qty: '0.0005', cum_qty: '0.0005', last_qty: '0.0005', last_price: '98990.0', fees: [{ asset: 'USD', qty: '0.4' }], ord_ref_id: 'OABC-1', timestamp: '2026-09-08T12:00:01.000000Z' }, T0 + 4); const childFill = events.filter((e) => e.type === 'EXECUTION_RECORDED').at(-1); assert.equal(childFill.payload.orderId, null, 'a child fill is not a parent fill: the dispatcher attributes it through the position'); assert.equal(childFill.payload.ordRefId, 'OABC-1'); assert.equal(childFill.payload.side, 'sell');
  a.onExecutionRecord({ order_id: 'OFOREIGN', cl_ord_id: 'someone', exec_id: 'E9', exec_type: 'trade', side: 'buy', last_qty: '1', last_price: '2', cum_qty: '1', timestamp: '2026-09-08T12:00:02Z', symbol: 'ETH/USD' }, T0 + 5); assert.equal(events.at(-1).type, 'EXTERNAL_ACTIVITY'); assert.equal(events.at(-1).payload.kind, 'FILL');
  a.onExecutionRecord({ order_id: 'OABC-1', cl_ord_id: 'clord000000000001', exec_type: 'status', order_status: 'mystery', cum_qty: '0.0005', timestamp: '2026-09-08T12:00:03Z' }, T0 + 6); assert.equal(events.at(-1).payload.state, 'RECONCILIATION_REQUIRED');
  a.onExecutionRecord({ order_id: 'OABC-1', cl_ord_id: 'clord000000000001', exec_id: 'E10', exec_type: 'trade', side: 'buy', last_qty: 'abc', last_price: '1', cum_qty: '0.0005', timestamp: '2026-09-08T12:00:03Z' }, T0 + 7); assert.equal(events.at(-1).payload.state, 'RECONCILIATION_REQUIRED');
  const big = createKrakenAdapter({ accountId: 'x', clock: () => T0, credentials: CRED, transport: transportDouble({}), allowPrivate: () => true, allowOrders: () => true, nonceStore: { next: async () => '1', peek: () => '1' } }).parseLexemes; void big;
  const raw = '{"channel":"executions","type":"update","sequence":7,"data":[{"order_id":"OABC-1","cl_ord_id":"clord000000000001","exec_id":"E11","exec_type":"trade","side":"buy","last_qty":123456789012345678901.123456789,"last_price":0.1,"cum_qty":1,"timestamp":"2026-09-08T12:00:04Z"}]}'; const feed = createExecutionFeed(); const parsed = feed.parseLexemes(raw); a.onExecutionRecord(parsed.data[0], T0 + 8); assert.equal(events.at(-1).payload.base, '123456789012345678901.123456789');
});

// ---- PAPER ----------------------------------------------------------------------------------------------------------------
const fmt = (v, d) => v.toFixed(d).replace('.', '').replace(/^0+/, ''); const crcFor = (asks, bids) => crc32([...asks, ...bids].map(([p, q]) => fmt(p, 1) + fmt(q, 8)).join(''));
function paperFixture({ clock = fakeClock(), fee = TAKER_FEE, script, restore = null } = {}) {
  const feed = createExecutionFeed({ clock: clock.now }); feed.admit('XBT/USD', { priority: 'PENDING', reason: 'test' }); feed.onConnect(clock.now()); feed.ingest(JSON.stringify({ channel: 'instrument', type: 'snapshot', data: { pairs: [{ symbol: 'XBT/USD', price_precision: 1, qty_precision: 8 }] } }), clock.now());
  const adapter = createPaperAdapter({ accountId: 'paper-t', clock: clock.now, feed, fee, specOf: () => SPEC, script, restore }); const events = []; adapter.subscribe((e) => { assert.equal(adapterEventError(e), null); events.push(e); });
  const book = (type, asks, bids, ts = clock.now()) => { feed.ingest(JSON.stringify({ channel: 'book', type, data: [{ symbol: 'XBT/USD', asks: asks.map(([price, qty]) => ({ price, qty })), bids: bids.map(([price, qty]) => ({ price, qty })), timestamp: new Date(ts).toISOString() }] }), ts); };
  const trade = (price, ts = clock.now()) => feed.ingest(JSON.stringify({ channel: 'trade', type: 'update', data: [{ symbol: 'XBT/USD', side: 'sell', price, qty: 0.01, ord_type: 'market', trade_id: Math.floor(Math.random() * 1e9), timestamp: new Date(ts).toISOString() }] }), ts);
  return { clock, feed, adapter, events, book, trade };
}
const full = (asks, bids) => ({ asks, bids });

test('P01. paper fill samples the FIRST accepted book at/after arrival (dispatch + 250ms) within 1000ms: a pre-dispatch book and a later better book are never used; the extra observation wait is logged; no book -> UNFILLED_COVERAGE_UNKNOWN, unscorable, never a fill', async () => {
  const f = paperFixture(); const { clock, adapter, events, book } = f; const snap = { asks: [[100000.0, 1], [100000.5, 1]], bids: [[99999.0, 1]] };
  book('snapshot', snap.asks, snap.bids); clock.advance(100); const r = await adapter.submitEntryWithProtection({ intent: intent({ limitPrice: '100001' }), spec: SPEC }); assert.equal(r.outcome, 'ACKNOWLEDGED'); assert.equal(r.arrivalTs, clock.now() + 250);
  clock.advance(100); book('update', [[99990.0, 5]], []); assert.equal(events.filter((e) => e.type === 'EXECUTION_RECORDED').length, 0, 'a book before arrival is not sampled even when better');
  clock.advance(200); book('update', [[99995.0, 0.0002]], []); const fills = events.filter((e) => e.type === 'EXECUTION_RECORDED'); assert.equal(fills.length, 1, 'first post-arrival book fills at once'); assert.equal(fills[0].payload.price, '99990', 'at the sampled book, best ask 99990 with 5 available'); assert.equal(fills[0].payload.base, '0.001'); assert.equal(adapter.sampled('o1').observationWaitMs, 50); assert.equal(events.filter((e) => e.type === 'ORDER_STATE').at(-1).payload.state, 'FILLED');
  const prot = events.filter((e) => e.type === 'PROTECTION_STATE'); assert.deepEqual(prot.map((e) => e.payload.state), ['PENDING', 'ACTIVE']); assert.equal(prot[1].payload.qty, '0.001'); assert.equal(prot[1].payload.trigger, '99000');
  // no book inside the window -> unscorable
  const g = paperFixture(); g.book('snapshot', snap.asks, snap.bids); g.clock.advance(10); await g.adapter.submitEntryWithProtection({ intent: intent(), spec: SPEC }); g.clock.advance(1500); g.book('update', [[99000.0, 5]], []); assert.equal(g.events.filter((e) => e.type === 'EXECUTION_RECORDED').length, 0, 'a book after the window is never a fill'); g.adapter.onTick(g.clock.now()); const st = g.events.filter((e) => e.type === 'ORDER_STATE').at(-1); assert.equal(st.payload.state, 'EXPIRED'); assert.match(st.payload.reason, /UNFILLED_COVERAGE_UNKNOWN/); assert.equal(g.adapter.status().counters.unfilledCoverageUnknown, 1); assert.equal(g.adapter.limitation, PAPER_LIMITATION);
});

test('P09. per-level depletion oracle: Q=10 consume 6 -> 4; another price only -> 4; repeat Q=10 -> 4; Q=12 -> 6; Q=5 -> 0; explicit remove then re-add resets; a reconnect snapshot marks consumed levels PAPER_LIQUIDITY_UNCERTAIN; the checkpoint restores depletion; two orders share one account and separate accounts do not', async () => {
  const f = paperFixture(); const { clock, adapter, book } = f; const L = 100000.0;
  book('snapshot', [[L, 10]], [[99999.0, 1]]); await adapter.submitEntryWithProtection({ intent: intent({ qty: '6', limitPrice: '100000', clientOrderId: 'a' }), spec: SPEC }); clock.advance(300); book('update', [[L, 10]], []);
  assert.equal(adapter.availableAt('XBT/USD', 'asks', '100000', '10'), '4');
  clock.advance(10); book('update', [[100000.5, 3]], []); assert.equal(adapter.availableAt('XBT/USD', 'asks', '100000', '10'), '4', 'an unrelated level does not refill');
  clock.advance(10); book('update', [[L, 10]], []); assert.equal(adapter.availableAt('XBT/USD', 'asks', '100000', '10'), '4', 'an identical repeat does not refill');
  clock.advance(10); book('update', [[L, 12]], []); assert.equal(adapter.availableAt('XBT/USD', 'asks', '100000', '12'), '6', 'an increase adds only its increment');
  clock.advance(10); book('update', [[L, 5]], []); assert.equal(adapter.availableAt('XBT/USD', 'asks', '100000', '5'), '0', 'a decrease never refunds');
  clock.advance(10); book('update', [[L, 0]], []); clock.advance(10); book('update', [[L, 7]], []); assert.equal(adapter.availableAt('XBT/USD', 'asks', '100000', '7'), '7', 'explicit removal then a new positive level is a new generation'); assert.equal(adapter.depletionOf('XBT/USD', 'asks', '100000').generation, 2);
  await adapter.submitEntryWithProtection({ intent: intent({ qty: '2', limitPrice: '100000', clientOrderId: 'b', orderId: 'o2', positionId: 'p2' }), spec: SPEC }); clock.advance(300); book('update', [[L, 7]], []); assert.equal(adapter.availableAt('XBT/USD', 'asks', '100000', '7'), '5', 'the second order of the SAME account shares the depletion');
  const cp = adapter.checkpoint(); const g = paperFixture({ restore: cp }); g.book('snapshot', [[L, 7]], [[99999.0, 1]]); assert.equal(g.adapter.availableAt('XBT/USD', 'asks', '100000', '7'), '5', 'restart conserves depletion (first snapshot of the new life does not mark uncertainty)');
  clock.advance(10); f.feed.onDisconnect(clock.now()); f.feed.onConnect(clock.now()); book('snapshot', [[L, 7]], [[99999.0, 1]]); assert.equal(adapter.availableAt('XBT/USD', 'asks', '100000', '7'), '0', 'continuity loss: consumed levels are PAPER_LIQUIDITY_UNCERTAIN, not fresh liquidity'); assert.ok(adapter.status().counters.uncertainLevels >= 1);
  const other = paperFixture(); other.book('snapshot', [[L, 7]], [[99999.0, 1]]); assert.equal(other.adapter.availableAt('XBT/USD', 'asks', '100000', '7'), '7', 'a separate shadow account has its own depth');
});

test('P02/E06/E07. partial fill against thin displayed depth with per-execution fee rounding, base-currency fee reduces the protected quantity, the paper stop triggers from the trade feed (trigger=last) and fills against the first bids after arrival, cancel-vs-trigger race reports ALREADY_TERMINAL, a rejected child stop is FAILED, adverse stop fill below trigger', async () => {
  const perExec = feeContract({ venue: 'kraken', pairKey: null, orderType: 'TAKER', rate: '0.0001', rateKind: 'PAPER_REFERENCE', currency: 'QUOTE', roundingQuantum: '0.01', roundingMode: 'UP', minimumFee: '0', scope: 'PER_EXECUTION', maxExecutionsBound: 4, boundSource: 'synthetic witness', scheduleId: 'w', observedTs: T0 });
  const f = paperFixture({ fee: perExec }); const { clock, adapter, events, book, trade } = f;
  book('snapshot', [[100000.0, 0.0005], [100000.5, 0.0003]], [[99999.0, 2], [99998.0, 2]]); await adapter.submitEntryWithProtection({ intent: intent({ limitPrice: '100001' }), spec: SPEC }); clock.advance(300); book('update', [[100001.0, 1]], []);
  const fills = events.filter((e) => e.type === 'EXECUTION_RECORDED'); assert.equal(fills.length, 3); assert.deepEqual(fills.map((e) => e.payload.base), ['0.0005', '0.0003', '0.0002']); assert.deepEqual(fills.map((e) => e.payload.fee.amount), ['0.01', '0.01', '0.01'], 'each execution rounds its own fee up'); assert.equal(events.filter((e) => e.type === 'ORDER_STATE').at(-1).payload.state, 'FILLED');
  clock.advance(10); book('update', [], [[99999.0, 0], [99998.0, 0]]); clock.advance(10); trade(98999.0); const trig = events.filter((e) => e.type === 'PROTECTION_STATE').at(-1); assert.equal(trig.payload.state, 'TRIGGERED');
  assert.equal((await adapter.cancelOwnedOrder({ nativeOrderId: trig.payload.nativeOrderId })).outcome, 'ALREADY_TERMINAL', 'the cancel lost the race');
  clock.advance(100); book('update', [], [[98990.0, 0.0004]]); assert.equal(events.filter((e) => e.type === 'EXECUTION_RECORDED').length, 3, 'a bid before the stop arrival is not used');
  clock.advance(200); book('update', [], [[98950.0, 1]]); const stopFills = events.filter((e) => e.type === 'EXECUTION_RECORDED' && e.payload.side === 'sell'); assert.equal(stopFills.length, 2); assert.equal(stopFills[0].payload.price, '98990', 'adverse: below the 99000 trigger, at the sampled bids'); assert.deepEqual(stopFills.map((e) => e.payload.base), ['0.0004', '0.0006']); assert.equal(stopFills[0].payload.orderId, trig.payload.nativeOrderId);
  const g = paperFixture({ fee: feeContract({ ...TAKER_FEE, currency: 'BASE', feeDigest: undefined }), script: () => ({ childStop: 'REJECT' }) }); g.book('snapshot', [[100000.0, 1]], [[99999.0, 1]]); await g.adapter.submitEntryWithProtection({ intent: intent(), spec: SPEC }); g.clock.advance(300); g.book('update', [[100000.0, 1]], []); const gf = g.events.filter((e) => e.type === 'EXECUTION_RECORDED'); assert.equal(gf[0].payload.fee.asset, 'BTC'); assert.equal(gf[0].payload.fee.amount, '0.000008'); const gp = g.events.filter((e) => e.type === 'PROTECTION_STATE'); assert.deepEqual(gp.map((e) => e.payload.state), ['PENDING', 'FAILED']); assert.equal(gp[0].payload.qty, '0.000992', 'the protected quantity is net of the base fee');
  const h = paperFixture({ script: () => ({ dispatch: 'UNCERTAIN' }) }); h.book('snapshot', [[100000.0, 1]], [[99999.0, 1]]); const hr = await h.adapter.submitEntryWithProtection({ intent: intent(), spec: SPEC }); assert.equal(hr.outcome, 'UNCERTAIN'); assert.equal((await h.adapter.cancelOwnedOrder({ orderId: 'o1', nativeOrderId: null })).outcome, 'UNCERTAIN');
});
