// JUDGE — the end-to-end fault matrix over the REAL composition and the PostgreSQL journal authority (own schema on the
// established loopback cluster; skips honestly without a database). Two vertical slices:
//   1. PAPER / MARKET_DIRECT: sealed case intake (refused as operational evidence when synthetic), a real RANGE_IGNITION
//      decision, the paper fill + child stop, a Watch deterioration exit, restart / reconciliation, verified account,
//      projection / posture agreement, the evaluation report.
//   2. LIVE wire serialization against a scripted venue (loopback transport, synthetic key): exact AddOrder body, a partial
//      fill BEFORE the order status, the native contingent child, IOC expiry, deterioration exit through cancel + the
//      cancel / fill race (the venue acknowledges the cancel, the stop's fill still arrives: the fill is the truth), FLAT
//      with realized P&L, restart reconciliation deduplicating the trades it already knows, live-owner slot claim / release.
import test from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import { mkdtempSync, rmSync, writeFileSync, readFileSync, mkdirSync, cpSync } from 'node:fs';
import { tmpdir } from 'node:os';

const TEST_DATA = mkdtempSync(path.join(tmpdir(), 'cobra-judge-e2e-')); process.env.COBRA_DATA_DIR = TEST_DATA;
const TEST_URL = process.env.PERSIST_TEST_DATABASE_URL ?? process.env.DATABASE_URL; const SCHEMA = `judge_e2e_${Date.now().toString(36)}`; const skip = !TEST_URL;
const { Db } = await import('../persistence/db.js'); const { runMigrations } = await import('../persistence/migrate.js'); const { createPgJournal } = await import('../execution/journal.js');
const { composeJudge, initAccount } = await import('../judge/composition.js'); const { loadJudgePolicy } = await import('../judge/policy.js'); const { createCaseSource } = await import('../judge/case-source.js');
const { fakeClock, SPEC, SAMPLE_LIMITS, T0 } = await import('./helpers/judge.js'); const M = await import('../execution/money.js'); const { crc32 } = await import('../lib/crc32.js');
const { syncPosture, STATES } = await import('../state/machine.js'); const { readExecutionProjection } = await import('../state/execution-projection.js');
const { prepareRelease, approveRelease } = await import('../judge/arming.js'); const { makeEvent, keyFingerprint } = await import('../execution/contract.js');
const MC = await import('./helpers/market-closeout.js'); const MT0 = MC.T0; const { json, H } = MC; const { loadPolicy } = await import('../market-lab/policy.js'); const { createCaseRuntime } = await import('../socrates/runtime.js'); const { corpusCases } = await import('../socrates/corpus.js');

const paperRaw = JSON.parse(readFileSync(path.resolve('judge/samples/policy.paper-reference.json'), 'utf8'));
// a SYNTHETIC 0.1% fee so the reference geometry can pass the 1.5 reward / stressed-risk screen in a fixture (the 0.8% oracle refusals live in judge-cost-capital)
const feeOver = { taker: { ...paperRaw.fees.taker, rate: '0.001', scheduleId: 'synthetic-test-fee' } };
const PAPER_FILE = path.join(TEST_DATA, 'paper.json'); writeFileSync(PAPER_FILE, JSON.stringify({ ...paperRaw, policyName: 'e2e-paper', account: { ...paperRaw.account, accountId: 'e2e-paper' }, fees: feeOver }));
const LIVE_FILE = path.join(TEST_DATA, 'live.json'); writeFileSync(LIVE_FILE, JSON.stringify({ ...paperRaw, policyName: 'e2e-live', mode: 'LIVE', account: { accountId: 'e2e-live', initialCapital: '500', compounding: 'NONE' }, execution: { ...paperRaw.execution, adapter: 'KRAKEN' }, fees: feeOver, live: { allocationCeiling: '500', reinvestment: 'NONE', ownerLimits: null, armExpiryMs: 7 * 86_400_000, canaryMaxBuyConsiderationWithFees: '25', keyEnv: 'E2E_KEY', secretEnv: 'E2E_SECRET' }, authorityNote: 'e2e LIVE test policy against a scripted venue; owner limits / expiry are owner choices at arm time.' }));
const PAPER = loadJudgePolicy(PAPER_FILE); const LIVE = loadJudgePolicy(LIVE_FILE); const KEY = 'SYNTHETIC-E2E-KEY-not-real'; const SECRET = 'kQH5HW/8p1uGOVjbgWA7FunAmGO8lsSUXNsu3eow76sz84Q18fWxnyRzBHCd3pd5nE9qa99HAZtuZuj6F1huXg=='; const ENV = { E2E_KEY: KEY, E2E_SECRET: SECRET };
const CODE = 'c'.repeat(64);
let db; let journal;
test.before(async () => { if (skip) return; db = new Db({ url: TEST_URL, schema: SCHEMA }); assert.equal(await db.connect(), true); await runMigrations(db); journal = createPgJournal({ db }); });
test.after(async () => { if (db) { try { await db.query(`DROP SCHEMA IF EXISTS ${SCHEMA} CASCADE`); } catch { /* best effort */ } await db.end(); } rmSync(TEST_DATA, { recursive: true, force: true }); });

const fmt = (v, d) => v.toFixed(d).replace('.', '').replace(/^0+/, ''); const crcFor = (asks, bids) => crc32([...asks.slice(0, 10), ...bids.slice(0, 10)].map(([p, q]) => fmt(p, 1) + fmt(q, 8)).join(''));
function bars({ n = 61, endTs, close = 100000, range = 400, wickAt = 41, wickLow = 96000 } = {}) { const out = []; for (let i = 0; i < n; i += 1) out.push({ periodStartTs: endTs - (n - i) * 60_000, periodEndTs: endTs - (n - i - 1) * 60_000, open: close, high: close + range / 2, low: i === wickAt ? wickLow : close - range / 2, close, volumeQuote: 1000, volumeBase: 0.01, closed: true }); return out; }
const HISTORY = { bars: (symbol, nowTs) => bars({ endTs: Math.floor(nowTs / 60_000) * 60_000 }) };
const pclockOf = (clock) => ({ now: clock.now, monotonic: clock.monotonic, observeWall: () => null, status: () => ({ trusted: true, kind: 'TEST' }), expired: (t) => clock.now() > t });
// the driver over a composed run: exact wire messages into the execution feed, ticks through the composition, settle via the real queues
function driver(run, clock) {
  const feed = run.feed; feed.onConnect(clock.now()); feed.ingest(JSON.stringify({ channel: 'instrument', type: 'snapshot', data: { pairs: [{ symbol: 'XBT/USD', price_precision: 1, qty_precision: 8 }] } }), clock.now()); feed.ingest(JSON.stringify({ method: 'subscribe', success: true, result: { channel: 'trade', symbol: 'XBT/USD' } }), clock.now());
  const book = (asks, bids, type = 'snapshot') => feed.ingest(JSON.stringify({ channel: 'book', type, data: [{ symbol: 'XBT/USD', asks: asks.map(([price, qty]) => ({ price, qty })), bids: bids.map(([price, qty]) => ({ price, qty })), checksum: crcFor(asks, bids), timestamp: new Date(clock.now()).toISOString() }] }), clock.now());
  let tid = 0; const trade = (price, side = 'buy', qty = 0.05) => feed.ingest(JSON.stringify({ channel: 'trade', type: 'update', data: [{ symbol: 'XBT/USD', side, price, qty, ord_type: 'market', trade_id: ++tid, timestamp: new Date(clock.now()).toISOString() }] }), clock.now());
  const settle = async () => { await run.tick(); await run.judge.drain(); await run.dispatcher.idle(); await run.watch.onTick(clock.now()); await run.dispatcher.idle(); };
  const advance = async (ms, step = 250) => { for (let t = 0; t < ms; t += step) { clock.advance(Math.min(step, ms - t)); await settle(); } };
  async function warm({ minutes = 22, price = 100000 } = {}) { book([[price + 10, 5]], [[price - 10, 5]], 'snapshot'); for (let m = 0; m < minutes; m += 1) { for (let k = 0; k < 4; k += 1) { clock.advance(15_000); trade(price + 1, 'buy'); trade(price - 1, 'sell'); book([[price + 10, 5]], [[price - 10, 5]]); } } await settle(); }
  async function ignite({ price = 100000, level = 100400, books = 3, spanMs = 2100, askQty = 5 } = {}) { const start = Math.floor(clock.now() / 60_000) * 60_000 + 60_000; while (clock.now() < start) clock.advance(1000); for (let k = 0; k < 20; k += 1) { clock.advance(2000); trade(price + 50, 'buy', 0.2); } while (clock.now() % 60_000 !== 0) clock.advance(1000); clock.advance(500); for (let i = 0; i < books; i += 1) { book([[level + 20, askQty], [level + 30, 5]], [[level, 5], [level - 10, 5]]); trade(level + 10, 'buy', 0.1); await settle(); if (i < books - 1) clock.advance(Math.ceil(spanMs / (books - 1))); } await settle(); }
  async function deteriorate() { const p = 100420; for (let i = 0; i < 80; i += 1) { clock.advance(1000); book([[p + 10, 5]], [[p, 1], [p - 10, 1]]); trade(p + 5, 'buy', 0.05); } await settle(); for (let i = 0; i < 4; i += 1) { clock.advance(1100); book([[p + 10, 5]], [[p, 0.1], [p - 10, 0.1]]); for (let k = 0; k < 6; k += 1) trade(p + 1, 'sell', 0.5); clock.advance(100); await settle(); } }
  return { feed, book, trade, settle, advance, warm, ignite, deteriorate, state: () => run.dispatcher.state() };
}
async function sealedCase(dir, { recorded = false } = {}) { const c = corpusCases().find((x) => x.id === 'C01'); const cdir = path.join(dir, `case-${(recorded ? 'b' : 'a').repeat(40)}-${String(MT0 + (recorded ? 1000 : 0)).padStart(13, '0')}`); const policy = loadPolicy(H.policyWith({ providers: ['KRAKEN_SPOT', 'COINBASE_SPOT'], model: { enabled: true, maxEstimatedUsdPerCase: 1, maxEstimatedUsdPerDay: 5, maxEstimatedUsdPerMonth: 50, totalSmokeMaxEstimatedUsd: 1, maxOutputTokens: 2048 } })); const message = { type: 'message', id: 'msg_test', model: 'claude-sonnet-5', stop_reason: 'end_turn', content: [{ type: 'text', text: JSON.stringify(c.scripted) }], usage: { input_tokens: 1200, output_tokens: 300, cache_creation_input_tokens: 0, cache_read_input_tokens: 0 } }; const fetchImpl = async (url) => (new URL(url).pathname === '/v1/messages/count_tokens' ? json({ input_tokens: 1000 }) : json(message)); const rt = createCaseRuntime({ policy, env: { ANTHROPIC_API_KEY: 'sk-ant-test-fixture-not-a-real-key' }, fetchImpl, budgetDir: path.join(dir, recorded ? 'budget-b' : 'budget'), clock: () => MT0 + (recorded ? 1000 : 0), recordedResponse: recorded ? { text: JSON.stringify(c.scripted), source: 'test-fixture' } : null }); try { const r = await rt.runCase({ packet: c.packet, out: cdir }).done; assert.equal(r.status, 'COMPLETED'); return { cdir, packet: c.packet }; } finally { await rt.close(); } }

test('E2E-1 (J02/J09/W04/D04/A07/P08). PAPER over PostgreSQL: a synthetic sealed case is verified but refused as operational evidence (accepted only under REPLAY); the live path decides RANGE_IGNITION MARKET_DIRECT, reserves, fills against the paper venue, protects, then a deterioration exit flattens; restart reconciles the same journal, the chain replays, projection / posture / evaluation agree with the journal', { skip }, async () => {
  const casesDir = path.join(TEST_DATA, 'cases'); mkdirSync(casesDir, { recursive: true }); const { packet } = await sealedCase(casesDir); await sealedCase(casesDir, { recorded: true });
  const clock = fakeClock(MT0 + 60_000); await initAccount({ journal, policy: PAPER.policy, policyDigest: PAPER.digest, mode: 'PAPER', ownerRef: 'owner-test', nowTs: clock.now() });
  const run = await composeJudge({ policyFile: PAPER_FILE, mode: 'PAPER', journal, clock: pclockOf(clock), specs: [SPEC], history: HISTORY, casesDir, nominations: () => [{ symbol: 'XBT/USD', assetId: 'BTC' }], writeProjection: true, codeDigest: CODE, log: () => {} });
  const report = await run.start(); assert.deepEqual(report.uncertainOrders, []); assert.equal(report.authorizationEnded, null);
  await run.cases.refresh(); assert.equal(run.cases.status().verified, 2, 'both sealed cases verify by bytes'); const det = run.cases.detail(packet.subject.canonicalCoin, clock.now(), { requireContext: false }); assert.equal(det.case?.provenance, 'LIVE_MODEL', 'the live-path case is admissible (without a context requirement)'); assert.ok(det.refused.some((r) => r.reasons.includes('SYNTHETIC_PROVENANCE_REFUSED')), `the RECORDED_RESPONSE case is refused as operational evidence: ${JSON.stringify(det.refused)}`); const strict = run.cases.detail(packet.subject.canonicalCoin, clock.now()); assert.equal(strict.case, null); assert.ok(strict.refused.some((r) => r.reasons.some((x) => x.startsWith('CONTEXT_'))), 'without a recomputed context: not a context proof, so the Judge stays MARKET_DIRECT');
  const replaySource = createCaseSource({ casesDir, clock: clock.now, mode: 'REPLAY' }); await replaySource.refresh(); const rp = replaySource.detail(packet.subject.canonicalCoin, clock.now(), { requireContext: false }); assert.ok(rp.case && !rp.refused.some((r) => r.reasons.includes('SYNTHETIC_PROVENANCE_REFUSED')), 'REPLAY may consume the recorded case at its true availability time');
  run.admitNominations(); const d = driver(run, clock); assert.equal(run.judge.candidates().length, 1); await d.warm(); await d.ignite();
  const decisions = run.judge.decisions(); const dec = decisions.find((x) => x.status === 'ENTRY_RESERVED'); assert.ok(dec, `no ENTRY_RESERVED: ${JSON.stringify(decisions.map((x) => [x.status, x.reasonCodes]))} ${JSON.stringify(run.judge.candidates()[0]?.readiness?.RANGE_IGNITION)}`); assert.equal(dec.inputMode, 'MARKET_DIRECT'); assert.equal(dec.caseRefs.packetId, null, 'a refused synthetic case never becomes an input');
  clock.advance(300); d.book([[100420.0, 5]], [[100400.0, 5]]); await d.settle(); const pos = Object.values(d.state().positions)[0]; assert.equal(pos.state, 'OPEN', JSON.stringify(Object.values(d.state().orders).map((o) => [o.orderId, o.state]))); assert.equal(pos.protection.state, 'ACTIVE'); assert.equal(pos.initialR.state, 'FINAL');
  const page = await journal.page('e2e-paper', { afterSeq: 0, limit: 500 }); const types = page.map((p) => p.event.type); assert.ok(types.indexOf('HYPOTHESIS_LOCKED') < types.indexOf('DECISION_RECORDED') && types.indexOf('ORDER_INTENT') < types.indexOf('DISPATCH_ATTEMPTED') && types.indexOf('DISPATCH_ATTEMPTED') < types.indexOf('DISPATCH_RESULT'), 'durable outbox order in PostgreSQL');
  const proj = readExecutionProjection({ now: clock.now() }); assert.equal(proj.state, 'FRESH'); assert.equal(proj.posture, 'STRIKE'); assert.equal(proj.openPositions, 1);
  await d.deteriorate(); const w = run.watch.positions()[0]; assert.equal(w.exit.reason, 'DETERIORATION', JSON.stringify(run.watch.evaluateReasons(d.state().positions[pos.positionId]).det)); clock.advance(300); d.book([[100430.0, 5]], [[100380.0, 5]]); await d.settle(); await d.advance(600);
  const flat = d.state().positions[pos.positionId]; assert.equal(flat.state, 'FLAT', JSON.stringify(run.watch.positions()[0].exit)); assert.ok(flat.realizedPnl !== null); assert.equal(run.feed.pinned().size, 0);
  const funnel = run.judge.funnel(); assert.ok(funnel.reserved >= 1 && funnel.filled >= 1 && funnel.protected >= 1, JSON.stringify(funnel));
  const stopped = await run.stop(); assert.equal(stopped.writerLost, false);
  // restart over the same PostgreSQL journal: nothing resends, the chain verifies, the posture stands down from the persisted STRIKE
  const run2 = await composeJudge({ policyFile: PAPER_FILE, mode: 'PAPER', journal, clock: pclockOf(clock), specs: [SPEC], history: HISTORY, writeProjection: true, codeDigest: CODE, log: () => {}, nominations: () => [] }); const rep2 = await run2.start(); assert.deepEqual(rep2.uncertainOrders, []); assert.deepEqual(rep2.exposedPositions, []);
  const verified = await journal.replayVerify('e2e-paper'); assert.equal(verified.ok, true, verified.reason); assert.equal(run2.dispatcher.state().positions[pos.positionId].state, 'FLAT');
  const p2 = readExecutionProjection({ now: clock.now() }); assert.equal(p2.posture, null); assert.equal(syncPosture().machine.posture, STATES.COILED);
  const ev = run2.evaluate('REF_COMBINED'); assert.equal(ev.support.closedTrades, 1); assert.equal(ev.calibrationState, 'UNVALIDATED_HYPOTHESIS'); assert.ok(ev.netPnl !== null);
  const rel = prepareRelease({ codeTreeDigest: CODE, policy: PAPER.policy, policyDigest: PAPER.digest, evaluation: { paperAccountId: 'e2e-paper', forwardClosedTrades: 1, holdoutUntouched: false, netPnl: ev.netPnl, drawdown: 0, feesAccounted: true, openPositions: 0, evaluationDigest: null, source: 'FIXTURE' }, tests: { criticalSuitesPassing: true, evidenceFile: 'x' }, coverage: { dataFamilies: [], latencySamples: 0 }, acceptance: { independentReview: 'NOT_RUN', reviewer: null }, proposedLimits: SAMPLE_LIMITS, nowTs: clock.now() }); assert.equal(rel.state, 'BLOCKED', 'a fixture run is never release evidence');
  await run2.stop();
});

test('E2E-2 (E02/E04/E06/D06/W08/A09/A04). LIVE wire serialization against a scripted venue: exact AddOrder body (IOC limit + conditional stop, fciq, cl_ord_id <= 18); a partial fill BEFORE the status, the contingent child becomes protection, IOC expiry settles the remainder; a deterioration exit cancels the child (acknowledged) yet the stop fill still arrives — the fill is the truth, no second sell; FLAT with realized P&L; restart reconciliation dedups known trades; the venue owner slot is claimed once and released only reconciled', { skip }, async () => {
  const clock = fakeClock(MT0 + 3_600_000 * 24); await initAccount({ journal, policy: LIVE.policy, policyDigest: LIVE.digest, mode: 'LIVE_UNARMED', ownerRef: 'owner-test', nowTs: clock.now() });
  const trades = {}; let addOrders = 0; const calls = [];
  const transport = async (url, init) => { const u = new URL(url); const body = init?.body ? Object.fromEntries(new URLSearchParams(init.body)) : {}; calls.push({ path: u.pathname, body }); const routes = { '/0/public/Time': { result: { unixtime: Math.floor(clock.now() / 1000) } }, '/0/private/GetApiKeyInfo': { result: { apiKey: KEY, permissions: ['Query Funds', 'Query Open Orders & Trades', 'Query Closed Orders & Trades', 'Create & Modify Orders', 'Cancel & Close Orders'], validUntil: 0, nonceWindow: 0 } }, '/0/private/Balance': { result: { ZUSD: '500.00', XXBT: '0' } }, '/0/private/OpenOrders': { result: { open: {} } }, '/0/private/TradesHistory': { result: { count: Object.keys(trades).length, trades } }, '/0/private/Ledgers': { result: { ledger: {} } }, '/0/private/AddOrder': () => { addOrders += 1; return { result: { txid: [`OE2E-${addOrders}`], descr: { order: 'buy', close: 'close position @ stop loss' } } }; }, '/0/private/CancelOrder': { result: { count: 1, pending: false } } }; const r = routes[u.pathname]; if (!r) return { status: 404, ok: false, text: async () => 'not found' }; const out = typeof r === 'function' ? r(body) : r; return { status: 200, ok: true, text: async () => JSON.stringify({ error: [], result: out.result }) }; };
  const compose = (mode, allowOrders) => composeJudge({ policyFile: LIVE_FILE, mode, accountId: 'e2e-live', env: ENV, journal, clock: pclockOf(clock), transport, specs: [SPEC], history: HISTORY, allowPrivate: () => true, allowOrders, writeProjection: true, codeDigest: CODE, log: () => {}, nominations: () => [{ symbol: 'XBT/USD', assetId: 'BTC' }] });
  // arm: preflight + approved release + owner limits + expiry, then the venue owner slot
  const run0 = await compose('LIVE_UNARMED', () => false); await run0.start(); const pre = await run0.preflight(); assert.equal(pre.ok, true, JSON.stringify(pre));
  const m = prepareRelease({ codeTreeDigest: CODE, policy: LIVE.policy, policyDigest: LIVE.digest, evaluation: { paperAccountId: 'e2e-paper', forwardClosedTrades: 40, holdoutUntouched: true, netPnl: '12.5', drawdown: 0.03, feesAccounted: true, openPositions: 0, evaluationDigest: null, source: 'FORWARD_PAPER' }, tests: { criticalSuitesPassing: true, evidenceFile: 'x' }, coverage: { dataFamilies: ['BOOK'], latencySamples: 10 }, acceptance: { independentReview: 'PASSED', reviewer: 'r' }, proposedLimits: SAMPLE_LIMITS, nowTs: clock.now() }); const ap = approveRelease({ manifest: m, manifestDigest: m.manifestDigest, assessment: 'forward paper sample; uncertainty is wide; the risk of cost underestimation is acknowledged; an experiment-risk decision, not proof.', ownerRef: 'owner-test', sessionTag: 'tag00001', nowTs: clock.now() }); assert.equal(ap.ok, true);
  const armed = await run0.arm({ ownerLimits: SAMPLE_LIMITS, expiresTs: clock.now() + 3_600_000, allocationCeiling: '500', approval: ap.approval, ownerRef: 'owner-test', releaseDigest: ap.approval.releaseDigest }); assert.equal(armed.ok, true, JSON.stringify(armed)); await run0.stop();
  const run = await compose('LIVE_ARMED', () => true); const claim = await journal.claimLiveOwner({ venue: 'kraken', accountId: 'e2e-live', keyFingerprint: run.keyFingerprint, exchangeContext: 'kraken-spot', writerEpoch: run.writer.epoch }); assert.equal(claim.ok, true);
  const rep = await run.start(); assert.equal(rep.authorizationEnded, null); assert.equal(run.dispatcher.state().mode, 'LIVE_UNARMED'); await run.preflight();
  await run.dispatcher.commit(makeEvent({ type: 'MODE_TRANSITION', accountId: 'e2e-live', knownAtTs: clock.now(), payload: { from: 'LIVE_UNARMED', to: 'LIVE_ARMED', reason: 'unexpired authorization resumed after reconciliation + preflight', authorizationId: armed.authorizationId, ts: clock.now() } })); assert.equal(run.dispatcher.state().mode, 'LIVE_ARMED');
  const other = createPgJournal({ db }); assert.equal((await other.claimLiveOwner({ venue: 'kraken', accountId: 'e2e-live-2', keyFingerprint: 'kf-other', exchangeContext: 'kraken-spot', writerEpoch: run.writer.epoch }).catch((e) => ({ ok: false, reason: e.code }))).ok, false, 'A09: a second LIVE identity cannot allocate the same venue');
  run.admitNominations(); const d = driver(run, clock); await d.warm(); await d.ignite();
  const dec = run.judge.decisions().find((x) => x.status === 'ENTRY_RESERVED'); assert.ok(dec, JSON.stringify(run.judge.decisions().map((x) => [x.status, x.reasonCodes]))); await run.dispatcher.idle();
  const add = calls.find((c) => c.path === '/0/private/AddOrder'); assert.ok(add, 'the entry reached the scripted venue'); assert.equal(add.body.ordertype, 'limit'); assert.equal(add.body.type, 'buy'); assert.equal(add.body.timeinforce, 'IOC'); assert.equal(add.body.oflags, 'fciq'); assert.equal(add.body['close[ordertype]'], 'stop-loss'); assert.equal(add.body.trigger, 'last'); assert.ok(add.body.cl_ord_id.length <= 18); assert.equal(add.body.pair, SPEC.altname); assert.equal(add.body.volume, dec.sizing.q); assert.ok(M.lte(add.body.price, dec.sizing.entryLimitPrice)); assert.match(add.body.deadline, /^\d{4}-\d{2}-\d{2}T/);
  const order = Object.values(d.state().orders).find((o) => o.kind === 'ENTRY'); assert.equal(order.state, 'ACKNOWLEDGED'); assert.equal(order.nativeOrderId, 'OE2E-1'); const pos = d.state().positions[order.positionId];
  // native execution records: a partial trade BEFORE the status, the contingent child, then the IOC expiry of the remainder
  const half = M.div(order.qty, '2', 8, 'DOWN'); const px = add.body.price; const a = run.adapter; const ts = () => new Date(clock.now()).toISOString();
  trades.TE2E1 = { ordertxid: 'OE2E-1', pair: SPEC.pairKey, time: clock.now() / 1000, type: 'buy', vol: half, cost: M.mul(half, px), price: px, fee: '0.05' };
  a.onExecutionRecord({ order_id: 'OE2E-1', cl_ord_id: add.body.cl_ord_id, exec_id: 'TE2E1', exec_type: 'trade', order_status: 'partially_filled', side: 'buy', order_type: 'limit', order_qty: order.qty, cum_qty: half, last_qty: half, last_price: px, fees: [{ asset: 'USD', qty: '0.05' }], timestamp: ts(), symbol: 'BTC/USD' }, clock.now()); await run.dispatcher.idle();
  a.onExecutionRecord({ order_id: 'OE2E-1', cl_ord_id: add.body.cl_ord_id, exec_type: 'status', order_status: 'partially_filled', order_qty: order.qty, cum_qty: half, timestamp: ts() }, clock.now()); await run.dispatcher.idle();
  a.onExecutionRecord({ order_id: 'OSTOP-E2E', exec_type: 'new', order_status: 'new', order_type: 'stop-loss', side: 'sell', order_qty: half, ord_ref_id: 'OE2E-1', triggers: { price: add.body['close[price]'], price_type: 'static', reference: 'last' }, timestamp: ts() }, clock.now()); await run.dispatcher.idle();
  a.onExecutionRecord({ order_id: 'OE2E-1', cl_ord_id: add.body.cl_ord_id, exec_type: 'status', order_status: 'expired', order_qty: order.qty, cum_qty: half, timestamp: ts() }, clock.now()); await run.dispatcher.idle(); clock.advance(300); d.book([[100430.0, 5]], [[100410.0, 5], [100400.0, 5]]); await d.settle();
  let p = d.state().positions[pos.positionId]; assert.equal(p.state, 'OPEN'); assert.equal(p.confirmedBase, half); assert.equal(p.protection.state, 'ACTIVE'); assert.equal(p.protection.nativeOrderId, 'OSTOP-E2E'); assert.equal(d.state().orders[order.orderId].state, 'EXPIRED'); assert.ok(p.initialR.state === 'FINAL', JSON.stringify(p.initialR)); const stopOrder = Object.values(d.state().orders).find((o) => o.kind === 'PROTECTIVE_STOP'); assert.ok(stopOrder, 'a journal PROTECTIVE_STOP order books the native child'); assert.equal(readExecutionProjection({ now: clock.now() }).posture, 'STRIKE');
  // deterioration -> exit: the child is cancelled (acknowledged), yet its fill still arrives from the venue: the fill is the truth
  await d.deteriorate(); assert.equal(run.watch.positions()[0].exit.reason, 'DETERIORATION', JSON.stringify({ det: run.watch.evaluateReasons(d.state().positions[pos.positionId]), pos: d.state().positions[pos.positionId].state, exit: run.watch.positions()[0].exit, watch: run.watch.status() })); await d.advance(500);
  const cancel = calls.find((c) => c.path === '/0/private/CancelOrder'); assert.ok(cancel, 'the protection cancel reached the venue'); assert.equal(cancel.body.txid, 'OSTOP-E2E');
  const stopPx = add.body['close[price]']; trades.TE2E2 = { ordertxid: 'OSTOP-E2E', pair: SPEC.pairKey, time: clock.now() / 1000, type: 'sell', vol: half, cost: M.mul(half, stopPx), price: stopPx, fee: '0.05' };
  // the cancel was acknowledged, so the Watch already sent its protective market sell; the venue then reports the stop's fill (late fill after cancellation)
  const sell = calls.filter((c) => c.path === '/0/private/AddOrder')[1]; assert.ok(sell, 'the protective sell reached the venue after the cancel acknowledgement'); assert.equal(sell.body.type, 'sell'); assert.equal(sell.body.ordertype, 'market'); assert.equal(sell.body.volume, half); const sellOrder = Object.values(d.state().orders).find((o) => o.kind === 'PROTECTIVE_EXIT'); assert.equal(sellOrder.state, 'ACKNOWLEDGED'); assert.equal(sellOrder.nativeOrderId, 'OE2E-2');
  a.onExecutionRecord({ order_id: 'OSTOP-E2E', exec_id: 'TE2E2', exec_type: 'trade', order_status: 'filled', order_type: 'stop-loss', side: 'sell', order_qty: half, cum_qty: half, last_qty: half, last_price: stopPx, fees: [{ asset: 'USD', qty: '0.05' }], ord_ref_id: 'OE2E-1', timestamp: ts() }, clock.now()); await run.dispatcher.idle(); await d.advance(1000);
  p = d.state().positions[pos.positionId]; assert.equal(p.soldBase, half, 'the late stop fill is the truth: booked against the protective order'); assert.equal(d.state().orders[stopOrder.orderId].lateFills, 1); assert.equal(p.state, 'EXITING', 'not flat while the protective sell is still open at the venue: no fiction'); assert.equal(run.watch.positions()[0].exit.phase, 'SELLING');
  // the venue refuses the now-unbacked sell (nothing left to sell): its terminal record closes the exit; a fill of it would have been refused as OVERSELL
  a.onExecutionRecord({ order_id: 'OE2E-2', cl_ord_id: sell.body.cl_ord_id, exec_type: 'status', order_status: 'canceled', order_qty: half, cum_qty: '0', reason: 'insufficient funds', timestamp: ts() }, clock.now()); await run.dispatcher.idle(); await d.advance(1000);
  p = d.state().positions[pos.positionId]; assert.equal(p.state, 'FLAT', `${p.state} ${JSON.stringify(run.watch.positions()[0].exit)} ${JSON.stringify(Object.values(d.state().orders).map((o) => [o.kind, o.state]))}`); assert.ok(M.isNegative(p.realizedPnl), 'stopped below entry: a realized loss, recorded'); assert.equal(d.state().orders[sellOrder.orderId].state, 'CANCELLED'); assert.equal(calls.filter((c) => c.path === '/0/private/AddOrder').length, 2, 'entry + one protective sell; never a third'); assert.equal(p.exitQuote, M.mul(half, stopPx), 'exactly one sale accounted');
  assert.ok(!JSON.stringify(run.projection()).includes(SECRET)); const stopped = await run.stop(); assert.equal(stopped.writerLost, false);
  // restart: reconciliation sees both trades it already knows (dedup), nothing external, COMPLETE; the owner slot releases only reconciled
  const run3 = await compose('LIVE_UNARMED', () => false); const rep3 = await run3.start(); assert.deepEqual(rep3.uncertainOrders, []); assert.deepEqual(rep3.exposedPositions, []); assert.equal(rep3.reconciliation?.outcome, 'COMPLETE', JSON.stringify(rep3)); assert.equal(rep3.reconciliation.unmatched, 0, 'known trades are not external activity');
  const verified = await journal.replayVerify('e2e-live'); assert.equal(verified.ok, true, verified.reason); assert.equal((await journal.load('e2e-live')).state.positions[pos.positionId].state, 'FLAT');
  await assert.rejects(journal.releaseLiveOwner({ venue: 'kraken', accountId: 'e2e-live', writerEpoch: run3.writer.epoch, reason: 'x', reconciled: true }), (e) => e.code === 'EPOCH_FENCED', 'a restarted writer must re-claim the slot with its own epoch before it may release'); assert.equal((await journal.claimLiveOwner({ venue: 'kraken', accountId: 'e2e-live', keyFingerprint: run3.keyFingerprint, exchangeContext: 'kraken-spot', writerEpoch: run3.writer.epoch })).ok, true, 'the same binding re-claims on a controlled restart');
  await assert.rejects(journal.releaseLiveOwner({ venue: 'kraken', accountId: 'e2e-live', writerEpoch: run3.writer.epoch, reason: 'x', reconciled: false }), (e) => e.code === 'RELEASE_UNRECONCILED');
  assert.equal((await journal.releaseLiveOwner({ venue: 'kraken', accountId: 'e2e-live', writerEpoch: run3.writer.epoch, reason: 'reconciled flat', reconciled: true })).ok, true); await run3.stop();
  assert.equal(calls.filter((c) => /Withdraw|Transfer|Margin/i.test(c.path)).length, 0);
});
