// JUDGE — cost and capital (C01-C12), the four setup evaluators' clause law (J01 clauses) and cached-vs-batch features (J12).
import test from 'node:test';
import assert from 'node:assert/strict';
import * as M from '../execution/money.js';
import { feeContract, instrumentSpec, digestOf } from '../execution/contract.js';
import { feesForExecutions, worstFeeBound, feeMismatch } from '../execution/fees.js';
import { evaluateEntry, sizeSearch, scenarioExit, stopStressMid, liquidationValue, REWARD_RISK_MIN } from '../judge/cost.js';
import { admitCandidate, computeClusters, rankCandidates, riskBudgetFor } from '../judge/risk.js';
import { indicatorBlock, validateBarBlock, flowImbalance, relativeVolume60, createFlowTracker, createFeatureCache, nearestResistanceAbove, dedupTrades } from '../judge/features.js';
import { freezeReferences, evaluateSetup, createConfirmation, createEpisodeTracker, REFERENCE } from '../judge/setups.js';
import { paperAccount, SPEC, TAKER_FEE, SAMPLE_LIMITS, T0 } from './helpers/judge.js';

const snap = ({ bids, asks, ts = T0 }) => { const s = { snapshotVersion: 'execution-book-snapshot-1', symbol: 'XBT/USD', canonicalCoin: 'BTC', feedEpoch: 1, receiptSequence: 1, nativeSequence: null, sourceTs: ts, receiptTs: ts, crc: 1, crcVerified: true, crcComputed: 1, synced: true, instrumentDigest: SPEC.specDigest, priceDecimals: 1, qtyDecimals: 8, bids, asks, levelsCap: 100, truncated: false, kind: 'SNAPSHOT', digest: 'x'.repeat(64) }; s.digest = digestOf({ ...s, digest: null }); return s; };
const fee = (rate, over = {}) => feeContract({ venue: 'kraken', pairKey: null, orderType: 'TAKER', rate, rateKind: 'PAPER_REFERENCE', currency: 'QUOTE', roundingQuantum: '0.0001', roundingMode: 'UP', minimumFee: '0', scope: 'ORDER_TOTAL', scheduleId: 'synthetic', observedTs: T0, ...over });
const UNIT = instrumentSpec({ venue: 'kraken', pairKey: 'UNITUSD', altname: 'UNITUSD', wsname: 'UNIT/USD', base: 'UNIT', quote: 'ZUSD', canonicalCoin: 'UNIT', status: 'online', priceIncrement: '0.01', qtyIncrement: '0.00000001', orderMin: '0.5', costMin: null, priceDecimals: 2, qtyDecimals: 8, observedTs: T0, source: 'FIXTURE' });

test('C01/C08. exact synthetic oracle: buy 1 @ 100.00 with 0.8% fee, executable bid 100.60 with 0.8% fee -> net -1.0048 before uncertainty: entry refused (positive gross, negative net); a loss-making protective exit is never vetoed by cost', () => {
  const book = snap({ bids: [['100.6', '10']], asks: [['100', '10'], ['100.01', '10']] }); const f = fee('0.008');
  const exit = scenarioExit({ snapshot: book, q: '1', scenarioMid: M.div(M.add('100', '100.6'), '2', 9, 'HALF_UP'), spec: UNIT, fee: f, haircut: '1' }); assert.equal(exit.cashIn, '99.7952'); const cashOut = M.add('100', M.mul('100', '0.008')); assert.equal(cashOut, '100.8'); assert.equal(M.sub(exit.cashIn, cashOut), '-1.0048');
  const e = evaluateEntry({ snapshot: book, q: '1', spec: UNIT, fee: f, atr14: '0.01', structuralStop: '90', targetPrice: M.div(M.add('100', '100.6'), '2', 9, 'HALF_UP'), maxEntryLevel: '100' }); assert.equal(e.status, 'REFUSED'); assert.ok(e.reasons.includes('BUFFERED_REWARD_NEGATIVE'), e.reasons.join());
  const lv = liquidationValue({ snapshot: snap({ bids: [['80', '10']], asks: [['81', '1']] }), q: '1', spec: UNIT, fee: f }); assert.equal(lv.status, 'OK'); assert.equal(lv.cashIn, '79.36', 'a protective exit at a loss is valued honestly and permitted (cost governs NEW risk only)');
});

test('C09. second price-bound oracle: q=1, ask 100, allowed limit 100.3, exit bid 100.4, 0.1% both legs -> book estimate +0.1996 but permitted-limit net -0.1007: refuse; full q plus fee at the limit fits the funds; the limit cannot increase after reservation', async () => {
  const book = snap({ bids: [['100.4', '10']], asks: [['100', '10']] }); const f = fee('0.001');
  const e = evaluateEntry({ snapshot: book, q: '1', spec: UNIT, fee: f, atr14: '4', structuralStop: '95', targetPrice: '100.2', maxEntryLevel: '100.3' }); assert.equal(e.entryLimitPrice, '100.3'); assert.equal(e.capped, true); assert.equal(e.entryBookEstimate.cashOut, '100.1'); assert.equal(M.sub(e.scenarioExitCashIn, e.entryBookEstimate.cashOut), '0.1996', 'observed-book estimate'); assert.equal(e.scenarioNetProfit, '-0.1007', 'permitted-price bound'); assert.equal(e.status, 'REFUSED'); assert.equal(e.entryCashOut, '100.4003');
  const a = await paperAccount(); await a.append([a.F.hypothesis('d1'), a.F.decision('d1', { sizing: { q: '1', entryLimitPrice: '100.3', entryCashOut: '100.4003', riskUsd: '4', bufferedScenarioNetProfit: '1' } }), a.F.reserve('r1', 'd1', { cashReserved: '100.4003' }), a.F.position('p1', 'd1', { structuralStop: '95', targetPrice: '110', atr14: '3', requestedQty: '1' }), a.F.pin()]);
  await assert.rejects(a.append(a.F.intent('o1', 'p1', 'r1', { qty: '1', limitPrice: '100.4', protection: { ordertype: 'stop-loss', trigger: 'last', price: '95' } })), (err) => err.detail?.code === 'LIMIT_ABOVE_DECISION', 'the limit cannot rise above the recorded decision'); await a.append(a.F.intent('o1', 'p1', 'r1', { qty: '1', limitPrice: '100.2', protection: { ordertype: 'stop-loss', trigger: 'last', price: '95' } }));
});

test('C02/C03/C04. buffered reward exactly zero refuses and just above passes only with every gate; size-specific costs on one book (small vs large, depth exhaustion, lot / minimum rules, base fees); spread and slippage attributed once; a mid target is never an executable bid; the stop-gap stress is a scenario', () => {
  const book = snap({ bids: [['100', '2'], ['99.9', '2'], ['99', '50']], asks: [['100.2', '1'], ['100.4', '1'], ['101', '50']] }); const f = fee('0');
  const small = evaluateEntry({ snapshot: book, q: '1', spec: UNIT, fee: f, atr14: '0.1', structuralStop: '99.5', targetPrice: '104', maxEntryLevel: null }); const large = evaluateEntry({ snapshot: book, q: '3', spec: UNIT, fee: f, atr14: '0.1', structuralStop: '99.5', targetPrice: '104', maxEntryLevel: null });
  assert.equal(small.entryBookEstimate.avgPrice, '100.2'); assert.equal(large.entryBookEstimate.avgPrice, '100.53333334', 'a small-order estimate cannot price a large order'); assert.ok(M.gt(large.entryLimitPrice, small.entryLimitPrice));
  assert.equal(evaluateEntry({ snapshot: book, q: '60', spec: UNIT, fee: f, atr14: '0.1', structuralStop: '99.5', targetPrice: '104', maxEntryLevel: null }).reasons[0], 'ENTRY_DEPTH_INSUFFICIENT');
  assert.equal(evaluateEntry({ snapshot: book, q: '0.4', spec: UNIT, fee: f, atr14: '0.1', structuralStop: '99.5', targetPrice: '104', maxEntryLevel: null }).reasons[0], 'SIZE_NOT_LEGAL'); assert.equal(evaluateEntry({ snapshot: book, q: '1.000000001', spec: UNIT, fee: f, atr14: '0.1', structuralStop: '99.5', targetPrice: '104', maxEntryLevel: null }).reasons[0], 'SIZE_NOT_LEGAL');
  assert.equal(small.attribution.spread, '0.2'); assert.equal(small.attribution.slippage, '0'); assert.ok(/never deducted twice/.test(small.attribution.note));
  const mid = evaluateEntry({ snapshot: book, q: '1', spec: UNIT, fee: f, atr14: '0.1', structuralStop: '99.5', targetPrice: '100.1', maxEntryLevel: null }); assert.ok(M.lt(mid.scenarioExitCashIn, '100.1'), 'the target mid is shifted onto BIDS with a 50% haircut, never sold at the mid');
  assert.equal(stopStressMid({ stop: '99.5', atr14: '0.1', spread: '0.2', tick: '0.01' }), '99.1', 'max(0.5 ATR, 2 spread, 2 tick) = 0.4 below the stop'); assert.ok(M.isPositive(small.scenarioStressedLoss)); assert.equal(small.expectancyState, 'UNCALIBRATED');
  // exactly-zero buffered reward refuses; a hair above passes the cost gate
  const flat = snap({ bids: [['100', '100']], asks: [['100', '100']] }); void flat;
  const base = fee('0', { roundingQuantum: '0.000001' }); const z = (target) => evaluateEntry({ snapshot: snap({ bids: [['100', '100']], asks: [['100.01', '100']] }), q: '1', spec: UNIT, fee: base, atr14: '0.05', structuralStop: '99', targetPrice: target, maxEntryLevel: null });
  let zero = null; for (const tgt of ['100.06', '100.07', '100.08', '100.09', '100.1', '100.11', '100.12']) { const r = z(tgt); if (M.isZero(r.bufferedScenarioNetProfit)) zero = r; } assert.ok(zero, 'a target exists where the buffered reward is exactly zero'); assert.ok(zero.reasons.includes('BUFFERED_REWARD_ZERO'));
  const baseFee = fee('0.001', { currency: 'BASE' }); const bf = evaluateEntry({ snapshot: book, q: '1', spec: UNIT, fee: baseFee, atr14: '0.1', structuralStop: '99.5', targetPrice: '104', maxEntryLevel: null }); assert.equal(bf.netBase, '0.999', 'fee-in-base reduces the sellable inventory');
});

test('C11. fee scope witnesses: two USD 50 fills at 0.01% rounded UP to 0.01 PER_EXECUTION cost 0.02 (one order-level rounding would under-reserve 0.01); USD 100.01 cannot authorize the USD 100 order; ORDER_TOTAL charges once; an unqualified per-execution bound refuses; an actual fee mismatch is recorded as truth', () => {
  const per = fee('0.0001', { roundingQuantum: '0.01', scope: 'PER_EXECUTION', maxExecutionsBound: 2, boundSource: 'synthetic witness' }); const tot = fee('0.0001', { roundingQuantum: '0.01', scope: 'ORDER_TOTAL' });
  assert.equal(feesForExecutions(per, [{ quote: '50' }, { quote: '50' }]).total, '0.02'); assert.equal(feesForExecutions(tot, [{ quote: '50' }, { quote: '50' }]).total, '0.01');
  assert.equal(worstFeeBound(per, '100').fee, '0.02'); assert.equal(worstFeeBound(tot, '100').fee, '0.01'); assert.ok(M.gt(M.add('100', worstFeeBound(per, '100').fee), '100.01'), 'funds of 100.01 cannot authorize the order under the per-execution contract');
  assert.equal(worstFeeBound(fee('0.0001', { roundingQuantum: '0.01', scope: 'PER_EXECUTION' }), '100').reason, 'FEE_BOUND_UNQUALIFIED');
  const mm = feeMismatch(tot, [{ quote: '50' }, { quote: '50' }], '0.02'); assert.equal(mm.mismatch, true); assert.equal(mm.delta, '0.01'); assert.equal(mm.overcharged, true);
});

test('C06/C10. USD 500 including fees: concurrent cash / risk / slot reservations cannot overdraw; the largest legal lot is searched boundedly with explicit binding constraints; sample risks USD 5 / 10 / 7.50; ranking is deterministic at admissible size; no liquidation to fund a new candidate', async () => {
  const a = await paperAccount(); const s = await a.state(); const budget = riskBudgetFor({ state: s, limits: SAMPLE_LIMITS, clusterId: 'BTC' }); assert.equal(budget.budget, '5'); assert.equal(budget.caps.aggregateRisk, '10'); assert.equal(budget.caps.clusterRisk, '7.5'); assert.equal(budget.cash, '500');
  const book = snap({ bids: [['100', '1000']], asks: [['100.01', '1000']] }); const f = fee('0.008', { roundingQuantum: '0.01' });
  const found = sizeSearch({ snapshot: book, spec: UNIT, fee: f, atr14: '0.5', structuralStop: '99.5', targetPrice: '110', maxEntryLevel: null, cashAvailable: '500', riskBudget: '5' }); assert.equal(found.status, 'OK'); assert.ok(M.lte(found.evaluation.entryCashOut, '500')); assert.ok(M.lte(found.evaluation.scenarioStressedLoss, '5')); assert.ok(found.binding.length >= 1, `binding: ${found.binding}`); assert.ok(found.iterations <= 40);
  const bigger = sizeSearch({ snapshot: book, spec: UNIT, fee: f, atr14: '0.5', structuralStop: '99.5', targetPrice: '110', maxEntryLevel: null, cashAvailable: '500', riskBudget: '50' }); assert.ok(M.gt(bigger.q, found.q), 'risk budget binds before cash at USD 5'); assert.ok(bigger.binding.includes('CASH'));
  const admit = admitCandidate({ state: s, candidate: { assetId: 'BTC', clusterId: 'BTC', entryCashOut: '400', riskUsd: '5', decisionId: 'd' }, limits: SAMPLE_LIMITS }); assert.equal(admit.ok, true);
  assert.ok(admitCandidate({ state: s, candidate: { assetId: 'BTC', clusterId: 'BTC', entryCashOut: '500.01', riskUsd: '5' }, limits: SAMPLE_LIMITS }).reasons.includes('CASH_INSUFFICIENT')); assert.deepEqual(admitCandidate({ state: s, candidate: { assetId: 'BTC', clusterId: 'BTC', entryCashOut: '10', riskUsd: '5.01' }, limits: SAMPLE_LIMITS }).reasons, ['RISK_PER_POSITION']);
  assert.deepEqual(admitCandidate({ state: s, candidate: { assetId: 'BTC', clusterId: 'BTC', entryCashOut: '10', riskUsd: '2.51' }, limits: SAMPLE_LIMITS, lockLevel: 'SELECTIVE' }).reasons, ['RISK_PER_POSITION'], 'SELECTIVE halves per-entry risk'); assert.ok(admitCandidate({ state: s, candidate: { assetId: 'BTC', clusterId: 'BTC', entryCashOut: '10', riskUsd: '1' }, limits: SAMPLE_LIMITS, lockLevel: 'PROTECT' }).reasons.includes('GAIN_LOCK_PROTECT'));
  await a.append([a.F.hypothesis('d1'), a.F.decision('d1'), a.F.reserve('r1', 'd1', { cashReserved: '300', riskReserved: '5' })]); const s2 = await a.state(); const r2 = admitCandidate({ state: s2, candidate: { assetId: 'ETH', clusterId: 'ETH', entryCashOut: '201', riskUsd: '5' }, limits: SAMPLE_LIMITS }); assert.ok(r2.reasons.includes('CASH_INSUFFICIENT'), 'the pending reservation consumes cash; no liquidation funds the newcomer');
  const ranked = rankCandidates([{ assetId: 'ZZZ', rewardRiskRatio: '2', costBps: '10', firstKnownTs: 5 }, { assetId: 'AAA', rewardRiskRatio: '2', costBps: '10', firstKnownTs: 5 }, { assetId: 'BBB', rewardRiskRatio: '3', costBps: '50', firstKnownTs: 9 }, { assetId: 'CCC', rewardRiskRatio: '2', costBps: '5', firstKnownTs: 9 }, { assetId: 'NUL', rewardRiskRatio: null, costBps: '1', firstKnownTs: 1 }]); assert.deepEqual(ranked.map((c) => c.assetId), ['BBB', 'CCC', 'AAA', 'ZZZ'], 'ratio desc, cost asc, first-known, asset id; unknown ratio refused');
});

test('C07. clusters: wrapped aliases share one underlying; correlation >= 0.70 over 60 complete synchronized 1m returns joins; insufficient history is one shared UNKNOWN_CORRELATION group that blocks additions through the cluster cap; one position per underlying', () => {
  const series = (f) => Array.from({ length: 60 }, (_, i) => ({ periodStartTs: T0 - (61 - i) * 60_000, r: f(i) })); const base = (i) => Math.sin(i / 3) * 0.01;
  const clusters = computeClusters({ BTC: series(base), ETH: series((i) => base(i) * 0.9 + 0.0001), SOL: series((i) => Math.cos(i / 2) * 0.01), NEW: series(base).slice(-30), WBTC: series(base) }, { asOfTs: T0 });
  assert.equal(clusters.clusterOf.BTC, clusters.clusterOf.ETH); assert.notEqual(clusters.clusterOf.BTC, clusters.clusterOf.SOL); assert.equal(clusters.clusterOf.NEW, 'UNKNOWN_CORRELATION'); assert.equal(clusters.clusterOf.WBTC, clusters.clusterOf.BTC); assert.deepEqual(clusters.unknown, ['NEW']); assert.equal(clusters.support.NEW, 30);
  const s = { performance: { riskPerformanceEquity: '500' }, valuation: { unknown: false }, reservations: { r1: { state: 'OPEN', assetId: 'ADA', clusterId: 'UNKNOWN_CORRELATION', riskReserved: '5', cashReserved: '100' } }, positions: {}, vetoes: [], cash: '500' };
  assert.ok(admitCandidate({ state: s, candidate: { assetId: 'NEW', clusterId: 'UNKNOWN_CORRELATION', entryCashOut: '50', riskUsd: '3' }, limits: SAMPLE_LIMITS }).reasons.includes('RISK_CLUSTER_UNKNOWN_CORRELATION'));
  const held = { ...s, reservations: {}, positions: { p: { state: 'OPEN', assetId: 'BTC', clusterId: 'cl-BTC', riskReserved: '2' } } }; assert.ok(admitCandidate({ state: held, candidate: { assetId: 'WBTC', clusterId: 'cl-BTC', entryCashOut: '50', riskUsd: '1' }, limits: SAMPLE_LIMITS }).reasons.includes('ONE_POSITION_PER_UNDERLYING'));
});

// ---- setups / features --------------------------------------------------------------------------------------------------------
function bars({ n = 61, endTs = T0, close = 100, step = 0, range = 1, spikeAt = null, spike = 5, lastRange = null } = {}) { const out = []; for (let i = 0; i < n; i += 1) { const c = close + step * i; const rg = lastRange !== null && i >= n - 5 ? lastRange : range; const hi = spikeAt === i ? c + spike : c + rg / 2; out.push({ periodStartTs: endTs - (n - i) * 60_000, periodEndTs: endTs - (n - i - 1) * 60_000, open: c, high: hi, low: c - rg / 2, close: c, volumeQuote: 1000, volumeBase: 10, closed: true }); } return out; }
const trade = (ts, side, price, qty, id) => ({ eventTs: ts, receiptTs: ts, side, price: String(price), qty: String(qty), quoteNotional: M.mul(String(price), String(qty)), nativeTradeId: String(id), fromSubscriptionSnapshot: false, feedEpoch: 1 });

test('J01-features. 61 contiguous complete bars are mandatory (gaps, provisional, 60 bars, future bars refuse); Wilder ATR14 / EMA seeds restart per block; H20 / L20 exclude nothing later than the reference; a confirmed swing high is the nearest resistance strictly above entry', () => {
  const b = bars(); const ind = indicatorBlock(b); assert.equal(ind.bars, 61); assert.equal(ind.trueRanges, 60); assert.ok(Math.abs(ind.atr14 - 1) < 1e-9, 'constant range 1 -> ATR 1'); assert.ok(Math.abs(ind.ema5 - 100) < 1e-9); assert.equal(ind.h20, 100.5); assert.equal(ind.l20, 99.5);
  assert.equal(validateBarBlock(b.slice(1)).reason, 'BARS_60_OF_61'); const gap = b.map((x, i) => (i === 30 ? { ...x, periodStartTs: x.periodStartTs + 1 } : x)); assert.match(validateBarBlock(gap).reason, /GAP|NOT_COMPLETE/); assert.equal(validateBarBlock(b.map((x, i) => (i === 60 ? { ...x, closed: false } : x))).reason, 'BAR_60_NOT_COMPLETE'); assert.equal(validateBarBlock(b, { referenceTs: T0 - 1 }).reason, 'BAR_60_AFTER_REFERENCE');
  const trending = indicatorBlock(bars({ step: 0.1 })); assert.ok(trending.ema5 > trending.ema20); assert.ok(trending.prior20Return > 0);
  const spiked = bars({ spikeAt: 50 }); const res = nearestResistanceAbove(spiked, 101); assert.equal(res.price, 105); assert.equal(nearestResistanceAbove(spiked, 106), null, 'no invented resistance above'); assert.equal(nearestResistanceAbove(bars({ spikeAt: 59 }), 101), null, 'a swing needs two closed bars on either side');
  const c1 = createFeatureCache(); const k = { blockDigest: ind.blockDigest, referenceTs: ind.referenceTs }; c1.get(k, () => 1); assert.equal(c1.get(k, () => 2).hit, true, 'an unchanged block is not recomputed'); assert.equal(c1.get({ ...k, blockDigest: 'other' }, () => 3).hit, false, 'a 62nd bar changes the block and the seeds');
});

test('J12/J01-flow. incremental flow tracker equals the batch calculation on values / identities / decisions: half-open endpoints, duplicate native ids, quiet-time expiry, unknown side fraction, RV60 completed-minute law with 20 baseline windows and zero-median UNKNOWN', () => {
  const trades = []; let id = 0; for (let m = 0; m < 25; m += 1) for (let k = 0; k < 4; k += 1) trades.push(trade(T0 - (25 - m) * 60_000 + k * 15_000, k % 2 ? 'sell' : 'buy', 100, 1 + (m === 24 ? 3 : 0), ++id));
  const tracker = createFlowTracker({ retentionMs: 30 * 60_000 }); for (const t of trades) tracker.add(t); tracker.add(trades[10]); assert.equal(tracker.status().duplicatesDropped, 1);
  const cov = { continuous: true, startTs: T0 - 26 * 60_000, endTs: T0 }; const D = T0 + 5_000;
  const inc = tracker.rv60(D, cov); const batch = relativeVolume60(dedupTrades(trades).trades, D, cov); assert.deepEqual(inc, batch); assert.equal(inc.state, 'KNOWN'); assert.equal(inc.E, T0); assert.equal(inc.rv60, 4, 'last complete minute 4x the median baseline'); assert.equal(inc.completedMinuteDelayMs, 5000);
  assert.equal(relativeVolume60(trades, D, { ...cov, startTs: T0 - 10 * 60_000 }).reason, 'COVERAGE_INCOMPLETE'); assert.equal(relativeVolume60([], D, cov).reason, 'ZERO_MEDIAN');
  const fi = tracker.fi(T0 - 60_000, T0); assert.deepEqual(fi, flowImbalance(trades, T0 - 60_000, T0)); assert.equal(fi.state, 'KNOWN'); assert.equal(fi.count, 4, 'a trade exactly at the end boundary belongs to the NEXT window');
  const unknownSide = [...trades.slice(-4), trade(T0 - 1000, 'unknown', 100, 100, 999)]; const fu = flowImbalance(unknownSide, T0 - 60_000, T0); assert.equal(fu.state, 'UNKNOWN'); assert.equal(fu.reason, 'CLASSIFIED_BELOW_95PCT'); assert.ok(fu.classifiedFraction < 0.95);
  tracker.advance(T0 + 40 * 60_000); assert.equal(tracker.status().trades, 0, 'quiet time expires trades without a new trade'); assert.equal(tracker.fi(T0 - 60_000, T0).state, 'UNKNOWN');
});

test('J01-setups. RANGE_IGNITION: one lawful positive and each independently failing clause; the persistence law needs 3 distinct books over >= 2s with no intervening breach; an over-cap burst is not 3 proofs; 10s expiry; cooldown and reset before a new crossing', () => {
  const b = bars(); const ind = indicatorBlock(b); const fastGood = (over = {}) => ({ mid: '100.7', fi15: { state: 'KNOWN', fi: 0.3 }, fi60: { state: 'KNOWN', fi: 0.1 }, rv60: { state: 'KNOWN', rv60: 2.5 }, coverage: { continuous: true, startTs: T0 - 600_000, endTs: T0 }, decisionTs: T0, bookAgeMs: 200, crcVerified: true, ...over });
  const frozen = freezeReferences({ setupId: 'RANGE_IGNITION', ind, spec: SPEC, fast: fastGood(), triggerTs: T0 }); assert.equal(frozen.triggerLevel, '100.6', 'H20 + max(1 tick, 0.10 ATR) = 100.5 + 0.1'); assert.equal(frozen.structuralStop, '99.4'); assert.equal(frozen.scenarioRaw, '101.5');
  const ok = evaluateSetup({ setupId: 'RANGE_IGNITION', frozen, ind, fast: fastGood(), bars: b, entry: '100.7', decisionTs: T0 }); assert.equal(ok.state, 'ELIGIBLE', ok.refused.join()); assert.equal(ok.scenario.target, '101.5'); assert.equal(ok.calibrationState, 'UNVALIDATED_HYPOTHESIS');
  const fails = [['MID_ABOVE_TRIGGER', { mid: '100.5' }], ['EXTENSION_CAP', { mid: '101.3' }], ['FI15', { fi15: { state: 'KNOWN', fi: 0.19 } }], ['FI60_POSITIVE', { fi60: { state: 'KNOWN', fi: 0 } }], ['RV60', { rv60: { state: 'KNOWN', rv60: 1.99 } }], ['COVERAGE_60S', { coverage: { continuous: true, startTs: T0 - 59_000, endTs: T0 } }], ['BOOK_FRESH', { bookAgeMs: 1001 }], ['BOOK_FRESH', { crcVerified: null }]];
  for (const [clause, over] of fails) { const r = evaluateSetup({ setupId: 'RANGE_IGNITION', frozen, ind, fast: fastGood(over), bars: b, entry: '100.7', decisionTs: T0 }); assert.equal(r.state, 'REFUSED', clause); assert.deepEqual(r.refused, [clause], clause); }
  const needs = evaluateSetup({ setupId: 'RANGE_IGNITION', frozen, ind, fast: fastGood({ rv60: { state: 'UNKNOWN', rv60: null, reason: 'ZERO_MEDIAN' } }), bars: b, entry: '100.7', decisionTs: T0 }); assert.equal(needs.state, 'NEEDS_DATA');
  const wb = bars({ range: 0.5, lastRange: 4 }); const wi = indicatorBlock(wb); const wide = freezeReferences({ setupId: 'RANGE_IGNITION', ind: wi, spec: SPEC, fast: fastGood(), triggerTs: T0 }); const comp = evaluateSetup({ setupId: 'RANGE_IGNITION', frozen: wide, ind: wi, fast: fastGood({ mid: '102.3' }), bars: wb, entry: '102.3', decisionTs: T0 }); assert.ok(comp.refused.includes('COMPRESSION_5BAR'), `envelope ${wide.envelope5} vs 2xATR ${wide.atr14}`);
  const c = createConfirmation({ level: '100.6', triggerTs: T0 }); assert.equal(c.observe('100.7', T0 + 100, 1), 'PENDING'); assert.equal(c.observe('100.7', T0 + 100, 1), 'PENDING', 'the same sequence is one observation'); assert.equal(c.observe('100.8', T0 + 500, 2), 'PENDING'); assert.equal(c.observe('100.9', T0 + 900, 3), 'PENDING', '3 books within 900ms are not 2s'); assert.equal(c.observe('100.55', T0 + 1200, 4), 'RESET', 'a breach below the FULL level resets'); assert.equal(c.observe('100.7', T0 + 1300, 5), 'PENDING'); assert.equal(c.observe('100.7', T0 + 2400, 6), 'PENDING'); assert.equal(c.observe('100.7', T0 + 3400, 7), 'CONFIRMED');
  const c2 = createConfirmation({ level: '100.6', triggerTs: T0 }); assert.equal(c2.observe('100.7', T0 + 10_001, 1), 'EXPIRED', '10s without a completed confirmation expires the proposal');
  const ep = createEpisodeTracker({ assetId: 'BTC', setupId: 'RANGE_IGNITION' }); assert.equal(ep.observeMid('100.7', '100.6', T0).crossing, true); assert.equal(ep.observeMid('100.9', '100.6', T0 + 10).crossing, false, 'the same crossing is not a new setup'); ep.decide('ENTRY_REFUSED'); assert.equal(ep.observeMid('100.9', '100.6', T0 + 20).crossing, false, 'no new crossing without a reset below the level'); ep.observeMid('100.5', '100.6', T0 + 30); assert.equal(ep.observeMid('100.7', '100.6', T0 + 40).crossing, true); ep.closed(T0 + 50); ep.observeMid('100.5', '100.6', T0 + 60); assert.equal(ep.observeMid('100.7', '100.6', T0 + 70).refused, 'COOLDOWN'); assert.equal(ep.observeMid('100.7', '100.6', T0 + 50 + REFERENCE.cooldownMs + 1).crossing, false, 'still above: needs a reset first');
});

test('J01-setups. TREND_PULLBACK, ABSORPTION_RECLAIM and CATALYST_TRANSMISSION: lawful positives and independently failing structural clauses; IV needs a primary-confirmed occurred event with an UPWARD_PRESSURE mechanism and a pre-event P0', () => {
  const tb = bars({ step: 0.05, spikeAt: 55, spike: 1 }); const ti = indicatorBlock(tb); const fast = (over = {}) => ({ mid: String(ti.last2High + 0.2), fi15: { state: 'KNOWN', fi: 0.3 }, fi60: { state: 'KNOWN', fi: 0.1 }, rv60: { state: 'KNOWN', rv60: 1.6 }, coverage: { continuous: true, startTs: T0 - 600_000, endTs: T0 }, decisionTs: T0, bookAgeMs: 100, crcVerified: true, ...over });
  const tf = freezeReferences({ setupId: 'TREND_PULLBACK_CONTINUATION', ind: ti, spec: SPEC, fast: fast(), triggerTs: T0 }); const tr = evaluateSetup({ setupId: 'TREND_PULLBACK_CONTINUATION', frozen: tf, ind: ti, fast: fast(), bars: tb, entry: fast().mid, decisionTs: T0 }); assert.equal(tr.state, 'ELIGIBLE', tr.refused.join()); assert.equal(tf.prior20HighBarsFromEnd, 5);
  const flatBars = bars({ step: -0.05 }); const fi2 = indicatorBlock(flatBars); const ff = freezeReferences({ setupId: 'TREND_PULLBACK_CONTINUATION', ind: fi2, spec: SPEC, fast: fast(), triggerTs: T0 }); const fr = evaluateSetup({ setupId: 'TREND_PULLBACK_CONTINUATION', frozen: ff, ind: fi2, fast: fast({ mid: String(fi2.last2High + 0.2) }), bars: flatBars, entry: String(fi2.last2High + 0.2), decisionTs: T0 }); assert.ok(fr.refused.includes('EMA5_ABOVE_EMA20')); assert.ok(fr.refused.includes('PRIOR20_RETURN_POSITIVE'));
  const ab = bars(); const ai = indicatorBlock(ab); const afast = (over = {}) => ({ mid: '100.2', vwap60: '100.1', priorFi: { state: 'KNOWN', fi: -0.3 }, priorMidChange: '0.05', priorMedianDepth: '5000', priorDepthSamples: 31, priorLow60: '99.7', reclaimFi: { state: 'KNOWN', fi: 0.25 }, depth10bps: '4500', fi15: { state: 'KNOWN', fi: 0.25 }, fi60: { state: 'KNOWN', fi: 0.05 }, coverage: { continuous: true, startTs: T0 - 600_000, endTs: T0 }, decisionTs: T0, bookAgeMs: 100, crcVerified: true, ...over });
  const af = freezeReferences({ setupId: 'ABSORPTION_RECLAIM', ind: ai, spec: SPEC, fast: afast(), triggerTs: T0 }); assert.equal(af.triggerLevel, '100.2'); assert.equal(af.structuralStop, '99.6'); const ar = evaluateSetup({ setupId: 'ABSORPTION_RECLAIM', frozen: af, ind: ai, fast: afast(), bars: ab, entry: '100.2', decisionTs: T0 }); assert.equal(ar.state, 'ELIGIBLE', ar.refused.join()); assert.equal(ar.maxEntryLevel, null, 'II has no extra level cap');
  for (const [clause, over] of [['PRIOR_FI_ABSORBED', { priorFi: { state: 'KNOWN', fi: -0.1 } }], ['PRIOR_MID_RESPONSE_SMALL', { priorMidChange: '0.5' }], ['PRIOR_MID_RESPONSE_SMALL', { priorMidChange: '-0.5' }], ['BASELINE_DEPTH_SUPPORT', { priorDepthSamples: 29 }], ['RECLAIM_FI15', { reclaimFi: { state: 'KNOWN', fi: 0.1 } }], ['DEPTH_HOLDS_80PCT_OF_BASELINE', { depth10bps: '3999' }]]) { const f2 = freezeReferences({ setupId: 'ABSORPTION_RECLAIM', ind: ai, spec: SPEC, fast: afast(over), triggerTs: T0 }); const r = evaluateSetup({ setupId: 'ABSORPTION_RECLAIM', frozen: f2, ind: ai, fast: afast(over), bars: ab, entry: '100.2', decisionTs: T0 }); assert.deepEqual(r.refused, [clause], clause); }
  const event = { eventId: 'claim-1', knownAtTs: T0 - 60_000, occurred: true, primaryConfirmed: true, mechanismDirection: 'UPWARD_PRESSURE', mechanismCitesEvent: true, p0: '100', p0Source: 'PRE_EVENT_SNAPSHOT', taxonomy: 'LISTING_OR_INTEGRATION', caseId: 'c', analysisId: 'a' }; const cfast = (over = {}) => ({ mid: '100.2', fi15: { state: 'KNOWN', fi: 0.3 }, fi60: { state: 'KNOWN', fi: 0.1 }, rv60: { state: 'KNOWN', rv60: 1.6 }, coverage: { continuous: true, startTs: T0 - 600_000, endTs: T0 }, decisionTs: T0, bookAgeMs: 100, crcVerified: true, ...over });
  const cf = freezeReferences({ setupId: 'CATALYST_TRANSMISSION', ind: ai, spec: SPEC, fast: cfast(), event, triggerTs: T0 }); assert.equal(cf.triggerLevel, '100.1'); assert.equal(cf.structuralStop, '99.4', 'min(P0, pre-event last5 low) minus the buffer: min(100, 99.5) - 0.1'); const cr = evaluateSetup({ setupId: 'CATALYST_TRANSMISSION', frozen: cf, ind: ai, fast: cfast(), bars: ab, entry: '100.2', decisionTs: T0, event }); assert.equal(cr.state, 'ELIGIBLE', cr.refused.join()); assert.equal(cr.maxEntryLevel, '101');
  for (const [clause, ev] of [['EVENT_PRIMARY_CONFIRMED', { ...event, primaryConfirmed: false }], ['EVENT_KNOWN_WITHIN_10M', { ...event, knownAtTs: T0 - 601_000 }], ['EVENT_OCCURRED_NOT_SCHEDULED', { ...event, occurred: false }], ['MECHANISM_UPWARD_PRESSURE_CITED', { ...event, mechanismDirection: 'MIXED' }], ['P0_FROM_PRE_EVENT_SNAPSHOT', { ...event, p0Source: 'LATER_CANDLE_LOW' }]]) { const fz = freezeReferences({ setupId: 'CATALYST_TRANSMISSION', ind: ai, spec: SPEC, fast: cfast(), event: ev, triggerTs: T0 }); const r = evaluateSetup({ setupId: 'CATALYST_TRANSMISSION', frozen: fz, ind: ai, fast: cfast(), bars: ab, entry: '100.2', decisionTs: T0, event: ev }); assert.deepEqual(r.refused, [clause], clause); }
  assert.equal(freezeReferences({ setupId: 'CATALYST_TRANSMISSION', ind: ai, spec: SPEC, fast: cfast(), event: null, triggerTs: T0 }), null, 'no pre-event price -> nothing to freeze (NEEDS_DATA upstream)');
});
