// JUDGE — arming / security / composition (A01-A10) against the REAL cockpit server, the real composition over a memory
// journal, the real CLI parser and command set, and the posture machine. No socket to any venue: every transport is a
// loopback double; credentials are SYNTHETIC test strings; nothing here can place an order.
import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync, readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { Readable } from 'node:stream';

const TEST_DATA = mkdtempSync(path.join(tmpdir(), 'cobra-judge-arm-'));
process.env.COBRA_DATA_DIR = TEST_DATA;
const PORT = 39600 + Math.floor(Math.random() * 300); process.env.PORT = String(PORT);
const PW = 'arming-test-owner-password-4410';
delete process.env.SERPENT_CONTROL_PASSWORD; delete process.env.DATABASE_URL; delete process.env.REPLIT_DEPLOYMENT; delete process.env.SERPENT_DURABLE_REQUIRED;
const { server, setJudgeRun } = await import('../ui/server.js');
const { composeJudge, initAccount, RUN_MODES } = await import('../judge/composition.js');
const { createMemoryJournal } = await import('../execution/journal.js');
const { loadJudgePolicy } = await import('../judge/policy.js');
const { prepareRelease, approveRelease, buildLiveAuthorization, createArmChallenge, verifyArmRequest, manifestError } = await import('../judge/arming.js');
const { writeApproval, readApproval, verifyOwnerIntent, ownerAuditFile, approvalsDir } = await import('../judge/owner.js');
const { parseArgs, runCli, FLAGS, USAGE } = await import('../bin/judge.js');
const { COMMANDS, MUTATING } = await import('../judge/commands.js');
const { KRAKEN_ENDPOINTS, FORBIDDEN_ENDPOINT_RE, keyFingerprint: kfOf } = await import('../execution/kraken-adapter.js').then(async (m) => ({ ...m, keyFingerprint: (await import('../execution/contract.js')).keyFingerprint }));
const { syncPosture, getEngineState, STATES } = await import('../state/machine.js');
const { PostureMachine, NotYetImplemented } = await import('../state/posture.js');
const { eventsFor, fakeClock, SAMPLE_LIMITS, SPEC, T0 } = await import('./helpers/judge.js');
const { makeEvent } = await import('../execution/contract.js');
const { atomicWriteJson } = await import('../lib/jsonl.js');

const BASE = `http://127.0.0.1:${PORT}`;
const post = (pathname, body, headers = {}) => fetch(BASE + pathname, { method: 'POST', headers: { 'content-type': 'application/json', ...headers }, body: JSON.stringify(body) });
const KEY = 'SYNTHETIC-TEST-KEY-not-real-arm'; const SECRET = 'kQH5HW/8p1uGOVjbgWA7FunAmGO8lsSUXNsu3eow76sz84Q18fWxnyRzBHCd3pd5nE9qa99HAZtuZuj6F1huXg==';
const PAPER_POLICY = path.resolve('judge/samples/policy.paper-reference.json');
const paperRaw = JSON.parse(readFileSync(PAPER_POLICY, 'utf8'));
const LIVE_POLICY = path.join(TEST_DATA, 'policy.live-test.json');
writeFileSync(LIVE_POLICY, JSON.stringify({ ...paperRaw, policyName: 'live-test-usd500', mode: 'LIVE', account: { accountId: 'live-t', initialCapital: '500', compounding: 'NONE' }, execution: { ...paperRaw.execution, adapter: 'KRAKEN' }, live: { allocationCeiling: '500', reinvestment: 'NONE', ownerLimits: null, armExpiryMs: 7 * 86_400_000, canaryMaxBuyConsiderationWithFees: '25', keyEnv: 'JUDGE_TEST_KRAKEN_KEY', secretEnv: 'JUDGE_TEST_KRAKEN_SECRET' }, authorityNote: 'LIVE test policy: owner limits and expiry are owner choices at arm time; nothing here is a performance promise.' }));
const LIVE = loadJudgePolicy(LIVE_POLICY); const PAPER = loadJudgePolicy(PAPER_POLICY);
const ENV = { JUDGE_TEST_KRAKEN_KEY: KEY, JUDGE_TEST_KRAKEN_SECRET: SECRET, SERPENT_CONTROL_PASSWORD: PW };
const CODE = 'c'.repeat(64);
function transportDouble(routes) { const calls = []; const fn = async (url, init) => { const u = new URL(url); const body = init?.body ? Object.fromEntries(new URLSearchParams(init.body)) : {}; calls.push({ path: u.pathname, body, headers: init?.headers ?? {} }); const r = routes[u.pathname]; if (!r) return { status: 404, ok: false, text: async () => 'not found' }; const out = typeof r === 'function' ? await r(body, calls.length) : r; return { status: out.status ?? 200, ok: (out.status ?? 200) < 400, text: async () => JSON.stringify(out.json ?? { error: [], result: out.result ?? {} }) }; }; fn.calls = calls; return fn; }
const KEYINFO = { apiKey: KEY, apiKeyName: 'trade-bot', permissions: ['Query Funds', 'Query Open Orders & Trades', 'Query Closed Orders & Trades', 'Create & Modify Orders', 'Cancel & Close Orders'], validUntil: 0, nonceWindow: 0 };
const liveRoutes = (over = {}) => ({ '/0/public/Time': (b, i) => ({ result: { unixtime: Math.floor(T0 / 1000) + i } }), '/0/private/GetApiKeyInfo': { result: KEYINFO }, '/0/private/Balance': { result: { ZUSD: '612.50' } }, '/0/private/OpenOrders': { result: { open: {} } }, '/0/private/TradesHistory': { result: { count: 0, trades: {} } }, '/0/private/Ledgers': { result: { ledger: {} } }, ...over });
async function liveJournal(accountId = 'live-t', clock = fakeClock()) { const journal = createMemoryJournal(); await initAccount({ journal, policy: LIVE.policy, policyDigest: LIVE.digest, mode: 'LIVE_UNARMED', ownerRef: 'owner-test', nowTs: clock.now(), accountId }); return journal; }
const pclockOf = (clock) => ({ now: clock.now, monotonic: clock.monotonic, observeWall: () => null, status: () => ({ trusted: true, kind: 'TEST' }), expired: (t) => clock.now() > t });
async function liveRun({ journal, clock = fakeClock(), transport = transportDouble(liveRoutes()), codeDigest = CODE, env = ENV, mode = 'LIVE_UNARMED', accountId = 'live-t', writeProjection = false } = {}) { return composeJudge({ policyFile: LIVE_POLICY, mode, accountId, env, journal, clock: pclockOf(clock), transport, specs: [SPEC], allowPrivate: () => true, allowOrders: () => false, writeProjection, codeDigest, log: () => {}, nominations: () => [] }); }
// a CANDIDATE release manifest + approval (the only inputs that can make a LIVE authorization)
function approvedRelease(nowTs = T0) { const m = prepareRelease({ codeTreeDigest: CODE, policy: LIVE.policy, policyDigest: LIVE.digest, evaluation: { paperAccountId: 'paper-x', forwardClosedTrades: 40, holdoutUntouched: true, netPnl: '12.5', drawdown: 0.03, feesAccounted: true, openPositions: 0, evaluationDigest: null, source: 'FORWARD_PAPER' }, tests: { criticalSuitesPassing: true, evidenceFile: 'logs/x' }, coverage: { dataFamilies: ['BOOK'], latencySamples: 100 }, acceptance: { independentReview: 'PASSED', reviewer: 'reviewer-x' }, proposedLimits: SAMPLE_LIMITS, nowTs }); assert.equal(m.state, 'CANDIDATE', m.blockers.join(',')); const a = approveRelease({ manifest: m, manifestDigest: m.manifestDigest, assessment: 'Forward paper sample of 40 closed trades; wide uncertainty remains (small sample, one regime); risk of net cost underestimation acknowledged; approval is an experiment-risk decision, not proof.', ownerRef: 'owner-test', sessionTag: 'tag00001', nowTs }); assert.equal(a.ok, true, a.reason); return { manifest: m, approval: a.approval }; }

test.after(() => { server.close(); rmSync(TEST_DATA, { recursive: true, force: true }); });

test('A01/A08. strict binding: the paper sample cannot arm (no live section, wrong kind); a LIVE run needs a LIVE policy; an authorization needs an APPROVED release whose policy / code digests match, owner limits, an expiry and a passed preflight; fixture-only, empty, negative or tampered evidence cannot become a candidate; approval cannot edit results', async () => {
  await assert.rejects(composeJudge({ policyFile: PAPER_POLICY, mode: 'LIVE_UNARMED', journal: createMemoryJournal(), env: ENV, log: () => {} }), /LIVE policy/);
  await assert.rejects(composeJudge({ policyFile: LIVE_POLICY, mode: 'PAPER', journal: createMemoryJournal(), env: ENV, log: () => {} }), /cannot run a paper/);
  const clock = fakeClock(); const journal = createMemoryJournal(); await initAccount({ journal, policy: PAPER.policy, policyDigest: PAPER.digest, mode: 'PAPER', ownerRef: 'o', nowTs: clock.now() });
  const paper = await composeJudge({ policyFile: PAPER_POLICY, mode: 'PAPER', journal, clock: pclockOf(clock), specs: [SPEC], writeProjection: false, log: () => {}, codeDigest: CODE, nominations: () => [] });
  assert.equal(paper.kind, 'PAPER'); assert.equal(paper.credentialsPresent, false); assert.deepEqual(await paper.arm({ ownerLimits: SAMPLE_LIMITS, expiresTs: clock.now() + 1000, allocationCeiling: '500', approval: null, ownerRef: 'o', releaseDigest: 'f'.repeat(64) }), { ok: false, reasons: ['NOT_A_LIVE_ACCOUNT'] }); await paper.stop();
  const { approval } = approvedRelease();
  const base = { accountId: 'live-t', releaseDigest: approval.releaseDigest, policyDigest: LIVE.digest, codeDigest: CODE, allocationCeiling: '500', reinvestment: 'NONE', ownerLimits: SAMPLE_LIMITS, keyFingerprint: 'kf-x', ownerRef: 'owner-test', expiresTs: T0 + 3_600_000, restrictionRevision: 1, nowTs: T0, verifiedAvailableUsd: '612.50', preflight: { ok: true }, approval };
  assert.equal(buildLiveAuthorization(base).ok, true);
  assert.deepEqual(buildLiveAuthorization({ ...base, ownerLimits: null }).reasons, ['OWNER_LIMITS_REQUIRED']); assert.equal(buildLiveAuthorization({ ...base, ownerLimits: null }).state, 'OWNER_LIMITS_REQUIRED');
  assert.deepEqual(buildLiveAuthorization({ ...base, expiresTs: T0 }).reasons, ['OWNER_EXPIRY_REQUIRED'], 'expiry equality is expired');
  assert.deepEqual(buildLiveAuthorization({ ...base, approval: null }).reasons, ['RELEASE_NOT_APPROVED']); assert.deepEqual(buildLiveAuthorization({ ...base, policyDigest: 'e'.repeat(64) }).reasons, ['POLICY_DIGEST_CHANGED_SINCE_APPROVAL']); assert.deepEqual(buildLiveAuthorization({ ...base, codeDigest: 'd'.repeat(64) }).reasons, ['CODE_DIGEST_CHANGED_SINCE_APPROVAL']);
  assert.deepEqual(buildLiveAuthorization({ ...base, preflight: { ok: false } }).reasons, ['LIVE_PREFLIGHT_NOT_PASSED']); assert.deepEqual(buildLiveAuthorization({ ...base, verifiedAvailableUsd: '100' }).reasons, ['ALLOCATION_EXCEEDS_VERIFIED_FUNDS']); assert.deepEqual(buildLiveAuthorization({ ...base, keyFingerprint: null }).reasons, ['KEY_FINGERPRINT_REQUIRED']);
  assert.deepEqual(buildLiveAuthorization({ ...base, canary: { pair: 'XBT/USD', maxBuyConsiderationWithFees: '25', maxDurationMs: 600_000, lossAcknowledged: false } }).reasons, ['CANARY_BOUNDS_REQUIRED']);
  // A08: evidence that cannot make a candidate
  const blocked = (evaluation, extra = {}) => prepareRelease({ codeTreeDigest: CODE, policy: LIVE.policy, policyDigest: LIVE.digest, evaluation, tests: { criticalSuitesPassing: true, evidenceFile: 'x' }, coverage: { dataFamilies: [], latencySamples: 0 }, acceptance: { independentReview: 'PASSED', reviewer: 'r' }, proposedLimits: SAMPLE_LIMITS, nowTs: T0, ...extra });
  assert.ok(blocked(null).blockers.includes('FORWARD_PAPER_EVIDENCE_MISSING')); assert.ok(blocked({ paperAccountId: 'p', forwardClosedTrades: 5, holdoutUntouched: true, netPnl: '1', drawdown: 0, feesAccounted: true, openPositions: 0, evaluationDigest: null, source: 'FIXTURE' }).blockers.includes('FIXTURE_ONLY_EVIDENCE_NOT_ACCEPTABLE'));
  assert.ok(blocked({ paperAccountId: 'p', forwardClosedTrades: 0, holdoutUntouched: true, netPnl: null, drawdown: 0, feesAccounted: true, openPositions: 0, evaluationDigest: null, source: 'FORWARD_PAPER' }).blockers.includes('EMPTY_TRADE_SAMPLE'));
  assert.ok(blocked({ paperAccountId: 'p', forwardClosedTrades: 9, holdoutUntouched: true, netPnl: '-3.1', drawdown: 0.1, feesAccounted: true, openPositions: 1, evaluationDigest: null, source: 'FORWARD_PAPER' }).blockers.includes('NEGATIVE_NET_EVALUATION_NOT_POSITIVE_EVIDENCE'));
  assert.ok(blocked({ paperAccountId: 'p', forwardClosedTrades: 9, holdoutUntouched: false, netPnl: '3', drawdown: 0.1, feesAccounted: true, openPositions: 0, evaluationDigest: null, source: 'FORWARD_PAPER' }).blockers.includes('HOLDOUT_NOT_UNTOUCHED'));
  const m0 = blocked(null); assert.equal(approveRelease({ manifest: m0, manifestDigest: m0.manifestDigest, assessment: 'x'.repeat(50) + ' uncertainty', ownerRef: 'o', sessionTag: 't', nowTs: T0 }).reason, 'MANIFEST_BLOCKED');
  const { manifest } = approvedRelease(); const tampered = { ...manifest, evaluation: { ...manifest.evaluation, netPnl: '9999' } }; assert.match(manifestError(tampered), /digest/); assert.equal(approveRelease({ manifest: tampered, manifestDigest: manifest.manifestDigest, assessment: 'x'.repeat(50) + ' uncertainty', ownerRef: 'o', sessionTag: 't', nowTs: T0 }).reason, 'MANIFEST_INVALID');
  assert.equal(approveRelease({ manifest, manifestDigest: 'a'.repeat(64), assessment: 'x'.repeat(50) + ' uncertainty', ownerRef: 'o', sessionTag: 't', nowTs: T0 }).reason, 'MANIFEST_DIGEST_MISMATCH'); assert.equal(approveRelease({ manifest, manifestDigest: manifest.manifestDigest, assessment: 'looks great, ship it, guaranteed edge confirmed by the fixtures', ownerRef: 'o', sessionTag: 't', nowTs: T0 }).reason, 'ASSESSMENT_MUST_STATE_UNCERTAINTY');
  const file = writeApproval(approvedRelease().approval); const raw = JSON.parse(readFileSync(file, 'utf8')); raw.assessment = 'edited after the fact: certain profit'; writeFileSync(file, JSON.stringify(raw)); assert.equal(readApproval(file).reason, 'APPROVAL_ASSESSMENT_TAMPERED');
});

test('A02. ARM_LIVE over the real cockpit: GET is 405; unauthenticated 401; cookie without CSRF 403; cross-origin 403; confirm without the fresh password 403; a wrong / reused / expired phrase is refused; a payload naming another account is refused; nothing arms without a passed preflight; then a bound challenge + fresh password + exact phrase commits ONE authorization whose reasons are empty; the secret never appears in any response or log', async () => {
  process.env.SERPENT_CONTROL_PASSWORD = PW;
  assert.equal((await fetch(`${BASE}/api/judge/arm`)).status, 405, 'no GET arm');
  const off = await (await fetch(`${BASE}/api/judge`)).json(); assert.equal(off.enabled, false); assert.equal(off.prominent, 'JUDGE OFF');
  assert.equal((await post('/api/judge/arm', { step: 'challenge' })).status, 401);
  const login = await post('/api/auth/login', { password: PW }); const cookie = login.headers.get('set-cookie').split(';')[0]; const csrf = (await login.json()).csrfToken; const authed = (extra = {}) => ({ cookie, 'X-Serpent-CSRF': csrf, ...extra });
  assert.equal((await post('/api/judge/arm', { step: 'challenge' }, { cookie })).status, 403, 'cookie without CSRF');
  assert.equal((await post('/api/judge/arm', { step: 'challenge' }, authed({ origin: 'https://evil.example' }))).status, 403, 'cross-origin');
  assert.equal((await (await post('/api/judge/arm', { step: 'challenge' }, authed())).json()).reason, 'JUDGE_NOT_RUNNING');
  const clock = fakeClock(); const journal = await liveJournal('live-t', clock); const transport = transportDouble(liveRoutes()); const run = await liveRun({ journal, clock, transport, writeProjection: true }); await run.start(); setJudgeRun(run);
  const { approval } = approvedRelease(); const file = writeApproval(approval);
  const view = await (await fetch(`${BASE}/api/judge`)).json(); assert.equal(view.enabled, true); assert.equal(view.running, true); assert.match(view.prominent, /^LIVE/); assert.ok(view.approvals.includes(path.basename(file))); assert.ok(!JSON.stringify(view).includes(SECRET) && !JSON.stringify(view).includes(KEY), 'no secret in the view');
  const body = { accountId: 'live-t', allocationCeiling: '500', approvalId: approval.approvalId };
  assert.equal((await (await post('/api/judge/arm', { ...body, step: 'challenge', accountId: 'paper-reference-usd500' }, authed())).json()).reason, 'ACCOUNT_BINDING_MISMATCH', 'the payload cannot substitute another account');
  assert.equal((await (await post('/api/judge/arm', { ...body, step: 'challenge', approvalId: 'apr-' + '0'.repeat(24) }, authed())).json()).reason, 'APPROVAL_UNKNOWN');
  const ch = await (await post('/api/judge/arm', { ...body, step: 'challenge' }, authed())).json(); assert.equal(ch.ok, true); assert.match(ch.phrase, /^ARM LIVE live-t 500 [0-9a-f]{8} [0-9A-F]{12}$/);
  assert.equal((await post('/api/judge/arm', { ...body, step: 'confirm', phrase: ch.phrase, expiresAt: '2026-09-09T12:00:00Z' }, authed())).status, 403, 'confirm without the fresh password');
  assert.equal((await post('/api/judge/arm', { ...body, step: 'confirm', phrase: ch.phrase, password: 'wrong', expiresAt: '2026-09-09T12:00:00Z' }, authed())).status, 403, 'a wrong fresh password');
  const wrong = await post('/api/judge/arm', { ...body, step: 'confirm', phrase: ch.phrase.replace(/.$/, 'Z'), password: PW, expiresAt: '2026-09-09T12:00:00Z' }, authed()); assert.equal(wrong.status, 403); assert.equal((await wrong.json()).reason, 'ARM_REFUSED');
  const reused = await post('/api/judge/arm', { ...body, step: 'confirm', phrase: ch.phrase, password: PW, expiresAt: '2026-09-09T12:00:00Z' }, authed()); assert.equal(reused.status, 403, 'one attempt per phrase: the old phrase is consumed');
  // a correct phrase without a passed preflight in this process: the composition refuses with named reasons
  const ch2 = await (await post('/api/judge/arm', { ...body, step: 'challenge' }, authed())).json(); const noPre = await post('/api/judge/arm', { ...body, step: 'confirm', phrase: ch2.phrase, password: PW, expiresAt: '2026-09-09T12:00:00Z', ownerLimits: SAMPLE_LIMITS }, authed()); assert.equal(noPre.status, 409); const npb = await noPre.json(); assert.ok(npb.reasons.includes('LIVE_PREFLIGHT_NOT_PASSED'), JSON.stringify(npb)); assert.ok(npb.reasons.includes('AVAILABLE_FUNDS_UNVERIFIED'));
  const pre = await run.preflight(); assert.equal(pre.ok, true, JSON.stringify(pre)); assert.equal(pre.checks.balance.quoteAvailable, '612.5', 'canonical lexeme'); assert.equal(transport.calls.filter((c) => /AddOrder|Cancel|Amend|Withdraw/i.test(c.path)).length, 0, 'preflight sends no order');
  const ch3 = await (await post('/api/judge/arm', { ...body, step: 'challenge' }, authed())).json();
  const noLimits = await post('/api/judge/arm', { ...body, step: 'confirm', phrase: ch3.phrase, password: PW, expiresAt: '2026-09-09T12:00:00Z' }, authed()); assert.equal((await noLimits.json()).state, 'OWNER_LIMITS_REQUIRED', 'the live policy carries no owner limits: they are an owner choice at arm time');
  const ch4 = await (await post('/api/judge/arm', { ...body, step: 'challenge' }, authed())).json();
  const ok = await post('/api/judge/arm', { ...body, step: 'confirm', phrase: ch4.phrase, password: PW, expiresAt: '2026-09-09T12:00:00Z', ownerLimits: SAMPLE_LIMITS }, authed()); const okb = await ok.json(); assert.equal(ok.status, 200, JSON.stringify(okb)); assert.deepEqual(okb.reasons, []); assert.match(okb.authorizationId, /^auth-/);
  const s = run.dispatcher.state(); assert.equal(s.authorization.kind, 'LIVE_ARM'); assert.equal(s.authorization.expiresTs, Date.parse('2026-09-09T12:00:00Z')); assert.equal(s.authorization.keyFingerprint, kfOf(KEY)); assert.equal(s.mode, 'LIVE_UNARMED', 'an authorization is not yet the armed mode: the run transitions after reconciliation + preflight on start');
  const again = await post('/api/judge/arm', { ...body, step: 'confirm', phrase: ch4.phrase, password: PW, expiresAt: '2026-09-09T12:00:00Z', ownerLimits: SAMPLE_LIMITS }, authed()); assert.equal(again.status, 403, 'the phrase is consumed');
  const log = readFileSync(path.join(TEST_DATA, 'state', 'control_auth_log.jsonl'), 'utf8'); assert.ok(log.includes('ARM_LIVE_COMMITTED') && log.includes('ARM_AUTHENTICATED') && log.includes('ARM_REFUSED')); assert.ok(!log.includes(PW) && !log.includes(SECRET) && !log.includes(KEY), 'no secret in the audit');
  const proj = JSON.parse(readFileSync(path.join(TEST_DATA, 'execution', 'projection.json'), 'utf8')); assert.equal(proj.authorization.active, true); assert.ok(!JSON.stringify(proj).includes(SECRET) && !JSON.stringify(proj).includes(KEY));
  await run.stop(); setJudgeRun(null);
});

test('A03/A04/A09/A10. keys alone never permit an entry (ARM_REQUIRED); a changed code / policy / key binding ENDS the old authorization on restart while exposure stays managed; an expired authorization (equality) refuses entries and grants no fresh window; a qualified restart with the SAME binding resumes the SAME unexpired authorization and can enter LIVE_ARMED; a PAPER account can never be opened LIVE; canary and ordinary authorizations are mutually exclusive', async () => {
  const clock = fakeClock(); const journal = await liveJournal('live-t', clock); const F = eventsFor('live-t', clock);
  const run = await liveRun({ journal, clock }); await run.start(); await run.preflight();
  const entry = () => run.dispatcher.commit([F.hypothesis('d1'), F.decision('d1'), F.reserve('r1', 'd1'), F.position('p1', 'd1'), F.pin(), F.intent('o1', 'p1', 'r1')]);
  await assert.rejects(entry(), (e) => ['MODE_FORBIDS_ENTRY', 'ARM_REQUIRED'].includes(e.detail?.code), 'credentials present, no authorization: no entry (LIVE_UNARMED forbids even the reservation)');
  const { approval } = approvedRelease(); const armed = await run.arm({ ownerLimits: SAMPLE_LIMITS, expiresTs: clock.now() + 3_600_000, allocationCeiling: '500', approval, ownerRef: 'owner-test', releaseDigest: approval.releaseDigest }); assert.equal(armed.ok, true, JSON.stringify(armed));
  const canary = await run.arm({ ownerLimits: SAMPLE_LIMITS, expiresTs: clock.now() + 600_000, allocationCeiling: '25', approval, ownerRef: 'owner-test', releaseDigest: approval.releaseDigest, canary: { pair: 'XBT/USD', maxBuyConsiderationWithFees: '25', maxDurationMs: 600_000, lossAcknowledged: true } }); assert.equal(canary.ok, false); assert.deepEqual(canary.reasons, ['AUTHORIZATION_EXCLUSIVE'], `A09: canary vs ordinary entries on one account ${JSON.stringify(canary)}`);
  await run.stop();
  // restart with a DIFFERENT code digest: the old authorization ends (BINDING_CHANGED); the account is still managed
  const run2 = await liveRun({ journal, clock, codeDigest: 'd'.repeat(64) }); const rep = await run2.start(); assert.deepEqual(rep.authorizationEnded, ['CODE_CHANGED']); assert.equal(run2.dispatcher.state().authorization.ended, true); assert.equal(run2.dispatcher.state().authorization.endedReason, 'BINDING_CHANGED');
  await assert.rejects(run2.dispatcher.commit([F.hypothesis('d2'), F.decision('d2'), F.reserve('r2', 'd2'), F.position('p2', 'd2'), F.pin(), F.intent('o2', 'p2', 'r2')]), (e) => ['MODE_FORBIDS_ENTRY', 'ARM_REQUIRED'].includes(e.detail?.code)); await run2.stop();
  // the SAME binding on a fresh unexpired authorization resumes and can transition to LIVE_ARMED after reconciliation
  clock.advance(5_000); const run3 = await liveRun({ journal, clock }); await run3.start(); await run3.preflight(); const armed3 = await run3.arm({ ownerLimits: SAMPLE_LIMITS, expiresTs: clock.now() + 3_600_000, allocationCeiling: '500', approval, ownerRef: 'owner-test', releaseDigest: approval.releaseDigest }); assert.equal(armed3.ok, true); await run3.stop();
  const run4 = await liveRun({ journal, clock }); const rep4 = await run4.start(); assert.equal(rep4.authorizationEnded, null, 'same code / policy / key: the same authorization resumes'); const a4 = run4.dispatcher.state().authorization; assert.equal(a4.authorizationId, armed3.authorizationId); assert.equal(a4.ended, false);
  await run4.dispatcher.commit(makeEvent({ type: 'MODE_TRANSITION', accountId: 'live-t', knownAtTs: clock.now(), payload: { from: 'LIVE_UNARMED', to: 'LIVE_ARMED', reason: 'test resume', authorizationId: a4.authorizationId, ts: clock.now() } })); assert.equal(run4.dispatcher.state().mode, 'LIVE_ARMED');
  // A10: expiry equality — at exactly expiresTs the authorization is inactive; the entry is refused; no fresh window is granted
  clock.setWall(a4.expiresTs); await assert.rejects(run4.dispatcher.commit([F.hypothesis('d3'), F.decision('d3'), F.reserve('r3', 'd3'), F.position('p3', 'd3'), F.pin(), F.intent('o3', 'p3', 'r3')]), (e) => ['ARM_EXPIRED', 'ARM_REQUIRED', 'MODE_FORBIDS_ENTRY'].includes(e.detail?.code), 'expiry equality: no entry'); assert.equal(run4.projection().authorization.active, false); await run4.stop();
  // a PAPER account can never be opened LIVE (never imports paper balances)
  const pj = createMemoryJournal(); await initAccount({ journal: pj, policy: PAPER.policy, policyDigest: PAPER.digest, mode: 'PAPER', ownerRef: 'o', nowTs: clock.now(), accountId: 'live-t' }); await assert.rejects(liveRun({ journal: pj, clock }), (e) => e.code === 'ACCOUNT_KIND_MISMATCH');
});

test('A05/A06. no withdrawal / margin / transfer endpoint exists in the allowlist; secrets never serialize (projection, inspect, audit); the disabled default: fly.js guards the composition behind JUDGE_ENABLED, the posture machine sees no projection and stays as before, STRIKE stays unreachable without a fresh projection; authority fences hold in BOTH directions (execution / watch / judge never import research writers; research never imports execution)', async () => {
  for (const [name, e] of Object.entries(KRAKEN_ENDPOINTS)) { assert.ok(!FORBIDDEN_ENDPOINT_RE.test(name) && !FORBIDDEN_ENDPOINT_RE.test(e.path), name); assert.ok(/^\/0\/(public|private)\//.test(e.path)); }
  const fly = readFileSync('fly.js', 'utf8'); assert.ok(fly.includes("if (process.env.JUDGE_ENABLED === 'true') {")); assert.ok(fly.includes('let judgeRun = null;')); assert.ok(fly.indexOf('let judgeRun = null;') < fly.indexOf('await runTape(')); assert.ok(!/JUDGE_ENABLED\s*=[^=]/.test(fly.split('\n').filter((l) => !/^\s*\/\//.test(l)).join('\n')), 'the opt-in is never assigned in code');
  rmSync(path.join(TEST_DATA, 'execution', 'projection.json'), { force: true }); const st = getEngineState(); assert.equal(st.execution, null); assert.ok([STATES.COILED, STATES.STALKING].includes(st.state));
  const m = new PostureMachine(); assert.throws(() => m.transition('STALKING', 'x') && m.transition('STRIKE', 'no projection'), NotYetImplemented); if (m.posture === 'STALKING') m.transition('COILED', 'undo');
  assert.throws(() => new PostureMachine().transition('STRIKE', 'stale projection', { execution: { state: 'STALE', exposure: true, posture: 'STRIKE' } }), Error);
  // both-direction fences over the tracked tree
  const { execSync } = await import('node:child_process'); const tracked = execSync("git ls-files '*.js'", { encoding: 'utf8' }).trim().split('\n');
  const imports = (f) => [...readFileSync(f, 'utf8').split('\n').filter((l) => !/^\s*\/\//.test(l)).join('\n').matchAll(/(?:import\s[^;]*?from\s*|import\s*\(\s*|export\s[^;]*?from\s*)['"]([^'"]+)['"]/g)].map((x) => x[1]);
  const resolveRel = (f, spec) => (spec.startsWith('.') ? path.normalize(path.join(path.dirname(f), spec)).replace(/\\/g, '/') : spec);
  const ALLOWED = { 'judge/intake.js': ['socrates/runtime.js', 'market-lab/store.js', 'market-lab/policy.js'], 'bin/judge.js': ['market-lab/time.js'] };
  for (const f of tracked.filter((x) => /^(execution|watch|judge)\//.test(x) || x === 'bin/judge.js')) for (const spec of imports(f)) { if (!spec.startsWith('.')) { assert.match(spec, /^node:/, `${f} -> ${spec}: no new dependency`); continue; } const t = resolveRel(f, spec); if (/^(market-lab|socrates|evidence|rumor2|research)\//.test(t)) assert.ok((ALLOWED[f] ?? []).includes(t), `${f} -> ${t} is not an allowlisted read-only research seam`); assert.ok(!/^(market-lab\/(service|owner|commands|providers)|socrates\/(commands|client|broker))/.test(t), `${f} -> ${t} reaches a research runtime / writer`); }
  for (const f of tracked.filter((x) => /^(market-lab|socrates|evidence|rumor2)\//.test(x))) { for (const spec of imports(f)) assert.ok(!/(execution|watch|judge)\//.test(resolveRel(f, spec)), `${f} -> ${spec} crosses into execution`); assert.ok(!/\b(composeJudge|createDispatcher|submitEntryWithProtection|createKrakenAdapter|closeResidual)\b/.test(readFileSync(f, 'utf8')), `${f} names an execution identifier`); }
  // secrets never serialize: inspect over the live policy with credentials present
  let out = ''; const code = await runCli(['inspect', '--policy', LIVE_POLICY], { env: ENV, stdout: (s) => { out += s; }, stderr: () => {}, cwd: process.cwd() }); assert.equal(code, 0); const ins = JSON.parse(out); assert.equal(ins.policy.live.credentialsPresent, true); assert.equal(ins.policy.live.keyEnv, 'JUDGE_TEST_KRAKEN_KEY'); assert.ok(!out.includes(SECRET) && !out.includes(KEY)); assert.equal(ins.authority, 'READ_ONLY');
  if (existsSync(ownerAuditFile())) assert.ok(!readFileSync(ownerAuditFile(), 'utf8').includes(PW));
});

test('A07. the projection is the ONE truth the cockpit, the CLI status and the posture machine read: a FRESH projection with an open position projects STRIKE through the legal path, an exiting one DIGESTING, a flat one walks back to COILED, a STALE one stands down with the exposure still named; /api/status and `judge status` show the same record', async () => {
  const file = path.join(TEST_DATA, 'execution', 'projection.json'); mkdirSync(path.dirname(file), { recursive: true });
  const proj = (over) => atomicWriteJson(file, { projectionVersion: 'judge-projection-1', ts: Date.now(), accountId: 'live-t', mode: 'LIVE_ARMED', runMode: 'LIVE_ARMED', accountKind: 'LIVE', adapter: 'KRAKEN', positions: [], pendingOrders: [], restrictions: [], posture: null, exposure: { openPositions: 0, pendingOrders: 0 }, ...over });
  proj({ positions: [{ positionId: 'p1', pair: 'XBT/USD', state: 'OPEN', base: '0.001', protection: 'ACTIVE' }], posture: 'STRIKE' }); let s = syncPosture(); assert.equal(s.machine.posture, STATES.STRIKE, JSON.stringify(s.transition)); assert.match(s.transition.cause, /execution STRIKE/); assert.equal(s.execution.exposure, true);
  const status = await (await fetch(`${BASE}/api/status`)).json(); assert.equal(status.posture, 'STRIKE'); assert.equal(status.execution.openPositions, 1); assert.ok(status.advisories.some((a) => /execution exposure: 1 open/.test(a)));
  proj({ positions: [{ positionId: 'p1', pair: 'XBT/USD', state: 'EXITING', base: '0.001', protection: 'ACTIVE' }], posture: 'DIGESTING' }); s = syncPosture(); assert.equal(s.machine.posture, STATES.DIGESTING);
  proj({ positions: [], posture: null }); s = syncPosture(); assert.equal(s.machine.posture, STATES.COILED); assert.match(s.transition.cause, /flat/);
  proj({ positions: [{ positionId: 'p1', pair: 'XBT/USD', state: 'OPEN', base: '0.001', protection: 'ACTIVE' }], posture: 'STRIKE' }); assert.equal(syncPosture().machine.posture, STATES.STRIKE);
  atomicWriteJson(file, { ...JSON.parse(readFileSync(file, 'utf8')), ts: Date.now() - 60_000 }); s = syncPosture(); assert.equal(s.machine.posture, STATES.RETREAT, 'a stale projection cannot hold STRIKE'); assert.match(s.transition.cause, /unreachable posture STRIKE found persisted \(execution projection STALE/); assert.ok(getEngineState().reasons.some((r) => /STALE .* recorded exposure/.test(r)), 'the exposure is still named, never a flat fiction');
  let out = ''; assert.equal(await runCli(['status'], { env: {}, stdout: (x) => { out += x; }, stderr: () => {} }), 0); const st = JSON.parse(out); assert.equal(st.projection.fresh, false); assert.equal(st.projection.positions[0].positionId, 'p1'); assert.equal(st.authority, 'READ_ONLY');
  rmSync(file, { force: true }); s = syncPosture(); assert.equal(s.machine.posture, STATES.COILED);
});

test('A02-cli/A08-cli. the CLI: closed commands, strict flags, no positional arguments, secrets never as flags; every mutating command needs owner intent (unconfigured -> refused, wrong password -> refused with a durable audit line, right password from stdin -> proceeds); prepare-release is read-only and BLOCKED without evidence; approve-release writes a durable approval; arm-live issues a bound short-lived phrase and refuses a wrong / reused one BEFORE touching any journal; PAPER init needs the database authority', async () => {
  assert.deepEqual([...COMMANDS], ['inspect', 'run-observe', 'init-paper', 'replay', 'run-paper', 'preflight-live', 'arm-live', 'run-live', 'canary-live', 'prepare-release', 'approve-release', 'cage', 'kill', 'veto', 'reconcile', 'status', 'evaluate', 'verify']); for (const c of COMMANDS) assert.ok(FLAGS[c], c); for (const m of MUTATING) assert.ok(COMMANDS.includes(m));
  assert.throws(() => parseArgs(['strike']), /unknown command/); assert.throws(() => parseArgs(['inspect', 'policy.json']), /positional/); assert.throws(() => parseArgs(['init-paper', '--policy', 'p', '--password', 'x']), /secrets never travel as flags/); assert.throws(() => parseArgs(['arm-live', '--policy', 'p', '--approval', 'a', '--allocation-ceiling', '500', '--confirm', 'true']), /expires-at/); assert.throws(() => parseArgs(['arm-live', '--policy', 'p', '--approval', 'a', '--allocation-ceiling', '500', '--confirm', 'true', '--expires-at', 'tomorrow']), /UTC instant/); assert.equal(parseArgs(['--help']).help, true); assert.ok(USAGE.includes('never from a flag'));
  const stdin = (text) => Readable.from([text]); const run = (argv, opts = {}) => { let out = ''; let err = ''; return runCli(argv, { env: {}, stdout: (s) => { out += s; }, stderr: (s) => { err += s; }, cwd: process.cwd(), ...opts }).then((code) => ({ code, out, err, json: () => JSON.parse(out) })); };
  const unconfigured = await run(['kill', '--owner-stdin', 'true'], { stdin: stdin(`${PW}\n`), env: {} }); assert.equal(unconfigured.code, 6); assert.match(unconfigured.err, /CONTROL_AUTH_UNCONFIGURED/);
  const wrong = await run(['kill', '--owner-stdin', 'true'], { stdin: stdin('nope\n'), env: { SERPENT_CONTROL_PASSWORD: PW } }); assert.equal(wrong.code, 6); assert.match(wrong.err, /AUTH_FAILED/); const audit = readFileSync(ownerAuditFile(), 'utf8'); assert.ok(audit.includes('"action":"kill"') && audit.includes('"ok":false')); assert.ok(!audit.includes('nope') && !audit.includes(PW));
  const noEnvPw = await run(['kill'], { env: { SERPENT_CONTROL_PASSWORD: PW } }); assert.equal(noEnvPw.code, 6); assert.match(noEnvPw.err, /OWNER_PASSWORD_REQUIRED/);
  const killed = await run(['kill', '--owner-stdin', 'true'], { stdin: stdin(`${PW}\n`), env: { SERPENT_CONTROL_PASSWORD: PW } }); assert.equal(killed.code, 0, killed.err); assert.equal(killed.json().controls.kill, true); assert.ok(readFileSync(ownerAuditFile(), 'utf8').includes('"action":"kill","ok":true'));
  const init = await run(['init-paper', '--policy', PAPER_POLICY, '--owner-stdin', 'true'], { stdin: stdin(`${PW}\n`), env: { SERPENT_CONTROL_PASSWORD: PW } }); assert.equal(init.code, 4, init.err); assert.match(init.err, /DB_REQUIRED/);
  const prep = await run(['prepare-release', '--policy', LIVE_POLICY, '--out', path.join(TEST_DATA, 'rel', 'manifest.json')]); assert.equal(prep.code, 0, prep.err); assert.equal(prep.json().state, 'BLOCKED'); assert.ok(prep.json().blockers.includes('FORWARD_PAPER_EVIDENCE_MISSING')); assert.equal(prep.json().authority, 'READ_ONLY_NO_TRADING_PERMISSION');
  const { manifest } = approvedRelease(); const mfile = path.join(TEST_DATA, 'rel', 'candidate.json'); atomicWriteJson(mfile, manifest, { pretty: true }); const afile = path.join(TEST_DATA, 'rel', 'assessment.txt'); writeFileSync(afile, 'Forward paper 40 trades; uncertainty is wide (one regime); the risk of cost underestimation is acknowledged; this approval is an experiment-risk decision.');
  const appr = await run(['approve-release', '--manifest', mfile, '--manifest-digest', manifest.manifestDigest, '--assessment', afile, '--owner-stdin', 'true'], { stdin: stdin(`${PW}\n`), env: { SERPENT_CONTROL_PASSWORD: PW } }); assert.equal(appr.code, 0, appr.err); const approvalFile = appr.json().file; assert.ok(existsSync(approvalFile)); assert.equal(appr.json().grants, 'ELIGIBILITY_FOR_PREFLIGHT_CANARY_ARM_CHECKS_ONLY');
  const badDigest = await run(['approve-release', '--manifest', mfile, '--manifest-digest', 'a'.repeat(64), '--assessment', afile, '--owner-stdin', 'true'], { stdin: stdin(`${PW}\n`), env: { SERPENT_CONTROL_PASSWORD: PW } }); assert.equal(badDigest.code, 6); assert.match(badDigest.err, /MANIFEST_DIGEST_MISMATCH/);
  const ch = await run(['arm-live', '--policy', LIVE_POLICY, '--approval', approvalFile, '--allocation-ceiling', '500', '--challenge', 'true', '--owner-stdin', 'true'], { stdin: stdin(`${PW}\n`), env: { SERPENT_CONTROL_PASSWORD: PW } }); assert.equal(ch.code, 0, ch.err); assert.match(ch.json().phrase, /^ARM LIVE live-t 500 /); assert.ok(!ch.out.includes(PW));
  const wrongPhrase = await run(['arm-live', '--policy', LIVE_POLICY, '--approval', approvalFile, '--allocation-ceiling', '500', '--confirm', 'true', '--expires-at', '2026-09-09T12:00:00Z', '--owner-stdin', 'true'], { stdin: stdin(`${PW}\nARM LIVE live-t 500 deadbeef 000000000000\n`), env: { SERPENT_CONTROL_PASSWORD: PW } }); assert.equal(wrongPhrase.code, 6); assert.match(wrongPhrase.err, /PHRASE_MISMATCH/);
  const consumed = await run(['arm-live', '--policy', LIVE_POLICY, '--approval', approvalFile, '--allocation-ceiling', '500', '--confirm', 'true', '--expires-at', '2026-09-09T12:00:00Z', '--owner-stdin', 'true'], { stdin: stdin(`${PW}\n${ch.json().phrase}\n`), env: { SERPENT_CONTROL_PASSWORD: PW } }); assert.equal(consumed.code, 6, consumed.err); assert.match(consumed.err, /NO_CHALLENGE|PHRASE_MISMATCH|CHALLENGE_EXPIRED/, 'a phrase is consumed by the first confirmation attempt');
  const ch2 = await run(['arm-live', '--policy', LIVE_POLICY, '--approval', approvalFile, '--allocation-ceiling', '500', '--challenge', 'true', '--owner-stdin', 'true'], { stdin: stdin(`${PW}\n`), env: { SERPENT_CONTROL_PASSWORD: PW } });
  const noDb = await run(['arm-live', '--policy', LIVE_POLICY, '--approval', approvalFile, '--allocation-ceiling', '500', '--confirm', 'true', '--expires-at', '2026-09-09T12:00:00Z', '--owner-stdin', 'true', '--owner-limits', path.join(TEST_DATA, 'limits.json')], { stdin: stdin(`${PW}\n${ch2.json().phrase}\n`), env: { SERPENT_CONTROL_PASSWORD: PW, ...ENV } }); assert.equal(noDb.code, 3, noDb.err); assert.match(noDb.err, /owner limits/, 'a missing owner-limits file is an invalid input, not a default');
  atomicWriteJson(path.join(TEST_DATA, 'limits.json'), SAMPLE_LIMITS); const ch3 = await run(['arm-live', '--policy', LIVE_POLICY, '--approval', approvalFile, '--allocation-ceiling', '500', '--challenge', 'true', '--owner-stdin', 'true'], { stdin: stdin(`${PW}\n`), env: { SERPENT_CONTROL_PASSWORD: PW } });
  const noDb2 = await run(['arm-live', '--policy', LIVE_POLICY, '--approval', approvalFile, '--allocation-ceiling', '500', '--confirm', 'true', '--expires-at', '2026-09-09T12:00:00Z', '--owner-stdin', 'true', '--owner-limits', path.join(TEST_DATA, 'limits.json')], { stdin: stdin(`${PW}\n${ch3.json().phrase}\n`), env: { SERPENT_CONTROL_PASSWORD: PW, ...ENV } }); assert.equal(noDb2.code, 4, noDb2.err); assert.match(noDb2.err, /DB_REQUIRED/, 'the LIVE journal authority is PostgreSQL: no database, no authorization record');
  const verify = await run(['verify', '--manifest', mfile, '--approval', approvalFile]); assert.equal(verify.code, 0, verify.err); assert.equal(verify.json().checks.manifest.state, 'CANDIDATE'); assert.equal(verify.json().checks.approval.ok, true);
  assert.ok(RUN_MODES.includes('OBSERVE') && !RUN_MODES.includes('LIVE'), 'LIVE is never a bare run mode: UNARMED or ARMED, explicitly');
});
