// SERPENT FINAL CLOSEOUT — MARKET-EDGE W1..W13: the thirteen independently reproduced witnesses, each closed as a NEGATIVE
// regression (the old wrong behaviour is asserted refused, the repaired truth asserted). Offline, mock only, no credential,
// no order verb, no Judge / Socrates / execution import.
import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import * as H from './helpers/market-lab.js';
import { createScriptedWebSocket } from './helpers/scripted-ws.js';
import { T0, HOUR, IMS, FUT, SPOT, SUBJECT, corpus, candle, book, l3snap, l3events, bucket, sealSources, darkCoverage, price } from './helpers/market-edge.js';
import { buildDeclaration, buildDatasetRows, sealDataset, scoreSealedDataset, reportError, exactForwardLabel, baselineFeatures, l3Features, derivativesFeatures, featureRow, buildSelectionLock, buildHoldoutOpening, CHARTS_INCOMPLETE_CODES, BOOK_MAX_AGE_MS, CANDLE_MAX_LAG_MS, RECIPE_DIGEST } from '../market-lab/edge-evaluation.js';
import { createMemoryEdgeEvalStore, EdgeEvalStoreError } from '../market-lab/edge-eval-store.js';
import { verifyRecordSemantics, manifestError, reportDigestOf, DECLARATION_CLOCK_TOLERANCE_MS } from '../market-lab/edge-eval-records.js';
import { declareEdge, evaluateEdge, lockEdgeSelection, openEdgeHoldout, consumeEdgeHoldout, verifyEdgeChain, retrospectiveEdgeEvaluation, runEdgeCapture, readEdgeCapture, readEdgeSources } from '../market-lab/edge-capture.js';
import { l3Microstructure, L3_WINDOW_REASONS } from '../market-lab/edge-recipes.js';
import { assessKeyPermissions, createL3AuthHelper, KEY_VERDICTS } from '../market-lab/providers/kraken-l3-auth.js';
import { createKrakenL3Stream, createSubscriptionPacer, L3_SUBSCRIPTION_WEIGHTS, L3_RATE_BUDGETS } from '../market-lab/providers/kraken-l3.js';
import { createKrakenChartsClient } from '../market-lab/providers/kraken-charts.js';
import { createKrakenDerivativesClient } from '../market-lab/providers/kraken-derivatives.js';
import { createHttpTransport } from '../market-lab/transport.js';
import { createL3Book } from '../market-lab/l3-book.js';
import { observationError, makeObservation, makeCoverage, quality, emptyProvenance, subjectId, CLOCK_CONFLICT_TOLERANCE_MS, QUALITY_REASON_CODES } from '../market-lab/contracts.js';
import { loadPolicy, sampleSubjects, L3_DEFAULTS, RESOURCE_DEFAULTS, CHARTS_DEFAULTS } from '../market-lab/policy.js';
import { MINUTE_MS } from '../market-lab/time.js';

const DIGEST = 'a'.repeat(64); const SOURCES = [{ bundleKind: 'EDGE_CAPTURE', bundleId: `mb-${'1'.repeat(64)}`, manifestSha256: '2'.repeat(64) }, { bundleKind: 'CAPTURE', bundleId: `mb-${'3'.repeat(64)}`, manifestSha256: '4'.repeat(64) }];
const COV = { publicObservations: 1, darkObservations: 1, darkCoverageRecords: 1, darkGapRecords: 0 };
const DECL = (over = {}) => buildDeclaration({ evaluationId: 'w', createdTs: T0 - 1, startTs: T0, durationMs: 6 * HOUR, embargoMs: HOUR, seed: 's', policyDigest: DIGEST, subject: SUBJECT, sourceRoots: SOURCES, ...over });
const rehash = (r) => ({ ...r, reportDigest: reportDigestOf(r) });
const FX = JSON.parse(readFileSync(new URL('./fixtures/kraken-l3-checksum-snapshot.json', import.meta.url), 'utf8')).data[0];
const MARKET = (wsname = 'BTC/USD') => ({ wsname, subject: { subjectKind: 'MARKET', canonicalCoin: wsname.split('/')[0], providerAssetId: null, venue: 'kraken', nativeSymbol: wsname, base: wsname.split('/')[0], quote: 'USD', marketType: 'SPOT', quoteAliasGroup: null }, pricePrecision: 1, qtyPrecision: 8 });
const TL3 = Date.parse('2026-09-10T12:00:00Z');
async function l3rig({ permissions = ['query-funds', 'create-ws-token'], l3 = L3_DEFAULTS, markets = [MARKET()], timers = null } = {}) {
  let t = TL3; const clock = () => t; const logs = [];
  const fixture = await H.startHttpFixture({ 'POST /0/private/GetApiKeyInfo': () => ({ json: { error: [], result: { permissions, validUntil: '0', nonceWindow: 0 } } }), 'POST /0/private/GetWebSocketsToken': () => ({ json: { error: [], result: { token: 'TOKEN-VALUE', expires: 900 } } }) });
  const transport = createHttpTransport({ fetchImpl: H.fetchFor(fixture), clock, log: (m) => logs.push(m) });
  const auth = createL3AuthHelper({ transport, clock, env: { K: 'key-value', S: Buffer.from('s').toString('base64') }, keyEnv: 'K', secretEnv: 'S', log: (m) => logs.push(m) });
  const sw = createScriptedWebSocket({ ackSubscriptions: false }); const out = { snaps: [], events: [], cov: [] };
  const stream = createKrakenL3Stream({ transport, clock, auth, markets, l3, WebSocketImpl: sw.WebSocketImpl, onSnapshot: (o) => out.snaps.push(o), onEvents: (o) => out.events.push(o), onCoverage: (c) => out.cov.push(c), log: (m) => logs.push(m), ...(timers ? { timers } : {}) });
  const st = await stream.start(); assert.equal(st.ok, true); await H.waitFor(() => sw.latest()?.sent.some((s) => s.includes('"level3"')), { timeoutMs: 2000 }); const sock = sw.latest(); sock.deliver({ method: 'subscribe', success: true, result: { channel: 'level3', symbol: markets[0].wsname, depth: l3.depth } });
  return { stream, sock, out, logs, advance: (ms) => { t += ms; }, now: () => t, close: async () => { await stream.stop(); await fixture.close(); } };
}
const fakeTimers = () => { const pending = []; return { pending, timers: { setTimeout: (fn, ms) => { const h = { fn, ms, cleared: false }; pending.push(h); return h; }, clearTimeout: (h) => { if (h) h.cleared = true; } }, fire: () => { const p = pending.splice(0); for (const h of p) if (!h.cleared) h.fn(); return p.length; } }; };

test('W1. EXACT label horizon: the label endpoint is the closed candle ending EXACTLY at t + H; when that candle is missing the label is CENSORED (null) — never the nearest earlier or later candle; the label is known only at the later candle knownAtTs', () => {
  const d = DECL(); const obs = corpus({ hours: 2 }); const t = T0 + HOUR; const candles = obs.filter((o) => o.kind === 'CANDLE').sort((a, b) => a.periodEndTs - b.periodEndTs);
  const exact = exactForwardLabel(candles, t, 15 * MINUTE_MS); assert.equal(exact.value, Number(Math.log(price(t + 15 * MINUTE_MS) / price(t)).toFixed(8))); assert.equal(exact.knownAtTs, t + 15 * MINUTE_MS + 500);
  // remove ONLY the candle ending at t + 15m: neighbours at +14m and +16m exist, yet the label is censored
  const holed = candles.filter((c) => c.periodEndTs !== t + 15 * MINUTE_MS); assert.ok(holed.some((c) => c.periodEndTs === t + 14 * MINUTE_MS) && holed.some((c) => c.periodEndTs === t + 16 * MINUTE_MS));
  assert.equal(exactForwardLabel(holed, t, 15 * MINUTE_MS), null, 'a missing exact endpoint is censored, never bridged'); assert.ok(exactForwardLabel(holed, t, 5 * MINUTE_MS) !== null, 'other horizons are untouched');
  const rows = buildDatasetRows({ declaration: d, observations: obs.filter((o) => !(o.kind === 'CANDLE' && o.periodEndTs === t + 15 * MINUTE_MS)), asOfTs: T0 + 2 * HOUR }); const row = rows.find((r) => r.decisionTs === t); assert.equal(row.labels['900000'], null); assert.ok(row.labels['300000'] !== null);
  // the candle ending at t + 15m exists but is known late: censored at an as-of before its knownAtTs, present after
  const late = candle(t + 14 * MINUTE_MS, { knownAtTs: T0 + 3 * HOUR }); const withLate = obs.filter((o) => !(o.kind === 'CANDLE' && o.periodStartTs === t + 14 * MINUTE_MS)).concat([late]);
  assert.equal(buildDatasetRows({ declaration: d, observations: withLate, asOfTs: T0 + 2 * HOUR }).find((r) => r.decisionTs === t).labels['900000'], null, 'not yet known at the as-of');
  assert.ok(buildDatasetRows({ declaration: d, observations: withLate, asOfTs: T0 + 3 * HOUR }).find((r) => r.decisionTs === t).labels['900000'] !== null);
  // the decision-time anchor is exact too: no closed candle ending exactly at t -> every label of that row is censored
  const noAnchor = obs.filter((o) => !(o.kind === 'CANDLE' && o.periodEndTs === t)); const r2 = buildDatasetRows({ declaration: d, observations: noAnchor, asOfTs: T0 + 3 * HOUR }).find((r) => r.decisionTs === t); assert.ok(Object.values(r2.labels).every((l) => l === null));
});

test('W2. REAL prospective precommitment: the declaration clock is the RUNTIME clock (a typed createdTs is ignored; a backdated declaration is refused by the chain); prospective only when the declaration existed before its start; the durable record binds id, clocks, window, deadline, split law, recipe version + digest, horizons, arms / features, scoring law, code / policy digests, source roots, seed, holdout definition and a content digest; the evaluator cannot mint a prospective declaration; the retrospective convenience says RETROSPECTIVE and is never release evidence', async () => {
  const base = mkdtempSync(path.join(tmpdir(), 'w2-')); const { capDir, edgeDir } = sealSources(base, corpus({ hours: 3 })); let t = T0 + 2 * HOUR; const clock = () => t; const store = createMemoryEdgeEvalStore({ clock });
  const late = await declareEdge({ store, clock, edgeCaptureDir: edgeDir, captureDir: capDir, evaluationId: 'late', startTs: T0, durationMs: 3 * HOUR, embargoMs: HOUR, seed: 's', subject: SUBJECT, codeDigest: DIGEST, createdTs: T0 - 1 /* ignored: not a parameter */ });
  assert.equal(late.createdTs, T0 + 2 * HOUR, 'the runtime clock, not the caller'); assert.equal(late.prospective, false);
  t = T0 - 1; const early = await declareEdge({ store, clock, edgeCaptureDir: edgeDir, captureDir: capDir, evaluationId: 'early', startTs: T0, durationMs: 3 * HOUR, embargoMs: HOUR, seed: 's', subject: SUBJECT, codeDigest: DIGEST }); assert.equal(early.prospective, true);
  const d = early.declaration; for (const k of ['declarationId', 'evaluationId', 'createdTs', 'knownAtTs', 'startTs', 'endTs', 'selectionDeadlineTs', 'splitLaw', 'recipeSetVersion', 'recipeDigest', 'horizonsMs', 'arms', 'features', 'scoringLaw', 'codeDigest', 'policyDigest', 'sourceRoots', 'seed', 'holdout']) assert.ok(k in d, k); assert.equal(d.recipeDigest, RECIPE_DIGEST); assert.equal(d.sourceRoots.length, 2); assert.equal(d.codeDigest, DIGEST);
  // a backdated declaration (createdTs typed before the runtime clock to LOOK prospective) is refused by the chain on write
  t = T0 + HOUR; const forged = buildDeclaration({ evaluationId: 'forged', createdTs: T0 - 1, startTs: T0, durationMs: 3 * HOUR, embargoMs: HOUR, seed: 's', subject: SUBJECT, policyDigest: DIGEST, sourceRoots: SOURCES }); assert.equal(forged.prospective, true);
  await assert.rejects(store.append('forged', 'DECLARED', forged, { expectSeq: 0 }), (e) => e instanceof EdgeEvalStoreError && /not the runtime clock|backdated/.test(e.message));
  const future = buildDeclaration({ evaluationId: 'future', createdTs: T0 + HOUR + DECLARATION_CLOCK_TOLERANCE_MS + 1, startTs: T0 + 2 * HOUR, durationMs: 3 * HOUR, embargoMs: HOUR, seed: 's', subject: SUBJECT, policyDigest: DIGEST, sourceRoots: SOURCES }); await assert.rejects(store.append('future', 'DECLARED', future, { expectSeq: 0 }), /runtime clock/);
  // ...and on read: a declaration re-typed after the fact is exposed even with a valid digest chain
  store._retamper('early', 1, (row) => { row.record.createdTs = T0 - HOUR; row.record.knownAtTs = T0 - HOUR; row.record.declarationId = `ee-${'0'.repeat(64)}`; }); await assert.rejects(store.records('early'), /RECORD_INVALID/);
  // the evaluator cannot mint a declaration: nothing declared -> refused; the retrospective convenience never touches the chain and is never release evidence
  await assert.rejects(evaluateEdge({ store, clock, evaluationId: 'never-declared', stage: 'DEVELOPMENT', edgeCaptureDir: edgeDir, captureDir: capDir, asOfTs: T0 + HOUR }), /nothing declared/);
  t = T0 + 4 * HOUR; const retro = retrospectiveEdgeEvaluation({ clock, edgeCaptureDir: edgeDir, captureDir: capDir, evaluationId: 'retro', startTs: T0, durationMs: 3 * HOUR, embargoMs: HOUR, seed: 's', subject: SUBJECT, asOfTs: T0 + 4 * HOUR, codeDigest: DIGEST, minN: 5 });
  assert.equal(retro.mode, 'RETROSPECTIVE'); assert.equal(retro.releaseEvidence, 'NEVER'); assert.equal(retro.declaration.prospective, false); assert.equal(retro.reports.DEVELOPMENT.releaseEvidence, 'NEVER'); assert.equal(retro.chain, 'NOT_RECORDED'); assert.deepEqual(await store.list(), ['early', 'late']);
  t = T0 - 1; assert.throws(() => retrospectiveEdgeEvaluation({ clock, edgeCaptureDir: edgeDir, captureDir: capDir, evaluationId: 'retro2', startTs: T0, durationMs: 3 * HOUR, embargoMs: HOUR, seed: 's', subject: SUBJECT, asOfTs: T0 + 4 * HOUR, codeDigest: DIGEST }), /DECLARED into the durable chain/, 'a window that has not started is never scored retrospectively');
  assert.match(reportError({ ...retro.reports.DEVELOPMENT, releaseEvidence: 'NONE' }, { declaration: retro.declaration, manifest: null }), /dataset digest|release evidence|reportDigest/);
});

test('W3. ONE-SHOT holdout lifecycle: DECLARED -> DEVELOPMENT_ALLOWED -> SELECTION_LOCKED -> HOLDOUT_OPENED -> HOLDOUT_CONSUMED -> QUALIFIED | CONSUMED_BUT_UNQUALIFIED; every out-of-order step is refused (evaluate before declare, lock without a look or after the deadline, open before the lock, a second opening, a look / dataset after the lock, a second consumption, anything after consumption); a crash resumes ONLY the same opened run (same runId / lock / bindings / as-of); a retampered lock or opening is exposed on read', async () => {
  const base = mkdtempSync(path.join(tmpdir(), 'w3-')); const obs = corpus({ hours: 6 }); const { capDir, edgeDir } = sealSources(base, obs); let t = T0 - 1; const clock = () => t; const store = createMemoryEdgeEvalStore({ clock }); const args = { store, clock, edgeCaptureDir: edgeDir, captureDir: capDir, evaluationId: 'lc' };
  await assert.rejects(lockEdgeSelection({ store, clock, evaluationId: 'lc', arm: 'BASELINE_PLUS_BOTH' }), /nothing declared/); await assert.rejects(openEdgeHoldout({ store, clock, evaluationId: 'lc' }), /nothing declared/);
  await declareEdge({ ...args, startTs: T0, durationMs: 6 * HOUR, embargoMs: HOUR, seed: 's', subject: SUBJECT, codeDigest: DIGEST }); assert.equal((await store.state('lc')).state, 'DECLARED');
  await assert.rejects(lockEdgeSelection({ store, clock, evaluationId: 'lc', arm: 'BASELINE_PLUS_BOTH' }), /at least one .* look/); await assert.rejects(openEdgeHoldout({ store, clock, evaluationId: 'lc' }), /only after the selection lock/); await assert.rejects(consumeEdgeHoldout({ ...args, asOfTs: T0 + 7 * HOUR }), /not opened/);
  await assert.rejects(evaluateEdge({ ...args, stage: 'HOLDOUT', asOfTs: T0 + 3 * HOUR }), /DEVELOPMENT or VALIDATION/);
  t = T0 + 3 * HOUR; await evaluateEdge({ ...args, stage: 'DEVELOPMENT', asOfTs: T0 + 3 * HOUR, minN: 5 }); assert.equal((await store.state('lc')).state, 'DEVELOPMENT_ALLOWED');
  // the lock must precede the declared selection deadline (holdout start): a late lock is refused by the record law
  t = T0 + 4.5 * HOUR + 1; await assert.rejects(lockEdgeSelection({ store, clock, evaluationId: 'lc', arm: 'BASELINE_PLUS_BOTH' }), /after the selection deadline/);
  t = T0 + 4 * HOUR; await lockEdgeSelection({ store, clock, evaluationId: 'lc', arm: 'BASELINE_PLUS_BOTH' }); assert.equal((await store.state('lc')).state, 'SELECTION_LOCKED');
  await assert.rejects(evaluateEdge({ ...args, stage: 'VALIDATION', asOfTs: T0 + 4 * HOUR }), /locked/); await assert.rejects(lockEdgeSelection({ store, clock, evaluationId: 'lc', arm: 'EXISTING_MARKET_BASELINE' }), /already locked/);
  const st = await store.state('lc'); const extraDataset = sealDataset({ declaration: st.declaration, rows: buildDatasetRows({ declaration: st.declaration, observations: obs, asOfTs: T0 + 4 * HOUR }), stage: 'VALIDATION', asOfTs: T0 + 4 * HOUR, sealedTs: T0 + 4 * HOUR, sources: st.declaration.sourceRoots, coverageSummary: COV }); await assert.rejects(store.append('lc', 'DATASET_SEALED', extraDataset), /after the lock/);
  t = T0 + 7 * HOUR; const opened = await openEdgeHoldout({ store, clock, evaluationId: 'lc' }); assert.equal((await store.state('lc')).state, 'HOLDOUT_OPENED');
  await assert.rejects(openEdgeHoldout({ store, clock, evaluationId: 'lc' }), /already opened/, 'one shot');
  const st2 = await store.state('lc'); const secondOpening = buildHoldoutOpening({ declaration: st2.declaration, lock: st2.lock, openedTs: T0 + 7 * HOUR + 1 }); await assert.rejects(store.append('lc', 'HOLDOUT_OPENED', secondOpening), /already opened/);
  const otherArmLock = buildSelectionLock({ declaration: st2.declaration, arm: 'EXISTING_MARKET_BASELINE', lockedTs: T0 + 4 * HOUR, lookReportDigests: st2.lock.lookReportDigests }); await assert.rejects(store.append('lc', 'SELECTION_LOCKED', otherArmLock), /second selection lock/, 'no alternate arm reuses the opened holdout');
  // crash between the sealed holdout dataset and the consumption: the resume must be the SAME run; a different as-of is refused
  const holdoutRows = buildDatasetRows({ declaration: st2.declaration, observations: obs, coverage: readEdgeSources({ edgeCaptureDir: edgeDir, captureDir: capDir }).coverage, asOfTs: T0 + 7 * HOUR }); const src = readEdgeSources({ edgeCaptureDir: edgeDir, captureDir: capDir });
  const hm = sealDataset({ declaration: st2.declaration, rows: holdoutRows, stage: 'HOLDOUT', runId: opened.runId, asOfTs: T0 + 7 * HOUR, sealedTs: T0 + 7 * HOUR, sources: src.sourceRoots, coverageSummary: src.coverageSummary }); await store.append('lc', 'DATASET_SEALED', hm);
  await assert.rejects(store.append('lc', 'DATASET_SEALED', { ...hm, runId: 'run-other', manifestDigest: undefined }), /holdout dataset run mismatch|manifestDigest|undeclared|malformed/);
  await assert.rejects(consumeEdgeHoldout({ ...args, asOfTs: T0 + 6 * HOUR + 1 }), /sealed its holdout dataset as of/);
  const done = await consumeEdgeHoldout({ ...args, minN: 5 }); assert.equal(done.resumed, true); assert.equal(done.runId, opened.runId); assert.equal(done.qualification.status, 'QUALIFIED'); assert.equal((await store.state('lc')).state, 'HOLDOUT_CONSUMED');
  await assert.rejects(consumeEdgeHoldout({ ...args, minN: 5 }), /consumed/); await assert.rejects(evaluateEdge({ ...args, stage: 'DEVELOPMENT', asOfTs: T0 + HOUR }), /consumed|locked/); await assert.rejects(openEdgeHoldout({ store, clock, evaluationId: 'lc' }), /already opened|consumed/);
  await assert.rejects(store.append('lc', 'DECLARED', st2.declaration), /consumed|second declaration/);
  // an unqualified consumption is still a consumption (the one shot is spent): a retrospective declaration cannot qualify
  const rows = await store.records('lc'); assert.equal(verifyRecordSemantics(rows).ok, true);
  store._retamper('lc', rows.find((r) => r.kind === 'SELECTION_LOCKED').seq, (row) => { row.record.arm = 'EXISTING_MARKET_BASELINE'; }); await assert.rejects(store.records('lc'), /RECORD_INVALID/, 'a retampered lock breaks the opening binding');
});

test('W4. NO caller-fabricated production dataset: the chain functions take no rows; a report over rows that are not the sealed rows is refused; a self-consistent manifest + report appended over FABRICATED rows (a perfect statistic) is exposed by edge-verify, which rebuilds every sealed dataset from the declared bundles; foreign bundles are refused by source-root binding', async () => {
  const base = mkdtempSync(path.join(tmpdir(), 'w4-')); const obs = corpus({ hours: 6 }); const { capDir, edgeDir } = sealSources(base, obs); let t = T0 - 1; const clock = () => t; const store = createMemoryEdgeEvalStore({ clock }); const args = { store, clock, edgeCaptureDir: edgeDir, captureDir: capDir, evaluationId: 'fab' };
  await declareEdge({ ...args, startTs: T0, durationMs: 6 * HOUR, embargoMs: HOUR, seed: 's', subject: SUBJECT, codeDigest: DIGEST }); t = T0 + 3 * HOUR; await evaluateEdge({ ...args, stage: 'DEVELOPMENT', asOfTs: T0 + 3 * HOUR, minN: 5 });
  assert.equal((await verifyEdgeChain({ ...args })).ok, true);
  const st = await store.state('fab'); const real = buildDatasetRows({ declaration: st.declaration, observations: obs, asOfTs: T0 + 3 * HOUR });
  // fabricated: the same decision points, features replaced by the labels themselves (a perfect rank correlation)
  const fake = real.map((r) => ({ ...r, features: Object.fromEntries(Object.keys(r.features).map((k) => [k, r.labels['900000']?.value ?? null])), support: Object.fromEntries(Object.keys(r.support).map((k) => [k, { state: r.labels['900000'] ? 'COMPLETE' : 'MISSING', reasons: [] }])) }));
  const fakeManifest = sealDataset({ declaration: st.declaration, rows: fake, stage: 'DEVELOPMENT', asOfTs: T0 + 3 * HOUR, sealedTs: T0 + 3 * HOUR, sources: st.declaration.sourceRoots, coverageSummary: COV }); assert.equal(manifestError(fakeManifest, st.declaration), null, 'the manifest alone cannot tell (it is self-consistent)');
  const fakeReport = scoreSealedDataset({ declaration: st.declaration, manifest: fakeManifest, rows: fake, stage: 'DEVELOPMENT', generatedTs: T0 + 3 * HOUR, minN: 5 }); assert.equal(fakeReport.arms.EXISTING_MARKET_BASELINE.horizons['900000'].features.log_return_5m.spearmanIc, 1, 'the forged statistic is perfect');
  assert.throws(() => scoreSealedDataset({ declaration: st.declaration, manifest: st.datasets[0], rows: fake, stage: 'DEVELOPMENT', generatedTs: T0 + 3 * HOUR }), /not the sealed rows/, 'fabricated rows never score against a real manifest');
  await store.append('fab', 'DATASET_SEALED', fakeManifest); await store.append('fab', 'EVALUATED', { stage: 'DEVELOPMENT', report: fakeReport });
  const v = await verifyEdgeChain({ ...args }); assert.equal(v.ok, false); assert.deepEqual(v.findings.map((f) => f.finding), ['ROWS_NOT_DERIVED_FROM_SOURCES']); assert.equal(v.findings[0].seq, 4); assert.equal(v.datasets, 2);
  // foreign bundles (another sealed corpus) are not the declared source roots
  const other = sealSources(mkdtempSync(path.join(tmpdir(), 'w4b-')), corpus({ hours: 6 }).filter((o) => o.kind !== 'TRADE')); await assert.rejects(evaluateEdge({ ...args, edgeCaptureDir: other.edgeDir, captureDir: other.capDir, stage: 'VALIDATION', asOfTs: T0 + 4 * HOUR }), /not the declared source roots/);
  for (const fn of [evaluateEdge, consumeEdgeHoldout]) assert.ok(!/\brows\b\s*[,}=]/.test(String(fn).split('\n')[0]), `${fn.name} takes no rows parameter`);
});

test('W5. CLOSED recursive semantic report validation: every listed mutation is refused even when validly rehashed — wrong evaluationId / declarationId, wrong recipe version / digest, wrong scoring law, negative / impossible decision counts, split counts inconsistent, arms not the locked selection, statistics inconsistent with the sealed n, holdout state inconsistent, dataset digest mismatch, clocks outside the manifest, unknown nested keys', () => {
  const d = DECL(); const obs = corpus({ hours: 6 }); const asOfTs = T0 + 7 * HOUR; const rows = buildDatasetRows({ declaration: d, observations: obs, asOfTs });
  const m = sealDataset({ declaration: d, rows, stage: 'DEVELOPMENT', asOfTs, sealedTs: asOfTs + 1, sources: SOURCES, coverageSummary: COV }); const r = scoreSealedDataset({ declaration: d, manifest: m, rows, stage: 'DEVELOPMENT', generatedTs: asOfTs + 2, minN: 10 }); const ctx = { declaration: d, manifest: m };
  assert.equal(reportError(r, ctx), null);
  const lie = (mut, re) => { const x = structuredClone(r); mut(x); const e = reportError(rehash(x), ctx); assert.ok(e, `accepted: ${re}`); assert.match(e, re); };
  lie((x) => { x.evaluationId = 'other'; }, /not bound/); lie((x) => { x.declarationId = 'ee-' + '0'.repeat(64); }, /not bound/); lie((x) => { x.recipeSetVersion = 'market-edge-recipes-9'; }, /bindings/); lie((x) => { x.recipeDigest = '9'.repeat(64); }, /bindings/); lie((x) => { x.scoringLaw = 'mean ic'; }, /law text/);
  lie((x) => { x.decisionPoints = -1; }, /decision points/); lie((x) => { x.decisionPoints = 10_000; }, /decision points/); lie((x) => { x.splitCounts.DEVELOPMENT += 1; }, /split counts/); lie((x) => { x.scoredRows += 1; }, /scored rows/);
  lie((x) => { delete x.arms.BASELINE_PLUS_BOTH; }, /arms are not the locked selection/); lie((x) => { x.arms.EXTRA = x.arms.EXISTING_MARKET_BASELINE; }, /arms are not the locked selection/);
  lie((x) => { x.arms.EXISTING_MARKET_BASELINE.horizons['900000'].features.log_return_5m.n += 1; }, /n disagrees with the sealed manifest/); lie((x) => { x.arms.EXISTING_MARKET_BASELINE.horizons['900000'].features.log_return_5m.spearmanIc = 0.99; }, /aggregate statistics disagree/); lie((x) => { x.arms.EXISTING_MARKET_BASELINE.horizons['900000'].meanAbsIc = 0.99; }, /aggregate statistics disagree/); lie((x) => { const f = x.arms.EXISTING_MARKET_BASELINE.horizons['900000'].features.log_return_5m; f.state = 'INSUFFICIENT_N'; }, /INSUFFICIENT_N contradiction/); lie((x) => { const f = x.arms.EXISTING_MARKET_BASELINE.horizons['900000'].features.log_return_5m; f.spearmanIc = 1.5; }, /SCORED contradiction/);
  lie((x) => { x.holdout.state = 'OPENED'; }, /holdout state/); lie((x) => { x.holdout.rows += 1; }, /holdout state/); lie((x) => { x.datasetDigest = '5'.repeat(64); }, /dataset digest/); lie((x) => { x.asOfTs += 1; }, /clocks disagree/); lie((x) => { x.generatedTs = m.sealedTs - 1; }, /clocks disagree/);
  lie((x) => { x.arms.EXISTING_MARKET_BASELINE.horizons['900000'].features.log_return_5m.note = 'x'; }, /undeclared key/); lie((x) => { x.arms.EXISTING_MARKET_BASELINE.horizons['900000'].extra = 1; }, /undeclared key/); lie((x) => { x.holdout.promoted = true; }, /undeclared key/); lie((x) => { x.edgeClaim = 'MADE'; }, /never claims edge/); lie((x) => { x.mode = 'RETROSPECTIVE'; }, /mode disagrees/); lie((x) => { x.releaseEvidence = 'CANARY'; }, /release evidence/);
  const unhashed = structuredClone(r); unhashed.decisionPoints = 1; assert.match(reportError(unhashed, ctx), /decision points|reportDigest/);
  assert.match(manifestError({ ...m, availability: { ...m.availability, DEVELOPMENT: { ...m.availability.DEVELOPMENT, log_return_5m: { ...m.availability.DEVELOPMENT.log_return_5m, 900000: m.splitCounts.DEVELOPMENT + 1 } } } }, d), /exceeds the split|manifestDigest/);
});

test('W6. STALE current-state inputs: a book snapshot older than the shared displayed-book law (15 s) yields spread_bps STALE / null, never "current"; a closed candle older than one interval yields STALE returns; an L3 snapshot received before the window start is SNAPSHOT_STALE (PARTIAL support -> STALE feature); the bounds are the existing laws, not invented', () => {
  assert.equal(BOOK_MAX_AGE_MS, 15_000); assert.equal(CANDLE_MAX_LAG_MS, MINUTE_MS);
  const t = T0 + HOUR; const obs = corpus({ hours: 2 });
  const fresh = baselineFeatures(obs, { spotSymbol: 'BTC/USD', t }); assert.equal(fresh.spread_bps.state, 'COMPLETE'); assert.ok(Number.isFinite(fresh.spread_bps.value));
  const oldBooks = obs.filter((o) => o.kind !== 'BOOK_SNAPSHOT').concat([book(t - 3 * HOUR)]); const stale = baselineFeatures(oldBooks, { spotSymbol: 'BTC/USD', t }); assert.equal(stale.spread_bps.state, 'STALE'); assert.equal(stale.spread_bps.value, null); assert.deepEqual(stale.spread_bps.reasons, ['BOOK_OLDER_THAN_MAX_AGE']);
  const edge = baselineFeatures(obs.filter((o) => o.kind !== 'BOOK_SNAPSHOT').concat([book(t - 15_001)]), { spotSymbol: 'BTC/USD', t }); assert.equal(edge.spread_bps.state, 'STALE'); assert.equal(baselineFeatures(obs.filter((o) => o.kind !== 'BOOK_SNAPSHOT').concat([book(t - 15_000)]), { spotSymbol: 'BTC/USD', t }).spread_bps.state, 'COMPLETE');
  const noRecentCandles = obs.filter((o) => !(o.kind === 'CANDLE' && o.periodEndTs > t - 10 * MINUTE_MS)); const sc = baselineFeatures(noRecentCandles, { spotSymbol: 'BTC/USD', t }); assert.equal(sc.log_return_5m.state, 'STALE'); assert.equal(sc.realized_volatility_20.state, 'STALE'); assert.equal(sc.log_return_5m.value, null);
  const l3 = l3Features(obs, { spotSymbol: 'BTC/USD', t, windowMs: 5 * MINUTE_MS }); assert.equal(l3.order_age_p50_bid_ms.state, 'COMPLETE');
  const oldL3 = obs.filter((o) => o.kind !== 'L3_BOOK_SNAPSHOT').concat([l3snap(t - 2 * HOUR)]); const s3 = l3Features(oldL3, { spotSymbol: 'BTC/USD', t, windowMs: 5 * MINUTE_MS }); assert.equal(s3.order_age_p50_bid_ms.state, 'STALE'); assert.equal(s3.order_age_p50_bid_ms.value, null); assert.ok(s3.order_age_p50_bid_ms.reasons.includes('SNAPSHOT_STALE'));
  assert.ok(L3_WINDOW_REASONS.includes('SNAPSHOT_STALE'));
});

test('W7. COMPLETE-only primary scoring: a recipe that carries a numeric value under PARTIAL support (a coverage gap inside the L3 window) yields a NULL feature with the reason retained; the sealed manifest keeps the state in supportCounts and excludes the row from availability; the report n equals that availability; PARTIAL / MISSING / STALE / UNVERIFIED never enter the primary statistic and are never zero-filled', () => {
  const d = DECL(); const t = T0 + HOUR; const obs = corpus({ hours: 6 });
  const gap = { provider: 'KRAKEN_SPOT', endpointId: 'ws-l3', subject: SPOT, kind: 'L3_BOOK_COVERAGE', receivedTs: t - 90_000, knownAtTs: t - 90_000 };
  const gapObs = makeObservation({ sourceKey: null, sourceRevision: null, sourceEventTs: null, periodStartTs: null, periodEndTs: null, publishedTs: null, ...gap, sequence: 999_999, epochId: 'KRAKEN_SPOT:ws-l3:1', quality: quality('KNOWN'), provenance: { ...emptyProvenance(), vintage: 'LIVE_FORWARD_CAPTURE' }, payload: { state: 'GAP', reason: 'EPOCH_GAP', sinceTs: t - 90_000, untilTs: null, droppedUpdates: 0, depth: 10, ordersTracked: 2 } });
  const withGap = [...obs, gapObs]; const w = { asOfTs: t, startTs: t - 5 * MINUTE_MS, endTs: t };
  const recipe = l3Microstructure(withGap.filter((o) => o.subject.nativeSymbol === 'BTC/USD' && ['L3_BOOK_SNAPSHOT', 'L3_ORDER_EVENT', 'L3_BOOK_COVERAGE'].includes(o.kind)), w).components.new_order_impulse; assert.ok(Number.isFinite(recipe.value.net), 'the recipe still carries a number'); assert.equal(recipe.support.state, 'PARTIAL');
  const f = l3Features(withGap, { spotSymbol: 'BTC/USD', t, windowMs: 5 * MINUTE_MS }); assert.equal(f.new_order_impulse_net.value, null, 'PARTIAL support: null for the primary statistic'); assert.equal(f.new_order_impulse_net.state, 'PARTIAL'); assert.ok(f.new_order_impulse_net.reasons.includes('COVERAGE_GAP'));
  const rows = buildDatasetRows({ declaration: d, observations: withGap, asOfTs: T0 + 7 * HOUR }); const row = rows.find((r) => r.decisionTs === t); assert.equal(row.features.new_order_impulse_net, null); assert.equal(row.support.new_order_impulse_net.state, 'PARTIAL'); assert.ok(rows.filter((r) => r.decisionTs !== t).every((r) => r.support.new_order_impulse_net.state === 'COMPLETE'));
  const m = sealDataset({ declaration: d, rows, stage: 'DEVELOPMENT', asOfTs: T0 + 7 * HOUR, sealedTs: T0 + 7 * HOUR, sources: SOURCES, coverageSummary: COV }); assert.equal(m.supportCounts.new_order_impulse_net.PARTIAL, 1); assert.equal(m.supportCounts.new_order_impulse_net.COMPLETE, rows.length - 1);
  const devComplete = rows.filter((r) => r.split === 'DEVELOPMENT' && r.support.new_order_impulse_net.state === 'COMPLETE' && r.labels['900000'] !== null).length; assert.equal(m.availability.DEVELOPMENT.new_order_impulse_net['900000'], devComplete);
  const r = scoreSealedDataset({ declaration: d, manifest: m, rows, stage: 'DEVELOPMENT', generatedTs: T0 + 7 * HOUR, minN: 5 }); assert.equal(r.arms.BASELINE_PLUS_L3_MICROSTRUCTURE.horizons['900000'].features.new_order_impulse_net.n, devComplete); assert.ok(JSON.stringify(m.supportCounts).includes('"PARTIAL":1'));
  // an UNVERIFIED L3 window (checksum not verified) is null too — never zero
  const unv = obs.map((o) => (o.kind === 'L3_ORDER_EVENT' && o.receivedTs > t - 5 * MINUTE_MS && o.receivedTs <= t ? { ...o, payload: { ...o.payload, checksumVerified: null } } : o)); const fu = l3Features(unv, { spotSymbol: 'BTC/USD', t, windowMs: 5 * MINUTE_MS }); assert.equal(fu.new_order_impulse_net.state, 'UNVERIFIED'); assert.equal(fu.new_order_impulse_net.value, null); assert.notEqual(fu.new_order_impulse_net.value, 0);
});

test('W8. SAFE KEY != L3-USABLE KEY: two separate verdicts — NON_AUTHORITY_KEY (no trading / withdraw / funding authority but no documented token capability) and SAFE_L3_DATA_KEY (no authority, no unknown permission, create-ws-token present, probe succeeded); the non-authority key keeps L3 blocked with TOKEN_PERMISSION_MISSING; authority and undocumented permissions outrank the token capability', () => {
  assert.deepEqual([...KEY_VERDICTS], ['SAFE_L3_DATA_KEY', 'NON_AUTHORITY_KEY', 'AUTHORITY_CAPABLE', 'UNKNOWN_PERMISSION', 'MALFORMED']);
  const a = assessKeyPermissions(['query-funds', 'query-ledger']); assert.equal(a.verdict, 'NON_AUTHORITY_KEY'); assert.equal(a.blocker, 'TOKEN_PERMISSION_MISSING'); assert.equal(a.l3Usable, false);
  const b = assessKeyPermissions(['query-funds', 'create-ws-token']); assert.equal(b.verdict, 'SAFE_L3_DATA_KEY'); assert.equal(b.blocker, null); assert.equal(b.l3Usable, true);
  assert.equal(assessKeyPermissions(['create-ws-token', 'withdraw-funds']).verdict, 'AUTHORITY_CAPABLE'); assert.equal(assessKeyPermissions(['create-ws-token', 'mystery']).verdict, 'UNKNOWN_PERMISSION'); assert.equal(assessKeyPermissions(['create-ws-token', 'mystery']).l3Usable, false);
  assert.ok(!Object.values(assessKeyPermissions(['create-ws-token', 'mystery'])).flat().includes('mystery'), 'never echoed');
});

test('W9. ONE weighted subscription limiter: the documented counter (+5 / +25 / +100 per symbol for depth 10 / 100 / 1000) against 200 points per second on the STANDARD tier (500 only when the policy says PRO), shared by the initial subscribe, every resubscribe and every unsubscribe; the operator symbols-per-second bound applies on top; nothing is dropped, the remainder waits a real second', async () => {
  assert.deepEqual(L3_SUBSCRIPTION_WEIGHTS, { 10: 5, 100: 25, 1000: 100 }); assert.deepEqual(L3_RATE_BUDGETS, { STANDARD: 200, PRO: 500 });
  const mk = ({ depth, rateTier = 'STANDARD', symbolsPerSecond = 50 }) => { const sent = []; const ft = fakeTimers(); let t = TL3; const p = createSubscriptionPacer({ depth, rateTier, symbolsPerSecond, clock: () => t, timers: ft.timers, send: (m) => sent.push(m) }); return { p, sent, ft, advance: (ms) => { t += ms; } }; };
  const syms = (n) => Array.from({ length: n }, (_, i) => `S${i}/USD`);
  const d100 = mk({ depth: 100 }); d100.p.request('subscribe', syms(9), 'tok'); assert.equal(d100.sent.length, 1); assert.equal(d100.sent[0].params.symbol.length, 8, '8 x 25 = 200 points: the ninth waits'); assert.equal(d100.p.status().queued, 1); assert.equal(d100.ft.pending.length, 1); d100.advance(1000); d100.ft.fire(); assert.equal(d100.sent.length, 2); assert.deepEqual(d100.sent[1].params.symbol, ['S8/USD']); assert.equal(d100.p.status().points, 225);
  const d1000 = mk({ depth: 1000 }); d1000.p.request('subscribe', syms(5), 'tok'); assert.equal(d1000.sent[0].params.symbol.length, 2, '2 x 100 = 200'); assert.equal(d1000.p.status().queued, 3);
  const pro = mk({ depth: 100, rateTier: 'PRO' }); pro.p.request('subscribe', syms(20), 'tok'); assert.equal(pro.sent[0].params.symbol.length, 20, '20 x 25 = 500 on the proven PRO tier only'); assert.equal(pro.p.budget, 500);
  const unknownTier = mk({ depth: 100, rateTier: 'ULTRA' }); assert.equal(unknownTier.p.budget, 200, 'an unknown tier fails safe to STANDARD'); assert.equal(unknownTier.p.rateTier, 'STANDARD');
  const capped = mk({ depth: 10, symbolsPerSecond: 2 }); capped.p.request('subscribe', syms(3), 'tok'); assert.equal(capped.sent[0].params.symbol.length, 2, 'the operator symbol bound applies on top of the weighted budget'); assert.equal(capped.p.status().queued, 1);
  // the SAME pacer serves the resubscribe: unsubscribe + subscribe are charged; with the window spent, the resubscribe is deferred, never bypassed
  const ft = fakeTimers(); const r = await l3rig({ l3: { ...L3_DEFAULTS, maxSubscriptionsPerSecond: 2 }, timers: ft.timers });
  try {
    assert.equal(r.stream.pacer.status().points, 5); r.advance(100); r.sock.deliver({ channel: 'level3', type: 'snapshot', data: [{ ...FX, timestamp: '2026-09-10T12:00:00.100000000Z' }] }); assert.equal(r.stream.books.get('BTC/USD').synchronized, true);
    r.advance(100); r.sock.deliver({ channel: 'level3', type: 'update', data: [{ symbol: 'BTC/USD', checksum: 12345, timestamp: '2026-09-10T12:00:00.200000000Z', bids: [], asks: [{ event: 'delete', order_id: FX.asks[1].order_id, limit_price: FX.asks[1].limit_price, order_qty: '0', timestamp: FX.asks[1].timestamp }] }] });
    assert.equal(r.stream.books.get('BTC/USD').synchronized, false); const sent = r.sock.sent.map((s) => JSON.parse(s)); assert.deepEqual(sent.map((m) => m.method), ['subscribe', 'unsubscribe'], 'the unsubscribe took the second slot of the same second; the resubscribe waits'); assert.equal(r.stream.pacer.status().queued, 1); assert.equal(r.stream.pacer.status().deferred, 1); assert.equal(r.stream.status().pacing.points, 10);
    r.advance(1000); ft.fire(); const after = r.sock.sent.map((s) => JSON.parse(s)); assert.deepEqual(after.map((m) => m.method), ['subscribe', 'unsubscribe', 'subscribe']); assert.equal(after[2].params.token, 'TOKEN-VALUE'); assert.equal(r.stream.pacer.status().points, 15); assert.equal(r.stream.pacer.status().queued, 0);
  } finally { await r.close(); }
});

test('W10. PRESERVE the matching-engine message time: snapshot and update records carry the exchange timestamp as sourceEventTs BESIDE receivedTs / knownAtTs (never in their place); an INTERVAL sample carries the exchange clock of the message that shaped the state; a source clock ahead of receipt beyond the shared tolerance is CLOCK_CONFLICT and degrades the window support — never silently normalized; replay of the same messages reproduces both clocks', async () => {
  const r = await l3rig();
  try {
    r.advance(1000); const receipt = r.now(); r.sock.deliver({ channel: 'level3', type: 'snapshot', data: [{ ...FX, timestamp: '2026-09-10T12:00:00.250000000Z' }] });
    const snap = r.out.snaps.find((o) => o.kind === 'L3_BOOK_SNAPSHOT'); assert.equal(snap.sourceEventTs, TL3 + 250); assert.equal(snap.receivedTs, receipt); assert.equal(snap.knownAtTs, receipt); assert.notEqual(snap.sourceEventTs, snap.receivedTs); assert.equal(snap.quality.state, 'KNOWN'); assert.equal(observationError(snap), null);
    const pb = createL3Book({ symbol: 'BTC/USD', depth: 10 }); pb.applySnapshot({ bids: FX.bids, asks: FX.asks }, { receivedTs: TL3 }); const del = { event: 'delete', order_id: FX.asks[1].order_id, limit_price: FX.asks[1].limit_price, order_qty: '0', timestamp: FX.asks[1].timestamp }; pb.applyUpdate({ bids: [], asks: [del], checksum: null }, { receivedTs: TL3 });
    r.advance(1000); r.sock.deliver({ channel: 'level3', type: 'update', data: [{ symbol: 'BTC/USD', checksum: pb.checksum(), timestamp: '2026-09-10T12:00:01.750000000Z', bids: [], asks: [del] }] });
    const ev = r.out.events[0]; assert.equal(ev.sourceEventTs, TL3 + 1750); assert.equal(ev.receivedTs, r.now()); assert.equal(ev.knownAtTs, r.now()); assert.equal(ev.quality.state, 'KNOWN'); assert.equal(ev.payload.checksumVerified, true);
    const sample = r.stream.sample('BTC/USD'); assert.equal(sample.sourceEventTs, TL3 + 1750, 'the sample names the exchange clock of the last message that shaped the state'); assert.equal(sample.receivedTs, r.now()); assert.equal(sample.payload.checksumVerified, true); assert.equal(sample.quality.state, 'KNOWN');
    // a source clock far ahead of receipt: CLOCK_CONFLICT with its reason, the value preserved as sent
    const del2 = { event: 'delete', order_id: FX.asks[2].order_id, limit_price: FX.asks[2].limit_price, order_qty: '0', timestamp: FX.asks[2].timestamp }; pb.applyUpdate({ bids: [], asks: [del2], checksum: null }, { receivedTs: TL3 });
    r.advance(1000); const ahead = new Date(r.now() + CLOCK_CONFLICT_TOLERANCE_MS + 10_000).toISOString(); r.sock.deliver({ channel: 'level3', type: 'update', data: [{ symbol: 'BTC/USD', checksum: pb.checksum(), timestamp: ahead, bids: [], asks: [del2] }] });
    const conflict = r.out.events[1]; assert.equal(conflict.quality.state, 'CLOCK_CONFLICT'); assert.ok(conflict.quality.reasonCodes.includes('SOURCE_EVENT_AHEAD_OF_RECEIPT')); assert.equal(conflict.sourceEventTs, Date.parse(ahead), 'never normalized'); assert.equal(conflict.receivedTs, r.now()); assert.equal(observationError(conflict), null); assert.equal(r.stream.status().clockConflicts, 1);
    const win = l3Microstructure([snap, ev, conflict], { asOfTs: r.now(), startTs: TL3, endTs: r.now() }).components.new_order_impulse; assert.equal(win.support.state, 'PARTIAL'); assert.ok(win.support.reasons.includes('CLOCK_CONFLICT'));
  } finally { await r.close(); }
  // replay determinism: the same messages through a second stream reproduce both clocks exactly
  const r2 = await l3rig(); try { r2.advance(1000); r2.sock.deliver({ channel: 'level3', type: 'snapshot', data: [{ ...FX, timestamp: '2026-09-10T12:00:00.250000000Z' }] }); const s2 = r2.out.snaps.find((o) => o.kind === 'L3_BOOK_SNAPSHOT'); assert.equal(s2.sourceEventTs, TL3 + 250); assert.equal(s2.receivedTs, TL3 + 1000); } finally { await r2.close(); }
});

test('W11. CHECKSUM / truncation / epoch truth: a snapshot or update WITHOUT the documented checksum is CHECKSUM_MISSING -> desynchronized + resubscribe (no record claims KNOWN); a snapshot whose checksum is unverified is PARTIAL with CHECKSUM_UNVERIFIED; the L3 window support is COMPLETE only when the latest snapshot AND every event batch carry a verified checksum; unknown order, duplicate add, crossed book, overflow, epoch gap and scope truncation all break COMPLETE support', async () => {
  const r = await l3rig();
  try {
    r.advance(1000); const { checksum, ...noChecksum } = FX; r.sock.deliver({ channel: 'level3', type: 'snapshot', data: [{ ...noChecksum, timestamp: '2026-09-10T12:00:00.100000000Z' }] });
    assert.equal(r.stream.books.get('BTC/USD').synchronized, false); assert.equal(r.stream.status().checksumMissing, 1); assert.ok(!r.out.snaps.some((o) => o.kind === 'L3_BOOK_SNAPSHOT'), 'no snapshot record from an unverifiable state'); assert.equal(r.out.snaps.at(-1).payload.state, 'DEGRADED'); assert.equal(r.out.snaps.at(-1).payload.reason, 'CHECKSUM_UNVERIFIED'); assert.deepEqual(r.out.cov.at(-1).reasonCodes, ['CHECKSUM_UNVERIFIED']); assert.equal(r.sock.sent.map((s) => JSON.parse(s).method).join(','), 'subscribe,unsubscribe,subscribe');
    r.advance(1000); r.sock.deliver({ channel: 'level3', type: 'snapshot', data: [{ ...FX, timestamp: '2026-09-10T12:00:00.200000000Z' }] }); assert.equal(r.stream.books.get('BTC/USD').synchronized, true); assert.equal(r.out.snaps.find((o) => o.kind === 'L3_BOOK_SNAPSHOT').quality.state, 'KNOWN');
    r.advance(1000); r.sock.deliver({ channel: 'level3', type: 'update', data: [{ symbol: 'BTC/USD', timestamp: '2026-09-10T12:00:00.300000000Z', bids: [], asks: [] }] }); assert.equal(r.stream.books.get('BTC/USD').synchronized, false, 'an update without a checksum is not synchronized enough'); assert.equal(r.stream.status().checksumMissing, 2); assert.equal(r.out.events.length, 0);
  } finally { await r.close(); }
  // window law over records: an unverified snapshot or event batch lowers support to PARTIAL with CHECKSUM_UNVERIFIED; the feature becomes UNVERIFIED / null
  const t = T0 + HOUR; const obs = corpus({ hours: 2 }); const win = { asOfTs: t, startTs: t - 5 * MINUTE_MS, endTs: t }; const l3only = (list) => list.filter((o) => ['L3_BOOK_SNAPSHOT', 'L3_ORDER_EVENT', 'L3_BOOK_COVERAGE'].includes(o.kind));
  assert.equal(l3Microstructure(l3only(obs), win).components.order_age_quantiles.support.state, 'COMPLETE');
  const unvSnap = obs.map((o) => (o.kind === 'L3_BOOK_SNAPSHOT' && o.receivedTs > t - 5 * MINUTE_MS && o.receivedTs <= t ? { ...o, quality: { ...o.quality, state: 'PARTIAL', reasonCodes: ['CHECKSUM_UNVERIFIED'] }, payload: { ...o.payload, checksumVerified: null } } : o)); const c1 = l3Microstructure(l3only(unvSnap), win).components; assert.equal(c1.order_age_quantiles.support.state, 'PARTIAL'); assert.ok(c1.order_age_quantiles.support.reasons.includes('CHECKSUM_UNVERIFIED')); assert.ok(c1.order_age_quantiles.value !== null, 'the recipe reports; the evaluator refuses');
  const f1 = l3Features(unvSnap, { spotSymbol: 'BTC/USD', t, windowMs: 5 * MINUTE_MS }); assert.equal(f1.order_age_p50_bid_ms.state, 'UNVERIFIED'); assert.equal(f1.order_age_p50_bid_ms.value, null);
  const unvEvents = obs.map((o) => (o.kind === 'L3_ORDER_EVENT' && o.receivedTs > t - 5 * MINUTE_MS && o.receivedTs <= t ? { ...o, payload: { ...o.payload, checksumVerified: false } } : o)); assert.equal(l3Features(unvEvents, { spotSymbol: 'BTC/USD', t, windowMs: 5 * MINUTE_MS }).new_order_impulse_net.state, 'UNVERIFIED');
  const epochBreak = obs.map((o) => (o.kind === 'L3_ORDER_EVENT' && o.receivedTs > t - 5 * MINUTE_MS && o.receivedTs <= t ? { ...o, epochId: 'KRAKEN_SPOT:ws-l3:2' } : o)); assert.equal(l3Features(epochBreak, { spotSymbol: 'BTC/USD', t, windowMs: 5 * MINUTE_MS }).new_order_impulse_net.state, 'PARTIAL');
  for (const reason of ['UNKNOWN_ORDER', 'DUPLICATE_ADD', 'CROSSED', 'OVERFLOW', 'CHECKSUM_MISMATCH']) { const b = createL3Book({ symbol: 'BTC/USD', depth: 10, maxOrders: reason === 'OVERFLOW' ? 3 : 1000 }); const snap = b.applySnapshot({ bids: FX.bids, asks: FX.asks }, { receivedTs: TL3 }); if (reason === 'OVERFLOW') { assert.equal(snap.reason, 'OVERFLOW'); continue; } const a0 = FX.asks[0]; const upd = reason === 'UNKNOWN_ORDER' ? { asks: [{ event: 'modify', order_id: 'GHOST', limit_price: a0.limit_price, order_qty: '1', timestamp: a0.timestamp }], bids: [] } : reason === 'DUPLICATE_ADD' ? { asks: [{ event: 'add', order_id: a0.order_id, limit_price: a0.limit_price, order_qty: '1', timestamp: a0.timestamp }], bids: [] } : reason === 'CROSSED' ? { bids: [{ event: 'add', order_id: 'X', limit_price: '45000.0', order_qty: '1', timestamp: a0.timestamp }], asks: [] } : { asks: [{ event: 'delete', order_id: a0.order_id, limit_price: a0.limit_price, order_qty: '0', timestamp: a0.timestamp }], bids: [], checksum: 1 }; assert.equal(b.applyUpdate({ checksum: null, ...upd }, { receivedTs: TL3 + 1 }).reason, reason); assert.equal(b.synchronized, false); }
});

test('W12. NO silent capture loss: an admitted L3 snapshot the recorder cannot persist (line bound) is counted AND leaves a durable DROPPED / RECORD_REJECTED coverage marker; the sealed manifest says capture PARTIAL with the counts (never COMPLETE); readEdgeCapture refuses a manifest claiming COMPLETE beside rejection markers or PARTIAL without its counts; the evaluation coverage summary carries the loss as dark gap records', async () => {
  const subjects = sampleSubjects(); const raw = structuredClone(H.policyWith({ providers: ['KRAKEN_SPOT'] })); raw.providers.KRAKEN_SPOT.l3 = { ...raw.providers.KRAKEN_SPOT.l3, enabled: true, keyEnv: 'L3K', secretEnv: 'L3S', maxSymbols: 1 }; const policy = loadPolicy(raw);
  let t = TL3; const clock = () => t; const sw = createScriptedWebSocket({ ackSubscriptions: false }); const logs = [];
  const fixture = await H.startHttpFixture({ 'GET /0/public/AssetPairs': { json: H.KRAKEN_ASSET_PAIRS }, '*': (req) => (req.path === '/0/private/GetApiKeyInfo' ? { json: { error: [], result: { permissions: ['query-funds', 'create-ws-token'], validUntil: '0', nonceWindow: 0 } } } : req.path === '/0/private/GetWebSocketsToken' ? { json: { error: [], result: { token: 'TOKEN-VALUE-XYZ', expires: 900 } } } : { status: 404, json: { error: 'nope' } }) });
  const root = mkdtempSync(path.join(tmpdir(), 'w12-root-')); const out = path.join(mkdtempSync(path.join(tmpdir(), 'w12-out-')), 'edge');
  const sleep = async () => { await new Promise((r) => setTimeout(r, 40)); const sock = sw.latest(); const subs = sock.sent.map((s) => JSON.parse(s)).filter((m) => m.method === 'subscribe'); assert.equal(subs.length, 1); sock.deliver({ method: 'subscribe', success: true, result: { channel: 'level3', symbol: 'BTC/USD', depth: 10 } }); sock.deliver({ channel: 'level3', type: 'snapshot', data: [{ ...FX, symbol: 'BTC/USD', timestamp: '2026-09-10T12:00:00.100000000Z' }] }); t += 20_000; };
  try {
    const limits = { ...RESOURCE_DEFAULTS, observationLineBytes: 1_500 }; // the fixture snapshot (28 orders) never fits; coverage observations do
    const r = await runEdgeCapture({ policy, subjects: { ...subjects, subjects: subjects.subjects.filter((s) => s.canonicalCoin === 'BTC') }, env: { L3K: 'k', L3S: Buffer.from('s').toString('base64') }, out, durationSeconds: 1, clock, fetchImpl: H.fetchFor(fixture), WebSocketImpl: sw.WebSocketImpl, researchRoot: root, sleep, limits, log: (m) => logs.push(m) });
    assert.equal(r.ok, true, JSON.stringify(r.error)); assert.equal(r.capture, 'PARTIAL'); assert.equal(r.counters.rejected, 1); assert.equal(r.counters.dropMarkers, 1); assert.ok(logs.some((m) => /durable DROPPED marker written/.test(m)));
    const edge = readEdgeCapture(out); assert.ok(!edge.observations.some((o) => o.kind === 'L3_BOOK_SNAPSHOT'), 'the snapshot itself was not persisted'); assert.equal(edge.capture, 'PARTIAL'); assert.equal(edge.rejected, 1); assert.equal(edge.bundle.manifest.summary.capture, 'PARTIAL'); assert.equal(edge.bundle.manifest.summary.rejected, 1);
    const marker = edge.coverage.find((c) => c.state === 'DROPPED'); assert.ok(marker); assert.deepEqual(marker.reasonCodes, ['RECORD_REJECTED']); assert.equal(marker.kind, 'L3_BOOK_SNAPSHOT'); assert.equal(marker.family, 'L3_MICROSTRUCTURE'); assert.equal(marker.droppedCount, 1); assert.equal(marker.startTs, TL3, 'the receipt clock of the rejected record');
    assert.ok(readFileSync(path.join(out, 'coverage.jsonl'), 'utf8').includes('RECORD_REJECTED'), 'durable');
  } finally { await fixture.close(); }
  // the reader law over hand-sealed bundles: COMPLETE beside a marker, or PARTIAL without its count, is refused; a truthful PARTIAL loads and counts as a dark gap
  const obs = corpus({ hours: 2 }); const marker = makeCoverage({ provider: 'KRAKEN_SPOT', endpointId: 'ws-l3', subjectId: subjectId(SPOT), family: 'L3_MICROSTRUCTURE', kind: 'L3_BOOK_SNAPSHOT', state: 'DROPPED', reasonCodes: ['RECORD_REJECTED'], startTs: T0, endTs: T0, observationCount: 0, droppedCount: 1, epochId: null, sequenceStart: null, sequenceEnd: null });
  const lying = sealSources(mkdtempSync(path.join(tmpdir(), 'w12a-')), obs, { darkCov: [darkCoverage(), marker], captureClaim: 'COMPLETE' }); assert.throws(() => readEdgeCapture(lying.edgeDir), /never claims COMPLETE while omitting/);
  const truthful = sealSources(mkdtempSync(path.join(tmpdir(), 'w12b-')), obs, { darkCov: [darkCoverage(), marker] }); const e = readEdgeCapture(truthful.edgeDir); assert.equal(e.capture, 'PARTIAL'); assert.equal(readEdgeSources({ edgeCaptureDir: truthful.edgeDir, captureDir: truthful.capDir }).coverageSummary.darkGapRecords, 1);
  assert.ok(QUALITY_REASON_CODES.includes('RECORD_REJECTED'));
});

test('W13. CHARTS partial acquisition stays explicit coverage truth: a later page failing after good rows (ACQUISITION_INCOMPLETE), a page cap (PAGINATION_INCOMPLETE), a non-advancing cursor and misaligned buckets (MISALIGNED_BUCKET) all keep the retained rows AND name the incompleteness in the coverage record with meta.acquisition PARTIAL; the evaluation never turns such an interval into COMPLETE support (COVERAGE_INCOMPLETE); a historical re-fetch is a new vintage known at fetch time; units stay NATIVE / UNIT_UNVERIFIED', async () => {
  const I = 300; const CH = { ...CHARTS_DEFAULTS, enabled: true, intervalsS: [60, 300, 3600], maxPagesPerRequest: 3, maxCallsPerDay: 100 }; const b = (k) => Math.floor(TL3 / IMS) * I - I * k;
  const page = (ts, more) => ({ result: { timestamp: ts, data: ts.map((_, i) => 100 + i), more }, errors: [] });
  let calls = 0; const fixture = await H.startHttpFixture({ 'GET /derivatives/api/v3/instruments': { json: H.KF_INSTRUMENTS }, '*': (req) => { calls += 1; const since = Number(req.query.since); if (req.query.mode !== undefined) return { status: 500, json: {} }; if (since === b(40)) return { json: page([b(40), b(39)], true) }; if (since === b(38)) return { status: 500, json: { errors: ['boom'] } }; if (since === b(30)) return { json: page([b(30), b(29) + 7], false) }; return { json: page([since / 1, since + I], true) }; } });
  let t = TL3; const clock = () => t; const transport = createHttpTransport({ fetchImpl: H.fetchFor(fixture), clock }); const d = createKrakenDerivativesClient({ transport, clock }); await d.loadInstruments(); const charts = createKrakenChartsClient({ transport, clock, resolveInstrument: d.resolveInstrument, charts: CH });
  try {
    const laterFail = await charts.fetchAnalytics({ symbol: 'PF_XBTUSD', analyticsType: 'open-interest', intervalS: I, sinceTs: b(40) * 1000, vintage: 'HISTORICAL_FETCH', maxPages: 3 });
    assert.equal(laterFail.ok, true, 'retained good rows stay available'); assert.equal(laterFail.observations.length, 2); assert.ok(laterFail.failure); assert.equal(laterFail.meta.acquisition, 'PARTIAL'); assert.ok(laterFail.coverage[0].reasonCodes.includes('ACQUISITION_INCOMPLETE')); assert.equal(laterFail.coverage[0].state, 'OBSERVED'); assert.equal(laterFail.coverage[0].endTs, (b(39) + I) * 1000);
    const capped = await charts.fetchAnalytics({ symbol: 'PF_XBTUSD', analyticsType: 'open-interest', intervalS: I, sinceTs: b(20) * 1000, vintage: 'HISTORICAL_FETCH', maxPages: 2 }); assert.equal(capped.meta.acquisition, 'PARTIAL'); assert.ok(capped.coverage[0].reasonCodes.includes('PAGINATION_INCOMPLETE')); assert.equal(capped.observations.length, 4);
    const mis = await charts.fetchAnalytics({ symbol: 'PF_XBTUSD', analyticsType: 'open-interest', intervalS: I, sinceTs: b(30) * 1000, vintage: 'HISTORICAL_FETCH', maxPages: 1 }); assert.equal(mis.meta.misaligned, 1); assert.equal(mis.meta.acquisition, 'PARTIAL'); assert.ok(mis.coverage[0].reasonCodes.includes('MISALIGNED_BUCKET')); assert.equal(mis.observations.length, 1); assert.equal(mis.observations[0].payload.vintage, 'HISTORICAL_FETCH'); assert.equal(mis.observations[0].knownAtTs, mis.observations[0].receivedTs); assert.equal(mis.observations[0].payload.normalizedUnit, 'NATIVE'); assert.ok(mis.observations[0].quality.reasonCodes.includes('UNIT_UNVERIFIED'));
    const full = await charts.fetchAnalytics({ symbol: 'PF_XBTUSD', analyticsType: 'open-interest', intervalS: I, sinceTs: b(10) * 1000, vintage: 'HISTORICAL_FETCH', maxPages: 1 }); assert.equal(full.meta.acquisition, full.meta.more ? 'PARTIAL' : 'COMPLETE');
    for (const r of [laterFail, capped, mis]) assert.ok(r.coverage[0].reasonCodes.every((c) => QUALITY_REASON_CODES.includes(c)));
  } finally { await fixture.close(); }
  // the evaluation: a derivatives feature whose lookback touches an incomplete acquisition is PARTIAL / COVERAGE_INCOMPLETE, never COMPLETE
  const t2 = T0 + HOUR; const obs = corpus({ hours: 2 }); const complete = derivativesFeatures(obs, { futuresSymbol: 'PF_XBTUSD', t: t2, intervalMs: IMS }); assert.equal(complete.oi_bucket_change.state, 'COMPLETE');
  const incomplete = darkCoverage({ state: 'OBSERVED', reasonCodes: ['PAGINATION_INCOMPLETE'], startTs: t2 - 3 * IMS, endTs: t2 - IMS, observationCount: 2 }); const gated = derivativesFeatures(obs, { futuresSymbol: 'PF_XBTUSD', t: t2, intervalMs: IMS, coverage: [incomplete] }); assert.equal(gated.oi_bucket_change.state, 'PARTIAL'); assert.equal(gated.oi_bucket_change.value, null); assert.ok(gated.oi_bucket_change.reasons.includes('COVERAGE_INCOMPLETE'));
  const old = darkCoverage({ state: 'OBSERVED', reasonCodes: ['PAGINATION_INCOMPLETE'], startTs: t2 - 12 * HOUR, endTs: t2 - 10 * HOUR, observationCount: 2 }); assert.equal(derivativesFeatures(obs, { futuresSymbol: 'PF_XBTUSD', t: t2, intervalMs: IMS, coverage: [old] }).oi_bucket_change.state, 'COMPLETE', 'an incomplete interval far before the lookback does not touch it');
  const future = darkCoverage({ state: 'OBSERVED', reasonCodes: ['PAGINATION_INCOMPLETE'], startTs: t2 + IMS, endTs: t2 + 2 * IMS, observationCount: 2 }); assert.equal(derivativesFeatures(obs, { futuresSymbol: 'PF_XBTUSD', t: t2, intervalMs: IMS, coverage: [future] }).oi_bucket_change.state, 'COMPLETE', 'a record not yet known at t is invisible');
  const row = featureRow(obs, DECL(), t2, [incomplete]); assert.equal(row.support.oi_bucket_change.state, 'PARTIAL'); assert.equal(row.features.oi_bucket_change, null); assert.deepEqual([...CHARTS_INCOMPLETE_CODES], ['PAGINATION_INCOMPLETE', 'ACQUISITION_INCOMPLETE', 'MISALIGNED_BUCKET', 'PROVIDER_ERROR', 'RECORD_REJECTED']);
  void bucket; void FUT; void l3events;
});
