// SERPENT PAPER — the ONE profile, the derived sensor inventory, the shared sensor snapshot, the read-only preflight, the launch
// law and the dark-capture state law. Offline: no network, no database (a scripted database stub stands in for the read-only
// storage checks), no secret VALUE anywhere (fake secrets are planted in the environment to prove they never leak).
import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, rmSync, existsSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { readdirSync } from 'node:fs';
import { loadProfile, profileError, profileEnvironment, applyProfileEnvironment, secretPresence, mergeOverlay, FORCED_ENV, SECRET_ENV_NAMES, PROFILE_GROUPS, RUNTIME_STATES, DESIRED_STATES, BLOCKER_POLICIES } from '../paper/profile.js';
import { loadConfig, resetConfigCache, profileOverlay, repoRoot } from '../lib/config.js';
import { sensorInventory, CLASSIFICATIONS, INVENTORY_GROUPS, ROW_KEYS as INVENTORY_KEYS, inventoryRow } from '../paper/inventory.js';
import { sensorSnapshot, snapshotRow, SNAPSHOT_GROUPS, ROW_KEYS as SNAPSHOT_KEYS, EXTRA_STATES } from '../paper/readiness.js';
import { runPreflight, renderPreflight, BLOCKER_GROUPS, SECTIONS } from '../paper/preflight.js';
import { prepareLaunch, launchPaper, COMPOSITION_ORDER } from '../paper/launch.js';
import { readPolicyFile, readSubjectsFile } from '../market-lab/commands.js';
import { darkStateOf, startDarkCapture, DARK_CAPTURE_STATES, STATUS_FILE } from '../paper/dark-capture.js';
import { PROVIDER_IDS as MARKET_PROVIDER_IDS } from '../market-lab/contracts.js';
import { PROVIDER_IDS as OFFICIAL_IDS } from '../rumor2/registry.js';
import { SOCIAL_PROVIDER_IDS } from '../rumor2/social-registry.js';
import { SCHEMA_VERSION } from '../persistence/schema.js';
import { loadPolicy } from '../market-lab/policy.js';

const ROOT = repoRoot(); const read = (f) => readFileSync(path.join(ROOT, f), 'utf8');
const FAKE = { SERPENT_CONTROL_PASSWORD: 'pw-FAKE-VALUE-1', DATABASE_URL: 'postgresql://user:SeCrEt-FAKE@127.0.0.1:1/db', X_BEARER_TOKEN: 'AAAAAAAAAAAAAAAAAAAAAFAKE-BEARER-VALUE', ANTHROPIC_API_KEY: 'sk-ant-FAKE-VALUE', KRAKEN_L3_DATA_API_KEY: 'l3-key-FAKE-VALUE', KRAKEN_L3_DATA_API_SECRET: Buffer.from('l3-secret-FAKE').toString('base64'), FRED_API_KEY: 'fred-FAKE-VALUE' };
const leaks = (s) => Object.values(FAKE).some((v) => s.includes(v));
const VALUE_LIKE = /sk-ant|sk_live|Bearer [A-Za-z0-9]|eyJ[A-Za-z0-9_-]{10,}|postgres(ql)?:\/\/[^<\s]+:[^<\s]+@/i;
const T = Date.parse('2026-09-11T12:00:00Z');
const tmp = (p = 'paper-') => mkdtempSync(path.join(tmpdir(), p));
const writeJson = (dir, rel, obj) => { const f = path.join(dir, rel); mkdirSync(path.dirname(f), { recursive: true }); writeFileSync(f, JSON.stringify(obj)); return f; };
// a scripted READ-ONLY database stub for the storage section: answers the exact queries the preflight makes, nothing else
const dbStub = ({ schema = SCHEMA_VERSION, account = true, held = false, reachable = true, tableMissing = false } = {}) => () => ({ schema: null, queries: [], async connect() { return reachable; }, async query(text, params) { this.queries.push({ text, params }); if (/serpent_schema_migrations/.test(text)) { if (tableMissing) { const e = new Error('relation does not exist'); e.code = '42P01'; throw e; } return { rows: [{ v: schema }] }; } if (/serpent_execution_accounts/.test(text)) return { rows: account ? [{ '?column?': 1 }] : [] }; if (/pg_locks/.test(text)) return { rows: [{ held }] }; throw new Error(`unexpected query ${text}`); }, async end() { this.ended = true; } });

test('P-01. the profile: closed law (runtimeMode PAPER, authority DISABLED, judge PAPER / no private / no orders, exact groups, desiredState / blockerPolicy vocabularies, no overlay on locks / fees / cost, no secret value); the derived environment carries enables and repo paths only; applying it FORCES the authority names over an operator environment that says LIVE / orders; the env example names every secret and carries no value', () => {
  const p = loadProfile(); assert.equal(p.runtimeMode, 'PAPER'); assert.deepEqual(Object.keys(p.groups), [...PROFILE_GROUPS]); assert.equal(profileError(p), null);
  const raw = JSON.parse(read('config/paper-runtime.json'));
  const bad = (mut, re) => { const x = structuredClone(raw); mut(x); assert.match(profileError(x) ?? '', re); };
  bad((x) => { x.runtimeMode = 'LIVE'; }, /PAPER/); bad((x) => { x.authority.judgeMode = 'LIVE_ARMED'; }, /judgeMode PAPER/); bad((x) => { x.authority.judgeAllowOrders = true; }, /allowOrders false/); bad((x) => { x.authority.realMoney = 'ENABLED'; }, /DISABLED/); bad((x) => { x.groups.judge.judge.mode = 'LIVE_UNARMED'; }, /judge\.judge/); bad((x) => { x.configOverlay.locks = { hardPct: 50 }; }, /locks/); bad((x) => { x.configOverlay.fees = {}; }, /fees/); bad((x) => { x.groups.extra = {}; }, /groups must be exactly/); bad((x) => { x.groups.social.X_OFFICIAL.desiredState = 'MAYBE'; }, /desiredState/); bad((x) => { x.groups.social.X_OFFICIAL.blockerPolicy = 'IGNORE'; }, /blockerPolicy/); bad((x) => { x.groups.persistence.localJournalFallback.desiredState = 'ON'; }, /never a silent fallback/); bad((x) => { x.groups.darkEdgeCapture.krakenL3.gate = 'ANY_KEY'; }, /SAFE_L3_DATA_KEY/); bad((x) => { x.groups.social.X_OFFICIAL.note = 'sk-ant-FAKE-VALUE'; }, /value-like secret/); bad((x) => { x.groups.cockpit.server.SERPENT_CONTROL_PASSWORD = 'hunter2'; }, /assigns a value to the secret name/); bad((x) => { x.files.judgePolicy = '/etc/judge.json'; }, /repo-relative/);
  for (const g of PROFILE_GROUPS) for (const [k, row] of Object.entries(p.groups[g])) { if (g === 'marketResearch' && k === 'providers') { for (const r of Object.values(row)) { assert.ok(DESIRED_STATES.includes(r.desiredState)); assert.ok(BLOCKER_POLICIES.includes(r.blockerPolicy)); } continue; } assert.ok(DESIRED_STATES.includes(row.desiredState), `${g}.${k}`); assert.ok(BLOCKER_POLICIES.includes(row.blockerPolicy)); }
  const env = profileEnvironment(p); assert.equal(env.JUDGE_MODE, 'PAPER'); assert.equal(env.JUDGE_ALLOW_PRIVATE, 'false'); assert.equal(env.JUDGE_ALLOW_ORDERS, 'false'); assert.equal(env.JUDGE_ENABLED, 'true'); assert.equal(env.MARKET_RESEARCH_ENABLED, 'true'); assert.equal(env.RUMOR2_ENABLED, 'true'); assert.equal(env.RUMOR2_SOCIAL_BLUESKY_ENABLED, 'true'); assert.equal(env.RUMOR2_EDGAR_ENABLED, 'true'); assert.equal(env.RUMOR2_OFAC_ENABLED, 'true'); assert.equal(env.RUMOR2_ALLOW_LOCAL_JOURNAL, 'false'); assert.equal(env.GATEWAY_ENABLED, 'true'); assert.equal(env.WIDEEYE_ENABLED, 'true'); assert.equal(env.RUMOR2_SOCIAL_X_ENABLED, 'true', 'requested: the X governor decides (credential -> budgets -> paid smoke)'); assert.equal(env.PRESS_ENABLED, 'true'); assert.equal(env.PRESS_SOURCES, 'COINDESK_NEWS,THEBLOCK_NEWS,COINTELEGRAPH_NEWS,DECRYPT_NEWS', 'only the ON publisher rows are selected; licensed / OFF rows are never named'); assert.equal(env.INFRA_OBS_ENABLED, 'true'); assert.equal(env.SOCIAL_VIDEO_ENABLED, 'true', 'requested: the video collector gate decides (key -> own queries -> explicit budget)'); assert.equal(env.INFRA_SOURCES, 'NOAA_SWPC,RIPE_RIS,CLOUDFLARE_RADAR', 'REQUEST rows are selected; their own gate (config / credential) decides with zero calls');
  assert.ok(env.JUDGE_POLICY.endsWith('config/judge.paper.json') && env.MARKET_RESEARCH_POLICY.endsWith('config/market-research.paper.json')); for (const n of SECRET_ENV_NAMES) assert.ok(!(n in env), `${n} never derived`);
  const hostile = { JUDGE_MODE: 'LIVE_ARMED', JUDGE_ALLOW_PRIVATE: 'true', JUDGE_ALLOW_ORDERS: 'true', RUMOR2_SOCIAL_MODE: 'REPLAY', ...FAKE }; const applied = applyProfileEnvironment(p, hostile);
  assert.equal(hostile.JUDGE_MODE, 'PAPER'); assert.equal(hostile.JUDGE_ALLOW_PRIVATE, 'false'); assert.equal(hostile.JUDGE_ALLOW_ORDERS, 'false'); assert.equal(hostile.RUMOR2_SOCIAL_MODE, 'LIVE'); assert.deepEqual(applied.overridden.map((o) => o.name).sort(), ['JUDGE_ALLOW_ORDERS', 'JUDGE_ALLOW_PRIVATE', 'JUDGE_MODE', 'RUMOR2_SOCIAL_MODE']); assert.ok(applied.overridden.every((o) => o.was === '<value>' || o.name === 'JUDGE_MODE'), 'overrides never echo a value except the mode word'); assert.equal(hostile.X_BEARER_TOKEN, FAKE.X_BEARER_TOKEN, 'secrets untouched'); assert.deepEqual(Object.keys(FORCED_ENV).sort(), ['JUDGE_ALLOW_ORDERS', 'JUDGE_ALLOW_PRIVATE', 'JUDGE_MODE', 'RUMOR2_SOCIAL_MODE']);
  const pres = secretPresence(p, hostile); assert.equal(pres.X_BEARER_TOKEN, true); assert.equal(pres.COINGLASS_API_KEY, false); assert.ok(!leaks(JSON.stringify(pres)));
  const example = read('.env.paper.example'); for (const n of SECRET_ENV_NAMES) assert.ok(example.includes(n), `${n} documented`); assert.ok(!VALUE_LIKE.test(example)); for (const line of example.split('\n')) { const m = /^#?\s*([A-Z0-9_]+)=(.*)$/.exec(line); if (m && SECRET_ENV_NAMES.includes(m[1])) assert.match(m[2], /^<.*>|^$/, `${m[1]} carries a placeholder only`); }
  for (const f of ['config/paper-runtime.json', 'config/market-research.paper.json', 'config/market-subjects.paper.json', 'config/judge.paper.json']) assert.ok(!VALUE_LIKE.test(read(f)) && !/"api[_-]?key"\s*:\s*"[A-Za-z0-9+/]{16,}/i.test(read(f)), `${f} carries no value-like secret`);
  const mr = loadPolicy(JSON.parse(read('config/market-research.paper.json'))); assert.equal(mr.mode, 'LIVE_OBSERVATION'); assert.equal(mr.providers.BYBIT.enabled, false); assert.equal(mr.providers.COINGLASS.enabled, false); assert.equal(mr.providers.KRAKEN_DERIVATIVES.charts.enabled, true); assert.equal(mr.providers.KRAKEN_SPOT.l3.enabled, true); assert.equal(mr.model.enabled, false); assert.equal(mr.model.maxEstimatedUsdPerDay, 0); assert.ok(Object.values(mr.providers).every((x) => x.limits.maxCallsPerDay <= 1000), 'conservative shipped caps, never maxed out');
  const jp = JSON.parse(read('config/judge.paper.json')); assert.equal(jp.mode, 'PAPER'); assert.equal(jp.execution.adapter, 'PAPER'); assert.ok(jp.live === null || jp.live === undefined, 'no LIVE block in the paper Judge policy'); assert.equal(read('config/judge.paper.json'), read('judge/samples/policy.paper-reference.json'), 'the paper Judge policy IS the reviewed reference (no threshold retune)');
});

test('P-02. the config overlay: COBRA_PROFILE deep-merges the profile overlay onto cobra.config.json for EVERY reader (gateway / wide eye / rumint / universe expansion on) and never touches locks, paper bankroll, fees or cost; a profile that is not PAPER or that overlays locks is refused; the base config without a profile is unchanged', () => {
  const saved = process.env.COBRA_PROFILE; try {
    delete process.env.COBRA_PROFILE; resetConfigCache(); const base = loadConfig(); assert.equal(base.gateway.enabled, false); assert.equal(profileOverlay({}), null);
    process.env.COBRA_PROFILE = 'config/paper-runtime.json'; resetConfigCache(); const c = loadConfig(); assert.equal(c.gateway.enabled, true); assert.deepEqual(c.gateway.sources, { kraken: true, krakenSystem: true, coinbase: true, okx: true }); assert.equal(c.wideeye.enabled, true); assert.equal(c.rumint.enabled, true); assert.equal(c.universeExpansion.enabled, true); assert.deepEqual(c.locks, base.locks); assert.deepEqual(c.paper, base.paper); assert.deepEqual(c.fees, base.fees); assert.deepEqual(c.cost, base.cost); assert.equal(c.gateway.pollSec, base.gateway.pollSec, 'unmentioned keys survive the merge');
    const dir = tmp('prof-'); const live = writeJson(dir, 'live.json', { ...JSON.parse(read('config/paper-runtime.json')), runtimeMode: 'LIVE' }); assert.throws(() => profileOverlay({ COBRA_PROFILE: live }), /runtimeMode must be PAPER/);
    const locks = writeJson(dir, 'locks.json', { ...JSON.parse(read('config/paper-runtime.json')), configOverlay: { locks: { hardPct: 99 } } }); assert.throws(() => profileOverlay({ COBRA_PROFILE: locks }), /may not touch locks/);
    assert.deepEqual(mergeOverlay({ a: { b: 1, c: 2 }, d: 3 }, { a: { c: 5 }, e: 6 }), { a: { b: 1, c: 5 }, d: 3, e: 6 });
  } finally { if (saved === undefined) delete process.env.COBRA_PROFILE; else process.env.COBRA_PROFILE = saved; resetConfigCache(); }
});

test('P-03. the sensor inventory is derived from the ACTUAL registries: every market-lab provider, every RUMOR official ear, every social provider, the gateway sources, the core / decision components and the doctrine-required transports that are NOT_PRESENT — each classified in the closed vocabulary with module, composition path, enable, credential NAMES, paid, governor, retention, transports, truth, replay, authority, blocker and smoke evidence; credential-gated rows flip their blocker with env presence (never their classification); the checked-in inventory equals a fresh derivation; no secret', () => {
  const inv = sensorInventory({ env: {}, clock: () => T }); assert.equal(inv.inventoryVersion, 'serpent-sensor-inventory-1');
  for (const r of inv.rows) { assert.deepEqual(Object.keys(r), [...INVENTORY_KEYS]); assert.ok(CLASSIFICATIONS.includes(r.classification)); assert.ok(INVENTORY_GROUPS.includes(r.group)); assert.ok(Array.isArray(r.credentialEnv)); assert.ok(r.paperDesiredState !== null); assert.ok(r.classification !== 'NOT_PRESENT' || r.paperDesiredState === 'OFF'); }
  const ids = inv.rows.map((r) => r.id); for (const id of MARKET_PROVIDER_IDS) assert.ok(ids.includes(id), id); for (const id of OFFICIAL_IDS) assert.ok(ids.includes(id), id); for (const id of SOCIAL_PROVIDER_IDS) assert.ok(ids.includes(id), id);
  for (const id of ['TAPE', 'WIDEEYE', 'UNIVERSE_EXPANSION', 'COST_EXECUTABILITY', 'GATEWAY_KRAKEN_STATUS', 'GATEWAY_KRAKEN_SYSTEM', 'GATEWAY_COINBASE_STATUS', 'GATEWAY_OKX_STATUS', 'RUMINT_STOCKTWITS_AGGREGATE', 'KRAKEN_CHARTS_DARK', 'KRAKEN_L3_DARK', 'SOCRATES', 'JUDGE', 'WATCH', 'PAPER_EXECUTION', 'GOVERNANCE_TALLY', 'META_REALTIME_TRANSPORT', 'TIKTOK_REALTIME_TRANSPORT', 'FARCASTER_LIVE_TRANSPORT']) assert.ok(ids.includes(id), id);
  assert.equal(new Set(ids).size, ids.length, 'unique ids'); assert.equal(inv.counts.DEPRECATED, 0); assert.deepEqual(inv.rows.filter((r) => r.classification === 'NOT_PRESENT').map((r) => r.id).sort(), ['BLOOMBERG_NEWS', 'FARCASTER_LIVE_TRANSPORT', 'META_REALTIME_TRANSPORT', 'REUTERS_NEWS', 'TIKTOK_REALTIME_TRANSPORT'], 'every requested-but-absent source is accounted for as NOT_PRESENT with its exact blocker (never silently dropped, never called complete)'); for (const r of inv.rows.filter((x) => x.classification === 'NOT_PRESENT')) assert.match(r.readinessBlocker, /NOT_IMPLEMENTED|EXTERNAL_ACCESS_BLOCKED/, r.id);
  for (const r of inv.rows) if (r.module) for (const m of r.module.split(/ \+ |, | \(/)[0].split(' ')) if (m.endsWith('.js')) assert.ok(existsSync(path.join(ROOT, m)), `${r.id} module ${m} exists`);
  assert.equal(inventoryRow(inv, 'BYBIT').classification, 'CODE_PATH_COMPLETE_EXTERNAL_ACCESS_BLOCKED'); assert.equal(inventoryRow(inv, 'BYBIT').readinessBlocker, 'BLOCKED_GEOGRAPHY'); assert.equal(inventoryRow(inv, 'FARCASTER_OFFICIAL').classification, 'FOUNDATION_ONLY'); assert.equal(inventoryRow(inv, 'REDDIT_OFFICIAL').classification, 'CODE_PATH_COMPLETE_EXTERNAL_ACCESS_BLOCKED'); assert.equal(inventoryRow(inv, 'BLUESKY_OFFICIAL').classification, 'OPERATIONAL_PUBLIC'); assert.equal(inventoryRow(inv, 'KRAKEN_SPOT').classification, 'OPERATIONAL_PUBLIC'); assert.equal(inventoryRow(inv, 'EDGAR_OFFICIAL').readinessBlocker, 'CONFIG_REQUIRED:EDGAR_WHITELIST'); assert.equal(inventoryRow(inv, 'SEC_OFFICIAL').readinessBlocker, 'CONFIG_REQUIRED:SERPENT_HTTP_CONTACT'); assert.equal(inventoryRow(inv, 'KRAKEN_L3_DARK').decisionAuthority, 'NONE'); assert.equal(inventoryRow(inv, 'KRAKEN_CHARTS_DARK').paperAuthority, 'NONE');
  const x0 = inventoryRow(inv, 'X_OFFICIAL'); assert.equal(x0.classification, 'OPERATIONAL_CREDENTIAL_GATED'); assert.equal(x0.readinessBlocker, 'CREDENTIAL_MISSING'); assert.equal(x0.paid, true);
  const x1 = inventoryRow(sensorInventory({ env: { X_BEARER_TOKEN: FAKE.X_BEARER_TOKEN }, clock: () => T }), 'X_OFFICIAL'); assert.equal(x1.readinessBlocker, 'BUDGET_NOT_CONFIGURED'); assert.equal(x1.classification, 'OPERATIONAL_CREDENTIAL_GATED');
  const x2 = inventoryRow(sensorInventory({ env: { X_BEARER_TOKEN: FAKE.X_BEARER_TOKEN, RUMOR2_SOCIAL_X_MAX_DAILY_POST_READS: '100', RUMOR2_SOCIAL_X_MAX_MONTHLY_POST_READS: '1000', RUMOR2_SOCIAL_X_MAX_ESTIMATED_DAILY_USD: '1' }, clock: () => T }), 'X_OFFICIAL'); assert.equal(x2.readinessBlocker, 'READY_REQUIRES_EXPLICIT_PAID_SMOKE');
  const withKeys = sensorInventory({ env: { ...FAKE, SERPENT_HTTP_CONTACT: 'ops@example.invalid', RUMOR2_EDGAR_CIKS: '0000320193' }, clock: () => T }); assert.equal(inventoryRow(withKeys, 'EDGAR_OFFICIAL').readinessBlocker, null); assert.equal(inventoryRow(withKeys, 'FRED').readinessBlocker, null); assert.match(inventoryRow(withKeys, 'KRAKEN_L3_DARK').readinessBlocker, /KEY_PRESENT_UNPROVEN/); assert.equal(inventoryRow(withKeys, 'COINGLASS').readinessBlocker, null === null ? inventoryRow(withKeys, 'COINGLASS').readinessBlocker : null); assert.match(inventoryRow(withKeys, 'COINGLASS').readinessBlocker ?? 'BLOCKED_BUDGET', /BLOCKED_BUDGET|CREDENTIAL_MISSING/, 'a paid plan stays blocked without attestation even with a key');
  assert.ok(!leaks(JSON.stringify(withKeys))); assert.deepEqual(withKeys.secretNamesPresent.sort(), Object.keys(FAKE).sort());
  const shipped = JSON.parse(read('docs/sensor-inventory.paper.json')); const fresh = JSON.parse(JSON.stringify(sensorInventory({ env: {}, clock: () => shipped.generatedTs }))); assert.deepEqual(shipped, fresh, 'docs/sensor-inventory.paper.json is the derivation (regenerate with: node bin/cobra.js paper inventory)');
});

test('P-04. the shared sensor snapshot: a sense is ACTIVE only from a FRESH status record (tape LIVE within 30 s; stale -> ACTIVE_DEGRADED; OFFLINE -> BLOCKED_PROVIDER; nothing -> NOT_OBSERVED); RUMOR ears, Bluesky, X governor states, research clients, dark capture states, Judge / Watch from the projection file bound to PAPER; a LIVE projection or a LIVE env mode is BLOCKED, never green; every state in the closed vocabulary, zero UNKNOWN rows, groups exact, no secret', () => {
  const dir = tmp('snap-'); const p = loadProfile(); const env = { ...profileEnvironment(p), ...FAKE, SERPENT_HTTP_CONTACT: 'ops@example.invalid' }; const base = { profile: p, env, dataDir: dir, now: T };
  const s0 = sensorSnapshot(base); assert.deepEqual(Object.keys(s0.groups), [...SNAPSHOT_GROUPS]); for (const r of s0.rows) { assert.deepEqual(Object.keys(r), [...SNAPSHOT_KEYS]); assert.ok(RUNTIME_STATES.includes(r.state) || EXTRA_STATES.includes(r.state) || /^CONFIG_REQUIRED:/.test(r.state), r.state); assert.ok(!/UNKNOWN/.test(r.state)); }
  assert.equal(snapshotRow(s0, 'TAPE').state, 'NOT_OBSERVED'); assert.equal(snapshotRow(s0, 'JUDGE').state, 'NOT_OBSERVED', 'DATABASE_URL present, no projection yet'); assert.equal(snapshotRow(s0, 'X_OFFICIAL').state, 'BLOCKED_BUDGET', 'bearer present without budgets'); assert.equal(snapshotRow(s0, 'EDGAR_OFFICIAL').state, 'CONFIG_REQUIRED:EDGAR_WHITELIST'); assert.equal(snapshotRow(s0, 'SEC_OFFICIAL').state, 'NOT_OBSERVED', 'contact configured -> the gate passes'); assert.equal(snapshotRow(s0, 'KRAKEN_L3_DARK').state, 'KEY_PRESENT_UNPROVEN'); assert.equal(snapshotRow(s0, 'SOCRATES_MODEL').state, 'DISABLED_BY_PAPER_POLICY'); assert.equal(snapshotRow(s0, 'FRED').state, 'NOT_OBSERVED'); assert.equal(snapshotRow(s0, 'COINGLASS').state, 'DISABLED_BY_PAPER_POLICY'); assert.equal(snapshotRow(s0, 'BYBIT').state, 'DISABLED_BY_PAPER_POLICY');
  assert.ok(!leaks(JSON.stringify(s0))); assert.equal(s0.authority.realMoney, 'DISABLED'); assert.equal(s0.authority.judgeMode, 'PAPER');
  writeJson(dir, 'tape/status.json', { ts: new Date(T - 5000).toISOString(), tsMs: T - 5000, state: 'LIVE', coins: { BTC: { synced: true }, ETH: { synced: false } } }); writeJson(dir, 'survey/status.json', { tsMs: T - 60_000, enabled: true, scanned: 900, catalog: { status: 'ACCEPTED', ageSec: 30 } }); writeJson(dir, 'universe/current.json', { date: '2026-09-11', selectedAt: T - 3_600_000, source: 'wideeye', pairs: [{ symbol: 'BTC/USD', coin: 'BTC' }] });
  writeJson(dir, 'rumor2/status.json', { tsMs: T - 1000, lifecycle: 'ACTIVE', durabilityMode: 'DURABLE_CORE', providers: [{ provider: 'KRAKEN_OFFICIAL', state: 'OBSERVED', checkedTs: T - 30_000, detail: null }, { provider: 'SEC_OFFICIAL', state: 'FAILED', checkedTs: T - 30_000, detail: 'HTTP 503' }, { provider: 'CFTC_OFFICIAL', state: 'NOT_QUERIED', checkedTs: null, detail: 'contact not configured' }], social: { enabled: true, state: 'ACTIVE', lastSettleTs: T - 2000, scope: { coverage: { state: 'CATALOG_BACKED' } } }, socialX: { enabled: true, state: 'DARK', gateDetail: 'BUDGET_NOT_CONFIGURED' } });
  writeJson(dir, 'market-research/status.json', { nowTs: T - 1000, state: 'ACTIVE', owner: { clients: { KRAKEN_SPOT: { runtime: 'ACTIVE', ok: 10, failed: 0 }, DERIBIT: { runtime: 'BLOCKED', ok: 0, failed: 3, lastFailure: { kind: 'HTTP_403', access: 'ENTITLEMENT_DENIED' } }, DEFILLAMA: { runtime: 'BACKOFF', ok: 2, failed: 1 } } }, cases: { queued: 0, running: 0, recent: [{ caseId: 'c1', status: 'BUDGET_BLOCKED', finishedTs: T - 9000 }] } });
  writeJson(dir, 'market-research-dark/edge-capture-status.json', { tsMs: T - 1000, lastSealTs: T - 60_000, capture: 'COMPLETE', charts: { polls: 3, calls: 36, failures: 0, partialAcquisitions: 0 }, l3: { verdict: 'NON_AUTHORITY_KEY', blocker: 'TOKEN_PERMISSION_MISSING', started: false, markets: ['BTC/USD'] } });
  writeJson(dir, 'execution/projection.json', { projectionVersion: 'judge-projection-1', ts: T - 3000, accountId: 'paper-reference-usd500', mode: 'PAPER', runMode: 'PAPER', revision: 12, accountKind: 'PAPER', adapter: 'PAPER', positions: [{ pair: 'XBT/USD', state: 'OPEN', exit: { phase: 'ARMED' } }], pendingOrders: [], restrictions: [], watch: { positions: 1 } });
  const s1 = sensorSnapshot(base); const st = (id) => snapshotRow(s1, id);
  assert.equal(st('TAPE').state, 'ACTIVE'); assert.equal(st('TAPE').ageMs, 5000); assert.match(st('TAPE').coverage, /1\/2 books synced/); assert.equal(st('WIDEEYE').state, 'ACTIVE'); assert.equal(st('UNIVERSE_EXPANSION').state, 'ACTIVE'); assert.equal(st('GATEWAY_KRAKEN').state, 'NOT_OBSERVED', 'enabled by the profile but no matrix yet');
  assert.equal(st('KRAKEN_OFFICIAL').state, 'ACTIVE'); assert.equal(st('SEC_OFFICIAL').state, 'BLOCKED_PROVIDER'); assert.equal(st('SEC_OFFICIAL').blocker, 'HTTP 503'); assert.equal(st('CFTC_OFFICIAL').state, 'ACTIVE_DEGRADED'); assert.equal(st('OFAC_OFFICIAL').state, 'NOT_OBSERVED');
  assert.equal(st('BLUESKY_OFFICIAL').state, 'ACTIVE'); assert.equal(st('BLUESKY_OFFICIAL').ageMs, 2000); assert.equal(st('X_OFFICIAL').state, 'BLOCKED_BUDGET'); assert.equal(st('X_OFFICIAL').blocker, 'BUDGET_NOT_CONFIGURED');
  assert.equal(st('KRAKEN_SPOT').state, 'ACTIVE'); assert.equal(st('DERIBIT').state, 'BLOCKED_GEOGRAPHY'); assert.match(st('DERIBIT').blocker, /HTTP_403/); assert.equal(st('DEFILLAMA').state, 'ACTIVE_DEGRADED'); assert.equal(st('COINBASE_SPOT').state, 'NOT_OBSERVED');
  assert.equal(st('KRAKEN_CHARTS_DARK').state, 'DARK_CAPTURE_OPERATIONAL'); assert.equal(st('KRAKEN_L3_DARK').state, 'BLOCKED_NO_SAFE_L3_DATA_KEY'); assert.match(st('KRAKEN_L3_DARK').blocker, /NON_AUTHORITY_KEY \(TOKEN_PERMISSION_MISSING\)/); assert.equal(st('KRAKEN_L3_DARK').authority, 'NONE');
  assert.equal(st('SOCRATES_CASE_RUNTIME').state, 'ACTIVE'); assert.equal(st('SOCRATES_MODEL').state, 'DISABLED_BY_PAPER_POLICY');
  assert.equal(st('JUDGE').state, 'ACTIVE'); assert.equal(st('JUDGE').authority, 'PAPER_SIMULATION_ONLY'); assert.equal(st('WATCH').state, 'ACTIVE'); assert.match(st('WATCH').detail, /XBT\/USD OPEN exit ARMED/);
  const stale = sensorSnapshot({ ...base, now: T + 60_000 }); assert.equal(snapshotRow(stale, 'TAPE').state, 'ACTIVE_DEGRADED'); assert.equal(snapshotRow(stale, 'JUDGE').state, 'ACTIVE_DEGRADED'); assert.equal(snapshotRow(stale, 'KRAKEN_CHARTS_DARK').state, 'DARK_CAPTURE_OPERATIONAL', 'a segment runner publishes per sealed segment: still fresh at +60 s'); assert.equal(snapshotRow(sensorSnapshot({ ...base, now: T + 3 * 3_600_000 }), 'KRAKEN_CHARTS_DARK').state, 'DARK_CAPTURE_DEGRADED', 'no publication for two segment lengths -> DEGRADED');
  writeJson(dir, 'market-research-dark/edge-capture-status.json', { tsMs: T - 1000, state: 'DARK_CAPTURE_BLOCKED_EXTERNAL', lastSealTs: null, segments: 0, failures: 2, capture: null, charts: null, l3: null, lastError: { code: 'INVALID_REQUEST', message: 'the parent of the output directory does not exist' } }); const blocked = snapshotRow(sensorSnapshot(base), 'KRAKEN_CHARTS_DARK'); assert.equal(blocked.state, 'DARK_CAPTURE_BLOCKED_EXTERNAL', 'the runner\'s own verdict wins over a fresh heartbeat'); assert.match(blocked.blocker, /INVALID_REQUEST/);
  writeJson(dir, 'market-research-dark/edge-capture-status.json', { tsMs: T - 1000, state: 'DARK_CAPTURE_OPERATIONAL', lastSealTs: null, segments: 0, failures: 0, running: true, capture: null, charts: null, l3: null, lastError: null }); const flight = snapshotRow(sensorSnapshot(base), 'KRAKEN_CHARTS_DARK'); assert.equal(flight.state, 'NOT_OBSERVED', 'a started runner with nothing sealed has NO verdict yet (never OPERATIONAL from a heartbeat)'); assert.match(flight.blocker, /in flight/);
  writeJson(dir, 'tape/status.json', { tsMs: T - 1000, state: 'OFFLINE', coins: {} }); assert.equal(snapshotRow(sensorSnapshot(base), 'TAPE').state, 'BLOCKED_PROVIDER');
  writeJson(dir, 'execution/projection.json', { projectionVersion: 'judge-projection-1', ts: T - 1000, accountId: 'live-acct', mode: 'LIVE_ARMED', runMode: 'LIVE_ARMED', revision: 1, accountKind: 'LIVE', adapter: 'KRAKEN', positions: [], pendingOrders: [] }); const liveProj = sensorSnapshot(base); assert.equal(snapshotRow(liveProj, 'JUDGE').state, 'BLOCKED_PROVIDER', 'a LIVE projection is never shown as the paper Judge'); assert.match(snapshotRow(liveProj, 'JUDGE').blocker, /account kind LIVE/);
  const liveEnv = sensorSnapshot({ ...base, env: { ...env, JUDGE_MODE: 'LIVE_ARMED' } }); assert.equal(snapshotRow(liveEnv, 'JUDGE').state, 'BLOCKED_PROVIDER'); assert.match(snapshotRow(liveEnv, 'JUDGE').blocker, /not PAPER/);
  assert.ok(!leaks(JSON.stringify(s1)) && !leaks(JSON.stringify(liveEnv)));
  rmSync(dir, { recursive: true, force: true });
});

test('P-05. the preflight is READ-ONLY and complete: sections A..L, blockers grouped, zero paid calls, no secret value; without DATABASE_URL it is NOT_READY with a CORE_RUNTIME_BLOCKER; with a reachable database, current schema, an initialized account and a free writer lock it is READY_FOR_PAPER even though optional / paid / dark blockers remain visible; an uninitialized account, a held lock, a newer schema or an unreachable database block the core; a LIVE operator environment is FORCED to PAPER and reported; the rendering carries the exact authority line', async () => {
  const dir = tmp('pre-'); const savedData = process.env.COBRA_DATA_DIR; process.env.COBRA_DATA_DIR = dir; resetConfigCache();
  try {
    const noDb = await runPreflight({ env: { SERPENT_CONTROL_PASSWORD: FAKE.SERPENT_CONTROL_PASSWORD }, now: () => T }); assert.equal(noDb.ready, false); assert.equal(noDb.verdict, 'NOT_READY_FOR_PAPER'); assert.deepEqual(Object.keys(noDb.sections), [...SECTIONS]); assert.deepEqual(Object.keys(noDb.blockers), [...BLOCKER_GROUPS]); assert.ok(noDb.blockers.CORE_RUNTIME_BLOCKER.some((b) => b.id === 'DATABASE_URL')); assert.equal(noDb.paidCalls, 0); assert.equal(noDb.readOnly, true); assert.equal(noDb.smoke, false);
    const env = { ...FAKE, SERPENT_HTTP_CONTACT: 'ops@example.invalid', JUDGE_MODE: 'LIVE_ARMED', JUDGE_ALLOW_ORDERS: 'true' };
    const ready = await runPreflight({ env, now: () => T, dbFactory: dbStub() }); assert.equal(ready.ready, true, JSON.stringify(ready.blockers)); assert.equal(ready.verdict, 'READY_FOR_PAPER'); assert.deepEqual(ready.blockers.CORE_CODE_BLOCKER, []); assert.deepEqual(ready.blockers.CORE_RUNTIME_BLOCKER, []);
    assert.ok(ready.blockers.PAID_SENSE_NOT_AUTHORIZED.some((b) => b.id === 'X_OFFICIAL' && /BUDGET_NOT_CONFIGURED/.test(b.reason)), 'X visible as NOT OPERATIONAL without hiding the ready core'); assert.ok(ready.blockers.PAID_SENSE_NOT_AUTHORIZED.some((b) => b.id === 'SOCRATES_MODEL')); assert.ok(ready.blockers.DARK_RESEARCH_BLOCKER.some((b) => b.id === 'KRAKEN_L3' && /KEY_PRESENT_UNPROVEN/.test(b.reason))); assert.ok(ready.blockers.EXTERNAL_OPTIONAL_SENSE_BLOCKER.some((b) => b.id === 'EDGAR_OFFICIAL'));
    assert.deepEqual(ready.sections.A_CODE.forcedOverrides.map((o) => o.name).sort(), ['JUDGE_ALLOW_ORDERS', 'JUDGE_MODE']); assert.equal(ready.sections.I_JUDGE.checks.envMode, 'PAPER'); assert.equal(ready.sections.I_JUDGE.checks.envAllowOrders, 'false'); assert.equal(ready.sections.I_JUDGE.checks.liveArmedPossible, false); assert.equal(ready.sections.I_JUDGE.checks.policyMode, 'PAPER'); assert.equal(ready.sections.I_JUDGE.checks.adapter, 'PAPER');
    assert.equal(ready.sections.B_STORAGE.database.schemaCurrent, true); assert.equal(ready.sections.B_STORAGE.database.accountInitialized, true); assert.equal(ready.sections.B_STORAGE.database.writerLockHeld, false); assert.equal(ready.sections.B_STORAGE.writable, true); assert.equal(ready.sections.K_CONTROLS.controlAuthConfigured, true); assert.equal(ready.sections.C_CORE_MARKET.wideEye.configEnabled, true, 'the profile overlay reached the config');
    assert.deepEqual(ready.authority, { realMoney: 'DISABLED', liveOrders: 'DISABLED', withdrawFunding: 'DISABLED', paperMode: 'READY_FOR_PAPER', darkKrakenJudgeAuthority: 'NONE', darkKrakenSocratesAuthority: 'NONE', thresholdChanges: 'NONE' });
    const text = JSON.stringify(ready); assert.ok(!leaks(text), 'no secret value in the report'); assert.deepEqual(ready.secretNamesPresent.sort(), Object.keys(FAKE).sort());
    const rendered = renderPreflight(ready); assert.ok(rendered.includes('L. FINAL     READY_FOR_PAPER')); for (const l of ['REAL MONEY: DISABLED', 'LIVE ORDERS: DISABLED', 'WITHDRAW/FUNDING: DISABLED', 'PAPER MODE: READY_FOR_PAPER', 'DARK KRAKEN JUDGE AUTHORITY: NONE', 'DARK KRAKEN SOCRATES AUTHORITY: NONE', 'THRESHOLD CHANGES: NONE']) assert.ok(rendered.split('\n').some((x) => x.trim() === l), `exact authority line: ${l}`); assert.ok(rendered.includes('FORCED JUDGE_MODE=PAPER')); assert.ok(!leaks(rendered));
    const uninit = await runPreflight({ env, now: () => T, dbFactory: dbStub({ account: false }) }); assert.equal(uninit.ready, false); assert.ok(uninit.blockers.CORE_RUNTIME_BLOCKER.some((b) => b.id === 'JUDGE_ACCOUNT' && /init-paper/.test(b.remedy)));
    const held = await runPreflight({ env, now: () => T, dbFactory: dbStub({ held: true }) }); assert.ok(held.blockers.CORE_RUNTIME_BLOCKER.some((b) => b.id === 'WRITER_HELD'));
    const newer = await runPreflight({ env, now: () => T, dbFactory: dbStub({ schema: SCHEMA_VERSION + 1 }) }); assert.ok(newer.blockers.CORE_RUNTIME_BLOCKER.some((b) => b.id === 'SCHEMA'));
    const fresh = await runPreflight({ env, now: () => T, dbFactory: dbStub({ tableMissing: true, account: false }) }); assert.equal(fresh.sections.B_STORAGE.database.schemaVersion, 0); assert.ok(fresh.warnings.some((w) => w.id === 'SCHEMA_BEHIND')); assert.ok(fresh.blockers.CORE_RUNTIME_BLOCKER.some((b) => b.id === 'JUDGE_ACCOUNT'));
    const down = await runPreflight({ env, now: () => T, dbFactory: dbStub({ reachable: false }) }); assert.ok(down.blockers.CORE_RUNTIME_BLOCKER.some((b) => b.id === 'DATABASE' && /unreachable/.test(b.reason)));
    const stub = dbStub(); const inst = stub(); await runPreflight({ env, now: () => T, dbFactory: () => inst }); assert.ok(inst.queries.every((q) => /^SELECT/.test(q.text)), 'read-only: SELECT only'); assert.equal(inst.ended, true, 'the connection is released');
    const bad = await runPreflight({ profileFile: writeJson(dir, 'bad.json', { profileVersion: 'x' }), env, now: () => T }); assert.equal(bad.ready, false); assert.equal(bad.profile, null); assert.ok(bad.blockers.CORE_CODE_BLOCKER.some((b) => b.id === 'PROFILE')); assert.ok(renderPreflight(bad).includes('NOT_READY_FOR_PAPER'));
  } finally { if (savedData === undefined) delete process.env.COBRA_DATA_DIR; else process.env.COBRA_DATA_DIR = savedData; resetConfigCache(); rmSync(dir, { recursive: true, force: true }); }
});

test('P-06. the launch law: prepareLaunch applies the profile and refuses to continue unless the forced authority names hold; launchPaper starts the dark capture runner AFTER the core composition begins (a delayed timer), hands the process to fly.js through the injected importer, and the shutdown seam stops every started component (a runner stopped before its timer fires never starts); the documented composition order is stated; the dark state law', async () => {
  const dir = tmp('launch-'); const savedData = process.env.COBRA_DATA_DIR; process.env.COBRA_DATA_DIR = dir; resetConfigCache();
  try {
    const env = { JUDGE_MODE: 'LIVE_ARMED', JUDGE_ALLOW_PRIVATE: 'true' }; const logs = []; const prep = prepareLaunch({ env, log: (m) => logs.push(m) }); assert.equal(env.JUDGE_MODE, 'PAPER'); assert.equal(env.JUDGE_ALLOW_PRIVATE, 'false'); assert.equal(prep.applied.overridden.length, 2); assert.ok(logs.some((m) => m.trim() === 'REAL MONEY: DISABLED') && logs.some((m) => m.trim() === 'LIVE ORDERS: DISABLED')); assert.ok(logs.every((m) => !leaks(m)));
    const pending = []; const timers = { setTimeout: (fn, ms) => { const h = { fn, ms, cleared: false }; pending.push(h); return h; }, clearTimeout: (h) => { h.cleared = true; } }; let flyImported = 0; const env2 = { ...FAKE };
    const r = await launchPaper({ env: env2, log: () => {}, importFly: async () => { flyImported += 1; assert.equal(typeof globalThis.serpentPaperShutdown, 'function', 'the seam exists before fly.js composes'); }, timers });
    assert.equal(flyImported, 1); assert.deepEqual(r.order, [...COMPOSITION_ORDER]); assert.equal(r.order.at(-1), 'Tape feed loop (execution feed + research observer seams)'); assert.ok(r.order.indexOf('persistence bootstrap (restrictive first)') === 0); assert.ok(r.order.indexOf('dark research capture (segments; authority NONE)') > r.order.indexOf('Judge PAPER (+ Watch + paper execution)'));
    assert.equal(pending.length, 1); assert.equal(pending[0].ms, 5000, 'the dark runner starts after the core composition began'); assert.ok(r.dark); assert.equal(r.dark.status().running, false);
    await globalThis.serpentPaperShutdown(); assert.equal(pending[0].cleared, true, 'a shutdown before the delay clears the timer'); assert.equal(r.dark.status().running, false); assert.equal(r.darkRoot, `${r.researchRoot}-dark`, 'the dark runner owns a SIBLING root (never the research owner\'s quota lock, never a tree Socrates reads)'); assert.ok(!existsSync(path.join(r.researchRoot, STATUS_FILE)), 'nothing dark is written under the research owner\'s root'); assert.ok(existsSync(path.join(r.darkRoot, STATUS_FILE)), 'the dark status file is published under the dark root even when never started');
    const status = JSON.parse(readFileSync(path.join(r.darkRoot, STATUS_FILE), 'utf8')); assert.ok(DARK_CAPTURE_STATES.includes(status.state)); assert.equal(status.authority, 'NONE'); assert.equal(status.edgeClaim, 'NOT_MADE'); assert.equal(status.segments, 0); assert.ok(!leaks(JSON.stringify(status)));
    delete globalThis.serpentPaperShutdown;
    // the runner creates its own segments directory: a fresh research root (no edge-captures/ yet) never refuses the first segment
    { const root = path.join(dir, 'fresh-root'); mkdirSync(root, { recursive: true }); const policy = readPolicyFile(path.join(ROOT, 'config/market-research.paper.json')); const subjects = readSubjectsFile(path.join(ROOT, 'config/market-subjects.paper.json'));
      const d = startDarkCapture({ policy, subjects, env: {}, researchRoot: root, segmentSeconds: 1, log: () => {}, fetchImpl: async () => { throw new Error('offline fixture: no network'); }, WebSocketImpl: undefined });
      d.start(); for (let i = 0; i < 400 && d.status().failures + d.status().segments === 0; i += 1) await new Promise((r) => setTimeout(r, 25)); await d.stop();
      const st = d.status(); assert.ok(st.failures + st.segments >= 1, 'one segment attempted'); assert.ok(existsSync(path.join(root, 'edge-captures')), 'the segments directory exists'); assert.notEqual(st.lastError?.code, 'INVALID_REQUEST', `the first segment is never refused for a missing parent: ${JSON.stringify(st.lastError)}`); assert.ok(!leaks(JSON.stringify(st))); }
    // the dark state law
    assert.equal(darkStateOf({ chartsOn: false, l3On: false, last: null }), 'DARK_CAPTURE_DISABLED_BY_POLICY'); assert.equal(darkStateOf({ chartsOn: true, l3On: true, last: null }), 'DARK_CAPTURE_DEGRADED');
    assert.equal(darkStateOf({ chartsOn: true, l3On: false, last: { ok: true, capture: 'COMPLETE', charts: { calls: 12, failures: 0, partialAcquisitions: 0 }, l3: null } }), 'DARK_CAPTURE_OPERATIONAL');
    assert.equal(darkStateOf({ chartsOn: true, l3On: true, last: { ok: true, capture: 'COMPLETE', charts: { calls: 12, failures: 0, partialAcquisitions: 0 }, l3: { started: false, verdict: 'NON_AUTHORITY_KEY' } } }), 'DARK_CAPTURE_DEGRADED', 'charts alive, L3 blocked: degraded, never operational');
    assert.equal(darkStateOf({ chartsOn: true, l3On: true, last: { ok: true, capture: 'COMPLETE', charts: { calls: 0, failures: 6, partialAcquisitions: 0 }, l3: { started: false, verdict: 'CREDENTIAL_MISSING' } } }), 'DARK_CAPTURE_BLOCKED_EXTERNAL');
    assert.equal(darkStateOf({ chartsOn: true, l3On: false, last: { ok: true, capture: 'PARTIAL', charts: { calls: 12, failures: 0, partialAcquisitions: 0 }, l3: null } }), 'DARK_CAPTURE_DEGRADED', 'W12 partial capture is never OPERATIONAL');
    assert.equal(darkStateOf({ chartsOn: true, l3On: false, last: { ok: false, capture: null, charts: null, l3: null, error: { code: 'IO_FAILURE' } } }), 'DARK_CAPTURE_BLOCKED_EXTERNAL');
    // a runner over a policy with both dark senses off never loops and publishes DISABLED
    const off = loadPolicy(JSON.parse(read('market-lab/samples/policy.sample.json'))); const rd = startDarkCapture({ policy: off, subjects: { subjects: [] }, env: {}, researchRoot: path.join(dir, 'root-off'), log: () => {} }); await rd.start(); assert.equal(rd.status().state, 'DARK_CAPTURE_DISABLED_BY_POLICY'); await rd.stop(); assert.equal(JSON.parse(readFileSync(rd.statusFile, 'utf8')).state, 'DARK_CAPTURE_DISABLED_BY_POLICY');
  } finally { delete globalThis.serpentPaperShutdown; if (savedData === undefined) delete process.env.COBRA_DATA_DIR; else process.env.COBRA_DATA_DIR = savedData; resetConfigCache(); rmSync(dir, { recursive: true, force: true }); }
});

test('P-07. the operator entry points and the static fences: `cobra paper preflight --json` (exit 1 when NOT_READY, valid JSON, no secret), `cobra paper inventory`, usage names the paper commands, package.json carries paper / paper:preflight / paper:inventory; fly.js keeps its proven composition seams and gains only the shutdown seam + a profile banner (it never names a dark module); paper/* never imports the live venue adapter; ui/server.js sensors route only reads; no bin / ui / state / lib module names the dark family word', () => {
  const dir = tmp('cli-'); try {
    const run = (args, env = {}) => { try { return { out: execFileSync(process.execPath, ['bin/cobra.js', ...args], { cwd: ROOT, encoding: 'utf8', env: { ...process.env, COBRA_DATA_DIR: dir, ...env, DATABASE_URL: '' }, stdio: ['ignore', 'pipe', 'pipe'] }), code: 0 }; } catch (err) { return { out: err.stdout, code: err.status }; } };
    const pre = run(['paper', 'preflight', '--json'], { X_BEARER_TOKEN: FAKE.X_BEARER_TOKEN }); assert.equal(pre.code, 1, 'NOT_READY exits 1'); const j = JSON.parse(pre.out); assert.equal(j.verdict, 'NOT_READY_FOR_PAPER'); assert.ok(!leaks(pre.out)); assert.ok(j.secretNamesPresent.includes('X_BEARER_TOKEN'));
    const inv = run(['paper', 'inventory']); assert.equal(inv.code, 0); assert.equal(JSON.parse(inv.out).inventoryVersion, 'serpent-sensor-inventory-1');
    const usage = run(['paper', 'nope']); assert.ok(usage.out.includes('cobra paper preflight') && usage.out.includes('cobra paper run'));
    const pkg = JSON.parse(read('package.json')); assert.equal(pkg.scripts.paper, 'node bin/cobra.js paper run'); assert.equal(pkg.scripts['paper:preflight'], 'node bin/cobra.js paper preflight'); assert.equal(pkg.scripts['paper:inventory'], 'node bin/cobra.js paper inventory');
    const fly = read('fly.js'); assert.ok(fly.includes("if (typeof globalThis.serpentPaperShutdown === 'function')")); assert.ok(fly.includes('await runTape({ executionFeed: judgeRun ? judgeRun.tapeFeed : null, observer: marketResearch ? marketResearch.observer : null })')); assert.ok(!/kraken-l3|kraken-charts|edge-capture|dark-capture|paper\//.test(fly), 'fly.js never names a dark module or the paper layer (the launcher imports fly.js, not the reverse)');
    for (const f of ['paper/profile.js', 'paper/inventory.js', 'paper/readiness.js', 'paper/preflight.js', 'paper/launch.js', 'paper/dark-capture.js']) { const src = read(f); assert.ok(!/execution\/kraken-adapter|\/0\/private\/AddOrder|AddOrder|CancelOrder|placeOrder|arm\(/.test(src), `${f} reaches no order path`); assert.ok(!/JUDGE_MODE\s*=\s*['"]LIVE/.test(src), `${f} never sets a LIVE mode`); }
    const ui = read('ui/server.js'); const a = ui.indexOf('function sensorsView'); const b = ui.indexOf('\n}', a); const helper = ui.slice(a, b); assert.ok(helper.length > 50); assert.ok(!/writeFile|appendFile|unlink|rename|mkdir|spawn|exec|fetch\(|process\.env\.\w+\s*=/.test(helper), 'the sensors view only reads');
    const grep = execFileSync('grep', ['-ril', 'microstructure', '--include=*.js', 'bin/', 'lib/', 'state/', 'ui/', 'paper/'], { cwd: ROOT, encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim(); void grep;
  } catch (err) { if (err?.status === 1 && err?.stdout === '') { /* grep found nothing: the fence holds */ } else throw err; } finally { rmSync(dir, { recursive: true, force: true }); }
});

test('P-08. the documents are fences, not prose: docs/PAPER-RUNBOOK.md names the ONE preflight and the ONE launch command, the forced authority names and the seven exact authority lines; docs/JUDGE-PAPER-AUDIT.md carries the verdict JUDGE_PAPER_COMPLETE and FROZEN_FOR_PAPER digests that EQUAL the working tree (judge/*.js, execution/*.js, watch/watch.js) — a silent edit of a frozen tree fails here; the launcher prints the same seven lines', () => {
  const read = (f) => readFileSync(path.join(ROOT, f), 'utf8'); const runbook = read('docs/PAPER-RUNBOOK.md'); const audit = read('docs/JUDGE-PAPER-AUDIT.md');
  for (const s of ['npm run paper:preflight', 'node bin/cobra.js paper preflight', 'npm run paper', 'node bin/cobra.js paper run', 'JUDGE_MODE=PAPER', 'JUDGE_ALLOW_PRIVATE=false', 'JUDGE_ALLOW_ORDERS=false', 'init-paper', 'FROZEN_FOR_PAPER', 'DISABLED_BY_PAPER_POLICY', 'SEALED_CASE_INPUT_ONLY']) assert.ok(runbook.includes(s), `runbook names ${s}`);
  for (const l of ['REAL MONEY: DISABLED', 'LIVE ORDERS: DISABLED', 'WITHDRAW/FUNDING: DISABLED', 'DARK KRAKEN JUDGE AUTHORITY: NONE', 'DARK KRAKEN SOCRATES AUTHORITY: NONE', 'THRESHOLD CHANGES: NONE']) assert.ok(runbook.includes(l), l);
  assert.match(audit, /^Verdict: `JUDGE_PAPER_COMPLETE`$/m); assert.ok(!/JUDGE_PAPER_BLOCKED/.test(audit));
  const files = [...readdirSync(path.join(ROOT, 'judge')).filter((f) => f.endsWith('.js')).map((f) => `judge/${f}`), ...readdirSync(path.join(ROOT, 'execution')).filter((f) => f.endsWith('.js')).map((f) => `execution/${f}`), 'watch/watch.js'].sort();
  const digestOf = (list) => { const h = createHash('sha256'); for (const f of list) { h.update(`${f}\n`); h.update(readFileSync(path.join(ROOT, f))); } return h.digest('hex'); };
  const pinned = (label) => { const m = audit.match(new RegExp(`^${label.replace(/[*/.()]/g, (c) => `\\${c}`)}\\s+([0-9a-f]{64})$`, 'm')); assert.ok(m, `audit pins ${label}`); return m[1]; };
  assert.equal(digestOf(files.filter((f) => f.startsWith('judge/'))), pinned('judge/*.js'), 'judge/ is FROZEN_FOR_PAPER: update docs/JUDGE-PAPER-AUDIT.md §4 with the audit of any change');
  assert.equal(digestOf(files.filter((f) => f.startsWith('execution/'))), pinned('execution/*.js'), 'execution/ is FROZEN_FOR_PAPER');
  assert.equal(digestOf(['watch/watch.js']), pinned('watch/watch.js'), 'watch/watch.js is FROZEN_FOR_PAPER');
  assert.equal(digestOf(files), pinned(`all (${files.length} files)`), 'the whole frozen set');
  const logs = []; const env = { JUDGE_MODE: 'LIVE_ARMED' }; prepareLaunch({ env, log: (m) => logs.push(m) }); for (const l of ['REAL MONEY: DISABLED', 'LIVE ORDERS: DISABLED', 'WITHDRAW/FUNDING: DISABLED', 'PAPER MODE: PROFILE_APPLIED', 'DARK KRAKEN JUDGE AUTHORITY: NONE', 'DARK KRAKEN SOCRATES AUTHORITY: NONE', 'THRESHOLD CHANGES: NONE']) assert.ok(logs.some((x) => x.trim() === l), `launch prints ${l}`);
});
