// SOCIAL-4D CORRECTION/CONFLICT RECORD INTEGRITY — target binding, first-known snapshot seal,
// history-safe replay, as-of provenance boundary. Every RED was reproduced on the untouched
// 32434e8 runtime with the ticket's probe (synthetic inputs, in-memory journal, no network);
// these tests assert the CORRECT outcomes. Fixture provenance: social-4d-legacy-d5db393-*.json
// (untouched d5db393 sources) and social-4d-legacy-32434e8-records.json (version-1 annotation /
// pending records produced by the untouched 32434e8 runtime) — never regenerated by repaired code.
import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { jetstreamCommitToRaw, jetstreamCursorOf, BLUESKY_OFFICIAL } from '../rumor2/providers/bluesky-official.js';
import { neynarEventToRaw, FARCASTER_OFFICIAL } from '../rumor2/providers/farcaster-official.js';
import { xPostToRaw, X_OFFICIAL } from '../rumor2/providers/x-official.js';
import { normalizeSocialObservation, buildSocialFilter } from '../rumor2/social.js';
import {
  socialObservationToEvent, validateSocialEvent, replaySocialHistory, socialReconciliationPendingEvent, validateSocialReconciliationPending, socialReconciliationIdentity,
  socialClockInterpretationEvent, validateSocialClockInterpretation, socialRecordSnapshotHash, socialPendingLinkError, validateSocialPendingContext, socialNativeKey, socialImmutableDigest,
  SOCIAL_OBSERVATION_TYPES, SOCIAL_EVENT_V2_TYPE, SOCIAL_CLOCK_INTERPRETATION_TYPE, SOCIAL_RECONCILIATION_PENDING_TYPE, SOCIAL_CURSOR_EVENT_TYPE, SOCIAL_RECONCILIATION_PENDING_KEYS_V2, SOCIAL_CLOCK_INTERPRETATION_KEYS_V2, MAX_RECONCILIATION_CANDIDATE_IDS, xRuleSetEvent,
} from '../rumor2/social-settle.js';
import { createSocialReconciler } from '../rumor2/social-reconcile.js';
import { socialTemporalView, SOCIAL_VIEW_CONFLICT_STATE } from '../rumor2/social-view.js';
import { createSocialRuntime } from '../rumor2/social-runtime.js';
import { memJournal } from './helpers/rumor2-journal.js';
import { canonicalJson, contentHash } from '../rumor2/truth.js';

const REPO = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const FIX = JSON.parse(readFileSync(path.join(REPO, 'test/fixtures/social-4d-legacy-d5db393-UTC.json'), 'utf8'));
const REC = JSON.parse(readFileSync(path.join(REPO, 'test/fixtures/social-4d-legacy-32434e8-records.json'), 'utf8'));
const fixtureCase = (p, label) => FIX.cases.find((c) => c.path === p && c.label === label);
const T_Z = '2026-09-06T12:00:00Z'; const T_MS = Date.parse(T_Z);
const FILTER = buildSocialFilter({ terms: ['BTC'], watchAuthorIds: ['did:plc:synthetic', 'did:plc:audit', 'fid:4242', 'fid:99', '42'] });
const LEGACY = fixtureCase('bsky_post', 'valid_z'); const T0 = LEGACY.event.knownAtTs; const T1 = T0 + 600_000; const T2 = T1 + 1_000; const T3 = T2 + 1_000;
const T = Date.parse('2026-09-06T14:00:00Z'); // the probe's acquisition clock
const bsky = (createdAt, o = {}) => ({ payload: { $type: 'x#commit', did: o.did ?? 'did:plc:synthetic', seq: 'seq' in o ? o.seq : 41, time: 'time' in o ? o.time : '2026-09-06T13:59:00Z', operation: o.op ?? 'create', collection: 'app.bsky.feed.post', rkey: o.rkey ?? 'k1', cid: o.op === 'delete' ? undefined : (o.cid ?? 'bafysynthetic1'), record: o.op === 'delete' ? undefined : { $type: 'app.bsky.feed.post', text: o.text ?? 'synthetic $BTC fixture', createdAt } } });
const probeMsg = ({ seq = 41, rkey = 'a', declared = '2026-09-06T12:00:00.100Z', text = 'synthetic $BTC fixture' } = {}) => ({ payload: { $type: 'x#commit', did: 'did:plc:audit', seq, time: '2026-09-06T13:59:00Z', operation: 'create', collection: 'app.bsky.feed.post', rkey, cid: 'bafy' + rkey, record: { $type: 'app.bsky.feed.post', text, createdAt: declared } } });
const fc = (timestamp, o = {}) => ({ type: 'cast.created', data: { object: 'cast', hash: o.hash ?? '0xsyntheticcast1', author: { fid: 4242, username: 'fx_synthetic', follower_count: 3 }, text: o.text ?? 'synthetic $BTC fixture', timestamp, parent_hash: null, reactions: { likes_count: 1 } } });
const rc = (timestamp) => ({ type: 'reaction.created', data: { reaction_type: 'recast', reactor: { fid: 99 }, cast: { hash: '0xsyntheticcast1' }, timestamp } });
const xp = (created_at, o = {}) => ({ data: { id: o.id ?? '100', text: o.text ?? 'synthetic $BTC fixture', author_id: '42', created_at, edit_history_tweet_ids: o.history ?? ['100'], public_metrics: { like_count: 1 } } });
const MAP = { bsky: [BLUESKY_OFFICIAL, jetstreamCommitToRaw, jetstreamCursorOf], fc: [FARCASTER_OFFICIAL, neynarEventToRaw, null], x: [X_OFFICIAL, xPostToRaw, null] };
const obs = (p, msg, nowMs = T1) => { const r = MAP[p][1](msg); assert.ok(r.raw, r.reason); const n = normalizeSocialObservation(r.raw, { nowMs }); assert.ok(n.observation, n.reason); return n.observation; };
const asEvent = (o) => { const e = socialObservationToEvent(o).event; assert.equal(validateSocialEvent(e), null); return e; };
const src = (evs) => evs.filter((e) => SOCIAL_OBSERVATION_TYPES.includes(e.type));
const ann = (evs) => evs.filter((e) => e.type === SOCIAL_CLOCK_INTERPRETATION_TYPE);
const pend = (evs) => evs.filter((e) => e.type === SOCIAL_RECONCILIATION_PENDING_TYPE);
const cursors = (evs) => evs.filter((e) => e.type === SOCIAL_CURSOR_EVENT_TYPE);
const rec = (history, provider = BLUESKY_OFFICIAL) => { const r = createSocialReconciler({ provider }); const h = replaySocialHistory(history); assert.ok(h.ok, h.error); r.hydrate(h); return r; };
// re-mint a pending record with ALTERED fields but a consistent identity + snapshot (what an adversary
// who can rewrite hashes would do): the target-context law must still refuse it
const remint = (p, changes) => { const ev = { ...structuredClone(p), ...changes }; ev.sourceEventId = socialReconciliationIdentity({ provider: ev.provider, nativeKeyDigest: contentHash(canonicalJson(ev.nativeKey)), immutableDigest: ev.immutableDigest, witnessHash: ev.witnessHash, reason: ev.reason, candidateIds: ev.candidateIds, candidateTotal: ev.candidateTotal }); ev.snapshotHash = socialRecordSnapshotHash(ev); return ev; };
const ctxOf = (history) => { const h = replaySocialHistory(history); assert.ok(h.ok, h.error); return { targetOf: (id) => h.targets.get(id) ?? null, annotationsOf: (id) => h.annotations.get(id) ?? [] }; };

function boot({ p = 'bsky', arr = [], deliveries, nowMs = T1, maxDrain = 200, seenCap } = {}) {
  const [provider, mapCommit, cursorOf] = MAP[p]; const j = memJournal(arr);
  const rt = createSocialRuntime({ provider, mapCommit, cursorOf, filter: FILTER, now: () => nowMs, mode: 'REPLAY', fixtures: deliveries, log: () => {}, maxDrain, intakeOptions: seenCap ? { seenCap } : {} });
  const h = rt.hydrate(arr); assert.equal(h.ok, true, h.error);
  const okLookup = async (type, ids) => ({ ok: true, existing: new Set(arr.filter((e) => e.type === type && ids.includes(e.sourceEventId)).map((e) => e.sourceEventId)) });
  const settle = ({ lookup = okLookup, append = (evs) => j.append(evs), fenceHeld = () => true } = {}) => rt.settle({ fenceHeld, append, lookup });
  return { rt, j, arr, settle, intake: () => rt._intake(), feed: (m) => rt._feed(JSON.stringify(m)) };
}
async function pipeline(opts) {
  const before = (opts.arr ?? []).map((e) => canonicalJson(e)); const b = boot(opts); b.rt.start();
  const res = await b.settle(opts.settle ?? {});
  for (let i = 0; i < before.length; i++) assert.equal(canonicalJson(b.arr[i]), before[i], `history row ${i} stays byte-identical`);
  return { ...b, res, appended: b.arr.slice(before.length), stats: b.rt.status().stats };
}
// the probe's own A / B / conflict trio, built through the real reconciler
function probeTrio() {
  const A = asEvent(obs('bsky', probeMsg(), T)); const B = asEvent(obs('bsky', probeMsg({ seq: 42, rkey: 'b' }), T));
  const r = rec([A, B]); const p = r.reconcile(obs('bsky', probeMsg({ declared: '2026-09-06T12:00:00.200Z' }), T + 1000), r.batch({ knownAtTs: T + 1000 }));
  assert.equal(p.kind, 'PENDING'); assert.equal(p.reason, 'DECLARATION_CONFLICT'); assert.equal(validateSocialReconciliationPending(p.event), null);
  return { A, B, p: p.event };
}

// =========================================================================================
// A. BASELINE PROBE SCENARIOS, CORRECT OUTCOMES
// =========================================================================================
test('A. the probe scenarios on the candidate: retarget, nonexistent target, backdated clocks, erased targets, and candidate-set growth all resolve honestly', () => {
  const { A, B, p } = probeTrio();
  assert.equal(p.schemaVersion, 2); assert.deepEqual(Object.keys(p).sort(), [...SOCIAL_RECONCILIATION_PENDING_KEYS_V2].sort()); assert.equal(p.candidateTotal, 1);
  const unrelated = { ...structuredClone(p), candidateIds: [B.sourceEventId] };
  assert.match(validateSocialReconciliationPending(unrelated), /derived identity/, 'the identity binds the target set'); assert.match(replaySocialHistory([A, B, unrelated]).error, /derived identity/);
  assert.match(replaySocialHistory([A, { ...structuredClone(p), candidateIds: ['r2sv-' + 'a'.repeat(40)] }]).error, /derived identity/);
  const backdate = structuredClone(p); backdate.candidate.retrievedTs = T + 1; backdate.knownAtTs = T + 1; backdate.ts = new Date(T + 1).toISOString();
  assert.match(validateSocialReconciliationPending(backdate), /snapshotHash/); assert.match(replaySocialHistory([A, backdate]).error, /snapshotHash/);
  assert.match(validateSocialReconciliationPending({ ...structuredClone(p), candidateIds: [] }), /names exactly one target/);
  const rr2 = rec([A]); const seqless = probeMsg({ seq: null });
  const phase1 = rr2.reconcile(obs('bsky', seqless, T + 1000), rr2.batch({ knownAtTs: T + 1000 })); assert.equal(phase1.kind, 'PENDING'); rr2.adopt([phase1.event]);
  rr2.adopt([asEvent(obs('bsky', probeMsg({ seq: 42 }), T + 2000))]);
  const phase2 = rr2.reconcile(obs('bsky', seqless, T + 3000), rr2.batch({ knownAtTs: T + 3000 }));
  assert.equal(phase2.kind, 'PENDING'); assert.equal(phase2.event.candidateIds.length, 2); assert.notEqual(phase2.event.sourceEventId, phase1.event.sourceEventId, 'a grown target set is a NEW later association record');
});

// =========================================================================================
// B-E. TARGET BINDING UNDER THE ONE CONTEXT LAW
// =========================================================================================
test('B. retargeting a conflict to an unrelated post is refused on every route — by identity, and by the context law even when identity and snapshot are re-minted', () => {
  const { A, B, p } = probeTrio();
  const forged = remint(p, { candidateIds: [B.sourceEventId] }); assert.equal(validateSocialReconciliationPending(forged), null, 'shape-valid on its own');
  assert.match(validateSocialPendingContext(forged, ctxOf([A, B])), /not the same native occurrence/);
  assert.match(replaySocialHistory([A, B, forged]).error, /not the same native occurrence/, 'sealed record with a false link: the history fails closed');
  const bv = socialTemporalView({ event: B, pending: [forged], asOfTs: T + 2000 }); assert.equal(bv.ok, false); assert.match(bv.error, /context invalid/);
  const clean = socialTemporalView({ event: B, asOfTs: T + 2000 }); assert.equal(clean.effective.sourceClockStatus, 'TRUSTED'); assert.equal(clean.conflict, null, 'B is undisputed');
  const rp = replaySocialHistory([A, B, p]); assert.equal(rp.ok, true); assert.equal(rp.pendingByTarget.get(A.sourceEventId).length, 1); assert.equal(rp.pendingByTarget.has(B.sourceEventId), false);
  assert.equal(socialTemporalView({ event: A, pending: [p], asOfTs: T + 2000 }).effective.sourceClockStatus, SOCIAL_VIEW_CONFLICT_STATE, 'the genuine conflict still applies to A');
});

test('C. nonexistent, wrong-provider, and causally later targets are refused with the precise reason; the original history is preserved', () => {
  const { A, B, p } = probeTrio();
  const ghost = remint(p, { candidateIds: ['r2sv-' + 'a'.repeat(40)] }); assert.match(validateSocialPendingContext(ghost, ctxOf([A])), /target not durable/); assert.match(replaySocialHistory([A, ghost]).error, /target not durable/);
  const fcEvent = asEvent(obs('fc', fc(T_Z), T)); assert.match(socialTemporalView({ event: fcEvent, pending: [remint(p, { candidateIds: [fcEvent.sourceEventId] })], asOfTs: T + 2000 }).error, /does not name this event|cross-provider/);
  assert.match(socialPendingLinkError(p, { ...A, provider: 'FARCASTER_OFFICIAL' }), /cross-provider/);
  const later = asEvent(obs('bsky', probeMsg({ declared: '2026-09-06T12:00:00.300Z' }), T + 5000)); assert.match(socialPendingLinkError(remint(p, { candidateIds: [later.sourceEventId] }), later), /causally later/);
  assert.match(replaySocialHistory([A, later, remint(p, { candidateIds: [later.sourceEventId] })]).error, /causally later/);
  const rp = replaySocialHistory([A, B, p]); assert.equal(rp.ok, true); assert.equal(rp.durableIds.size, 2); assert.equal(rp.pending, 1); assert.equal(rp.pendingUnlinked.length, 0);
});

test('D. erasing or over-filling a conflict\'s target set is refused, never a silent restoration of an undisputed status', () => {
  const { A, B, p } = probeTrio();
  for (const ids of [[], [A.sourceEventId, B.sourceEventId].sort()]) { const f = remint(p, { candidateIds: ids, candidateTotal: ids.length }); assert.match(validateSocialReconciliationPending(f), /names exactly one target/); assert.match(replaySocialHistory([A, B, f]).error, /names exactly one target/); }
  assert.match(validateSocialReconciliationPending(remint(p, { candidateTotal: 5 })), /candidateTotal/, 'a bounded list may not claim more targets than it lists unless truncated at the cap');
  const rp = replaySocialHistory([A, p]); assert.equal(socialTemporalView({ event: A, pending: rp.pendingByTarget.get(A.sourceEventId), asOfTs: T + 1000 }).effective.sourceClockStatus, SOCIAL_VIEW_CONFLICT_STATE);
});

test('E. reason lies: the same native occurrence without a genuine disagreement, a legacy target with no retained declaration, or an immutable conflict with equal facts cannot be asserted', () => {
  const { A, B, p } = probeTrio();
  // a DECLARATION_CONFLICT whose declaration equals A's retained witness
  const same = socialReconciliationPendingEvent({ observation: obs('bsky', probeMsg(), T + 1000), reason: 'DECLARATION_CONFLICT', candidateIds: [A.sourceEventId], knownAtTs: T + 1000 }); assert.equal(validateSocialReconciliationPending(same), null, 'shape-valid on its own');
  assert.match(validateSocialPendingContext(same, ctxOf([A])), /equivalent to a retained declaration/); assert.match(replaySocialHistory([A, same]).error, /equivalent to a retained declaration/);
  // a DECLARATION_CONFLICT against a legacy numeric-only row (no retained declaration)
  const r = rec([LEGACY.event]); const o = obs('bsky', bsky('2026-09-06T12:00:00.200Z'), T1);
  const fake = socialReconciliationPendingEvent({ observation: o, reason: 'DECLARATION_CONFLICT', candidateIds: [LEGACY.event.sourceEventId], knownAtTs: T1 });
  assert.equal(validateSocialReconciliationPending(fake), null); assert.match(validateSocialPendingContext(fake, ctxOf([LEGACY.event])), /retained no original declaration/); assert.match(socialTemporalView({ event: LEGACY.event, pending: [fake], asOfTs: T1 }).error, /retained no original declaration/);
  assert.equal(r.reconcile(o, r.batch({ knownAtTs: T1 })).kind, 'ANNOTATE', 'the reconciler itself annotates rather than conflicts here');
  // an IMMUTABLE_FACT_CONFLICT whose facts actually agree
  const imm = remint(p, { reason: 'IMMUTABLE_FACT_CONFLICT' }); assert.match(validateSocialPendingContext(imm, ctxOf([A])), /immutable facts agree/);
  // MULTIPLE_CANDIDATES over ids that are not the same occurrence
  const multi = remint(p, { reason: 'MULTIPLE_CANDIDATES', candidateIds: [A.sourceEventId, B.sourceEventId].sort(), candidateTotal: 2 }); assert.match(validateSocialPendingContext(multi, ctxOf([A, B])), /not the same native occurrence/);
  // OCCURRENCE_IDENTITY_INSUFFICIENT where both sides carry their sequence
  const occ = remint(p, { reason: 'OCCURRENCE_IDENTITY_INSUFFICIENT' }); assert.match(validateSocialPendingContext(occ, ctxOf([A])), /both sides carry their sequence/);
});

// =========================================================================================
// F-G. FIRST-KNOWN SNAPSHOT SEAL
// =========================================================================================
test('F. pending first-known clocks moved together under the old binding are refused; the genuine record applies only from its own knownAt', () => {
  const { A, p } = probeTrio();
  for (const shift of [T + 1, T - 1, T + 999]) { const b = structuredClone(p); b.candidate.retrievedTs = shift; b.knownAtTs = shift; b.ts = new Date(shift).toISOString(); assert.match(validateSocialReconciliationPending(b), /snapshotHash/); assert.match(replaySocialHistory([A, b]).error, /snapshotHash/); }
  const rp = replaySocialHistory([A, p]); const at = (asOfTs) => socialTemporalView({ event: A, pending: rp.pendingByTarget.get(A.sourceEventId), asOfTs });
  assert.equal(at(T + 999).conflict, null); assert.equal(at(T + 999).effective.sourceClockStatus, 'TRUSTED'); assert.equal(at(T + 1000).conflict.knownAtTs, T + 1000); assert.equal(at(T + 1000).effective.clockIntegrity, 'SEALED');
  const tampered = { ...structuredClone(p), witnessHash: 'f'.repeat(40) }; assert.match(validateSocialReconciliationPending(tampered), /witnessHash|derived identity/);
});

test('G. annotation evidence/known clocks moved together under the old binding are refused; no effective correction before its retained knowledge boundary', () => {
  const witness = obs('bsky', bsky('2026-09-06T12:00:00.200Z'), T1).sourceClockWitness;
  const a = socialClockInterpretationEvent({ target: LEGACY.event, clockRole: 'SOURCE_DECLARATION', basis: 'NEW_DELIVERY_SAME_EVENT', witness, evidenceRetrievedTs: T1, knownAtTs: T1 });
  assert.equal(a.schemaVersion, 2); assert.deepEqual(Object.keys(a).sort(), [...SOCIAL_CLOCK_INTERPRETATION_KEYS_V2].sort()); assert.equal(validateSocialClockInterpretation(a, { target: LEGACY.event }), null);
  const early = structuredClone(a); early.evidenceRetrievedTs = T0 + 1; early.knownAtTs = T0 + 1; early.ts = new Date(T0 + 1).toISOString();
  assert.equal(early.sourceEventId, a.sourceEventId); assert.match(validateSocialClockInterpretation(early, { target: LEGACY.event }), /snapshotHash/); assert.match(replaySocialHistory([LEGACY.event, early]).error, /snapshotHash/);
  for (const k of ['basis', 'evidenceRetrievedTs']) { const t = structuredClone(a); t[k] = k === 'basis' ? 'RETAINED_ORIGINAL_DECLARATION' : T1 - 5; assert.notEqual(validateSocialClockInterpretation(t, { target: LEGACY.event }), null, `${k} is sealed`); }
  const rp = replaySocialHistory([LEGACY.event, a]); assert.equal(rp.ok, true);
  const before = socialTemporalView({ event: LEGACY.event, annotations: rp.annotations.get(LEGACY.event.sourceEventId), asOfTs: T1 - 1 }); assert.deepEqual(before.appliedAnnotations, []); assert.equal(before.effective.sourceDeclaredTs, LEGACY.event.sourceDeclaredTs); assert.equal(before.effective.clockIntegrity, 'ORIGINAL_ONLY');
  const at = socialTemporalView({ event: LEGACY.event, annotations: rp.annotations.get(LEGACY.event.sourceEventId), asOfTs: T1 }); assert.deepEqual(at.appliedAnnotations, [a.sourceEventId]); assert.equal(at.effective.sourceDeclaredTs, T_MS + 200); assert.equal(at.effective.clockIntegrity, 'SEALED');
});

// =========================================================================================
// H-I. SEMANTIC IDENTITY: KEEP-FIRST REDELIVERY, LATER ASSOCIATION
// =========================================================================================
test('H. an identical legitimate redelivery at a later time keeps ONE settled semantic record with its first-known clocks — through settlement, restart, and cache eviction; the journal sees no altered payload', async () => {
  const r1 = await pipeline({ arr: [LEGACY.event], deliveries: [bsky('2026-09-06T12:00:00.100Z')], nowMs: T1 }); assert.equal(ann(r1.appended).length, 1);
  const r2 = await pipeline({ arr: r1.arr, deliveries: [bsky('2026-09-06T12:00:00.200Z')], nowMs: T2 }); const conflict = pend(r2.appended)[0]; assert.equal(conflict.knownAtTs, T2);
  for (const [nowMs, seenCap] of [[T3, undefined], [T3 + 60_000, 1]]) {
    const again = await pipeline({ arr: r2.arr, deliveries: [bsky('2026-09-06T12:00:00.200Z'), bsky('2026-09-06T12:00:00.100Z'), bsky('2026-09-06T12:00:00.200Z')], nowMs, seenCap });
    assert.equal(src(again.appended).length + ann(again.appended).length + pend(again.appended).length, 0, 'nothing new'); assert.equal(pend(again.arr)[0].knownAtTs, T2, 'first-known stands');
  }
  const later = socialReconciliationPendingEvent({ observation: obs('bsky', bsky('2026-09-06T12:00:00.200Z'), T3), reason: 'DECLARATION_CONFLICT', candidateIds: [LEGACY.event.sourceEventId], knownAtTs: T3 });
  assert.equal(later.sourceEventId, conflict.sourceEventId, 'same semantic identity'); assert.notEqual(later.snapshotHash, conflict.snapshotHash, 'a different first-known snapshot');
  assert.match((await memJournal(r2.arr).append([later])).reason, /CORRUPTION/, 'the journal duplicate law would refuse the altered payload — so reconciliation never presents it');
  assert.equal(r2.arr.length, 4);
});

test('I. the candidate set expands after a second occurrence is learned: a NEW later association record through real intake, no suppression by the local cache, earlier view unchanged, no new source; bounded sets report truncation', async () => {
  const seqless = bsky(T_Z); delete seqless.payload.seq;
  const b = boot({ arr: [LEGACY.event], deliveries: [seqless], nowMs: T1 }); b.rt.start();
  assert.equal((await b.settle()).ok, true); const first = pend(b.arr)[0]; assert.equal(first.reason, 'OCCURRENCE_IDENTITY_INSUFFICIENT'); assert.deepEqual(first.candidateIds, [LEGACY.event.sourceEventId]); assert.equal(first.candidateTotal, 1);
  b.feed(bsky(T_Z, { seq: 42 })); assert.equal((await b.settle()).ok, true); assert.equal(src(b.arr).length, 2, 'a second sequenced occurrence is a new commit');
  b.feed(seqless); assert.equal(b.intake().stats().enqueued, 3, 'the unresolved version was forgotten by the local cache, not suppressed'); assert.equal((await b.settle()).ok, true);
  const all = pend(b.arr); assert.equal(all.length, 2); assert.equal(all[1].candidateIds.length, 2); assert.equal(all[1].candidateTotal, 2); assert.notEqual(all[1].sourceEventId, first.sourceEventId); assert.equal(canonicalJson(all[0]), canonicalJson(first), 'the earlier record is untouched');
  b.feed(seqless); assert.equal((await b.settle()).ok, true); assert.equal(pend(b.arr).length, 2, 'an unchanged association is keep-first');
  const rp = replaySocialHistory(b.arr); assert.equal(rp.ok, true); assert.equal(rp.durableIds.size, 2, 'no logical source from associations'); assert.equal(rp.pendingByTarget.get(LEGACY.event.sourceEventId).length, 2);
  assert.equal(socialTemporalView({ event: LEGACY.event, pending: rp.pendingByTarget.get(LEGACY.event.sourceEventId), asOfTs: T1 }).conflict, null, 'occurrence uncertainty never disputes the source clock');
  b.rt.stop();
  // truncation: more potential occurrences than the bounded list holds
  const many = []; for (let s = 41; s < 41 + MAX_RECONCILIATION_CANDIDATE_IDS + 3; s++) many.push(asEvent(obs('bsky', bsky(T_Z, { seq: s }), T0)));
  const r = rec(many); const out = r.reconcile(obs('bsky', seqless, T1), r.batch({ knownAtTs: T1 })); assert.equal(out.kind, 'PENDING'); assert.equal(out.event.candidateIds.length, MAX_RECONCILIATION_CANDIDATE_IDS); assert.equal(out.event.candidateTotal, MAX_RECONCILIATION_CANDIDATE_IDS + 3, 'truncation is reported, completeness never claimed');
  assert.equal(validateSocialPendingContext(out.event, ctxOf(many)), null);
});

// =========================================================================================
// J-K. LEGITIMATE CONFLICTS AND GENUINE VERSIONS UNCHANGED
// =========================================================================================
test('J-K. immutable-fact and insufficient-occurrence conflicts still work; new sequences, X edits, and delete/recreate/delete are not collapsed', async () => {
  const j1 = await pipeline({ arr: [LEGACY.event], deliveries: [bsky(T_Z, { text: 'synthetic $BTC fixture!' })] }); assert.equal(pend(j1.appended)[0].reason, 'IMMUTABLE_FACT_CONFLICT'); assert.equal(pend(j1.appended)[0].schemaVersion, 2); assert.equal(replaySocialHistory(j1.arr).pendingUnlinked.length, 0);
  const seqless = bsky(T_Z); delete seqless.payload.seq; const j2 = await pipeline({ arr: [LEGACY.event], deliveries: [seqless] }); assert.equal(pend(j2.appended)[0].reason, 'OCCURRENCE_IDENTITY_INSUFFICIENT');
  const c10 = fixtureCase('bsky_post', 'seq10'); const d11 = fixtureCase('bsky_post', 'delete_seq11'); const c20 = fixtureCase('bsky_post', 'seq20'); const d21 = fixtureCase('bsky_post', 'delete_seq21');
  const k = await pipeline({ arr: [c10.event, d11.event], deliveries: [c20.msg, d21.msg, bsky(T_Z, { seq: 30 })] }); assert.deepEqual(src(k.appended).map((e) => e.providerEventSeq), [20, 21, 30]); assert.equal(pend(k.appended).length, 0);
  const x = fixtureCase('x_post', 'valid_z'); const kx = await pipeline({ p: 'x', arr: [x.event], deliveries: [xp(T_Z, { id: '101', history: ['100', '101'] })] }); assert.equal(src(kx.appended)[0].nativeVersionId, '101');
  const fr = await pipeline({ p: 'fc', arr: [fixtureCase('fc_recast', 'valid_z').event], deliveries: [rc('2026-09-06T12:00:00')] }); assert.equal(pend(fr.appended)[0].reason, 'OCCURRENCE_IDENTITY_INSUFFICIENT'); assert.equal(validateSocialPendingContext(pend(fr.appended)[0], ctxOf(fr.arr)), null);
});

// =========================================================================================
// L. LEGACY (VERSION-1) RECORDS FROM THE UNTOUCHED 32434e8 RUNTIME
// =========================================================================================
test('L. predecessor-generated version-1 annotation/pending records replay byte-identical under their own contract, are never promoted to sealed truth, and unverifiable legacy links are retained but never applied', async () => {
  assert.equal(REC.producedBy, '32434e81d066099b656f7abf1d66dadb3df95481');
  for (const [name, sc] of Object.entries(REC.scenarios)) {
    const rp = replaySocialHistory(sc.history); assert.equal(rp.ok, true, `${name}: ${rp.error}`); assert.equal(rp.recordVersions.annotations[2] + rp.recordVersions.pending[2], 0, `${name}: legacy records are version 1`); assert.equal(rp.pendingUnlinked.length, 0, `${name}: genuine legacy links hold`);
    // every legacy record survives the candidate's own redelivery of the same inputs byte-identically, with no duplicate representation
    const p = name === 'fc_recast' ? 'fc' : 'bsky'; const before = sc.history.map((e) => canonicalJson(e));
    for (const step of sc.steps) { const r = await pipeline({ p, arr: structuredClone(sc.history), deliveries: step.deliveries, nowMs: step.nowMs + 5_000 }); assert.equal(src(r.appended).length + ann(r.appended).length + pend(r.appended).length, 0, `${name}: redelivery repeats nothing`); for (let i = 0; i < before.length; i++) assert.equal(canonicalJson(r.arr[i]), before[i]); }
  }
  // the legacy conflict applies under its own contract — labelled UNSEALED, no seal manufactured
  const conflict = REC.scenarios.conflict; const cp = replaySocialHistory(conflict.history); const target = src(conflict.history)[0]; const id = target.sourceEventId;
  const v = socialTemporalView({ event: target, annotations: cp.annotations.get(id), pending: cp.pendingByTarget.get(id), asOfTs: REC.T2, settledOrder: cp.settledOrder }); assert.equal(v.effective.sourceClockStatus, SOCIAL_VIEW_CONFLICT_STATE); assert.equal(v.effective.clockIntegrity, 'LEGACY_UNSEALED');
  const before = socialTemporalView({ event: target, annotations: cp.annotations.get(id), pending: cp.pendingByTarget.get(id), asOfTs: REC.T1, settledOrder: cp.settledOrder }); assert.equal(before.effective.sourceDeclaredTs, T_MS + 100); assert.equal(before.effective.clockIntegrity, 'LEGACY_UNSEALED');
  // a legacy record whose links cannot be verified against actual history: retained, reported, never applied
  const legacyPending = pend(conflict.history)[0]; assert.equal(legacyPending.schemaVersion, 1);
  const other = asEvent(obs('bsky', bsky(T_Z, { seq: 77, rkey: 'k77', cid: 'bafy77' }), T0)); const retargeted = { ...structuredClone(legacyPending), candidateIds: [other.sourceEventId] };
  assert.equal(validateSocialReconciliationPending(retargeted), null, 'a version-1 identity never bound its target set — this cannot be detected by the record alone (stated limit)');
  const rl = replaySocialHistory([...src(conflict.history), other, ...ann(conflict.history), retargeted]); assert.equal(rl.ok, true, 'legacy bytes are never called corrupt for predating the seal');
  assert.equal(rl.pendingUnlinked.length, 1); assert.match(rl.pendingUnlinked[0].reason, /not the same native occurrence/); assert.equal(rl.pendingByTarget.has(other.sourceEventId), false); assert.equal(rl.pendingIds.has(retargeted.sourceEventId), true, 'retained as an unresolved observation');
  assert.equal(socialTemporalView({ event: other, asOfTs: REC.T2 }).conflict, null); assert.match(socialTemporalView({ event: other, pending: [retargeted], asOfTs: REC.T2 }).error, /context invalid/);
  // a legacy pending record with backdated clocks cannot be detected by the record alone either: stated limit, no seal is invented
  const moved = structuredClone(legacyPending); moved.knownAtTs = REC.T0 + 1; moved.ts = new Date(REC.T0 + 1).toISOString(); moved.candidate.retrievedTs = REC.T0 + 1; assert.equal(validateSocialReconciliationPending(moved), null);
  // the candidate keeps-first over the legacy identity for the same target set (no duplicate sealed twin)
  const r = rec(conflict.history); const again = r.reconcile(obs('bsky', bsky('2026-09-06T12:00:00.200Z'), REC.T2 + 1), r.batch({ knownAtTs: REC.T2 + 1 })); assert.equal(again.kind, 'KNOWN'); assert.equal(again.legacyRecord, true);
});

// =========================================================================================
// O-P. PARTIAL DRAIN STAYS FIXED; COUNTS, RETENTION, AUTHORITY
// =========================================================================================
test('O. 41 / 42 / duplicate 42 / filtered 43 with maxDrain=1 stays fixed; crash then inclusive replay yields 42 exactly once', async () => {
  const fx = () => [probeMsg(), probeMsg({ seq: 42, rkey: 'b' }), probeMsg({ seq: 42, rkey: 'b' }), { ...probeMsg({ seq: 43, rkey: 'c', text: 'unrelated garden' }), payload: { ...probeMsg({ seq: 43, rkey: 'c', text: 'unrelated garden' }).payload, did: 'did:plc:other' } }];
  const a = boot({ deliveries: fx(), maxDrain: 1, nowMs: T + 5000 }); a.rt.start(); assert.equal((await a.settle()).ok, true);
  assert.equal(a.rt.durableCursor(), 41); assert.deepEqual(src(a.arr).map((e) => e.providerEventSeq), [41]); assert.deepEqual(a.intake().obligation(42), { owed: 1, dropped: false }); a.rt.stop();
  const b = boot({ arr: a.arr, deliveries: fx(), nowMs: T + 6000 }); b.rt.start(); assert.equal((await b.settle()).ok, true); assert.deepEqual(src(b.arr).map((e) => e.providerEventSeq), [41, 42]); assert.equal(b.rt.durableCursor(), 43); b.rt.stop();
});

test('P. source and independence counts never grow from corrections or links; Reddit/StockTwits retention firewalls cover the sealed record paths; no authority fields', async () => {
  const r1 = await pipeline({ arr: [LEGACY.event], deliveries: [bsky('2026-09-06T12:00:00.100Z'), bsky('2026-09-06T12:00:00.200Z'), bsky(T_Z, { text: 'synthetic $BTC fixture!' })], nowMs: T1 });
  const rp = replaySocialHistory(r1.arr); assert.equal(rp.durableIds.size, 1); assert.equal(rp.observed, 1); assert.equal(ann(r1.appended).length, 1); assert.equal(pend(r1.appended).length, 2);
  for (const e of r1.appended) { const blob = JSON.stringify(e).toLowerCase(); for (const k of ['claim', 'proposition', 'attention', 'hyped', 'eligib', 'order', 'size', 'strike', 'model']) assert.ok(!blob.includes(`"${k}`), `${e.type} carries no ${k} field`); }
  const p = pend(r1.appended)[0]; for (const provider of ['REDDIT_OFFICIAL', 'STOCKTWITS_OFFICIAL']) { assert.match(validateSocialReconciliationPending({ ...p, provider }), /RETENTION_NOT_APPROVED|registry/); assert.match(validateSocialClockInterpretation({ ...ann(r1.appended)[0], provider }, { target: { ...LEGACY.event, provider } }), /RETENTION_NOT_APPROVED|registry/); }
  assert.match(socialTemporalView({ event: { ...LEGACY.event, provider: 'REDDIT_OFFICIAL' }, asOfTs: T1 }).error, /RETENTION_NOT_APPROVED|registry|provider/);
  assert.equal(src(r1.arr).length, 1, 'physical growth is corrections only');
});

// =========================================================================================
// M, N, R. REAL POSTGRESQL: mixed history through the collector, append/lookup refusal and stale
// writer, and the supported INDEX_DIVERGENCE recovery sequence
// =========================================================================================
const TEST_URL = process.env.PERSIST_TEST_DATABASE_URL ?? process.env.DATABASE_URL;
if (!TEST_URL) {
  test('SOCIAL-4D RECORD INTEGRITY durable drills', (t) => t.skip('no PERSIST_TEST_DATABASE_URL / DATABASE_URL configured'));
} else {
  const { Db } = await import('../persistence/db.js');
  const { Repository } = await import('../persistence/repository.js');
  const { runMigrations } = await import('../persistence/migrate.js');
  const { rumor2JournalStore } = await import('../persistence/rumor2-journal.js');
  const { rumor2CheckpointStore } = await import('../persistence/rumor2-checkpoint.js');
  const { startRumor2 } = await import('../rumor2/collector.js');
  const withDb = async (fn) => {
    const SCHEMA = `soc4dr_${Date.now().toString(36)}${Math.floor(Math.random() * 1e6).toString(36)}`;
    const db = new Db({ url: TEST_URL, schema: SCHEMA }); const admin = new Db({ url: TEST_URL, schema: SCHEMA });
    try {
      assert.equal(await db.connect(), true); assert.equal(await admin.connect(), true); await runMigrations(db);
      const repo = new Repository(db); const persistence = () => ({ repo, health: () => ({ databaseConfigured: true, restored: true }) });
      await fn({ admin, mkJournal: () => rumor2JournalStore({ persistence }), mkStores: () => ({ checkpointStore: rumor2CheckpointStore({ persistence }), journal: rumor2JournalStore({ persistence }) }) });
    } finally { await db.query(`DROP SCHEMA IF EXISTS ${SCHEMA} CASCADE`).catch(() => {}); await db.end(); await admin.end(); }
  };
  const killAdvisoryBackends = async (admin) => { const { rows } = await admin.query(`SELECT l.pid FROM pg_locks l WHERE l.locktype='advisory' AND l.granted AND l.database=(SELECT oid FROM pg_database WHERE datname=current_database()) AND l.pid <> pg_backend_pid()`); for (const r of rows) await admin.query(`SELECT pg_terminate_backend($1)`, [r.pid]).catch(() => {}); return rows.length; };
  const events = async (j) => (await j.read()).events;
  const acquire = async (j) => { const w = await j.acquireWriter(); assert.equal(w.ok, true); return w; };
  const bootRt = ({ fixtures, nowMs = T1, maxDrain = 200 }) => createSocialRuntime({ provider: BLUESKY_OFFICIAL, mapCommit: jetstreamCommitToRaw, cursorOf: jetstreamCursorOf, filter: FILTER, now: () => nowMs, mode: 'REPLAY', fixtures, log: () => {}, maxDrain });
  const settleWith = (rt, j, fenceHeld = () => true, append = (e) => j.append(e)) => rt.settle({ fenceHeld, append, lookup: (t, ids) => j.hasEventIds(t, ids) });

  test('M (PG). mixed legacy version-1 / sealed version-2 correction, conflict, cursor, and X operational history restores through the collector with the source gate OFF and ON; legacy rows stay byte-identical', async () => {
    await withDb(async ({ mkStores, mkJournal }) => {
      const legacy = REC.scenarios.conflict.history; const jA = mkJournal(); await acquire(jA); assert.equal((await jA.append(legacy)).ok, true); await jA.releaseWriter();
      const j = mkJournal(); await acquire(j); const rt = bootRt({ fixtures: [bsky('2026-09-06T12:00:00.300Z'), bsky(T_Z, { seq: 90, rkey: 'k90', cid: 'c90' })], nowMs: REC.T2 + 60_000 }); assert.equal(rt.hydrate(await events(j)).ok, true); rt.start(); assert.equal((await settleWith(rt, j)).ok, true); rt.stop();
      assert.equal((await j.append([xRuleSetEvent({ provider: 'X_OFFICIAL', ruleSetHash: 'a'.repeat(40), ruleTags: ['serpent:origin:v1'], coverageEpoch: 1, activatedKnownAtTs: T0, knownAtTs: T0 })])).ok, true); await j.releaseWriter();
      const hist = await events(mkJournal()); for (let i = 0; i < legacy.length; i++) assert.equal(canonicalJson(hist[i]), canonicalJson(legacy[i]), `legacy row ${i} byte-identical`);
      const rp = replaySocialHistory(hist); assert.equal(rp.ok, true); assert.equal(rp.recordVersions.pending[1], 1); assert.equal(rp.recordVersions.pending[2], 1, 'a sealed conflict (.300Z) sits beside the legacy one'); assert.equal(rp.durableIds.size, 2); assert.equal(rp.x.coverageEpoch, 1);
      const H = { get: () => null }; const mkRes = (status, body = '') => ({ status, headers: H, text: async () => body });
      const bootC = ({ checkpointStore, journal, social = {} }) => { process.env.COBRA_DATA_DIR = mkdtempSync(path.join(tmpdir(), 'cobra-soc4dr-')); const clock = { ms: REC.T2 + 120_000 }; const c = startRumor2({ log: () => {}, config: { universe: ['BTC', 'ETH', 'SOL'], socialResearch: { localAdmission: { mode: 'EXPLICIT_STATIC', policyVersion: 1, staticTerms: ['BTC', 'ETH', 'SOL'] } } }, fetchImpl: async () => mkRes(304, ''), now: () => clock.ms, intervalMs: 2_147_000_000, checkpointStore, journal, contact: 'ops@example.com', enabled: true, timeoutMs: 5000, ...social }); return { c, tick: async () => ((clock.ms += 4_000_000), await c.tickOnce()) }; };
      const LIVE = ['RESTORED', 'REBUILT_FROM_EVENT_HISTORY', 'FRESH_START'];
      const off = bootC({ ...mkStores() }); await off.tick(); assert.ok(LIVE.includes(off.c.status().lifecycle), off.c.status().withholdReason ?? off.c.status().lifecycle); assert.equal(off.c.status().social.state, 'DARK'); await off.c.stop();
      const on = bootC({ ...mkStores(), social: { socialBlueskyEnabled: true, socialMode: 'REPLAY', socialFixtures: [bsky('2026-09-06T12:00:00.200Z'), bsky(T_Z, { seq: 91, rkey: 'k91', cid: 'c91' })] } }); await on.tick(); assert.ok(LIVE.includes(on.c.status().lifecycle), on.c.status().withholdReason ?? on.c.status().lifecycle); await on.c.stop();
      const after = await events(mkJournal()); assert.equal(src(after).length, 3, 'only the genuine new commit was added'); assert.equal(pend(after).length, 2, 'the legacy conflict is keep-first, no sealed twin'); for (let i = 0; i < hist.length; i++) assert.equal(canonicalJson(after[i]), canonicalJson(hist[i]));
      // a sealed record with a false link in durable history withholds the collector fail-closed
      const forged = remint(pend(after).find((e) => e.schemaVersion === 2), { candidateIds: [src(after)[1].sourceEventId] }); const jf = mkJournal(); await acquire(jf); assert.equal((await jf.append([forged])).ok, true); await jf.releaseWriter();
      const bad = bootC({ ...mkStores() }); await bad.tick(); assert.equal(bad.c.status().lifecycle, 'WITHHELD_INVALID_CHECKPOINT'); assert.match(bad.c.status().withholdReason, /not the same native occurrence/); await bad.c.stop();
    });
  });

  test('N (PG). append refusal retains obligations with a byte-identical retry; a failed lookup adopts nothing; a stale writer cannot mutate; sealed records survive restart with as-of cutoffs', async () => {
    await withDb(async ({ mkJournal, admin }) => {
      const jA = mkJournal(); await acquire(jA); assert.equal((await jA.append([LEGACY.event])).ok, true); await jA.releaseWriter();
      const j = mkJournal(); await acquire(j); const rt = bootRt({ fixtures: [bsky('2026-09-06T12:00:00.100Z'), bsky('2026-09-06T12:00:00.200Z')], nowMs: T1 }); assert.equal(rt.hydrate(await events(j)).ok, true); rt.start();
      const f0 = await rt.settle({ fenceHeld: () => true, append: (e) => j.append(e), lookup: async () => ({ ok: false, reason: 'UNAVAILABLE' }) }); assert.equal(f0.ok, false); assert.equal(rt._intake().pendingCount(), 1); assert.equal(rt.reconciler().status().annotations + rt.reconciler().status().pending, 0);
      let attempts = 0; const captured = []; const failing = async (evs) => { attempts += 1; captured.push(canonicalJson(evs)); if (attempts === 1) return { ok: false, reason: 'UNAVAILABLE' }; return j.append(evs); };
      const f1 = await settleWith(rt, j, () => true, failing); assert.equal(f1.ok, false); assert.equal((await events(j)).length, 1); assert.equal(rt._intake().pendingCount(), 1); assert.equal(rt.reconciler().status().pending, 0, 'no adoption from a refused append');
      const f2 = await settleWith(rt, j, () => true, failing); assert.equal(f2.ok, true); assert.equal(captured[0], captured[1], 'byte-identical retry'); const all = await events(j); assert.equal(ann(all).length, 1); assert.equal(pend(all).length, 1); assert.equal(pend(all)[0].schemaVersion, 2); assert.equal(pend(all)[0].knownAtTs, T1);
      const killed = await killAdvisoryBackends(admin); assert.ok(killed >= 1); rt._feed(JSON.stringify(bsky('2026-09-06T12:00:00.300Z')));
      const r3 = await settleWith(rt, j, () => false); assert.equal(r3.reason, 'WRITER_FENCE_LOST'); assert.equal((await events(mkJournal())).length, all.length, 'no mutation after fence loss'); assert.equal(rt.isActive(), false);
      const rp = replaySocialHistory(await events(mkJournal())); assert.equal(rp.ok, true); const id = LEGACY.event.sourceEventId; const at = (asOfTs) => socialTemporalView({ event: rp.targets.get(id), annotations: rp.annotations.get(id), pending: rp.pendingByTarget.get(id), asOfTs, settledOrder: rp.settledOrder }); // canonical usage: the annotation and the conflict share one batch clock
      assert.equal(at(T1 - 1).effective.clockIntegrity, 'ORIGINAL_ONLY'); assert.equal(at(T1).effective.sourceClockStatus, SOCIAL_VIEW_CONFLICT_STATE, 'annotation and conflict were known in the same batch'); assert.equal(at(T1).effective.clockIntegrity, 'SEALED');
    });
  });

  test('R (PG). INDEX_DIVERGENCE recovery sequence: truth and obligations retained, nothing appended, no cursor moved; re-hydration from the authoritative journal then settles exactly once', async () => {
    await withDb(async ({ mkJournal }) => {
      const jA = mkJournal(); await acquire(jA); const rtA = bootRt({ fixtures: [bsky(T_Z)], nowMs: T1 }); assert.equal(rtA.hydrate(await events(jA)).ok, true); rtA.start(); assert.equal((await settleWith(rtA, jA)).ok, true); rtA.stop(); await jA.releaseWriter();
      const j = mkJournal(); await acquire(j);
      // a runtime whose index is STALE (hydrated before the durable commit) faces the same commit again plus a new one
      const rt = bootRt({ fixtures: [bsky(T_Z), bsky(T_Z, { seq: 42, rkey: 'k42', cid: 'c42' })], nowMs: T2 }); assert.equal(rt.hydrate([]).ok, true); rt.start();
      const d = await settleWith(rt, j); assert.equal(d.ok, false); assert.equal(d.reason, 'INDEX_DIVERGENCE'); assert.equal(rt._intake().pendingCount(), 2, 'both frames still owed'); assert.equal(rt.durableCursor(), null); assert.equal((await events(j)).length, 2, 'nothing appended'); assert.equal(rt.status().stats.indexDivergences, 1);
      assert.equal((await settleWith(rt, j)).reason, 'INDEX_DIVERGENCE', 'retrying without re-hydration cannot advance (the collector logs and retries; no automatic recovery exists)');
      // the supported recovery: re-hydrate from validated authoritative history, then settle once
      const h = rt.hydrate(await events(j)); assert.equal(h.ok, true); assert.equal(h.durableCursor, 41);
      const ok = await settleWith(rt, j); assert.equal(ok.ok, true); assert.equal(ok.appended, 1, 'only the genuinely new commit'); assert.equal(rt.durableCursor(), 42); assert.equal(rt._intake().pendingCount(), 0);
      const all = await events(j); assert.deepEqual(src(all).map((e) => e.providerEventSeq), [41, 42]); assert.equal(replaySocialHistory(all).ok, true);
      assert.equal((await settleWith(rt, j)).ok, true); assert.equal((await events(j)).length, all.length, 'idempotent afterwards');
      rt.stop(); await j.releaseWriter();
    });
  });
}
