// JUDGE — owner controls, live authorization, release preparation / approval and canary bounds (ticket §9). The
// authorization object binds account / mode, venue, exact release / policy / code digests, allocation ceiling,
// reinvestment policy, every risk / loss / position cap, fee / spec evidence, permitted product, issuance / expiry,
// owner identity and restriction revision. LIVE caps and expiry are REQUIRED owner choices (OWNER_LIMITS_REQUIRED
// otherwise); the paper sample can never auto-arm. prepare-release is read-only; approve-release is a separate
// authenticated owner action over a candidate manifest digest; canary-live has its own short-lived bounded authority.
// Nothing here places an order, and nothing here can arm itself.
import { randomBytes, timingSafeEqual, createHash } from 'node:crypto';
import { shapeError, T, LIMITS, digestOf, makeEvent } from '../execution/contract.js';

export const ARMING_VERSION = 'judge-arming-1';
export const SEALS = Object.freeze(['CODE_TESTED', 'INDEPENDENT_REVIEW', 'PAPER_OPERATIONAL', 'LIVE_PREFLIGHT', 'LIVE_CANARY', 'LIVE_ARMED']);
export const ARM_PHRASE_PREFIX = 'ARM LIVE'; export const ARM_PHRASE_TTL_MS = 120_000;
const PROPOSED_LIMITS = LIMITS;
export const RELEASE_MANIFEST_SCHEMA = Object.freeze({ manifestVersion: T.en(['judge-release-manifest-1']), candidateId: T.id, preparedTs: T.ts, code: { treeDigest: T.hex64, note: T.text }, policy: { policyDigest: T.hex64, policyName: T.id, strategyVersion: T.id, costModelVersion: T.id, watchVersion: T.id }, evaluation: { paperAccountId: T.idOrNull, forwardClosedTrades: T.count, holdoutUntouched: T.bool, netPnl: T.decOrNull, drawdown: T.finiteOrNull, feesAccounted: T.bool, openPositions: T.count, evaluationDigest: T.hex64OrNull, source: T.en(['FORWARD_PAPER', 'REPLAY', 'FIXTURE', 'NONE']) }, tests: { criticalSuitesPassing: T.bool, evidenceFile: T.textOrNull }, sourcePrefixes: T.idList, coverage: { dataFamilies: T.idList, latencySamples: T.count, costModelVersion: T.id }, acceptance: { independentReview: T.en(['NOT_RUN', 'PASSED', 'BLOCKED']), reviewer: T.textOrNull }, unresolvedFailures: listOfText, proposedLimits: (v) => v === null || shapeError(v, PROPOSED_LIMITS, 'proposedLimits') === null, unrunLiveChecks: T.idList, state: T.en(['CANDIDATE', 'BLOCKED']), blockers: listOfText, manifestDigest: T.hex64 });
function listOfText(v, where) { return Array.isArray(v) && v.length <= 64 && v.every((x) => typeof x === 'string' && x.length <= 300) ? null : `${where}: list of text`; }
// read-only with respect to trading authority: a candidate manifest, BLOCKED when any required input is missing
// ONE blocker law shared by manifest generation, reopen, approval and arm (closeout R14): the blockers follow from the content;
// a null / empty / negative evaluation is never qualification (unknown net P&L, missing evaluation digest, no source prefixes)
export function releaseBlockers({ codeTreeDigest, evaluation, tests, sourcePrefixes = [], acceptance = { independentReview: 'NOT_RUN' }, unresolvedFailures = [], proposedLimits = null }) {
  const blockers = []; if (!codeTreeDigest || codeTreeDigest === '0'.repeat(64)) blockers.push('CODE_TREE_DIGEST_MISSING'); if (!evaluation || evaluation.source !== 'FORWARD_PAPER') blockers.push('FORWARD_PAPER_EVIDENCE_MISSING'); if (evaluation && evaluation.source === 'FIXTURE') blockers.push('FIXTURE_ONLY_EVIDENCE_NOT_ACCEPTABLE'); if (!evaluation || evaluation.forwardClosedTrades === 0) blockers.push('EMPTY_TRADE_SAMPLE'); if (!evaluation || evaluation.netPnl === null || evaluation.netPnl === undefined) blockers.push('NET_EVALUATION_UNKNOWN'); if (evaluation && typeof evaluation.netPnl === 'string' && evaluation.netPnl.startsWith('-')) blockers.push('NEGATIVE_NET_EVALUATION_NOT_POSITIVE_EVIDENCE'); if (!evaluation?.evaluationDigest) blockers.push('EVALUATION_DIGEST_MISSING'); if (!evaluation?.holdoutUntouched) blockers.push('HOLDOUT_NOT_UNTOUCHED'); if (!evaluation?.feesAccounted) blockers.push('FEES_NOT_ACCOUNTED'); if (evaluation && evaluation.openPositions > 0) blockers.push('OPEN_POSITIONS_UNACCOUNTED'); if (!Array.isArray(sourcePrefixes) || !sourcePrefixes.length) blockers.push('SOURCE_PREFIXES_MISSING'); if (!tests?.criticalSuitesPassing) blockers.push('CRITICAL_TESTS_NOT_PASSING'); if (acceptance?.independentReview !== 'PASSED') blockers.push('INDEPENDENT_REVIEW_NOT_PASSED'); if (unresolvedFailures.length) blockers.push('UNRESOLVED_FAILURES_PRESENT'); if (!proposedLimits) blockers.push('PROPOSED_LIMITS_MISSING');
  return blockers;
}
const UNRUN_LIVE_CHECKS = Object.freeze(['LIVE_PREFLIGHT', 'LIVE_CANARY', 'LIVE_ARMED']);
export function prepareRelease({ codeTreeDigest, policy, policyDigest, evaluation, tests, sourcePrefixes = [], coverage, acceptance = { independentReview: 'NOT_RUN', reviewer: null }, unresolvedFailures = [], proposedLimits = null, nowTs }) {
  const blockers = releaseBlockers({ codeTreeDigest, evaluation, tests, sourcePrefixes, acceptance, unresolvedFailures, proposedLimits });
  const m = { manifestVersion: 'judge-release-manifest-1', candidateId: `rel-${digestOf({ codeTreeDigest, policyDigest, nowTs }).slice(0, 24)}`, preparedTs: nowTs, code: { treeDigest: codeTreeDigest ?? '0'.repeat(64), note: 'exact tracked tree digest at preparation' }, policy: { policyDigest, policyName: policy.policyName, strategyVersion: policy.strategyVersion, costModelVersion: policy.costModelVersion, watchVersion: policy.watchVersion }, evaluation: { paperAccountId: evaluation?.paperAccountId ?? null, forwardClosedTrades: evaluation?.forwardClosedTrades ?? 0, holdoutUntouched: Boolean(evaluation?.holdoutUntouched), netPnl: evaluation?.netPnl ?? null, drawdown: evaluation?.drawdown ?? null, feesAccounted: Boolean(evaluation?.feesAccounted), openPositions: evaluation?.openPositions ?? 0, evaluationDigest: evaluation?.evaluationDigest ?? null, source: evaluation?.source ?? 'NONE' }, tests: { criticalSuitesPassing: Boolean(tests?.criticalSuitesPassing), evidenceFile: tests?.evidenceFile ?? null }, sourcePrefixes, coverage: { dataFamilies: coverage?.dataFamilies ?? [], latencySamples: coverage?.latencySamples ?? 0, costModelVersion: policy.costModelVersion }, acceptance, unresolvedFailures, proposedLimits, unrunLiveChecks: [...UNRUN_LIVE_CHECKS], state: blockers.length ? 'BLOCKED' : 'CANDIDATE', blockers, manifestDigest: 'x'.repeat(64) };
  m.manifestDigest = digestOf({ ...m, manifestDigest: null }); const e = shapeError(m, RELEASE_MANIFEST_SCHEMA, 'manifest'); if (e) throw new Error(e); return Object.freeze(m);
}
// the semantics: state and blockers must FOLLOW from the manifest content (rehashing is integrity, never qualification)
export function manifestSemanticsError(m) {
  const expected = releaseBlockers({ codeTreeDigest: m.code?.treeDigest ?? null, evaluation: m.evaluation ?? null, tests: m.tests ?? null, sourcePrefixes: m.sourcePrefixes ?? [], acceptance: m.acceptance ?? null, unresolvedFailures: m.unresolvedFailures ?? [], proposedLimits: m.proposedLimits ?? null });
  const got = Array.isArray(m.blockers) ? m.blockers : null; if (!got || got.length !== expected.length || expected.some((b) => !got.includes(b))) return `manifest: blockers do not follow from the content (expected ${expected.join(',') || 'none'})`;
  const state = expected.length ? 'BLOCKED' : 'CANDIDATE'; if (m.state !== state) return `manifest: state ${m.state} does not follow from ${expected.length} blocker(s)`;
  if (!Array.isArray(m.unrunLiveChecks) || UNRUN_LIVE_CHECKS.some((c) => !m.unrunLiveChecks.includes(c))) return 'manifest: the live checks are never run by a manifest';
  return null;
}
export const manifestError = (m) => { const e = shapeError(m, RELEASE_MANIFEST_SCHEMA, 'manifest'); if (e) return e; if (digestOf({ ...m, manifestDigest: null }) !== m.manifestDigest) return 'manifest: digest does not match content'; return manifestSemanticsError(m); };
// an authenticated owner action over the candidate manifest digest with a bounded written assessment; never trading permission
export function approveRelease({ manifest, manifestDigest, assessment, ownerRef, sessionTag, nowTs }) { const e = manifestError(manifest); if (e) return { ok: false, reason: 'MANIFEST_INVALID', detail: e }; if (manifest.manifestDigest !== manifestDigest) return { ok: false, reason: 'MANIFEST_DIGEST_MISMATCH' }; if (manifest.state !== 'CANDIDATE') return { ok: false, reason: 'MANIFEST_BLOCKED', blockers: manifest.blockers }; if (typeof assessment !== 'string' || assessment.length < 40 || assessment.length > 4000) return { ok: false, reason: 'ASSESSMENT_REQUIRED' }; if (!/uncertain|limitation|risk/i.test(assessment)) return { ok: false, reason: 'ASSESSMENT_MUST_STATE_UNCERTAINTY' }; const approval = { approvalVersion: 'judge-release-approval-1', approvalId: `apr-${digestOf({ manifestDigest, ownerRef, nowTs }).slice(0, 24)}`, manifestDigest, releaseDigest: manifest.manifestDigest, codeTreeDigest: manifest.code.treeDigest, policyDigest: manifest.policy.policyDigest, ownerRef, sessionTag, approvedTs: nowTs, assessmentDigest: digestOf(assessment), assessment: assessment.slice(0, 4000), grants: 'ELIGIBILITY_FOR_PREFLIGHT_CANARY_ARM_CHECKS_ONLY', calibrationState: 'UNVALIDATED_HYPOTHESIS' }; return { ok: true, approval: Object.freeze(approval) }; }
// ---- ARM_LIVE: a distinct authenticated action; fresh password + the EXACT server-generated phrase bound to account / allocation / policy ----------
export function createArmChallenge({ accountId, allocationCeiling, policyDigest, releaseDigest, nowTs }) { const nonce = randomBytes(6).toString('hex').toUpperCase(); const phrase = `${ARM_PHRASE_PREFIX} ${accountId} ${allocationCeiling} ${policyDigest.slice(0, 8)} ${nonce}`; return { challengeId: `arm-${nonce}`, phrase, binding: { accountId, allocationCeiling, policyDigest, releaseDigest }, issuedTs: nowTs, expiresTs: nowTs + ARM_PHRASE_TTL_MS }; }
const eq = (a, b) => { const x = createHash('sha256').update(String(a)).digest(); const y = createHash('sha256').update(String(b)).digest(); return timingSafeEqual(x, y); };
export function verifyArmRequest({ challenge, request, nowTs }) { if (!challenge) return { ok: false, reason: 'NO_CHALLENGE' }; if (nowTs > challenge.expiresTs) return { ok: false, reason: 'CHALLENGE_EXPIRED' }; if (typeof request?.phrase !== 'string' || !eq(request.phrase, challenge.phrase)) return { ok: false, reason: 'PHRASE_MISMATCH' }; for (const k of ['accountId', 'allocationCeiling', 'policyDigest', 'releaseDigest']) if (request[k] !== challenge.binding[k]) return { ok: false, reason: `BINDING_${k.toUpperCase()}_MISMATCH` }; return { ok: true }; }
// the live authorization object: every field explicit; the paper sample cannot be inherited
export function buildLiveAuthorization({ accountId, releaseDigest, policyDigest, codeDigest, allocationCeiling, reinvestment, ownerLimits, keyFingerprint, ownerRef, expiresTs, restrictionRevision, nowTs, verifiedAvailableUsd, preflight, approval, canary = null, canaryEvidence = null }) {
  const reasons = []; if (!codeDigest) reasons.push('CODE_IDENTITY_UNKNOWN'); if (!approval || approval.releaseDigest !== releaseDigest) reasons.push('RELEASE_NOT_APPROVED');
  // the ordinary arm needs a COMPLETED, reconciled canary on this account under the same release (closeout R14); the canary itself needs none
  if (!canary && !(canaryEvidence && canaryEvidence.accountId === accountId && canaryEvidence.releaseDigest === releaseDigest && typeof canaryEvidence.authorizationId === 'string' && Number.isSafeInteger(canaryEvidence.completedTs))) reasons.push('CANARY_EVIDENCE_REQUIRED'); if (approval && approval.policyDigest !== policyDigest) reasons.push('POLICY_DIGEST_CHANGED_SINCE_APPROVAL'); if (approval && approval.codeTreeDigest !== codeDigest) reasons.push('CODE_DIGEST_CHANGED_SINCE_APPROVAL'); if (!ownerLimits || shapeError(ownerLimits, LIMITS, 'ownerLimits')) reasons.push('OWNER_LIMITS_REQUIRED'); if (!Number.isSafeInteger(expiresTs) || expiresTs <= nowTs) reasons.push('OWNER_EXPIRY_REQUIRED'); if (!keyFingerprint) reasons.push('KEY_FINGERPRINT_REQUIRED'); if (!preflight?.ok) reasons.push('LIVE_PREFLIGHT_NOT_PASSED'); if (verifiedAvailableUsd === null || verifiedAvailableUsd === undefined) reasons.push('AVAILABLE_FUNDS_UNVERIFIED'); else if (Number(verifiedAvailableUsd) < Number(allocationCeiling)) reasons.push('ALLOCATION_EXCEEDS_VERIFIED_FUNDS'); if (canary && (!canary.pair || !canary.maxBuyConsiderationWithFees || !canary.maxDurationMs || canary.lossAcknowledged !== true)) reasons.push('CANARY_BOUNDS_REQUIRED');
  if (reasons.length) return { ok: false, reasons, state: reasons.includes('OWNER_LIMITS_REQUIRED') ? 'OWNER_LIMITS_REQUIRED' : 'BLOCKED' };
  const payload = { authorizationId: `auth-${digestOf({ accountId, releaseDigest, nowTs, ownerRef, kind: canary ? 'CANARY' : 'LIVE_ARM', allocationCeiling, expiresTs, restrictionRevision }).slice(0, 24)}`, kind: canary ? 'CANARY' : 'LIVE_ARM', releaseDigest, policyDigest, codeDigest, allocationCeiling, reinvestment, limits: ownerLimits, keyFingerprint, ownerRef, issuedTs: nowTs, expiresTs, restrictionRevision, canary, canaryEvidence: canary ? null : { authorizationId: canaryEvidence.authorizationId, releaseDigest: canaryEvidence.releaseDigest, completedTs: canaryEvidence.completedTs } };
  return { ok: true, reasons: [], payload, event: (knownAtTs = nowTs) => makeEvent({ type: 'ACCOUNT_AUTHORIZED', accountId, payload, knownAtTs }) };
}
export function sealsReport({ codeTested, independentReview = 'NOT_RUN', paperOperational = 'NOT_RUN', livePreflight = 'NOT_RUN', liveCanary = 'NOT_RUN', liveArmed = 'NOT_RUN' }) { return { armingVersion: ARMING_VERSION, seals: { CODE_TESTED: codeTested, INDEPENDENT_REVIEW: independentReview, PAPER_OPERATIONAL: paperOperational, LIVE_PREFLIGHT: livePreflight, LIVE_CANARY: liveCanary, LIVE_ARMED: liveArmed }, law: 'each seal carries its own evidence or an explicit NOT_RUN / BLOCKED; none implies another' }; }
