// JUDGE — three measured entry challengers, one exit-policy comparison, benchmarks, predeclared splits, the opportunity
// funnel, the error / experience ledger and the evaluation report (ticket §5.3, §10). Every challenger is a full computed
// feature over point-in-time inputs (never a score or probability), evaluated offline / shadow; none alters live
// thresholds or allocates money. Cases lacking optional data stay in the denominator with missingness; losers are never
// discarded because a metric was unavailable. Metrics undefined on an empty / zero-loss sample are null with a reason.
import { createHash } from 'node:crypto';
import * as M from '../execution/money.js';
import { flowImbalance, bookFacts, bidDepthWithinBps, medianDecimal } from './features.js';
import { digestOf } from '../execution/contract.js';
import { applyEvent, emptyAccountState } from '../execution/reducer.js';

export const EVALUATION_VERSION = 'judge-evaluation-1';
export const ARMS = Object.freeze(['REF_RANGE_IGNITION', 'REF_ABSORPTION_RECLAIM', 'REF_TREND_PULLBACK_CONTINUATION', 'REF_CATALYST_TRANSMISSION', 'REF_COMBINED', 'D1_PRESSURE_TO_PROGRESS', 'D2_FLOW_EVENT_RESPONSE', 'D3_RESIDUAL_IGNITION', 'D4_TRAIL_CONTINUATION_MATCHED', 'D4_TRAIL_CONTINUATION_FUNDED', 'CASH', 'MOMENTUM_ABLATION', 'SEEDED_NOMINATION_CONTROL']);
export const RESPONSE_CLASSES = Object.freeze(['RESILIENT', 'DETERIORATING', 'MIXED', 'UNKNOWN']);
const num = (v) => (v === null ? null : Number(v));
// ---- D1 PRESSURE_TO_PROGRESS_WITH_EXIT_RESILIENCE ---------------------------------------------------------------------------
// window facts over [start, end): price response (end mid / start mid - 1), FI, signed notional, spread change, 10 / 25bps depth
export function windowFacts({ trades, books, startTs, endTs }) {
  const inWin = books.filter((b) => b.receiptTs >= startTs && b.receiptTs < endTs); if (inWin.length < 2) return { state: 'UNKNOWN', reason: 'BOOK_ENDPOINTS_MISSING', startTs, endTs };
  const first = bookFacts(inWin[0]); const last = bookFacts(inWin[inWin.length - 1]); if (!first || !last) return { state: 'UNKNOWN', reason: 'ONE_SIDED_BOOK', startTs, endTs };
  const fi = flowImbalance(trades, startTs, endTs); const net = fi.state === 'UNKNOWN' && M.isZero(M.add(fi.buy, fi.sell)) ? null : M.sub(fi.buy, fi.sell); const total = M.add(fi.buy, fi.sell);
  return { state: 'KNOWN', startTs, endTs, startMid: first.mid, endMid: last.mid, response: M.toStatistic(M.div(M.sub(last.mid, first.mid), first.mid, 10, 'HALF_UP')), fi: fi.fi, netBuyNotional: net, totalNotional: total, spreadStart: first.spread, spreadEnd: last.spread, depth10Start: bidDepthWithinBps(inWin[0], 10), depth10End: bidDepthWithinBps(inWin[inWin.length - 1], 10), depth25End: bidDepthWithinBps(inWin[inWin.length - 1], 25), books: inWin.length };
}
// pressureToProgress = (endMid / startMid - 1) / (netBuyNotionalUSD / 1000), RETURN_PER_1000_USD_NET_BUY; UNKNOWN unless positive
// net flow with |net| >= 10% of total and >= the proposed notional (never divide by nearly zero signed flow)
export function pressureToProgress(w, proposedNotional) { if (w.state !== 'KNOWN' || w.netBuyNotional === null) return { state: 'UNKNOWN', reason: 'WINDOW_UNKNOWN', unit: 'RETURN_PER_1000_USD_NET_BUY' }; if (!M.isPositive(w.netBuyNotional)) return { state: 'UNKNOWN', reason: 'NET_FLOW_NOT_POSITIVE', unit: 'RETURN_PER_1000_USD_NET_BUY' }; if (M.lt(M.abs(w.netBuyNotional), M.mul(w.totalNotional, '0.1')) || M.lt(M.abs(w.netBuyNotional), proposedNotional)) return { state: 'UNKNOWN', reason: 'NET_FLOW_TOO_SMALL', unit: 'RETURN_PER_1000_USD_NET_BUY' }; return { state: 'KNOWN', value: w.response / (M.toStatistic(w.netBuyNotional) / 1000), unit: 'RETURN_PER_1000_USD_NET_BUY' }; }
// exit resilience stresses the DISPLAYED liquidity (closeout R12): the same residual size q against a book whose every displayed
// level carries 100 / 50 / 25 percent of its quantity — never a smaller position against the full book
export const scaleDisplayedDepth = (snapshot, fraction) => { if (!snapshot) return snapshot; const scale = (levels) => (Array.isArray(levels) ? levels.map((l) => (Array.isArray(l) ? [l[0], M.mul(String(l[1]), fraction)] : { ...l, qty: M.mul(String(l.qty), fraction) })) : levels); return { ...snapshot, bids: scale(snapshot.bids), asks: scale(snapshot.asks), stressedDisplay: fraction }; };
export function d1Feature({ trades, books, decisionTs, proposedNotional, snapshot, q, spec, fee, liquidation }) {
  const prev = windowFacts({ trades, books, startTs: decisionTs - 30_000, endTs: decisionTs - 15_000 }); const cur = windowFacts({ trades, books, startTs: decisionTs - 15_000, endTs: decisionTs });
  const p1 = pressureToProgress(prev, proposedNotional); const p2 = pressureToProgress(cur, proposedNotional);
  const exits = {}; for (const f of ['1', '0.5', '0.25']) exits[`display_${Math.round(Number(f) * 100)}pct`] = liquidation ? liquidation({ snapshot: scaleDisplayedDepth(snapshot, f), q, spec, fee }) : null;
  const known = p1.state === 'KNOWN' && p2.state === 'KNOWN' && cur.state === 'KNOWN' && prev.state === 'KNOWN';
  const passes = known && p2.value > p1.value && M.lte(cur.spreadEnd, cur.spreadStart) && exits.display_50pct?.status === 'OK';
  return { challenger: 'D1_PRESSURE_TO_PROGRESS', state: known ? 'KNOWN' : 'UNKNOWN', previous: { ...prev, pressureToProgress: p1 }, current: { ...cur, pressureToProgress: p2 }, exitFeasibility: exits, stressed: 'DISPLAYED_DEPTH_FOR_THE_SAME_RESIDUAL_SIZE', restriction: known ? (passes ? 'ALLOW' : 'RESTRICT') : 'UNKNOWN', label: 'feature vector; stress assumptions are labelled, not forecasts' };
}
// ---- D2 FLOW_EVENT_RESPONSE: anomaly = current complete native interval > median + 3 * MAD of 20 preceding complete intervals -------
export function transferAnomaly(intervals) { const complete = intervals.filter((x) => x.complete && x.value !== null); if (complete.length < 21) return { state: 'UNKNOWN', reason: 'INSUFFICIENT_INTERVALS', have: complete.length }; const cur = complete[complete.length - 1]; const base = complete.slice(-21, -1).map((x) => x.value); const med = medianDecimal(base.map(String)); const mad = medianDecimal(base.map((v) => M.abs(M.sub(String(v), med)))); if (M.isZero(mad)) return { state: 'UNKNOWN', reason: 'MAD_ZERO', median: med }; const threshold = M.add(med, M.mul('3', mad)); return { state: 'KNOWN', anomaly: M.gt(String(cur.value), threshold), current: String(cur.value), median: med, mad, threshold, knownAtTs: cur.knownAtTs, periodStartTs: cur.periodStartTs, note: 'known at the REAL receipt / publication floor, not the period start' }; }
export function responseClass({ pre, post }) { if (pre.state !== 'KNOWN' || post.state !== 'KNOWN' || post.fi === null || pre.depth10End === null || post.depth10End === null) return 'UNKNOWN'; const depthOk = M.gte(post.depth10End, M.mul(pre.depth10End, '0.8')); const spreadOk = M.lte(post.spreadEnd, pre.spreadEnd); if (post.response >= 0 && post.fi > 0 && spreadOk && depthOk) return 'RESILIENT'; if (post.response < 0 && post.fi < 0 && M.lt(post.depth10End, pre.depth10End)) return 'DETERIORATING'; return 'MIXED'; }
// the response is measured over REAL post-known-at intervals (closeout R12): both windows [k-60s,k) and [k,k+60s) must lie inside
// continuous trade coverage that began at or before the pre-window start; an uncovered window is UNKNOWN, never a class
export const windowsCovered = (coverage, k, nowTs) => Boolean(coverage && coverage.continuous === true && Number.isSafeInteger(coverage.startTs) && coverage.startTs <= k - 60_000 && (Number.isSafeInteger(coverage.endTs) ? coverage.endTs : nowTs) >= k + 60_000);
export function d2Feature({ anomaly, trades, books, decisionTs, coverage = null }) { if (!anomaly || anomaly.state !== 'KNOWN') return { challenger: 'D2_FLOW_EVENT_RESPONSE', state: 'UNKNOWN', reason: anomaly?.reason ?? 'NO_ANOMALY_DATA', restriction: 'NO_RULE', note: 'no anomaly / entitlement is not bearish evidence' }; if (!anomaly.anomaly) return { challenger: 'D2_FLOW_EVENT_RESPONSE', state: 'KNOWN', anomaly: false, restriction: 'NO_RULE' }; const k = anomaly.knownAtTs; if (decisionTs < k + 60_000) return { challenger: 'D2_FLOW_EVENT_RESPONSE', state: 'UNKNOWN', anomaly: true, reason: 'RESPONSE_WINDOW_NOT_YET_OBSERVED', restriction: 'RESTRICT' }; if (!windowsCovered(coverage, k, decisionTs)) return { challenger: 'D2_FLOW_EVENT_RESPONSE', state: 'UNKNOWN', anomaly: true, reason: 'RESPONSE_WINDOW_NOT_COVERED', coverage: coverage ? { continuous: coverage.continuous, startTs: coverage.startTs ?? null, endTs: coverage.endTs ?? null } : null, restriction: 'UNKNOWN', note: 'a window outside continuous coverage cannot classify the response' }; const pre = windowFacts({ trades, books, startTs: k - 60_000, endTs: k }); const post = windowFacts({ trades, books, startTs: k, endTs: k + 60_000 }); const cls = responseClass({ pre, post }); return { challenger: 'D2_FLOW_EVENT_RESPONSE', state: cls === 'UNKNOWN' ? 'UNKNOWN' : 'KNOWN', anomaly: true, responseClass: cls, pre, post, restriction: cls === 'RESILIENT' ? 'ALLOW' : cls === 'UNKNOWN' ? 'UNKNOWN' : 'RESTRICT', note: 'measures the reaction after a large-transfer anomaly, never the intent of the transfer' }; }
// ---- D3 RESIDUAL_IGNITION: target 60s mid return minus the median of a peer membership frozen by the window START ------------------
export function peerMembership({ census, rankings, selectionTs, self, excludeBases = [], wrapped = [] }) { const excluded = []; const rows = []; for (const asset of census) { if (asset === self) { excluded.push({ asset, reason: 'SELF' }); continue; } if (excludeBases.includes(asset)) { excluded.push({ asset, reason: 'STABLE_OR_FIAT' }); continue; } if (wrapped.some((g) => g.includes(asset) && g.includes(self))) { excluded.push({ asset, reason: 'WRAPPED_DUPLICATE_OF_SELF' }); continue; } const r = rankings[asset]; if (!r || !Number.isSafeInteger(r.knownAtTs) || r.knownAtTs > selectionTs || selectionTs - r.knownAtTs > 3_600_000 || r.value === null) { excluded.push({ asset, reason: 'RANK_INPUT_ABSENT_OR_STALE' }); continue; } rows.push({ asset, rank: r.value, knownAtTs: r.knownAtTs, source: r.source }); } rows.sort((a, b) => M.cmp(b.rank, a.rank) || (a.asset < b.asset ? -1 : a.asset > b.asset ? 1 : 0)); const peers = rows.slice(0, 10); if (peers.length < 5) return { state: 'UNKNOWN', reason: 'FEWER_THAN_5_PEERS', self, census: census.slice(), excluded, selectionTs }; return { state: 'KNOWN', self, peers, census: census.slice(), excluded, selectionTs, rankingMethod: 'latest supported 24h quote-notional ranking known at selection (a volume x VWAP proxy is a labelled estimate, never cash authority)', membershipDigest: digestOf(peers.map((p) => p.asset)) }; }
export function d3Feature({ membership, returns, decisionTs }) { if (!membership || membership.state !== 'KNOWN') return { challenger: 'D3_RESIDUAL_IGNITION', state: 'UNKNOWN', reason: membership?.reason ?? 'NO_MEMBERSHIP', restriction: 'DISABLED' }; if (membership.selectionTs > decisionTs - 60_000) return { challenger: 'D3_RESIDUAL_IGNITION', state: 'UNKNOWN', reason: 'MEMBERSHIP_NOT_FROZEN_BY_WINDOW_START', restriction: 'DISABLED' }; const start = decisionTs - 60_000; const r = (asset) => { const x = returns[asset]; if (!x || x.startTs !== start || x.endTs !== decisionTs || x.startMid === null || x.endMid === null) return null; return M.toStatistic(M.div(M.sub(x.endMid, x.startMid), x.startMid, 10, 'HALF_UP')); }; if (typeof membership.self !== 'string' || !membership.self) return { challenger: 'D3_RESIDUAL_IGNITION', state: 'UNKNOWN', reason: 'TARGET_IDENTITY_MISSING', restriction: 'DISABLED', note: 'the membership must carry the target identity it was selected for' }; const target = r(membership.self); const peerReturns = membership.peers.map((p) => ({ asset: p.asset, r: r(p.asset) })); const missing = peerReturns.filter((p) => p.r === null).map((p) => p.asset); if (target === null || missing.length) return { challenger: 'D3_RESIDUAL_IGNITION', state: 'UNKNOWN', reason: target === null ? 'TARGET_ENDPOINTS_MISSING' : 'PEER_ENDPOINTS_MISSING', missing, restriction: 'DISABLED', note: 'a missing selected member stays missing; never replaced by a then-known winner' }; const sorted = peerReturns.map((p) => p.r).sort((a, b) => a - b); const med = sorted.length % 2 ? sorted[(sorted.length - 1) / 2] : (sorted[sorted.length / 2 - 1] + sorted[sorted.length / 2]) / 2; const residual = target - med; return { challenger: 'D3_RESIDUAL_IGNITION', state: 'KNOWN', window: { startTs: start, endTs: decisionTs }, targetReturn: target, medianPeerReturn: med, residual, peers: peerReturns, membershipDigest: membership.membershipDigest, restriction: residual > 0 ? 'ALLOW' : 'RESTRICT', note: 'declared peer benchmark; no causal lead claim' }; }
// ---- benchmarks / controls ---------------------------------------------------------------------------------------------------------
export const seededControlSelected = (seed, episodeId) => { const h = createHash('sha256').update(`${seed}|${episodeId}`).digest(); return h.readUInt32BE(0) / 0x100000000 < 0.5; };
// ---- predeclared chronological splits with whole-group integrity and an embargo -----------------------------------------------------
export function predeclareSplits({ episodes, fractions, embargoMs, seed }) { const groups = new Map(); for (const e of episodes) { const g = e.groupId ?? e.assetId; if (!groups.has(g)) groups.set(g, { groupId: g, firstTs: e.firstKnownTs, lastTs: e.lastTs ?? e.firstKnownTs, episodes: [] }); const grp = groups.get(g); grp.firstTs = Math.min(grp.firstTs, e.firstKnownTs); grp.lastTs = Math.max(grp.lastTs, e.lastTs ?? e.firstKnownTs); grp.episodes.push(e.episodeId); } const ordered = [...groups.values()].sort((a, b) => a.firstTs - b.firstTs || (a.groupId < b.groupId ? -1 : 1)); const n = ordered.length; const devEnd = Math.floor(n * fractions.developmentFraction); const valEnd = devEnd + Math.floor(n * fractions.validationFraction); const assignment = {}; const purged = []; let boundaryTs = null; ordered.forEach((g, i) => { const split = i < devEnd ? 'DEVELOPMENT' : i < valEnd ? 'VALIDATION' : 'HOLDOUT'; if (i === devEnd || i === valEnd) boundaryTs = g.firstTs; if (boundaryTs !== null && i >= devEnd && g.firstTs < boundaryTs + embargoMs && split !== assignment[ordered[Math.max(0, i - 1)]?.groupId]) { purged.push({ groupId: g.groupId, reason: 'EMBARGO_OVERLAP' }); assignment[g.groupId] = 'PURGED'; return; } assignment[g.groupId] = split; }); return { evaluationVersion: EVALUATION_VERSION, seed, fractions, embargoMs, groups: n, assignment, purged, declaredTs: null, digest: digestOf({ assignment, fractions, embargoMs, seed }), law: 'declared BEFORE any arm outcome is examined; a later split is exploratory, never holdout' }; }
// ---- the evaluation over journal events (one account = one arm) ---------------------------------------------------------------------
export function evaluateAccount(state, { arm, split = null } = {}) {
  const positions = Object.values(state.positions); const closed = positions.filter((p) => p.state === 'FLAT' && p.realizedPnl !== null); const open = positions.filter((p) => p.state !== 'FLAT'); const wins = closed.filter((p) => M.isPositive(p.realizedPnl)); const losses = closed.filter((p) => M.isNegative(p.realizedPnl));
  const sum = (list) => M.sum(list.map((p) => p.realizedPnl)); const avg = (list) => (list.length ? M.div(sum(list), String(list.length), 8, 'HALF_UP') : null);
  const decisions = state.counters.decisions ?? {}; const total = Object.values(decisions).reduce((a, b) => a + b, 0);
  return { evaluationVersion: EVALUATION_VERSION, arm, split, accountId: state.accountId, denominators: { decisions: total, byState: { ...decisions }, positions: positions.length, closed: closed.length, open: open.length }, netPnl: sum(closed), fees: state.realized.fees, openUnrealized: open.map((p) => ({ positionId: p.positionId, base: M.sub(M.sub(p.confirmedBase, p.soldBase), p.baseFees), lastMark: p.lastMark?.liquidationValue ?? null, note: 'marked separately, never excluded' })), wins: wins.length, losses: losses.length, averageNetWin: avg(wins), averageNetLoss: avg(losses), winRateNote: 'win rate alone is not evidence of edge', profitFactor: losses.length && !M.isZero(sum(losses)) ? M.div(sum(wins), M.abs(sum(losses)), 4, 'DOWN') : { value: null, reason: losses.length ? 'ZERO_LOSS_SUM' : 'NO_LOSSES_IN_SAMPLE' }, drawdown: state.performance.drawdown, highWater: state.performance.highWater, exposedPositions: positions.filter((p) => p.firstFillTs).length, calibrationState: 'UNVALIDATED_HYPOTHESIS', support: { closedTrades: closed.length, note: closed.length < 30 ? 'sample too small for any statistical claim' : 'block bootstrap available with a fixed seed' } };
}
export function blockBootstrap({ pnls, blocks = 5, resamples = 200, seed = 'seed' }) { if (pnls.length < 10) return { state: 'UNSUPPORTED', reason: 'FEWER_THAN_10_TRADES', seed }; let x = createHash('sha256').update(seed).digest().readUInt32BE(0) || 1; const rnd = () => { x ^= x << 13; x >>>= 0; x ^= x >>> 17; x ^= x << 5; x >>>= 0; return x / 0x100000000; }; const size = Math.max(1, Math.floor(pnls.length / blocks)); const means = []; for (let i = 0; i < resamples; i += 1) { let s = 0; let n = 0; for (let b = 0; b < blocks; b += 1) { const start = Math.floor(rnd() * Math.max(1, pnls.length - size + 1)); for (let k = start; k < start + size && k < pnls.length; k += 1) { s += Number(pnls[k]); n += 1; } } means.push(n ? s / n : 0); } means.sort((a, b) => a - b); return { state: 'KNOWN', seed, blocks, blockSize: size, resamples, p05: means[Math.floor(0.05 * resamples)], p50: means[Math.floor(0.5 * resamples)], p95: means[Math.floor(0.95 * resamples)], note: 'block bootstrap over trade order; assumes stationarity within blocks (stated, not proven)' }; }
// ---- error / experience ledger (facts only; no hindsight without its own executable simulation) -------------------------------------
export const ERROR_KINDS = Object.freeze(['COST_UNDERESTIMATION', 'LATE_ENTRY', 'FALSE_CATALYST_MAPPING', 'INSUFFICIENT_REMAINING_MOVE', 'EXIT_DELAY', 'EARLY_EXIT', 'LIQUIDITY_FAILURE', 'STALE_EVIDENCE', 'UNSCORABLE_COUNTERFACTUAL']);
export function experienceLedger(state, decisions = []) { const rows = []; for (const p of Object.values(state.positions)) { const entryOrder = p.entryOrderId ? state.orders[p.entryOrderId] : null; const d = decisions.find((x) => x.decisionId === p.decisionId) ?? null; if (d?.valuationRef && entryOrder && !M.isZero(entryOrder.filledQuote)) { const actual = M.add(entryOrder.filledQuote, entryOrder.feesQuote); const bound = d.valuationRef.entryCashOut; if (M.gt(actual, bound)) rows.push({ kind: 'COST_UNDERESTIMATION', positionId: p.positionId, fact: `actual ${actual} > bound ${bound}` }); } if (p.state === 'FLAT' && p.realizedPnl !== null && M.isNegative(p.realizedPnl) && p.exit?.primaryReason === 'MAX_DURATION') rows.push({ kind: 'EXIT_DELAY', positionId: p.positionId, fact: 'closed by duration at a loss' }); if (p.state !== 'FLAT' && p.lastMark === null) rows.push({ kind: 'UNSCORABLE_COUNTERFACTUAL', positionId: p.positionId, fact: 'open without a mark' }); } for (const d of decisions) if (d.status === 'EXPIRED') rows.push({ kind: 'LATE_ENTRY', decisionId: d.decisionId, fact: 'proposal expired at 10s' }); return { evaluationVersion: EVALUATION_VERSION, rows, kinds: ERROR_KINDS, law: 'attribution requires facts; no assertion that a different action would have won' }; }
// ---- independent simulated accounts per arm (closeout R13) --------------------------------------------------------------------------
// ONE decision / fill stream from the durable journal; every arm replays it through the REAL reducer into its own simulated
// account, taking only the decisions its rule admits (CASH takes none). An arm without a basis reports UNSCORABLE with its
// reason — never a figure copied from another arm. Valuation events belong to the real account and are NOT simulated.
export const ARM_RULES = Object.freeze({ CASH: { kind: 'NONE' }, REF_RANGE_IGNITION: { kind: 'SETUP', setupId: 'RANGE_IGNITION' }, REF_ABSORPTION_RECLAIM: { kind: 'SETUP', setupId: 'ABSORPTION_RECLAIM' }, REF_TREND_PULLBACK_CONTINUATION: { kind: 'SETUP', setupId: 'TREND_PULLBACK_CONTINUATION' }, REF_CATALYST_TRANSMISSION: { kind: 'SETUP', setupId: 'CATALYST_TRANSMISSION' }, REF_COMBINED: { kind: 'ALL' }, D1_PRESSURE_TO_PROGRESS: { kind: 'VERDICT', challenger: 'D1_PRESSURE_TO_PROGRESS' }, D2_FLOW_EVENT_RESPONSE: { kind: 'VERDICT', challenger: 'D2_FLOW_EVENT_RESPONSE' }, D3_RESIDUAL_IGNITION: { kind: 'VERDICT', challenger: 'D3_RESIDUAL_IGNITION' }, D4_TRAIL_CONTINUATION_MATCHED: { kind: 'SHADOW', reason: 'MATCHED_DIAGNOSTIC_NEEDS_PER_EPISODE_ACCOUNTS' }, D4_TRAIL_CONTINUATION_FUNDED: { kind: 'SHADOW', reason: 'FUNDED_SHADOW_NEEDS_ITS_OWN_ACCOUNT' }, MOMENTUM_ABLATION: { kind: 'VERDICT', challenger: 'MOMENTUM_ABLATION' }, SEEDED_NOMINATION_CONTROL: { kind: 'SEEDED' } });
const ADMITTING_VERDICTS = Object.freeze(['ALLOW', 'NO_RULE']);
const NOT_SIMULATED = new Set(['VALUATION', 'WATCH_MARKS']);
function armInclusion(rule, decisions, seed) {
  if (rule.kind === 'NONE') return { include: () => false };
  if (rule.kind === 'ALL') return { include: () => true };
  if (rule.kind === 'SETUP') return { include: (d) => d.setupId === rule.setupId };
  if (rule.kind === 'SEEDED') return { include: (d) => seededControlSelected(seed, d.episodeId) };
  if (rule.kind === 'VERDICT') { const withVerdict = decisions.filter((d) => d.verdicts && Object.hasOwn(d.verdicts, rule.challenger)); if (!withVerdict.length) return { unscorable: 'NO_RECORDED_VERDICTS' }; return { include: (d) => ADMITTING_VERDICTS.includes(d.verdicts?.[rule.challenger]), unverdicted: decisions.length - withVerdict.length }; }
  return { unscorable: rule.reason ?? 'ARM_RULE_UNKNOWN' };
}
// replay the stream into a fresh account, skipping every event that belongs to a decision the arm did not take
export function simulateArm({ accountId, events, include }) {
  let state = emptyAccountState(accountId); const skipped = { decisions: new Set(), reservations: new Set(), positions: new Set(), orders: new Set() }; const refused = []; let applied = 0; let skippedEvents = 0; let notSimulated = 0;
  for (const ev of events) {
    const p = ev.payload ?? {}; const t = ev.type; if (NOT_SIMULATED.has(t)) { notSimulated += 1; continue; }
    if ((t === 'HYPOTHESIS_LOCKED' || t === 'DECISION_RECORDED') && !include(p.decisionId)) skipped.decisions.add(p.decisionId);
    const skip = (typeof p.decisionId === 'string' && skipped.decisions.has(p.decisionId)) || (typeof p.reservationId === 'string' && skipped.reservations.has(p.reservationId)) || (typeof p.positionId === 'string' && skipped.positions.has(p.positionId)) || (typeof p.orderId === 'string' && skipped.orders.has(p.orderId));
    if (skip) { if (t === 'RESERVATION_OPENED') skipped.reservations.add(p.reservationId); if (t === 'POSITION_OPENED') skipped.positions.add(p.positionId); if (t === 'ORDER_INTENT') skipped.orders.add(p.orderId); skippedEvents += 1; continue; }
    try { state = applyEvent(state, ev); applied += 1; } catch (err) { refused.push({ type: t, code: err.code ?? 'REFUSED' }); if (refused.length >= 8) break; }
  }
  return { state, applied, skipped: skippedEvents, notSimulated, refused };
}
export function evaluateArms({ accountId, events, arms, seed = 'seed' }) {
  const decisions = events.filter((e) => e.type === 'DECISION_RECORDED').map((e) => e.payload); const byId = new Map(decisions.map((d) => [d.decisionId, d])); const out = {};
  for (const arm of arms) {
    const rule = ARM_RULES[arm]; if (!rule) { out[arm] = { arm, outcome: 'UNSCORABLE', reason: 'UNKNOWN_ARM', rule: null, evaluation: null }; continue; }
    const inc = armInclusion(rule, decisions, seed); if (inc.unscorable) { out[arm] = { arm, outcome: 'UNSCORABLE', reason: inc.unscorable, rule, decisions: { total: decisions.length }, evaluation: null }; continue; }
    const included = new Set(decisions.filter((d) => inc.include(d)).map((d) => d.decisionId)); const sim = simulateArm({ accountId, events, include: (id) => !byId.has(id) || included.has(id) });
    if (sim.refused.length) { out[arm] = { arm, outcome: 'UNSCORABLE', reason: `SIMULATION_REFUSED:${sim.refused[0].code}`, rule, simulatedAccount: `${accountId}#${arm}`, simulation: { applied: sim.applied, skipped: sim.skipped, refused: sim.refused }, evaluation: null }; continue; }
    out[arm] = { arm, outcome: 'SCORED', reason: null, rule, simulatedAccount: `${accountId}#${arm}`, decisions: { total: decisions.length, included: included.size, excluded: decisions.length - included.size, unverdicted: inc.unverdicted ?? 0 }, simulation: { applied: sim.applied, skipped: sim.skipped, notSimulated: sim.notSimulated, refused: [] }, evaluation: { ...evaluateAccount(sim.state, { arm }), drawdown: null, highWater: null, drawdownNote: 'valuation events belong to the real account: arm drawdown is NOT_SIMULATED' } };
  }
  return { evaluationVersion: EVALUATION_VERSION, accountId, arms: out, law: 'one decision / fill stream, one independent simulated account per arm; an arm without a basis is UNSCORABLE with its reason, never a copied figure' };
}
// durable predeclared splits (closeout R13): declared ONCE before any arm outcome is examined and reused verbatim afterwards;
// a group first seen after the declaration is UNDECLARED — never holdout, never development
export function declareSplits({ episodes, fractions, embargoMs, seed, nowTs, declared = null }) {
  if (!declared) { const d = predeclareSplits({ episodes, fractions, embargoMs, seed }); return { ...d, declaredTs: nowTs, declaration: 'FRESH', undeclared: [] }; }
  if (declared.seed !== seed || declared.embargoMs !== embargoMs || JSON.stringify(declared.fractions) !== JSON.stringify(fractions)) return { ...declared, declaration: 'MISMATCH', error: 'SPLIT_DECLARATION_MISMATCH', undeclared: [] };
  const groups = [...new Set(episodes.map((e) => e.groupId ?? e.assetId))]; const undeclared = groups.filter((g) => !Object.hasOwn(declared.assignment ?? {}, g)).sort(); const assignment = { ...declared.assignment }; for (const g of undeclared) assignment[g] = 'UNDECLARED';
  return { ...declared, assignment, declaration: 'REUSED', undeclared };
}
