// JUDGE — the closed command set behind bin/judge.js (ticket §9.1). Every mutating command proves local owner intent
// (judge/owner.js: the configured control password over stdin / a named env var, durable audit) and names its policy,
// account and mode explicitly; a payload can never substitute another account / mode for the authenticated context.
// Run commands need an initialized account, a valid policy and their dependencies (PostgreSQL for PAPER / LIVE); OBSERVE /
// REPLAY use hypothetical memory accounts and can never resolve live credentials or send private calls. Live preflight /
// canary / arm are implemented here and were NOT RUN in this build (documented in docs/JUDGE-EXECUTION.md).
import { readFileSync, mkdirSync, existsSync } from 'node:fs';
import path from 'node:path';
import { atomicWriteJson } from '../lib/jsonl.js';
import { Db } from '../persistence/db.js';
import { runMigrations } from '../persistence/migrate.js';
import { createPgJournal, createMemoryJournal, JournalError } from '../execution/journal.js';
import { shapeError, LIMITS, parseStrictJson, digestOf } from '../execution/contract.js';
import { applyRestriction } from '../persistence/control-plane.js';
import { loadJudgePolicy } from './policy.js';
import { composeJudge, initAccount, loadSpecs, projectionFile, judgeDir, accountKindOf } from './composition.js';
import { readSuppliedPassword, verifyOwnerIntent, codeTreeDigest, writeApproval, readApproval, readManifest, issueChallenge, consumeChallenge, executionDir } from './owner.js';
import { prepareRelease, approveRelease, sealsReport } from './arming.js';
import { evaluateAccount, experienceLedger, evaluateArms, declareSplits } from './challengers.js';
import { createCaseVerifier } from './intake.js';
import { readRecording, replayRecording, verifyRecording } from './recorder.js';
import { fakeReplayClock } from './replay-clock.js';

export const COMMANDS = Object.freeze(['inspect', 'run-observe', 'init-paper', 'replay', 'run-paper', 'preflight-live', 'arm-live', 'run-live', 'canary-live', 'prepare-release', 'approve-release', 'cage', 'kill', 'veto', 'reconcile', 'status', 'evaluate', 'verify']);
export const MUTATING = Object.freeze(['init-paper', 'run-paper', 'preflight-live', 'arm-live', 'run-live', 'canary-live', 'approve-release', 'cage', 'kill', 'veto', 'reconcile']);
export const EXIT = Object.freeze({ OK: 0, INVALID_REQUEST: 2, INVALID_INPUT: 3, RESOURCE: 4, FAILURE: 5, REFUSED: 6 });
export class CommandError extends Error { constructor(code, message, exitCode = EXIT.INVALID_REQUEST) { super(message); this.code = code; this.exitCode = exitCode; } toJSON() { return { code: this.code, message: this.message, exitCode: this.exitCode }; } }
const readJson = (file, what) => { try { return parseStrictJson(readFileSync(file, 'utf8')); } catch (err) { throw new CommandError('INVALID_INPUT', `${what} ${file}: ${err.message.slice(0, 120)}`, EXIT.INVALID_INPUT); } };

export function createCommands({ env = process.env, clock = () => Date.now(), stdin = null, log = () => {}, transport = null, dbFactory = null, tapeRunner = null, WebSocketImpl = null, specsSource = null, cwd = process.cwd() } = {}) {
  const now = () => clock();
  async function openDb() { const db = dbFactory ? dbFactory() : new Db({ url: env.DATABASE_URL, log }); if (!db.configured()) throw new CommandError('DB_REQUIRED', 'DATABASE_URL is required: PostgreSQL is the account authority', EXIT.RESOURCE); if (!(await db.connect())) throw new CommandError('DB_UNAVAILABLE', 'database unreachable', EXIT.RESOURCE); await runMigrations(db, { log }); return db; }
  async function withJournal(fn) { const db = await openDb(); try { return await fn(createPgJournal({ db, log }), db); } finally { await db.end(); } }
  async function owner(action, flags, binding) { const supplied = await readSuppliedPassword({ env, stdin, useStdin: flags['owner-stdin'] === true }); const v = verifyOwnerIntent({ supplied, env, action, binding, now }); if (!v.ok) throw new CommandError(v.reason, `owner intent refused: ${v.reason}`, EXIT.REFUSED); return v; }
  const policyOf = (flags) => { try { return loadJudgePolicy(flags.policy); } catch (err) { throw new CommandError('POLICY_INVALID', err.message, EXIT.INVALID_INPUT); } };
  const accountOf = (flags, policy) => flags.account ?? policy.account.accountId;
  async function specsFor(policy, symbols) { if (specsSource) return specsSource(symbols); return loadSpecs({ transport, symbols, nowTs: now() }); }
  const redactedAccount = (l) => (l ? { revision: l.revision, mode: l.state.mode, accountKind: l.state.accountKind, initialized: l.state.initialized, cash: l.state.cash, restrictions: Object.keys(l.state.restrictions ?? {}), authorization: l.state.authorization ? { authorizationId: l.state.authorization.authorizationId, kind: l.state.authorization.kind, expiresTs: l.state.authorization.expiresTs, ended: l.state.authorization.ended } : null, positions: Object.values(l.state.positions ?? {}).filter((p) => p.state !== 'FLAT').length } : null);
  // ---- shared run driver: compose -> start -> tape (real or injected) -> stop; the CLI owns its own tape when run standalone ----
  async function runMode({ flags, mode, allowPrivate = () => false, allowOrders = () => false, onReady = null }) {
    const { policy, digest } = policyOf(flags); const account = accountOf(flags, policy); const symbols = flags.pairs ? flags.pairs.split(',').map((s) => s.trim()).filter(Boolean) : null;
    const specs = symbols ? await specsFor(policy, symbols) : [];
    // the injected database factory (tests / operators) reaches the composition too: ONE authority for the CLI and the run it starts
    const run = await composeJudge({ policyFile: flags.policy, mode, accountId: account, env, log, db: dbFactory && (mode === 'PAPER' || mode.startsWith('LIVE')) ? dbFactory() : null, transport, WebSocketImpl, specs, casesDir: flags.cases ?? null, recordDir: flags.record ?? null, allowPrivate, allowOrders, nominations: symbols ? () => symbols.map((s) => ({ symbol: s, assetId: s.split('/')[0] })) : null });
    let report; try { report = await run.start(); if (onReady) await onReady(run); if (tapeRunner) await tapeRunner({ executionFeed: run.tapeFeed, minutes: flags.minutes ?? null, run }); else { const { runTape } = await import('../tape/run.js'); await runTape({ executionFeed: run.tapeFeed, minutes: flags.minutes ?? null, log }); } } finally { await run.stop(); }
    return { ok: true, command: mode, accountId: account, mode, policyDigest: digest, startup: report, projection: run.projection() };
  }
  const cmds = {
    async inspect(flags) { const { policy, digest } = policyOf(flags); const account = accountOf(flags, policy); let acct = null; if (env.DATABASE_URL || dbFactory) { try { acct = await withJournal(async (j) => redactedAccount(await j.load(account))); } catch (err) { acct = { unavailable: err.code ?? err.message }; } } return { ok: true, command: 'inspect', policy: { policyName: policy.policyName, mode: policy.mode, digest, strategyVersion: policy.strategyVersion, costModelVersion: policy.costModelVersion, watchVersion: policy.watchVersion, limits: policy.limits, live: policy.live ? { allocationCeiling: policy.live.allocationCeiling, reinvestment: policy.live.reinvestment, ownerLimits: policy.live.ownerLimits ? 'PRESENT' : 'OWNER_LIMITS_REQUIRED', armExpiryMs: policy.live.armExpiryMs, keyEnv: policy.live.keyEnv, secretEnv: policy.live.secretEnv, credentialsPresent: Boolean(env[policy.live.keyEnv] && env[policy.live.secretEnv]) } : null }, account: { accountId: account, kind: accountKindOf(policy.mode === 'LIVE' ? 'LIVE_UNARMED' : 'PAPER'), journal: acct }, codeDigest: codeTreeDigest({ cwd }), seals: sealsReport({ codeTested: 'SEE_TEST_LOG' }), authority: 'READ_ONLY' }; },
    async 'init-paper'(flags) { const { policy, digest } = policyOf(flags); if (policy.mode !== 'PAPER') throw new CommandError('MODE_MISMATCH', 'init-paper needs a PAPER policy'); const account = accountOf(flags, policy); const o = await owner('init-paper', flags, { accountId: account, policyDigest: digest, mode: 'PAPER' }); return withJournal(async (j) => { try { const r = await initAccount({ journal: j, policy, policyDigest: digest, mode: 'PAPER', ownerRef: o.ownerRef, nowTs: now(), accountId: account }); return { ok: true, command: 'init-paper', accountId: account, revision: r.revision, initialCapital: policy.account.initialCapital, mode: 'PAPER' }; } catch (err) { if (err instanceof JournalError) throw new CommandError(err.code, err.message, EXIT.REFUSED); throw err; } }); },
    async 'run-observe'(flags) { const { policy } = policyOf(flags); if (policy.mode !== 'PAPER') throw new CommandError('MODE_MISMATCH', 'run-observe needs a PAPER policy (hypothetical account, no orders)'); return runMode({ flags, mode: 'OBSERVE' }); },
    async 'run-paper'(flags) { const { policy, digest } = policyOf(flags); if (policy.mode !== 'PAPER') throw new CommandError('MODE_MISMATCH', 'run-paper needs a PAPER policy'); await owner('run-paper', flags, { accountId: accountOf(flags, policy), policyDigest: digest, mode: 'PAPER' }); return runMode({ flags, mode: 'PAPER' }); },
    async replay(flags) { const { policy, digest } = policyOf(flags); if (!existsSync(flags.recording)) throw new CommandError('INVALID_INPUT', `recording ${flags.recording} absent`, EXIT.INVALID_INPUT); let first = null; for (const row of readRecording(flags.recording)) { if (typeof row.receiptTs === 'number') { first = row.receiptTs; break; } } if (first === null) throw new CommandError('INVALID_INPUT', 'recording carries no messages', EXIT.INVALID_INPUT);
      const rclock = fakeReplayClock(first); const symbols = flags.pairs ? flags.pairs.split(',').map((s) => s.trim()).filter(Boolean) : []; const specs = flags.specs ? readJson(flags.specs, 'specs') : await specsFor(policy, symbols);
      const journal = createMemoryJournal({ log }); const account = `replay-${accountOf(flags, policy)}`; await initAccount({ journal, policy, policyDigest: digest, mode: 'REPLAY', ownerRef: 'replay', nowTs: first, accountId: account });
      const run = await composeJudge({ policyFile: flags.policy, mode: 'REPLAY', accountId: account, env: {}, log, journal, clock: rclock, specs, nominations: () => symbols.map((s) => ({ symbol: s, assetId: s.split('/')[0] })), writeProjection: false, codeDigest: codeTreeDigest({ cwd }) });
      try { await run.dispatcher.restart({ scope: 'STARTUP' }); run.admitNominations(); const r = await replayRecording({ dir: flags.recording, feed: run.feed, clock: rclock, onTick: (t) => run.tick(t) }); await run.dispatcher.idle(); const state = run.dispatcher.state(); const out = { ok: true, command: 'replay', accountId: account, recording: flags.recording, replayed: r, seed: policy.evaluation.seed, decisions: run.judge.decisions(), funnel: run.judge.funnel ? run.judge.funnel() : null, evaluation: evaluateAccount(state, { arm: 'REF_COMBINED' }), revision: run.dispatcher.revision(), stateDigest: (await journal.load(account)).headDigest, deterministic: 'same recording + policy + seed + code -> same decisions / accounting (P03)' }; if (flags.out) { mkdirSync(path.dirname(flags.out), { recursive: true }); atomicWriteJson(flags.out, out, { pretty: true }); } return out; } finally { await run.stop(); } },
    async 'preflight-live'(flags) { const { policy, digest } = policyOf(flags); if (policy.mode !== 'LIVE') throw new CommandError('MODE_MISMATCH', 'preflight-live needs a LIVE policy'); const account = accountOf(flags, policy); const o = await owner('preflight-live', flags, { accountId: account, policyDigest: digest, mode: 'LIVE_UNARMED' }); if (flags['allow-private'] !== true) throw new CommandError('PRIVATE_NOT_AUTHORIZED', 'preflight-live sends read-only PRIVATE calls: pass --allow-private true to authorize them explicitly', EXIT.REFUSED);
      return withJournal(async (j) => { if (!(await j.exists(account))) { await initAccount({ journal: j, policy, policyDigest: digest, mode: 'LIVE_UNARMED', ownerRef: o.ownerRef, nowTs: now(), accountId: account }); } const run = await composeJudge({ policyFile: flags.policy, mode: 'LIVE_UNARMED', accountId: account, env, log, journal: j, transport: transport ?? ((u, i) => fetch(u, i)), WebSocketImpl, allowPrivate: () => true, allowOrders: () => false, writeProjection: false }); try { const r = await run.preflight(); const file = path.join(executionDir(), `preflight-${account}-${now()}.json`); mkdirSync(executionDir(), { recursive: true }); atomicWriteJson(file, r, { pretty: true }); return { ok: r.ok, command: 'preflight-live', accountId: account, report: r, file, ordersSent: 0 }; } finally { await run.stop(); } }); },
    async 'arm-live'(flags) { const { policy, digest } = policyOf(flags); if (policy.mode !== 'LIVE') throw new CommandError('MODE_MISMATCH', 'arm-live needs a LIVE policy'); const account = accountOf(flags, policy); const canary = flags['canary-pair'] ? { pair: flags['canary-pair'], maxBuyConsiderationWithFees: flags['canary-max-consideration'] ?? null, maxDurationMs: flags['canary-max-duration-ms'] ?? null, lossAcknowledged: flags['canary-loss-acknowledged'] === true } : null;
      if (flags.challenge === true) { const o = await owner('arm-live:challenge', flags, { accountId: account, policyDigest: digest }); const approval = readApproval(flags.approval); if (!approval.ok) throw new CommandError(approval.reason, approval.detail ?? approval.reason, EXIT.INVALID_INPUT); const c = issueChallenge({ accountId: account, allocationCeiling: flags['allocation-ceiling'], policyDigest: digest, releaseDigest: approval.approval.releaseDigest, nowTs: now() }); return { ok: true, command: 'arm-live', step: 'CHALLENGE', ownerRef: o.ownerRef, challengeId: c.challengeId, phrase: c.phrase, expiresTs: c.expiresTs, next: 'arm-live --confirm true --owner-stdin true (stdin: password line, then the exact phrase line)' }; }
      if (flags.confirm !== true) throw new CommandError('INVALID_REQUEST', 'arm-live needs --challenge true or --confirm true');
      // confirm: password (line 1) + exact phrase (line 2) from stdin only
      const lines = await readTwoLines(stdin, flags); const v = verifyOwnerIntent({ supplied: lines[0], env, action: 'arm-live:confirm', binding: { accountId: account, policyDigest: digest, allocationCeiling: flags['allocation-ceiling'], canary: Boolean(canary) }, now }); if (!v.ok) throw new CommandError(v.reason, `owner intent refused: ${v.reason}`, EXIT.REFUSED);
      const approval = readApproval(flags.approval); if (!approval.ok) throw new CommandError(approval.reason, approval.detail ?? approval.reason, EXIT.INVALID_INPUT);
      const ch = consumeChallenge({ request: { phrase: lines[1], accountId: account, allocationCeiling: flags['allocation-ceiling'], policyDigest: digest, releaseDigest: approval.approval.releaseDigest }, nowTs: now() }); if (!ch.ok) throw new CommandError(ch.reason, `arm refused: ${ch.reason}`, EXIT.REFUSED);
      const ownerLimits = flags['owner-limits'] ? readJson(flags['owner-limits'], 'owner limits') : policy.live.ownerLimits; const le = ownerLimits ? shapeError(ownerLimits, LIMITS, 'ownerLimits') : 'ownerLimits: required'; if (le) throw new CommandError('OWNER_LIMITS_REQUIRED', le, EXIT.REFUSED);
      const preflight = flags.preflight ? readJson(flags.preflight, 'preflight report') : null;
      return withJournal(async (j) => { const run = await composeJudge({ policyFile: flags.policy, mode: 'LIVE_UNARMED', accountId: account, env, log, journal: j, transport: transport ?? null, allowPrivate: () => false, allowOrders: () => false, writeProjection: false, codeDigest: codeTreeDigest({ cwd }) }); try { const r = await run.arm({ ownerLimits, expiresTs: flags['expires-at'], allocationCeiling: flags['allocation-ceiling'], reinvestment: flags.reinvestment ?? policy.live.reinvestment, approval: approval.approval, ownerRef: v.ownerRef, releaseDigest: approval.approval.releaseDigest, canary, preflight }); return { ...r, command: 'arm-live', step: 'CONFIRM', accountId: account, kind: canary ? 'CANARY' : 'LIVE_ARM', note: 'an authorization grants entries only inside its limits until expiry; it never places an order by itself' }; } finally { await run.stop(); } }); },
    async 'run-live'(flags) { return liveRun(flags, 'run-live'); },
    async 'canary-live'(flags) { return liveRun(flags, 'canary-live'); },
    async 'prepare-release'(flags) { const { policy, digest } = policyOf(flags); const account = accountOf(flags, policy); const artifact = flags.evaluation ? readJson(flags.evaluation, 'evaluation') : null; const ev = artifact ? (artifact.release ?? artifact) : null; const sourcePrefixes = Array.isArray(artifact?.sourcePrefixes) ? artifact.sourcePrefixes : []; const tests = flags['tests-evidence'] ? { criticalSuitesPassing: true, evidenceFile: flags['tests-evidence'] } : { criticalSuitesPassing: false, evidenceFile: null }; const proposed = flags['proposed-limits'] ? readJson(flags['proposed-limits'], 'proposed limits') : null;
      let evaluation = null; if (ev) evaluation = ev; else if (env.DATABASE_URL || dbFactory) { try { evaluation = await withJournal(async (j) => { const l = await j.load(account); if (!l) return null; const e = evaluateAccount(l.state, { arm: 'REF_COMBINED' }); return { paperAccountId: account, forwardClosedTrades: e.support.closedTrades, holdoutUntouched: false, netPnl: e.netPnl ?? null, drawdown: typeof e.drawdown === 'number' ? e.drawdown : null, feesAccounted: true, openPositions: e.denominators.open, evaluationDigest: null, source: flags['evaluation-source'] ?? 'NONE' }; }); } catch { evaluation = null; } }
      const m = prepareRelease({ codeTreeDigest: codeTreeDigest({ cwd }), policy, policyDigest: digest, evaluation, tests, sourcePrefixes, coverage: { dataFamilies: [], latencySamples: 0 }, acceptance: { independentReview: flags.review ?? 'NOT_RUN', reviewer: flags.reviewer ?? null }, unresolvedFailures: flags.unresolved ? readJson(flags.unresolved, 'unresolved failures') : [], proposedLimits: proposed, nowTs: now() }); if (flags.out) { mkdirSync(path.dirname(flags.out), { recursive: true }); atomicWriteJson(flags.out, m, { pretty: true }); } return { ok: true, command: 'prepare-release', state: m.state, blockers: m.blockers, manifestDigest: m.manifestDigest, file: flags.out ?? null, authority: 'READ_ONLY_NO_TRADING_PERMISSION' }; },
    async 'approve-release'(flags) { const mf = readManifest(flags.manifest); if (!mf.ok) throw new CommandError(mf.reason, mf.detail ?? mf.reason, EXIT.INVALID_INPUT); const assessment = readFileSync(flags.assessment, 'utf8'); const o = await owner('approve-release', flags, { manifestDigest: flags['manifest-digest'] }); const r = approveRelease({ manifest: mf.manifest, manifestDigest: flags['manifest-digest'], assessment, ownerRef: o.ownerRef, sessionTag: o.sessionTag, nowTs: now() }); if (!r.ok) throw new CommandError(r.reason, `approval refused: ${r.reason}${r.blockers ? ` ${r.blockers.join(',')}` : ''}`, EXIT.REFUSED); const file = writeApproval(r.approval); return { ok: true, command: 'approve-release', approvalId: r.approval.approvalId, releaseDigest: r.approval.releaseDigest, file, grants: r.approval.grants }; },
    async kill(flags) { return restriction('kill', flags); }, async cage(flags) { return restriction('cage', flags); }, async veto(flags) { if (!flags['prediction-id']) throw new CommandError('INVALID_REQUEST', 'veto needs --prediction-id'); return restriction('veto', flags); },
    async reconcile(flags) { const { policy, digest } = policyOf(flags); const account = accountOf(flags, policy); const mode = policy.mode === 'LIVE' ? 'LIVE_UNARMED' : 'PAPER'; await owner('reconcile', flags, { accountId: account, policyDigest: digest, mode }); return withJournal(async (j) => { const run = await composeJudge({ policyFile: flags.policy, mode, accountId: account, env, log, journal: j, transport: mode === 'LIVE_UNARMED' ? (transport ?? ((u, i) => fetch(u, i))) : transport, allowPrivate: () => flags['allow-private'] === true, allowOrders: () => false, writeProjection: false }); try { const r = await run.dispatcher.restart({ scope: 'REQUESTED' }); return { ok: true, command: 'reconcile', accountId: account, mode, report: r, revision: run.dispatcher.revision() }; } finally { await run.stop(); } }); },
    async status(flags) { let projection = null; try { projection = parseStrictJson(readFileSync(projectionFile(), 'utf8')); } catch { projection = null; } let acct = null; if (flags.policy && (env.DATABASE_URL || dbFactory)) { const { policy } = policyOf(flags); const account = accountOf(flags, policy); try { acct = await withJournal(async (j) => redactedAccount(await j.load(account))); } catch (err) { acct = { unavailable: err.code ?? err.message }; } } return { ok: true, command: 'status', projection: projection ? { ...projection, fresh: now() - projection.ts <= 15_000 } : null, projectionFile: projectionFile(), account: acct, authority: 'READ_ONLY' }; },
    // evaluate (closeout R13): bounded pages of the WHOLE durable history (never the 256-entry projection window), one durable split
    // declaration per account reused on every later evaluation, one independent simulated account per configured arm, every arm
    // reported SCORED or UNSCORABLE with its reason; the artifact carries the evaluation digest and its source prefixes for prepare-release
    async evaluate(flags) { const { policy, digest } = policyOf(flags); const account = accountOf(flags, policy); return withJournal(async (j) => { const l = await j.load(account); if (!l) throw new CommandError('ACCOUNT_UNKNOWN', account, EXIT.INVALID_INPUT); const state = l.state;
      const events = []; let after = 0; let pages = 0; for (;;) { const page = await j.page(account, { afterSeq: after, limit: 500 }); if (!page.length) break; pages += 1; for (const row of page) { events.push(row.event); after = row.seq; } }
      const decisions = events.filter((e) => e.type === 'DECISION_RECORDED').map((e) => e.payload); const episodes = decisions.map((d) => ({ episodeId: d.episodeId, assetId: d.assetId, firstKnownTs: d.decisionKnownAtTs, lastTs: d.decisionKnownAtTs }));
      const splitsFile = path.join(judgeDir(), 'evaluation', `splits-${account}.json`); const declared = existsSync(splitsFile) ? readJson(splitsFile, 'split declaration') : null; const splits = declareSplits({ episodes, fractions: policy.evaluation.splits, embargoMs: policy.evaluation.splits.embargoMs, seed: policy.evaluation.seed, nowTs: now(), declared }); if (splits.declaration === 'FRESH') { mkdirSync(path.dirname(splitsFile), { recursive: true }); atomicWriteJson(splitsFile, splits, { pretty: true }); }
      const arms = evaluateArms({ accountId: account, events, arms: policy.evaluation.arms, seed: policy.evaluation.seed }); const ref = arms.arms.REF_COMBINED?.evaluation ?? null; const sourcePrefixes = [`journal:${account}:${String(l.headDigest ?? 'none').slice(0, 16)}`]; const evaluationDigest = digestOf({ arms: arms.arms, splits: { assignment: splits.assignment, digest: splits.digest }, headDigest: l.headDigest, sourcePrefixes });
      const release = { paperAccountId: account, forwardClosedTrades: ref?.support.closedTrades ?? 0, holdoutUntouched: false, netPnl: ref?.netPnl ?? null, drawdown: typeof state.performance?.drawdown === 'number' ? state.performance.drawdown : null, feesAccounted: true, openPositions: ref?.denominators.open ?? 0, evaluationDigest, source: state.accountKind === 'PAPER' ? 'FORWARD_PAPER' : state.accountKind === 'REPLAY' ? 'REPLAY' : 'NONE' };
      const out = { ok: true, command: 'evaluate', accountId: account, policyDigest: digest, revision: l.revision, headDigest: l.headDigest, history: { events: events.length, pages, decisions: decisions.length, projectionWindow: Object.keys(state.decisions ?? {}).length }, arms: arms.arms, splits, splitsFile, experience: experienceLedger(state, decisions), evaluationDigest, sourcePrefixes, release, calibrationState: 'UNVALIDATED_HYPOTHESIS', law: 'no reported return without basis; zero trades is a valid result, not a profitability seal; the holdout is examined here, so this artifact alone never qualifies a release' }; if (flags.out) { mkdirSync(path.dirname(flags.out), { recursive: true }); atomicWriteJson(flags.out, out, { pretty: true }); } return out; }); },
    async verify(flags) { const out = { ok: true, command: 'verify', checks: {} }; if (flags.policy) { const { policy, digest } = policyOf(flags); out.checks.policy = { ok: true, policyName: policy.policyName, digest }; if (flags.account || (env.DATABASE_URL || dbFactory)) { const account = accountOf(flags, policy); try { out.checks.journal = await withJournal(async (j) => (await j.exists(account)) ? { account, ...(await j.replayVerify(account)) } : { account, ok: false, reason: 'ACCOUNT_UNKNOWN' }); } catch (err) { out.checks.journal = { ok: false, reason: err.code ?? err.message }; } if (out.checks.journal && out.checks.journal.ok === false) out.ok = false; } }
      if (flags.case) { const v = await createCaseVerifier({ clock: now }).verify(flags.case); out.checks.case = { ok: v.ok, reasons: v.reasons ?? [], caseId: v.manifest?.caseId ?? null }; if (!v.ok) out.ok = false; }
      // a recording verifies only when it is SEALED COMPLETE with every segment present and digest-exact (closeout R11): partial data is never complete
      if (flags.recording) { const v = verifyRecording(flags.recording); out.checks.recording = v; if (!v.ok) out.ok = false; }
      if (flags.manifest) { const m = readManifest(flags.manifest); out.checks.manifest = m.ok ? { ok: true, state: m.manifest.state, manifestDigest: m.manifest.manifestDigest } : { ok: false, reason: m.reason, detail: m.detail }; if (!m.ok) out.ok = false; }
      if (flags.approval) { const a = readApproval(flags.approval); out.checks.approval = a.ok ? { ok: true, approvalId: a.approval.approvalId, releaseDigest: a.approval.releaseDigest } : { ok: false, reason: a.reason }; if (!a.ok) out.ok = false; }
      out.codeDigest = codeTreeDigest({ cwd }); return out; },
  };
  async function restriction(action, flags) { await owner(action, flags, { predictionId: flags['prediction-id'] ?? null }); const r = await applyRestriction(action, { predictionId: flags['prediction-id'] ?? null, source: 'judge-cli' }); if (!r.ok) throw new CommandError('CONTROL_REFUSED', r.error, EXIT.REFUSED); return { ok: true, command: action, controls: { kill: Boolean(r.controls.kill?.active), cage: Boolean(r.controls.cage?.active), vetoes: (r.controls.vetoes ?? []).length }, durable: r.durable, note: 'the shared control layer: a running Judge / Watch reads it on the next tick; KILL is reduce-only until owner CLEAR' }; }
  async function liveRun(flags, command) { const { policy, digest } = policyOf(flags); if (policy.mode !== 'LIVE') throw new CommandError('MODE_MISMATCH', `${command} needs a LIVE policy`); const account = accountOf(flags, policy); const o = await owner(command, flags, { accountId: account, policyDigest: digest, mode: 'LIVE' }); if (flags['allow-private'] !== true) throw new CommandError('PRIVATE_NOT_AUTHORIZED', `${command} sends private calls: pass --allow-private true`, EXIT.REFUSED);
    return withJournal(async (j) => { const l = await j.load(account); if (!l?.state.initialized) throw new CommandError('ACCOUNT_UNINITIALIZED', `${account}: run preflight-live first`, EXIT.REFUSED); const a = l.state.authorization; const active = a && !a.ended && a.expiresTs > now(); const wantKind = command === 'canary-live' ? 'CANARY' : 'LIVE_ARM'; const mode = active && a.kind === wantKind ? 'LIVE_ARMED' : 'LIVE_UNARMED'; if (command === 'canary-live' && mode !== 'LIVE_ARMED') throw new CommandError('CANARY_UNAUTHORIZED', 'canary-live needs its own active CANARY authorization (arm-live --canary-pair ...)', EXIT.REFUSED);
      let preflightPassed = false; const run = await composeJudge({ policyFile: flags.policy, mode, accountId: account, env, log, journal: j, transport: transport ?? ((u, i) => fetch(u, i)), WebSocketImpl, specs: flags.pairs ? await specsFor(policy, flags.pairs.split(',')) : [], casesDir: flags.cases ?? null, recordDir: flags.record ?? null, allowPrivate: () => true, allowOrders: () => preflightPassed && mode === 'LIVE_ARMED', nominations: () => (command === 'canary-live' ? [{ symbol: a.canary.pair, assetId: a.canary.pair.split('/')[0] }] : flags.pairs ? flags.pairs.split(',').map((s) => ({ symbol: s, assetId: s.split('/')[0] })) : []) });
      // ONE lifecycle law (closeout R15): the composition's start() claims the venue owner slot before any private call and stop() releases it only after a verified SHUTDOWN reconciliation
      let report; let stopped = null; try { try { report = await run.start(); } catch (err) { if (err.code === 'LIVE_OWNER_HELD') throw new CommandError('LIVE_OWNER_HELD', err.message, EXIT.REFUSED); throw err; } const pf = await run.preflight(); preflightPassed = Boolean(pf.ok); if (mode === 'LIVE_ARMED' && preflightPassed && run.dispatcher.state().mode !== 'LIVE_ARMED') { const { makeEvent } = await import('../execution/contract.js'); await run.dispatcher.commit(makeEvent({ type: 'MODE_TRANSITION', accountId: account, knownAtTs: now(), payload: { from: run.dispatcher.state().mode, to: 'LIVE_ARMED', reason: `${command}: unexpired ${wantKind} authorization resumed after reconciliation`, authorizationId: a.authorizationId, ts: now() } })); } if (tapeRunner) await tapeRunner({ executionFeed: run.tapeFeed, minutes: flags.minutes ?? null, run }); else { const { runTape } = await import('../tape/run.js'); await runTape({ executionFeed: run.tapeFeed, minutes: flags.minutes ?? null, log }); } } finally { stopped = await run.stop(); }
      return { ok: true, command, accountId: account, mode, ownerRef: o.ownerRef, preflightPassed, startup: report, shutdown: stopped ? { ownerRelease: stopped.ownerRelease, lifecycle: stopped.lifecycle } : null, projection: run.projection() }; }); }
  return cmds;
}
async function readTwoLines(stdin, flags) { if (flags['owner-stdin'] !== true || !stdin) return [null, null]; const text = await new Promise((resolve, reject) => { let buf = ''; stdin.setEncoding('utf8'); stdin.on('data', (c) => { buf += c; }); stdin.on('end', () => resolve(buf)); stdin.on('error', reject); }); const lines = text.split('\n'); return [lines[0]?.length ? lines[0] : null, lines[1]?.length ? lines[1] : null]; }
export { judgeDir };
