// JUDGE — the closed, versioned decision language (ticket §2.3). One validator for generation, durable append (the bounded
// DECISION_RECORDED payload carries the digest), reopening, replay, status exports and the public API. Closed input-mode
// variants (MARKET_DIRECT with explicit null case refs; CASE_ENRICHED / CATALYST_CASE with every verified reference), closed
// decision states, typed structured predicates only (never executable strings, URLs or field paths), own-property checks.
import { shapeError, T, nullable, listOf, digestOf, ContractError } from '../execution/contract.js';

export const DECISION_VERSION = 'judge-decision-1';
export const DECISION_STATES = Object.freeze(['NO_TRADE', 'NEEDS_DATA', 'WATCH_CANDIDATE', 'ENTRY_PROPOSED', 'ENTRY_RESERVED', 'ENTRY_REFUSED', 'EXPIRED']);
export const INPUT_MODES = Object.freeze(['MARKET_DIRECT', 'CASE_ENRICHED', 'CATALYST_CASE']);
export const PREDICATE_OPS = Object.freeze(['GTE', 'GT', 'LTE', 'LT', 'EQ', 'BETWEEN', 'TRUE', 'KNOWN']);
export const CALIBRATION_STATES = Object.freeze(['UNVALIDATED_HYPOTHESIS', 'EMPIRICALLY_SUPPORTED']);
const MEASUREMENT = Object.freeze({ id: T.id, ok: T.bool, ablated: T.opt(T.bool), /* research ablation marker (focused completion): present only when a clause was measured but not decisive */ value: (v) => v === null || typeof v === 'boolean' || typeof v === 'number' && Number.isFinite(v) || typeof v === 'string' && v.length <= 64, threshold: (v) => v === null || typeof v === 'boolean' || typeof v === 'number' && Number.isFinite(v) || typeof v === 'string' && v.length <= 64, unit: T.id, note: T.textOrNull });
const PREDICATE = Object.freeze({ field: T.id, op: T.en(PREDICATE_OPS), value: (v) => v === null || typeof v === 'number' && Number.isFinite(v) || typeof v === 'string' && v.length <= 64 || typeof v === 'boolean' || (Array.isArray(v) && v.length === 2), unit: T.id });
const CASE_REFS = Object.freeze({ packetId: T.idOrNull, analysisId: T.idOrNull, caseId: T.idOrNull, caseCompletionTs: T.tsOrNull, caseReceiptTs: T.tsOrNull, direction: T.enOrNull(['UPWARD_PRESSURE', 'DOWNWARD_PRESSURE', 'MIXED', 'NO_CLEAR_DIRECTION', 'UNKNOWN']), provenance: T.idOrNull, eventId: T.idOrNull, eventTaxonomy: T.idOrNull });
export const DECISION_SCHEMA = Object.freeze({
  decisionVersion: T.en([DECISION_VERSION]), decisionId: T.id, accountId: T.id, mode: T.en(['OBSERVE', 'REPLAY', 'PAPER', 'LIVE_UNARMED', 'LIVE_ARMED', 'REDUCE_ONLY', 'HALTED_UNRESOLVED']), strategyVersion: T.id, policyDigest: T.hex64, costModelVersion: T.id,
  asset: { canonicalCoin: T.id, venue: T.en(['kraken']), pair: T.id, specDigest: T.hex64 }, episodeId: T.id, setupId: T.id, decisionKnownAtTs: T.ts, triggerTs: T.ts,
  inputMode: T.en(INPUT_MODES), caseRefs: CASE_REFS,
  sourcePrefix: { snapshotDigest: T.hex64OrNull, feedEpoch: (v) => v === null || T.count(v), receiptSequence: (v) => v === null || T.count(v), barBlockDigest: T.hex64OrNull, tradeCoverageStartTs: T.tsOrNull, tradeCoverageEndTs: T.tsOrNull },
  featureSnapshotRef: T.hex64OrNull, portfolioRevision: T.count, restrictionRevision: T.count,
  status: T.en(DECISION_STATES), reasonCodes: T.idList, measurements: listOf(MEASUREMENT, 64), predicates: listOf(PREDICATE, 32),
  invalidation: nullable({ structuralStop: T.posDec, kind: T.en(['ABSOLUTE_PRICE_BELOW']) }), scenario: nullable({ target: T.decOrNull, cappedBy: T.decOrNull, kind: T.en(['SCENARIO_NOT_FORECAST']) }),
  valuationRef: nullable({ snapshotDigest: T.hex64, entryLimitPrice: T.posDec, entryCashOut: T.posDec, entryBookEstimateCashOut: T.posDec, scenarioExitCashIn: T.posDec, scenarioNetProfit: T.dec, executionUncertaintyBuffer: T.nonNegDec, bufferedScenarioNetProfit: T.dec, scenarioStressedLoss: T.dec, rewardRiskRatio: T.decOrNull, feeDigest: T.hex64, expectancyState: T.en(['UNCALIBRATED']) }),
  sizing: nullable({ q: T.posDec, entryLimitPrice: T.posDec, entryCashOut: T.posDec, riskUsd: T.posDec, bufferedScenarioNetProfit: T.dec, binding: T.idList, clusterId: T.id }),
  calibrationState: T.en(CALIBRATION_STATES), decisionDigest: T.hex64,
});
export function decisionError(d) { const e = shapeError(d, DECISION_SCHEMA, 'decision'); if (e) return e; if (digestOf({ ...d, decisionDigest: null }) !== d.decisionDigest) return 'decision: digest does not match content'; const r = d.caseRefs; if (d.inputMode === 'MARKET_DIRECT') { for (const k of ['packetId', 'analysisId', 'caseId', 'caseCompletionTs', 'caseReceiptTs', 'eventId']) if (r[k] !== null) return `decision: MARKET_DIRECT carries ${k}`; } else { for (const k of ['packetId', 'analysisId', 'caseId', 'caseCompletionTs', 'caseReceiptTs', 'provenance']) if (r[k] === null) return `decision: ${d.inputMode} needs ${k}`; if (d.inputMode === 'CATALYST_CASE' && (r.eventId === null || r.eventTaxonomy === null || r.direction !== 'UPWARD_PRESSURE')) return 'decision: CATALYST_CASE needs the primary-confirmed event and an UPWARD_PRESSURE mechanism'; } if ((d.status === 'ENTRY_PROPOSED' || d.status === 'ENTRY_RESERVED') && (d.sizing === null || d.valuationRef === null)) return `decision: ${d.status} needs sizing and a valuation`; if (d.calibrationState === 'EMPIRICALLY_SUPPORTED') return 'decision: no separately supported empirical calibration evidence exists in this release'; if (d.decisionKnownAtTs < d.triggerTs) return 'decision: decided before its trigger'; if (r.caseCompletionTs !== null && r.caseCompletionTs > d.decisionKnownAtTs) return 'decision: case completed after the decision'; return null; }
export function makeDecision(body) { const d = { decisionVersion: DECISION_VERSION, calibrationState: 'UNVALIDATED_HYPOTHESIS', ...body, decisionDigest: 'x'.repeat(64) }; d.decisionDigest = digestOf({ ...d, decisionDigest: null }); const e = decisionError(d); if (e) throw new ContractError(e, 'DECISION_INVALID'); return Object.freeze(d); }
export const decisionIdentity = ({ accountId, episodeId, setupId, decisionKnownAtTs, snapshotDigest }) => `dec-${digestOf({ accountId, episodeId, setupId, decisionKnownAtTs, snapshotDigest }).slice(0, 32)}`;
// the bounded durable projection of a decision (the DECISION_RECORDED payload)
export function decisionRecord(d, verdicts = null) { return { ...(verdicts ? { verdicts } : {}), decisionId: d.decisionId, episodeId: d.episodeId, assetId: d.asset.canonicalCoin, pair: d.asset.pair, setupId: d.setupId, inputMode: d.inputMode, state: d.status, reasonCodes: d.reasonCodes.slice(0, 64), decisionKnownAtTs: d.decisionKnownAtTs, decisionDigest: d.decisionDigest, sizing: d.sizing ? { q: d.sizing.q, entryLimitPrice: d.sizing.entryLimitPrice, entryCashOut: d.sizing.entryCashOut, riskUsd: d.sizing.riskUsd, bufferedScenarioNetProfit: d.sizing.bufferedScenarioNetProfit } : null, strategyVersion: d.strategyVersion, policyDigest: d.policyDigest }; }
