// WATCH — exposure first, until exchange-confirmed flat (ticket §8). A position shell and feed / protection slot exist
// BEFORE entry; the first partial fill is the highest-priority tracked risk. One serialized exit coordinator per position;
// deterministic single primary priority code with every supported reason retained; never two competing sells. Native
// structural stop submitted with entry; Watch observes its trigger and reconciles native fills. Reference deterioration,
// 1R trail (durably latched, continuous, coalesced, one unresolved amendment, 1000ms spacing), planned target on the ACTUAL
// residual, no-progress at 180s, mandatory duration 4h from FIRST fill. Health: book age > 1s blocks entries, > 5s cancels
// entry remainder and impairs, > 10s protective closure ONLY when a safe sell is known, else HALTED_UNRESOLVED with alert.
// KILL = halt additions and ATTEMPT a safe flatten, then stay killed (KILL_REQUESTED is not KILL_COMPLETE). FLAT only when
// confirmed residual is zero, pending possibilities are resolved and no orphan protective order remains.
import * as M from '../execution/money.js';
import { TERMINAL_ORDER_STATES } from '../execution/contract.js';
import { ownedBase } from '../execution/reducer.js';
import { reductionAuthority } from '../execution/authority.js';
import { createFlowTracker, bidDepthWithinBps, bookFacts, medianDecimal } from '../judge/features.js';
import { liquidationValue, scenarioExit, stopStressMid, bufferOf } from '../judge/cost.js';

export const WATCH_VERSION = 'watch-paper-reference-1';
export const WATCH_REFERENCE = Object.freeze({ heartbeatMs: 250, deterioration: { fi: -0.2, depthFraction: '0.5', minBooks: 3, spanMs: 2000, baselineMinSamples: 30, baselineWindowMs: 60_000, fiWindowMs: 15_000 }, trail: { rMultiple: '1', atrMultiple: '1', spacingMs: 1000 }, noProgress: { afterMs: 180_000, minRFraction: '0.25' }, health: { bookAgeMs: 1000, impairedMs: 5000, criticalMs: 10_000 }, protectionConfirmMs: 2000, plannedExitTimeoutMs: 5000, maxDurationMs: 4 * 3_600_000 });
const PRIORITY = { OWNER_KILL: 'P1_KILL_OR_INVALID_PROTECTION', CRITICAL_OPERATIONAL: 'P1_KILL_OR_INVALID_PROTECTION', PROTECTION_INVALID: 'P1_KILL_OR_INVALID_PROTECTION', NATIVE_STOP: 'P2_STRUCTURAL_INVALIDATION', STRUCTURAL_STOP: 'P2_STRUCTURAL_INVALIDATION', THESIS_FALSIFIED: 'P2_STRUCTURAL_INVALIDATION', DETERIORATION: 'P3_FLOW_LIQUIDITY_DETERIORATION', TRAIL_CROSSED: 'P4_TRAIL_OR_TARGET', PLANNED_TARGET: 'P4_TRAIL_OR_TARGET', NO_PROGRESS: 'P5_NO_PROGRESS_DURATION_RISK', MAX_DURATION: 'P5_NO_PROGRESS_DURATION_RISK', RISK_POLICY: 'P5_NO_PROGRESS_DURATION_RISK', FEED_UNUSABLE: 'P1_KILL_OR_INVALID_PROTECTION' };
const ORDER = ['OWNER_KILL', 'CRITICAL_OPERATIONAL', 'PROTECTION_INVALID', 'FEED_UNUSABLE', 'NATIVE_STOP', 'STRUCTURAL_STOP', 'THESIS_FALSIFIED', 'DETERIORATION', 'TRAIL_CROSSED', 'PLANNED_TARGET', 'NO_PROGRESS', 'MAX_DURATION', 'RISK_POLICY'];
const PROTECTIVE = new Set(['OWNER_KILL', 'CRITICAL_OPERATIONAL', 'PROTECTION_INVALID', 'FEED_UNUSABLE', 'NATIVE_STOP', 'STRUCTURAL_STOP', 'THESIS_FALSIFIED', 'DETERIORATION', 'TRAIL_CROSSED', 'MAX_DURATION', 'RISK_POLICY']);

export function createWatch({ accountId, dispatcher, adapter, feed = null, clock, specOf, feeOf, controls = () => ({ kill: false, cage: false }), falsifiers = () => [], policy = WATCH_REFERENCE, onClosed = () => {}, snapshotStore = null, log = () => {} }) {
  const P = policy; const T = new Map(); const now = () => clock.now(); const mono = () => clock.monotonic(); const counters = { books: 0, trades: 0, exitsStarted: 0, amends: 0, amendsCoalesced: 0, targetsHit: 0, deteriorations: 0, noProgress: 0, durations: 0, halted: 0, killRequested: 0, protectionMismatch: 0, reductionRefusals: 0, overlappedTicks: 0, snapshotPersistFailures: 0, eventLoopDelaySamples: [] }; let killComplete = false; let haltedLatched = false; let lastTickMono = null;
  const state = () => dispatcher.state(); const ev = dispatcher.ev;
  // durable restore (closeout R07): the per-unit target basis (POSITION_R), an in-progress exit (WATCH_STATE), the trail / highest bid
  const restoredExit = (pos) => { const x = pos.exit; if (!x || !['REQUESTED', 'IN_PROGRESS'].includes(x.state)) return { phase: 'NONE', reason: null, priority: null, startedMono: null, orderId: null, startedTs: null }; const openSell = Object.values(state()?.orders ?? {}).find((o) => o.positionId === pos.positionId && o.side === 'sell' && o.kind !== 'PROTECTIVE_STOP' && !TERMINAL_ORDER_STATES.includes(o.state)) ?? null; return { phase: 'CANCELLING_REMAINDER', reason: x.primaryReason, priority: x.priority, startedMono: mono(), startedTs: x.ts ?? now(), orderId: openSell?.orderId ?? null, protective: x.primaryReason ? PROTECTIVE.has(x.primaryReason) : true, restored: true }; };
  const track = (pos) => { if (!T.has(pos.positionId)) T.set(pos.positionId, { positionId: pos.positionId, symbol: pos.pair, flow: createFlowTracker({ retentionMs: 120_000, maxTrades: 20_000 }), depth: [], det: [], highestBid: pos.highestBid ?? null, maxNetPnl: null, lastNetPnl: null, lastBook: null, lastAmendMono: null, exit: restoredExit(pos), firstFillMono: pos.firstFillTs ? mono() - Math.max(0, now() - pos.firstFillTs) : null, protectionAlertedTs: null, remainderCancel: 'NONE', targetPerUnit: pos.initialR?.targetPerUnit ?? null, restored: Boolean(pos.firstFillTs), latencies: { firstFillToWatchMs: null, firstFillToProtectionMs: null, firstFillToExitMs: null } }); return T.get(pos.positionId); };
  const openPositions = () => Object.values(state()?.positions ?? {}).filter((p) => !['FLAT'].includes(p.state));
  const residualOf = (pos) => ownedBase(pos);
  // ---- P&L / R against the frozen admission recipe --------------------------------------------------------------------------
  function netLiquidation(pos, book) { const q = residualOf(pos); if (M.isZero(q) || !book) return null; const spec = specOf(pos.pair); const fee = feeOf(pos.pair); const lv = liquidationValue({ snapshot: book, q, spec, fee }); if (lv.status !== 'OK') return null; const soldFrac = M.isZero(pos.confirmedBase) ? '0' : M.div(pos.soldBase, pos.confirmedBase, 18, 'DOWN'); const entryForResidual = M.mul(M.add(pos.entryQuote, pos.entryFeesQuote), M.sub('1', soldFrac)); return { cashIn: lv.cashIn, entryAllocated: entryForResidual, netPnl: M.sub(lv.cashIn, entryForResidual), snapshotDigest: book.digest }; }
  async function finalizeR(pos, t) { if (pos.initialR.state === 'FINAL') return; const eo = pos.entryOrderId ? state().orders[pos.entryOrderId] : null; if (!eo || !TERMINAL_ORDER_STATES.includes(eo.state) || M.isZero(pos.confirmedBase) || !t.lastBook) return; const spec = specOf(pos.pair); const fee = feeOf(pos.pair); const f = bookFacts(t.lastBook); const stressMid = stopStressMid({ stop: pos.structuralStop, atr14: pos.atr14, spread: f.spread, tick: spec.priceIncrement }); if (!M.isPositive(stressMid)) return; const stress = scenarioExit({ snapshot: t.lastBook, q: residualOf(pos), scenarioMid: stressMid, spec, fee }); if (stress.status !== 'OK') return; const entryCashOut = M.add(pos.entryQuote, pos.entryFeesQuote); const R = M.sub(entryCashOut, stress.cashIn); if (!M.isPositive(R)) return; const vwap = M.div(pos.entryQuote, pos.confirmedBase, 8, 'HALF_UP'); if (pos.targetPrice) { const tgt = scenarioExit({ snapshot: t.lastBook, q: residualOf(pos), scenarioMid: pos.targetPrice, spec, fee }); if (tgt.status === 'OK') t.targetPerUnit = M.div(tgt.cashIn, residualOf(pos), 8, 'DOWN'); /* 8 decimals: a later per-unit x 8-decimal residual product stays inside the exact 18-decimal bound */ } await dispatcher.commit(ev('POSITION_R', { positionId: pos.positionId, state: 'FINAL', initialR: R, entryVwap: vwap, entryCashOut, confirmedBase: pos.confirmedBase, reason: 'entry IOC terminal; fills reconciled; frozen stress recipe on the current accepted book', ts: now(), targetPerUnit: t.targetPerUnit ?? null })); }
  // ---- feed -------------------------------------------------------------------------------------------------------------------
  function onBook(e) { for (const pos of openPositions()) { if (pos.pair !== e.symbol) continue; const t = track(pos); const snap = e.snapshot; if (!snap.synced) continue; t.lastBook = snap; counters.books += 1; const f = bookFacts(snap); if (!f) continue; if (!t.highestBid || M.gt(f.bestBid, t.highestBid)) t.highestBid = f.bestBid; const depth = bidDepthWithinBps(snap, 10); t.depth.push({ ts: snap.receiptTs, depth, sequence: snap.receiptSequence }); while (t.depth.length && t.depth[0].ts < snap.receiptTs - P.deterioration.baselineWindowMs - P.deterioration.fiWindowMs) t.depth.shift(); const nl = netLiquidation(pos, snap); if (nl) { t.lastNetPnl = nl; if (t.maxNetPnl === null || M.gt(nl.netPnl, t.maxNetPnl)) t.maxNetPnl = nl.netPnl; } } }
  function onTrade(e) { for (const pos of openPositions()) { if (pos.pair !== e.symbol) continue; const t = track(pos); t.flow.add(e.trade); counters.trades += 1; t.lastTradePrice = e.trade.price; t.lastTradeTs = e.trade.receiptTs; } }
  if (feed) feed.subscribe((e) => { if (e.kind === 'BOOK') onBook(e); else if (e.kind === 'TRADE') onTrade(e); });
  // ---- reasons ----------------------------------------------------------------------------------------------------------------
  function deterioration(pos, t, nowTs) { const d = P.deterioration; const fi = t.flow.fi(nowTs - d.fiWindowMs, nowTs); const cur = t.depth.filter((x) => x.ts >= nowTs - d.fiWindowMs); const base = t.depth.filter((x) => x.ts >= nowTs - d.fiWindowMs - d.baselineWindowMs && x.ts < nowTs - d.fiWindowMs).map((x) => x.depth).filter((x) => x !== null); if (fi.state !== 'KNOWN' || base.length < d.baselineMinSamples || !cur.length) return { active: false, reason: fi.state !== 'KNOWN' ? 'FI_UNKNOWN' : base.length < d.baselineMinSamples ? 'BASELINE_SUPPORT' : 'NO_CURRENT_BOOK', fi: fi.fi ?? null, baselineSamples: base.length }; const median = medianDecimal(base); const threshold = M.mul(median, d.depthFraction); const latest = cur.at(-1); const bad = fi.fi <= d.fi && latest.depth !== null && M.lt(latest.depth, threshold); if (!bad) { t.det = []; return { active: false, reason: 'NOT_DETERIORATED', fi: fi.fi, median, current: cur.at(-1).depth }; } const last = t.det.at(-1); if (!last || last.sequence !== cur.at(-1).sequence) t.det.push({ ts: nowTs, sequence: cur.at(-1).sequence }); const persisted = t.det.length >= d.minBooks && t.det.at(-1).ts - t.det[0].ts >= d.spanMs; return { active: persisted, reason: persisted ? 'DETERIORATION' : 'DEBOUNCING', fi: fi.fi, median, current: cur.at(-1).depth, books: t.det.length, spanMs: t.det.length ? t.det.at(-1).ts - t.det[0].ts : 0, since: t.det[0]?.ts ?? null }; }
  function evaluateReasons(pos, t, nowTs) {
    const reasons = []; const c = controls(); const s = state(); const hb = t.lastBook ? nowTs - t.lastBook.receiptTs : null; const feedHealth = feed ? feed.health(pos.pair, nowTs) : { usable: t.lastBook !== null, impaired: hb === null || hb > P.health.impairedMs, critical: hb === null || hb > P.health.criticalMs };
    if (c.kill || s.restrictions.KILL) reasons.push('OWNER_KILL');
    // unprotected owned inventory (no live set, or the confirmed children cover less than owned) past the confirmation window after the LAST fill
    const covered = ['ACTIVE', 'AMEND_PENDING', 'TRIGGERED'].includes(pos.protection.state) && !(pos.protection.coverage !== undefined && !M.isZero(residualOf(pos)) && M.lt(pos.protection.coverage, residualOf(pos)));
    if (!M.isZero(residualOf(pos)) && !covered && t.firstFillMono !== null && mono() - t.firstFillMono > P.protectionConfirmMs && nowTs - (pos.lastEconomicTs ?? pos.firstFillTs ?? nowTs) > P.protectionConfirmMs && t.exit.phase === 'NONE') reasons.push('PROTECTION_INVALID');
    if (pos.protection.state === 'TRIGGERED') reasons.push('NATIVE_STOP');
    if (t.lastTradePrice && M.lte(t.lastTradePrice, pos.structuralStop) && !['ACTIVE', 'AMEND_PENDING', 'TRIGGERED', 'PENDING'].includes(pos.protection.state)) reasons.push('STRUCTURAL_STOP');
    for (const f of falsifiers()) if (f.verified === true && (f.positionId === pos.positionId || f.assetId === pos.assetId) && ['PRIMARY_CORRECTION', 'VENUE_SUSPENSION', 'EXPLOIT_DISCLOSURE'].includes(f.factType)) reasons.push('THESIS_FALSIFIED');
    const det = deterioration(pos, t, nowTs); if (det.active) reasons.push('DETERIORATION');
    if (feedHealth.critical && t.firstFillMono !== null) reasons.push('FEED_UNUSABLE');
    const R = pos.initialR.state === 'FINAL' ? pos.initialR.value : null; const nl = t.lastNetPnl;
    if (R && nl) { if (pos.trailActive && t.lastBook && pos.protection.trigger && bookFacts(t.lastBook) && M.lte(bookFacts(t.lastBook).bestBid, pos.protection.trigger)) reasons.push('TRAIL_CROSSED'); if (t.targetPerUnit && M.gte(nl.cashIn, M.mul(t.targetPerUnit, residualOf(pos)))) reasons.push('PLANNED_TARGET'); const elapsed = t.firstFillMono === null ? 0 : mono() - t.firstFillMono; if (elapsed >= P.noProgress.afterMs) { const fi60 = t.flow.fi(nowTs - 60_000, nowTs); if (fi60.state === 'KNOWN' && t.maxNetPnl !== null && M.lt(t.maxNetPnl, M.mul(R, P.noProgress.minRFraction)) && M.lte(nl.netPnl, '0') && fi60.fi <= 0) reasons.push('NO_PROGRESS'); } }
    if (pos.durationDeadlineTs && nowTs >= pos.durationDeadlineTs) reasons.push('MAX_DURATION');
    const primary = ORDER.find((r) => reasons.includes(r)) ?? null; return { reasons, primary, priority: primary ? PRIORITY[primary] : null, det, feedHealth };
  }
  // ---- trail --------------------------------------------------------------------------------------------------------------------
  async function trail(pos, t, nowTs) {
    const R = pos.initialR.state === 'FINAL' ? pos.initialR.value : null; if (!R || !t.lastNetPnl) return; if (!pos.trailActive) { if (M.gte(t.lastNetPnl.netPnl, M.mul(R, P.trail.rMultiple))) { await dispatcher.commit(ev('WATCH_STATE', { positionId: pos.positionId, trailActive: true, highestBid: t.highestBid, exitState: 'NONE', primaryReason: null, priority: null, supportedReasons: [], ts: nowTs })); } return; }
    if (pos.protection.state !== 'ACTIVE' || !pos.protection.orderId) return; const spec = specOf(pos.pair); const desired = M.roundToStep(M.max(pos.protection.trigger ?? '0', M.sub(t.highestBid, M.mul(pos.atr14, P.trail.atrMultiple))), spec.priceIncrement, 'FLOOR'); if (!M.gt(desired, pos.protection.trigger ?? '0')) return; if (pos.protection.pendingAmend) { counters.amendsCoalesced += 1; return; } if (t.lastAmendMono !== null && mono() - t.lastAmendMono < P.trail.spacingMs) { counters.amendsCoalesced += 1; return; } const f = bookFacts(t.lastBook); if (f && M.gte(desired, f.bestBid)) return; // already crossed: protective handling, never a lowered stop
    const amendId = `am-${pos.positionId}-${++counters.amends}`; t.lastAmendMono = mono(); await dispatcher.commit(ev('PROTECTION_AMEND', { positionId: pos.positionId, orderId: pos.protection.orderId, amendId, requestedTrigger: desired, outcome: 'REQUESTED', confirmedTrigger: null, receiptTs: nowTs, reason: null })); let r; try { r = await adapter.amendProtection({ positionId: pos.positionId, orderId: pos.protection.orderId, nativeOrderId: pos.protection.nativeOrderId, amendId, requestedTrigger: desired }); } catch (err) { r = { outcome: 'UNCERTAIN', confirmedTrigger: null, reason: String(err?.message ?? err).slice(0, 120) }; } await dispatcher.commit(ev('PROTECTION_AMEND', { positionId: pos.positionId, orderId: pos.protection.orderId, amendId, requestedTrigger: desired, outcome: r.outcome === 'ACKNOWLEDGED' ? 'ACKNOWLEDGED' : r.outcome === 'FAILED' ? 'FAILED' : 'UNCERTAIN', confirmedTrigger: r.outcome === 'ACKNOWLEDGED' ? r.confirmedTrigger : null, receiptTs: now(), reason: r.reason ?? null }));
  }
  // ---- the serialized exit coordinator ----------------------------------------------------------------------------------------------
  async function cancelOrder(pos, orderId, nowTs) { const o = state().orders[orderId]; if (!o || TERMINAL_ORDER_STATES.includes(o.state) || o.state === 'CANCEL_PENDING') return o?.state ?? null; const attemptId = `cx-${orderId}-${(o.cancelAttempts ?? []).length + 1}`; await dispatcher.commit(ev('CANCEL_REQUESTED', { orderId, attemptId, ts: nowTs })); let r; try { r = await adapter.cancelOwnedOrder({ orderId, nativeOrderId: o.nativeOrderId, attemptId }); } catch (err) { r = { outcome: 'UNCERTAIN', reason: String(err?.message ?? err).slice(0, 120) }; } await dispatcher.commit(ev('CANCEL_RESULT', { orderId, attemptId, outcome: r.outcome, reason: r.reason ?? null, receiptTs: now() })); return state().orders[orderId]?.state ?? null; }
  async function startExit(pos, t, primary, priority, reasons, nowTs) { if (t.exit.phase !== 'NONE' && t.exit.phase !== 'DONE') return; counters.exitsStarted += 1; t.exit = { phase: 'CANCELLING_REMAINDER', reason: primary, priority, startedMono: mono(), startedTs: nowTs, orderId: null, protective: PROTECTIVE.has(primary) }; if (t.firstFillMono !== null) t.latencies.firstFillToExitMs = mono() - t.firstFillMono; if (primary === 'OWNER_KILL') { counters.killRequested += 1; if (!state().restrictions.KILL) await dispatcher.commit(ev('RESTRICTION', { code: 'KILL', action: 'LATCH', scope: null, source: 'watch:owner-kill', sessionDate: null, reason: 'owner KILL: halt additions, attempt a safe flatten, stay killed', ownerRef: null, ts: nowTs })); } if (primary === 'PROTECTION_INVALID') { counters.protectionMismatch += 1; await dispatcher.commit(ev('RESTRICTION', { code: 'PROTECTION_MISMATCH', action: 'LATCH', scope: pos.positionId, source: 'watch', sessionDate: null, reason: `protection ${pos.protection.state} ${P.protectionConfirmMs}ms after the first fill`, ownerRef: null, ts: nowTs })); } if (primary === 'DETERIORATION') counters.deteriorations += 1; if (primary === 'NO_PROGRESS') counters.noProgress += 1; if (primary === 'MAX_DURATION') counters.durations += 1; if (primary === 'PLANNED_TARGET') counters.targetsHit += 1; await dispatcher.commit(ev('WATCH_STATE', { positionId: pos.positionId, trailActive: pos.trailActive, highestBid: t.highestBid, exitState: 'REQUESTED', primaryReason: primary, priority, supportedReasons: reasons, ts: nowTs })); }
  async function advanceExit(pos, t, nowTs) {
    const s = state(); pos = s.positions[pos.positionId]; const e = t.exit; if (e.phase === 'NONE' || e.phase === 'DONE' || e.phase === 'UNRESOLVED') return;
    if (e.phase === 'CANCELLING_REMAINDER') { const eo = pos.entryOrderId ? s.orders[pos.entryOrderId] : null; if (eo && !TERMINAL_ORDER_STATES.includes(eo.state)) { const st = await cancelOrder(pos, pos.entryOrderId, nowTs); if (st === 'RECONCILIATION_REQUIRED') { e.phase = 'UNRESOLVED'; return; } if (!TERMINAL_ORDER_STATES.includes(st)) return; } e.phase = 'CANCELLING_PROTECTION'; }
    // cancel EVERY live child of the protection set (closeout R04), then confirm each cancellation; a triggered child is awaited
    if (e.phase === 'CANCELLING_PROTECTION') { const prot = pos.protection; const live = Object.values(prot.children ?? {}).filter((c) => ['ACTIVE', 'PENDING', 'AMEND_PENDING'].includes(c.state) && c.orderId && state().orders[c.orderId] && !TERMINAL_ORDER_STATES.includes(state().orders[c.orderId].state));
      for (const c of live) { const st = await cancelOrder(pos, c.orderId, nowTs); if (st === 'RECONCILIATION_REQUIRED') { e.phase = 'UNRESOLVED'; return; } }
      const p2 = state().positions[pos.positionId].protection; const kids = Object.values(p2.children ?? {});
      if (p2.state === 'MISMATCH' || kids.some((c) => c.state === 'MISMATCH')) { e.phase = 'UNRESOLVED'; return; }
      if (p2.state === 'TRIGGERED' || kids.some((c) => c.state === 'TRIGGERED' || c.state === 'CANCEL_PENDING')) { e.phase = 'AWAITING_TERMINAL'; return; }
      if (kids.some((c) => ['ACTIVE', 'PENDING', 'AMEND_PENDING'].includes(c.state)) || p2.state === 'PENDING') return; // not yet confirmed cancelled: try again next tick
      e.phase = 'RECONCILING'; }
    if (e.phase === 'AWAITING_TERMINAL') { const prot = state().positions[pos.positionId].protection; const kids = Object.values(prot.children ?? {}); const open = kids.filter((c) => c.orderId && state().orders[c.orderId] && !TERMINAL_ORDER_STATES.includes(state().orders[c.orderId].state)); if (open.length) return; e.phase = 'RECONCILING'; }
    // confirm the race through the venue BEFORE any sale (closeout R02): a late child fill that arrives now is the truth; the sale (if any) is the confirmed net residual
    if (e.phase === 'RECONCILING') { if (typeof dispatcher.reconcileNow !== 'function') { e.phase = 'SELLING'; } else { let rec; try { rec = await dispatcher.reconcileNow({ scope: 'REQUESTED' }); } catch (err) { rec = { outcome: 'FAILED', reason: String(err?.message ?? err).slice(0, 120) }; } e.reconciliation = { outcome: rec?.outcome ?? 'ABSENT', reason: rec?.reason ?? null, ts: nowTs }; if (rec?.outcome !== 'COMPLETE') { e.phase = 'UNRESOLVED'; await halt(pos, `reconciliation ${rec?.outcome ?? 'ABSENT'} before the residual sale`, nowTs); return; } const after = state().positions[pos.positionId]; const kidsAfter = Object.values(after.protection.children ?? {}); if (kidsAfter.some((c) => c.orderId && state().orders[c.orderId] && !TERMINAL_ORDER_STATES.includes(state().orders[c.orderId].state))) { e.phase = 'AWAITING_TERMINAL'; return; } e.phase = M.isZero(residualOf(after)) ? 'CLOSING' : 'SELLING'; } }
    if (e.phase === 'SELLING') { pos = state().positions[pos.positionId]; const openSells = Object.values(state().orders).filter((o) => o.positionId === pos.positionId && o.side === 'sell' && !TERMINAL_ORDER_STATES.includes(o.state)); if (openSells.length) { if (!e.protective && e.orderId && mono() - e.startedMono > P.plannedExitTimeoutMs) { const st = await cancelOrder(pos, e.orderId, nowTs); if (st === 'RECONCILIATION_REQUIRED') { e.phase = 'UNRESOLVED'; return; } e.protective = true; } return; } const q = residualOf(pos); if (M.isZero(q)) { e.phase = 'CLOSING'; } else { const spec = specOf(pos.pair); if (M.lt(q, spec.orderMin)) { e.phase = 'CLOSING'; } else { if (s.restrictions.RECONCILIATION_REQUIRED && adapter.kind === 'KRAKEN') { e.phase = 'UNRESOLVED'; await halt(pos, 'RECONCILIATION_REQUIRED blocks a safe sell', nowTs); return; } const f = t.lastBook ? bookFacts(t.lastBook) : null; if (!f && adapter.kind === 'PAPER') { e.phase = 'UNRESOLVED'; await halt(pos, 'no accepted book: paper exit coverage unknown', nowTs); return; } const n = Object.keys(s.orders).length + 1; const orderId = `${e.protective ? 'px' : 'tx'}-${pos.positionId}-${n}`; const limit = e.protective ? null : M.roundToStep(M.sub(f.bestBid, bufferOf(pos.atr14, spec.priceIncrement)), spec.priceIncrement, 'FLOOR'); const intent = { intentId: `int-${orderId}`, orderId, clientOrderId: `x${orderId.slice(-17)}`.slice(0, 18), reservationId: null, positionId: pos.positionId, kind: e.protective ? 'PROTECTIVE_EXIT' : 'PLANNED_EXIT', side: 'sell', pair: pos.pair, qty: M.roundToStep(q, spec.qtyIncrement, 'DOWN'), limitPrice: limit, orderType: e.protective ? 'market' : 'limit', timeInForce: 'IOC', protection: null, deadlineTs: nowTs + 5000, feeDigest: feeOf(pos.pair).feeDigest, specDigest: spec.specDigest, snapshotDigest: t.lastBook?.digest ?? null, createdTs: nowTs };
            // an owned protective reduction needs ownership, a held writer and an open sender — never the NEW-exposure authority (closeout R01)
            const ra = reductionAuthority(state(), intent, { writerHeld: dispatcher.writerHeld ? dispatcher.writerHeld() && !dispatcher.writerLost() : true, senderOpen: !dispatcher.status().closed }); if (!ra.ok) { counters.reductionRefusals += 1; log(`exit ${pos.positionId} reduction refused: ${ra.reasons.join(',')}`); if (ra.reasons.includes('WRITER_LOST') || ra.reasons.includes('SENDER_CLOSED')) { e.phase = 'UNRESOLVED'; } return; }
            e.orderId = orderId;
            // the exit snapshot is persisted BEFORE the sale is sent (closeout R11); a planned exit without its evidence is not sent, a protective one still is (safety first, the failure recorded)
            if (snapshotStore && t.lastBook) { const persisted = await snapshotStore.persist(t.lastBook, { purpose: 'EXIT', ref: orderId }); if (!persisted.ok) { counters.snapshotPersistFailures += 1; if (!e.protective) { log(`exit ${pos.positionId}: snapshot not persisted (${persisted.reason}); planned sale withheld`); e.orderId = null; return; } } }
            await dispatcher.commit([ev('ORDER_INTENT', intent), ev('DISPATCH_ATTEMPTED', { orderId, attemptId: `att-${orderId}`, adapter: adapter.kind, ts: nowTs })]); let r; try { r = await adapter.closeResidual({ intent, spec }); } catch (err) { r = { outcome: 'UNCERTAIN', nativeOrderId: null, reason: String(err?.message ?? err).slice(0, 120), guaranteesNoAcceptance: false }; } await dispatcher.commit(ev('DISPATCH_RESULT', { orderId, attemptId: `att-${orderId}`, outcome: r.outcome, nativeOrderId: r.nativeOrderId ?? null, reason: r.reason ?? null, sourceTs: null, receiptTs: now(), guaranteesNoAcceptance: Boolean(r.guaranteesNoAcceptance) })); if (r.outcome === 'UNCERTAIN') { e.phase = 'UNRESOLVED'; await dispatcher.commit(ev('ORDER_STATE', { orderId, state: 'RECONCILIATION_REQUIRED', nativeOrderId: null, nativeCumQty: null, reason: 'exit dispatch uncertain: no extra sell', sourceTs: null, receiptTs: now() })); } return; } } }
    if (e.phase === 'CLOSING') { pos = state().positions[pos.positionId]; const q = residualOf(pos); const openOrders = Object.values(state().orders).filter((o) => o.positionId === pos.positionId && !TERMINAL_ORDER_STATES.includes(o.state)); if (openOrders.length || ['ACTIVE', 'PENDING', 'AMEND_PENDING', 'CANCEL_PENDING', 'MISMATCH'].includes(pos.protection.state)) return; const spec = specOf(pos.pair); if (M.isZero(q)) { await dispatcher.commit([ev('POSITION_CLOSED', { positionId: pos.positionId, reason: e.reason ?? 'exit', residualBase: '0', state: 'FLAT', ts: nowTs }), ev('WATCH_STATE', { positionId: pos.positionId, trailActive: pos.trailActive, highestBid: t.highestBid, exitState: 'DONE', primaryReason: e.reason, priority: e.priority, supportedReasons: [], ts: nowTs }), ev('FEED_PIN', { symbol: pos.pair, action: 'RELEASE', reason: 'flat confirmed', ts: nowTs })]); if (feed) feed.release(pos.pair, { force: true }); e.phase = 'DONE'; onClosed(pos, e); if (e.reason === 'OWNER_KILL' && openPositions().length === 0) killComplete = true; } else if (M.lt(q, spec.orderMin)) { await dispatcher.commit([ev('DUST_STATE', { positionId: pos.positionId, base: q, state: 'DUST_UNRESOLVED', ownerRef: null, ts: nowTs }), ev('WATCH_STATE', { positionId: pos.positionId, trailActive: pos.trailActive, highestBid: t.highestBid, exitState: 'UNRESOLVED', primaryReason: e.reason, priority: e.priority, supportedReasons: [], ts: nowTs })]); e.phase = 'UNRESOLVED'; } else e.phase = 'SELLING'; }
  }
  async function halt(pos, reason, nowTs) { counters.halted += 1; if (haltedLatched) return; haltedLatched = true; const s = state(); if (s.mode !== 'HALTED_UNRESOLVED') { try { await dispatcher.commit(ev('MODE_TRANSITION', { from: s.mode, to: 'HALTED_UNRESOLVED', reason: `position ${pos.positionId}: ${reason}`.slice(0, 200), authorizationId: null, ts: nowTs })); } catch (err) { log(`halt transition refused: ${err.message}`); } } log(`ALERT HALTED_UNRESOLVED ${pos.positionId}: ${reason} — owner exchange intervention may be required; native stops retained`); }
  // ---- heartbeat ----------------------------------------------------------------------------------------------------------------
  let ticking = false;
  async function onTick(nowTs = now()) {
    if (ticking) { counters.overlappedTicks += 1; return; } ticking = true; try { await tickBody(nowTs); } finally { ticking = false; }
  }
  // serialized (closeout R08): a slow venue call inside one tick never lets the next heartbeat start a second exit / second sell
  async function tickBody(nowTs) {
    const m = mono(); if (lastTickMono !== null) { counters.eventLoopDelaySamples.push(Math.max(0, m - lastTickMono - P.heartbeatMs)); if (counters.eventLoopDelaySamples.length > 512) counters.eventLoopDelaySamples.shift(); } lastTickMono = m;
    for (const pos of openPositions()) { const t = track(pos); if (t.firstFillMono === null && pos.firstFillTs) { t.firstFillMono = m; t.latencies.firstFillToWatchMs = Math.max(0, nowTs - pos.firstFillReceiptTs); } if (pos.protection.state === 'ACTIVE' && t.latencies.firstFillToProtectionMs === null && pos.protection.confirmedTs && pos.firstFillReceiptTs) t.latencies.firstFillToProtectionMs = pos.protection.confirmedTs - pos.firstFillReceiptTs;
      try { await finalizeR(pos, t); const cur = state().positions[pos.positionId]; const hb = t.lastBook ? nowTs - t.lastBook.receiptTs : null; const eo = cur.entryOrderId ? state().orders[cur.entryOrderId] : null;
        if (hb !== null && hb > P.health.impairedMs && eo && !TERMINAL_ORDER_STATES.includes(eo.state) && t.remainderCancel === 'NONE') { t.remainderCancel = 'REQUESTED'; await cancelOrder(cur, cur.entryOrderId, nowTs); t.remainderCancel = 'DONE'; }
        if (t.exit.phase === 'NONE' || t.exit.phase === 'DONE') { const r = evaluateReasons(cur, t, nowTs); if (r.primary) { if (r.primary === 'FEED_UNUSABLE' && !(adapter.kind === 'KRAKEN' && !state().restrictions.RECONCILIATION_REQUIRED && cur.initialR.state === 'FINAL')) { await halt(cur, 'public feed unusable > 10s and no safe sell is known: native stops retained', nowTs); continue; } await startExit(cur, t, r.primary, r.priority, r.reasons, nowTs); } else await trail(cur, t, nowTs); }
        if (t.exit.phase !== 'NONE') await advanceExit(cur, t, nowTs);
      } catch (err) { log(`watch ${pos.positionId}: ${err.message}`); if (err.code === 'WRITER_LOST' || err.code === 'EPOCH_FENCED') return; } }
    if (adapter?.onTick) adapter.onTick(nowTs);
  }
  // conservative marks for the durable valuation (closeout R06): every held position's residual against its latest usable book
  // (the same liquidation recipe as admission); any held position without a usable book makes the valuation UNKNOWN
  function marks(nowTs = now()) { const out = []; let unknown = null; for (const pos of openPositions()) { const q = residualOf(pos); const t = track(pos); const h = feed ? feed.health(pos.pair, nowTs) : { usable: Boolean(t.lastBook) && nowTs - t.lastBook.receiptTs <= P.health.bookAgeMs }; if (M.isZero(q)) { out.push({ positionId: pos.positionId, base: '0', liquidationValue: '0', snapshotDigest: t.lastBook?.digest ?? null }); continue; } const nl = t.lastBook && h.usable ? netLiquidation(pos, t.lastBook) : null; if (!nl) { unknown = unknown ?? `position ${pos.positionId}: no usable book for a conservative mark`; out.push({ positionId: pos.positionId, base: q, liquidationValue: null, snapshotDigest: t.lastBook?.digest ?? null }); continue; } out.push({ positionId: pos.positionId, base: q, liquidationValue: nl.cashIn, snapshotDigest: nl.snapshotDigest }); } const liquidation = unknown ? null : M.sum(out.map((m) => m.liquidationValue ?? '0')); return { unknown: unknown !== null, reason: unknown, marks: out, liquidation, digest: out.map((m) => `${m.positionId}:${m.base}:${m.liquidationValue}`).join('|') }; }
  return { onTick, onBook, onTrade, track, marks, evaluateReasons: (pos) => evaluateReasons(pos, track(pos), now()), positions: () => [...T.values()].map((t) => ({ positionId: t.positionId, symbol: t.symbol, exit: { ...t.exit }, highestBid: t.highestBid, maxNetPnl: t.maxNetPnl, lastNetPnl: t.lastNetPnl?.netPnl ?? null, targetPerUnit: t.targetPerUnit, latencies: { ...t.latencies }, restored: t.restored, flow: t.flow.status() })), status: () => ({ watchVersion: WATCH_VERSION, tracked: T.size, killComplete, haltedLatched, counters: { ...counters, eventLoopDelaySamples: undefined, eventLoopDelayMaxMs: counters.eventLoopDelaySamples.length ? Math.max(...counters.eventLoopDelaySamples) : null } }), killComplete: () => killComplete };
}
