// EVIDENCE V2 — serpent-evidence-2 (§9). Keeps EVERY v1 field, truth law, semantic identity and bound, and adds:
//   * a required closed researchContext (mode, entrances, dossierRef, marketContextRef, sourceHistoryRefs,
//     coverageLimitations, authority NONE, purpose RESEARCH_ONLY);
//   * triggers MARKET_RESEARCH and RESEARCH_DOSSIER;
//   * typed evidence value schemas for the market / social context kinds, with MARKET_CONTEXT_SUMMARY binding the
//     immutable context id / recipe / as-of and a canonical componentIds set (<= 64, a NEW v2 summary field, separate
//     from the unchanged v1 limit of 16 refs per item);
//   * an explicit 163,840 UTF-8 byte cap beside the retained 131,072 canonical-character cap.
// v1 stays v1: evidence/contract.js is untouched; this module IMPORTS its helpers and vocabularies and dispatches by
// schemaVersion. Unknown versions reject without mutation. A v2 packet is never coerced through v1.
import { createHash } from 'node:crypto';
import {
  EVIDENCE_SCHEMA_VERSION, TRIGGER_KINDS, CLAIM_STATUSES, SOURCE_TYPES, AUTHORITY_CLASSES, CLAIM_LINK_KINDS, EVIDENCE_SENSES, EVIDENCE_STATES, PROVIDER_COVERAGE_STATES, COIN_RE,
  MAX_CLAIMS, MAX_SOURCES, MAX_EVIDENCE, MAX_CLAIM_LINKS, MAX_CONTRADICTIONS, MAX_MISSING_EVIDENCE, MAX_ANALOGS, MAX_EXCERPT_CHARS, MAX_PACKET_RAW_CHARS, MAX_TEXT_CHARS, MAX_ID_CHARS, MAX_PROVIDER_COVERAGE, MAX_REASONS, MAX_REFS_PER_ITEM, MAX_PACKET_CANONICAL_CHARS,
  canonicalJson, contentHash, normalizeRefSets, jsonShapeError, evidenceValueError, claimIdentity, sourceIdentity, evidenceIdentity, boundedReason, validateEvidencePacket, EVIDENCE_ALLOWED_KEYS, ARRAY_ORDER_POLICY,
} from './contract.js';

export const EVIDENCE_SCHEMA_VERSION_2 = 'serpent-evidence-2';
export const MAX_PACKET_UTF8_BYTES = 163_840;
export const MAX_COMPONENT_IDS = 64;
export const MAX_SOURCE_HISTORY_REFS = 8;
export const TRIGGER_KINDS_V2 = Object.freeze([...TRIGGER_KINDS, 'MARKET_RESEARCH', 'RESEARCH_DOSSIER']);
export const RESEARCH_MODES = Object.freeze(['LIVE_OBSERVATION', 'REPLAY_AS_OF']);
export const RESEARCH_ENTRANCES = Object.freeze(['MARKET_LED', 'PARTICIPATION_LED', 'INFORMATION_LED']);
export const COVERAGE_LIMITATION_REASONS = Object.freeze(['MARKET_CONTEXT_ABSENT', 'SOCIAL_PROJECTION_ABSENT', 'SOCIAL_COVERAGE_UNAVAILABLE', 'FAMILY_NOT_QUERIED', 'FAMILY_MISSING', 'FAMILY_NOT_SUPPORTED', 'FAMILY_PARTIAL', 'DETAIL_OMITTED_BY_BOUNDS', 'REPLAY_NETWORK_OFF', 'PROVIDER_ACCESS_BLOCKED', 'RESOURCE_EVICTION', 'SOURCE_HISTORY_PARTIAL', 'SOURCE_HISTORY_UNKNOWN', 'RETENTION_RESTRICTED', 'BOOK_ENDPOINTS_INCOMPLETE', 'PEER_COHORT_INSUFFICIENT', 'OPTIONS_CENSUS_PARTIAL']);
export const MARKET_EVIDENCE_KINDS = Object.freeze(['MARKET_CONTEXT_SUMMARY', 'MARKET_CHART_WINDOW', 'MARKET_BOOK_CONTEXT', 'MARKET_MICRO_CONTEXT', 'MARKET_PRESSURE_RESPONSE_CHANGE', 'MARKET_PEER_RELATIVE_MOVE', 'MARKET_DISPLAYED_EXIT_LIQUIDITY_CHANGE', 'MARKET_DERIVATIVES_CONTEXT', 'MARKET_LIQUIDATIONS_CONTEXT', 'MARKET_OPTIONS_CONTEXT', 'MARKET_MULTI_VENUE_CONTEXT', 'MARKET_SUPPLY_UNLOCKS', 'MARKET_DEX_DEFI_CONTEXT', 'MARKET_ONCHAIN_CONTEXT', 'MARKET_NETWORK_CONTEXT', 'MARKET_STABLECOIN_CONTEXT', 'MARKET_ETF_CONTEXT', 'MARKET_MACRO_CONTEXT', 'MARKET_CROSS_ASSET_CONTEXT', 'MARKET_EVENT_CONTEXT', 'MARKET_INFRA_CONTEXT']);
export const SOCIAL_EVIDENCE_KINDS = Object.freeze(['SOCIAL_DOSSIER_CONTEXT', 'SOCIAL_SOURCE_HISTORY']);
export const TYPED_EVIDENCE_KINDS = Object.freeze([...MARKET_EVIDENCE_KINDS, ...SOCIAL_EVIDENCE_KINDS]);
export const KIND_FAMILY = Object.freeze({ MARKET_CHART_WINDOW: 'SPOT_PRICE_CHART', MARKET_BOOK_CONTEXT: 'DISPLAYED_LIQUIDITY', MARKET_MICRO_CONTEXT: 'DISPLAYED_LIQUIDITY', MARKET_PRESSURE_RESPONSE_CHANGE: 'SPOT_FLOW', MARKET_PEER_RELATIVE_MOVE: 'CROSS_VENUE', MARKET_DISPLAYED_EXIT_LIQUIDITY_CHANGE: 'DISPLAYED_LIQUIDITY', MARKET_DERIVATIVES_CONTEXT: 'DERIVATIVES_FUNDING_OI', MARKET_LIQUIDATIONS_CONTEXT: 'LIQUIDATIONS', MARKET_OPTIONS_CONTEXT: 'OPTIONS_TERM_SKEW', MARKET_MULTI_VENUE_CONTEXT: 'CROSS_VENUE', MARKET_SUPPLY_UNLOCKS: 'SUPPLY_UNLOCKS', MARKET_DEX_DEFI_CONTEXT: 'DEX_DEFI', MARKET_ONCHAIN_CONTEXT: 'ONCHAIN_ENTITY_FLOW', MARKET_NETWORK_CONTEXT: 'NETWORK_ACTIVITY', MARKET_STABLECOIN_CONTEXT: 'STABLECOIN_LIQUIDITY', MARKET_ETF_CONTEXT: 'ETF_FLOWS', MARKET_MACRO_CONTEXT: 'MACRO_RELEASES', MARKET_CROSS_ASSET_CONTEXT: 'CROSS_ASSET', MARKET_EVENT_CONTEXT: 'OFFICIAL_SOCIAL_EVENTS', MARKET_INFRA_CONTEXT: 'INFRASTRUCTURE_STATUS' });
export const RESEARCH_CONTEXT_KEYS = Object.freeze(['mode', 'entrances', 'dossierRef', 'marketContextRef', 'sourceHistoryRefs', 'coverageLimitations', 'authority', 'purpose']);
export const EVIDENCE_ALLOWED_KEYS_V2 = Object.freeze({ ...EVIDENCE_ALLOWED_KEYS, packet: Object.freeze([...EVIDENCE_ALLOWED_KEYS.packet, 'researchContext']), researchContext: RESEARCH_CONTEXT_KEYS });
const KEY_SETS = Object.fromEntries(Object.entries(EVIDENCE_ALLOWED_KEYS_V2).map(([k, v]) => [k, new Set(v)]));
export const ARRAY_ORDER_POLICY_V2 = Object.freeze({ ...ARRAY_ORDER_POLICY });

// ---- typed evidence value: one closed envelope + kind-specific closed fields --------------------------------------------
export const TYPED_VALUE_KEYS = Object.freeze(['kind', 'canonicalCoin', 'asOfTs', 'windowStartTs', 'windowEndTs', 'observedTs', 'knownAtTs', 'recipe', 'support', 'units', 'sourceIds', 'fields']);
export const RECIPE_KEYS = Object.freeze(['recipeId', 'version', 'recipeSetVersion']);
export const SUPPORT_KEYS = Object.freeze(['state', 'reasons', 'completeness']);
const T = { num: (v) => typeof v === 'number' && Number.isFinite(v), numOrNull: (v) => v === null || (typeof v === 'number' && Number.isFinite(v)), int: (v) => Number.isSafeInteger(v), intOrNull: (v) => v === null || Number.isSafeInteger(v), ts: (v) => Number.isSafeInteger(v) && v > 0, tsOrNull: (v) => v === null || (Number.isSafeInteger(v) && v > 0), str: (v) => typeof v === 'string' && v.length > 0 && v.length <= MAX_ID_CHARS, strOrNull: (v) => v === null || (typeof v === 'string' && v.length > 0 && v.length <= MAX_ID_CHARS), text: (v) => typeof v === 'string' && v.length > 0 && v.length <= MAX_TEXT_CHARS, textOrNull: (v) => v === null || (typeof v === 'string' && v.length > 0 && v.length <= MAX_TEXT_CHARS), bool: (v) => typeof v === 'boolean', boolOrNull: (v) => v === null || typeof v === 'boolean', obj: (v) => v !== null && typeof v === 'object' && !Array.isArray(v), arr: (v) => Array.isArray(v), idSet: (v) => Array.isArray(v) && v.length <= 32 && v.every((x) => typeof x === 'string' && x.length <= MAX_ID_CHARS) && new Set(v).size === v.length };
const en = (list) => (v) => list.includes(v);
// kind -> { field: checker } (closed: no other field may appear; every field must appear)
export const FIELD_SCHEMAS = Object.freeze({
  MARKET_CONTEXT_SUMMARY: { contextId: T.str, recipeSetVersion: T.str, captureBundleId: T.strOrNull, familyStates: T.obj, componentIds: (v) => Array.isArray(v) && v.length <= MAX_COMPONENT_IDS && v.every((x) => /^evd-[0-9a-f]{40}$/.test(String(x))) && new Set(v).size === v.length && [...v].sort().join() === v.join(), omittedDetail: T.obj, resourceState: (v) => v === null || T.obj(v) },
  MARKET_CHART_WINDOW: { venue: T.str, quote: T.str, windowMs: T.int, open: T.numOrNull, high: T.numOrNull, low: T.numOrNull, close: T.numOrNull, vwap: T.numOrNull, logReturn: T.numOrNull, quoteNotional: T.numOrNull, count: T.intOrNull, relativeNotional: T.numOrNull, relativeRange: T.numOrNull, indicators: (v) => v === null || T.obj(v), previous: (v) => v === null || T.obj(v) },
  MARKET_BOOK_CONTEXT: { venue: T.str, quote: T.str, mid: T.numOrNull, spreadBps: T.numOrNull, microprice: T.numOrNull, bands: T.obj, bookAgeMs: T.intOrNull, synchronized: T.boolOrNull, checksumVerified: T.boolOrNull, attribution: T.str },
  MARKET_MICRO_CONTEXT: { venue: T.str, absorption: (v) => v === null || T.obj(v), depletion: (v) => v === null || T.obj(v), recovery: (v) => v === null || T.obj(v), flowResponse: (v) => v === null || T.obj(v), attribution: T.str, proxyLabels: T.arr },
  MARKET_PRESSURE_RESPONSE_CHANGE: { venue: T.str, quote: T.str, previousSigned: T.numOrNull, currentSigned: T.numOrNull, previousResponseBps: T.numOrNull, currentResponseBps: T.numOrNull, previousEfficiency: T.numOrNull, currentEfficiency: T.numOrNull, efficiencyChange: T.numOrNull, pressureChange: T.numOrNull, spreadStartBps: T.numOrNull, spreadEndBps: T.numOrNull, replenishment: (v) => v === null || T.obj(v), knownSideFraction: T.numOrNull, alternatives: T.arr },
  MARKET_PEER_RELATIVE_MOVE: { cohortLabel: T.str, targetReturnBps: T.numOrNull, medianPeerReturnBps: T.numOrNull, residualBps: T.numOrNull, madBps: T.numOrNull, n: T.int, positivePeers: T.intOrNull, excluded: T.arr, firstObservedChanges: T.arr },
  MARKET_DISPLAYED_EXIT_LIQUIDITY_CHANGE: { venue: T.str, quoteNotional: T.num, currentLossBps: T.numOrNull, previousLossBps: T.numOrNull, lossChangeBps: T.numOrNull, currentCoverage: T.str, previousCoverage: T.strOrNull, worstBuyPrice: T.numOrNull, worstSellPrice: T.numOrNull, residualBuyQuote: T.numOrNull, residualSellBase: T.numOrNull, haircuts: T.arr, preFee: T.bool },
  MARKET_DERIVATIVES_CONTEXT: { instrument: T.str, venue: T.str, marketType: T.str, basisBps: T.numOrNull, markPrice: T.numOrNull, indexPrice: T.numOrNull, openInterest: T.numOrNull, openInterestUnit: T.str, oiChangeAbsolute: T.numOrNull, oiChangePercent: T.numOrNull, fundingNative: T.numOrNull, fundingUnit: T.str, fundingIntervalMs: T.intOrNull, fundingRelative: T.numOrNull, ageMs: T.intOrNull },
  MARKET_LIQUIDATIONS_CONTEXT: { windowMs: T.int, events: T.int, longNotional: T.numOrNull, shortNotional: T.numOrNull, unknownSideNotional: T.numOrNull, unit: T.strOrNull, venues: T.arr, zeroMeaningful: T.bool },
  MARKET_OPTIONS_CONTEXT: { scope: T.strOrNull, admitted: T.int, omitted: T.int, censusComplete: T.bool, term: T.arr },
  MARKET_MULTI_VENUE_CONTEXT: { quote: T.strOrNull, medianMid: T.numOrNull, dispersionBps: T.numOrNull, n: T.int, venues: T.arr, firstObservedChanges: T.arr },
  MARKET_SUPPLY_UNLOCKS: { circulatingOverTotal: T.numOrNull, circulatingOverMax: T.numOrNull, fdvOverMarketCap: T.numOrNull, volumeOverMarketCap: T.numOrNull, maxSupplyKnown: T.boolOrNull, marketCapUsd: T.numOrNull, upcoming: T.arr, untrackedAllocations: T.intOrNull, referenceProvider: T.strOrNull },
  MARKET_DEX_DEFI_CONTEXT: { pools: T.arr, protocols: T.arr },
  MARKET_ONCHAIN_CONTEXT: { provider: T.str, entitySet: T.strOrNull, chain: T.strOrNull, window: T.strOrNull, inflow: T.numOrNull, outflow: T.numOrNull, net: T.numOrNull, reserve: T.numOrNull, unit: T.strOrNull, labelVintage: T.strOrNull, periodStartTs: T.tsOrNull, periodEndTs: T.tsOrNull },
  MARKET_NETWORK_CONTEXT: { provider: T.str, metrics: T.arr },
  MARKET_STABLECOIN_CONTEXT: { stablecoinId: T.str, chain: T.strOrNull, current: T.numOrNull, change: T.numOrNull, unit: T.strOrNull, pegPrice: T.numOrNull, pegDeviationBps: T.numOrNull, fromTs: T.tsOrNull, toTs: T.tsOrNull },
  MARKET_ETF_CONTEXT: { asset: T.str, latestFlowUsd: T.numOrNull, latestPeriodStartTs: T.tsOrNull, latestPeriodEndTs: T.tsOrNull, trailing5: T.numOrNull, trailing20: T.numOrNull, estimate: T.boolOrNull, days: T.int },
  MARKET_MACRO_CONTEXT: { levels: T.arr, upcoming: T.arr, released: T.arr },
  MARKET_CROSS_ASSET_CONTEXT: { instruments: T.arr },
  MARKET_EVENT_CONTEXT: { events: T.arr },
  MARKET_INFRA_CONTEXT: { statuses: T.arr, incidents: T.arr },
  SOCIAL_DOSSIER_CONTEXT: { dossierId: T.str, derivedKnownAtTs: T.ts, researchState: T.str, entrances: T.arr, packetStatus: T.strOrNull, packetId: T.strOrNull, episodeId: T.strOrNull, episodeIndex: T.intOrNull, compositeId: T.strOrNull, coverage: T.obj },
  SOCIAL_SOURCE_HISTORY: { socialAuthorId: T.str, provider: T.str, profileId: T.strOrNull, history: en(['UNKNOWN', 'AVAILABLE']), resourceHistoryState: T.strOrNull, firstObservedKnownAtTs: T.tsOrNull, observationCount: T.intOrNull, observationCountIncludingDropped: T.intOrNull, currentProfileFirstObservedKnownAtTs: T.tsOrNull, currentProfileObservationCountIncludingDropped: T.intOrNull, distinctResearchEpisodeCount: T.intOrNull, retentionState: T.strOrNull, factualIndependenceStatus: T.strOrNull, associatedClaimCount: T.intOrNull, associationAvailable: T.bool, coverageLimitations: T.arr, supportingPrefixKnownAtTs: T.tsOrNull },
});
const isPlainObject = (v) => v !== null && typeof v === 'object' && !Array.isArray(v);
const isTs = (v) => Number.isSafeInteger(v) && v > 0;
export function typedValueError(kind, v, { asOfTs, itemObservedTs, itemKnownAtTs, canonicalCoin } = {}, where = 'value') {
  if (!isPlainObject(v)) return `${where}: typed value must be an object`;
  const keys = Object.keys(v); for (let i = 0; i < keys.length; i += 1) if (!TYPED_VALUE_KEYS.includes(keys[i])) return `${where}: undeclared key at position ${i + 1} of ${keys.length}`; for (const k of TYPED_VALUE_KEYS) if (!(k in v)) return `${where}: missing key '${k}'`;
  if (v.kind !== kind) return `${where}: kind disagrees with the evidence kind`;
  if (!(v.canonicalCoin === null || COIN_RE.test(String(v.canonicalCoin)))) return `${where}: canonicalCoin malformed`;
  if (canonicalCoin !== undefined && v.canonicalCoin !== null && v.canonicalCoin !== canonicalCoin) return `${where}: canonicalCoin disagrees with the packet subject`;
  if (!isTs(v.asOfTs) || (isTs(asOfTs) && v.asOfTs > asOfTs)) return `${where}: asOfTs malformed or after the packet as-of`;
  if (!(v.windowStartTs === null || isTs(v.windowStartTs)) || !(v.windowEndTs === null || isTs(v.windowEndTs)) || (v.windowStartTs !== null && v.windowEndTs !== null && v.windowStartTs > v.windowEndTs)) return `${where}: window malformed`;
  if (v.windowEndTs !== null && v.windowEndTs > v.asOfTs) return `${where}: window ends after the as-of`;
  if (!(v.observedTs === null || isTs(v.observedTs)) || !isTs(v.knownAtTs) || v.knownAtTs > v.asOfTs) return `${where}: clocks malformed`;
  if (itemObservedTs !== undefined && v.observedTs !== itemObservedTs) return `${where}: observedTs disagrees with the evidence item`;
  if (itemKnownAtTs !== undefined && v.knownAtTs !== itemKnownAtTs) return `${where}: knownAtTs disagrees with the evidence item`;
  if (v.recipe !== null) { if (!isPlainObject(v.recipe) || Object.keys(v.recipe).length !== RECIPE_KEYS.length || RECIPE_KEYS.some((k) => !(k in v.recipe))) return `${where}: recipe malformed`; if (!T.str(v.recipe.recipeId) || !T.int(v.recipe.version) || !T.str(v.recipe.recipeSetVersion)) return `${where}: recipe fields malformed`; }
  if (!isPlainObject(v.support) || Object.keys(v.support).length !== SUPPORT_KEYS.length || SUPPORT_KEYS.some((k) => !(k in v.support)) || !/^[A-Z][A-Z0-9_]{0,47}$/.test(String(v.support.state)) || !Array.isArray(v.support.reasons) || v.support.reasons.length > 8 || v.support.reasons.some((r) => !/^[A-Z][A-Z0-9_:-]{0,63}$/.test(String(r))) || !(v.support.completeness === null || (T.num(v.support.completeness) && v.support.completeness >= 0 && v.support.completeness <= 1))) return `${where}: support malformed`;
  if (!isPlainObject(v.units) || Object.keys(v.units).length > 16 || Object.entries(v.units).some(([k, u]) => !/^[a-zA-Z0-9_]{1,40}$/.test(k) || !T.str(u))) return `${where}: units malformed`;
  if (!T.idSet(v.sourceIds)) return `${where}: sourceIds malformed`;
  const schema = FIELD_SCHEMAS[kind]; if (!schema) return `${where}: no field schema for kind`;
  if (!isPlainObject(v.fields)) return `${where}: fields must be an object`;
  const fk = Object.keys(v.fields); for (let i = 0; i < fk.length; i += 1) if (!(fk[i] in schema)) return `${where}.fields: undeclared key at position ${i + 1} of ${fk.length}`;
  for (const [k, check] of Object.entries(schema)) { if (!(k in v.fields)) return `${where}.fields: missing key '${k}'`; if (!check(v.fields[k])) return `${where}.fields: '${k}' malformed`; }
  return null;
}

// ---- identity (v2 prefix; member identities reuse the v1 helpers) ---------------------------------------------------------
const sha1 = (s) => createHash('sha1').update(s).digest('hex');
const sortSet = (arr) => [...arr].map((e) => canonicalJson(e)).sort();
export function packetIdentityBasisV2(packet) { const basis = {}; for (const k of Object.keys(packet)) { if (k === 'packetId') continue; const v = normalizeRefSets(packet[k]); basis[k] = ARRAY_ORDER_POLICY_V2[k] === 'UNORDERED' && Array.isArray(v) ? sortSet(v) : v; } return basis; }
export const packetIdentityV2 = (packet) => `sep2-${sha1(canonicalJson(packetIdentityBasisV2(packet)))}`;
export const PACKET_ID_RE_V2 = /^sep2-[0-9a-f]{40}$/;
export const utf8Bytes = (s) => Buffer.byteLength(s, 'utf8');

// ---- validator: v1 law re-stated for v2 + the v2 additions ---------------------------------------------------------------
export function validateEvidencePacketV2(packet) { try { return inner(packet); } catch (err) { return { valid: false, reasons: [boundedReason(`packet: rejected hostile input (${err?.name ?? 'error'})`)] }; } }
export function validateEvidencePacketAny(packet) {
  if (!isPlainObject(packet)) return { valid: false, reasons: ['packet: not an object'], version: null };
  if (packet.schemaVersion === EVIDENCE_SCHEMA_VERSION) return { ...validateEvidencePacket(packet), version: 1 };
  if (packet.schemaVersion === EVIDENCE_SCHEMA_VERSION_2) return { ...validateEvidencePacketV2(packet), version: 2 };
  return { valid: false, reasons: [boundedReason(`packet: unsupported schemaVersion ${JSON.stringify(packet.schemaVersion).slice(0, 40)}`)], version: null };
}
function inner(packet) {
  const reasons = []; const fail = (m) => { if (reasons.length < MAX_REASONS) reasons.push(boundedReason(m)); }; const done = () => ({ valid: reasons.length === 0, reasons });
  if (!isPlainObject(packet)) { fail('packet: not an object'); return done(); }
  if (packet.schemaVersion !== EVIDENCE_SCHEMA_VERSION_2) { fail(`packet: unsupported schemaVersion ${JSON.stringify(packet.schemaVersion).slice(0, 40)}`); return done(); }
  const shapeErr = jsonShapeError(packet, 'packet'); if (shapeErr !== null) { fail(shapeErr); return done(); }
  const canon = canonicalJson(packet); if (canon.length > MAX_PACKET_CANONICAL_CHARS) { fail(`packet: canonical form ${canon.length} chars exceeds ${MAX_PACKET_CANONICAL_CHARS}`); return done(); }
  const bytes = utf8Bytes(canon); if (bytes > MAX_PACKET_UTF8_BYTES) { fail(`packet: canonical form ${bytes} bytes exceeds ${MAX_PACKET_UTF8_BYTES}`); return done(); }
  const checkKeys = (obj, layer, tag) => { for (const k of Object.keys(obj)) if (!KEY_SETS[layer].has(k)) fail(`${tag}: undeclared field '${k}' — the contract is closed`); for (const k of EVIDENCE_ALLOWED_KEYS_V2[layer]) if (layer === 'packet' && !(k in obj)) fail(`${tag}: missing field '${k}'`); };
  checkKeys(packet, 'packet', 'packet');
  if (!isTs(packet.asOfTs)) fail('packet: asOfTs must be a positive epoch-ms integer'); const asOf = packet.asOfTs;
  const inTime = (ts, label) => { if (!isTs(ts)) return fail(`${label}: must be a positive epoch-ms integer`); if (isTs(asOf) && ts > asOf) fail(`${label}: ${ts} is after packet asOfTs ${asOf} — future knowledge rejected`); };
  const isBoundedString = (v, max) => typeof v === 'string' && v.length > 0 && v.length <= max;
  let canonicalCoin = null;
  if (!isPlainObject(packet.subject)) fail('subject: missing'); else { checkKeys(packet.subject, 'subject', 'subject'); if (typeof packet.subject.canonicalCoin !== 'string' || !COIN_RE.test(packet.subject.canonicalCoin)) fail('subject: invalid canonicalCoin'); else canonicalCoin = packet.subject.canonicalCoin; if (packet.subject.providerSymbols !== undefined && packet.subject.providerSymbols !== null) { if (!isPlainObject(packet.subject.providerSymbols)) fail('subject: providerSymbols must be an object'); else for (const [p, s] of Object.entries(packet.subject.providerSymbols)) if (!isBoundedString(p, MAX_ID_CHARS) || !isBoundedString(s, MAX_ID_CHARS)) fail('subject: invalid provider mapping'); } }
  if (!isPlainObject(packet.trigger)) fail('trigger: missing'); else { checkKeys(packet.trigger, 'trigger', 'trigger'); if (!TRIGGER_KINDS_V2.includes(packet.trigger.kind)) fail(`trigger: unknown kind ${JSON.stringify(packet.trigger.kind).slice(0, 40)}`); if (packet.trigger.sourceEventId !== null && !isBoundedString(packet.trigger.sourceEventId, MAX_ID_CHARS)) fail('trigger: sourceEventId must be null or a bounded string'); if (packet.trigger.observedTs !== null) inTime(packet.trigger.observedTs, 'trigger.observedTs'); }
  for (const [key, max] of [['claims', MAX_CLAIMS], ['sources', MAX_SOURCES], ['evidence', MAX_EVIDENCE], ['claimLinks', MAX_CLAIM_LINKS], ['providerCoverage', MAX_PROVIDER_COVERAGE], ['contradictions', MAX_CONTRADICTIONS], ['missingEvidence', MAX_MISSING_EVIDENCE], ['analogs', MAX_ANALOGS]]) { if (!Array.isArray(packet[key])) fail(`${key}: must be an array`); else if (packet[key].length > max) fail(`${key}: ${packet[key].length} exceeds bound ${max}`); }
  const arr = (k) => (Array.isArray(packet[k]) ? packet[k] : []);
  const refSetCheck = (refs, label) => { if (!Array.isArray(refs)) return fail(`${label}: must be an array`); if (refs.length > MAX_REFS_PER_ITEM) fail(`${label}: ${refs.length} refs exceeds bound ${MAX_REFS_PER_ITEM}`); if (new Set(refs).size !== refs.length) fail(`${label}: duplicate refs in an unordered set`); };
  const dupSetCheck = (key) => { const seen = new Set(); for (const m of arr(key)) { if (!isPlainObject(m)) continue; const c = canonicalJson(normalizeRefSets(m)); if (seen.has(c)) fail(`${key}: duplicate set member — multiplicity is not meaning`); else seen.add(c); } };
  const claimIds = new Set();
  for (const c of arr('claims')) { if (!isPlainObject(c)) { fail('claim: not an object'); continue; } const tag = `claim ${String(c.claimId).slice(0, 24)}`; checkKeys(c, 'claim', tag); if (typeof c.claimId !== 'string' || !/^clm-[0-9a-f]{40}$/.test(c.claimId)) fail(`${tag}: invalid claimId`); else if (claimIdentity(c) !== c.claimId) fail(`${tag}: claimId is not the semantic hash of this claim — forged identity`); else if (claimIds.has(c.claimId)) fail(`${tag}: duplicate claimId`); else claimIds.add(c.claimId); if (!isBoundedString(c.claimType, MAX_ID_CHARS)) fail(`${tag}: claimType required`); if (!isBoundedString(c.normalizedSubject, MAX_ID_CHARS)) fail(`${tag}: normalizedSubject required`); if (!isBoundedString(c.claimText, MAX_TEXT_CHARS)) fail(`${tag}: claimText must be a bounded non-empty string`); inTime(c.firstObservedTs, `${tag}: firstObservedTs`); if (!CLAIM_STATUSES.includes(c.status)) fail(`${tag}: unknown status`); }
  const sourceIds = new Set(); let rawChars = 0; const sourceById = new Map();
  for (const s of arr('sources')) { if (!isPlainObject(s)) { fail('source: not an object'); continue; } const tag = `source ${String(s.sourceId).slice(0, 24)}`; checkKeys(s, 'source', tag); if (typeof s.sourceId !== 'string' || !/^src-[0-9a-f]{40}$/.test(s.sourceId)) fail(`${tag}: invalid sourceId`); else if (sourceIdentity(s) !== s.sourceId) fail(`${tag}: sourceId is not the semantic hash of this source — forged identity`); else if (sourceIds.has(s.sourceId)) fail(`${tag}: duplicate sourceId`); else { sourceIds.add(s.sourceId); sourceById.set(s.sourceId, s); } if (!isBoundedString(s.provider, MAX_ID_CHARS)) fail(`${tag}: provider required`); if (!SOURCE_TYPES.includes(s.sourceType)) fail(`${tag}: unknown sourceType`); if (!AUTHORITY_CLASSES.includes(s.authorityClass)) fail(`${tag}: unknown authorityClass`); if (s.publishedTs !== null) inTime(s.publishedTs, `${tag}: publishedTs`); inTime(s.retrievedTs, `${tag}: retrievedTs`); if (isTs(s.publishedTs) && isTs(s.retrievedTs) && s.publishedTs > s.retrievedTs) fail(`${tag}: publishedTs after retrievedTs — causally impossible`); if (s.locator !== null && !isBoundedString(s.locator, MAX_ID_CHARS)) fail(`${tag}: locator must be null or bounded string`); if (s.excerpt === undefined) fail(`${tag}: excerpt must be explicitly null when absent`); else if (s.excerpt !== null) { const e = s.excerpt; if (!isPlainObject(e)) fail(`${tag}: excerpt must be null or an object`); else { checkKeys(e, 'excerpt', `${tag}: excerpt`); if (typeof e.text !== 'string' || e.text.length === 0) fail(`${tag}: excerpt.text must be a non-empty string`); else if (e.text.length > MAX_EXCERPT_CHARS) fail(`${tag}: excerpt ${e.text.length} chars exceeds ${MAX_EXCERPT_CHARS}`); else rawChars += e.text.length; if (e.untrusted !== true) fail(`${tag}: excerpt.untrusted must be literally true`); if (typeof e.text === 'string' && e.contentHash !== contentHash(e.text)) fail(`${tag}: excerpt.contentHash mismatch`); } } }
  if (rawChars > MAX_PACKET_RAW_CHARS) fail(`sources: total raw excerpt ${rawChars} chars exceeds ${MAX_PACKET_RAW_CHARS}`);
  const evidenceIds = new Set(); const evidenceById = new Map();
  for (const ev of arr('evidence')) { if (!isPlainObject(ev)) { fail('evidence: not an object'); continue; } const tag = `evidence ${String(ev.evidenceId).slice(0, 24)}`; checkKeys(ev, 'evidence', tag); if (typeof ev.evidenceId !== 'string' || !/^evd-[0-9a-f]{40}$/.test(ev.evidenceId)) fail(`${tag}: invalid evidenceId`); else if (evidenceIdentity(ev) !== ev.evidenceId) fail(`${tag}: evidenceId is not the semantic hash of this evidence — forged identity`); else if (evidenceIds.has(ev.evidenceId)) fail(`${tag}: duplicate evidenceId`); else { evidenceIds.add(ev.evidenceId); evidenceById.set(ev.evidenceId, ev); } if (!EVIDENCE_SENSES.includes(ev.sense)) fail(`${tag}: unknown sense`); if (!isBoundedString(ev.kind, MAX_ID_CHARS)) fail(`${tag}: kind required`); if (!EVIDENCE_STATES.includes(ev.state)) fail(`${tag}: unknown state`); inTime(ev.knownAtTs, `${tag}: knownAtTs`); if (ev.observedTs !== null) inTime(ev.observedTs, `${tag}: observedTs`); if (isTs(ev.observedTs) && isTs(ev.knownAtTs) && ev.observedTs > ev.knownAtTs) fail(`${tag}: observedTs after knownAtTs — causally impossible`); if (ev.state === 'MISSING' || ev.state === 'UNAVAILABLE') { if (ev.value !== null) fail(`${tag}: state ${ev.state} requires value null — never a coerced number`); } else if (ev.value === undefined) fail(`${tag}: value must be present`); else if (ev.value !== null) { const ve = evidenceValueError(ev.value); if (ve !== null) fail(`${tag}: value ${ve}`); else if (TYPED_EVIDENCE_KINDS.includes(ev.kind)) { const te = typedValueError(ev.kind, ev.value, { asOfTs: asOf, itemObservedTs: ev.observedTs, itemKnownAtTs: ev.knownAtTs, canonicalCoin: canonicalCoin ?? undefined }, `${tag}: value`); if (te) fail(te); } }
    if (TYPED_EVIDENCE_KINDS.includes(ev.kind) && ev.value === null && ev.state !== 'MISSING' && ev.state !== 'UNAVAILABLE') fail(`${tag}: a typed kind needs its typed value unless MISSING/UNAVAILABLE`);
    if (MARKET_EVIDENCE_KINDS.includes(ev.kind) && ev.sense !== 'MARKET') fail(`${tag}: market context kinds carry sense MARKET`);
    if (ev.state === 'STALE' && ev.observedTs === null) fail(`${tag}: STALE evidence must say when it was actually observed`); if (!isBoundedString(ev.provenance, MAX_ID_CHARS)) fail(`${tag}: provenance identity required`); refSetCheck(ev.sourceRefs, `${tag}: sourceRefs`); refSetCheck(ev.claimRefs, `${tag}: claimRefs`); for (const r of Array.isArray(ev.sourceRefs) ? ev.sourceRefs : []) if (!sourceIds.has(r)) fail(`${tag}: dangling sourceRef`); for (const r of Array.isArray(ev.claimRefs) ? ev.claimRefs : []) if (!claimIds.has(r)) fail(`${tag}: dangling claimRef`); }
  // v2: summary/component reference graph — each componentId resolves to a MARKET_* item of the same coin/as-of, is not a summary, and no component names the summary
  const summaries = [...evidenceById.values()].filter((e) => e.kind === 'MARKET_CONTEXT_SUMMARY');
  if (summaries.length > 1) fail('evidence: at most one MARKET_CONTEXT_SUMMARY');
  for (const s of summaries) { const ids = s.value?.fields?.componentIds ?? []; for (const id of ids) { const c = evidenceById.get(id); if (!c) fail(`summary: componentId does not resolve`); else { if (!MARKET_EVIDENCE_KINDS.includes(c.kind) || c.kind === 'MARKET_CONTEXT_SUMMARY') fail('summary: componentId must name a market component'); if (c.value && (c.value.canonicalCoin !== s.value.canonicalCoin || c.value.asOfTs !== s.value.asOfTs)) fail('summary: component subject/as-of disagrees with the summary'); if (c.value && Array.isArray(c.value.sourceIds) && c.value.sourceIds.includes(s.evidenceId)) fail('summary: a component references the summary back (cycle)'); if (typeof c.provenance === 'string' && c.provenance.includes(s.evidenceId)) fail('summary: component provenance references the summary (cycle)'); } } }
  dupSetCheck('claimLinks');
  const supportGroups = new Map(); const supportSources = new Map(); const pairs = new Set(); const primary = new Map(); const kinds = new Map();
  for (const l of arr('claimLinks')) { if (!isPlainObject(l)) { fail('claimLink: not an object'); continue; } const tag = `claimLink ${String(l.claimRef).slice(0, 24)}/${String(l.sourceRef).slice(0, 24)}`; checkKeys(l, 'claimLink', tag); if (!claimIds.has(l.claimRef)) fail(`${tag}: relation names a nonexistent claim`); if (!sourceIds.has(l.sourceRef)) fail(`${tag}: relation names a nonexistent source`); if (!CLAIM_LINK_KINDS.includes(l.kind)) fail(`${tag}: unknown kind`); if (l.independenceGroup !== null && !isBoundedString(l.independenceGroup, MAX_ID_CHARS)) fail(`${tag}: independenceGroup must be null or a bounded string`); if (l.observedTs !== null) inTime(l.observedTs, `${tag}: observedTs`); if (claimIds.has(l.claimRef) && sourceIds.has(l.sourceRef)) { if (!kinds.has(l.claimRef)) kinds.set(l.claimRef, new Set()); kinds.get(l.claimRef).add(l.kind); if (l.kind === 'ORIGIN' || l.kind === 'INDEPENDENT_SUPPORT') { const p = `${l.claimRef}|${l.sourceRef}`; if (pairs.has(p)) fail(`${tag}: at most one non-ECHO support relation per claim+source — one source is one source`); else pairs.add(p); if (typeof l.independenceGroup === 'string') { if (!supportGroups.has(l.claimRef)) supportGroups.set(l.claimRef, new Set()); supportGroups.get(l.claimRef).add(l.independenceGroup); if (!supportSources.has(l.claimRef)) supportSources.set(l.claimRef, new Set()); supportSources.get(l.claimRef).add(l.sourceRef); } } if (l.kind === 'PRIMARY_CONFIRMATION') { const src = sourceById.get(l.sourceRef); if (src && src.authorityClass === 'OFFICIAL') primary.set(l.claimRef, true); } } }
  for (const c of arr('claims')) { if (!isPlainObject(c) || !claimIds.has(c.claimId)) continue; const tag = `claim ${String(c.claimId).slice(0, 24)}`; const k = kinds.get(c.claimId) ?? new Set(); if (c.status === 'CORROBORATED' && ((supportSources.get(c.claimId)?.size ?? 0) < 2 || (supportGroups.get(c.claimId)?.size ?? 0) < 2)) fail(`${tag}: CORROBORATED requires non-ECHO support from >=2 distinct sources AND >=2 distinct independenceGroups`); if (c.status === 'PRIMARY_CONFIRMED' && !primary.get(c.claimId)) fail(`${tag}: PRIMARY_CONFIRMED requires a PRIMARY_CONFIRMATION link from an OFFICIAL source`); if (c.status === 'RETRACTED' && !k.has('RETRACTION')) fail(`${tag}: RETRACTED requires a RETRACTION relation`); if (c.status === 'CONTRADICTED' && !k.has('CONTRADICTION')) fail(`${tag}: CONTRADICTED requires a CONTRADICTION relation`); }
  const covered = new Set();
  for (const pc of arr('providerCoverage')) { if (!isPlainObject(pc)) { fail('providerCoverage: not an object'); continue; } const tag = `coverage ${String(pc.provider).slice(0, 24)}`; checkKeys(pc, 'providerCoverage', tag); if (!isBoundedString(pc.provider, MAX_ID_CHARS)) fail(`${tag}: provider required`); else if (covered.has(pc.provider)) fail(`${tag}: duplicate provider coverage entry`); else covered.add(pc.provider); if (!PROVIDER_COVERAGE_STATES.includes(pc.state)) fail(`${tag}: unknown state`); if (pc.state === 'NOT_QUERIED') { if (pc.checkedTs !== null) fail(`${tag}: NOT_QUERIED must carry checkedTs null`); } else inTime(pc.checkedTs, `${tag}: checkedTs`); if (pc.detail !== null && !isBoundedString(pc.detail, MAX_TEXT_CHARS)) fail(`${tag}: detail must be null or bounded`); }
  dupSetCheck('contradictions');
  for (const cd of arr('contradictions')) { if (!isPlainObject(cd)) { fail('contradiction: not an object'); continue; } checkKeys(cd, 'contradiction', 'contradiction'); if (!isBoundedString(cd.description, MAX_TEXT_CHARS)) fail('contradiction: description required'); refSetCheck(cd.claimRefs, 'contradiction: claimRefs'); refSetCheck(cd.sourceRefs, 'contradiction: sourceRefs'); refSetCheck(cd.evidenceRefs, 'contradiction: evidenceRefs'); let n = 0; for (const r of Array.isArray(cd.claimRefs) ? cd.claimRefs : []) { if (!claimIds.has(r)) fail('contradiction: dangling claimRef'); n += 1; } for (const r of Array.isArray(cd.sourceRefs) ? cd.sourceRefs : []) { if (!sourceIds.has(r)) fail('contradiction: dangling sourceRef'); n += 1; } for (const r of Array.isArray(cd.evidenceRefs) ? cd.evidenceRefs : []) { if (!evidenceIds.has(r)) fail('contradiction: dangling evidenceRef'); n += 1; } if (n < 2) fail('contradiction: must point at >=2 exact references'); }
  dupSetCheck('missingEvidence');
  for (const m of arr('missingEvidence')) { if (!isPlainObject(m)) { fail('missingEvidence: not an object'); continue; } checkKeys(m, 'missingEvidence', 'missingEvidence'); if (!isBoundedString(m.kind, MAX_ID_CHARS)) fail('missingEvidence: kind required'); if (!isBoundedString(m.description, MAX_TEXT_CHARS)) fail('missingEvidence: description required'); }
  dupSetCheck('analogs');
  for (const a of arr('analogs')) { if (!isPlainObject(a)) { fail('analog: not an object'); continue; } const tag = `analog ${String(a.memoryId).slice(0, 24)}`; checkKeys(a, 'analog', tag); if (!isBoundedString(a.memoryId, MAX_ID_CHARS)) fail(`${tag}: memoryId required`); if (!isBoundedString(a.setupFamily, MAX_ID_CHARS)) fail(`${tag}: setupFamily required`); if (!isBoundedString(a.similarityBasis, MAX_TEXT_CHARS)) fail(`${tag}: similarityBasis required`); inTime(a.knownAtTs, `${tag}: knownAtTs`); if (a.outcome !== null) { if (!isPlainObject(a.outcome)) fail(`${tag}: outcome must be null or an object`); else { checkKeys(a.outcome, 'analogOutcome', `${tag}: outcome`); if (!isBoundedString(a.outcome.reference, MAX_ID_CHARS)) fail(`${tag}: outcome.reference required`); inTime(a.outcome.outcomeKnownAtTs, `${tag}: outcome.outcomeKnownAtTs`); } } }
  if (!isPlainObject(packet.security)) fail('security: missing'); else { checkKeys(packet.security, 'security', 'security'); const has = arr('sources').some((s) => isPlainObject(s) && isPlainObject(s.excerpt)) || arr('evidence').some((e) => isPlainObject(e) && e.kind === 'MARKET_EVENT_CONTEXT' && Array.isArray(e.value?.fields?.events) && e.value.fields.events.some((x) => x && x.headline !== null && x.headline !== undefined)); if (typeof packet.security.untrustedTextPresent !== 'boolean') fail('security: untrustedTextPresent must be boolean'); else if (packet.security.untrustedTextPresent !== has) fail(`security: untrustedTextPresent=${packet.security.untrustedTextPresent} disagrees with actual untrusted text`); }
  // v2 researchContext
  if (!isPlainObject(packet.researchContext)) fail('researchContext: missing'); else {
    const rc = packet.researchContext; checkKeys(rc, 'researchContext', 'researchContext'); for (const k of RESEARCH_CONTEXT_KEYS) if (!(k in rc)) fail(`researchContext: missing field '${k}'`);
    if (!RESEARCH_MODES.includes(rc.mode)) fail('researchContext: unknown mode');
    if (!Array.isArray(rc.entrances) || rc.entrances.length === 0 || rc.entrances.length > RESEARCH_ENTRANCES.length || rc.entrances.some((e) => !RESEARCH_ENTRANCES.includes(e)) || new Set(rc.entrances).size !== rc.entrances.length) fail('researchContext: entrances must be a non-empty unique subset of the closed set');
    if (!(rc.dossierRef === null || (typeof rc.dossierRef === 'string' && /^evd-[0-9a-f]{40}$/.test(rc.dossierRef)))) fail('researchContext: dossierRef must be null or an evidence id'); else if (rc.dossierRef !== null) { const d = evidenceById.get(rc.dossierRef); if (!d) fail('researchContext: dossierRef does not resolve'); else if (d.kind !== 'SOCIAL_DOSSIER_CONTEXT') fail('researchContext: dossierRef must name a SOCIAL_DOSSIER_CONTEXT item'); }
    if (!(rc.marketContextRef === null || (typeof rc.marketContextRef === 'string' && /^evd-[0-9a-f]{40}$/.test(rc.marketContextRef)))) fail('researchContext: marketContextRef must be null or an evidence id'); else if (rc.marketContextRef !== null) { const m = evidenceById.get(rc.marketContextRef); if (!m) fail('researchContext: marketContextRef does not resolve'); else if (m.kind !== 'MARKET_CONTEXT_SUMMARY') fail('researchContext: marketContextRef must name the MARKET_CONTEXT_SUMMARY, never an arbitrary chart item'); }
    if (rc.marketContextRef === null && summaries.length) fail('researchContext: a MARKET_CONTEXT_SUMMARY exists but marketContextRef is null'); if (rc.marketContextRef !== null && !summaries.length) fail('researchContext: marketContextRef names a summary that is absent');
    if (!Array.isArray(rc.sourceHistoryRefs) || rc.sourceHistoryRefs.length > MAX_SOURCE_HISTORY_REFS || new Set(rc.sourceHistoryRefs).size !== rc.sourceHistoryRefs.length) fail(`researchContext: sourceHistoryRefs must be a unique set of at most ${MAX_SOURCE_HISTORY_REFS}`); else for (const r of rc.sourceHistoryRefs) { const h = evidenceById.get(r); if (!h) fail('researchContext: sourceHistoryRef does not resolve'); else if (h.kind !== 'SOCIAL_SOURCE_HISTORY') fail('researchContext: sourceHistoryRef must name a SOCIAL_SOURCE_HISTORY item'); }
    if (!Array.isArray(rc.coverageLimitations) || rc.coverageLimitations.some((x) => !COVERAGE_LIMITATION_REASONS.includes(x)) || new Set(rc.coverageLimitations).size !== rc.coverageLimitations.length) fail('researchContext: coverageLimitations must be a unique subset of the closed reason set');
    if (rc.authority !== 'NONE') fail('researchContext: authority must be NONE'); if (rc.purpose !== 'RESEARCH_ONLY') fail('researchContext: purpose must be RESEARCH_ONLY');
    if (rc.mode === 'REPLAY_AS_OF' && !rc.coverageLimitations.includes('REPLAY_NETWORK_OFF')) fail('researchContext: replay mode must declare REPLAY_NETWORK_OFF');
    if (packet.trigger && packet.trigger.kind === 'MARKET_RESEARCH' && !rc.entrances.includes('MARKET_LED')) fail('researchContext: a MARKET_RESEARCH trigger is MARKET_LED');
  }
  if (reasons.length === 0) { if (typeof packet.packetId !== 'string' || !PACKET_ID_RE_V2.test(packet.packetId)) fail('packet: invalid packetId'); else if (packet.packetId !== packetIdentityV2(packet)) fail('packet: packetId does not match semantic content'); }
  return done();
}
export { EVIDENCE_SCHEMA_VERSION as EVIDENCE_SCHEMA_VERSION_1, MAX_PACKET_CANONICAL_CHARS, MAX_PACKET_RAW_CHARS, MAX_EXCERPT_CHARS, MAX_CLAIMS, MAX_SOURCES, MAX_EVIDENCE, MAX_CLAIM_LINKS, MAX_CONTRADICTIONS, MAX_MISSING_EVIDENCE, MAX_ANALOGS, MAX_REFS_PER_ITEM, MAX_TEXT_CHARS, MAX_ID_CHARS, canonicalJson, contentHash, normalizeRefSets, claimIdentity, sourceIdentity, evidenceIdentity, boundedReason, jsonShapeError };
