// EVIDENCE V2 — buildResearchEvidenceV2 (§9, closeout R03): ONE pure boundary that assembles the actual market/social dossier.
//   buildResearchEvidenceV2({ marketContext, socialProjection, asOfTs, trigger, mode, entrances, detailRequests })
// marketContext (a validated market-context-2) and socialProjection (a validated social-projection-1) may each be null
// but must validate when supplied; both null => a valid, explicitly EMPTY research packet (never a forged observation).
// METRIC_MAP is the ONE closed mapping family + registered metric -> context component (recipe) -> typed evidence kind /
// fields -> native inputs; it drives the default summaries, explicit DETAIL admission and the broker's satisfaction test.
// Deterministic admission recipe: reserve one compact summary per required family in canonical family order (plus the
// exit-liquidity and multi-venue descriptors, H03 / H02, which are independent of their siblings), then the
// MARKET_CONTEXT_SUMMARY (components first, summary next, packet last), then Social items, then explicitly requested detail
// in canonical order until the bounds bind; omission counts are reconciled AFTER admission. Failure to fit the mandatory
// summaries returns PACKET_LIMIT_EXCEEDED with no packet — no family is silently dropped.
import { EVIDENCE_SCHEMA_VERSION_2, MARKET_EVIDENCE_KINDS, KIND_FAMILY, COVERAGE_LIMITATION_REASONS, TRIGGER_KINDS_V2, RESEARCH_MODES, RESEARCH_ENTRANCES, MAX_COMPONENT_IDS, MAX_EVIDENCE, MAX_SOURCES, MAX_PACKET_CANONICAL_CHARS, MAX_PACKET_UTF8_BYTES, canonicalJson, sourceIdentity, evidenceIdentity, packetIdentityV2, validateEvidencePacketV2, typedValueError } from './contract-v2.js';
import { contextError } from '../market-lab/context.js';
import { FAMILIES, FAMILY_REGISTRY, VALUE_BEARING } from '../market-lab/contracts.js';
import { RECIPE_SET_VERSION } from '../market-lab/recipes.js';
import { projectSocial, socialProjectionError } from './social-projection.js';

export const ADMISSION_RECIPE = 'mandatory-summaries-then-explicit-detail-canonical-order-v2';
export const MAX_VALUE_CHARS = 4_096;
export const OMISSION_REASONS = Object.freeze(['DETAIL_NOT_REQUESTED', 'EVIDENCE_CAP', 'PACKET_BYTE_CAP', 'INVALID', 'NO_COMPONENT_IN_CONTEXT', 'NO_COMPONENT_RECIPE', 'ADMITTED']);
const PROVIDER_SOURCE_TYPE = (p) => (['CRYPTOQUANT', 'SANTIMENT', 'COINMETRICS', 'GECKOTERMINAL', 'DEFILLAMA'].includes(p) ? 'ONCHAIN' : p === 'SETTLED_RECORDS' ? 'OTHER' : 'MARKET_DATA');
const VENUE_PROVIDER = { kraken: 'KRAKEN_SPOT', coinbase: 'COINBASE_SPOT', 'kraken-futures': 'KRAKEN_DERIVATIVES', deribit: 'DERIBIT', bybit: 'BYBIT', 'coinglass-aggregate': 'COINGLASS' };
const isTs = (v) => Number.isSafeInteger(v) && v > 0;
const num = (v) => (typeof v === 'number' && Number.isFinite(v) ? v : null);
const clip = (arr, n) => (Array.isArray(arr) ? arr.slice(0, n) : []);
// shrink a typed value deterministically until its canonical form fits the per-value cap (arrays first, longest first)
function fit(value) { let v = value; for (let round = 0; round < 12; round += 1) { if (canonicalJson(v).length <= MAX_VALUE_CHARS) return v; const f = { ...v.fields }; const arrays = Object.entries(f).filter(([, x]) => Array.isArray(x) && x.length > 0).sort((a, b) => b[1].length - a[1].length); if (!arrays.length) break; const [k, x] = arrays[0]; f[k] = x.slice(0, Math.max(0, Math.floor(x.length / 2))); v = { ...v, fields: f }; } return canonicalJson(v).length <= MAX_VALUE_CHARS ? v : null; }
// closeout E04 / V03: a component whose support says the input is ABSENT (no book, no closed bar, no options, ...) is a MISSING item,
// never a KNOWN one with null fields; a stale input is STALE; only a value-bearing support is KNOWN
const ABSENT_SUPPORT = new Set(['NO_BOOK', 'NO_TWO_SIDED_BOOK', 'NO_CLOSED_BARS', 'NO_OPTIONS', 'NO_FLOWS', 'NO_REFERENCE', 'MISSING', 'MISSING_LEG', 'MISSING_POINT', 'VALUE_MISSING', 'NO_EVENT', 'UNIT_MISMATCH', 'SCOPE_MISMATCH', 'QUOTE_MISMATCH', 'MATCH_FAILED', 'RECIPE_MISMATCH']);
const stateOf = (support, famState) => (famState === 'NOT_SUPPORTED' ? 'UNAVAILABLE' : famState === 'MISSING' || famState === 'NOT_QUERIED' ? 'MISSING' : support?.state === 'STALE' ? 'STALE' : ABSENT_SUPPORT.has(support?.state) ? 'MISSING' : 'KNOWN');
// ---- typed value envelope from a context component -------------------------------------------------------------------
const base = (ctx, c, kind, fields, { units = {}, supportOverride = null } = {}) => ({ kind, canonicalCoin: ctx.canonicalCoin, asOfTs: ctx.asOfTs, windowStartTs: c?.windowStartTs ?? null, windowEndTs: c?.windowEndTs ?? null, observedTs: c ? (c.windowEndTs ?? c.inputKnownAtMax ?? null) : null, knownAtTs: c ? Math.min(ctx.asOfTs, Math.max(c.inputKnownAtMax ?? ctx.asOfTs, c.windowEndTs ?? 0)) : ctx.asOfTs, recipe: c ? { recipeId: c.recipeId, version: c.version, recipeSetVersion: ctx.recipeSetVersion } : null, support: supportOverride ?? { state: (c?.support?.state ?? 'NO_COMPONENT').replace(/[^A-Z0-9_]/g, '_').slice(0, 48), reasons: clip(c?.support?.reasons ?? [], 8).map((r) => String(r).replace(/[^A-Z0-9_:-]/g, '_').slice(0, 64)), completeness: null }, units, sourceIds: c ? [c.componentId] : [], fields });
const v = (c) => c?.value ?? {};
// ---- per-component typed-value builders (one per context recipe component) ------------------------------------------------
const BUILD = {
  chart: (ctx, c, comps) => { const cur = v(c).current ?? {}; const prev = v(c).previous ?? {}; const ra = comps.find((x) => x.metricId === 'relative_activity' && x.value?.venue === v(c).venue) ?? null; const ind = comps.find((x) => x.metricId === 'indicators' && x.value?.venue === v(c).venue && x.value?.intervalMs === 3_600_000) ?? comps.find((x) => x.metricId === 'indicators' && x.value?.venue === v(c).venue) ?? null; const iv = ind ? v(ind) : null;
    return { comp: c, extra: [ra, ind].filter(Boolean), value: base(ctx, c, 'MARKET_CHART_WINDOW', { venue: v(c).venue, quote: v(c).quote, windowMs: cur.windowMs ?? 60_000, open: cur.open ?? null, high: cur.high ?? null, low: cur.low ?? null, close: cur.close ?? null, vwap: cur.vwap ?? null, logReturn: cur.logReturn ?? null, quoteNotional: cur.quoteNotional ?? null, count: cur.count ?? null, relativeNotional: ra ? num(v(ra).notional?.ratio) : null, relativeRange: ra ? num(v(ra).range?.ratio) : null, indicators: iv ? { intervalMs: iv.intervalMs, closedBars: iv.closedBars, lastClose: iv.lastClose, sma: iv.sma, ema: iv.ema, rsi14: iv.rsi14, macd: iv.macd, bollinger20: iv.bollinger20, atr14: iv.atr14, prior20: iv.prior20, prior60: iv.prior60, realizedVolatility: iv.realizedVolatility, breakout: iv.breakout, capReached: iv.completeness?.capReached ?? null } : null, previous: { logReturn: prev.logReturn ?? null, quoteNotional: prev.quoteNotional ?? null, count: prev.count ?? null, close: prev.close ?? null, coverage: prev.support?.state ?? null } }, { units: { close: v(c).quote ?? 'QUOTE', quoteNotional: v(c).quote ?? 'QUOTE', logReturn: 'FRACTION' } }) }; },
  indicators: (ctx, c) => { const iv = v(c); return { comp: c, extra: [], value: base(ctx, c, 'MARKET_CHART_WINDOW', { venue: iv.venue, quote: 'QUOTE', windowMs: iv.intervalMs, open: null, high: null, low: null, close: iv.lastClose ?? null, vwap: null, logReturn: null, quoteNotional: null, count: null, relativeNotional: null, relativeRange: null, indicators: { intervalMs: iv.intervalMs, closedBars: iv.closedBars, lastClose: iv.lastClose, sma: iv.sma, ema: iv.ema, rsi14: iv.rsi14, macd: iv.macd, bollinger20: iv.bollinger20, atr14: iv.atr14, prior20: iv.prior20, prior60: iv.prior60, realizedVolatility: iv.realizedVolatility, breakout: iv.breakout, capReached: iv.completeness?.capReached ?? null }, previous: null }, { units: { close: 'QUOTE' } }) }; },
  relativeActivity: (ctx, c) => { const x = v(c); return { comp: c, extra: [], value: base(ctx, c, 'MARKET_CHART_WINDOW', { venue: x.venue, quote: 'QUOTE', windowMs: 60_000, open: null, high: null, low: null, close: null, vwap: null, logReturn: null, quoteNotional: num(x.notional?.current), count: null, relativeNotional: num(x.notional?.ratio), relativeRange: num(x.range?.ratio), indicators: null, previous: null }, { units: { quoteNotional: 'QUOTE' } }) }; },
  flow: (ctx, c) => { const x = v(c); const q = x.current ?? {}; const p = x.previous ?? {}; return { comp: c, extra: [], value: base(ctx, c, 'MARKET_PRESSURE_RESPONSE_CHANGE', { venue: x.venue, quote: x.quote, previousSigned: p.signedNotional ?? null, currentSigned: q.signedNotional ?? null, previousResponseBps: null, currentResponseBps: null, previousEfficiency: null, currentEfficiency: null, efficiencyChange: null, pressureChange: num(q.signedNotional) !== null && num(p.signedNotional) !== null ? q.signedNotional - p.signedNotional : null, spreadStartBps: null, spreadEndBps: null, replenishment: null, knownSideFraction: q.knownSideFraction ?? null, alternatives: [] }, { units: { signed: x.quote ?? 'QUOTE' } }) }; },
  pressure: (ctx, c) => { const x = v(c); const p = x.previous ?? {}; const q = x.current ?? {}; return { comp: c, extra: [], value: base(ctx, c, 'MARKET_PRESSURE_RESPONSE_CHANGE', { venue: x.venue, quote: x.quote, previousSigned: p.signedNotional ?? null, currentSigned: q.signedNotional ?? null, previousResponseBps: p.responseBps ?? null, currentResponseBps: q.responseBps ?? null, previousEfficiency: p.efficiencyBpsPerMillion ?? null, currentEfficiency: q.efficiencyBpsPerMillion ?? null, efficiencyChange: x.efficiencyChange ?? null, pressureChange: x.pressureChange ?? null, spreadStartBps: q.spreadStartBps ?? null, spreadEndBps: q.spreadEndBps ?? null, replenishment: x.replenishment ?? null, knownSideFraction: q.knownSideFraction ?? null, alternatives: q.alternatives ?? [] }, { units: { signed: x.quote ?? 'QUOTE', efficiency: `bps per million ${x.quote ?? 'QUOTE'}` } }) }; },
  book: (ctx, c) => { const x = v(c); const bands = {}; for (const [k, b] of Object.entries(x.bands ?? {})) bands[k] = { bidNotional: b.bid?.notional ?? null, askNotional: b.ask?.notional ?? null, bidLowerBoundOnly: b.bid?.lowerBoundOnly ?? null, askLowerBoundOnly: b.ask?.lowerBoundOnly ?? null, imbalance: b.imbalance ?? null };
    return { comp: c, extra: [], value: base(ctx, c, 'MARKET_BOOK_CONTEXT', { venue: x.venue, quote: x.quote ?? 'QUOTE', mid: x.mid ?? null, spreadBps: x.spreadBps ?? null, microprice: x.microprice ?? null, bands, bookAgeMs: x.bookAgeMs ?? null, synchronized: x.synchronized ?? null, checksumVerified: x.checksumVerified ?? null, attribution: 'AGGREGATE_L2_UNATTRIBUTED' }, { units: { mid: x.quote ?? 'QUOTE', spreadBps: 'BPS' } }) }; },
  // H03: displayed round-trip loss — lossBps, proceeds and depth support, independent of spreadBps; haircuts stay scenarios
  exit: (ctx, c) => { const x = v(c); const cur = x.current ?? {}; const prev = x.previous ?? null; return { comp: c, extra: [], value: base(ctx, c, 'MARKET_DISPLAYED_EXIT_LIQUIDITY_CHANGE', { venue: x.venue, quoteNotional: x.quoteNotional, currentLossBps: cur.lossBps ?? null, previousLossBps: prev?.lossBps ?? null, lossChangeBps: x.lossChangeBps ?? null, currentCoverage: cur.coverage ?? 'NO_BOOK', previousCoverage: prev?.coverage ?? null, worstBuyPrice: cur.worstBuyPrice ?? null, worstSellPrice: cur.worstSellPrice ?? null, residualBuyQuote: cur.buy?.residualQuote ?? null, residualSellBase: cur.sell?.residualBase ?? null, haircuts: clip(x.haircuts, 3).map((h) => ({ haircut: h.haircut, scenario: h.scenario, lossBps: h.lossBps ?? null, coverage: h.coverage })), preFee: true }, { units: { quoteNotional: 'QUOTE', lossBps: 'BPS' } }) }; },
  peers: (ctx, c, comps) => { const x = v(c); const d = comps.find((z) => z.metricId === 'venue_mid_dispersion') ?? null; return { comp: c, extra: [], value: base(ctx, c, 'MARKET_PEER_RELATIVE_MOVE', { cohortLabel: x.cohortLabel ?? 'SAME_QUOTE_VENUE', targetReturnBps: x.targetReturnBps ?? null, medianPeerReturnBps: x.medianPeerReturnBps ?? null, residualBps: x.residualBps ?? null, madBps: x.madBps ?? null, n: x.n ?? 0, positivePeers: x.positivePeers ?? null, excluded: clip(x.excluded, 16), firstObservedChanges: clip(d ? v(d).firstObservedChanges?.sequence : [], 8) }, { units: { residualBps: 'BPS' } }) }; },
  // H02 cross-venue: dispersion of same-quote venue mids, independent of the peer cohort (works with zero peers)
  dispersion: (ctx, c) => { const x = v(c); const d = x.dispersion ?? {}; return { comp: c, extra: [], value: base(ctx, c, 'MARKET_MULTI_VENUE_CONTEXT', { quote: d.quote ?? null, medianMid: d.medianMid ?? null, dispersionBps: d.dispersionBps ?? null, n: d.n ?? 0, venues: clip(d.venues, 8).map((z) => ({ venue: z.venue, mid: z.mid, receivedTs: z.receivedTs ?? null })), firstObservedChanges: clip(x.firstObservedChanges?.sequence, 8) }, { units: { dispersionBps: 'BPS', medianMid: d.quote ?? 'QUOTE' } }, { supportOverride: { state: String(d.support?.state ?? c.support?.state ?? 'UNKNOWN').replace(/[^A-Z0-9_]/g, '_').slice(0, 48), reasons: clip(d.support?.reasons ?? [], 8).map((r) => String(r).replace(/[^A-Z0-9_:-]/g, '_').slice(0, 64)), completeness: null } }) }; },
  derivatives: (ctx, c) => { const x = v(c); return { comp: c, extra: [], value: base(ctx, c, 'MARKET_DERIVATIVES_CONTEXT', { instrument: x.instrument, venue: String(x.instrument).split(':')[0], marketType: x.marketType, basisBps: x.basisBps ?? null, markPrice: x.markPrice ?? null, indexPrice: x.indexPrice ?? null, openInterest: x.openInterest?.value ?? null, openInterestUnit: x.openInterest?.unit ?? 'UNKNOWN', oiChangeAbsolute: x.openInterest?.changeOverHour?.absolute ?? null, oiChangePercent: x.openInterest?.changeOverHour?.percent ?? null, fundingNative: x.funding?.value ?? null, fundingUnit: x.funding?.unit ?? 'UNKNOWN', fundingIntervalMs: x.funding?.intervalMs ?? null, fundingRelative: x.funding?.relative ?? null, ageMs: x.ageMs ?? null }, { units: { basisBps: 'BPS', funding: x.funding?.unit ?? 'UNKNOWN' } }) }; },
  liquidations: (ctx, c) => { const x = v(c); return { comp: c, extra: [], value: base(ctx, c, 'MARKET_LIQUIDATIONS_CONTEXT', { windowMs: c.windowEndTs - c.windowStartTs, events: x.events ?? 0, longNotional: x.longNotional ?? null, shortNotional: x.shortNotional ?? null, unknownSideNotional: x.unknownSideNotional ?? null, unit: x.unit ?? null, venues: clip(x.venues, 16), zeroMeaningful: x.zeroMeaningful === true }, { units: { notional: x.unit ?? 'UNKNOWN' } }) }; },
  options: (ctx, c) => { const x = v(c); return { comp: c, extra: [], value: base(ctx, c, 'MARKET_OPTIONS_CONTEXT', { scope: x.scope ?? null, admitted: x.admitted ?? 0, omitted: x.admission?.omitted ?? x.census?.omitted ?? 0, censusComplete: x.censusComplete === true, term: clip(x.term, 8).map((t) => ({ expiryTs: t.expiryTs, contracts: t.contracts, atmIv: t.atm?.markIv ?? null, atmStrike: t.atm?.strike ?? null, riskReversal25d: t.riskReversal25d, butterfly25d: t.butterfly25d, callDelta: t.call25?.delta ?? null, putDelta: t.put25?.delta ?? null, putCallOiRatio: t.putCallOiRatio, ratioScope: t.ratioScope ?? null, atmIvBidAskSpread: t.atmIvBidAskSpread, greeksMissing: t.greeksMissing ?? null, support: t.support?.state ?? null })) }, { units: { iv: 'FRACTION' } }) }; },
  supply: (ctx, c, comps) => { const s = c.metricId === 'supply_ratios' ? c : comps.find((z) => z.metricId === 'supply_ratios') ?? null; const u = c.metricId === 'unlock_schedule' ? c : comps.find((z) => z.metricId === 'unlock_schedule') ?? null; const x = v(s); const uu = v(u); return { comp: c, extra: [s, u].filter((z) => z && z !== c), value: base(ctx, c, 'MARKET_SUPPLY_UNLOCKS', { circulatingOverTotal: x.circulatingOverTotal ?? null, circulatingOverMax: x.circulatingOverMax ?? null, fdvOverMarketCap: x.fdvOverMarketCap ?? null, volumeOverMarketCap: x.volumeOverMarketCap ?? null, maxSupplyKnown: x.maxSupplyKnown ?? null, marketCapUsd: x.reference?.marketCapUsd ?? null, upcoming: clip(uu.upcoming, 8), untrackedAllocations: uu.untrackedAllocations ?? null, referenceProvider: x.reference?.provider ?? null }, { units: { marketCapUsd: 'USD' } }) }; },
  dex: (ctx, c, comps) => { const pools = comps.filter((z) => z.metricId === 'pool_liquidity'); const prots = comps.filter((z) => z.family === 'DEX_DEFI' && z.metricId !== 'pool_liquidity'); return { comp: c, extra: [...pools, ...prots].filter((z) => z !== c), value: base(ctx, c, 'MARKET_DEX_DEFI_CONTEXT', { pools: clip(pools, 4).map((p) => ({ chain: p.value.chain, poolAddress: p.value.poolAddress, dex: p.value.dex ?? null, quoteToken: p.value.quoteToken, priceUsd: p.value.priceUsd, liquidityUsd: p.value.liquidityUsd, volume24hUsd: p.value.volume24hUsd, txCount24h: p.value.txCount24h, ageMs: p.value.ageMs, provider: p.value.provider })), protocols: clip(prots, 8).map((p) => ({ metricId: p.value.metricId, protocol: p.value.protocol ?? null, chain: p.value.chain ?? null, value: p.value.value, unit: p.value.unit, periodKind: p.value.periodKind, ageMs: p.value.ageMs, provider: p.value.provider })) }, { units: { liquidityUsd: 'USD' } }) }; },
  onchain: (ctx, c, comps) => { const f = c.metricId === 'exchange_net_flow' ? c : comps.find((z) => z.metricId === 'exchange_net_flow') ?? null; const r = c.metricId === 'exchange_reserve' ? c : comps.find((z) => z.metricId === 'exchange_reserve') ?? null; const x = v(f); return { comp: c, extra: [f, r].filter((z) => z && z !== c), value: base(ctx, c, 'MARKET_ONCHAIN_CONTEXT', { provider: x.provider ?? v(r).provider ?? v(c).provider ?? 'UNKNOWN', entitySet: x.entitySet ?? v(r).entitySet ?? v(c).entitySet ?? null, chain: x.chain ?? v(r).chain ?? v(c).chain ?? null, window: x.window ?? v(r).window ?? v(c).window ?? null, inflow: x.inflow ?? null, outflow: x.outflow ?? null, net: x.net ?? null, reserve: v(r).value ?? null, unit: x.unit ?? v(r).unit ?? v(c).unit ?? null, labelVintage: x.labelVintage ?? v(c).labelVintage ?? null, periodStartTs: x.periodStartTs ?? c.windowStartTs ?? null, periodEndTs: x.periodEndTs ?? c.windowEndTs ?? null }, { units: { net: x.unit ?? 'NATIVE' } }) }; },
  network: (ctx, c, comps) => { const prov = c.value.provider; const mine = comps.filter((z) => z.family === 'NETWORK_ACTIVITY' && z.value.provider === prov); const list = mine.length ? mine : [c]; return { comp: c, extra: list.filter((z) => z !== c), value: base(ctx, c, 'MARKET_NETWORK_CONTEXT', { provider: prov, metrics: clip(list, 12).map((m) => ({ metricId: m.value.nativeMetric ?? m.metricId, registeredMetric: m.metricId, value: m.value.value, unit: m.value.unit, change: m.value.change ?? null, periodEndTs: m.windowEndTs, ageMs: m.value.ageMs })) }) }; },
  stable: (ctx, c) => { const x = v(c); return { comp: c, extra: [], value: base(ctx, c, 'MARKET_STABLECOIN_CONTEXT', { stablecoinId: x.stablecoinId, chain: x.chain ?? null, current: x.current ?? null, change: x.change ?? null, unit: x.unit ?? null, pegPrice: x.pegPrice ?? null, pegDeviationBps: x.pegDeviationBps ?? null, fromTs: x.fromTs ?? null, toTs: x.toTs ?? null }, { units: { current: x.unit ?? 'NATIVE', pegDeviationBps: 'BPS' } }) }; },
  etf: (ctx, c) => { const x = v(c); return { comp: c, extra: [], value: base(ctx, c, 'MARKET_ETF_CONTEXT', { asset: x.asset ?? ctx.canonicalCoin, latestFlowUsd: x.latest?.flowUsd ?? null, latestPeriodStartTs: x.latest?.periodStartTs ?? null, latestPeriodEndTs: x.latest?.periodEndTs ?? null, trailing5: x.trailing5 ?? null, trailing20: x.trailing20 ?? null, estimate: x.latest?.estimate ?? null, days: x.days ?? 0 }, { units: { flow: 'USD' } }) }; },
  macro: (ctx, c, comps) => { const levels = comps.filter((z) => z.metricId === 'macro_level'); const ev = comps.find((z) => z.metricId === 'macro_surprise') ?? null; const list = c.metricId === 'macro_level' ? levels : []; return { comp: c, extra: [...levels, ev].filter((z) => z && z !== c), value: base(ctx, c, 'MARKET_MACRO_CONTEXT', { levels: clip(list.length ? list : levels, 16).map((l) => ({ seriesId: l.value.seriesId, value: l.value.value, unit: l.value.unit, observationDate: l.value.observationDate, vintageDate: l.value.vintageDate, change: l.value.change, ageMs: l.value.ageMs })), upcoming: clip(ev ? v(ev).upcoming : [], 8), released: clip(ev ? v(ev).released : [], 8).map((r) => ({ eventName: r.eventName, countryCode: r.countryCode, scheduledTs: r.scheduledTs, actual: r.actual, forecast: r.forecast, unit: r.unit, surprise: r.surprise?.surprise ?? null, surpriseSupport: r.surprise?.support?.state ?? null })) }) }; },
  cross: (ctx, c, comps) => { const list = comps.filter((z) => z.family === 'CROSS_ASSET'); return { comp: c, extra: list.filter((z) => z !== c), value: base(ctx, c, 'MARKET_CROSS_ASSET_CONTEXT', { instruments: clip(list.length ? list : [c], 8).map((z) => ({ instrument: z.value.instrument, proxyFor: z.value.proxyFor, sessionState: z.value.sessionState, intervalMs: z.value.intervalMs, lastClose: z.value.lastClose, lastBarEndTs: z.value.lastBarEndTs, logReturnLastBar: z.value.logReturnLastBar, correlationR: z.value.correlationWithTarget?.r ?? null, correlationN: z.value.correlationWithTarget?.n ?? null, ageMs: z.value.ageMs })) }) }; },
  events: (ctx, c) => ({ comp: c, extra: [], value: base(ctx, c, 'MARKET_EVENT_CONTEXT', { events: clip(v(c).events, 16).map((e) => ({ eventKind: e.eventKind, sourceProvider: e.sourceProvider, nativeRef: e.nativeRef, sourceEventTs: e.sourceEventTs, knownAtTs: e.knownAtTs, status: e.status, headline: e.headline ?? null, untrusted: e.untrusted })) }) }),
  infra: (ctx, c) => ({ comp: c, extra: [], value: base(ctx, c, 'MARKET_INFRA_CONTEXT', { statuses: clip(v(c).statuses, 16), incidents: clip(v(c).incidents, 8) }) }),
};
const onchainNative = (o) => o.payload?.metricId ?? null;
// ---- THE closed mapping: family + registered metric -> context component -> typed kind + builder -> native inputs ---------------
// component: the recipe component that carries the metric (its metricId in the context); pick: how the default summary selects
// it; kind: the closed v2 evidence kind; inputKinds / native: the observation kinds and native ids that SATISFY the metric
// (used by the broker); scope: SUBJECT (registered subject) or GLOBAL (a null-subject observation may satisfy it).
const M = (component, build, kind, { inputKinds, native = null, nativeOf = null, scope = 'SUBJECT', pick = null, summary = false, unsupported = null } = {}) => ({ component, build, kind, inputKinds, native, nativeOf, scope, pick, summary, unsupported });
const chartPick = (comps) => comps.find((c) => c.metricId === 'window_ohlcv' && c.value?.current?.windowMs === 60_000) ?? comps.find((c) => c.metricId === 'window_ohlcv') ?? null;
export const METRIC_MAP = Object.freeze({
  SPOT_PRICE_CHART: { window_ohlcv: M('window_ohlcv', 'chart', 'MARKET_CHART_WINDOW', { inputKinds: ['TRADE', 'CANDLE'], pick: chartPick, summary: true }), vwap: M('window_ohlcv', 'chart', 'MARKET_CHART_WINDOW', { inputKinds: ['TRADE'], pick: chartPick }), log_return: M('window_ohlcv', 'chart', 'MARKET_CHART_WINDOW', { inputKinds: ['TRADE', 'CANDLE'], pick: chartPick }), close_location: M('window_ohlcv', 'chart', 'MARKET_CHART_WINDOW', { inputKinds: ['TRADE'], pick: chartPick }), sma: M('indicators', 'indicators', 'MARKET_CHART_WINDOW', { inputKinds: ['CANDLE'] }), ema: M('indicators', 'indicators', 'MARKET_CHART_WINDOW', { inputKinds: ['CANDLE'] }), realized_volatility: M('indicators', 'indicators', 'MARKET_CHART_WINDOW', { inputKinds: ['CANDLE'] }), atr14: M('indicators', 'indicators', 'MARKET_CHART_WINDOW', { inputKinds: ['CANDLE'] }), rsi14: M('indicators', 'indicators', 'MARKET_CHART_WINDOW', { inputKinds: ['CANDLE'] }), macd: M('indicators', 'indicators', 'MARKET_CHART_WINDOW', { inputKinds: ['CANDLE'] }), bollinger20: M('indicators', 'indicators', 'MARKET_CHART_WINDOW', { inputKinds: ['CANDLE'] }), prior_range: M('indicators', 'indicators', 'MARKET_CHART_WINDOW', { inputKinds: ['CANDLE'] }), relative_activity: M('relative_activity', 'relativeActivity', 'MARKET_CHART_WINDOW', { inputKinds: ['TRADE'] }), breakout_distance: M('indicators', 'indicators', 'MARKET_CHART_WINDOW', { inputKinds: ['CANDLE'] }) },
  SPOT_FLOW: { signed_notional: M('signed_notional', 'flow', 'MARKET_PRESSURE_RESPONSE_CHANGE', { inputKinds: ['TRADE'] }), known_side_imbalance: M('signed_notional', 'flow', 'MARKET_PRESSURE_RESPONSE_CHANGE', { inputKinds: ['TRADE'] }), trade_size_stats: M('signed_notional', 'flow', 'MARKET_PRESSURE_RESPONSE_CHANGE', { inputKinds: ['TRADE'] }), interarrival: M('signed_notional', 'flow', 'MARKET_PRESSURE_RESPONSE_CHANGE', { inputKinds: ['TRADE'] }), pressure_response_efficiency: M('pressure_response_efficiency', 'pressure', 'MARKET_PRESSURE_RESPONSE_CHANGE', { inputKinds: ['TRADE', 'BOOK_SNAPSHOT'], native: ['TRADE', 'BOOK_SNAPSHOT'], nativeOf: (o) => o.kind, summary: true }) },
  DISPLAYED_LIQUIDITY: { spread_bps: M('spread_bps', 'book', 'MARKET_BOOK_CONTEXT', { inputKinds: ['BOOK_SNAPSHOT'], summary: true }), depth_bands: M('spread_bps', 'book', 'MARKET_BOOK_CONTEXT', { inputKinds: ['BOOK_SNAPSHOT'] }), band_imbalance: M('spread_bps', 'book', 'MARKET_BOOK_CONTEXT', { inputKinds: ['BOOK_SNAPSHOT'] }), microprice: M('spread_bps', 'book', 'MARKET_BOOK_CONTEXT', { inputKinds: ['BOOK_SNAPSHOT'] }), book_walk: M('round_trip_loss', 'exit', 'MARKET_DISPLAYED_EXIT_LIQUIDITY_CHANGE', { inputKinds: ['BOOK_SNAPSHOT'] }), round_trip_loss: M('round_trip_loss', 'exit', 'MARKET_DISPLAYED_EXIT_LIQUIDITY_CHANGE', { inputKinds: ['BOOK_SNAPSHOT'], pick: (comps) => comps.filter((c) => c.metricId === 'round_trip_loss').sort((a, b) => a.value.quoteNotional - b.value.quoteNotional)[0] ?? null, summary: true }), liquidity_haircut: M('round_trip_loss', 'exit', 'MARKET_DISPLAYED_EXIT_LIQUIDITY_CHANGE', { inputKinds: ['BOOK_SNAPSHOT'] }), micro_projection: M(null, null, 'MARKET_MICRO_CONTEXT', { inputKinds: ['BOOK_SNAPSHOT'], unsupported: 'an owner projection of the live Tape microstructure (MARKET_MICRO_CONTEXT), never a context component' }) },
  CROSS_VENUE: { venue_mid_dispersion: M('venue_mid_dispersion', 'dispersion', 'MARKET_MULTI_VENUE_CONTEXT', { inputKinds: ['BOOK_SNAPSHOT'], summary: true }), first_observed_change: M('venue_mid_dispersion', 'dispersion', 'MARKET_MULTI_VENUE_CONTEXT', { inputKinds: ['BOOK_SNAPSHOT'] }), peer_relative_move: M('peer_relative_move', 'peers', 'MARKET_PEER_RELATIVE_MOVE', { inputKinds: ['TRADE'], summary: true }) },
  DERIVATIVES_FUNDING_OI: { basis_bps: M('basis_bps', 'derivatives', 'MARKET_DERIVATIVES_CONTEXT', { inputKinds: ['DERIVATIVE_TICK'], pick: (comps) => comps.find((c) => c.metricId === 'basis_bps' && c.value?.marketType === 'PERPETUAL') ?? comps.find((c) => c.metricId === 'basis_bps') ?? null, summary: true }), oi_change: M('basis_bps', 'derivatives', 'MARKET_DERIVATIVES_CONTEXT', { inputKinds: ['DERIVATIVE_TICK'] }), funding_native: M('basis_bps', 'derivatives', 'MARKET_DERIVATIVES_CONTEXT', { inputKinds: ['DERIVATIVE_TICK'] }), dated_basis: M('basis_bps', 'derivatives', 'MARKET_DERIVATIVES_CONTEXT', { inputKinds: ['DERIVATIVE_TICK'], pick: (comps) => comps.find((c) => c.metricId === 'basis_bps' && c.value?.marketType === 'FUTURE') ?? null }) },
  LIQUIDATIONS: { liquidation_notional_by_side: M('liquidation_notional_by_side', 'liquidations', 'MARKET_LIQUIDATIONS_CONTEXT', { inputKinds: ['LIQUIDATION'], pick: (comps) => comps.find((c) => c.metricId === 'liquidation_notional_by_side' && (c.windowEndTs - c.windowStartTs) === 3_600_000) ?? comps.find((c) => c.metricId === 'liquidation_notional_by_side') ?? null, summary: true }) },
  OPTIONS_TERM_SKEW: { atm_iv_term: M('atm_iv_term', 'options', 'MARKET_OPTIONS_CONTEXT', { inputKinds: ['OPTION_TICK'], summary: true }), risk_reversal_25d: M('atm_iv_term', 'options', 'MARKET_OPTIONS_CONTEXT', { inputKinds: ['OPTION_TICK'] }), butterfly_25d: M('atm_iv_term', 'options', 'MARKET_OPTIONS_CONTEXT', { inputKinds: ['OPTION_TICK'] }), put_call_oi_ratio: M('atm_iv_term', 'options', 'MARKET_OPTIONS_CONTEXT', { inputKinds: ['OPTION_TICK'] }), put_call_volume_ratio: M('atm_iv_term', 'options', 'MARKET_OPTIONS_CONTEXT', { inputKinds: ['OPTION_TICK'] }), iv_bid_ask_spread: M('atm_iv_term', 'options', 'MARKET_OPTIONS_CONTEXT', { inputKinds: ['OPTION_TICK'] }) },
  SUPPLY_UNLOCKS: { supply_ratios: M('supply_ratios', 'supply', 'MARKET_SUPPLY_UNLOCKS', { inputKinds: ['ASSET_REFERENCE'], summary: true }), unlock_schedule: M('unlock_schedule', 'supply', 'MARKET_SUPPLY_UNLOCKS', { inputKinds: ['UNLOCK_EVENT'] }), next_unlock: M('unlock_schedule', 'supply', 'MARKET_SUPPLY_UNLOCKS', { inputKinds: ['UNLOCK_EVENT'] }) },
  DEX_DEFI: { pool_liquidity: M('pool_liquidity', 'dex', 'MARKET_DEX_DEFI_CONTEXT', { inputKinds: ['DEX_POOL'], summary: true }), pool_activity: M('pool_liquidity', 'dex', 'MARKET_DEX_DEFI_CONTEXT', { inputKinds: ['DEX_POOL'] }), protocol_tvl: M('protocol_tvl', 'dex', 'MARKET_DEX_DEFI_CONTEXT', { inputKinds: ['DEFI_METRIC'], native: ['protocol_tvl'], nativeOf: (o) => (/tvl/.test(o.payload.metricId) ? 'protocol_tvl' : o.payload.metricId) }), protocol_fees_revenue: M('protocol_fees_revenue', 'dex', 'MARKET_DEX_DEFI_CONTEXT', { inputKinds: ['DEFI_METRIC'], native: ['protocol_fees_revenue'], nativeOf: (o) => (/fee|revenue/.test(o.payload.metricId) ? 'protocol_fees_revenue' : o.payload.metricId) }), lending_rates: M('lending_rates', 'dex', 'MARKET_DEX_DEFI_CONTEXT', { inputKinds: ['DEFI_METRIC'], native: ['lending_rates'], nativeOf: (o) => (/apy/.test(o.payload.metricId) ? 'lending_rates' : o.payload.metricId) }) },
  ONCHAIN_ENTITY_FLOW: { exchange_net_flow: M('exchange_net_flow', 'onchain', 'MARKET_ONCHAIN_CONTEXT', { inputKinds: ['ONCHAIN_METRIC'], native: ['exchange_inflow', 'exchange_outflow'], nativeOf: onchainNative, summary: true }), exchange_reserve: M('exchange_reserve', 'onchain', 'MARKET_ONCHAIN_CONTEXT', { inputKinds: ['ONCHAIN_METRIC'], native: ['exchange_reserve'], nativeOf: onchainNative }), holder_cohorts: M('holder_cohorts', 'onchain', 'MARKET_ONCHAIN_CONTEXT', { inputKinds: ['ONCHAIN_METRIC'], native: ['holder_age_cohort'], nativeOf: onchainNative }) },
  NETWORK_ACTIVITY: { active_addresses: M('active_addresses', 'network', 'MARKET_NETWORK_CONTEXT', { inputKinds: ['ONCHAIN_METRIC'], native: ['active_addresses'], nativeOf: onchainNative, summary: true }), transaction_count: M('transaction_count', 'network', 'MARKET_NETWORK_CONTEXT', { inputKinds: ['ONCHAIN_METRIC'], native: ['transaction_count'], nativeOf: onchainNative }), transfer_volume: M('transfer_volume', 'network', 'MARKET_NETWORK_CONTEXT', { inputKinds: ['ONCHAIN_METRIC'], native: ['transfer_volume'], nativeOf: onchainNative }), network_fees: M('network_fees', 'network', 'MARKET_NETWORK_CONTEXT', { inputKinds: ['ONCHAIN_METRIC'], native: ['fees_total'], nativeOf: onchainNative }), realized_value_metrics: M('realized_value_metrics', 'network', 'MARKET_NETWORK_CONTEXT', { inputKinds: ['ONCHAIN_METRIC'], native: ['mvrv', 'sopr', 'realized_price'], nativeOf: onchainNative, anyNative: true }) },
  STABLECOIN_LIQUIDITY: { stablecoin_supply_change: M('stablecoin_supply_change', 'stable', 'MARKET_STABLECOIN_CONTEXT', { inputKinds: ['STABLECOIN_METRIC'], native: ['circulating_supply'], nativeOf: onchainNative, scope: 'GLOBAL', pick: (comps) => comps.find((c) => c.metricId === 'stablecoin_supply_change' && c.value?.chain === null) ?? comps.find((c) => c.metricId === 'stablecoin_supply_change') ?? null, summary: true }), peg_deviation: M('stablecoin_supply_change', 'stable', 'MARKET_STABLECOIN_CONTEXT', { inputKinds: ['STABLECOIN_METRIC'], native: ['peg_price'], nativeOf: onchainNative, scope: 'GLOBAL' }) },
  ETF_FLOWS: { etf_daily_flow: M('etf_daily_flow', 'etf', 'MARKET_ETF_CONTEXT', { inputKinds: ['ETF_FLOW'], summary: true }), etf_flow_trailing: M('etf_daily_flow', 'etf', 'MARKET_ETF_CONTEXT', { inputKinds: ['ETF_FLOW'] }) },
  MACRO_RELEASES: { macro_level: M('macro_level', 'macro', 'MARKET_MACRO_CONTEXT', { inputKinds: ['MACRO_OBSERVATION'], scope: 'GLOBAL', summary: true }), macro_change: M('macro_level', 'macro', 'MARKET_MACRO_CONTEXT', { inputKinds: ['MACRO_OBSERVATION'], scope: 'GLOBAL' }), macro_surprise: M('macro_surprise', 'macro', 'MARKET_MACRO_CONTEXT', { inputKinds: ['ECONOMIC_EVENT'], scope: 'GLOBAL' }), release_schedule: M('macro_surprise', 'macro', 'MARKET_MACRO_CONTEXT', { inputKinds: ['ECONOMIC_EVENT'], scope: 'GLOBAL' }) },
  CROSS_ASSET: { cross_asset_return: M('cross_asset_return', 'cross', 'MARKET_CROSS_ASSET_CONTEXT', { inputKinds: ['CROSS_ASSET_BAR'], scope: 'GLOBAL', summary: true }), pearson_correlation: M('cross_asset_return', 'cross', 'MARKET_CROSS_ASSET_CONTEXT', { inputKinds: ['CROSS_ASSET_BAR', 'CANDLE'], native: ['CROSS_ASSET_BAR', 'CANDLE'], nativeOf: (o) => o.kind, scope: 'SUBJECT' }) },
  OFFICIAL_SOCIAL_EVENTS: { event_references: M('event_references', 'events', 'MARKET_EVENT_CONTEXT', { inputKinds: ['EVENT_REFERENCE'], summary: true }) },
  INFRASTRUCTURE_STATUS: { provider_status: M('provider_status', 'infra', 'MARKET_INFRA_CONTEXT', { inputKinds: ['PROVIDER_STATUS', 'EVENT_REFERENCE'], scope: 'GLOBAL', summary: true }) },
});
// broker satisfaction of ONE observation against a metric mapping: kind, native id and a value-bearing payload
export function metricInputMatch(m, o) {
  if (!m.inputKinds.includes(o.kind)) return { ok: false, reason: 'KIND' };
  if (m.native && m.nativeOf && o.kind === 'ONCHAIN_METRIC' || (m.native && o.kind === 'STABLECOIN_METRIC')) { const n = m.nativeOf(o); if (!m.native.includes(n)) return { ok: false, reason: 'NATIVE' }; }
  if (m.native && o.kind === 'DEFI_METRIC') { const n = m.nativeOf(o); if (!m.native.includes(n)) return { ok: false, reason: 'NATIVE' }; }
  if (!o.payload || !VALUE_BEARING(o.kind, o.payload) || ['MISSING', 'UNAVAILABLE', 'FAILED', 'NOT_SUPPORTED'].includes(o.quality?.state)) return { ok: false, reason: 'VALUE_NULL' };
  return { ok: true };
}
// every registered metric has a mapping (audited by MC-J03); every mapping names a closed kind
for (const f of FAMILIES) for (const id of Object.keys(FAMILY_REGISTRY[f].metrics)) { if (!METRIC_MAP[f]?.[id]) throw new Error(`METRIC_MAP: ${f}.${id} unmapped`); if (!MARKET_EVIDENCE_KINDS.includes(METRIC_MAP[f][id].kind)) throw new Error(`METRIC_MAP: ${f}.${id} names an unknown kind`); }
export const metricMapping = (family, metricId) => METRIC_MAP[family]?.[metricId] ?? null;
// the components that carry a metric (by the mapping's component id) and the typed value for one component
export const componentsFor = (ctx, family, metricId) => { const m = metricMapping(family, metricId); if (!m || !m.component) return []; return (ctx.families[family]?.components ?? []).filter((c) => c.metricId === m.component); };
export function buildValue(ctx, family, metricId, comp, comps) { const m = metricMapping(family, metricId); if (!m || !m.build || !comp) return null; return BUILD[m.build](ctx, comp, comps); }
// the DEFAULT family summaries: one per family (first summary metric that has a component), plus the independent H03 exit
// liquidity and H02 multi-venue descriptors, so the intended measurements are visible without a detail request
function defaultSummaries(ctx, family, comps) {
  const out = []; const summaryMetrics = Object.entries(METRIC_MAP[family]).filter(([, m]) => m.summary);
  for (const [metricId, m] of summaryMetrics) { const pool = comps.filter((c) => c.metricId === m.component); const comp = m.pick ? m.pick(comps) : pool[0] ?? null; if (!comp) continue; if (out.some((x) => x.comp === comp)) continue; const built = BUILD[m.build](ctx, comp, comps); if (built) out.push({ ...built, metricId }); }
  return out;
}
// the providers behind a family's components: its coverage records, value-level provider / venue / instrument facts and, for the
// cross-venue derivations (dispersion over venue mids, first-observed changes, peer cohorts), the venues named inside the value
const venueSet = (v, set) => { if (typeof v === 'string' && VENUE_PROVIDER[v]) set.add(VENUE_PROVIDER[v]); };
const providersOf = (ctx, family) => { const set = new Set(); for (const c of ctx.families[family]?.coverage ?? []) set.add(c.provider); for (const comp of ctx.families[family]?.components ?? []) { const p = comp.value?.provider; if (typeof p === 'string' && /^[A-Z_]+$/.test(p)) set.add(p); venueSet(comp.value?.venue, set); const inst = comp.value?.instrument; if (typeof inst === 'string') venueSet(inst.split(':')[0], set); for (const x of comp.value?.dispersion?.venues ?? []) venueSet(x?.venue, set); for (const x of comp.value?.firstObservedChanges?.sequence ?? []) venueSet(x?.venue, set); }
  if (family === 'CROSS_VENUE' && !set.size) for (const f of ['DISPLAYED_LIQUIDITY', 'SPOT_PRICE_CHART']) for (const p of providersOf(ctx, f)) set.add(p); // a peer cohort is derived from the subject's own trade / book providers
  return [...set].sort(); };

export function buildResearchEvidenceV2({ marketContext = null, socialProjection = null, asOfTs, trigger, mode = 'LIVE_OBSERVATION', entrances = null, detailRequests = [], microProjection = null, providerSymbols = null, coverageLimitations = [] }) {
  if (!isTs(asOfTs)) return { ok: false, reason: 'INVALID_INPUT', detail: 'asOfTs required' };
  if (!RESEARCH_MODES.includes(mode)) return { ok: false, reason: 'INVALID_INPUT', detail: 'unknown mode' };
  if (!trigger || !TRIGGER_KINDS_V2.includes(trigger.kind)) return { ok: false, reason: 'INVALID_INPUT', detail: 'trigger kind outside the closed set' };
  if (marketContext !== null) { const e = contextError(marketContext); if (e) return { ok: false, reason: 'INVALID_INPUT', detail: e }; if (marketContext.asOfTs > asOfTs) return { ok: false, reason: 'INVALID_INPUT', detail: 'market context as-of after the packet as-of' }; }
  if (socialProjection !== null) { const e = socialProjectionError(socialProjection); if (e) return { ok: false, reason: 'INVALID_INPUT', detail: e }; if (marketContext && socialProjection.asOfTs !== marketContext.asOfTs) return { ok: false, reason: 'INVALID_INPUT', detail: 'the Social projection must be read at the market context as-of' }; if (socialProjection.asOfTs > asOfTs) return { ok: false, reason: 'INVALID_INPUT', detail: 'social projection after the packet as-of' }; }
  const canonicalCoin = marketContext?.canonicalCoin ?? socialProjection?.canonicalCoin ?? null;
  if (marketContext && socialProjection && marketContext.canonicalCoin !== socialProjection.canonicalCoin) return { ok: false, reason: 'INVALID_INPUT', detail: 'market and social subjects disagree' };
  if (canonicalCoin === null) return { ok: false, reason: 'INVALID_INPUT', detail: 'an empty packet still needs a subject: supply trigger.canonicalCoin', hint: 'use buildEmptyResearchPacket' };
  if (!Array.isArray(detailRequests) || detailRequests.some((d) => !d || !FAMILIES.includes(d.family) || (d.metricId !== undefined && d.metricId !== null && !FAMILY_REGISTRY[d.family].metrics[d.metricId]))) return { ok: false, reason: 'INVALID_INPUT', detail: 'detail request names an unregistered family / metric' };
  const limitations = new Set(coverageLimitations.filter((x) => COVERAGE_LIMITATION_REASONS.includes(x)));
  const sources = new Map(); const contextMap = { evidenceToComponent: {}, omitted: { detail: [], unsupported: [], counts: { families: 0, components: 0 } }, admissionRecipe: ADMISSION_RECIPE };
  const addSource = (provider, sourceType, retrievedTs, locator) => { if (sources.has(provider)) return sources.get(provider).sourceId; const s = { sourceId: 'src-x', provider, sourceType, authorityClass: 'ESTABLISHED', publishedTs: null, retrievedTs: Math.min(retrievedTs, asOfTs), locator, excerpt: null }; s.sourceId = sourceIdentity(s); sources.set(provider, s); return s.sourceId; };
  const missing = []; const providerCoverage = new Map();
  const summaryItems = []; const detailItems = []; const admittedComponents = new Set();
  const itemOf = (ctx, family, built, state, tag) => { const value = fit(built.value); if (!value) return { error: 'FIT' }; const te = typedValueError(value.kind, value, { asOfTs, canonicalCoin }); if (te) return { error: te }; const item = { evidenceId: 'evd-x', sense: 'MARKET', kind: value.kind, state, knownAtTs: value.knownAtTs, observedTs: value.observedTs, value, sourceRefs: providersOf(ctx, family).map((p) => addSource(p, PROVIDER_SOURCE_TYPE(p), value.knownAtTs, `market-lab:${p}`)).sort(), claimRefs: [], provenance: `mlab:${ctx.contextId.slice(5, 21)}:${built.comp.componentId}${tag}` }; item.evidenceId = evidenceIdentity(item); return { item }; };
  if (marketContext) {
    const ctx = marketContext;
    for (const family of FAMILIES) {
      const f = ctx.families[family]; if (!f) continue;
      for (const c of f.coverage) { const prev = providerCoverage.get(c.provider); const st = c.state === 'OBSERVED' || c.state === 'SUBSCRIBED' ? 'OBSERVED' : c.state === 'ACCESS_BLOCKED' ? 'UNAVAILABLE' : c.state === 'NOT_SUPPORTED' ? 'NOT_SUPPORTED' : c.state === 'NOT_QUERIED' ? 'NOT_QUERIED' : c.state === 'GAP' || c.state === 'DROPPED' || c.state === 'EVICTED' ? 'STALE' : 'FAILED'; if (!prev || prev.state !== 'OBSERVED') providerCoverage.set(c.provider, { provider: c.provider, state: st, checkedTs: st === 'NOT_QUERIED' ? null : Math.min(c.endTs ?? c.startTs, asOfTs), detail: c.reasonCodes.length ? c.reasonCodes.join(',').slice(0, 200) : null }); }
      const provs = providersOf(ctx, family); const built = defaultSummaries(ctx, family, f.components);
      if (!built.length) { missing.push({ kind: family, description: `${family}: ${f.state} — no admissible component at the as-of` }); limitations.add(f.state === 'NOT_QUERIED' ? 'FAMILY_NOT_QUERIED' : f.state === 'NOT_SUPPORTED' ? 'FAMILY_NOT_SUPPORTED' : 'FAMILY_MISSING'); contextMap.omitted.counts.families += 1;
        const st = f.state === 'NOT_SUPPORTED' ? 'UNAVAILABLE' : 'MISSING'; const kind = Object.values(METRIC_MAP[family]).find((m) => m.summary).kind; const item = { evidenceId: 'evd-x', sense: 'MARKET', kind, state: st, knownAtTs: ctx.asOfTs, observedTs: null, value: null, sourceRefs: provs.map((p) => addSource(p, PROVIDER_SOURCE_TYPE(p), ctx.asOfTs, `market-lab:${p}`)).sort(), claimRefs: [], provenance: `mlab:${ctx.contextId.slice(5, 21)}:${family}:${f.state}` }; item.evidenceId = evidenceIdentity(item); summaryItems.push(item); continue; }
      for (const b of built) {
        if (f.state === 'PARTIAL' || b.comp.support?.state === 'PARTIAL' || b.comp.support?.state === 'STALE') limitations.add('FAMILY_PARTIAL');
        if (family === 'CROSS_VENUE' && b.comp.support?.state === 'INSUFFICIENT_PEERS') limitations.add('PEER_COHORT_INSUFFICIENT');
        if (family === 'SPOT_FLOW' && (b.comp.support?.reasons ?? []).includes('BOOK_ENDPOINTS_INCOMPLETE')) limitations.add('BOOK_ENDPOINTS_INCOMPLETE');
        if (family === 'OPTIONS_TERM_SKEW' && b.value.fields.censusComplete === false) limitations.add('OPTIONS_CENSUS_PARTIAL');
        if (family === 'SPOT_PRICE_CHART' && /UNKNOWN_COVERAGE|PARTIAL/.test(String(b.comp.support?.state))) limitations.add('FAMILY_PARTIAL');
        const st = stateOf(b.comp.support, f.state);
        if (st === 'MISSING' && ABSENT_SUPPORT.has(b.comp.support?.state)) { const item = { evidenceId: 'evd-x', sense: 'MARKET', kind: b.value.kind, state: 'MISSING', knownAtTs: ctx.asOfTs, observedTs: null, value: null, sourceRefs: provs.map((p) => addSource(p, PROVIDER_SOURCE_TYPE(p), ctx.asOfTs, `market-lab:${p}`)).sort(), claimRefs: [], provenance: `mlab:${ctx.contextId.slice(5, 21)}:${b.comp.componentId}:${b.comp.support.state}` }; item.evidenceId = evidenceIdentity(item); summaryItems.push(item); contextMap.evidenceToComponent[item.evidenceId] = b.comp.componentId; admittedComponents.add(b.comp.componentId); limitations.add('FAMILY_PARTIAL'); continue; } // an absent input is a MISSING item with value null, never KNOWN with null fields
        const r = itemOf(ctx, family, b, st, ''); if (r.error === 'FIT') return { ok: false, reason: 'PACKET_LIMIT_EXCEEDED', detail: `${family}: mandatory summary cannot fit the per-value bound` }; if (r.error) return { ok: false, reason: 'INVALID_INPUT', detail: `${family}: ${r.error}` };
        summaryItems.push(r.item); contextMap.evidenceToComponent[r.item.evidenceId] = b.comp.componentId; admittedComponents.add(b.comp.componentId);
      }
      // every component not carried by a default summary is detail (omitted until requested); reconciled after admission
      for (const other of f.components) if (!admittedComponents.has(other.componentId)) contextMap.omitted.detail.push({ family, metricId: other.metricId, componentId: other.componentId, subjectId: other.subjectId, reason: 'DETAIL_NOT_REQUESTED' });
    }
    if (microProjection) { const mv = { kind: 'MARKET_MICRO_CONTEXT', canonicalCoin, asOfTs: ctx.asOfTs, windowStartTs: null, windowEndTs: null, observedTs: microProjection.observedTs, knownAtTs: microProjection.knownAtTs, recipe: null, support: { state: 'OWNER_PROJECTION', reasons: [], completeness: null }, units: {}, sourceIds: [String(microProjection.sourceId)], fields: { venue: 'kraken', absorption: microProjection.absorption ?? null, depletion: microProjection.depletion ?? null, recovery: microProjection.recovery ?? null, flowResponse: microProjection.flowResponse ?? null, attribution: 'AGGREGATE_L2_UNATTRIBUTED', proxyLabels: microProjection.proxyLabels ?? [] } }; const te = typedValueError('MARKET_MICRO_CONTEXT', mv, { asOfTs, canonicalCoin }); if (!te) { const item = { evidenceId: 'evd-x', sense: 'MICRO', kind: 'MARKET_MICRO_CONTEXT', state: 'KNOWN', knownAtTs: mv.knownAtTs, observedTs: mv.observedTs, value: mv, sourceRefs: [addSource('KRAKEN_SPOT', 'MARKET_DATA', mv.knownAtTs, 'market-lab:KRAKEN_SPOT')], claimRefs: [], provenance: `tape-micro:${microProjection.sourceId}` }; item.evidenceId = evidenceIdentity(item); summaryItems.push(item); } }
    // explicit DETAIL admission through the closed mapping (canonical order: family, metric, subject), until bounds bind; a
    // requested metric with no mapped component in this context is an EXPLICIT unsupported omission, never "omitted by bounds"
    const wanted = []; for (const d of detailRequests) { if (d.metricId === undefined || d.metricId === null) { for (const id of Object.keys(METRIC_MAP[d.family])) wanted.push({ family: d.family, metricId: id }); } else wanted.push({ family: d.family, metricId: d.metricId }); }
    const seenCandidates = new Set();
    for (const w of wanted.sort((a, b) => FAMILIES.indexOf(a.family) - FAMILIES.indexOf(b.family) || (a.metricId < b.metricId ? -1 : a.metricId > b.metricId ? 1 : 0))) {
      const m = METRIC_MAP[w.family][w.metricId]; if (!m.component) { contextMap.omitted.unsupported.push({ family: w.family, metricId: w.metricId, reason: 'NO_COMPONENT_RECIPE' }); continue; }
      const comps = componentsFor(ctx, w.family, w.metricId).sort((a, b) => ((a.subjectId ?? '') < (b.subjectId ?? '') ? -1 : (a.subjectId ?? '') > (b.subjectId ?? '') ? 1 : (a.windowEndTs ?? 0) - (b.windowEndTs ?? 0)));
      if (!comps.length) { contextMap.omitted.unsupported.push({ family: w.family, metricId: w.metricId, reason: 'NO_COMPONENT_IN_CONTEXT' }); continue; }
      for (const comp of comps) { if (admittedComponents.has(comp.componentId) || seenCandidates.has(comp.componentId)) continue; seenCandidates.add(comp.componentId); if (ABSENT_SUPPORT.has(comp.support?.state)) { const d = contextMap.omitted.detail.find((x) => x.componentId === comp.componentId); if (d) d.reason = 'NO_COMPONENT_IN_CONTEXT'; continue; } const built = BUILD[m.build](ctx, comp, ctx.families[w.family].components); if (!built) continue; const r = itemOf(ctx, w.family, built, stateOf(comp.support, ctx.families[w.family].state), ':detail'); if (r.error) { const d = contextMap.omitted.detail.find((x) => x.componentId === comp.componentId); if (d) d.reason = 'INVALID'; continue; } if (summaryItems.some((s) => s.evidenceId === r.item.evidenceId) || detailItems.some((s) => s.item.evidenceId === r.item.evidenceId)) continue; detailItems.push({ item: r.item, componentId: comp.componentId, metricId: w.metricId, family: w.family }); }
    }
  } else limitations.add('MARKET_CONTEXT_ABSENT');
  // Social projection
  let socialItems = []; let dossierRef = null; const historyRefs = []; let socialEntrances = null;
  if (socialProjection) { const p = projectSocial(socialProjection, { asOfTs }); if (!p.ok) return { ok: false, reason: 'INVALID_INPUT', detail: p.error }; for (const l of p.limitations) limitations.add(l); socialEntrances = p.entrances; for (const s of p.sources) addSource(s.provider, s.sourceType, s.retrievedTs, s.locator); for (const it of p.items) { const item = { evidenceId: 'evd-x', sense: 'RUMINT', kind: it.kind, state: it.state, knownAtTs: it.knownAtTs, observedTs: it.observedTs, value: it.value, sourceRefs: it.sourceProviders.map((pr) => sources.get(pr)?.sourceId).filter(Boolean).sort(), claimRefs: [], provenance: it.provenanceKey }; item.evidenceId = evidenceIdentity(item); socialItems.push(item); if (it.kind === 'SOCIAL_DOSSIER_CONTEXT') dossierRef = item.evidenceId; else if (historyRefs.length < 8) historyRefs.push(item.evidenceId); } if (socialProjection.coverage.state !== 'AVAILABLE') missing.push({ kind: 'SOCIAL_DOSSIER', description: `Social coverage ${socialProjection.coverage.state}: ${socialProjection.coverage.reason ?? 'no reason recorded'}` }); }
  else limitations.add('SOCIAL_PROJECTION_ABSENT');
  if (mode === 'REPLAY_AS_OF') limitations.add('REPLAY_NETWORK_OFF');
  const entrancesFinal = entrances ?? (trigger.kind === 'MARKET_RESEARCH' ? ['MARKET_LED'] : socialEntrances ?? ['MARKET_LED']);
  // the market summary is computed over the FINAL admitted market items (components first, summary next): it is built per trial
  const summaryOf = (marketItems, omittedCount) => { if (!marketContext) return null; const components = marketItems.map((i) => i.evidenceId).sort(); if (components.length > MAX_COMPONENT_IDS) return { error: 'more mandatory components than the summary can bind' }; const value = { kind: 'MARKET_CONTEXT_SUMMARY', canonicalCoin, asOfTs: marketContext.asOfTs, windowStartTs: null, windowEndTs: null, observedTs: marketContext.asOfTs, knownAtTs: marketContext.asOfTs, recipe: { recipeId: 'context', version: 1, recipeSetVersion: marketContext.recipeSetVersion }, support: { state: 'CONTEXT_SEALED', reasons: [], completeness: null }, units: {}, sourceIds: [marketContext.contextId], fields: { contextId: marketContext.contextId, recipeSetVersion: marketContext.recipeSetVersion, captureBundleId: marketContext.captureRef?.bundleId ?? marketContext.captureRef?.prefixId ?? null, familyStates: Object.fromEntries(FAMILIES.filter((f) => marketContext.families[f]).map((f) => [f, marketContext.families[f].state])), componentIds: components, omittedDetail: { count: omittedCount, familiesWithoutSummary: contextMap.omitted.counts.families }, resourceState: marketContext.resourceState ?? null } }; const te = typedValueError('MARKET_CONTEXT_SUMMARY', value, { asOfTs, canonicalCoin }); if (te) return { error: te }; const summary = { evidenceId: 'evd-x', sense: 'MARKET', kind: 'MARKET_CONTEXT_SUMMARY', state: 'KNOWN', knownAtTs: marketContext.asOfTs, observedTs: marketContext.asOfTs, value, sourceRefs: [...sources.values()].filter((s) => s.sourceType !== 'SOCIAL_ACCOUNT' && s.provider !== 'rumor2-research').map((s) => s.sourceId).sort().slice(0, 16), claimRefs: [], provenance: `mlab:${marketContext.contextId.slice(5, 21)}:summary` }; summary.evidenceId = evidenceIdentity(summary); return { summary }; };
  const assemble = (marketItems, omittedCount) => { const s = summaryOf(marketItems, omittedCount); if (s?.error) return { error: s.error }; const items = [...marketItems, ...(s ? [s.summary] : []), ...socialItems]; const packet = { schemaVersion: EVIDENCE_SCHEMA_VERSION_2, packetId: 'sep2-x', asOfTs, subject: { canonicalCoin, providerSymbols: providerSymbols ?? null }, trigger: { kind: trigger.kind, sourceEventId: trigger.sourceEventId ?? null, observedTs: trigger.observedTs ?? null }, claims: [], sources: [...sources.values()].sort((a, b) => (a.sourceId < b.sourceId ? -1 : 1)), evidence: items, claimLinks: [], providerCoverage: [...providerCoverage.values()].sort((a, b) => (a.provider < b.provider ? -1 : 1)).slice(0, 64), contradictions: [], missingEvidence: missing.sort((a, b) => (a.kind < b.kind ? -1 : 1)), analogs: [], security: { untrustedTextPresent: items.some((e) => e.kind === 'MARKET_EVENT_CONTEXT' && Array.isArray(e.value?.fields?.events) && e.value.fields.events.some((x) => x.headline !== null && x.headline !== undefined)) }, researchContext: { mode, entrances: [...new Set(entrancesFinal)].filter((e) => RESEARCH_ENTRANCES.includes(e)), dossierRef, marketContextRef: s ? s.summary.evidenceId : null, sourceHistoryRefs: historyRefs, coverageLimitations: [...limitations].sort(), authority: 'NONE', purpose: 'RESEARCH_ONLY' } }; packet.packetId = packetIdentityV2(packet); return { packet, summary: s?.summary ?? null }; };
  const mandatoryCount = summaryItems.length + (marketContext ? 1 : 0) + socialItems.length;
  if (mandatoryCount > MAX_EVIDENCE || sources.size > MAX_SOURCES) return { ok: false, reason: 'PACKET_LIMIT_EXCEEDED', detail: `mandatory items ${mandatoryCount} / sources ${sources.size} exceed the bounds` };
  const pendingOmitted = () => contextMap.omitted.detail.filter((d) => d.reason !== 'ADMITTED').length;
  if (contextMap.omitted.detail.length) limitations.add('DETAIL_OMITTED_BY_BOUNDS');
  let current = assemble(summaryItems, pendingOmitted()); if (current.error) return { ok: false, reason: 'PACKET_LIMIT_EXCEEDED', detail: current.error };
  let check = validateEvidencePacketV2(current.packet);
  if (!check.valid) { const overflow = check.reasons.some((r) => /exceeds/.test(r)); return { ok: false, reason: overflow ? 'PACKET_LIMIT_EXCEEDED' : 'VALIDATION_FAILURE', detail: check.reasons.slice(0, 5) }; }
  const admitted = [];
  for (const d of detailItems) {
    const entry = contextMap.omitted.detail.find((x) => x.componentId === d.componentId);
    if (mandatoryCount + admitted.length + 1 > MAX_EVIDENCE) { if (entry) entry.reason = 'EVIDENCE_CAP'; continue; }
    const trialOmitted = pendingOmitted() - (entry ? 1 : 0); const trial = assemble([...summaryItems, ...admitted, d.item], trialOmitted); if (trial.error) { if (entry) entry.reason = 'EVIDENCE_CAP'; continue; }
    const c = validateEvidencePacketV2(trial.packet); if (!c.valid) { if (entry) entry.reason = c.reasons.some((r) => /exceeds/.test(r)) ? 'PACKET_BYTE_CAP' : 'INVALID'; continue; }
    current = trial; admitted.push(d.item); contextMap.evidenceToComponent[d.item.evidenceId] = d.componentId; if (entry) entry.reason = 'ADMITTED';
  }
  // reconcile AFTER admission: the omission list, its counts and the limitation reflect exactly what the final packet carries
  contextMap.omitted.detail = contextMap.omitted.detail.filter((d) => d.reason !== 'ADMITTED'); contextMap.omitted.counts.components = contextMap.omitted.detail.length;
  if (!contextMap.omitted.detail.length) limitations.delete('DETAIL_OMITTED_BY_BOUNDS');
  const final = assemble([...summaryItems, ...admitted], contextMap.omitted.detail.length); if (final.error) return { ok: false, reason: 'PACKET_LIMIT_EXCEEDED', detail: final.error };
  const fv = validateEvidencePacketV2(final.packet); if (!fv.valid) return { ok: false, reason: fv.reasons.some((r) => /exceeds/.test(r)) ? 'PACKET_LIMIT_EXCEEDED' : 'VALIDATION_FAILURE', detail: fv.reasons.slice(0, 5) };
  const packet = final.packet; const sourceIds = new Set(packet.sources.map((s) => s.sourceId));
  for (const e of packet.evidence) for (const ref of e.sourceRefs) if (!sourceIds.has(ref)) return { ok: false, reason: 'VALIDATION_FAILURE', detail: 'an evidence item names a source absent from the final packet' };
  return { ok: true, packet, contextMap: { packetId: packet.packetId, contextId: marketContext?.contextId ?? null, ...contextMap, admittedDetail: admitted.length, mandatoryItems: mandatoryCount, canonicalChars: canonicalJson(packet).length, utf8Bytes: Buffer.byteLength(canonicalJson(packet), 'utf8'), limits: { maxEvidence: MAX_EVIDENCE, maxChars: MAX_PACKET_CANONICAL_CHARS, maxBytes: MAX_PACKET_UTF8_BYTES } } };
}
// both inputs null: a valid, explicitly empty research packet for a named subject (never a forged observation)
export function buildEmptyResearchPacket({ canonicalCoin, asOfTs, trigger, mode = 'LIVE_OBSERVATION', entrances = ['MARKET_LED'] }) {
  const packet = { schemaVersion: EVIDENCE_SCHEMA_VERSION_2, packetId: 'sep2-x', asOfTs, subject: { canonicalCoin, providerSymbols: null }, trigger: { kind: trigger.kind, sourceEventId: trigger.sourceEventId ?? null, observedTs: trigger.observedTs ?? null }, claims: [], sources: [], evidence: [], claimLinks: [], providerCoverage: [], contradictions: [], missingEvidence: [{ kind: 'MARKET_CONTEXT', description: 'no market context was supplied' }, { kind: 'SOCIAL_DOSSIER', description: 'no Social projection was supplied' }], analogs: [], security: { untrustedTextPresent: false }, researchContext: { mode, entrances, dossierRef: null, marketContextRef: null, sourceHistoryRefs: [], coverageLimitations: ['MARKET_CONTEXT_ABSENT', 'SOCIAL_PROJECTION_ABSENT', ...(mode === 'REPLAY_AS_OF' ? ['REPLAY_NETWORK_OFF'] : [])].sort(), authority: 'NONE', purpose: 'RESEARCH_ONLY' } };
  packet.packetId = packetIdentityV2(packet); const v = validateEvidencePacketV2(packet); return v.valid ? { ok: true, packet, contextMap: { packetId: packet.packetId, contextId: null, evidenceToComponent: {}, omitted: { detail: [], unsupported: [], counts: { families: 0, components: 0 } }, admissionRecipe: ADMISSION_RECIPE, admittedDetail: 0, mandatoryItems: 0 } } : { ok: false, reason: 'VALIDATION_FAILURE', detail: v.reasons };
}
export { MARKET_EVIDENCE_KINDS, KIND_FAMILY, RECIPE_SET_VERSION };
