// EVIDENCE V2 — buildResearchEvidenceV2 (§9): ONE pure boundary that assembles the actual market/social dossier.
//   buildResearchEvidenceV2({ marketContext, socialProjection, asOfTs, trigger, mode, entrances, detailRequests })
// marketContext (a validated market-context-1) and socialProjection (a validated social-projection-1) may each be null
// but must validate when supplied; both null => a valid, explicitly EMPTY research packet (never a forged observation).
// Deterministic admission recipe: reserve one compact summary/status per required family in canonical family order,
// then the MARKET_CONTEXT_SUMMARY (components first, summary next, packet last), then Social items, then explicitly
// requested detail in canonical order until the bounds bind; omitted detail is recorded in the context map. Failure to
// fit the mandatory summaries returns PACKET_LIMIT_EXCEEDED with no packet — no family is silently dropped.
import { EVIDENCE_SCHEMA_VERSION_2, MARKET_EVIDENCE_KINDS, KIND_FAMILY, COVERAGE_LIMITATION_REASONS, TRIGGER_KINDS_V2, RESEARCH_MODES, RESEARCH_ENTRANCES, MAX_COMPONENT_IDS, MAX_EVIDENCE, MAX_SOURCES, MAX_PACKET_CANONICAL_CHARS, MAX_PACKET_UTF8_BYTES, canonicalJson, sourceIdentity, evidenceIdentity, packetIdentityV2, validateEvidencePacketV2, typedValueError } from './contract-v2.js';
import { contextError } from '../market-lab/context.js';
import { FAMILIES } from '../market-lab/contracts.js';
import { RECIPE_SET_VERSION } from '../market-lab/recipes.js';
import { projectSocial, socialProjectionError } from './social-projection.js';

export const ADMISSION_RECIPE = 'mandatory-summaries-then-explicit-detail-canonical-order-v1';
export const MAX_VALUE_CHARS = 4_096;
const FAMILY_KIND = Object.freeze({ SPOT_PRICE_CHART: 'MARKET_CHART_WINDOW', SPOT_FLOW: 'MARKET_PRESSURE_RESPONSE_CHANGE', DISPLAYED_LIQUIDITY: 'MARKET_BOOK_CONTEXT', CROSS_VENUE: 'MARKET_PEER_RELATIVE_MOVE', DERIVATIVES_FUNDING_OI: 'MARKET_DERIVATIVES_CONTEXT', LIQUIDATIONS: 'MARKET_LIQUIDATIONS_CONTEXT', OPTIONS_TERM_SKEW: 'MARKET_OPTIONS_CONTEXT', SUPPLY_UNLOCKS: 'MARKET_SUPPLY_UNLOCKS', DEX_DEFI: 'MARKET_DEX_DEFI_CONTEXT', ONCHAIN_ENTITY_FLOW: 'MARKET_ONCHAIN_CONTEXT', NETWORK_ACTIVITY: 'MARKET_NETWORK_CONTEXT', STABLECOIN_LIQUIDITY: 'MARKET_STABLECOIN_CONTEXT', ETF_FLOWS: 'MARKET_ETF_CONTEXT', MACRO_RELEASES: 'MARKET_MACRO_CONTEXT', CROSS_ASSET: 'MARKET_CROSS_ASSET_CONTEXT', OFFICIAL_SOCIAL_EVENTS: 'MARKET_EVENT_CONTEXT', INFRASTRUCTURE_STATUS: 'MARKET_INFRA_CONTEXT' });
const PROVIDER_SOURCE_TYPE = (p) => (['CRYPTOQUANT', 'SANTIMENT', 'COINMETRICS', 'GECKOTERMINAL', 'DEFILLAMA'].includes(p) ? 'ONCHAIN' : p === 'SETTLED_RECORDS' ? 'OTHER' : 'MARKET_DATA');
const VENUE_PROVIDER = { kraken: 'KRAKEN_SPOT', coinbase: 'COINBASE_SPOT', 'kraken-futures': 'KRAKEN_DERIVATIVES', deribit: 'DERIBIT', bybit: 'BYBIT', 'coinglass-aggregate': 'COINGLASS' };
const isTs = (v) => Number.isSafeInteger(v) && v > 0;
const num = (v) => (typeof v === 'number' && Number.isFinite(v) ? v : null);
const clip = (arr, n) => (Array.isArray(arr) ? arr.slice(0, n) : []);
// shrink a typed value deterministically until its canonical form fits the per-value cap (arrays first, longest first)
function fit(value) { let v = value; for (let round = 0; round < 12; round += 1) { if (canonicalJson(v).length <= MAX_VALUE_CHARS) return v; const f = { ...v.fields }; const arrays = Object.entries(f).filter(([, x]) => Array.isArray(x) && x.length > 0).sort((a, b) => b[1].length - a[1].length); if (!arrays.length) break; const [k, x] = arrays[0]; f[k] = x.slice(0, Math.max(0, Math.floor(x.length / 2))); v = { ...v, fields: f }; } return canonicalJson(v).length <= MAX_VALUE_CHARS ? v : null; }
const stateOf = (support, famState) => (famState === 'NOT_SUPPORTED' ? 'UNAVAILABLE' : famState === 'MISSING' || famState === 'NOT_QUERIED' ? 'MISSING' : support?.state === 'STALE' ? 'STALE' : 'KNOWN');
// ---- per-family compact summary from context components ---------------------------------------------------------------
function familyValue(family, ctx, comps) {
  const first = (metricId, pred = () => true) => comps.find((c) => c.metricId === metricId && pred(c)) ?? null;
  const base = (c, kind, fields, { units = {}, supportOverride = null } = {}) => ({ kind, canonicalCoin: ctx.canonicalCoin, asOfTs: ctx.asOfTs, windowStartTs: c?.windowStartTs ?? null, windowEndTs: c?.windowEndTs ?? null, observedTs: c ? (c.windowEndTs ?? c.inputKnownAtMax ?? null) : null, knownAtTs: c ? Math.min(ctx.asOfTs, Math.max(c.inputKnownAtMax ?? ctx.asOfTs, c.windowEndTs ?? 0)) : ctx.asOfTs, recipe: c ? { recipeId: c.recipeId, version: c.version, recipeSetVersion: ctx.recipeSetVersion } : null, support: supportOverride ?? { state: (c?.support?.state ?? 'NO_COMPONENT').replace(/[^A-Z0-9_]/g, '_').slice(0, 48), reasons: clip(c?.support?.reasons ?? [], 8).map((r) => String(r).replace(/[^A-Z0-9_:-]/g, '_').slice(0, 64)), completeness: null }, units, sourceIds: c ? [c.componentId] : [], fields });
  const v = (c) => c?.value ?? {};
  switch (family) {
    case 'SPOT_PRICE_CHART': { const c = first('window_ohlcv', (x) => x.value?.current?.windowMs === 60_000) ?? first('window_ohlcv'); if (!c) return null; const cur = v(c).current ?? {}; const prev = v(c).previous ?? {}; const ra = first('relative_activity', (x) => x.value?.venue === v(c).venue); const ind = first('indicators', (x) => x.value?.venue === v(c).venue && x.value?.intervalMs === 3_600_000) ?? first('indicators', (x) => x.value?.venue === v(c).venue); const iv = ind ? v(ind) : null;
      return { comp: c, extra: [ra, ind].filter(Boolean), value: base(c, 'MARKET_CHART_WINDOW', { venue: v(c).venue, quote: v(c).quote, windowMs: cur.windowMs ?? 60_000, open: cur.open, high: cur.high, low: cur.low, close: cur.close, vwap: cur.vwap, logReturn: cur.logReturn, quoteNotional: cur.quoteNotional, count: cur.count, relativeNotional: ra ? num(v(ra).notional?.ratio) : null, relativeRange: ra ? num(v(ra).range?.ratio) : null, indicators: iv ? { intervalMs: iv.intervalMs, closedBars: iv.closedBars, lastClose: iv.lastClose, sma: iv.sma, ema: iv.ema, rsi14: iv.rsi14, macd: iv.macd, bollinger20: iv.bollinger20, atr14: iv.atr14, prior20: iv.prior20, prior60: iv.prior60, realizedVolatility: iv.realizedVolatility, breakout: iv.breakout, capReached: iv.completeness?.capReached ?? null } : null, previous: { logReturn: prev.logReturn ?? null, quoteNotional: prev.quoteNotional ?? null, count: prev.count ?? null, close: prev.close ?? null } }, { units: { close: v(c).quote ?? 'QUOTE', quoteNotional: v(c).quote ?? 'QUOTE', logReturn: 'FRACTION' } }) }; }
    case 'SPOT_FLOW': { const c = first('pressure_response_efficiency'); if (!c) return null; const x = v(c); const p = x.previous ?? {}; const q = x.current ?? {}; return { comp: c, extra: [], value: base(c, 'MARKET_PRESSURE_RESPONSE_CHANGE', { venue: x.venue, quote: x.quote, previousSigned: p.signedNotional ?? null, currentSigned: q.signedNotional ?? null, previousResponseBps: p.responseBps ?? null, currentResponseBps: q.responseBps ?? null, previousEfficiency: p.efficiencyBpsPerMillion ?? null, currentEfficiency: q.efficiencyBpsPerMillion ?? null, efficiencyChange: x.efficiencyChange ?? null, pressureChange: x.pressureChange ?? null, spreadStartBps: q.spreadStartBps ?? null, spreadEndBps: q.spreadEndBps ?? null, replenishment: x.replenishment ?? null, knownSideFraction: q.knownSideFraction ?? null, alternatives: q.alternatives ?? [] }, { units: { signed: x.quote ?? 'QUOTE', efficiency: `bps per million ${x.quote ?? 'QUOTE'}` } }) }; }
    case 'DISPLAYED_LIQUIDITY': { const c = first('spread_bps'); if (!c) return null; const x = v(c); const bands = {}; for (const [k, b] of Object.entries(x.bands ?? {})) bands[k] = { bidNotional: b.bid?.notional ?? null, askNotional: b.ask?.notional ?? null, bidLowerBoundOnly: b.bid?.lowerBoundOnly ?? null, askLowerBoundOnly: b.ask?.lowerBoundOnly ?? null, imbalance: b.imbalance ?? null };
      return { comp: c, extra: [], value: base(c, 'MARKET_BOOK_CONTEXT', { venue: x.venue, quote: x.quote, mid: x.mid ?? null, spreadBps: x.spreadBps ?? null, microprice: x.microprice ?? null, bands, bookAgeMs: x.bookAgeMs ?? null, synchronized: x.synchronized ?? null, checksumVerified: x.checksumVerified ?? null, attribution: 'AGGREGATE_L2_UNATTRIBUTED' }, { units: { mid: x.quote ?? 'QUOTE', spreadBps: 'BPS' } }) }; }
    case 'CROSS_VENUE': { const c = first('peer_relative_move'); if (!c) return null; const x = v(c); const d = first('venue_mid_dispersion'); return { comp: c, extra: [d].filter(Boolean), value: base(c, 'MARKET_PEER_RELATIVE_MOVE', { cohortLabel: x.cohortLabel ?? 'SAME_QUOTE_VENUE', targetReturnBps: x.targetReturnBps ?? null, medianPeerReturnBps: x.medianPeerReturnBps ?? null, residualBps: x.residualBps ?? null, madBps: x.madBps ?? null, n: x.n ?? 0, positivePeers: x.positivePeers ?? null, excluded: clip(x.excluded, 16), firstObservedChanges: clip(d ? v(d).firstObservedChanges?.sequence : [], 8) }, { units: { residualBps: 'BPS' } }) }; }
    case 'DERIVATIVES_FUNDING_OI': { const c = first('basis_bps', (x) => x.value?.marketType === 'PERPETUAL') ?? first('basis_bps'); if (!c) return null; const x = v(c); return { comp: c, extra: [], value: base(c, 'MARKET_DERIVATIVES_CONTEXT', { instrument: x.instrument, venue: String(x.instrument).split(':')[0], marketType: x.marketType, basisBps: x.basisBps ?? null, markPrice: x.markPrice ?? null, indexPrice: x.indexPrice ?? null, openInterest: x.openInterest?.value ?? null, openInterestUnit: x.openInterest?.unit ?? 'UNKNOWN', oiChangeAbsolute: x.openInterest?.changeOverHour?.absolute ?? null, oiChangePercent: x.openInterest?.changeOverHour?.percent ?? null, fundingNative: x.funding?.value ?? null, fundingUnit: x.funding?.unit ?? 'UNKNOWN', fundingIntervalMs: x.funding?.intervalMs ?? null, fundingRelative: x.funding?.relative ?? null, ageMs: x.ageMs ?? null }, { units: { basisBps: 'BPS', funding: x.funding?.unit ?? 'UNKNOWN' } }) }; }
    case 'LIQUIDATIONS': { const c = first('liquidation_notional_by_side', (x) => (x.windowEndTs - x.windowStartTs) === 3_600_000) ?? first('liquidation_notional_by_side'); if (!c) return null; const x = v(c); return { comp: c, extra: [], value: base(c, 'MARKET_LIQUIDATIONS_CONTEXT', { windowMs: c.windowEndTs - c.windowStartTs, events: x.events ?? 0, longNotional: x.longNotional ?? null, shortNotional: x.shortNotional ?? null, unknownSideNotional: x.unknownSideNotional ?? null, unit: x.unit ?? null, venues: clip(x.venues, 16), zeroMeaningful: x.zeroMeaningful === true }, { units: { notional: x.unit ?? 'UNKNOWN' } }) }; }
    case 'OPTIONS_TERM_SKEW': { const c = first('atm_iv_term'); if (!c) return null; const x = v(c); return { comp: c, extra: [], value: base(c, 'MARKET_OPTIONS_CONTEXT', { scope: x.scope ?? null, admitted: x.admitted ?? 0, omitted: x.census?.omitted ?? 0, censusComplete: x.censusComplete === true, term: clip(x.term, 8).map((t) => ({ expiryTs: t.expiryTs, contracts: t.contracts, atmIv: t.atm?.markIv ?? null, atmStrike: t.atm?.strike ?? null, riskReversal25d: t.riskReversal25d, butterfly25d: t.butterfly25d, callDelta: t.call25?.delta ?? null, putDelta: t.put25?.delta ?? null, putCallOiRatio: t.putCallOiRatio, atmIvBidAskSpread: t.atmIvBidAskSpread })) }, { units: { iv: 'FRACTION' } }) }; }
    case 'SUPPLY_UNLOCKS': { const c = first('supply_ratios'); const u = first('unlock_schedule'); const anchor = c ?? u; if (!anchor) return null; const x = v(c); const uu = v(u); return { comp: anchor, extra: [c, u].filter((z) => z && z !== anchor), value: base(anchor, 'MARKET_SUPPLY_UNLOCKS', { circulatingOverTotal: x.circulatingOverTotal ?? null, circulatingOverMax: x.circulatingOverMax ?? null, fdvOverMarketCap: x.fdvOverMarketCap ?? null, volumeOverMarketCap: x.volumeOverMarketCap ?? null, maxSupplyKnown: x.maxSupplyKnown ?? null, marketCapUsd: x.reference?.marketCapUsd ?? null, upcoming: clip(uu.upcoming, 8), untrackedAllocations: uu.untrackedAllocations ?? null, referenceProvider: x.reference?.provider ?? null }, { units: { marketCapUsd: 'USD' } }) }; }
    case 'DEX_DEFI': { const pools = comps.filter((z) => z.metricId === 'pool_liquidity'); const prots = comps.filter((z) => z.metricId !== 'pool_liquidity'); const anchor = pools[0] ?? prots[0]; if (!anchor) return null; return { comp: anchor, extra: [...pools, ...prots].filter((z) => z !== anchor), value: base(anchor, 'MARKET_DEX_DEFI_CONTEXT', { pools: clip(pools, 4).map((p) => ({ chain: p.value.chain, poolAddress: p.value.poolAddress, dex: p.value.dex ?? null, quoteToken: p.value.quoteToken, priceUsd: p.value.priceUsd, liquidityUsd: p.value.liquidityUsd, volume24hUsd: p.value.volume24hUsd, txCount24h: p.value.txCount24h, ageMs: p.value.ageMs, provider: p.value.provider })), protocols: clip(prots, 8).map((p) => ({ metricId: p.value.metricId, protocol: p.value.protocol ?? null, chain: p.value.chain ?? null, value: p.value.value, unit: p.value.unit, periodKind: p.value.periodKind, ageMs: p.value.ageMs, provider: p.value.provider })) }, { units: { liquidityUsd: 'USD' } }) }; }
    case 'ONCHAIN_ENTITY_FLOW': { const c = first('exchange_net_flow'); const r = first('exchange_reserve'); const anchor = c ?? r; if (!anchor) return null; const x = v(c); return { comp: anchor, extra: [c, r].filter((z) => z && z !== anchor), value: base(anchor, 'MARKET_ONCHAIN_CONTEXT', { provider: x.provider ?? v(r).provider ?? 'UNKNOWN', entitySet: x.entitySet ?? v(r).entitySet ?? null, chain: x.chain ?? v(r).chain ?? null, window: x.window ?? v(r).window ?? null, inflow: x.inflow ?? null, outflow: x.outflow ?? null, net: x.net ?? null, reserve: v(r).value ?? null, unit: x.unit ?? v(r).unit ?? null, labelVintage: x.labelVintage ?? null, periodStartTs: x.periodStartTs ?? null, periodEndTs: x.periodEndTs ?? null }, { units: { net: x.unit ?? 'NATIVE' } }) }; }
    case 'NETWORK_ACTIVITY': { if (!comps.length) return null; const prov = comps[0].value.provider; const mine = comps.filter((z) => z.value.provider === prov); return { comp: mine[0], extra: mine.slice(1), value: base(mine[0], 'MARKET_NETWORK_CONTEXT', { provider: prov, metrics: clip(mine, 12).map((m) => ({ metricId: m.value.nativeMetric ?? m.metricId, value: m.value.value, unit: m.value.unit, change: m.value.change ?? null, periodEndTs: m.windowEndTs, ageMs: m.value.ageMs })) }) }; }
    case 'STABLECOIN_LIQUIDITY': { const c = first('stablecoin_supply_change', (x) => x.value?.chain === null) ?? first('stablecoin_supply_change'); if (!c) return null; const x = v(c); return { comp: c, extra: [], value: base(c, 'MARKET_STABLECOIN_CONTEXT', { stablecoinId: x.stablecoinId, chain: x.chain ?? null, current: x.current ?? null, change: x.change ?? null, unit: x.unit ?? null, pegPrice: x.pegPrice ?? null, pegDeviationBps: x.pegDeviationBps ?? null, fromTs: x.fromTs ?? null, toTs: x.toTs ?? null }, { units: { current: x.unit ?? 'NATIVE', pegDeviationBps: 'BPS' } }) }; }
    case 'ETF_FLOWS': { const c = first('etf_daily_flow'); if (!c) return null; const x = v(c); return { comp: c, extra: [], value: base(c, 'MARKET_ETF_CONTEXT', { asset: x.asset ?? ctx.canonicalCoin, latestFlowUsd: x.latest?.flowUsd ?? null, latestPeriodStartTs: x.latest?.periodStartTs ?? null, latestPeriodEndTs: x.latest?.periodEndTs ?? null, trailing5: x.trailing5 ?? null, trailing20: x.trailing20 ?? null, estimate: x.latest?.estimate ?? null, days: x.days ?? 0 }, { units: { flow: 'USD' } }) }; }
    case 'MACRO_RELEASES': { const levels = comps.filter((z) => z.metricId === 'macro_level'); const ev = first('macro_surprise'); const anchor = levels[0] ?? ev; if (!anchor) return null; return { comp: anchor, extra: [...levels, ev].filter((z) => z && z !== anchor), value: base(anchor, 'MARKET_MACRO_CONTEXT', { levels: clip(levels, 16).map((l) => ({ seriesId: l.value.seriesId, value: l.value.value, unit: l.value.unit, observationDate: l.value.observationDate, vintageDate: l.value.vintageDate, change: l.value.change, ageMs: l.value.ageMs })), upcoming: clip(ev ? v(ev).upcoming : [], 8), released: clip(ev ? v(ev).released : [], 8).map((r) => ({ eventName: r.eventName, countryCode: r.countryCode, scheduledTs: r.scheduledTs, actual: r.actual, forecast: r.forecast, unit: r.unit, surprise: r.surprise?.surprise ?? null, surpriseSupport: r.surprise?.support?.state ?? null })) }) }; }
    case 'CROSS_ASSET': { if (!comps.length) return null; return { comp: comps[0], extra: comps.slice(1), value: base(comps[0], 'MARKET_CROSS_ASSET_CONTEXT', { instruments: clip(comps, 8).map((c) => ({ instrument: c.value.instrument, proxyFor: c.value.proxyFor, sessionState: c.value.sessionState, intervalMs: c.value.intervalMs, lastClose: c.value.lastClose, lastBarEndTs: c.value.lastBarEndTs, logReturnLastBar: c.value.logReturnLastBar, correlationR: c.value.correlationWithTarget?.r ?? null, correlationN: c.value.correlationWithTarget?.n ?? null, ageMs: c.value.ageMs })) }) }; }
    case 'OFFICIAL_SOCIAL_EVENTS': { const c = first('event_references'); if (!c) return null; return { comp: c, extra: [], value: base(c, 'MARKET_EVENT_CONTEXT', { events: clip(v(c).events, 16).map((e) => ({ eventKind: e.eventKind, sourceProvider: e.sourceProvider, nativeRef: e.nativeRef, sourceEventTs: e.sourceEventTs, knownAtTs: e.knownAtTs, status: e.status, headline: e.headline ?? null, untrusted: e.untrusted })) }) }; }
    case 'INFRASTRUCTURE_STATUS': { const c = first('provider_status'); if (!c) return null; return { comp: c, extra: [], value: base(c, 'MARKET_INFRA_CONTEXT', { statuses: clip(v(c).statuses, 16), incidents: clip(v(c).incidents, 8) }) }; }
    default: return null;
  }
}
const providersOf = (ctx, family) => { const set = new Set(); for (const c of ctx.families[family]?.coverage ?? []) set.add(c.provider); for (const comp of ctx.families[family]?.components ?? []) { const p = comp.value?.provider; if (typeof p === 'string' && /^[A-Z_]+$/.test(p)) set.add(p); const venue = comp.value?.venue; if (venue && VENUE_PROVIDER[venue]) set.add(VENUE_PROVIDER[venue]); const inst = comp.value?.instrument; if (typeof inst === 'string' && VENUE_PROVIDER[inst.split(':')[0]]) set.add(VENUE_PROVIDER[inst.split(':')[0]]); } return [...set].sort(); };

export function buildResearchEvidenceV2({ marketContext = null, socialProjection = null, asOfTs, trigger, mode = 'LIVE_OBSERVATION', entrances = null, detailRequests = [], microProjection = null, providerSymbols = null, coverageLimitations = [] }) {
  if (!isTs(asOfTs)) return { ok: false, reason: 'INVALID_INPUT', detail: 'asOfTs required' };
  if (!RESEARCH_MODES.includes(mode)) return { ok: false, reason: 'INVALID_INPUT', detail: 'unknown mode' };
  if (!trigger || !TRIGGER_KINDS_V2.includes(trigger.kind)) return { ok: false, reason: 'INVALID_INPUT', detail: 'trigger kind outside the closed set' };
  if (marketContext !== null) { const e = contextError(marketContext); if (e) return { ok: false, reason: 'INVALID_INPUT', detail: e }; if (marketContext.asOfTs > asOfTs) return { ok: false, reason: 'INVALID_INPUT', detail: 'market context as-of after the packet as-of' }; }
  if (socialProjection !== null) { const e = socialProjectionError(socialProjection); if (e) return { ok: false, reason: 'INVALID_INPUT', detail: e }; if (marketContext && socialProjection.asOfTs !== marketContext.asOfTs) return { ok: false, reason: 'INVALID_INPUT', detail: 'the Social projection must be read at the market context as-of' }; if (socialProjection.asOfTs > asOfTs) return { ok: false, reason: 'INVALID_INPUT', detail: 'social projection after the packet as-of' }; }
  const canonicalCoin = marketContext?.canonicalCoin ?? socialProjection?.canonicalCoin ?? null;
  if (marketContext && socialProjection && marketContext.canonicalCoin !== socialProjection.canonicalCoin) return { ok: false, reason: 'INVALID_INPUT', detail: 'market and social subjects disagree' };
  if (canonicalCoin === null) return { ok: false, reason: 'INVALID_INPUT', detail: 'an empty packet still needs a subject: supply trigger.canonicalCoin' , hint: 'use buildEmptyResearchPacket' };
  const limitations = new Set(coverageLimitations.filter((x) => COVERAGE_LIMITATION_REASONS.includes(x)));
  const sources = new Map(); const evidence = []; const contextMap = { evidenceToComponent: {}, omitted: { detail: [], counts: { families: 0, components: 0 } }, admissionRecipe: ADMISSION_RECIPE };
  const addSource = (provider, sourceType, retrievedTs, locator) => { if (sources.has(provider)) return sources.get(provider).sourceId; const s = { sourceId: 'src-x', provider, sourceType, authorityClass: 'ESTABLISHED', publishedTs: null, retrievedTs: Math.min(retrievedTs, asOfTs), locator, excerpt: null }; s.sourceId = sourceIdentity(s); sources.set(provider, s); return s.sourceId; };
  const missing = []; const providerCoverage = new Map();
  let summaryItems = []; let detailItems = [];
  if (marketContext) {
    const ctx = marketContext;
    for (const family of FAMILIES) {
      const f = ctx.families[family]; if (!f) continue;
      for (const c of f.coverage) { const prev = providerCoverage.get(c.provider); const st = c.state === 'OBSERVED' ? 'OBSERVED' : c.state === 'ACCESS_BLOCKED' ? 'UNAVAILABLE' : c.state === 'NOT_SUPPORTED' ? 'NOT_SUPPORTED' : c.state === 'NOT_QUERIED' ? 'NOT_QUERIED' : c.state === 'GAP' || c.state === 'DROPPED' || c.state === 'EVICTED' ? 'STALE' : 'FAILED'; if (!prev || prev.state !== 'OBSERVED') providerCoverage.set(c.provider, { provider: c.provider, state: st, checkedTs: st === 'NOT_QUERIED' ? null : Math.min(c.endTs ?? c.startTs, asOfTs), detail: c.reasonCodes.length ? c.reasonCodes.join(',').slice(0, 200) : null }); }
      const provs = providersOf(ctx, family);
      const built = familyValue(family, ctx, f.components);
      if (!built) { missing.push({ kind: family, description: `${family}: ${f.state} — no admissible component at the as-of` }); limitations.add(f.state === 'NOT_QUERIED' ? 'FAMILY_NOT_QUERIED' : f.state === 'NOT_SUPPORTED' ? 'FAMILY_NOT_SUPPORTED' : 'FAMILY_MISSING'); contextMap.omitted.counts.families += 1;
        const st = f.state === 'NOT_SUPPORTED' ? 'UNAVAILABLE' : 'MISSING'; const item = { evidenceId: 'evd-x', sense: 'MARKET', kind: FAMILY_KIND[family], state: st, knownAtTs: ctx.asOfTs, observedTs: null, value: null, sourceRefs: provs.map((p) => addSource(p, PROVIDER_SOURCE_TYPE(p), ctx.asOfTs, `market-lab:${p}`)).sort(), claimRefs: [], provenance: `mlab:${ctx.contextId.slice(5, 21)}:${family}:${f.state}` }; item.evidenceId = evidenceIdentity(item); summaryItems.push(item); continue; }
      if (f.state === 'PARTIAL' || built.comp.support?.state === 'PARTIAL' || built.comp.support?.state === 'STALE') limitations.add('FAMILY_PARTIAL');
      if (family === 'CROSS_VENUE' && built.comp.support?.state === 'INSUFFICIENT_PEERS') limitations.add('PEER_COHORT_INSUFFICIENT');
      if (family === 'SPOT_FLOW' && (built.comp.support?.reasons ?? []).includes('BOOK_ENDPOINTS_INCOMPLETE')) limitations.add('BOOK_ENDPOINTS_INCOMPLETE');
      if (family === 'OPTIONS_TERM_SKEW' && built.value.fields.censusComplete === false) limitations.add('OPTIONS_CENSUS_PARTIAL');
      const value = fit(built.value); if (!value) return { ok: false, reason: 'PACKET_LIMIT_EXCEEDED', detail: `${family}: mandatory summary cannot fit the per-value bound` };
      const te = typedValueError(value.kind, value, { asOfTs, canonicalCoin }); if (te) return { ok: false, reason: 'INVALID_INPUT', detail: `${family}: ${te}` };
      const item = { evidenceId: 'evd-x', sense: 'MARKET', kind: value.kind, state: stateOf(built.comp.support, f.state), knownAtTs: value.knownAtTs, observedTs: value.observedTs, value, sourceRefs: provs.map((p) => addSource(p, PROVIDER_SOURCE_TYPE(p), value.knownAtTs, `market-lab:${p}`)).sort(), claimRefs: [], provenance: `mlab:${ctx.contextId.slice(5, 21)}:${built.comp.componentId}` };
      item.evidenceId = evidenceIdentity(item); summaryItems.push(item); contextMap.evidenceToComponent[item.evidenceId] = built.comp.componentId;
      for (const extra of built.extra) contextMap.omitted.detail.push({ family, metricId: extra.metricId, componentId: extra.componentId, subjectId: extra.subjectId, reason: 'DETAIL_NOT_REQUESTED' });
      for (const other of f.components.filter((c) => c !== built.comp && !built.extra.includes(c))) contextMap.omitted.detail.push({ family, metricId: other.metricId, componentId: other.componentId, subjectId: other.subjectId, reason: 'DETAIL_NOT_REQUESTED' });
    }
    if (microProjection) { const mv = { kind: 'MARKET_MICRO_CONTEXT', canonicalCoin, asOfTs: ctx.asOfTs, windowStartTs: null, windowEndTs: null, observedTs: microProjection.observedTs, knownAtTs: microProjection.knownAtTs, recipe: null, support: { state: 'OWNER_PROJECTION', reasons: [], completeness: null }, units: {}, sourceIds: [String(microProjection.sourceId)], fields: { venue: 'kraken', absorption: microProjection.absorption ?? null, depletion: microProjection.depletion ?? null, recovery: microProjection.recovery ?? null, flowResponse: microProjection.flowResponse ?? null, attribution: 'AGGREGATE_L2_UNATTRIBUTED', proxyLabels: microProjection.proxyLabels ?? [] } }; const te = typedValueError('MARKET_MICRO_CONTEXT', mv, { asOfTs, canonicalCoin }); if (!te) { const item = { evidenceId: 'evd-x', sense: 'MICRO', kind: 'MARKET_MICRO_CONTEXT', state: 'KNOWN', knownAtTs: mv.knownAtTs, observedTs: mv.observedTs, value: mv, sourceRefs: [addSource('KRAKEN_SPOT', 'MARKET_DATA', mv.knownAtTs, 'market-lab:KRAKEN_SPOT')], claimRefs: [], provenance: `tape-micro:${microProjection.sourceId}` }; item.evidenceId = evidenceIdentity(item); summaryItems.push(item); } }
    // explicit detail admission (canonical order: family order, then metricId, then subjectId), until bounds bind
    const wanted = detailRequests.map((d) => `${d.family}|${d.metricId ?? '*'}`);
    const candidates = contextMap.omitted.detail.filter((d) => wanted.includes(`${d.family}|${d.metricId}`) || wanted.includes(`${d.family}|*`)).sort((a, b) => FAMILIES.indexOf(a.family) - FAMILIES.indexOf(b.family) || (a.metricId < b.metricId ? -1 : a.metricId > b.metricId ? 1 : (a.subjectId ?? '') < (b.subjectId ?? '') ? -1 : 1));
    for (const d of candidates) { const comp = ctx.families[d.family].components.find((c) => c.componentId === d.componentId); if (!comp) continue; const built = familyValue(d.family, ctx, [comp]); if (!built) continue; const value = fit(built.value); if (!value) continue; const te = typedValueError(value.kind, value, { asOfTs, canonicalCoin }); if (te) continue; const item = { evidenceId: 'evd-x', sense: 'MARKET', kind: value.kind, state: stateOf(comp.support, ctx.families[d.family].state), knownAtTs: value.knownAtTs, observedTs: value.observedTs, value, sourceRefs: providersOf(ctx, d.family).map((p) => addSource(p, PROVIDER_SOURCE_TYPE(p), value.knownAtTs, `market-lab:${p}`)).sort(), claimRefs: [], provenance: `mlab:${ctx.contextId.slice(5, 21)}:${comp.componentId}:detail` }; item.evidenceId = evidenceIdentity(item); if (summaryItems.some((s) => s.evidenceId === item.evidenceId) || detailItems.some((s) => s.evidenceId === item.evidenceId)) continue; detailItems.push({ item, d }); }
  } else limitations.add('MARKET_CONTEXT_ABSENT');
  // Social projection
  let socialItems = []; let dossierRef = null; const historyRefs = []; let socialEntrances = null;
  if (socialProjection) { const p = projectSocial(socialProjection, { asOfTs }); if (!p.ok) return { ok: false, reason: 'INVALID_INPUT', detail: p.error }; for (const l of p.limitations) limitations.add(l); socialEntrances = p.entrances; for (const s of p.sources) addSource(s.provider, s.sourceType, s.retrievedTs, s.locator); for (const it of p.items) { const item = { evidenceId: 'evd-x', sense: 'RUMINT', kind: it.kind, state: it.state, knownAtTs: it.knownAtTs, observedTs: it.observedTs, value: it.value, sourceRefs: it.sourceProviders.map((pr) => sources.get(pr)?.sourceId).filter(Boolean).sort(), claimRefs: [], provenance: it.provenanceKey }; item.evidenceId = evidenceIdentity(item); socialItems.push(item); if (it.kind === 'SOCIAL_DOSSIER_CONTEXT') dossierRef = item.evidenceId; else if (historyRefs.length < 8) historyRefs.push(item.evidenceId); } if (socialProjection.coverage.state !== 'AVAILABLE') missing.push({ kind: 'SOCIAL_DOSSIER', description: `Social coverage ${socialProjection.coverage.state}: ${socialProjection.coverage.reason ?? 'no reason recorded'}` }); }
  else limitations.add('SOCIAL_PROJECTION_ABSENT');
  if (mode === 'REPLAY_AS_OF') limitations.add('REPLAY_NETWORK_OFF');
  // summary of the market context (after components, before the packet)
  let summary = null;
  if (marketContext) { const components = summaryItems.filter((i) => i.sense === 'MARKET').map((i) => i.evidenceId).sort(); const value = { kind: 'MARKET_CONTEXT_SUMMARY', canonicalCoin, asOfTs: marketContext.asOfTs, windowStartTs: null, windowEndTs: null, observedTs: marketContext.asOfTs, knownAtTs: marketContext.asOfTs, recipe: { recipeId: 'context', version: 1, recipeSetVersion: marketContext.recipeSetVersion }, support: { state: 'CONTEXT_SEALED', reasons: [], completeness: null }, units: {}, sourceIds: [marketContext.contextId], fields: { contextId: marketContext.contextId, recipeSetVersion: marketContext.recipeSetVersion, captureBundleId: marketContext.captureRef?.bundleId ?? null, familyStates: Object.fromEntries(FAMILIES.filter((f) => marketContext.families[f]).map((f) => [f, marketContext.families[f].state])), componentIds: components.slice(0, MAX_COMPONENT_IDS), omittedDetail: { count: contextMap.omitted.detail.length, familiesWithoutSummary: contextMap.omitted.counts.families }, resourceState: marketContext.resourceState ?? null } }; if (components.length > MAX_COMPONENT_IDS) return { ok: false, reason: 'PACKET_LIMIT_EXCEEDED', detail: 'more mandatory components than the summary can bind' }; const te = typedValueError('MARKET_CONTEXT_SUMMARY', value, { asOfTs, canonicalCoin }); if (te) return { ok: false, reason: 'INVALID_INPUT', detail: te }; summary = { evidenceId: 'evd-x', sense: 'MARKET', kind: 'MARKET_CONTEXT_SUMMARY', state: 'KNOWN', knownAtTs: marketContext.asOfTs, observedTs: marketContext.asOfTs, value, sourceRefs: [...sources.values()].filter((s) => s.sourceType !== 'SOCIAL_ACCOUNT' && s.provider !== 'rumor2-research').map((s) => s.sourceId).sort().slice(0, 16), claimRefs: [], provenance: `mlab:${marketContext.contextId.slice(5, 21)}:summary` }; summary.evidenceId = evidenceIdentity(summary); if (contextMap.omitted.detail.length) limitations.add('DETAIL_OMITTED_BY_BOUNDS'); }
  const entrancesFinal = entrances ?? (trigger.kind === 'MARKET_RESEARCH' ? ['MARKET_LED'] : socialEntrances ?? ['MARKET_LED']);
  const assemble = (items) => { const packet = { schemaVersion: EVIDENCE_SCHEMA_VERSION_2, packetId: 'sep2-x', asOfTs, subject: { canonicalCoin, providerSymbols: providerSymbols ?? null }, trigger: { kind: trigger.kind, sourceEventId: trigger.sourceEventId ?? null, observedTs: trigger.observedTs ?? null }, claims: [], sources: [...sources.values()].sort((a, b) => (a.sourceId < b.sourceId ? -1 : 1)), evidence: items, claimLinks: [], providerCoverage: [...providerCoverage.values()].sort((a, b) => (a.provider < b.provider ? -1 : 1)).slice(0, 64), contradictions: [], missingEvidence: missing.sort((a, b) => (a.kind < b.kind ? -1 : 1)), analogs: [], security: { untrustedTextPresent: items.some((e) => e.kind === 'MARKET_EVENT_CONTEXT' && Array.isArray(e.value?.fields?.events) && e.value.fields.events.some((x) => x.headline !== null && x.headline !== undefined)) }, researchContext: { mode, entrances: [...new Set(entrancesFinal)].filter((e) => RESEARCH_ENTRANCES.includes(e)), dossierRef, marketContextRef: summary ? summary.evidenceId : null, sourceHistoryRefs: historyRefs, coverageLimitations: [...limitations].sort(), authority: 'NONE', purpose: 'RESEARCH_ONLY' } }; packet.packetId = packetIdentityV2(packet); return packet; };
  const mandatory = [...summaryItems, ...(summary ? [summary] : []), ...socialItems];
  if (mandatory.length > MAX_EVIDENCE || sources.size > MAX_SOURCES) return { ok: false, reason: 'PACKET_LIMIT_EXCEEDED', detail: `mandatory items ${mandatory.length} / sources ${sources.size} exceed the bounds` };
  let packet = assemble(mandatory); let check = validateEvidencePacketV2(packet);
  if (!check.valid) { const overflow = check.reasons.some((r) => /exceeds/.test(r)); return { ok: false, reason: overflow ? 'PACKET_LIMIT_EXCEEDED' : 'VALIDATION_FAILURE', detail: check.reasons.slice(0, 5) }; }
  const admitted = []; for (const { item, d } of detailItems) { if (mandatory.length + admitted.length + 1 > MAX_EVIDENCE) { d.reason = 'EVIDENCE_CAP'; continue; } const trial = assemble([...mandatory, ...admitted, item]); const c = validateEvidencePacketV2(trial); if (!c.valid) { d.reason = c.reasons.some((r) => /exceeds/.test(r)) ? 'PACKET_BYTE_CAP' : 'INVALID'; continue; } packet = trial; admitted.push(item); contextMap.evidenceToComponent[item.evidenceId] = d.componentId; d.reason = 'ADMITTED'; }
  contextMap.omitted.detail = contextMap.omitted.detail.filter((d) => d.reason !== 'ADMITTED'); contextMap.omitted.counts.components = contextMap.omitted.detail.length;
  return { ok: true, packet, contextMap: { packetId: packet.packetId, contextId: marketContext?.contextId ?? null, ...contextMap, admittedDetail: admitted.length, mandatoryItems: mandatory.length, canonicalChars: canonicalJson(packet).length, utf8Bytes: Buffer.byteLength(canonicalJson(packet), 'utf8'), limits: { maxEvidence: MAX_EVIDENCE, maxChars: MAX_PACKET_CANONICAL_CHARS, maxBytes: MAX_PACKET_UTF8_BYTES } } };
}
// both inputs null: a valid, explicitly empty research packet for a named subject (never a forged observation)
export function buildEmptyResearchPacket({ canonicalCoin, asOfTs, trigger, mode = 'LIVE_OBSERVATION', entrances = ['MARKET_LED'] }) {
  const packet = { schemaVersion: EVIDENCE_SCHEMA_VERSION_2, packetId: 'sep2-x', asOfTs, subject: { canonicalCoin, providerSymbols: null }, trigger: { kind: trigger.kind, sourceEventId: trigger.sourceEventId ?? null, observedTs: trigger.observedTs ?? null }, claims: [], sources: [], evidence: [], claimLinks: [], providerCoverage: [], contradictions: [], missingEvidence: [{ kind: 'MARKET_CONTEXT', description: 'no market context was supplied' }, { kind: 'SOCIAL_DOSSIER', description: 'no Social projection was supplied' }], analogs: [], security: { untrustedTextPresent: false }, researchContext: { mode, entrances, dossierRef: null, marketContextRef: null, sourceHistoryRefs: [], coverageLimitations: ['MARKET_CONTEXT_ABSENT', 'SOCIAL_PROJECTION_ABSENT', ...(mode === 'REPLAY_AS_OF' ? ['REPLAY_NETWORK_OFF'] : [])].sort(), authority: 'NONE', purpose: 'RESEARCH_ONLY' } };
  packet.packetId = packetIdentityV2(packet); const v = validateEvidencePacketV2(packet); return v.valid ? { ok: true, packet, contextMap: { packetId: packet.packetId, contextId: null, evidenceToComponent: {}, omitted: { detail: [], counts: { families: 0, components: 0 } }, admissionRecipe: ADMISSION_RECIPE, admittedDetail: 0, mandatoryItems: 0 } } : { ok: false, reason: 'VALIDATION_FAILURE', detail: v.reasons };
}
export { MARKET_EVIDENCE_KINDS, KIND_FAMILY, RECIPE_SET_VERSION };
