// MARKET-EDGE closeout test helpers: a deterministic offline corpus (spot candles / trades / books + dark analytics buckets +
// L3 snapshots / events) and the sealing of ONE public CAPTURE bundle + ONE dark EDGE_CAPTURE bundle exactly as the runners
// publish them. No network, no credential, no order verb.
import path from 'node:path';
import { makeObservation, makeCoverage, quality, emptyProvenance, subjectId, ANALYTICS_MANIPULATION_RISK } from '../../market-lab/contracts.js';
import { prepareOutputTarget, reserveOutputDir, jsonlWriter, writeJsonFile, publishManifest } from '../../market-lab/store.js';
import { codeIdentity } from '../../market-lab/identity.js';
import { samplePolicy, RESOURCE_DEFAULTS } from '../../market-lab/policy.js';
import { orderKeyOf } from '../../market-lab/l3-book.js';
import { EDGE_CAPTURE_VERSION, EDGE_STATUS, CAPTURE_LAW } from '../../market-lab/edge-capture.js';
import { MINUTE_MS } from '../../market-lab/time.js';

export const T0 = Date.parse('2026-09-10T00:00:00Z'); export const HOUR = 3_600_000; export const IMS = 5 * MINUTE_MS;
export const FUT = { subjectKind: 'DERIVATIVE', canonicalCoin: 'BTC', providerAssetId: null, venue: 'kraken-futures', instrumentId: 'PF_XBTUSD', specificationId: 'PF_XBTUSD:flexible_futures:1', marketType: 'PERPETUAL' };
export const SPOT = { subjectKind: 'MARKET', canonicalCoin: 'BTC', providerAssetId: null, venue: 'kraken', nativeSymbol: 'BTC/USD', base: 'BTC', quote: 'USD', marketType: 'SPOT', quoteAliasGroup: null };
export const SUBJECT = { canonicalCoin: 'BTC', spotSymbol: 'BTC/USD', futuresSymbol: 'PF_XBTUSD' };
export const NULLS = { sourceKey: null, sourceRevision: null, sourceEventTs: null, periodStartTs: null, periodEndTs: null, publishedTs: null, epochId: null };
let seq = 0; export const nextSeq = () => (seq += 1);
export const price = (ts) => 100 + 5 * Math.sin((ts - T0) / (2 * HOUR) * 2 * Math.PI) + ((ts / MINUTE_MS) % 7) * 0.01; // a smooth deterministic path
export const candle = (startTs, { knownAtTs = null } = {}) => { const o = price(startTs); const c = price(startTs + MINUTE_MS); return makeObservation({ ...NULLS, provider: 'KRAKEN_SPOT', endpointId: 'rest-ohlc', subject: SPOT, kind: 'CANDLE', sourceKey: `BTC/USD:1:${startTs}`, periodStartTs: startTs, periodEndTs: startTs + MINUTE_MS, receivedTs: startTs + MINUTE_MS + 500, knownAtTs: knownAtTs ?? startTs + MINUTE_MS + 500, sequence: nextSeq(), quality: quality('KNOWN'), provenance: emptyProvenance(), payload: { intervalMs: MINUTE_MS, open: o, high: Math.max(o, c) + 0.1, low: Math.min(o, c) - 0.1, close: c, volumeBase: 1, volumeQuote: o, tradeCount: 3, vwap: (o + c) / 2, closed: true, provisional: false } }); };
export const trade = (ts, side) => makeObservation({ ...NULLS, provider: 'KRAKEN_SPOT', endpointId: 'ws-v2', subject: SPOT, kind: 'TRADE', sourceEventTs: ts, receivedTs: ts + 10, knownAtTs: ts + 10, sequence: nextSeq(), epochId: 'KRAKEN_SPOT:ws-v2:1', quality: quality('KNOWN'), provenance: emptyProvenance(), payload: { price: price(ts), qty: 0.5, quoteNotional: price(ts) * 0.5, takerSide: side, sideConvention: 'TAKER_NATIVE', nativeTradeId: String(ts), orderType: null } });
export const book = (ts, over = {}) => makeObservation({ ...NULLS, provider: 'KRAKEN_SPOT', endpointId: 'ws-v2', subject: SPOT, kind: 'BOOK_SNAPSHOT', receivedTs: ts, knownAtTs: ts, sequence: nextSeq(), epochId: 'KRAKEN_SPOT:ws-v2:1', quality: quality('KNOWN'), provenance: emptyProvenance(), payload: { bids: [[price(ts) - 0.05, 1]], asks: [[price(ts) + 0.05, 1]], levelsPerSideCap: 10, synchronized: true, checksumVerified: true, bookAgeMs: 0, sampleReason: 'INTERVAL', pricePrecision: 2, qtyPrecision: 8, ...over } });
export const bucket = (bucketTs, value, { type = 'open-interest' } = {}) => makeObservation({ ...NULLS, provider: 'KRAKEN_DERIVATIVES', endpointId: 'charts-analytics', subject: FUT, kind: 'DERIVATIVE_ANALYTIC_BUCKET', sourceKey: `PF_XBTUSD:${type}:300:${bucketTs}`, sourceRevision: 'LIVE_FORWARD_CAPTURE:x', sourceEventTs: bucketTs, periodStartTs: bucketTs, periodEndTs: bucketTs + IMS, receivedTs: bucketTs + IMS + 1_000, knownAtTs: bucketTs + IMS + 1_000, sequence: nextSeq(), quality: quality('KNOWN', { reasonCodes: ['UNIT_UNVERIFIED'] }), provenance: { ...emptyProvenance(), vintage: 'LIVE_FORWARD_CAPTURE' }, payload: { analyticsType: type, intervalMs: IMS, bucketTs, values: type === 'cvd' ? { buyVolume: 1, sellVolume: 1, cvd: value } : { value }, nativeUnit: 'x', normalizedUnit: 'NATIVE', normalization: 'NONE', finality: 'FINAL', manipulationRisk: ANALYTICS_MANIPULATION_RISK[type], vintage: 'LIVE_FORWARD_CAPTURE', pageIndex: 0, more: false } });
export const l3snap = (ts, over = {}, top = {}) => makeObservation({ ...NULLS, provider: 'KRAKEN_SPOT', endpointId: 'ws-l3', subject: SPOT, kind: 'L3_BOOK_SNAPSHOT', receivedTs: ts, knownAtTs: ts, sequence: nextSeq(), epochId: 'KRAKEN_SPOT:ws-l3:1', quality: quality('KNOWN'), provenance: { ...emptyProvenance(), vintage: 'LIVE_FORWARD_CAPTURE' }, ...top, payload: { depth: 10, bids: [{ orderKey: orderKeyOf('BTC/USD', `b${ts}`), price: price(ts) - 0.05, qty: 1, providerTs: ts - 60_000, firstSeenTs: ts - 60_000, modifiedTs: null }], asks: [{ orderKey: orderKeyOf('BTC/USD', `a${ts}`), price: price(ts) + 0.05, qty: 1, providerTs: ts - 30_000, firstSeenTs: ts - 30_000, modifiedTs: null }], checksumVerified: true, synchronized: true, sampleReason: 'INTERVAL', truncated: false, pricePrecision: 2, qtyPrecision: 8, ...over } });
export const l3events = (ts, over = {}, top = {}) => makeObservation({ ...NULLS, provider: 'KRAKEN_SPOT', endpointId: 'ws-l3', subject: SPOT, kind: 'L3_ORDER_EVENT', receivedTs: ts, knownAtTs: ts, sequence: nextSeq(), epochId: 'KRAKEN_SPOT:ws-l3:1', quality: quality('KNOWN'), provenance: { ...emptyProvenance(), vintage: 'LIVE_FORWARD_CAPTURE' }, ...top, payload: { depth: 10, events: [{ event: 'ADD', orderKey: orderKeyOf('BTC/USD', `n${ts}`), side: 'BID', price: price(ts) - 0.05, qty: 0.3, previousQty: null, providerTs: ts, firstSeenTs: ts, ageMs: 0 }, { event: 'DELETE', orderKey: orderKeyOf('BTC/USD', `d${ts}`), side: 'ASK', price: price(ts) + 0.05, qty: 0, previousQty: 0.2, providerTs: ts - 5_000, firstSeenTs: ts - 5_000, ageMs: 5_000 }], checksumVerified: true, ...over } });
export function corpus({ hours = 6 } = {}) {
  const obs = []; const end = T0 + hours * HOUR;
  for (let ts = T0 - HOUR; ts < end + HOUR; ts += MINUTE_MS) { obs.push(candle(ts)); if (ts % (5 * MINUTE_MS) === 0) { obs.push(trade(ts + 1_000, ts % (10 * MINUTE_MS) === 0 ? 'BUY' : 'SELL')); obs.push(book(ts - 1_000)); obs.push(l3snap(ts + 3_000)); obs.push(l3events(ts + 4_000)); } }
  for (let b = T0 - 3 * HOUR; b < end + HOUR; b += IMS) { obs.push(bucket(b, 1_000 + Math.round(20 * Math.sin((b - T0) / HOUR)))); obs.push(bucket(b, Math.round(10 * Math.cos((b - T0) / HOUR)), { type: 'cvd' })); }
  return obs;
}
export const DARK_KINDS = ['DERIVATIVE_ANALYTIC_BUCKET', 'L3_BOOK_SNAPSHOT', 'L3_ORDER_EVENT', 'L3_BOOK_COVERAGE'];
export const splitCorpus = (obs) => { const dark = obs.filter((o) => DARK_KINDS.includes(o.kind)); const pub = obs.filter((o) => !dark.includes(o)); return { dark, pub }; };
const seal = (dir, kind, members, extraJson, summary, identity, limits, createdTs) => { const real = prepareOutputTarget(dir); const res = reserveOutputDir(real); const descs = []; for (const [name, rows] of Object.entries(members)) { const w = jsonlWriter(res, name, { lineBytes: limits.observationLineBytes, fileBytes: limits.segmentBytes }); for (const r of rows) w.append(r); descs.push(w.close()); } for (const [name, obj] of Object.entries(extraJson)) descs.push(writeJsonFile(res, name, obj, { maxBytes: limits.contextBytes })); descs.push(writeJsonFile(res, 'code-identity.json', codeIdentity(), { maxBytes: limits.manifestBytes })); return publishManifest(res, { kind, createdTs, summary, limits, identity, members: descs }); };
export const darkCoverage = (over = {}) => makeCoverage({ provider: 'KRAKEN_DERIVATIVES', endpointId: 'charts-analytics', subjectId: subjectId(FUT), family: 'DERIVATIVES_PRESSURE', kind: 'DERIVATIVE_ANALYTIC_BUCKET', state: 'OBSERVED', reasonCodes: [], startTs: T0 - 3 * HOUR, endTs: T0 + 5 * HOUR, observationCount: 1, droppedCount: 0, epochId: null, sequenceStart: null, sequenceEnd: null, ...over });
// seal the two bundles the way the runners do (the dark manifest carries the W12 capture claim reconciled with its markers)
export function sealSources(base, obs, { policy = samplePolicy(), limits = RESOURCE_DEFAULTS, darkCov = null, captureClaim = null, createdTs = T0 + 10 * HOUR } = {}) {
  const { dark, pub } = splitCorpus(obs);
  const spotCov = makeCoverage({ provider: 'KRAKEN_SPOT', endpointId: 'rest-ohlc', subjectId: subjectId(SPOT), family: 'SPOT_PRICE_CHART', kind: 'CANDLE', state: 'OBSERVED', reasonCodes: [], startTs: T0 - HOUR, endTs: T0 + 5 * HOUR, observationCount: Math.max(1, pub.filter((o) => o.kind === 'CANDLE').length), droppedCount: 0, epochId: null, sequenceStart: null, sequenceEnd: null });
  const capDir = path.join(base, 'cap'); const cap = seal(capDir, 'CAPTURE', { 'observations.jsonl': pub, 'coverage.jsonl': [spotCov] }, { 'catalog.json': { catalogVersion: 'market-capture-catalog-1' }, 'policy.json': policy }, { observations: pub.length, coverageRecords: 1, providers: ['KRAKEN_SPOT'], firstReceivedTs: Math.min(...pub.map((o) => o.receivedTs)), lastReceivedTs: Math.max(...pub.map((o) => o.receivedTs)) }, { test: true }, limits, createdTs);
  const cov = darkCov ?? [darkCoverage({ observationCount: Math.max(1, dark.filter((o) => o.kind === 'DERIVATIVE_ANALYTIC_BUCKET').length) })];
  const markers = cov.filter((c) => c.state === 'DROPPED' && c.reasonCodes.includes('RECORD_REJECTED')).length;
  const edgeDir = path.join(base, 'edge'); const edge = seal(edgeDir, 'EDGE_CAPTURE', { 'analytics.jsonl': dark.filter((o) => o.kind === 'DERIVATIVE_ANALYTIC_BUCKET'), 'l3-snapshots.jsonl': dark.filter((o) => o.kind === 'L3_BOOK_SNAPSHOT'), 'l3-events.jsonl': dark.filter((o) => o.kind === 'L3_ORDER_EVENT'), 'coverage.jsonl': cov }, { 'policy.json': policy }, { observations: dark.length, coverageRecords: cov.length, rejected: markers, dropMarkers: markers, capture: captureClaim ?? (markers ? 'PARTIAL' : 'COMPLETE'), captureLaw: CAPTURE_LAW }, { captureVersion: EDGE_CAPTURE_VERSION, status: EDGE_STATUS[0], authority: 'NONE' }, limits, createdTs);
  return { capDir, edgeDir, cap, edge, dark, pub };
}
