// MARKET-EDGE-KRAKEN-1 §7 — DARK research recipes over the two dark senses. PURE and deterministic: closed inputs
// (validated observation envelopes), an explicit as-of, no clock, no network, no future data (knownAtTs <= asOfTs is the
// admission wall), no zero-fill (a missing bucket is a gap that lowers support, never a zero), no cross-unit arithmetic
// (every derivatives recipe reads ONE native field of ONE analytics type / interval series), and every output carries its
// support / coverage metadata. Nothing here is a buy or sell signal; the combinations are NAMED DESCRIPTORS, not scores.
import { deepFreeze, fail, isFiniteNum, isTs, round, DARK_FAMILY_REGISTRY, ANALYTICS_TYPES } from './contracts.js';
import { median, nearestRank } from './recipes.js';

export const EDGE_RECIPE_SET_VERSION = 'market-edge-recipes-1';
export const EDGE_SUPPORT_STATES = Object.freeze(['COMPLETE', 'PARTIAL', 'MISSING']);
const R = (id, family, o) => [id, deepFreeze({ recipeId: id, version: 1, family, unit: DARK_FAMILY_REGISTRY[family].metrics[id], ...o })];
export const EDGE_RECIPES = deepFreeze(Object.fromEntries([
  R('oi_bucket_level', 'DERIVATIVES_PRESSURE', { inputs: ['DERIVATIVE_ANALYTIC_BUCKET'], analyticsType: 'open-interest', field: 'value', formula: 'latest FINAL open-interest bucket value at or before the as-of (native unit)' }),
  R('oi_bucket_change', 'DERIVATIVES_PRESSURE', { inputs: ['DERIVATIVE_ANALYTIC_BUCKET'], analyticsType: 'open-interest', field: 'value', formula: 'value(t) - value(t - interval) over two CONTIGUOUS final buckets; a missing neighbour is a gap, never zero' }),
  R('oi_bucket_acceleration', 'DERIVATIVES_PRESSURE', { inputs: ['DERIVATIVE_ANALYTIC_BUCKET'], analyticsType: 'open-interest', field: 'value', formula: 'change(t) - change(t - interval) over three contiguous final buckets' }),
  R('aggressor_bucket_level', 'DERIVATIVES_PRESSURE', { inputs: ['DERIVATIVE_ANALYTIC_BUCKET'], analyticsType: 'aggressor-differential', field: 'value', formula: 'latest FINAL aggressor-differential bucket value' }),
  R('aggressor_bucket_change', 'DERIVATIVES_PRESSURE', { inputs: ['DERIVATIVE_ANALYTIC_BUCKET'], analyticsType: 'aggressor-differential', field: 'value', formula: 'value(t) - value(t - interval) over two contiguous final buckets' }),
  R('aggressor_bucket_slope', 'DERIVATIVES_PRESSURE', { inputs: ['DERIVATIVE_ANALYTIC_BUCKET'], analyticsType: 'aggressor-differential', field: 'value', formula: 'OLS slope per bucket over the last N (default 6) CONTIGUOUS final buckets' }),
  R('cvd_bucket_change', 'DERIVATIVES_PRESSURE', { inputs: ['DERIVATIVE_ANALYTIC_BUCKET'], analyticsType: 'cvd', field: 'cvd', formula: 'cvd(t) - cvd(t - interval) over two contiguous final buckets' }),
  R('cvd_bucket_slope', 'DERIVATIVES_PRESSURE', { inputs: ['DERIVATIVE_ANALYTIC_BUCKET'], analyticsType: 'cvd', field: 'cvd', formula: 'OLS slope per bucket over the last N contiguous final cvd buckets' }),
  R('liquidation_bucket_burst', 'DERIVATIVES_PRESSURE', { inputs: ['DERIVATIVE_ANALYTIC_BUCKET'], analyticsType: 'liquidation-volume', field: 'value', formula: 'latest final bucket / median of the trailing N (default 24) contiguous final buckets (positive median); a shorter trail is PARTIAL with null' }),
  R('basis_bucket_level', 'DERIVATIVES_PRESSURE', { inputs: ['DERIVATIVE_ANALYTIC_BUCKET'], analyticsType: 'future-basis', field: 'basis', formula: 'latest FINAL future-basis bucket value (native unit)' }),
  R('basis_bucket_change', 'DERIVATIVES_PRESSURE', { inputs: ['DERIVATIVE_ANALYTIC_BUCKET'], analyticsType: 'future-basis', field: 'basis', formula: 'basis(t) - basis(t - interval) over two contiguous final buckets' }),
  R('funding_bucket_level', 'DERIVATIVES_PRESSURE', { inputs: ['DERIVATIVE_ANALYTIC_BUCKET'], analyticsType: 'funding', field: 'rateClose', formula: 'latest FINAL funding bucket rateClose (native unit; relativeRateClose reported alongside, never combined)' }),
  R('funding_bucket_change', 'DERIVATIVES_PRESSURE', { inputs: ['DERIVATIVE_ANALYTIC_BUCKET'], analyticsType: 'funding', field: 'rateClose', formula: 'rateClose(t) - rateClose(t - interval) over two contiguous final buckets' }),
  R('pressure_combinations', 'DERIVATIVES_PRESSURE', { inputs: ['DERIVATIVE_ANALYTIC_BUCKET'], analyticsType: null, field: null, formula: 'named boolean descriptors over the component recipes (oi_bucket_change, aggressor_bucket_level, cvd_bucket_change, liquidation_bucket_burst, basis_bucket_change); an unavailable component yields null, never false' }),
  R('visible_order_age_imbalance', 'L3_MICROSTRUCTURE', { inputs: ['L3_BOOK_SNAPSHOT'], formula: '(meanAgeBid - meanAgeAsk) / (meanAgeBid + meanAgeAsk) over the visible orders of the latest synchronized snapshot; age = snapshot receipt - firstSeenTs (our own observation clock, never a bridged age)' }),
  R('queue_turnover_imbalance', 'L3_MICROSTRUCTURE', { inputs: ['L3_ORDER_EVENT', 'L3_BOOK_SNAPSHOT'], formula: 'per side ADD+MODIFY+DELETE event count / resting orders at the latest snapshot; imbalance = (bid - ask) / (bid + ask)' }),
  R('depth_persistence', 'L3_MICROSTRUCTURE', { inputs: ['L3_BOOK_SNAPSHOT'], formula: 'fraction of orders visible in the first snapshot of the window still visible (same orderKey) in the last, per side' }),
  R('new_order_impulse', 'L3_MICROSTRUCTURE', { inputs: ['L3_ORDER_EVENT'], formula: 'sum of ADD quantities per side inside the window (BASE); net = bid - ask' }),
  R('visible_liquidity_disappearance', 'L3_MICROSTRUCTURE', { inputs: ['L3_ORDER_EVENT', 'L3_BOOK_COVERAGE'], formula: 'quantity that left the visible window per side split by DELETE (fill / cancel / expiry, indistinguishable) vs SCOPE_EVICTED (left the depth window) vs GAP (a coverage break inside the window: unknown, never counted as either)' }),
  R('replenishment_after_pressure', 'L3_MICROSTRUCTURE', { inputs: ['L3_ORDER_EVENT'], formula: 'on the side with the larger DELETE quantity: ADD quantity arriving AFTER the largest single DELETE / that side\'s DELETE quantity' }),
  R('queue_concentration', 'L3_MICROSTRUCTURE', { inputs: ['L3_BOOK_SNAPSHOT'], formula: 'per side at the touch level: largest order / level quantity and Herfindahl of order shares; touch share of the visible depth' }),
  R('order_age_quantiles', 'L3_MICROSTRUCTURE', { inputs: ['L3_BOOK_SNAPSHOT'], formula: 'nearest-rank p50 / p90 visible age in ms per side at the latest snapshot' }),
  R('top_level_churn', 'L3_MICROSTRUCTURE', { inputs: ['L3_ORDER_EVENT', 'L3_BOOK_SNAPSHOT'], formula: 'count of events at the touch price of the latest snapshot per side inside the window' }),
  R('microstructure_pressure_change', 'L3_MICROSTRUCTURE', { inputs: ['L3_ORDER_EVENT'], formula: 'net impulse share ((addBid - addAsk) / (addBid + addAsk)) of the current window minus the previous adjacent window' }),
]));
for (const f of Object.keys(DARK_FAMILY_REGISTRY)) for (const id of Object.keys(DARK_FAMILY_REGISTRY[f].metrics)) if (!EDGE_RECIPES[id] || EDGE_RECIPES[id].family !== f) throw new Error(`EDGE_RECIPES: ${f}.${id} unbound`);

const supportOf = (state, reasons = [], extra = {}) => ({ state, reasons, ...extra });
const out = (id, value, support, { asOfTs, windowStartTs = null, windowEndTs = null, inputKnownAtMax = null, inputs = 0 }) => deepFreeze({ recipeId: id, version: EDGE_RECIPES[id].version, recipeSetVersion: EDGE_RECIPE_SET_VERSION, family: EDGE_RECIPES[id].family, unit: EDGE_RECIPES[id].unit, value, support, asOfTs, windowStartTs, windowEndTs, inputKnownAtMax, inputs, authority: 'NONE' });
const admissible = (observations, asOfTs) => { if (!isTs(asOfTs)) fail('INVALID_REQUEST', 'asOfTs required'); return observations.filter((o) => o && isTs(o.knownAtTs) && o.knownAtTs <= asOfTs); };
const knownMax = (list) => (list.length ? Math.max(...list.map((o) => o.knownAtTs)) : null);

// ---- §7.1 derivatives: one native series (subject + analyticsType + interval), one version per bucket ---------------------------
// The latest admissible revision per bucket wins (knownAtTs, then sequence); PROVISIONAL buckets are excluded unless asked for.
export function analyticsSeries(observations, { analyticsType, intervalMs, asOfTs, includeProvisional = false }) {
  if (!ANALYTICS_TYPES.includes(analyticsType) || !isTs(intervalMs)) fail('INVALID_REQUEST', 'analyticsType/intervalMs malformed');
  const byBucket = new Map(); let provisionalExcluded = 0; let revisions = 0; let subjects = new Set();
  for (const o of admissible(observations, asOfTs)) {
    if (o.kind !== 'DERIVATIVE_ANALYTIC_BUCKET' || o.payload.analyticsType !== analyticsType || o.payload.intervalMs !== intervalMs) continue;
    if (o.payload.finality === 'PROVISIONAL' && !includeProvisional) { provisionalExcluded += 1; continue; }
    subjects.add(o.subject.instrumentId);
    const prev = byBucket.get(o.payload.bucketTs);
    if (prev) { revisions += 1; if (o.knownAtTs > prev.knownAtTs || (o.knownAtTs === prev.knownAtTs && o.sequence > prev.sequence)) byBucket.set(o.payload.bucketTs, o); }
    else byBucket.set(o.payload.bucketTs, o);
  }
  if (subjects.size > 1) fail('INVALID_REQUEST', 'one instrument per series');
  const points = [...byBucket.values()].sort((a, b) => a.payload.bucketTs - b.payload.bucketTs).map((o) => ({ bucketTs: o.payload.bucketTs, values: o.payload.values, finality: o.payload.finality, knownAtTs: o.knownAtTs, observationId: o.observationId }));
  return { points, intervalMs, provisionalExcluded, revisions, instrumentId: [...subjects][0] ?? null };
}
// the last n CONTIGUOUS buckets ending at the latest bucket (gaps break contiguity; nulls break it too — never zero-filled)
function tail(series, field, n) {
  const pts = series.points; if (!pts.length) return { values: [], reasons: ['NO_BUCKETS'], endTs: null, startTs: null };
  const values = []; let i = pts.length - 1; let expected = pts[i].bucketTs;
  while (i >= 0 && values.length < n) { const p = pts[i]; if (p.bucketTs !== expected) break; const v = p.values ? p.values[field] : null; if (!isFiniteNum(v)) break; values.unshift(v); expected -= series.intervalMs; i -= 1; }
  const reasons = values.length < n ? [values.length === 0 ? 'VALUE_MISSING' : 'GAP'] : [];
  return { values, reasons, endTs: pts[pts.length - 1].bucketTs + series.intervalMs, startTs: pts[pts.length - 1].bucketTs + series.intervalMs - values.length * series.intervalMs };
}
const clocks = (series, asOfTs, t) => ({ asOfTs, windowStartTs: t.startTs, windowEndTs: t.endTs, inputKnownAtMax: knownMax(series.points), inputs: series.points.length });
export function level(id, series, { asOfTs }) { const t = tail(series, EDGE_RECIPES[id].field, 1); return out(id, t.values.length ? round(t.values[0]) : null, supportOf(t.values.length ? 'COMPLETE' : 'MISSING', t.reasons, { buckets: t.values.length, required: 1, provisionalExcluded: series.provisionalExcluded }), clocks(series, asOfTs, t)); }
export function change(id, series, { asOfTs }) { const t = tail(series, EDGE_RECIPES[id].field, 2); const ok = t.values.length === 2; return out(id, ok ? round(t.values[1] - t.values[0]) : null, supportOf(ok ? 'COMPLETE' : t.values.length ? 'PARTIAL' : 'MISSING', t.reasons, { buckets: t.values.length, required: 2, provisionalExcluded: series.provisionalExcluded }), clocks(series, asOfTs, t)); }
export function acceleration(id, series, { asOfTs }) { const t = tail(series, EDGE_RECIPES[id].field, 3); const ok = t.values.length === 3; return out(id, ok ? round((t.values[2] - t.values[1]) - (t.values[1] - t.values[0])) : null, supportOf(ok ? 'COMPLETE' : t.values.length ? 'PARTIAL' : 'MISSING', t.reasons, { buckets: t.values.length, required: 3, provisionalExcluded: series.provisionalExcluded }), clocks(series, asOfTs, t)); }
export function slope(id, series, { asOfTs, n = 6 }) { const t = tail(series, EDGE_RECIPES[id].field, n); const ok = t.values.length === n; let s = null; if (ok) { const m = (n - 1) / 2; const my = t.values.reduce((a, b) => a + b, 0) / n; let num = 0; let den = 0; t.values.forEach((y, i) => { num += (i - m) * (y - my); den += (i - m) ** 2; }); s = den > 0 ? round(num / den) : null; } return out(id, s, supportOf(ok ? 'COMPLETE' : t.values.length ? 'PARTIAL' : 'MISSING', t.reasons, { buckets: t.values.length, required: n, provisionalExcluded: series.provisionalExcluded }), clocks(series, asOfTs, t)); }
export function liquidationBurst(series, { asOfTs, trailing = 24 }) { const id = 'liquidation_bucket_burst'; const t = tail(series, 'value', trailing + 1); const ok = t.values.length === trailing + 1; let v = null; const reasons = [...t.reasons]; if (ok) { const base = median(t.values.slice(0, trailing)); if (base !== null && base > 0) v = round(t.values[trailing] / base); else reasons.push('ZERO_BASELINE'); } return out(id, v, supportOf(v !== null ? 'COMPLETE' : t.values.length ? 'PARTIAL' : 'MISSING', reasons, { buckets: t.values.length, required: trailing + 1, provisionalExcluded: series.provisionalExcluded }), clocks(series, asOfTs, t)); }
// the whole §7.1 block for one instrument at one interval: series per analytics type are built from the same observation set
export function derivativesPressure(observations, { intervalMs, asOfTs, slopeN = 6, burstTrailing = 24 }) {
  const S = (type) => analyticsSeries(observations, { analyticsType: type, intervalMs, asOfTs });
  const oi = S('open-interest'); const ag = S('aggressor-differential'); const cvd = S('cvd'); const liq = S('liquidation-volume'); const basis = S('future-basis'); const fund = S('funding');
  const c = {
    oi_bucket_level: level('oi_bucket_level', oi, { asOfTs }), oi_bucket_change: change('oi_bucket_change', oi, { asOfTs }), oi_bucket_acceleration: acceleration('oi_bucket_acceleration', oi, { asOfTs }),
    aggressor_bucket_level: level('aggressor_bucket_level', ag, { asOfTs }), aggressor_bucket_change: change('aggressor_bucket_change', ag, { asOfTs }), aggressor_bucket_slope: slope('aggressor_bucket_slope', ag, { asOfTs, n: slopeN }),
    cvd_bucket_change: change('cvd_bucket_change', cvd, { asOfTs }), cvd_bucket_slope: slope('cvd_bucket_slope', cvd, { asOfTs, n: slopeN }),
    liquidation_bucket_burst: liquidationBurst(liq, { asOfTs, trailing: burstTrailing }),
    basis_bucket_level: level('basis_bucket_level', basis, { asOfTs }), basis_bucket_change: change('basis_bucket_change', basis, { asOfTs }),
    funding_bucket_level: level('funding_bucket_level', fund, { asOfTs }), funding_bucket_change: change('funding_bucket_change', fund, { asOfTs }),
  };
  const v = (k) => c[k].value; const both = (a, b) => (a === null || b === null ? null : a && b);
  const combos = { oi_rising_aggressor_positive: both(v('oi_bucket_change') === null ? null : v('oi_bucket_change') > 0, v('aggressor_bucket_level') === null ? null : v('aggressor_bucket_level') > 0), oi_rising_aggressor_negative: both(v('oi_bucket_change') === null ? null : v('oi_bucket_change') > 0, v('aggressor_bucket_level') === null ? null : v('aggressor_bucket_level') < 0), oi_falling_cvd_negative: both(v('oi_bucket_change') === null ? null : v('oi_bucket_change') < 0, v('cvd_bucket_change') === null ? null : v('cvd_bucket_change') < 0), liquidation_burst_with_oi_drop: both(v('liquidation_bucket_burst') === null ? null : v('liquidation_bucket_burst') > 2, v('oi_bucket_change') === null ? null : v('oi_bucket_change') < 0), basis_widening_with_oi_rise: both(v('basis_bucket_change') === null ? null : v('basis_bucket_change') > 0, v('oi_bucket_change') === null ? null : v('oi_bucket_change') > 0) };
  const known = Object.values(combos).filter((x) => x !== null).length; const total = Object.keys(combos).length;
  c.pressure_combinations = out('pressure_combinations', combos, supportOf(known === total ? 'COMPLETE' : known ? 'PARTIAL' : 'MISSING', known === total ? [] : ['COMPONENT_MISSING'], { known, total }), { asOfTs, inputKnownAtMax: knownMax([...oi.points, ...ag.points, ...cvd.points, ...liq.points, ...basis.points]), inputs: oi.points.length + ag.points.length + cvd.points.length + liq.points.length + basis.points.length + fund.points.length });
  return deepFreeze({ recipeSetVersion: EDGE_RECIPE_SET_VERSION, family: 'DERIVATIVES_PRESSURE', asOfTs, intervalMs, components: c, descriptor: 'named descriptors over native series; not a signal', authority: 'NONE' });
}

// ---- §7.2 L3 microstructure over one market and one window (startTs, endTs], endTs <= asOfTs ------------------------------------
function l3Inputs(observations, { asOfTs, startTs, endTs }) {
  if (!isTs(startTs) || !isTs(endTs) || endTs <= startTs || endTs > asOfTs) fail('INVALID_REQUEST', 'window malformed or after the as-of');
  const adm = admissible(observations, asOfTs); const inWin = (o) => o.receivedTs > startTs && o.receivedTs <= endTs;
  const snaps = adm.filter((o) => o.kind === 'L3_BOOK_SNAPSHOT').sort((a, b) => a.receivedTs - b.receivedTs || a.sequence - b.sequence);
  const events = adm.filter((o) => o.kind === 'L3_ORDER_EVENT' && inWin(o)).sort((a, b) => a.receivedTs - b.receivedTs || a.sequence - b.sequence);
  const cov = adm.filter((o) => o.kind === 'L3_BOOK_COVERAGE' && inWin(o));
  const latest = snaps.filter((o) => o.receivedTs <= endTs).at(-1) ?? null; const inWindow = snaps.filter(inWin);
  const gap = cov.some((o) => ['GAP', 'DESYNCHRONIZED', 'DEGRADED', 'OVERFLOW', 'ACCESS_BLOCKED', 'UNSUBSCRIBED'].includes(o.payload.state)) || events.some((o) => o.quality.state !== 'KNOWN');
  const epochs = new Set([...events, ...inWindow].map((o) => o.epochId)); const epochBreak = epochs.size > 1;
  return { snaps: inWindow, latest, events, cov, gap, epochBreak, all: adm, clocks: { asOfTs, windowStartTs: startTs, windowEndTs: endTs, inputKnownAtMax: knownMax([...inWindow, ...events, ...cov, ...(latest ? [latest] : [])]), inputs: inWindow.length + events.length + cov.length } };
}
const sideEvents = (events, side) => events.flatMap((o) => o.payload.events.filter((e) => e.side === side));
const sum = (a) => a.reduce((x, y) => x + y, 0);
const imb = (b, a) => (isFiniteNum(b) && isFiniteNum(a) && b + a > 0 ? round((b - a) / (b + a)) : null);
const windowSupport = (inp, reasons = [], extra = {}) => supportOf(inp.gap || inp.epochBreak ? 'PARTIAL' : reasons.length ? 'PARTIAL' : 'COMPLETE', [...(inp.gap ? ['COVERAGE_GAP'] : []), ...(inp.epochBreak ? ['EPOCH_BREAK'] : []), ...reasons], { snapshots: inp.snaps.length, eventBatches: inp.events.length, ...extra });
export function visibleOrderAgeImbalance(observations, w) { const inp = l3Inputs(observations, w); const id = 'visible_order_age_imbalance'; if (!inp.latest || !inp.latest.payload.synchronized) return out(id, null, supportOf('MISSING', ['NO_SYNCHRONIZED_SNAPSHOT']), inp.clocks); const age = (list) => (list.length ? sum(list.map((o) => inp.latest.receivedTs - o.firstSeenTs)) / list.length : null); const b = age(inp.latest.payload.bids); const a = age(inp.latest.payload.asks); return out(id, imb(b, a), windowSupport(inp, b === null || a === null ? ['ONE_SIDED_BOOK'] : [], { meanAgeBidMs: b === null ? null : round(b, 0), meanAgeAskMs: a === null ? null : round(a, 0), snapshotTs: inp.latest.receivedTs }), inp.clocks); }
export function queueTurnoverImbalance(observations, w) { const inp = l3Inputs(observations, w); const id = 'queue_turnover_imbalance'; if (!inp.latest) return out(id, null, supportOf('MISSING', ['NO_SNAPSHOT']), inp.clocks); const rest = (s) => (s === 'BID' ? inp.latest.payload.bids : inp.latest.payload.asks).length; const turn = (s) => { const n = rest(s); return n > 0 ? sideEvents(inp.events, s).filter((e) => e.event !== 'SCOPE_EVICTED').length / n : null; }; const b = turn('BID'); const a = turn('ASK'); return out(id, imb(b, a), windowSupport(inp, b === null || a === null ? ['ONE_SIDED_BOOK'] : [], { turnoverBid: b === null ? null : round(b), turnoverAsk: a === null ? null : round(a) }), inp.clocks); }
export function depthPersistence(observations, w) { const inp = l3Inputs(observations, w); const id = 'depth_persistence'; if (inp.snaps.length < 2) return out(id, null, supportOf('MISSING', ['FEWER_THAN_TWO_SNAPSHOTS']), inp.clocks); const first = inp.snaps[0]; const last = inp.snaps.at(-1); const keep = (side) => { const f = first.payload[side]; if (!f.length) return null; const l = new Set(last.payload[side].map((o) => o.orderKey)); return round(f.filter((o) => l.has(o.orderKey)).length / f.length); }; const b = keep('bids'); const a = keep('asks'); return out(id, { bid: b, ask: a }, windowSupport(inp, [], { firstTs: first.receivedTs, lastTs: last.receivedTs, sameEpoch: first.epochId === last.epochId }), inp.clocks); }
export function newOrderImpulse(observations, w) { const inp = l3Inputs(observations, w); const id = 'new_order_impulse'; if (!inp.events.length) return out(id, null, supportOf(inp.gap ? 'PARTIAL' : 'MISSING', ['NO_EVENTS']), inp.clocks); const add = (s) => round(sum(sideEvents(inp.events, s).filter((e) => e.event === 'ADD').map((e) => e.qty))); const b = add('BID'); const a = add('ASK'); return out(id, { bid: b, ask: a, net: round(b - a) }, windowSupport(inp), inp.clocks); }
export function visibleLiquidityDisappearance(observations, w) { const inp = l3Inputs(observations, w); const id = 'visible_liquidity_disappearance'; if (!inp.events.length) return out(id, null, supportOf(inp.gap ? 'PARTIAL' : 'MISSING', ['NO_EVENTS']), inp.clocks); const q = (s, kind) => round(sum(sideEvents(inp.events, s).filter((e) => e.event === kind).map((e) => e.previousQty ?? 0))); const v = { bid: { deleted: q('BID', 'DELETE'), scopeEvicted: q('BID', 'SCOPE_EVICTED') }, ask: { deleted: q('ASK', 'DELETE'), scopeEvicted: q('ASK', 'SCOPE_EVICTED') }, gap: inp.gap || inp.epochBreak }; return out(id, v, windowSupport(inp, [], { law: 'DELETE is a removal from the visible book (fill, cancel or expiry — indistinguishable); SCOPE_EVICTED left the depth window and was not cancelled; a gap is unknown' }), inp.clocks); }
export function replenishmentAfterPressure(observations, w) { const inp = l3Inputs(observations, w); const id = 'replenishment_after_pressure'; if (!inp.events.length) return out(id, null, supportOf(inp.gap ? 'PARTIAL' : 'MISSING', ['NO_EVENTS']), inp.clocks); const flat = inp.events.flatMap((o) => o.payload.events.map((e, idx) => ({ ...e, receivedTs: o.receivedTs, seq: o.sequence, idx }))); const del = (s) => sum(flat.filter((e) => e.side === s && e.event === 'DELETE').map((e) => e.previousQty ?? 0)); const db = del('BID'); const da = del('ASK'); if (db === 0 && da === 0) return out(id, null, windowSupport(inp, ['NO_DELETES']), inp.clocks); const side = db >= da ? 'BID' : 'ASK'; const deletes = flat.filter((e) => e.side === side && e.event === 'DELETE'); const largest = deletes.reduce((m, e) => ((e.previousQty ?? 0) > (m.previousQty ?? 0) ? e : m), deletes[0]); const laterThan = (e, l) => e.receivedTs > l.receivedTs || (e.receivedTs === l.receivedTs && (e.seq > l.seq || (e.seq === l.seq && e.idx > l.idx))); const after = flat.filter((e) => e.side === side && e.event === 'ADD' && laterThan(e, largest)); const ratio = round(sum(after.map((e) => e.qty)) / (side === 'BID' ? db : da)); return out(id, { side, ratio, largestDeleteQty: round(largest.previousQty ?? 0), largestDeleteTs: largest.receivedTs, addedAfter: round(sum(after.map((e) => e.qty))) }, windowSupport(inp), inp.clocks); }
export function queueConcentration(observations, w) { const inp = l3Inputs(observations, w); const id = 'queue_concentration'; if (!inp.latest || !inp.latest.payload.synchronized) return out(id, null, supportOf('MISSING', ['NO_SYNCHRONIZED_SNAPSHOT']), inp.clocks); const side = (list) => { if (!list.length) return null; const touch = list[0].price; const lvl = list.filter((o) => o.price === touch); const q = sum(lvl.map((o) => o.qty)); const total = sum(list.map((o) => o.qty)); if (!(q > 0)) return { largestShare: null, herfindahl: null, touchShare: null, orders: lvl.length }; return { largestShare: round(Math.max(...lvl.map((o) => o.qty)) / q), herfindahl: round(sum(lvl.map((o) => (o.qty / q) ** 2))), touchShare: total > 0 ? round(q / total) : null, orders: lvl.length }; }; const b = side(inp.latest.payload.bids); const a = side(inp.latest.payload.asks); return out(id, { bid: b, ask: a }, windowSupport(inp, b === null || a === null ? ['ONE_SIDED_BOOK'] : [], { snapshotTs: inp.latest.receivedTs }), inp.clocks); }
export function orderAgeQuantiles(observations, w) { const inp = l3Inputs(observations, w); const id = 'order_age_quantiles'; if (!inp.latest || !inp.latest.payload.synchronized) return out(id, null, supportOf('MISSING', ['NO_SYNCHRONIZED_SNAPSHOT']), inp.clocks); const qs = (list) => { const ages = list.map((o) => inp.latest.receivedTs - o.firstSeenTs).sort((x, y) => x - y); return ages.length ? { p50Ms: nearestRank(ages, 50), p90Ms: nearestRank(ages, 90), n: ages.length } : null; }; const b = qs(inp.latest.payload.bids); const a = qs(inp.latest.payload.asks); return out(id, { bid: b, ask: a }, windowSupport(inp, b === null || a === null ? ['ONE_SIDED_BOOK'] : [], { snapshotTs: inp.latest.receivedTs, ageBasis: 'firstSeenTs within the current epoch (snapshot resets ages)' }), inp.clocks); }
export function topLevelChurn(observations, w) { const inp = l3Inputs(observations, w); const id = 'top_level_churn'; if (!inp.latest) return out(id, null, supportOf('MISSING', ['NO_SNAPSHOT']), inp.clocks); const touch = (list) => (list.length ? list[0].price : null); const tb = touch(inp.latest.payload.bids); const ta = touch(inp.latest.payload.asks); const n = (s, p) => (p === null ? null : sideEvents(inp.events, s).filter((e) => e.price === p).length); return out(id, { bid: n('BID', tb), ask: n('ASK', ta), touchBid: tb, touchAsk: ta }, windowSupport(inp, tb === null || ta === null ? ['ONE_SIDED_BOOK'] : []), inp.clocks); }
export function microstructurePressureChange(observations, w) { const id = 'microstructure_pressure_change'; const cur = l3Inputs(observations, w); const prev = l3Inputs(observations, { asOfTs: w.asOfTs, startTs: w.startTs - (w.endTs - w.startTs), endTs: w.startTs }); const share = (inp) => { if (!inp.events.length) return null; const b = sum(sideEvents(inp.events, 'BID').filter((e) => e.event === 'ADD').map((e) => e.qty)); const a = sum(sideEvents(inp.events, 'ASK').filter((e) => e.event === 'ADD').map((e) => e.qty)); return imb(b, a); }; const c = share(cur); const p = share(prev); return out(id, c === null || p === null ? null : round(c - p), supportOf(c !== null && p !== null && !cur.gap && !prev.gap ? 'COMPLETE' : c !== null || p !== null ? 'PARTIAL' : 'MISSING', [...(c === null ? ['CURRENT_WINDOW_EMPTY'] : []), ...(p === null ? ['PREVIOUS_WINDOW_EMPTY'] : []), ...(cur.gap || prev.gap ? ['COVERAGE_GAP'] : [])], { current: c, previous: p }), cur.clocks); }
export function l3Microstructure(observations, w) {
  const c = { visible_order_age_imbalance: visibleOrderAgeImbalance(observations, w), queue_turnover_imbalance: queueTurnoverImbalance(observations, w), depth_persistence: depthPersistence(observations, w), new_order_impulse: newOrderImpulse(observations, w), visible_liquidity_disappearance: visibleLiquidityDisappearance(observations, w), replenishment_after_pressure: replenishmentAfterPressure(observations, w), queue_concentration: queueConcentration(observations, w), order_age_quantiles: orderAgeQuantiles(observations, w), top_level_churn: topLevelChurn(observations, w), microstructure_pressure_change: microstructurePressureChange(observations, w) };
  return deepFreeze({ recipeSetVersion: EDGE_RECIPE_SET_VERSION, family: 'L3_MICROSTRUCTURE', asOfTs: w.asOfTs, windowStartTs: w.startTs, windowEndTs: w.endTs, components: c, descriptor: 'visible-book descriptors; not a signal', authority: 'NONE' });
}
