// MARKET LAB — THE IMMUTABLE SOURCE MANIFEST (§4). Every provider client requests ONLY endpoints declared here: fixed
// host, fixed path template, method, native version, authentication ENV NAME (never a value), families, mapping rule,
// cadence, lag, units, pagination, quota, plan requirement, license note, documentation URL and verification date.
// Provider URLs are chosen by this code, never by Socrates or by external text. Secret values never enter this file.
// Verified against official documentation on 2026-09-08 (see docs/MARKET-SOCRATES-ACCEPTANCE.md for the sources).
import { deepFreeze } from './contracts.js';

export const REGISTRY_VERSION = 'market-source-registry-1';
export const VERIFIED = '2026-09-08';
const ep = (providerId, endpointId, o) => ({ providerId, endpointId, method: 'GET', authEnv: null, authPlacement: 'NONE', nativeVersion: null, pagination: 'NONE', quota: null, planRequirement: 'PUBLIC', cadenceMs: null, lagMs: 0, granularity: null, units: null, license: 'per provider terms; research use only', verifiedDate: VERIFIED, ...o });

export const PROVIDERS = deepFreeze({
  KRAKEN_SPOT: { hosts: ['api.kraken.com', 'ws.kraken.com'], billing: 'FREE', name: 'Kraken spot (public REST + WS v2)', docs: 'https://docs.kraken.com/api-reference/market-data/get-ohlc-data', ticket: 'D01' },
  COINBASE_SPOT: { hosts: ['api.exchange.coinbase.com', 'ws-feed.exchange.coinbase.com'], billing: 'FREE', name: 'Coinbase Exchange public market data', docs: 'https://docs.cdp.coinbase.com/exchange/websocket-feed/channels', ticket: 'D02' },
  KRAKEN_DERIVATIVES: { hosts: ['futures.kraken.com'], billing: 'FREE', name: 'Kraken Derivatives public', docs: 'https://docs.kraken.com/api-reference/historical-funding-rates/historical-funding-rates', ticket: 'D03' },
  DERIBIT: { hosts: ['www.deribit.com'], billing: 'FREE', name: 'Deribit public', docs: 'https://docs.deribit.com/api-reference/market-data/public-ticker', ticket: 'D04' },
  BYBIT: { hosts: ['api.bybit.com', 'stream.bybit.com'], billing: 'FREE', name: 'Bybit v5 public market data', docs: 'https://bybit-exchange.github.io/docs/v5/websocket/public/all-liquidation', ticket: 'D05', accessNote: 'geographic restrictions apply (CloudFront 403 observed from this build environment); never evaded' },
  COINGECKO: { hosts: ['api.coingecko.com', 'pro-api.coingecko.com'], billing: 'INCLUDED_QUOTA', name: 'CoinGecko (keyless public / Demo key)', docs: 'https://docs.coingecko.com/reference/coins-markets', ticket: 'D06' },
  GECKOTERMINAL: { hosts: ['api.geckoterminal.com'], billing: 'FREE', name: 'GeckoTerminal public on-chain DEX', docs: 'https://apiguide.geckoterminal.com/', ticket: 'D06', independenceNote: 'same team as CoinGecko: not independent corroboration' },
  DEFILLAMA: { hosts: ['api.llama.fi', 'stablecoins.llama.fi', 'yields.llama.fi'], billing: 'FREE', name: 'DefiLlama open API', docs: 'https://github.com/DefiLlama/api-sdk', ticket: 'D07' },
  COINGLASS: { hosts: ['open-api-v4.coinglass.com'], billing: 'METERED', name: 'CoinGlass v4 (paid)', docs: 'https://docs.coinglass.com/reference/endpoint-overview', ticket: 'D08', pricing: { displayed: 'STARTUP $79/month equivalent billed $948/year; $1,140 comparison annual amount shown; monthly checkout amount unconfirmed', source: 'https://www.coinglass.com/pricing' } },
  CRYPTOQUANT: { hosts: ['api.cryptoquant.com'], billing: 'METERED', name: 'CryptoQuant v1 (paid)', docs: 'https://docs.cryptoquant.com/', ticket: 'D09', pricing: { displayed: 'Professional advertised $99/month on pricing page; author-program page calls Professional a $109/month value; billing period unreconciled', source: 'https://cryptoquant.com/pricing' } },
  SANTIMENT: { hosts: ['api.santiment.net'], billing: 'METERED', name: 'Santiment SanAPI (alternative)', docs: 'https://academy.santiment.net/for-developers/', ticket: 'D10', pricing: { displayed: 'Max advertised $249/month for real-time API; Pro website plan is not equivalent', source: 'https://app.santiment.net/pricing' } },
  COINMETRICS: { hosts: ['community-api.coinmetrics.io'], billing: 'FREE', name: 'Coin Metrics Community API v4', docs: 'https://gitbook-docs.coinmetrics.io/packages/coin-metrics-community-data', ticket: 'D11', note: 'documented community root is community-api.coinmetrics.io/v4; api.coinmetrics.io/v4 answers 401 without a key (observed 2026-09-08); 10 requests / 6 seconds' },
  FRED: { hosts: ['api.stlouisfed.org'], billing: 'FREE', name: 'FRED / ALFRED', docs: 'https://fred.stlouisfed.org/docs/api/fred/', ticket: 'D12', note: 'api_key travels as a query parameter by provider design; the transport redacts it from every diagnostic' },
  TWELVEDATA: { hosts: ['api.twelvedata.com'], billing: 'METERED', name: 'Twelve Data (paid-capable)', docs: 'https://twelvedata.com/docs', ticket: 'D13', pricing: { displayed: 'Grow from $29/month; exchange / non-display entitlements can require a different plan; 8 trial WS credits are not production streaming', source: 'https://twelvedata.com/pricing' } },
  SETTLED_RECORDS: { hosts: [], billing: 'FREE', name: 'Existing settled official / social / infrastructure / governance records (read-only projection)', docs: 'doctrine/RUMOR2.md', ticket: 'D14' },
  TOKENOMIST: { hosts: ['api.tokenomist.ai'], billing: 'METERED', name: 'Tokenomist API v5 (alternative)', docs: 'https://docs.tokenomist.ai/api-documents/introduction', ticket: 'D15', pricing: { displayed: 'Pro $69/month equivalent at $828/year vs $99 comparison; 300 API credits/month; only successful requests count; free trial duration/eligibility unestablished', source: 'https://tokenomist.ai/pricing' } },
});

export const ENDPOINTS = deepFreeze([
  // ---- D01 Kraken spot
  ep('KRAKEN_SPOT', 'rest-asset-pairs', { host: 'api.kraken.com', path: '/0/public/AssetPairs', families: ['SPOT_PRICE_CHART'], mapping: 'wsname base/quote; legacy aliases XBT->BTC, XDG->DOGE only', cadenceMs: 300_000, units: 'catalog', docs: 'https://docs.kraken.com/api-reference/market-data/get-tradable-asset-pairs' }),
  ep('KRAKEN_SPOT', 'rest-ticker', { host: 'api.kraken.com', path: '/0/public/Ticker', families: ['SPOT_PRICE_CHART', 'CROSS_VENUE'], mapping: 'pair key from AssetPairs', cadenceMs: 60_000, units: 'quote', docs: 'https://docs.kraken.com/api-reference/market-data/get-tickers' }),
  ep('KRAKEN_SPOT', 'rest-ohlc', { host: 'api.kraken.com', path: '/0/public/OHLC', families: ['SPOT_PRICE_CHART'], mapping: 'pair key from AssetPairs; interval minutes 1/5/15/60/240/1440', cadenceMs: 60_000, granularity: 'at most 720 most recent bars per interval; older data cannot be retrieved regardless of since', units: 'quote/base', docs: 'https://docs.kraken.com/api-reference/market-data/get-ohlc-data' }),
  ep('KRAKEN_SPOT', 'rest-trades', { host: 'api.kraken.com', path: '/0/public/Trades', families: ['SPOT_FLOW'], mapping: 'pair key; side b/s = taker side', pagination: 'since cursor (last id); bounded pages', cadenceMs: 60_000, docs: 'https://docs.kraken.com/api-reference/market-data/get-recent-trades' }),
  ep('KRAKEN_SPOT', 'ws-v2', { method: 'WS', host: 'ws.kraken.com', path: '/v2', families: ['SPOT_PRICE_CHART', 'SPOT_FLOW', 'DISPLAYED_LIQUIDITY', 'CROSS_VENUE'], mapping: 'channels trade (side = taker), book (checksum, snapshot/update), instrument (precision)', units: 'quote/base', docs: 'https://docs.kraken.com/exchange/api-reference/spot-websocket-v2/book' }),
  // ---- D02 Coinbase Exchange public
  ep('COINBASE_SPOT', 'rest-products', { host: 'api.exchange.coinbase.com', path: '/products', families: ['SPOT_PRICE_CHART'], mapping: 'product_id base-quote; fx_stablecoin flag; USD/USDC alias group', cadenceMs: 300_000, docs: 'https://docs.cdp.coinbase.com/api-reference/exchange-api/rest-api/products/get-products' }),
  ep('COINBASE_SPOT', 'rest-trades', { host: 'api.exchange.coinbase.com', path: '/products/{product_id}/trades', families: ['SPOT_FLOW'], mapping: 'side = MAKER order side (documented): taker side is the opposite', pagination: 'cursor headers CB-BEFORE/CB-AFTER; bounded pages', cadenceMs: 60_000, docs: 'https://docs.cdp.coinbase.com/api-reference/exchange-api/rest-api/products/get-product-trades' }),
  ep('COINBASE_SPOT', 'rest-book', { host: 'api.exchange.coinbase.com', path: '/products/{product_id}/book', families: ['DISPLAYED_LIQUIDITY'], mapping: 'level=2 aggregated best 50 per side [price,size,num_orders]', cadenceMs: 15_000, docs: 'https://docs.cdp.coinbase.com/api-reference/exchange-api/rest-api/products/get-product-book' }),
  ep('COINBASE_SPOT', 'rest-candles', { host: 'api.exchange.coinbase.com', path: '/products/{product_id}/candles', families: ['SPOT_PRICE_CHART'], mapping: 'granularity seconds 60/300/900/3600/21600/86400; rows [time,low,high,open,close,volume]; max 300 per request', cadenceMs: 60_000, docs: 'https://docs.cdp.coinbase.com/api-reference/exchange-api/rest-api/products/get-product-candles' }),
  ep('COINBASE_SPOT', 'ws-feed', { method: 'WS', host: 'ws-feed.exchange.coinbase.com', path: '/', families: ['SPOT_FLOW', 'DISPLAYED_LIQUIDITY', 'CROSS_VENUE'], mapping: 'channels matches (side = maker side; buy = down-tick), level2_batch (public, 50 ms batches)', docs: 'https://docs.cdp.coinbase.com/exchange/websocket-feed/channels' }),
  // ---- D03 Kraken Derivatives public
  ep('KRAKEN_DERIVATIVES', 'rest-instruments', { host: 'futures.kraken.com', path: '/derivatives/api/v3/instruments', families: ['DERIVATIVES_FUNDING_OI'], mapping: 'symbol, type (flexible_futures = linear multi-collateral, futures_inverse), contractSize, tickSize, tradeable', cadenceMs: 300_000, docs: 'https://docs.kraken.com/api-reference/kraken-futures/instruments/get-instruments' }),
  ep('KRAKEN_DERIVATIVES', 'rest-tickers', { host: 'futures.kraken.com', path: '/derivatives/api/v3/tickers', families: ['DERIVATIVES_FUNDING_OI', 'CROSS_VENUE'], mapping: 'markPrice, indexPrice, openInterest (contracts), fundingRate (ABSOLUTE native), fundingRatePrediction; hourly funding', cadenceMs: 60_000, units: 'native absolute funding; relative = fundingRate/markPrice per docs', docs: 'https://docs.kraken.com/api-reference/kraken-futures/market-data/get-tickers' }),
  ep('KRAKEN_DERIVATIVES', 'rest-funding-history', { host: 'futures.kraken.com', path: '/derivatives/api/v4/historicalfundingrates', families: ['DERIVATIVES_FUNDING_OI'], mapping: 'symbol; rates[{timestamp, fundingRate (absolute), relativeFundingRate}] hourly', cadenceMs: 3_600_000, docs: 'https://docs.kraken.com/api-reference/historical-funding-rates/historical-funding-rates' }),
  // ---- D04 Deribit public
  ep('DERIBIT', 'get-instruments', { host: 'www.deribit.com', path: '/api/v2/public/get_instruments', families: ['OPTIONS_TERM_SKEW', 'DERIVATIVES_FUNDING_OI'], mapping: 'currency + kind; full census in one response (no pagination); instrument_name, strike, option_type, expiration_timestamp, settlement_currency, contract_size', cadenceMs: 300_000, docs: 'https://docs.deribit.com/api-reference/market-data/public-get_instruments' }),
  ep('DERIBIT', 'get-book-summary-by-currency', { host: 'www.deribit.com', path: '/api/v2/public/get_book_summary_by_currency', families: ['OPTIONS_TERM_SKEW', 'DERIVATIVES_FUNDING_OI'], mapping: 'mark_iv (PERCENT native -> fraction), open_interest, volume, bid/ask price, underlying_price, underlying_index, current_funding, funding_8h', cadenceMs: 300_000, units: 'iv percent native', docs: 'https://docs.deribit.com/api-reference/market-data/public-get_book_summary_by_currency' }),
  ep('DERIBIT', 'ticker', { host: 'www.deribit.com', path: '/api/v2/public/ticker', families: ['OPTIONS_TERM_SKEW', 'DERIVATIVES_FUNDING_OI'], mapping: 'greeks.delta/gamma/vega/theta, mark_iv/bid_iv/ask_iv (percent native), open_interest, mark_price, index_price, funding_8h, current_funding', cadenceMs: 300_000, docs: 'https://docs.deribit.com/api-reference/market-data/public-ticker' }),
  // ---- D05 Bybit public
  ep('BYBIT', 'rest-instruments', { host: 'api.bybit.com', path: '/v5/market/instruments-info', families: ['DERIVATIVES_FUNDING_OI', 'LIQUIDATIONS'], mapping: 'category linear/inverse; symbol, contractType, settleCoin, fundingInterval (minutes), lotSizeFilter', pagination: 'cursor', cadenceMs: 300_000, docs: 'https://bybit-exchange.github.io/docs/v5/market/instrument' }),
  ep('BYBIT', 'rest-tickers', { host: 'api.bybit.com', path: '/v5/market/tickers', families: ['DERIVATIVES_FUNDING_OI', 'CROSS_VENUE'], mapping: 'markPrice, indexPrice, openInterest, openInterestValue, fundingRate (fraction per interval), nextFundingTime', cadenceMs: 60_000, docs: 'https://bybit-exchange.github.io/docs/v5/market/tickers' }),
  ep('BYBIT', 'ws-public-linear', { method: 'WS', host: 'stream.bybit.com', path: '/v5/public/linear', families: ['LIQUIDATIONS', 'DERIVATIVES_FUNDING_OI'], mapping: 'topics allLiquidation.{symbol} (S = liquidated POSITION side: Buy = long liquidated), tickers.{symbol} (snapshot/delta; omitted delta field = unchanged only inside a valid same-epoch snapshot)', docs: 'https://bybit-exchange.github.io/docs/v5/websocket/public/all-liquidation' }),
  // ---- D06 CoinGecko / GeckoTerminal
  ep('COINGECKO', 'coins-list', { host: 'api.coingecko.com', path: '/api/v3/coins/list', authEnv: 'COINGECKO_DEMO_API_KEY', authPlacement: 'HEADER_OPTIONAL', families: ['SUPPLY_UNLOCKS'], mapping: 'id, symbol, name, platforms (chain -> contract) with include_platform=true', cadenceMs: 86_400_000, planRequirement: 'PUBLIC_OR_DEMO', docs: 'https://docs.coingecko.com/reference/coins-list' }),
  ep('COINGECKO', 'coins-markets', { host: 'api.coingecko.com', path: '/api/v3/coins/markets', authEnv: 'COINGECKO_DEMO_API_KEY', authPlacement: 'HEADER_OPTIONAL', families: ['SUPPLY_UNLOCKS'], mapping: 'vs_currency=usd, ids; market_cap, fully_diluted_valuation, circulating/total/max supply, total_volume, last_updated', cadenceMs: 300_000, planRequirement: 'PUBLIC_OR_DEMO', quota: 'Demo: 30 calls/min, 10,000/month (inspect the supplied plan)', docs: 'https://docs.coingecko.com/reference/coins-markets' }),
  ep('COINGECKO', 'coin-detail', { host: 'api.coingecko.com', path: '/api/v3/coins/{id}', authEnv: 'COINGECKO_DEMO_API_KEY', authPlacement: 'HEADER_OPTIONAL', families: ['SUPPLY_UNLOCKS'], mapping: 'categories, platforms/detail_platforms, market_data', cadenceMs: 3_600_000, planRequirement: 'PUBLIC_OR_DEMO', docs: 'https://docs.coingecko.com/reference/coins-id' }),
  ep('GECKOTERMINAL', 'token-pools', { host: 'api.geckoterminal.com', path: '/api/v2/networks/{network}/tokens/{address}/pools', families: ['DEX_DEFI'], mapping: 'pool discovery by token contract', cadenceMs: 3_600_000, quota: '30 calls/min public', docs: 'https://apiguide.geckoterminal.com/' }),
  ep('GECKOTERMINAL', 'pool', { host: 'api.geckoterminal.com', path: '/api/v2/networks/{network}/pools/{address}', families: ['DEX_DEFI'], mapping: 'attributes: base_token_price_usd, reserve_in_usd (total pool value, NOT executable depth), volume_usd (rolling), transactions, pool_created_at, pool_fee_percentage', cadenceMs: 300_000, docs: 'https://apiguide.geckoterminal.com/' }),
  ep('GECKOTERMINAL', 'pool-ohlcv', { host: 'api.geckoterminal.com', path: '/api/v2/networks/{network}/pools/{address}/ohlcv/{timeframe}', families: ['DEX_DEFI'], mapping: 'ohlcv_list [ts, o, h, l, c, v]; timeframe day/hour/minute with aggregate', cadenceMs: 3_600_000, docs: 'https://docs.coingecko.com/reference/pool-ohlcv-contract-address' }),
  // ---- D07 DefiLlama open
  ep('DEFILLAMA', 'tvl', { host: 'api.llama.fi', path: '/tvl/{slug}', families: ['DEX_DEFI'], mapping: 'current total protocol TVL (USD scalar; includes price effects)', cadenceMs: 3_600_000, docs: 'https://github.com/DefiLlama/api-sdk' }),
  ep('DEFILLAMA', 'protocol', { host: 'api.llama.fi', path: '/protocol/{slug}', families: ['DEX_DEFI'], mapping: 'currentChainTvls per chain (USD; includes price effects); the full history body can exceed 8 MiB, so this route carries an explicit 32 MiB bound and is requested only when per-chain detail is wanted', cadenceMs: 3_600_000, docs: 'https://github.com/DefiLlama/api-sdk' }),
  ep('DEFILLAMA', 'chains', { host: 'api.llama.fi', path: '/v2/chains', families: ['DEX_DEFI'], mapping: 'chain tvl USD', cadenceMs: 3_600_000, docs: 'https://github.com/DefiLlama/api-sdk' }),
  ep('DEFILLAMA', 'fees-summary', { host: 'api.llama.fi', path: '/summary/fees/{slug}', families: ['DEX_DEFI'], mapping: 'dataType dailyFees | dailyRevenue; total24h, total7d (USD-valued; gross vs net differ)', cadenceMs: 3_600_000, docs: 'https://github.com/DefiLlama/api-sdk' }),
  ep('DEFILLAMA', 'dexs-summary', { host: 'api.llama.fi', path: '/summary/dexs/{slug}', families: ['DEX_DEFI'], mapping: 'total24h dex volume USD', cadenceMs: 3_600_000, docs: 'https://github.com/DefiLlama/api-sdk' }),
  ep('DEFILLAMA', 'stablecoins', { host: 'stablecoins.llama.fi', path: '/stablecoins', families: ['STABLECOIN_LIQUIDITY'], mapping: 'includePrices=true; circulating by peg type, price, chainCirculating per chain', cadenceMs: 3_600_000, docs: 'https://github.com/DefiLlama/api-sdk' }),
  ep('DEFILLAMA', 'stablecoin', { host: 'stablecoins.llama.fi', path: '/stablecoin/{id}', families: ['STABLECOIN_LIQUIDITY'], mapping: 'chainBalances history (bridged balances are NOT counted twice)', cadenceMs: 3_600_000, docs: 'https://github.com/DefiLlama/api-sdk' }),
  ep('DEFILLAMA', 'yields-pools', { host: 'yields.llama.fi', path: '/pools', families: ['DEX_DEFI'], mapping: 'apy / apyBase / apyBaseBorrow per pool (APY is not a funding rate)', cadenceMs: 3_600_000, docs: 'https://github.com/DefiLlama/api-sdk' }),
  // ---- D08 CoinGlass v4 (paid)
  ep('COINGLASS', 'supported-coins', { host: 'open-api-v4.coinglass.com', path: '/api/futures/supported-coins', authEnv: 'COINGLASS_API_KEY', authPlacement: 'HEADER', families: ['DERIVATIVES_FUNDING_OI'], mapping: 'coin symbols list', cadenceMs: 86_400_000, planRequirement: 'HOBBYIST', docs: 'https://docs.coinglass.com/reference/coins' }),
  ep('COINGLASS', 'supported-exchanges', { host: 'open-api-v4.coinglass.com', path: '/api/futures/supported-exchanges', authEnv: 'COINGLASS_API_KEY', authPlacement: 'HEADER', families: ['DERIVATIVES_FUNDING_OI'], mapping: 'exchange list', cadenceMs: 86_400_000, planRequirement: 'HOBBYIST', docs: 'https://docs.coinglass.com/reference/supported-exchanges' }),
  ep('COINGLASS', 'coin-vesting', { host: 'open-api-v4.coinglass.com', path: '/api/coin/vesting', authEnv: 'COINGLASS_API_KEY', authPlacement: 'HEADER', families: ['SUPPLY_UNLOCKS'], mapping: 'symbol; allocations[] with is_untracked, unlock_type, next_unlock{date, amount}, total_locked/unlocked/untracked, circulating_supply', cadenceMs: 86_400_000, planRequirement: 'STARTUP', docs: 'https://docs.coinglass.com/reference/token-vesting' }),
  ep('COINGLASS', 'coin-unlock-list', { host: 'open-api-v4.coinglass.com', path: '/api/coin/unlock-list', authEnv: 'COINGLASS_API_KEY', authPlacement: 'HEADER', families: ['SUPPLY_UNLOCKS'], mapping: 'symbol, total_locked/unlocked, circulating_supply, next_unlock_date (ms), next_unlock_tokens', cadenceMs: 86_400_000, planRequirement: 'STARTUP', docs: 'https://docs.coinglass.com/reference/coin-unlock-list' }),
  ep('COINGLASS', 'economic-data', { host: 'open-api-v4.coinglass.com', path: '/api/calendar/economic-data', authEnv: 'COINGLASS_API_KEY', authPlacement: 'HEADER', families: ['MACRO_RELEASES'], mapping: 'start_time/end_time ms; calendar_name, country_code, forecast_value, previous_value, revised_previous_value, published_value, publish_timestamp, has_exact_publish_time, importance_level', cadenceMs: 600_000, planRequirement: 'STARTUP', docs: 'https://docs.coinglass.com/reference/economic-data' }),
  ep('COINGLASS', 'etf-bitcoin-flow-history', { host: 'open-api-v4.coinglass.com', path: '/api/etf/bitcoin/flow-history', authEnv: 'COINGLASS_API_KEY', authPlacement: 'HEADER', families: ['ETF_FLOWS'], mapping: 'timestamp (day ms), flow_usd, price_usd, etf_flows[{etf_ticker, flow_usd}] — periodic reported estimates', cadenceMs: 3_600_000, planRequirement: 'HOBBYIST', docs: 'https://docs.coinglass.com/reference/etf-flows-history' }),
  ep('COINGLASS', 'etf-ethereum-flow-history', { host: 'open-api-v4.coinglass.com', path: '/api/etf/ethereum/flow-history', authEnv: 'COINGLASS_API_KEY', authPlacement: 'HEADER', families: ['ETF_FLOWS'], mapping: 'as bitcoin flow history', cadenceMs: 3_600_000, planRequirement: 'HOBBYIST', docs: 'https://docs.coinglass.com/reference/ethereum-etf-flows-history' }),
  ep('COINGLASS', 'oi-exchange-list', { host: 'open-api-v4.coinglass.com', path: '/api/futures/open-interest/exchange-list', authEnv: 'COINGLASS_API_KEY', authPlacement: 'HEADER', families: ['DERIVATIVES_FUNDING_OI'], mapping: 'symbol; per exchange open_interest_usd, open_interest_quantity (aggregated, provider methodology)', cadenceMs: 300_000, planRequirement: 'HOBBYIST', docs: 'https://docs.coinglass.com/reference/oi-exchange-list' }),
  ep('COINGLASS', 'funding-exchange-list', { host: 'open-api-v4.coinglass.com', path: '/api/futures/funding-rate/exchange-list', authEnv: 'COINGLASS_API_KEY', authPlacement: 'HEADER', families: ['DERIVATIVES_FUNDING_OI'], mapping: 'stablecoin_margin_list / token_margin_list: exchange, funding_rate (fraction), funding_rate_interval (hours), next_funding_time', cadenceMs: 300_000, planRequirement: 'HOBBYIST', docs: 'https://docs.coinglass.com/reference/fr-exchange-list' }),
  ep('COINGLASS', 'liquidation-aggregated-history', { host: 'open-api-v4.coinglass.com', path: '/api/futures/liquidation/aggregated-history', authEnv: 'COINGLASS_API_KEY', authPlacement: 'HEADER', families: ['LIQUIDATIONS'], mapping: 'exchange_list, symbol, interval; aggregated_long_liquidation_usd / aggregated_short_liquidation_usd per bucket (provider coverage decides whether zero is meaningful)', cadenceMs: 300_000, planRequirement: 'HOBBYIST', docs: 'https://docs.coinglass.com/reference/aggregated-liquidation-history' }),
  ep('COINGLASS', 'article-list', { host: 'open-api-v4.coinglass.com', path: '/api/article/list', authEnv: 'COINGLASS_API_KEY', authPlacement: 'HEADER', families: ['OFFICIAL_SOCIAL_EVENTS'], mapping: 'article_title (bounded, untrusted), source_name, article_release_time — headline references only; bodies are never persisted', cadenceMs: 600_000, planRequirement: 'HOBBYIST', docs: 'https://docs.coinglass.com/reference/article-list' }),
  // ---- D09 CryptoQuant (paid)
  ep('CRYPTOQUANT', 'exchange-flows', { host: 'api.cryptoquant.com', path: '/v1/{asset}/exchange-flows/{metric}', authEnv: 'CRYPTOQUANT_API_KEY', authPlacement: 'BEARER', families: ['ONCHAIN_ENTITY_FLOW'], mapping: 'metric netflow|inflow|outflow|reserve|transactions-count|addresses-count; exchange (entity set), window day|hour|block, from/to YYYYMMDD[THHMMSS], limit; result.data[{date|datetime, value...}]', pagination: 'limit + from/to', cadenceMs: 3_600_000, planRequirement: 'PLAN_WINDOW_ENTITLEMENT', docs: 'https://docs.cryptoquant.com/openapi/v1.json' }),
  ep('CRYPTOQUANT', 'network-data', { host: 'api.cryptoquant.com', path: '/v1/{asset}/network-data/{metric}', authEnv: 'CRYPTOQUANT_API_KEY', authPlacement: 'BEARER', families: ['NETWORK_ACTIVITY'], mapping: 'metric addresses-count|transactions-count|tokens-transferred|supply|fees; window day|hour|block', cadenceMs: 3_600_000, planRequirement: 'PLAN_WINDOW_ENTITLEMENT', docs: 'https://docs.cryptoquant.com/openapi/v1.json' }),
  ep('CRYPTOQUANT', 'market-indicator', { host: 'api.cryptoquant.com', path: '/v1/{asset}/market-indicator/{metric}', authEnv: 'CRYPTOQUANT_API_KEY', authPlacement: 'BEARER', families: ['NETWORK_ACTIVITY'], mapping: 'metric mvrv|sopr|realized-price|stablecoin-supply-ratio (provider definitions)', cadenceMs: 3_600_000, planRequirement: 'PLAN_WINDOW_ENTITLEMENT', docs: 'https://docs.cryptoquant.com/openapi/v1.json' }),
  ep('CRYPTOQUANT', 'stablecoin-exchange-flows', { host: 'api.cryptoquant.com', path: '/v1/stablecoin/exchange-flows/{metric}', authEnv: 'CRYPTOQUANT_API_KEY', authPlacement: 'BEARER', families: ['STABLECOIN_LIQUIDITY'], mapping: 'metric reserve|netflow|inflow; token, exchange, window', cadenceMs: 3_600_000, planRequirement: 'PLAN_WINDOW_ENTITLEMENT', docs: 'https://docs.cryptoquant.com/openapi/v1.json' }),
  ep('CRYPTOQUANT', 'miner-flows', { host: 'api.cryptoquant.com', path: '/v1/{asset}/miner-flows/{metric}', authEnv: 'CRYPTOQUANT_API_KEY', authPlacement: 'BEARER', families: ['ONCHAIN_ENTITY_FLOW'], mapping: 'metric reserve|netflow; miner entity', cadenceMs: 3_600_000, planRequirement: 'PLAN_WINDOW_ENTITLEMENT', docs: 'https://docs.cryptoquant.com/openapi/v1.json' }),
  // ---- D10 Santiment (alternative, paid)
  ep('SANTIMENT', 'graphql-get-metric', { method: 'POST', host: 'api.santiment.net', path: '/graphql', authEnv: 'SANTIMENT_API_KEY', authPlacement: 'HEADER_APIKEY', families: ['ONCHAIN_ENTITY_FLOW', 'NETWORK_ACTIVITY'], mapping: 'getMetric(metric){timeseriesData(slug, from, to, interval){datetime value}}; metrics exchange_inflow, exchange_outflow, exchange_balance, daily_active_addresses, transaction_volume, dev_activity, circulation_1d, whale_transaction_count_100k_usd_to_inf, whale_transaction_count_1m_usd_to_inf, whale_transaction_volume_100k_usd_to_inf, whale_transaction_volume_1m_usd_to_inf (restricted; 5m native interval for the four whale metrics) (only under supplied entitlement)', cadenceMs: 3_600_000, planRequirement: 'SANAPI_PLAN', docs: 'https://academy.santiment.net/for-developers/' }),
  // ---- D11 Coin Metrics community
  ep('COINMETRICS', 'catalog-asset-metrics', { host: 'community-api.coinmetrics.io', path: '/v4/catalog-v2/asset-metrics', families: ['NETWORK_ACTIVITY'], mapping: 'assets; metrics[].frequencies[{frequency, min_time, max_time, community}]', pagination: 'next_page_token', cadenceMs: 86_400_000, quota: '10 requests / 6 seconds', docs: 'https://gitbook-docs.coinmetrics.io/api-reference' }),
  ep('COINMETRICS', 'timeseries-asset-metrics', { host: 'community-api.coinmetrics.io', path: '/v4/timeseries/asset-metrics', families: ['NETWORK_ACTIVITY'], mapping: 'assets, metrics (AdrActCnt, TxCnt, TxTfrValNtv, FeeTotNtv, CapMrktCurUSD, CapRealUSD, SplyCur...), frequency 1d, page_size, paging_from=end; values are strings', pagination: 'next_page_token', cadenceMs: 3_600_000, quota: '10 requests / 6 seconds', docs: 'https://gitbook-docs.coinmetrics.io/api-reference' }),
  // ---- D12 FRED / ALFRED
  ep('FRED', 'series', { host: 'api.stlouisfed.org', path: '/fred/series', authEnv: 'FRED_API_KEY', authPlacement: 'QUERY', families: ['MACRO_RELEASES'], mapping: 'series_id; units, frequency, title, last_updated', cadenceMs: 86_400_000, docs: 'https://fred.stlouisfed.org/docs/api/fred/series.html' }),
  ep('FRED', 'series-observations', { host: 'api.stlouisfed.org', path: '/fred/series/observations', authEnv: 'FRED_API_KEY', authPlacement: 'QUERY', families: ['MACRO_RELEASES'], mapping: 'series_id, observation_start/end, realtime_start/end (ALFRED vintages); observations[{date, value, realtime_start, realtime_end}]; "." = missing', pagination: 'limit/offset', cadenceMs: 3_600_000, lagMs: 0, docs: 'https://fred.stlouisfed.org/docs/api/fred/series_observations.html' }),
  ep('FRED', 'series-vintagedates', { host: 'api.stlouisfed.org', path: '/fred/series/vintagedates', authEnv: 'FRED_API_KEY', authPlacement: 'QUERY', families: ['MACRO_RELEASES'], mapping: 'vintage_dates[] (revision context, NOT sub-minute availability proof)', cadenceMs: 86_400_000, docs: 'https://fred.stlouisfed.org/docs/api/fred/series_vintagedates.html' }),
  ep('FRED', 'releases-dates', { host: 'api.stlouisfed.org', path: '/fred/releases/dates', authEnv: 'FRED_API_KEY', authPlacement: 'QUERY', families: ['MACRO_RELEASES'], mapping: 'release_dates[{release_id, release_name, date}] (date-only precision)', cadenceMs: 86_400_000, docs: 'https://fred.stlouisfed.org/docs/api/fred/releases_dates.html' }),
  // ---- D13 Twelve Data
  ep('TWELVEDATA', 'symbol-search', { host: 'api.twelvedata.com', path: '/symbol_search', authEnv: 'TWELVEDATA_API_KEY', authPlacement: 'HEADER_APIKEY', families: ['CROSS_ASSET'], mapping: 'symbol -> instrument_name, exchange, mic_code, instrument_type, currency', cadenceMs: 86_400_000, planRequirement: 'PLAN_ENTITLEMENT', docs: 'https://twelvedata.com/docs#symbol-search' }),
  ep('TWELVEDATA', 'quote', { host: 'api.twelvedata.com', path: '/quote', authEnv: 'TWELVEDATA_API_KEY', authPlacement: 'HEADER_APIKEY', families: ['CROSS_ASSET'], mapping: 'symbol, exchange; is_market_open, timestamp, close, currency; delayed vs real-time depends on plan', cadenceMs: 60_000, planRequirement: 'PLAN_ENTITLEMENT', docs: 'https://twelvedata.com/docs#quote' }),
  ep('TWELVEDATA', 'time-series', { host: 'api.twelvedata.com', path: '/time_series', authEnv: 'TWELVEDATA_API_KEY', authPlacement: 'HEADER_APIKEY', families: ['CROSS_ASSET'], mapping: 'symbol, interval (1min..1day), outputsize, timezone=UTC; meta{exchange, currency, type}, values[{datetime, open, high, low, close, volume}]', cadenceMs: 60_000, planRequirement: 'PLAN_ENTITLEMENT', quota: 'credits per call by plan', docs: 'https://twelvedata.com/docs#time-series' }),
  // ---- D14 existing settled records (read-only projection; no network of its own)
  ep('SETTLED_RECORDS', 'official-claims', { host: null, path: null, families: ['OFFICIAL_SOCIAL_EVENTS'], mapping: 'RUMOR2 settled claim / source observations via the composition-injected read-only accessor', docs: 'doctrine/RUMOR2.md' }),
  ep('SETTLED_RECORDS', 'social-dossier', { host: null, path: null, families: ['OFFICIAL_SOCIAL_EVENTS'], mapping: 'Social research dossier / composite projection (detached DTO) via the collector accessor', docs: 'doctrine/SOCIAL.md' }),
  ep('SETTLED_RECORDS', 'governance-status', { host: null, path: null, families: ['OFFICIAL_SOCIAL_EVENTS'], mapping: 'governance collector status / proposal records (atomic status file)', docs: 'doctrine/GOVERNANCE.md' }),
  ep('SETTLED_RECORDS', 'gateway-status', { host: null, path: null, families: ['INFRASTRUCTURE_STATUS'], mapping: 'gateway friction collector door matrix (venue status pages; experimental)', docs: 'gateway/collector.js' }),
  // ---- D15 Tokenomist (alternative, paid)
  ep('TOKENOMIST', 'token-list', { host: 'api.tokenomist.ai', path: '/v5/token/list', authEnv: 'TOKENOMIST_API_KEY', authPlacement: 'HEADER', families: ['SUPPLY_UNLOCKS'], mapping: 'tokenId slugs (optional filter); credit metadata.credit{used, limit, resetAt}', cadenceMs: 86_400_000, planRequirement: 'PRO', quota: 'Pro 300 credits/month; only successful requests count; 120 req/min', docs: 'https://docs.tokenomist.ai/api-documents/token-list/v5' }),
  ep('TOKENOMIST', 'unlock-events', { host: 'api.tokenomist.ai', path: '/v5/unlock/events/{tokenId}', authEnv: 'TOKENOMIST_API_KEY', authPlacement: 'HEADER', families: ['SUPPLY_UNLOCKS'], mapping: 'start/end YYYY-MM-DD, page/pageSize; cliff events with allocations[{allocationName, standardAllocation, cliffAmount, cliffValue}]', pagination: 'page/pageSize', cadenceMs: 86_400_000, planRequirement: 'PRO', docs: 'https://docs.tokenomist.ai/api-documents/unlock-events/v5' }),
  ep('TOKENOMIST', 'upcoming-unlock-events', { host: 'api.tokenomist.ai', path: '/v5/unlock/events/upcoming', authEnv: 'TOKENOMIST_API_KEY', authPlacement: 'HEADER', families: ['SUPPLY_UNLOCKS'], mapping: 'start/end, minMarketCap, page/pageSize; bulk upcoming events across tokens (bulk route: one call covers many assets)', pagination: 'page/pageSize', cadenceMs: 86_400_000, planRequirement: 'PRO', docs: 'https://docs.tokenomist.ai/api-documents/upcoming-unlock-events/v5' }),
  ep('TOKENOMIST', 'allocations', { host: 'api.tokenomist.ai', path: '/v5/allocations/{tokenId}', authEnv: 'TOKENOMIST_API_KEY', authPlacement: 'HEADER', families: ['SUPPLY_UNLOCKS'], mapping: 'maxSupply, allocations with locked / unlocked by category', cadenceMs: 86_400_000, planRequirement: 'PRO', docs: 'https://docs.tokenomist.ai/api-documents/allocations/v5' }),
  ep('TOKENOMIST', 'daily-emission', { host: 'api.tokenomist.ai', path: '/v5/daily-emission/{tokenId}', authEnv: 'TOKENOMIST_API_KEY', authPlacement: 'HEADER', families: ['SUPPLY_UNLOCKS'], mapping: 'daily unlockAmount / unlockValue / totalCumulativeUnlockedAmount; linear + cliff', pagination: 'page/pageSize', cadenceMs: 86_400_000, planRequirement: 'PRO', docs: 'https://docs.tokenomist.ai/api-documents/daily-emission/v5' }),
]);

export const endpointOf = (providerId, endpointId) => ENDPOINTS.find((e) => e.providerId === providerId && e.endpointId === endpointId) ?? null;
export const endpointsOf = (providerId) => ENDPOINTS.filter((e) => e.providerId === providerId);
export const providerHosts = (providerId) => PROVIDERS[providerId]?.hosts ?? [];
export const providersForFamily = (family) => [...new Set(ENDPOINTS.filter((e) => e.families.includes(family)).map((e) => e.providerId))];

// §3 cost planning facts — planning inputs, never permission to subscribe and never an all-inclusive bill
export const COST_FACTS = deepFreeze({
  planningComparisonUsdPerMonthEquivalent: { coinglassStartup: 79, cryptoquantProfessional: 99, twelvedataGrow: 29, sum: 207, note: 'before model usage, tax, hosting, coverage upgrades and billing-term differences; NOT an all-inclusive quote; do not enroll in annual plans to obtain it' },
  observations: [
    { provider: 'COINGECKO', displayed: '$0 Demo/keyless option; Demo quota and paid endpoint access differ', source: 'https://www.coingecko.com/en/api/pricing' },
    { provider: 'COINGLASS', displayed: 'STARTUP $79/month equivalent billed $948/year; $1,140 comparison annual; monthly checkout unconfirmed; token vesting + economic calendar require STARTUP or above', source: 'https://www.coinglass.com/pricing' },
    { provider: 'CRYPTOQUANT', displayed: 'Professional $99/month (pricing page) vs "$109/month value" (author program); billing period / window entitlements unreconciled', source: 'https://cryptoquant.com/pricing' },
    { provider: 'TWELVEDATA', displayed: 'Grow from $29/month; entitlements may require a different plan; 8 trial WS credits are not production streaming', source: 'https://twelvedata.com/pricing' },
    { provider: 'SANTIMENT', displayed: 'Max $249/month for real-time API; Pro website plan not equivalent', source: 'https://app.santiment.net/pricing' },
    { provider: 'TOKENOMIST', displayed: 'Pro $69/month equivalent at $828/year vs $99 comparison; 300 API calls/month; free trial duration/eligibility unestablished', source: 'https://tokenomist.ai/pricing' },
    { provider: 'DEFILLAMA', displayed: 'Open API distinct from $49/month Pro UI and $300/month API plan; 7-day Pro trial is not API entitlement', source: 'https://docs.llama.fi/pro-api' },
  ],
  billingStates: ['FEED_OFF_STOPS_NEW_CALLS', 'SUBSCRIPTION_STILL_ACTIVE', 'VENDOR_BILLING_CONTINUES'], // reported separately: turning a feed off cancels nothing
});
