// SERPENT PAPER — the REPOSITORY-WIDE SENSOR INVENTORY, derived from the ACTUAL registries (market-lab/registry.js, the paper
// market-research policy, rumor2/registry.js, rumor2/social-registry.js, cobra.config.json gateway sources) plus the curated
// composition facts of the core / decision components (module + startup path). Every row is classified with the closed
// closeout vocabulary; a doctrine mention never resurrects a sense the repository does not implement. Read-only, no network.
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { loadConfig } from '../lib/config.js';
import { PROVIDERS as MARKET_PROVIDERS } from '../market-lab/registry.js';
import { PROVIDER_IDS as MARKET_PROVIDER_IDS } from '../market-lab/contracts.js';
import { PROVIDERS as OFFICIAL_PROVIDERS } from '../rumor2/registry.js';
import { SOCIAL_PROVIDERS } from '../rumor2/social-registry.js';
import { loadProfile, profileFileOf, secretPresence } from './profile.js';
import { PRESS_SOURCES } from '../press/registry.js';
import { INFRA_SOURCES } from '../infra/registry.js';

export const INVENTORY_VERSION = 'serpent-sensor-inventory-1';
export const CLASSIFICATIONS = Object.freeze(['OPERATIONAL_PUBLIC', 'OPERATIONAL_CREDENTIAL_GATED', 'IMPLEMENTED_NOT_LIVE_SMOKED', 'CODE_PATH_COMPLETE_EXTERNAL_ACCESS_BLOCKED', 'FOUNDATION_ONLY', 'DEPRECATED', 'NOT_PRESENT']);
export const INVENTORY_GROUPS = Object.freeze(['CORE_MARKET', 'INFRASTRUCTURE', 'RUMOR_OFFICIAL', 'SOCIAL', 'MARKET_RESEARCH', 'DARK_RESEARCH', 'DECISION', 'PUBLISHER_NEWS']);
export const ROW_KEYS = Object.freeze(['id', 'group', 'family', 'classification', 'module', 'compositionPath', 'enable', 'credentialEnv', 'paid', 'budgetGovernor', 'retentionTermsGate', 'liveTransport', 'durableTruth', 'pointInTimeContract', 'replay', 'decisionAuthority', 'paperAuthority', 'paperDesiredState', 'blockerPolicy', 'readinessBlocker', 'smokeEvidence']);
// repository-known live-smoke facts (dated; a reference, never a runtime claim)
export const SMOKE_FACTS = Object.freeze({
  TAPE: 'Kraken WS v2 public feed: continuous live operation on the deployment; doctrine/WIDEEYE.md, doctrine/DEPLOYMENT.md. 2026-09-12 local OBSERVE run (no credentials, no orders): 34231 CRC-verified book snapshots and 537 trades delivered to the Judge consumer in 5 minutes, 0 CRC failures (docs/evidence/operational-repair-2026-09-12.md)',
  KRAKEN_SPOT: 'PROBED_OK 2026-09-12 read-only preflight smoke, 622 markets (docs/evidence/operational-repair-2026-09-12.md); L01', COINBASE_SPOT: 'PROBED_OK 2026-09-12 (record count not reported by the endpoint); L01', KRAKEN_DERIVATIVES: 'PROBED_OK 2026-09-12, 295 records; L01', DERIBIT: 'PROBED_OK 2026-09-12, 950 records; L01', GECKOTERMINAL: 'PROBED_OK 2026-09-12, 1 record; L01', DEFILLAMA: 'PROBED_OK 2026-09-12, 1 record; L01', COINMETRICS: 'PROBED_OK 2026-09-12 (community API); L01',
  BYBIT: 'HTTP 403 from this build environment (geo / access), 2026-09-11 read-only probe; 2026-09-12 NOT_PROBED (PROVIDER_DISABLED by the paper policy); docs/MARKET-SOCRATES-ACCEPTANCE.md',
  COINGLASS: 'docs/MARKET-SOCRATES-ACCEPTANCE.md L02: BLOCKED (no entitled plan)', CRYPTOQUANT: 'L02: BLOCKED', SANTIMENT: 'L02: BLOCKED', TWELVEDATA: 'L02: BLOCKED', TOKENOMIST: 'L02: BLOCKED', COINGECKO: 'unauthenticated public ping reached HTTP 200 on 2026-09-12; the CONFIGURED provider path stays NOT_PROBED (PROVIDER_DISABLED); demo plan / cost UNKNOWN (policy plan attestation absent)', FRED: 'PROBED_FAILED 2026-09-12 CREDENTIAL_MISSING / coverage ACCESS_BLOCKED without FRED_API_KEY (documented free key required; docs/evidence/operational-repair-2026-09-12.md)',
  SETTLED_RECORDS: 'local settled records (no network)', BLUESKY_OFFICIAL: 'Jetstream public read 2026-09-12: open 461 ms, 200 messages in 3.3 s, 200/200 mapped to valid shared-contract observations (112 posts / 88 reposts), 0 skips, provider sequence 25754477318; durable delivery to the RUMOR2 event root NOT proven locally (no DATABASE_URL); docs/evidence/operational-repair-2026-09-12.md, doctrine/SOCIAL.md §5B', X_OFFICIAL: 'never spent (paid; explicit smoke envelope required)',
  KRAKEN_OFFICIAL: 'doctrine/RUMOR2.md (official feed live on the deployment); 2026-09-12 local read through rumor2/http.js + feed.js: HTTP 200, 10 items parsed, 0 truncated (docs/evidence/sensor-scope-2026-09-12.md)', SEC_OFFICIAL: 'doctrine/RUMOR2.md; NOT_QUERIED locally (SERPENT_HTTP_CONTACT unset: the SEC user-agent law is never bypassed)', CFTC_OFFICIAL: 'doctrine/RUMOR2.md; 2026-09-12 local read through rumor2/http.js + feed.js: HTTP 200, 10 items parsed', EDGAR_OFFICIAL: 'doctrine/RUMOR2.md (RUMOR-2B1; whitelist-gated); NOT_QUERIED locally (contact + CIK whitelist unset)', OFAC_OFFICIAL: 'doctrine/RUMOR2.md (RUMOR-2B1); 2026-09-12 local read through rumor2/http.js: HTTP 200, SDN CSV 5.69 MB / 19389 lines within the provider byte bound',
  GATEWAY: 'doctrine/GATEWAY.md (public status pages; polite polling); 2026-09-12 local reads through gateway/parse.js: status.kraken.com 200 (7 events, 0 unparsed, indicator minor), status.coinbase.com 200 (1 event, door UNKNOWN as parsed), api.kraken.com SystemStatus 200 (online), okx system status 200 (code 0)', WIDEEYE: 'doctrine/WIDEEYE.md', RUMINT: 'doctrine/RUMINT.md (StockTwits aggregate ear; RUMINT-R1); 2026-09-12 local read through rumint/stocktwits.js fetchSymbolPage(BTC.X): ok, 30 messages, cursor present', KRAKEN_OHLC: '2026-09-12 local read through judge/history.js refresh(XBT/USD): ok, 721 rows, 720 closed bars retained, 61-bar block complete (missingOf61 0)', REPLAY: 'no network by design; test/judge-composition.test.js P03 (same bytes + clocks -> same digests), test/judge-experiment-replay.test.js, test/childhood.test.js', KRAKEN_CHARTS: 'public poll 2026-09-12: PF_XBTUSD open-interest 60 s, 2 observations, acquisition COMPLETE, coverage OBSERVED (docs/evidence/operational-repair-2026-09-12.md)', KRAKEN_L3: 'NOT_RUN_NO_SAFE_L3_DATA_KEY (2026-09-12 probe: CREDENTIAL_MISSING). Separate from the Judge book route: no module under judge/, execution/, watch/ or tape/ names L3 at all',
});
const PROVIDER_MODULES = Object.freeze({ KRAKEN_SPOT: 'kraken-spot.js', COINBASE_SPOT: 'coinbase.js', KRAKEN_DERIVATIVES: 'kraken-derivatives.js', DERIBIT: 'deribit.js', BYBIT: 'bybit.js', COINGECKO: 'coingecko.js', GECKOTERMINAL: 'coingecko.js', DEFILLAMA: 'defillama.js', COINGLASS: 'coinglass.js', CRYPTOQUANT: 'cryptoquant.js', SANTIMENT: 'santiment.js', COINMETRICS: 'coinmetrics.js', FRED: 'fred.js', TWELVEDATA: 'twelvedata.js', SETTLED_RECORDS: 'settled.js', TOKENOMIST: 'tokenomist.js' });
const row = (o) => { const r = {}; for (const k of ROW_KEYS) r[k] = o[k] === undefined ? null : o[k]; if (!CLASSIFICATIONS.includes(r.classification)) throw new Error(`inventory ${r.id}: classification ${r.classification}`); if (!INVENTORY_GROUPS.includes(r.group)) throw new Error(`inventory ${r.id}: group`); return Object.freeze(r); };
const present = (env, names) => (Array.isArray(names) ? names : [names]).filter(Boolean).every((n) => typeof env[n] === 'string' && env[n].length > 0);
const readJson = (f) => JSON.parse(readFileSync(f, 'utf8'));

export function sensorInventory({ profile = loadProfile(), env = process.env, config = loadConfig(), clock = () => Date.now() } = {}) {
  const g = profile.groups; const policy = readJson(profileFileOf(profile, 'marketResearchPolicy')); const rows = [];
  const prof = (grp, id) => g[grp]?.[id] ?? null; const mrProf = (id) => g.marketResearch.providers[id] ?? null;
  const NONE = 'NONE';
  // ---- CORE MARKET / SURVEY --------------------------------------------------------------------------------------------------
  rows.push(row({ id: 'TAPE', group: 'CORE_MARKET', family: 'KRAKEN_PUBLIC_MARKET_DATA', classification: 'OPERATIONAL_PUBLIC', module: 'tape/run.js', compositionPath: 'fly.js -> runTape (last; execution feed + research observer seams)', enable: 'always (cobra.config.json tape.*)', credentialEnv: [], paid: false, budgetGovernor: 'none (public WS)', retentionTermsGate: 'public market data', liveTransport: true, durableTruth: 'tape store (jsonl) + PostgreSQL mirror', pointInTimeContract: 'receipt clocks + feature snapshot', replay: 'experiment input bundles (judge)', decisionAuthority: 'FEED_ONLY', paperAuthority: 'FEED_ONLY', paperDesiredState: prof('coreObservation', 'tape').desiredState, blockerPolicy: prof('coreObservation', 'tape').blockerPolicy, readinessBlocker: null, smokeEvidence: SMOKE_FACTS.TAPE }));
  rows.push(row({ id: 'WIDEEYE', group: 'CORE_MARKET', family: 'FULL_UNIVERSE_SURVEY', classification: 'OPERATIONAL_PUBLIC', module: 'survey/wideeye.js', compositionPath: 'fly.js -> startWideEye', enable: 'cobra.config.json wideeye.enabled / WIDEEYE_ENABLED', credentialEnv: [], paid: false, budgetGovernor: 'sweep cadence + catalog resource settings', retentionTermsGate: 'public market data', liveTransport: true, durableTruth: 'survey status + nominations', pointInTimeContract: 'sweep population snapshot', replay: 'none', decisionAuthority: NONE, paperAuthority: NONE, paperDesiredState: prof('coreObservation', 'wideEye').desiredState, blockerPolicy: prof('coreObservation', 'wideEye').blockerPolicy, readinessBlocker: config.wideeye?.enabled ? null : 'DISABLED_BY_CONFIG', smokeEvidence: SMOKE_FACTS.WIDEEYE }));
  rows.push(row({ id: 'UNIVERSE_EXPANSION', group: 'CORE_MARKET', family: 'DEEP_OBSERVATION_SET', classification: 'OPERATIONAL_PUBLIC', module: 'tape/universe.js', compositionPath: 'tape/run.js (subscription selection)', enable: 'cobra.config.json universeExpansion.enabled', credentialEnv: [], paid: false, budgetGovernor: 'resource caps (heap / loop lag / shed fraction)', retentionTermsGate: 'public market data', liveTransport: true, durableTruth: 'universe current.json', pointInTimeContract: 'selection date / selectedAt', replay: 'none', decisionAuthority: NONE, paperAuthority: NONE, paperDesiredState: prof('coreObservation', 'universeExpansion').desiredState, blockerPolicy: prof('coreObservation', 'universeExpansion').blockerPolicy, readinessBlocker: config.universeExpansion?.enabled ? null : 'DISABLED_BY_CONFIG', smokeEvidence: SMOKE_FACTS.TAPE }));
  rows.push(row({ id: 'COST_EXECUTABILITY', group: 'CORE_MARKET', family: 'EXECUTION_COST_MODEL', classification: 'OPERATIONAL_PUBLIC', module: 'cost/model.js + judge/cost.js', compositionPath: 'bin/cobra.js cost; judge intake (book age law)', enable: 'always (cobra.config.json cost.*)', credentialEnv: [], paid: false, budgetGovernor: 'none', retentionTermsGate: 'derived from public book', liveTransport: false, durableTruth: 'current book files', pointInTimeContract: 'maxBookAgeSec freshness law', replay: 'judge experiment replay', decisionAuthority: 'INPUT_TO_JUDGE_READINESS', paperAuthority: 'INPUT_TO_JUDGE_READINESS', paperDesiredState: prof('coreObservation', 'costExecutability').desiredState, blockerPolicy: prof('coreObservation', 'costExecutability').blockerPolicy, readinessBlocker: null, smokeEvidence: 'derived (no network)' }));
  rows.push(row({ id: 'MEMORY_MIRROR', group: 'CORE_MARKET', family: 'DURABLE_MEMORY', classification: 'OPERATIONAL_PUBLIC', module: 'memory/mirror.js', compositionPath: 'fly.js -> startMemoryMirror (dark; no return path)', enable: 'always', credentialEnv: [], paid: false, budgetGovernor: 'none', retentionTermsGate: 'internal', liveTransport: false, durableTruth: 'PostgreSQL memory + childhood archive', pointInTimeContract: 'settled-event knownAt', replay: 'childhood archive (read-only)', decisionAuthority: NONE, paperAuthority: NONE, paperDesiredState: prof('coreObservation', 'memoryMirror').desiredState, blockerPolicy: prof('coreObservation', 'memoryMirror').blockerPolicy, readinessBlocker: null, smokeEvidence: 'doctrine/MEMORY.md' }));
  rows.push(row({ id: 'RESEARCH_STRAINER', group: 'CORE_MARKET', family: 'SOCIAL_RESEARCH_STRAINER', classification: 'OPERATIONAL_PUBLIC', module: 'rumor2/social-research-strainer.js', compositionPath: 'fly.js -> RUMOR2 collector (the composition root wires the social strainer)', enable: 'composition (fly.js) — always in the paper profile', credentialEnv: [], paid: false, budgetGovernor: 'none', retentionTermsGate: 'derived dossiers only', liveTransport: false, durableTruth: 'dossier records', pointInTimeContract: 'as-of composite', replay: 'none', decisionAuthority: NONE, paperAuthority: NONE, paperDesiredState: prof('coreObservation', 'socialStrainer').desiredState, blockerPolicy: prof('coreObservation', 'socialStrainer').blockerPolicy, readinessBlocker: null, smokeEvidence: 'doctrine/SOCIAL.md §36' }));
  // ---- EXCHANGE / INFRASTRUCTURE -----------------------------------------------------------------------------------------------
  const gw = prof('infrastructure', 'gateway'); const sources = config.gateway?.sources ?? {};
  for (const [src, label, host] of [['kraken', 'GATEWAY_KRAKEN_STATUS', 'status.kraken.com'], ['krakenSystem', 'GATEWAY_KRAKEN_SYSTEM', 'api.kraken.com SystemStatus'], ['coinbase', 'GATEWAY_COINBASE_STATUS', 'status.coinbase.com'], ['okx', 'GATEWAY_OKX_STATUS', 'www.okx.com system status']]) {
    rows.push(row({ id: label, group: 'INFRASTRUCTURE', family: 'EXCHANGE_INFRASTRUCTURE', classification: 'OPERATIONAL_PUBLIC', module: 'gateway/collector.js', compositionPath: 'fly.js -> startGateway (collector only; wired to nothing)', enable: `cobra.config.json gateway.enabled + gateway.sources.${src} / GATEWAY_ENABLED`, credentialEnv: [], paid: false, budgetGovernor: 'pollSec floor 60 s + backoff', retentionTermsGate: `public status page (${host})`, liveTransport: true, durableTruth: 'incidents_state.json + matrix.json + events.jsonl', pointInTimeContract: 'observedAt per poll', replay: 'none', decisionAuthority: NONE, paperAuthority: NONE, paperDesiredState: gw.desiredState, blockerPolicy: gw.blockerPolicy, readinessBlocker: sources[src] === false ? 'SOURCE_DISABLED_BY_CONFIG' : null, smokeEvidence: SMOKE_FACTS.GATEWAY }));
  }
  rows.push(row({ id:'GOVERNANCE_TALLY',group:'INFRASTRUCTURE',family:'GOVERNANCE',classification:'CODE_PATH_COMPLETE_EXTERNAL_ACCESS_BLOCKED',module:'governance/tally.js + governance/collector.js',compositionPath:'fly.js -> startGovernance -> pollTally -> governance/events.jsonl -> memory/adapters.js',enable:'cobra.config.json governance.enabled + governance.verifiedMappings',credentialEnv:['TALLY_API_KEY'],paid:false,budgetGovernor:'separate Tally GovBudget; >=1 second request spacing',retentionTermsGate:'verified governor mappings required',liveTransport:true,durableTruth:'shared governance source log, pending debt and checkpoints',pointInTimeContract:'provider event/start/end clocks separately from retrieval; exact Uint256 strings; INDEXED_BY_TALLY',replay:'source reconciliation + checkpoint restore',decisionAuthority:NONE,paperAuthority:NONE,paperDesiredState:'REQUEST',blockerPolicy:'DEGRADE',readinessBlocker:'TALLY_API_KEY and verified governor mappings not verified on the host',smokeEvidence:'test/tally-runtime.test.js; no live Tally request made'}));
  // ---- RUMINT / RUMOR OFFICIAL -------------------------------------------------------------------------------------------------
  const rl = prof('rumorOfficial', 'rumintLegacy');
  rows.push(row({ id: 'RUMINT_STOCKTWITS_AGGREGATE', group: 'RUMOR_OFFICIAL', family: 'LEGACY_RUMINT', classification: 'OPERATIONAL_PUBLIC', module: 'rumint/poller.js', compositionPath: 'fly.js -> startRumint', enable: 'cobra.config.json rumint.enabled / RUMINT_ENABLED', credentialEnv: [], paid: false, budgetGovernor: 'hourlyBudget + spacing + backoff', retentionTermsGate: 'aggregate counts only (no raw social content)', liveTransport: true, durableTruth: 'rumint checkpoint (PostgreSQL)', pointInTimeContract: 'poll clocks', replay: 'aggregate checkpoint only', decisionAuthority: 'NOMINATE_WARN_ONLY', paperAuthority: 'NOMINATE_WARN_ONLY', paperDesiredState: rl.desiredState, blockerPolicy: rl.blockerPolicy, readinessBlocker: config.rumint?.enabled ? null : 'DISABLED_BY_CONFIG', smokeEvidence: SMOKE_FACTS.RUMINT }));
  for (const p of OFFICIAL_PROVIDERS) {
    const pr = prof('rumorOfficial', p.id); const needContact = p.requiresContact && !present(env, 'SERPENT_HTTP_CONTACT');
    const blocker = p.id === 'EDGAR_OFFICIAL' && !present(env, 'RUMOR2_EDGAR_CIKS') ? 'CONFIG_REQUIRED:EDGAR_WHITELIST' : needContact ? 'CONFIG_REQUIRED:SERPENT_HTTP_CONTACT' : null;
    rows.push(row({ id: p.id, group: 'RUMOR_OFFICIAL', family: p.providerKind, classification: 'OPERATIONAL_PUBLIC', module: p.adapter === 'EDGAR_SUBMISSIONS' ? 'rumor2/edgar.js' : p.adapter === 'OFAC_SDN_CSV' ? 'rumor2/ofac.js' : 'rumor2/feed.js', compositionPath: 'fly.js -> RUMOR2 collector (RUMOR2_ENABLED)', enable: pr?.enableEnv ?? 'RUMOR2_ENABLED', credentialEnv: p.requiresContact ? ['SERPENT_HTTP_CONTACT (contact NAME, not a secret)'] : [], paid: false, budgetGovernor: `cadence ${p.cadenceSec}s, hourly budget ${p.hourlyBudget}`, retentionTermsGate: `official host ${p.host}; bounded references only`, liveTransport: true, durableTruth: 'PostgreSQL event journal (authoritative) + checkpoint', pointInTimeContract: 'settled-event clocks (RUMOR-2 truth law)', replay: 'journal replay', decisionAuthority: 'EVIDENCE_ONLY', paperAuthority: 'EVIDENCE_ONLY', paperDesiredState: pr?.desiredState ?? 'OFF', blockerPolicy: pr?.blockerPolicy ?? 'DEGRADE', readinessBlocker: blocker, smokeEvidence: SMOKE_FACTS[p.id] ?? null }));
  }
  // ---- SOCIAL ----------------------------------------------------------------------------------------------------------------
  for (const s of SOCIAL_PROVIDERS) {
    const pr = prof('social', s.id); const paid = s.id === 'X_OFFICIAL';
    const cls = s.id === 'BLUESKY_OFFICIAL' ? 'OPERATIONAL_PUBLIC' : s.id === 'X_OFFICIAL' ? 'OPERATIONAL_CREDENTIAL_GATED' : s.foundation?.fixtureOnly ? 'FOUNDATION_ONLY' : 'CODE_PATH_COMPLETE_EXTERNAL_ACCESS_BLOCKED';
    const blocker = s.id === 'BLUESKY_OFFICIAL' ? null : s.id === 'X_OFFICIAL' ? (!present(env, 'X_BEARER_TOKEN') ? 'CREDENTIAL_MISSING' : !present(env, ['RUMOR2_SOCIAL_X_MAX_DAILY_POST_READS', 'RUMOR2_SOCIAL_X_MAX_MONTHLY_POST_READS', 'RUMOR2_SOCIAL_X_MAX_ESTIMATED_DAILY_USD']) ? 'BUDGET_NOT_CONFIGURED' : 'READY_REQUIRES_EXPLICIT_PAID_SMOKE') : pr?.reason ?? s.accessState;
    rows.push(row({ id: s.id, group: 'SOCIAL', family: 'SOCIAL', classification: cls, module: s.id === 'BLUESKY_OFFICIAL' ? 'rumor2/social-runtime.js + social-stream.js' : s.id === 'X_OFFICIAL' ? 'rumor2/x-runtime.js + x-stream.js' : s.foundation?.module ?? (s.id === 'REDDIT_OFFICIAL' ? 'rumor2/social-reddit.js' : s.id === 'STOCKTWITS_OFFICIAL' ? 'rumor2/social-stocktwits.js' : null), compositionPath: s.durable ? 'fly.js -> RUMOR2 collector (social gate)' : 'not composed (foundation / access boundary only)', enable: pr?.enableEnv ?? 'not enableable', credentialEnv: [s.credentialEnv, ...(s.foundation?.credentialEnvs ?? [])].filter(Boolean), paid, budgetGovernor: paid ? 'x-runtime governor: daily / monthly / USD caps + explicit paid smoke' : 'none', retentionTermsGate: `${s.accessState}${s.retention ? `; retention ${s.retention}` : ''}`, liveTransport: s.durable === true && s.transport !== null, durableTruth: s.durable ? 'PostgreSQL social journal' : 'none', pointInTimeContract: s.durable ? 'social settle law (SOCIAL-1)' : 'fixture only', replay: s.durable ? 'JOURNAL_REPLAY' : 'FIXTURE_REPLAY_ONLY', decisionAuthority: NONE, paperAuthority: NONE, paperDesiredState: pr?.desiredState ?? 'OFF', blockerPolicy: pr?.blockerPolicy ?? 'DEGRADE', readinessBlocker: blocker, smokeEvidence: SMOKE_FACTS[s.id] ?? 'none (no lawful live route)' }));
  }
  // ---- MARKET-LAB / DEEP MARKET ---------------------------------------------------------------------------------------------
  for (const id of MARKET_PROVIDER_IDS) {
    const reg = MARKET_PROVIDERS[id]; const pol = policy.providers[id]; const pr = mrProf(id); const cred = pol?.credentialEnv ?? null;
    const paidPlan = pol?.plan?.billing !== 'FREE'; const keyPresent = cred ? present(env, cred) : true;
    const cls = id === 'BYBIT' ? 'CODE_PATH_COMPLETE_EXTERNAL_ACCESS_BLOCKED' : cred ? 'OPERATIONAL_CREDENTIAL_GATED' : 'OPERATIONAL_PUBLIC';
    const blocker = id === 'BYBIT' ? 'BLOCKED_GEOGRAPHY' : paidPlan ? (keyPresent ? 'BLOCKED_BUDGET (plan / cost attestation required in the policy)' : 'CREDENTIAL_MISSING + BLOCKED_BUDGET') : cred && !keyPresent ? 'CREDENTIAL_MISSING' : null;
    rows.push(row({ id, group: 'MARKET_RESEARCH', family: reg.name, classification: cls, module: `market-lab/providers/${PROVIDER_MODULES[id]}`, compositionPath: 'fly.js -> createResearchService (MARKET_RESEARCH_ENABLED) -> owner', enable: `policy providers.${id}.enabled`, credentialEnv: cred ? [cred] : [], paid: paidPlan, budgetGovernor: 'market-lab quota journal + dispatch guard (maxCallsPerDay / Month, smoke caps)', retentionTermsGate: `hosts ${reg.hosts.join(', ')}`, liveTransport: true, durableTruth: 'sealed CAPTURE bundles + accounting journal', pointInTimeContract: 'observation envelope (sourceEventTs / receivedTs / knownAtTs / revision)', replay: 'REPLAY_AS_OF over sealed bundles', decisionAuthority: 'EVIDENCE_ONLY (decision families)', paperAuthority: 'EVIDENCE_ONLY', paperDesiredState: pr?.desiredState ?? 'OFF', blockerPolicy: pr?.blockerPolicy ?? 'DEGRADE', readinessBlocker: blocker, smokeEvidence: SMOKE_FACTS[id] ?? null }));
  }
  // ---- DARK RESEARCH (Kraken Charts + L3): EDGE_CAPTURE only; zero decision authority --------------------------------------------
  const ch = prof('darkEdgeCapture', 'krakenCharts'); const l3 = prof('darkEdgeCapture', 'krakenL3'); const l3Keys = present(env, ['KRAKEN_L3_DATA_API_KEY', 'KRAKEN_L3_DATA_API_SECRET']);
  rows.push(row({ id: 'KRAKEN_CHARTS_DARK', group: 'DARK_RESEARCH', family: 'DERIVATIVES_PRESSURE (dark)', classification: 'OPERATIONAL_PUBLIC', module: 'market-lab/providers/kraken-charts.js', compositionPath: 'bin/market-research.js edge-capture (bounded run) — never the decision owner', enable: 'policy providers.KRAKEN_DERIVATIVES.charts.enabled', credentialEnv: [], paid: false, budgetGovernor: 'charts maxCallsPerDay + polling cadence + accounting journal', retentionTermsGate: 'public futures.kraken.com charts API', liveTransport: true, durableTruth: 'sealed EDGE_CAPTURE bundles', pointInTimeContract: 'bucket period / receipt / knownAt / finality / vintage', replay: 'sealed bundle replay', decisionAuthority: NONE, paperAuthority: NONE, paperDesiredState: ch.desiredState, blockerPolicy: ch.blockerPolicy, readinessBlocker: policy.providers.KRAKEN_DERIVATIVES?.charts?.enabled ? null : 'DARK_CAPTURE_DISABLED_BY_POLICY', smokeEvidence: SMOKE_FACTS.KRAKEN_CHARTS }));
  rows.push(row({ id: 'KRAKEN_L3_DARK', group: 'DARK_RESEARCH', family: 'L3 order-level (dark)', classification: 'OPERATIONAL_CREDENTIAL_GATED', module: 'market-lab/providers/kraken-l3.js + kraken-l3-auth.js + l3-book.js', compositionPath: 'bin/market-research.js edge-capture — connection opens ONLY on a proven SAFE_L3_DATA_KEY', enable: 'policy providers.KRAKEN_SPOT.l3.enabled', credentialEnv: ['KRAKEN_L3_DATA_API_KEY', 'KRAKEN_L3_DATA_API_SECRET'], paid: false, budgetGovernor: 'weighted subscription pacer (W9) + queue / order / byte bounds', retentionTermsGate: 'dedicated DATA-ONLY key; never an execution credential', liveTransport: true, durableTruth: 'sealed EDGE_CAPTURE bundles (W12 markers)', pointInTimeContract: 'sourceEventTs + receivedTs + knownAtTs (W10)', replay: 'sealed bundle replay', decisionAuthority: NONE, paperAuthority: NONE, paperDesiredState: l3.desiredState, blockerPolicy: l3.blockerPolicy, readinessBlocker: l3Keys ? 'KEY_PRESENT_UNPROVEN (SAFE_L3_DATA_KEY verdict needs the read-only probe: preflight --smoke)' : 'BLOCKED_NO_SAFE_L3_DATA_KEY (CREDENTIAL_MISSING)', smokeEvidence: SMOKE_FACTS.KRAKEN_L3 }));
  // ---- DECISION / SUPERVISION -----------------------------------------------------------------------------------------------
  const soc = prof('socrates', 'model'); const modelKey = present(env, policy.model?.credentialEnv ?? 'ANTHROPIC_API_KEY'); const modelBudget = (policy.model?.maxEstimatedUsdPerCase ?? 0) > 0 && (policy.model?.maxEstimatedUsdPerDay ?? 0) > 0;
  rows.push(row({ id: 'SOCRATES', group: 'DECISION', family: 'INTERPRETATION', classification: 'OPERATIONAL_CREDENTIAL_GATED', module: 'socrates/runtime.js (+ broker, client, report)', compositionPath: 'market-lab/service.js case runtime (inside the research service)', enable: 'policy model.enabled + explicit USD caps', credentialEnv: [policy.model?.credentialEnv ?? 'ANTHROPIC_API_KEY'], paid: true, budgetGovernor: 'socrates budget (per case / day / month USD caps, model reservation)', retentionTermsGate: 'model output is interpretation, never source truth', liveTransport: true, durableTruth: 'sealed case bundles', pointInTimeContract: 'evidence v2 as-of packet', replay: 'recorded responses', decisionAuthority: 'SEALED_CASE_INPUT_TO_JUDGE', paperAuthority: 'SEALED_CASE_INPUT_TO_JUDGE', paperDesiredState: soc.desiredState, blockerPolicy: soc.blockerPolicy, readinessBlocker: !policy.model?.enabled ? 'MODEL_DISABLED_IN_POLICY (cases seal BUDGET_BLOCKED; Judge runs MARKET_DIRECT setups)' : !modelKey ? 'CREDENTIAL_MISSING' : !modelBudget ? 'BUDGET_NOT_CONFIGURED' : null, smokeEvidence: 'docs/MARKET-SOCRATES-ACCEPTANCE.md (recorded-response evaluation; no paid call in tests)' }));
  const jd = prof('judge', 'judge'); const db = present(env, 'DATABASE_URL');
  rows.push(row({ id: 'JUDGE', group: 'DECISION', family: 'DECISION', classification: 'OPERATIONAL_CREDENTIAL_GATED', module: 'judge/composition.js (+ intake, readiness, features, setups, judge, risk, cost, scheduler, recorder, history, owner, arming, experiment*, snapshot-store)', compositionPath: 'fly.js -> composeJudge (JUDGE_ENABLED; mode from the profile = PAPER)', enable: 'JUDGE_ENABLED + JUDGE_POLICY + JUDGE_MODE (forced PAPER)', credentialEnv: ['DATABASE_URL (journal authority; not a provider key)'], paid: false, budgetGovernor: 'risk limits / daily loss / drawdown restrictions (policy)', retentionTermsGate: 'internal', liveTransport: false, durableTruth: 'PostgreSQL execution journal (migration 8 / 9)', pointInTimeContract: 'permission clock + receipt-to-decision lag law', replay: 'journal replay + experiment replay', decisionAuthority: 'PAPER_DECISIONS', paperAuthority: 'PAPER_SIMULATION_ONLY', paperDesiredState: jd.desiredState, blockerPolicy: jd.blockerPolicy, readinessBlocker: db ? null : 'DATABASE_URL missing (PAPER needs the journal authority)', smokeEvidence: 'test/judge-e2e-pg.test.js + test/paper-e2e-pg.test.js (mock market inputs; PostgreSQL)' }));
  const wt = prof('watch', 'watch');
  rows.push(row({ id: 'WATCH', group: 'DECISION', family: 'SUPERVISION', classification: 'OPERATIONAL_CREDENTIAL_GATED', module: 'watch/watch.js', compositionPath: 'judge/composition.js (owns every non-FLAT position)', enable: 'with the Judge', credentialEnv: ['DATABASE_URL (through the Judge)'], paid: false, budgetGovernor: 'none', retentionTermsGate: 'internal', liveTransport: false, durableTruth: 'journal events', pointInTimeContract: 'fresh book / evidence context law', replay: 'journal replay', decisionAuthority: 'PAPER_EXIT_INTENT', paperAuthority: 'PAPER_EXIT_INTENT_ONLY', paperDesiredState: wt.desiredState, blockerPolicy: wt.blockerPolicy, readinessBlocker: db ? null : 'DATABASE_URL missing', smokeEvidence: 'test/judge-watch*.test.js + paper E2E' }));
  rows.push(row({ id: 'PAPER_EXECUTION', group: 'DECISION', family: 'EXECUTION_SIMULATION', classification: 'OPERATIONAL_CREDENTIAL_GATED', module: 'execution/paper-adapter.js + execution/journal.js + reconciliation', compositionPath: 'judge/composition.js (adapter PAPER; the LIVE adapter is never constructed without a LIVE policy + mode)', enable: 'judge policy execution.adapter PAPER', credentialEnv: ['DATABASE_URL'], paid: false, budgetGovernor: 'none', retentionTermsGate: 'internal', liveTransport: false, durableTruth: 'PostgreSQL execution journal', pointInTimeContract: 'arrival-window fills (paperMaxObservationWaitMs) else UNFILLED_COVERAGE_UNKNOWN', replay: 'journal replay', decisionAuthority: NONE, paperAuthority: 'SIMULATED_FILLS_ONLY', paperDesiredState: jd.desiredState, blockerPolicy: jd.blockerPolicy, readinessBlocker: db ? null : 'DATABASE_URL missing', smokeEvidence: 'test/judge-e2e-pg.test.js' }));
  // ---- Kraken 1m history + the point-in-time capture / replay capability (internal, present) ------------------------------------------
  rows.push(row({ id: 'KRAKEN_OHLC_HISTORY', group: 'CORE_MARKET', family: 'KRAKEN_PUBLIC_MARKET_DATA', classification: 'OPERATIONAL_PUBLIC', module: 'judge/history.js', compositionPath: 'judge/composition.js -> createBarHistory (REST OHLC cold start, live continuation from the execution feed trades)', enable: 'with the Judge (shared transport)', credentialEnv: [], paid: false, budgetGovernor: 'one bounded REST refresh per symbol when needsRefresh (720-row cap, never re-entrant)', retentionTermsGate: 'public market data', liveTransport: true, durableTruth: 'experiment input bundles (HISTORY rows under one capture sequence)', pointInTimeContract: 'closed 1m bars with a receipt floor (knownAtTs); the provisional minute and rows after `last` are dropped', replay: 'HISTORY rows replayed through ingestRows', decisionAuthority: 'FEED_ONLY', paperAuthority: 'FEED_ONLY', paperDesiredState: prof('coreObservation', 'tape').desiredState, blockerPolicy: prof('coreObservation', 'tape').blockerPolicy, readinessBlocker: null, smokeEvidence: SMOKE_FACTS.KRAKEN_OHLC }));
  rows.push(row({ id: 'HISTORICAL_CAPTURE_REPLAY', group: 'CORE_MARKET', family: 'POINT_IN_TIME_MEMORY', classification: 'OPERATIONAL_PUBLIC', module: 'judge/recorder.js + judge/experiment-replay.js + judge/experiment-store.js + childhood/fetch.js', compositionPath: 'judge/composition.js (JUDGE_RECORD_DIR -> sealed input bundles); bin/judge.js replay / replay-experiment (offline); childhood archive', enable: 'JUDGE_RECORD_DIR for capture; replay is an offline command', credentialEnv: [], paid: false, budgetGovernor: 'segment rotation + bounded retention (MC-5); a recording failure stops admission', retentionTermsGate: 'internal', liveTransport: false, durableTruth: 'sealed recording segments + PostgreSQL experiment store (migration 9)', pointInTimeContract: 'receipt clocks per row; the replay clock is the recorded receipt; no future outcome is ever an input', replay: 'deterministic: same bytes + same clocks -> same digests, epochs, receipt sequences', decisionAuthority: NONE, paperAuthority: NONE, paperDesiredState: 'ON', blockerPolicy: 'DEGRADE', readinessBlocker: null, smokeEvidence: SMOKE_FACTS.REPLAY }));
  // ---- PUBLISHER NEWS (press/): a SEPARATE, explicitly classified observation tier — headline / link / publisher timestamp only,
  // authority NONE, never a RUMOR-2 evidence provider (doctrine/RUMOR2.md keeps publishers out of the frozen evidence core; the
  // press tier reuses only the pure feed parser). Reuters / Bloomberg stay NOT_PRESENT: they publish no public route and a client
  // around an unknown licensed endpoint is never invented (the registry names the prerequisite; the collector makes zero calls).
  const PRESS_SMOKE = Object.freeze({
    COINDESK_NEWS: '2026-09-12: www.coindesk.com/arc/outboundfeeds/rss/ HTTP 200 application/xml, 25 items (docs/evidence/sensor-scope-2026-09-12.md); live read through press/collector.js pollOnce on 2026-09-12: see docs/evidence/sensor-implementation-2026-09-12.md',
    THEBLOCK_NEWS: '2026-09-12: www.theblock.co/rss.xml HTTP 200 text/xml, 20 items; live read through press/collector.js: docs/evidence/sensor-implementation-2026-09-12.md',
    COINTELEGRAPH_NEWS: '2026-09-12: cointelegraph.com/rss HTTP 200 application/xml, 30 items; live read through press/collector.js: docs/evidence/sensor-implementation-2026-09-12.md',
    DECRYPT_NEWS: '2026-09-12: decrypt.co/feed HTTP 200 application/xml, 55 items; live read through press/collector.js: docs/evidence/sensor-implementation-2026-09-12.md',
    FT_NEWS: '2026-09-12: ft.com/rss/home answered HTTP 403 to the runtime\'s Node fetch client (default headers too) from this environment while curl on the same URL answered 301 -> 200 text/xml (anti-bot client gate); unverified on the host; headlines / links only, bodies paywalled; profile OFF pending the owner\'s terms review',
    CNBC_NEWS: '2026-09-12: live read through press/collector.js pollOnce: www.cnbc.com/id/100003114/device/rss/rss.html HTTP 200, 30 items admitted (the cnbc.com/rss-feeds index page answered HTTP 403 here); profile OFF pending the owner\'s terms review (docs/evidence/sensor-implementation-2026-09-12.md)',
    GOOGLE_NEWS_AGGREGATOR: '2026-09-12: news.google.com/rss/search?q=bitcoin HTTP 200 application/xml; per-item <source> publisher preserved by press/parse.js extractItemSources; profile OFF pending the owner\'s terms acceptance',
    REUTERS_NEWS: '2026-09-12: reuters.com/tools/rss HTTP 401; reutersagency.com products page HTTP 404; no public feed documented — licensed distribution (Reuters Connect) only',
    BLOOMBERG_NEWS: '2026-09-12: bloomberg.com/feeds and /professional/products/data HTTP 403 anti-bot; no public feed documented — Terminal / B-PIPE / Enterprise licensing only',
  });
  for (const src of PRESS_SOURCES) {
    const pr = prof('publisherNews', src.id); const licensed = src.route === 'LICENSED_INTERFACE_REQUIRED';
    if (licensed) { rows.push(row({ id: src.id, group: 'PUBLISHER_NEWS', family: 'PUBLISHER', classification: 'NOT_PRESENT', module: null, compositionPath: 'not composed', enable: 'none', credentialEnv: [], paid: false, budgetGovernor: 'none', retentionTermsGate: 'licensed distribution agreement required', liveTransport: false, durableTruth: 'none', pointInTimeContract: 'none', replay: 'none', decisionAuthority: NONE, paperAuthority: NONE, paperDesiredState: 'OFF', blockerPolicy: pr?.blockerPolicy ?? 'DEGRADE', readinessBlocker: `NOT_IMPLEMENTED: LICENSED_INTERFACE_REQUIRED — ${src.prerequisite}; press/registry.js names the source so the collector refuses it with zero calls (the frozen RUMOR-2 core stays publisher-free: doctrine/RUMOR2.md)`, smokeEvidence: PRESS_SMOKE[src.id] })); continue; }
    const cls = src.id === 'FT_NEWS' ? 'CODE_PATH_COMPLETE_EXTERNAL_ACCESS_BLOCKED' : 'OPERATIONAL_PUBLIC';
    const blocker = src.id === 'FT_NEWS' ? `EXTERNAL_ACCESS_BLOCKED (HTTP 403 to the runtime client from the development environment on 2026-09-12); ${pr?.reason ?? 'OFF'} (profile OFF)` : pr?.desiredState === 'OFF' ? `${pr.reason} (profile OFF; enable by setting the profile row ON — no code change)` : src.terms === 'UNVERIFIED' ? 'TERMS_UNVERIFIED (headline / link use only; the owner confirms syndication terms)' : null;
    rows.push(row({ id: src.id, group: 'PUBLISHER_NEWS', family: src.kind, classification: cls, module: 'press/collector.js (+ press/registry.js, press/parse.js, press/reader.js)', compositionPath: 'fly.js -> startPress (dark; PRESS_ENABLED + PRESS_SOURCES from the profile); observations <data>/press/observations.jsonl; status <data>/press/status.json; reader press/reader.js; CLI cobra press status | tail', enable: `profile publisherNews.${src.id} ON -> PRESS_ENABLED=true + PRESS_SOURCES contains ${src.id}`, credentialEnv: [], paid: false, budgetGovernor: `polite polling: cadence ${src.cadenceSec}s, If-None-Match / If-Modified-Since, Retry-After honoured, exponential backoff to 1h`, retentionTermsGate: `headline / link / publisher timestamp only (${src.terms === 'UNVERIFIED' ? 'terms UNVERIFIED' : src.terms}); bodies never fetched; observations file capped at 50 MiB`, liveTransport: true, durableTruth: 'local JSONL observations + per-source checkpoint (etag / last-modified / seen ids); NOT a RUMOR-2 journal event', pointInTimeContract: 'publishedTs from the feed (null when absent), receiptTs / knownAtTs from the collector clock; future-dated items skipped', replay: 'none (observations are a headline log, never replayed into a decision)', decisionAuthority: NONE, paperAuthority: NONE, paperDesiredState: pr?.desiredState ?? 'OFF', blockerPolicy: pr?.blockerPolicy ?? 'DEGRADE', readinessBlocker: blocker, smokeEvidence: PRESS_SMOKE[src.id] }));
  }
  // ---- INFRASTRUCTURE observation tier (infra/): NOAA SWPC (EXPERIMENTAL), RIPE RIS routing status, Cloudflare Radar BGP ----------------
  const INFRA_SMOKE = Object.freeze({
    NOAA_SWPC: '2026-09-12: services.swpc.noaa.gov/products/noaa-planetary-k-index.json HTTP 200 (rows {time_tag, Kp, a_running, station_count}) and noaa-scales.json HTTP 200 (keys "-1".."3"); live read through infra/collector.js pollOnce: docs/evidence/sensor-implementation-2026-09-12.md',
    RIPE_RIS: '2026-09-12: stat.ripe.net/data/routing-status/data.json?resource=1.1.1.0/24 HTTP 200 status ok (data_call_status supported); a one-off documented example resource was read through infra/collector.js for the receipt — the PAPER watch list stays CONFIG_REQUIRED until the owner names INFRA_RIPE_RESOURCES',
    CLOUDFLARE_RADAR: '2026-09-12: api.cloudflare.com/client/v4/radar/bgp/timeseries unauthenticated -> HTTP 400 code 9106 (token required); the OpenAPI response shape (meta + serie_0 {timestamps, values}) is parsed from the documented schema; NOT live smoked (no CLOUDFLARE_API_TOKEN in this environment)',
  });
  for (const src of INFRA_SOURCES) {
    const pr = prof('infrastructure', src.id); const cred = src.credentialEnv ? [src.credentialEnv] : []; const keyPresent = src.credentialEnv ? present(env, src.credentialEnv) : true; const cfgPresent = src.configEnv ? present(env, src.configEnv) : true;
    const cls = src.credentialEnv ? 'IMPLEMENTED_NOT_LIVE_SMOKED' : 'OPERATIONAL_PUBLIC';
    const blocker = src.credentialEnv && !keyPresent ? `CREDENTIAL_MISSING (${src.credentialEnv}); zero calls until present` : src.configEnv && !cfgPresent ? `CONFIG_REQUIRED:${src.configEnv} (the operator names the monitored prefixes / ASNs; nothing is invented); zero calls until set` : src.credentialEnv ? 'credential present: live response shape unproven from this environment' : null;
    rows.push(row({ id: src.id === 'NOAA_SWPC' ? 'NOAA_SWPC_SPACE_WEATHER' : src.id === 'RIPE_RIS' ? 'RIPE_RIS_BGP' : src.id, group: 'INFRASTRUCTURE', family: src.kind, classification: cls, module: 'infra/collector.js (+ infra/registry.js, infra/parse.js, infra/reader.js)', compositionPath: `fly.js -> startInfra (dark; INFRA_OBS_ENABLED + INFRA_SOURCES from the profile); observations <data>/infra/observations.jsonl; status <data>/infra/status.json; reader infra/reader.js; CLI cobra infra status | tail${src.experimental ? '; EXPERIMENTAL family' : ''}`, enable: `profile infrastructure.${src.id} ${pr?.desiredState ?? 'OFF'} -> INFRA_OBS_ENABLED=true + INFRA_SOURCES contains ${src.id}${src.configEnv ? ` + ${src.configEnv}` : ''}${src.credentialEnv ? ` + ${src.credentialEnv}` : ''}`, credentialEnv: cred, paid: false, budgetGovernor: `cadence ${src.cadenceSec}s; bounded 2 MiB JSON; exponential backoff to 1h; Retry-After honoured${src.credentialEnv ? '; token-refused answers park the source for 1h (CREDENTIAL_REQUIRED)' : ''}`, retentionTermsGate: 'public documented data API (route + docs dated in infra/registry.js); observations file capped at 50 MiB', liveTransport: true, durableTruth: 'local JSONL observations + per-source checkpoint; never a decision input', pointInTimeContract: `source clock as served (${src.id === 'RIPE_RIS' ? 'day precision' : 'UTC timestamps'}) + receiptTs; a measurement exists only from a parsed payload`, replay: 'none', decisionAuthority: NONE, paperAuthority: NONE, paperDesiredState: pr?.desiredState ?? 'OFF', blockerPolicy: pr?.blockerPolicy ?? 'DEGRADE', readinessBlocker: blocker, smokeEvidence: INFRA_SMOKE[src.id] }));
  }
  // ---- SOCIAL VIDEO (video/): YouTube public metadata — a separate social-observation tier outside the sealed RUMOR-2 social registry ---
  const ytKey = present(env, 'YOUTUBE_API_KEY'); const ytQueries = present(env, 'SOCIAL_VIDEO_YOUTUBE_QUERIES'); const ytBudget = present(env, 'SOCIAL_VIDEO_YOUTUBE_MAX_DAILY_SEARCHES'); const yt = prof('social', 'YOUTUBE_DATA_API');
  rows.push(row({ id: 'YOUTUBE_DATA_API', group: 'SOCIAL', family: 'SOCIAL_VIDEO', classification: 'IMPLEMENTED_NOT_LIVE_SMOKED', module: 'video/collector.js (+ video/registry.js, video/parse.js, video/reader.js)', compositionPath: 'fly.js -> startVideo (dark; SOCIAL_VIDEO_ENABLED from the profile; the closed gate decides with zero requests); observations <data>/video/observations.jsonl; status <data>/video/status.json; reader video/reader.js; CLI cobra video status | tail — NOT a RUMOR-2 social provider (rumor2/social-registry.js is sealed; its validators refuse unregistered providers)', enable: 'profile social.YOUTUBE_DATA_API REQUEST -> SOCIAL_VIDEO_ENABLED=true; then YOUTUBE_API_KEY + SOCIAL_VIDEO_YOUTUBE_QUERIES + SOCIAL_VIDEO_YOUTUBE_MAX_DAILY_SEARCHES', credentialEnv: ['YOUTUBE_API_KEY'], paid: false, budgetGovernor: 'explicit daily search.list budget (no default is ever read) counted per Pacific accounting day in the durable checkpoint; one search per poll in query rotation; interval = max(900 s, day / budget); quotaExceeded parks until the next day; documented default quota 100 search.list calls / day', retentionTermsGate: 'YouTube API Services Terms (owner accepts at key issue); METADATA_ONLY — title / description snippet / channel / publish clock / public counters; never captions, transcripts, comments, media or viewer identity; observations file capped at 50 MiB', liveTransport: true, durableTruth: 'local JSONL observations + checkpoint; never a RUMOR-2 event', pointInTimeContract: 'publishedAt (RFC 3339) + receiptTs / knownAtTs from the collector clock; future-dated items rejected', replay: 'none', decisionAuthority: NONE, paperAuthority: NONE, paperDesiredState: yt?.desiredState ?? 'OFF', blockerPolicy: yt?.blockerPolicy ?? 'DEGRADE', readinessBlocker: !ytKey ? 'CREDENTIAL_MISSING (YOUTUBE_API_KEY); zero requests until present' : !ytQueries ? 'CONFIG_REQUIRED:SOCIAL_VIDEO_YOUTUBE_QUERIES (the operator names the queries; nothing is invented)' : !ytBudget ? 'BUDGET_NOT_CONFIGURED (SOCIAL_VIDEO_YOUTUBE_MAX_DAILY_SEARCHES)' : 'gate satisfied by env NAMES; live response shape unproven from this environment', smokeEvidence: '2026-09-12: developers.google.com/youtube/v3/getting-started (200: default quota 100 search.list calls + 10,000 units / day), docs/search/list (200), docs/videos/list (200, 1 unit), cloud.google.com API-key header docs (200); live denied path observed: unauthenticated search.list HTTP 403 "unregistered callers", malformed header key HTTP 400; NOT live smoked with a real key (none in this environment)' }));
  // ---- doctrine-required senses NOT PRESENT (stated, never silently called complete) ------------------------------------------------
  for (const [id,module] of [['META_REALTIME_TRANSPORT','rumor2/social-current-clients.js'],['FARCASTER_LIVE_TRANSPORT','rumor2/social-farcaster-runtime.js']]) rows.push(row({id,group:'SOCIAL',family:'SOCIAL',classification:'CODE_PATH_COMPLETE_EXTERNAL_ACCESS_BLOCKED',module,compositionPath:'fly.js -> RUMOR2 collector -> provider runtime',enable:'requested paper social profile; source-specific credential, scope, access review and request allowance',credentialEnv:id.startsWith('META')?['META_APP_TOKEN']:['NEYNAR_API_KEY'],paid:false,budgetGovernor:'journaled request reservations; Meta routes share a lane',retentionTermsGate:'operator/provider access review required',liveTransport:true,durableTruth:id.startsWith('META')?'current RAM view, five-minute expiry; anonymous request meter only is journaled':'existing fenced social journal',pointInTimeContract:'source timestamp separate from retrieval',replay:id.startsWith('META')?'no historical content; refetch current scope':'durable social reconciliation',decisionAuthority:NONE,paperAuthority:NONE,paperDesiredState:'REQUEST',blockerPolicy:'DEGRADE',readinessBlocker:'credentials / approved scope / explicit request cap',smokeEvidence:'new composed offline tests; NOT live verified'}));
  rows.push(row({id:'TIKTOK_REALTIME_TRANSPORT',group:'SOCIAL',family:'SOCIAL',classification:'NOT_PRESENT',module:null,compositionPath:'not composed',enable:'none',credentialEnv:[],paid:false,budgetGovernor:'none',retentionTermsGate:'no eligible public market-intelligence route established',liveTransport:false,durableTruth:'none',pointInTimeContract:'none',replay:'none',decisionAuthority:NONE,paperAuthority:NONE,paperDesiredState:'OFF',blockerPolicy:'DEGRADE',readinessBlocker:'NOT_IMPLEMENTED: institutional Research eligibility not established; own-account Display is insufficient',smokeEvidence:'2026-09-12 source inspection: rumor2/social-tiktok.js access review; no live transport or live smoke'}));
  for (const [rowIndex,r] of rows.entries()) if (['REDDIT_OFFICIAL','STOCKTWITS_OFFICIAL','META_PUBLIC','FARCASTER_OFFICIAL'].includes(r.id)) {
    const fc=r.id==='FARCASTER_OFFICIAL';rows[rowIndex]=Object.freeze({...r,classification:'CODE_PATH_COMPLETE_EXTERNAL_ACCESS_BLOCKED',module:fc?'rumor2/social-farcaster-runtime.js':'rumor2/social-current-runtime.js + rumor2/social-current-clients.js',compositionPath:fc?'fly.js -> RUMOR2 collector -> social journal -> research projection':'fly.js -> RUMOR2 collector -> erasable current view -> owner Senses panel',enable:fc?'RUMOR2_SOCIAL_FARCASTER_ENABLED plus scoped access and request allowance':'RUMOR2_SOCIAL_CURRENT_ENABLED plus provider-specific enable, access and request allowance',budgetGovernor:'request reservation acknowledged in the existing journal before dispatch',retentionTermsGate:fc?'approved DERIVED_FEATURES and compatible existing Social journal retention':'approved RETRIEVAL; current content and identities RAM only, max five minutes',replay:fc?'JOURNAL_REPLAY':'CURRENT_VIEW_ONLY (anonymous accounting replays; posts do not)',liveTransport:true,durableTruth:fc?'existing epoch-fenced social journal':'anonymous request counts only; content/identity RAM expires within five minutes',paperDesiredState:'REQUEST',readinessBlocker:'source-scoped approval, credentials, query/entity scope and explicit request allowance required',smokeEvidence:fc?'test/farcaster-runtime.test.js (offline injected transport)':'test/social-current-runtime.test.js (offline injected transport)'});
  }
  const secrets = secretPresence(profile, env); const counts = Object.fromEntries(CLASSIFICATIONS.map((c) => [c, rows.filter((r) => r.classification === c).length]));
  return Object.freeze({ inventoryVersion: INVENTORY_VERSION, generatedTs: clock(), profile: profile.profileName, policyFile: profile.files.marketResearchPolicy, classifications: [...CLASSIFICATIONS], counts, rows, secretNamesPresent: Object.entries(secrets).filter(([, v]) => v).map(([k]) => k), law: 'derived from the registries at generation time; classification never implies edge or authority; secret VALUES never appear here' });
}
export const inventoryRow = (inv, id) => inv.rows.find((r) => r.id === id) ?? null;
