// SERPENT PAPER — the REPOSITORY-WIDE SENSOR INVENTORY, derived from the ACTUAL registries (market-lab/registry.js, the paper
// market-research policy, rumor2/registry.js, rumor2/social-registry.js, cobra.config.json gateway sources) plus the curated
// composition facts of the core / decision components (module + startup path). Every row is classified with the closed
// closeout vocabulary; a doctrine mention never resurrects a sense the repository does not implement. Read-only, no network.
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { loadConfig } from '../lib/config.js';
import { PROVIDERS as MARKET_PROVIDERS } from '../market-lab/registry.js';
import { PROVIDER_IDS as MARKET_PROVIDER_IDS } from '../market-lab/contracts.js';
import { paidCallAuthorized } from '../market-lab/policy.js';
import { PROVIDERS as OFFICIAL_PROVIDERS } from '../rumor2/registry.js';
import { SOCIAL_PROVIDERS } from '../rumor2/social-registry.js';
import { loadProfile, profileFileOf, secretPresence } from './profile.js';

export const INVENTORY_VERSION = 'serpent-sensor-inventory-1';
export const CLASSIFICATIONS = Object.freeze(['OPERATIONAL_PUBLIC', 'OPERATIONAL_CREDENTIAL_GATED', 'IMPLEMENTED_NOT_LIVE_SMOKED', 'CODE_PATH_COMPLETE_EXTERNAL_ACCESS_BLOCKED', 'FOUNDATION_ONLY', 'DEPRECATED', 'NOT_PRESENT']);
export const INVENTORY_GROUPS = Object.freeze(['CORE_MARKET', 'INFRASTRUCTURE', 'RUMOR_OFFICIAL', 'SOCIAL', 'MARKET_RESEARCH', 'DARK_RESEARCH', 'DECISION', 'PUBLISHER_NEWS']);
export const ROW_KEYS = Object.freeze(['id', 'group', 'family', 'classification', 'module', 'compositionPath', 'enable', 'credentialEnv', 'paid', 'budgetGovernor', 'retentionTermsGate', 'liveTransport', 'durableTruth', 'pointInTimeContract', 'replay', 'decisionAuthority', 'paperAuthority', 'paperDesiredState', 'blockerPolicy', 'readinessBlocker', 'smokeEvidence']);
// repository-known live-smoke facts (dated; a reference, never a runtime claim)
export const SMOKE_FACTS = Object.freeze({
  TAPE: 'Kraken WS v2 public feed: continuous live operation on the deployment; doctrine/WIDEEYE.md, doctrine/DEPLOYMENT.md. 2026-09-12 local OBSERVE run (no credentials, no orders): 34231 CRC-verified book snapshots and 537 trades delivered to the Judge consumer in 5 minutes, 0 CRC failures (docs/evidence/operational-repair-2026-09-12.md)',
  KRAKEN_SPOT: 'PROBED_OK 2026-09-12 read-only preflight smoke, 622 markets (docs/evidence/operational-repair-2026-09-12.md); L01', COINBASE_SPOT: 'PROBED_OK 2026-09-12 (record count not reported by the endpoint); L01', KRAKEN_DERIVATIVES: 'PROBED_OK 2026-09-12, 295 records; L01', DERIBIT: 'PROBED_OK 2026-09-12, 950 records; L01', GECKOTERMINAL: 'PROBED_OK 2026-09-12, 1 record; L01', DEFILLAMA: 'PROBED_OK 2026-09-12, 1 record; L01', COINMETRICS: 'PROBED_OK 2026-09-12 (community API); L01',
  BYBIT: 'HTTP 403 from this build environment (geo / access), 2026-09-11 read-only probe; 2026-09-12 NOT_PROBED (PROVIDER_DISABLED by the paper policy); docs/MARKET-SOCRATES-ACCEPTANCE.md',
  COINGLASS: 'docs/MARKET-SOCRATES-ACCEPTANCE.md L02: BLOCKED (no entitled plan)', CRYPTOQUANT: 'L02: BLOCKED', SANTIMENT: 'L02: BLOCKED', TWELVEDATA: 'L02: BLOCKED', TOKENOMIST: 'L02: BLOCKED', COINGECKO: 'Demo key receipt 2026-09-12: two authorized zero-cost calls (catalog + coins-markets), both settled, one observation sealed in bundle mb-d0cb3c5d606789fc4c12ea3463e4c837bd9a50da06fbaeebc7a0b036833a04a8; local two-call entitlement exhausted; production not verified', FRED: '2026-09-12 bounded capture: 16 successful requests, 240 observations sealed in bundle mb-d0cb3c5d606789fc4c12ea3463e4c837bd9a50da06fbaeebc7a0b036833a04a8; production not verified',
  SETTLED_RECORDS: 'local settled records (no network)', BLUESKY_OFFICIAL: 'Jetstream public read 2026-09-12: open 461 ms, 200 messages in 3.3 s, 200/200 mapped to valid shared-contract observations (112 posts / 88 reposts), 0 skips, provider sequence 25754477318; durable delivery to the RUMOR2 event root NOT proven locally (no DATABASE_URL); docs/evidence/operational-repair-2026-09-12.md, doctrine/SOCIAL.md §5B', X_OFFICIAL: 'never spent (paid; explicit smoke envelope required)',
  KRAKEN_OFFICIAL: 'doctrine/RUMOR2.md (official feed live on the deployment); 2026-09-12 local read through rumor2/http.js + feed.js: HTTP 200, 10 items parsed, 0 truncated (docs/evidence/sensor-scope-2026-09-12.md)', SEC_OFFICIAL: 'doctrine/RUMOR2.md; NOT_QUERIED locally (SERPENT_HTTP_CONTACT unset: the SEC user-agent law is never bypassed)', CFTC_OFFICIAL: 'doctrine/RUMOR2.md; 2026-09-12 local read through rumor2/http.js + feed.js: HTTP 200, 10 items parsed', EDGAR_OFFICIAL: 'doctrine/RUMOR2.md (RUMOR-2B1; whitelist-gated); NOT_QUERIED locally (contact + CIK whitelist unset)', OFAC_OFFICIAL: 'doctrine/RUMOR2.md (RUMOR-2B1); 2026-09-12 local read through rumor2/http.js: HTTP 200, SDN CSV 5.69 MB / 19389 lines within the provider byte bound',
  GATEWAY: 'doctrine/GATEWAY.md (public status pages; polite polling); 2026-09-12 local reads through gateway/parse.js: status.kraken.com 200 (7 events, 0 unparsed, indicator minor), status.coinbase.com 200 (1 event, door UNKNOWN as parsed), api.kraken.com SystemStatus 200 (online), okx system status 200 (code 0)', WIDEEYE: 'doctrine/WIDEEYE.md', RUMINT: 'doctrine/RUMINT.md (StockTwits aggregate ear; RUMINT-R1); 2026-09-12 local read through rumint/stocktwits.js fetchSymbolPage(BTC.X): ok, 30 messages, cursor present', KRAKEN_OHLC: '2026-09-12 local read through judge/history.js refresh(XBT/USD): ok, 721 rows, 720 closed bars retained, 61-bar block complete (missingOf61 0)', REPLAY: 'no network by design; test/judge-composition.test.js P03 (same bytes + clocks -> same digests), test/judge-experiment-replay.test.js, test/childhood.test.js', KRAKEN_CHARTS: 'public poll 2026-09-12: PF_XBTUSD open-interest 60 s, 2 observations, acquisition COMPLETE, coverage OBSERVED (docs/evidence/operational-repair-2026-09-12.md)', KRAKEN_L3: 'NOT_RUN_NO_SAFE_L3_DATA_KEY (2026-09-12 probe: CREDENTIAL_MISSING). Separate from the Judge book route: no module under judge/, execution/, watch/ or tape/ names L3 at all',
});
const PROVIDER_MODULES = Object.freeze({ KRAKEN_SPOT: 'kraken-spot.js', COINBASE_SPOT: 'coinbase.js', KRAKEN_DERIVATIVES: 'kraken-derivatives.js', DERIBIT: 'deribit.js', BYBIT: 'bybit.js', COINGECKO: 'coingecko.js', GECKOTERMINAL: 'coingecko.js', DEFILLAMA: 'defillama.js', COINGLASS: 'coinglass.js', CRYPTOQUANT: 'cryptoquant.js', SANTIMENT: 'santiment.js', COINMETRICS: 'coinmetrics.js', FRED: 'fred.js', TWELVEDATA: 'twelvedata.js', SETTLED_RECORDS: 'settled.js', TOKENOMIST: 'tokenomist.js' });
const row = (o) => { const r = {}; for (const k of ROW_KEYS) r[k] = o[k] === undefined ? null : o[k]; if (!CLASSIFICATIONS.includes(r.classification)) throw new Error(`inventory ${r.id}: classification ${r.classification}`); if (!INVENTORY_GROUPS.includes(r.group)) throw new Error(`inventory ${r.id}: group`); return Object.freeze(r); };
const present = (env, names) => (Array.isArray(names) ? names : [names]).filter(Boolean).every((n) => typeof env[n] === 'string' && env[n].length > 0);
const readJson = (f) => JSON.parse(readFileSync(f, 'utf8'));

export function sensorInventory({ profile = loadProfile(), env = process.env, config = loadConfig(), clock = () => Date.now() } = {}) {
  const g = profile.groups; const policy = readJson(profileFileOf(profile, 'marketResearchPolicy')); const rows = [];
  const prof = (grp, id) => g[grp]?.[id] ?? null; const mrProf = (id) => g.marketResearch.providers[id] ?? null;
  const NONE = 'NONE';
  // ---- CORE MARKET / SURVEY --------------------------------------------------------------------------------------------------
  rows.push(row({ id: 'TAPE', group: 'CORE_MARKET', family: 'KRAKEN_PUBLIC_MARKET_DATA', classification: 'OPERATIONAL_PUBLIC', module: 'tape/run.js', compositionPath: 'fly.js -> runTape (last; execution feed + research observer seams)', enable: 'always (cobra.config.json tape.*)', credentialEnv: [], paid: false, budgetGovernor: 'none (public WS)', retentionTermsGate: 'public market data', liveTransport: true, durableTruth: 'tape store (jsonl) + PostgreSQL mirror', pointInTimeContract: 'receipt clocks + feature snapshot', replay: 'experiment input bundles (judge)', decisionAuthority: 'FEED_ONLY', paperAuthority: 'FEED_ONLY', paperDesiredState: prof('coreObservation', 'tape').desiredState, blockerPolicy: prof('coreObservation', 'tape').blockerPolicy, readinessBlocker: null, smokeEvidence: SMOKE_FACTS.TAPE }));
  rows.push(row({ id: 'WIDEEYE', group: 'CORE_MARKET', family: 'FULL_UNIVERSE_SURVEY', classification: 'OPERATIONAL_PUBLIC', module: 'survey/wideeye.js', compositionPath: 'fly.js -> startWideEye', enable: 'cobra.config.json wideeye.enabled / WIDEEYE_ENABLED', credentialEnv: [], paid: false, budgetGovernor: 'sweep cadence + catalog resource settings', retentionTermsGate: 'public market data', liveTransport: true, durableTruth: 'survey status + nominations', pointInTimeContract: 'sweep population snapshot', replay: 'none', decisionAuthority: NONE, paperAuthority: NONE, paperDesiredState: prof('coreObservation', 'wideEye').desiredState, blockerPolicy: prof('coreObservation', 'wideEye').blockerPolicy, readinessBlocker: config.wideeye?.enabled ? null : 'DISABLED_BY_CONFIG', smokeEvidence: SMOKE_FACTS.WIDEEYE }));
  rows.push(row({ id: 'UNIVERSE_EXPANSION', group: 'CORE_MARKET', family: 'DEEP_OBSERVATION_SET', classification: 'OPERATIONAL_PUBLIC', module: 'tape/universe.js', compositionPath: 'tape/run.js (subscription selection)', enable: 'cobra.config.json universeExpansion.enabled', credentialEnv: [], paid: false, budgetGovernor: 'resource caps (heap / loop lag / shed fraction)', retentionTermsGate: 'public market data', liveTransport: true, durableTruth: 'universe current.json', pointInTimeContract: 'selection date / selectedAt', replay: 'none', decisionAuthority: NONE, paperAuthority: NONE, paperDesiredState: prof('coreObservation', 'universeExpansion').desiredState, blockerPolicy: prof('coreObservation', 'universeExpansion').blockerPolicy, readinessBlocker: config.universeExpansion?.enabled ? null : 'DISABLED_BY_CONFIG', smokeEvidence: SMOKE_FACTS.TAPE }));
  rows.push(row({ id: 'COST_EXECUTABILITY', group: 'CORE_MARKET', family: 'EXECUTION_COST_MODEL', classification: 'OPERATIONAL_PUBLIC', module: 'cost/model.js + judge/cost.js', compositionPath: 'bin/cobra.js cost; judge intake (book age law)', enable: 'always (cobra.config.json cost.*)', credentialEnv: [], paid: false, budgetGovernor: 'none', retentionTermsGate: 'derived from public book', liveTransport: false, durableTruth: 'current book files', pointInTimeContract: 'maxBookAgeSec freshness law', replay: 'judge experiment replay', decisionAuthority: 'INPUT_TO_JUDGE_READINESS', paperAuthority: 'INPUT_TO_JUDGE_READINESS', paperDesiredState: prof('coreObservation', 'costExecutability').desiredState, blockerPolicy: prof('coreObservation', 'costExecutability').blockerPolicy, readinessBlocker: null, smokeEvidence: 'derived (no network)' }));
  rows.push(row({ id: 'MEMORY_MIRROR', group: 'CORE_MARKET', family: 'DURABLE_MEMORY', classification: 'OPERATIONAL_PUBLIC', module: 'memory/mirror.js', compositionPath: 'fly.js -> startMemoryMirror (dark; no return path)', enable: 'always', credentialEnv: [], paid: false, budgetGovernor: 'none', retentionTermsGate: 'internal', liveTransport: false, durableTruth: 'PostgreSQL memory + childhood archive', pointInTimeContract: 'settled-event knownAt', replay: 'childhood archive (read-only)', decisionAuthority: NONE, paperAuthority: NONE, paperDesiredState: prof('coreObservation', 'memoryMirror').desiredState, blockerPolicy: prof('coreObservation', 'memoryMirror').blockerPolicy, readinessBlocker: null, smokeEvidence: 'doctrine/MEMORY.md' }));
  rows.push(row({ id: 'RESEARCH_STRAINER', group: 'CORE_MARKET', family: 'SOCIAL_RESEARCH_STRAINER', classification: 'OPERATIONAL_PUBLIC', module: 'rumor2/social-research-strainer.js', compositionPath: 'fly.js -> RUMOR2 collector (the composition root wires the social strainer)', enable: 'composition (fly.js) — always in the paper profile', credentialEnv: [], paid: false, budgetGovernor: 'none', retentionTermsGate: 'derived dossiers only', liveTransport: false, durableTruth: 'dossier records', pointInTimeContract: 'as-of composite', replay: 'none', decisionAuthority: NONE, paperAuthority: NONE, paperDesiredState: prof('coreObservation', 'socialStrainer').desiredState, blockerPolicy: prof('coreObservation', 'socialStrainer').blockerPolicy, readinessBlocker: null, smokeEvidence: 'doctrine/SOCIAL.md §36' }));
  // ---- EXCHANGE / INFRASTRUCTURE -----------------------------------------------------------------------------------------------
  const gw = prof('infrastructure', 'gateway'); const sources = config.gateway?.sources ?? {};
  for (const [src, label, host] of [['kraken', 'GATEWAY_KRAKEN_STATUS', 'status.kraken.com'], ['krakenSystem', 'GATEWAY_KRAKEN_SYSTEM', 'api.kraken.com SystemStatus'], ['coinbase', 'GATEWAY_COINBASE_STATUS', 'status.coinbase.com'], ['okx', 'GATEWAY_OKX_STATUS', 'www.okx.com system status']]) {
    rows.push(row({ id: label, group: 'INFRASTRUCTURE', family: 'EXCHANGE_INFRASTRUCTURE', classification: 'OPERATIONAL_PUBLIC', module: 'gateway/collector.js', compositionPath: 'fly.js -> startGateway (collector only; wired to nothing)', enable: `cobra.config.json gateway.enabled + gateway.sources.${src} / GATEWAY_ENABLED`, credentialEnv: [], paid: false, budgetGovernor: 'pollSec floor 60 s + backoff', retentionTermsGate: `public status page (${host})`, liveTransport: true, durableTruth: 'incidents_state.json + matrix.json + events.jsonl', pointInTimeContract: 'observedAt per poll', replay: 'none', decisionAuthority: NONE, paperAuthority: NONE, paperDesiredState: gw.desiredState, blockerPolicy: gw.blockerPolicy, readinessBlocker: sources[src] === false ? 'SOURCE_DISABLED_BY_CONFIG' : null, smokeEvidence: SMOKE_FACTS.GATEWAY }));
  }
  rows.push(row({ id: 'GOVERNANCE_TALLY', group: 'INFRASTRUCTURE', family: 'GOVERNANCE', classification: 'FOUNDATION_ONLY', module: 'governance/collector.js', compositionPath: 'fly.js -> startGovernance (dark; no config key => off)', enable: 'cobra.config.json governance (absent in this repo)', credentialEnv: ['TALLY_API_KEY'], paid: false, budgetGovernor: 'collector budget', retentionTermsGate: 'zero verified mappings', liveTransport: true, durableTruth: 'gov checkpoint', pointInTimeContract: 'checkpoint', replay: 'none', decisionAuthority: NONE, paperAuthority: NONE, paperDesiredState: 'OFF', blockerPolicy: 'DEGRADE', readinessBlocker: 'FOUNDATION_ONLY (no verified DAO mappings)', smokeEvidence: 'doctrine/GOVERNANCE.md' }));
  // ---- RUMINT / RUMOR OFFICIAL -------------------------------------------------------------------------------------------------
  const rl = prof('rumorOfficial', 'rumintLegacy');
  rows.push(row({ id: 'RUMINT_STOCKTWITS_AGGREGATE', group: 'RUMOR_OFFICIAL', family: 'LEGACY_RUMINT', classification: 'OPERATIONAL_PUBLIC', module: 'rumint/poller.js', compositionPath: 'fly.js -> startRumint', enable: 'cobra.config.json rumint.enabled / RUMINT_ENABLED', credentialEnv: [], paid: false, budgetGovernor: 'hourlyBudget + spacing + backoff', retentionTermsGate: 'aggregate counts only (no raw social content)', liveTransport: true, durableTruth: 'rumint checkpoint (PostgreSQL)', pointInTimeContract: 'poll clocks', replay: 'aggregate checkpoint only', decisionAuthority: 'NOMINATE_WARN_ONLY', paperAuthority: 'NOMINATE_WARN_ONLY', paperDesiredState: rl.desiredState, blockerPolicy: rl.blockerPolicy, readinessBlocker: config.rumint?.enabled ? null : 'DISABLED_BY_CONFIG', smokeEvidence: SMOKE_FACTS.RUMINT }));
  for (const p of OFFICIAL_PROVIDERS) {
    const pr = prof('rumorOfficial', p.id); const needContact = p.requiresContact && !present(env, 'SERPENT_HTTP_CONTACT');
    const blocker = p.id === 'EDGAR_OFFICIAL' && !present(env, 'RUMOR2_EDGAR_CIKS') ? 'CONFIG_REQUIRED:EDGAR_WHITELIST' : needContact ? 'CONFIG_REQUIRED:SERPENT_HTTP_CONTACT' : null;
    rows.push(row({ id: p.id, group: 'RUMOR_OFFICIAL', family: p.providerKind, classification: 'OPERATIONAL_PUBLIC', module: p.adapter === 'EDGAR_SUBMISSIONS' ? 'rumor2/edgar.js' : p.adapter === 'OFAC_SDN_CSV' ? 'rumor2/ofac.js' : 'rumor2/feed.js', compositionPath: 'fly.js -> RUMOR2 collector (RUMOR2_ENABLED)', enable: pr?.enableEnv ?? 'RUMOR2_ENABLED', credentialEnv: p.requiresContact ? ['SERPENT_HTTP_CONTACT (contact NAME, not a secret)'] : [], paid: false, budgetGovernor: `cadence ${p.cadenceSec}s, hourly budget ${p.hourlyBudget}`, retentionTermsGate: `official host ${p.host}; bounded references only`, liveTransport: true, durableTruth: 'PostgreSQL event journal (authoritative) + checkpoint', pointInTimeContract: 'settled-event clocks (RUMOR-2 truth law)', replay: 'journal replay', decisionAuthority: 'EVIDENCE_ONLY', paperAuthority: 'EVIDENCE_ONLY', paperDesiredState: pr?.desiredState ?? 'OFF', blockerPolicy: pr?.blockerPolicy ?? 'DEGRADE', readinessBlocker: blocker, smokeEvidence: SMOKE_FACTS[p.id] ?? null }));
  }
  // ---- SOCIAL ----------------------------------------------------------------------------------------------------------------
  for (const s of SOCIAL_PROVIDERS) {
    const pr = prof('social', s.id); const paid = s.id === 'X_OFFICIAL';
    const cls = s.id === 'BLUESKY_OFFICIAL' ? 'OPERATIONAL_PUBLIC' : s.id === 'X_OFFICIAL' ? 'OPERATIONAL_CREDENTIAL_GATED' : s.id === 'YOUTUBE_OFFICIAL' ? 'CODE_PATH_COMPLETE_EXTERNAL_ACCESS_BLOCKED' : s.foundation?.fixtureOnly ? 'FOUNDATION_ONLY' : 'CODE_PATH_COMPLETE_EXTERNAL_ACCESS_BLOCKED';
    const youtubeOn = env.RUMOR2_SOCIAL_YOUTUBE_ENABLED === 'true';
    const youtubeBudget = present(env, ['RUMOR2_SOCIAL_YOUTUBE_MAX_DAILY_QUOTA_UNITS', 'RUMOR2_SOCIAL_YOUTUBE_MAX_MONTHLY_QUOTA_UNITS']);
    const blocker = s.id === 'BLUESKY_OFFICIAL' ? null : s.id === 'X_OFFICIAL' ? (!present(env, 'X_BEARER_TOKEN') ? 'CREDENTIAL_MISSING' : !present(env, ['RUMOR2_SOCIAL_X_MAX_DAILY_POST_READS', 'RUMOR2_SOCIAL_X_MAX_MONTHLY_POST_READS', 'RUMOR2_SOCIAL_X_MAX_ESTIMATED_DAILY_USD']) ? 'BUDGET_NOT_CONFIGURED' : 'READY_REQUIRES_EXPLICIT_PAID_SMOKE') : s.id === 'YOUTUBE_OFFICIAL' ? (!youtubeOn ? 'DISABLED_BY_PAPER_POLICY' : !present(env, 'YOUTUBE_API_KEY') ? 'CREDENTIAL_MISSING' : !youtubeBudget ? 'BUDGET_NOT_CONFIGURED' : 'WATCH_SCOPE_NOT_CONFIGURED') : pr?.reason ?? s.accessState;
    const module = s.id === 'BLUESKY_OFFICIAL' ? 'rumor2/social-runtime.js + social-stream.js' : s.id === 'X_OFFICIAL' ? 'rumor2/x-runtime.js + x-stream.js' : s.id === 'YOUTUBE_OFFICIAL' ? 'rumor2/providers/youtube-official.js (fixture/request boundary; no collector)' : s.foundation?.module ?? (s.id === 'REDDIT_OFFICIAL' ? 'rumor2/social-reddit.js' : s.id === 'STOCKTWITS_OFFICIAL' ? 'rumor2/social-stocktwits.js' : null);
    const budgetGovernor = paid ? 'x-runtime governor: daily / monthly / USD caps + explicit paid smoke' : s.id === 'YOUTUBE_OFFICIAL' ? 'search.list hard cost 100 quota units/request + explicit daily/monthly quota-unit caps' : 'none';
    rows.push(row({ id: s.id, group: 'SOCIAL', family: 'SOCIAL', classification: cls, module, compositionPath: s.durable ? 'fly.js -> RUMOR2 collector (social gate)' : 'not composed (foundation / access boundary only)', enable: pr?.enableEnv ?? (s.id === 'YOUTUBE_OFFICIAL' ? 'RUMOR2_SOCIAL_YOUTUBE_ENABLED' : 'not enableable'), credentialEnv: [s.credentialEnv, ...(s.foundation?.credentialEnvs ?? [])].filter(Boolean), paid, budgetGovernor, retentionTermsGate: `${s.accessState}${s.retention ? `; retention ${s.retention}` : ''}`, liveTransport: s.durable === true && s.transport !== null, durableTruth: s.durable ? 'PostgreSQL social journal' : 'none', pointInTimeContract: s.durable ? 'social settle law (SOCIAL-1)' : 'fixture only', replay: s.durable ? 'JOURNAL_REPLAY' : 'FIXTURE_REPLAY_ONLY', decisionAuthority: NONE, paperAuthority: NONE, paperDesiredState: pr?.desiredState ?? 'OFF', blockerPolicy: pr?.blockerPolicy ?? 'DEGRADE', readinessBlocker: blocker, smokeEvidence: SMOKE_FACTS[s.id] ?? (s.id === 'YOUTUBE_OFFICIAL' ? 'none (no receipt; fixture-only)' : 'none (no lawful live route)') }));
  }
  // ---- MARKET-LAB / DEEP MARKET ---------------------------------------------------------------------------------------------
  for (const id of MARKET_PROVIDER_IDS) {
    const reg = MARKET_PROVIDERS[id]; const pol = policy.providers[id]; const pr = mrProf(id); const cred = pol?.credentialEnv ?? null;
    const quotaGated = pol?.plan?.billing !== 'FREE'; const paidPlan = pol?.plan?.billing !== 'FREE' && !(id === 'COINGECKO' && pol?.plan?.billing === 'INCLUDED_QUOTA' && pol?.plan?.incrementalUsdPerCall === 0 && pol?.plan?.quoteUsdPerMonth === 0); const keyPresent = cred ? present(env, cred) : true;
    const cls = id === 'BYBIT' ? 'CODE_PATH_COMPLETE_EXTERNAL_ACCESS_BLOCKED' : cred ? 'OPERATIONAL_CREDENTIAL_GATED' : 'OPERATIONAL_PUBLIC';
    const blocker = id === 'BYBIT' ? 'BLOCKED_GEOGRAPHY' : id === 'COINGECKO' ? (!keyPresent ? 'CREDENTIAL_MISSING' : quotaGated && !paidCallAuthorized(policy, id) ? 'BLOCKED_BUDGET (plan / cost attestation required in the policy)' : null) : quotaGated ? (keyPresent ? 'BLOCKED_BUDGET (plan / cost attestation required in the policy)' : 'CREDENTIAL_MISSING + BLOCKED_BUDGET') : cred && !keyPresent ? 'CREDENTIAL_MISSING' : null;
    rows.push(row({ id, group: 'MARKET_RESEARCH', family: reg.name, classification: cls, module: `market-lab/providers/${PROVIDER_MODULES[id]}`, compositionPath: 'fly.js -> createResearchService (MARKET_RESEARCH_ENABLED) -> owner', enable: `policy providers.${id}.enabled`, credentialEnv: cred ? [cred] : [], paid: paidPlan, budgetGovernor: 'market-lab quota journal + dispatch guard (maxCallsPerDay / Month, smoke caps)', retentionTermsGate: `hosts ${reg.hosts.join(', ')}`, liveTransport: true, durableTruth: 'sealed CAPTURE bundles + accounting journal', pointInTimeContract: 'observation envelope (sourceEventTs / receivedTs / knownAtTs / revision)', replay: 'REPLAY_AS_OF over sealed bundles', decisionAuthority: 'EVIDENCE_ONLY (decision families)', paperAuthority: 'EVIDENCE_ONLY', paperDesiredState: pr?.desiredState ?? 'OFF', blockerPolicy: pr?.blockerPolicy ?? 'DEGRADE', readinessBlocker: blocker, smokeEvidence: SMOKE_FACTS[id] ?? null }));
  }
  // ---- DARK RESEARCH (Kraken Charts + L3): EDGE_CAPTURE only; zero decision authority --------------------------------------------
  const ch = prof('darkEdgeCapture', 'krakenCharts'); const l3 = prof('darkEdgeCapture', 'krakenL3'); const l3Keys = present(env, ['KRAKEN_L3_DATA_API_KEY', 'KRAKEN_L3_DATA_API_SECRET']);
  rows.push(row({ id: 'KRAKEN_CHARTS_DARK', group: 'DARK_RESEARCH', family: 'DERIVATIVES_PRESSURE (dark)', classification: 'OPERATIONAL_PUBLIC', module: 'market-lab/providers/kraken-charts.js', compositionPath: 'bin/market-research.js edge-capture (bounded run) — never the decision owner', enable: 'policy providers.KRAKEN_DERIVATIVES.charts.enabled', credentialEnv: [], paid: false, budgetGovernor: 'charts maxCallsPerDay + polling cadence + accounting journal', retentionTermsGate: 'public futures.kraken.com charts API', liveTransport: true, durableTruth: 'sealed EDGE_CAPTURE bundles', pointInTimeContract: 'bucket period / receipt / knownAt / finality / vintage', replay: 'sealed bundle replay', decisionAuthority: NONE, paperAuthority: NONE, paperDesiredState: ch.desiredState, blockerPolicy: ch.blockerPolicy, readinessBlocker: policy.providers.KRAKEN_DERIVATIVES?.charts?.enabled ? null : 'DARK_CAPTURE_DISABLED_BY_POLICY', smokeEvidence: SMOKE_FACTS.KRAKEN_CHARTS }));
  rows.push(row({ id: 'KRAKEN_L3_DARK', group: 'DARK_RESEARCH', family: 'L3 order-level (dark)', classification: 'OPERATIONAL_CREDENTIAL_GATED', module: 'market-lab/providers/kraken-l3.js + kraken-l3-auth.js + l3-book.js', compositionPath: 'bin/market-research.js edge-capture — connection opens ONLY on a proven SAFE_L3_DATA_KEY', enable: 'policy providers.KRAKEN_SPOT.l3.enabled', credentialEnv: ['KRAKEN_L3_DATA_API_KEY', 'KRAKEN_L3_DATA_API_SECRET'], paid: false, budgetGovernor: 'weighted subscription pacer (W9) + queue / order / byte bounds', retentionTermsGate: 'dedicated DATA-ONLY key; never an execution credential', liveTransport: true, durableTruth: 'sealed EDGE_CAPTURE bundles (W12 markers)', pointInTimeContract: 'sourceEventTs + receivedTs + knownAtTs (W10)', replay: 'sealed bundle replay', decisionAuthority: NONE, paperAuthority: NONE, paperDesiredState: l3.desiredState, blockerPolicy: l3.blockerPolicy, readinessBlocker: l3Keys ? 'KEY_PRESENT_UNPROVEN (SAFE_L3_DATA_KEY verdict needs the read-only probe: preflight --smoke)' : 'BLOCKED_NO_SAFE_L3_DATA_KEY (CREDENTIAL_MISSING)', smokeEvidence: SMOKE_FACTS.KRAKEN_L3 }));
  // ---- DECISION / SUPERVISION -----------------------------------------------------------------------------------------------
  const soc = prof('socrates', 'model'); const modelKey = present(env, policy.model?.credentialEnv ?? 'ANTHROPIC_API_KEY'); const modelBudget = (policy.model?.maxEstimatedUsdPerCase ?? 0) > 0 && (policy.model?.maxEstimatedUsdPerDay ?? 0) > 0;
  rows.push(row({ id: 'SOCRATES', group: 'DECISION', family: 'INTERPRETATION', classification: 'OPERATIONAL_CREDENTIAL_GATED', module: 'socrates/runtime.js (+ broker, client, report)', compositionPath: 'market-lab/service.js case runtime (inside the research service)', enable: 'policy model.enabled + explicit USD caps', credentialEnv: [policy.model?.credentialEnv ?? 'ANTHROPIC_API_KEY'], paid: true, budgetGovernor: 'socrates budget (per case / day / month USD caps, model reservation)', retentionTermsGate: 'model output is interpretation, never source truth', liveTransport: true, durableTruth: 'sealed case bundles', pointInTimeContract: 'evidence v2 as-of packet', replay: 'recorded responses', decisionAuthority: 'SEALED_CASE_INPUT_TO_JUDGE', paperAuthority: 'SEALED_CASE_INPUT_TO_JUDGE', paperDesiredState: soc.desiredState, blockerPolicy: soc.blockerPolicy, readinessBlocker: !policy.model?.enabled ? 'MODEL_DISABLED_IN_POLICY (cases seal BUDGET_BLOCKED; Judge runs MARKET_DIRECT setups)' : !modelKey ? 'CREDENTIAL_MISSING' : !modelBudget ? 'BUDGET_NOT_CONFIGURED' : null, smokeEvidence: 'docs/MARKET-SOCRATES-ACCEPTANCE.md (recorded-response evaluation; no paid call in tests)' }));
  const jd = prof('judge', 'judge'); const db = present(env, 'DATABASE_URL');
  rows.push(row({ id: 'JUDGE', group: 'DECISION', family: 'DECISION', classification: 'OPERATIONAL_CREDENTIAL_GATED', module: 'judge/composition.js (+ intake, readiness, features, setups, judge, risk, cost, scheduler, recorder, history, owner, arming, experiment*, snapshot-store)', compositionPath: 'fly.js -> composeJudge (JUDGE_ENABLED; mode from the profile = PAPER)', enable: 'JUDGE_ENABLED + JUDGE_POLICY + JUDGE_MODE (forced PAPER)', credentialEnv: ['DATABASE_URL (journal authority; not a provider key)'], paid: false, budgetGovernor: 'risk limits / daily loss / drawdown restrictions (policy)', retentionTermsGate: 'internal', liveTransport: false, durableTruth: 'PostgreSQL execution journal (migration 8 / 9)', pointInTimeContract: 'permission clock + receipt-to-decision lag law', replay: 'journal replay + experiment replay', decisionAuthority: 'PAPER_DECISIONS', paperAuthority: 'PAPER_SIMULATION_ONLY', paperDesiredState: jd.desiredState, blockerPolicy: jd.blockerPolicy, readinessBlocker: db ? null : 'DATABASE_URL missing (PAPER needs the journal authority)', smokeEvidence: 'test/judge-e2e-pg.test.js + test/paper-e2e-pg.test.js (mock market inputs; PostgreSQL)' }));
  const wt = prof('watch', 'watch');
  rows.push(row({ id: 'WATCH', group: 'DECISION', family: 'SUPERVISION', classification: 'OPERATIONAL_CREDENTIAL_GATED', module: 'watch/watch.js', compositionPath: 'judge/composition.js (owns every non-FLAT position)', enable: 'with the Judge', credentialEnv: ['DATABASE_URL (through the Judge)'], paid: false, budgetGovernor: 'none', retentionTermsGate: 'internal', liveTransport: false, durableTruth: 'journal events', pointInTimeContract: 'fresh book / evidence context law', replay: 'journal replay', decisionAuthority: 'PAPER_EXIT_INTENT', paperAuthority: 'PAPER_EXIT_INTENT_ONLY', paperDesiredState: wt.desiredState, blockerPolicy: wt.blockerPolicy, readinessBlocker: db ? null : 'DATABASE_URL missing', smokeEvidence: 'test/judge-watch*.test.js + paper E2E' }));
  rows.push(row({ id: 'PAPER_EXECUTION', group: 'DECISION', family: 'EXECUTION_SIMULATION', classification: 'OPERATIONAL_CREDENTIAL_GATED', module: 'execution/paper-adapter.js + execution/journal.js + reconciliation', compositionPath: 'judge/composition.js (adapter PAPER; the LIVE adapter is never constructed without a LIVE policy + mode)', enable: 'judge policy execution.adapter PAPER', credentialEnv: ['DATABASE_URL'], paid: false, budgetGovernor: 'none', retentionTermsGate: 'internal', liveTransport: false, durableTruth: 'PostgreSQL execution journal', pointInTimeContract: 'arrival-window fills (paperMaxObservationWaitMs) else UNFILLED_COVERAGE_UNKNOWN', replay: 'journal replay', decisionAuthority: NONE, paperAuthority: 'SIMULATED_FILLS_ONLY', paperDesiredState: jd.desiredState, blockerPolicy: jd.blockerPolicy, readinessBlocker: db ? null : 'DATABASE_URL missing', smokeEvidence: 'test/judge-e2e-pg.test.js' }));
  // ---- Kraken 1m history + the point-in-time capture / replay capability (internal, present) ------------------------------------------
  rows.push(row({ id: 'KRAKEN_OHLC_HISTORY', group: 'CORE_MARKET', family: 'KRAKEN_PUBLIC_MARKET_DATA', classification: 'OPERATIONAL_PUBLIC', module: 'judge/history.js', compositionPath: 'judge/composition.js -> createBarHistory (REST OHLC cold start, live continuation from the execution feed trades)', enable: 'with the Judge (shared transport)', credentialEnv: [], paid: false, budgetGovernor: 'one bounded REST refresh per symbol when needsRefresh (720-row cap, never re-entrant)', retentionTermsGate: 'public market data', liveTransport: true, durableTruth: 'experiment input bundles (HISTORY rows under one capture sequence)', pointInTimeContract: 'closed 1m bars with a receipt floor (knownAtTs); the provisional minute and rows after `last` are dropped', replay: 'HISTORY rows replayed through ingestRows', decisionAuthority: 'FEED_ONLY', paperAuthority: 'FEED_ONLY', paperDesiredState: prof('coreObservation', 'tape').desiredState, blockerPolicy: prof('coreObservation', 'tape').blockerPolicy, readinessBlocker: null, smokeEvidence: SMOKE_FACTS.KRAKEN_OHLC }));
  rows.push(row({ id: 'HISTORICAL_CAPTURE_REPLAY', group: 'CORE_MARKET', family: 'POINT_IN_TIME_MEMORY', classification: 'OPERATIONAL_PUBLIC', module: 'judge/recorder.js + judge/experiment-replay.js + judge/experiment-store.js + childhood/fetch.js', compositionPath: 'judge/composition.js (JUDGE_RECORD_DIR -> sealed input bundles); bin/judge.js replay / replay-experiment (offline); childhood archive', enable: 'JUDGE_RECORD_DIR for capture; replay is an offline command', credentialEnv: [], paid: false, budgetGovernor: 'segment rotation + bounded retention (MC-5); a recording failure stops admission', retentionTermsGate: 'internal', liveTransport: false, durableTruth: 'sealed recording segments + PostgreSQL experiment store (migration 9)', pointInTimeContract: 'receipt clocks per row; the replay clock is the recorded receipt; no future outcome is ever an input', replay: 'deterministic: same bytes + same clocks -> same digests, epochs, receipt sequences', decisionAuthority: NONE, paperAuthority: NONE, paperDesiredState: 'ON', blockerPolicy: 'DEGRADE', readinessBlocker: null, smokeEvidence: SMOKE_FACTS.REPLAY }));
  // ---- requested scope that the repository does NOT implement (accounted for, never silently called complete) -----------------------
  // Publishers: doctrine/RUMOR2.md ("No Reuters/Bloomberg/CNBC/FT/CoinDesk/any publisher"; RUMOR-2 IS FROZEN) and test/rumor2-authority.test.js
  // (the frozen core may not even name these sources) make a publisher ear a rule conflict for the evidence tier, not a missing file.
  // Route facts are dated read-only documentation / feed probes from the development container (docs/evidence/sensor-scope-2026-09-12.md).
  const FROZEN = 'NOT_IMPLEMENTED: doctrine/RUMOR2.md forbids publisher ears in the frozen evidence core (test/rumor2-authority.test.js bans the token)';
  for (const [id, family, blocker, note] of [
    ['REUTERS_NEWS', 'PUBLISHER', `${FROZEN}; NO_ELIGIBLE_DOCUMENTED_ROUTE (licensed distribution only)`, '2026-09-12: reuters.com/tools/rss HTTP 401; reutersagency.com products page HTTP 404; no public feed documented — licensed distribution (Reuters Connect) only'],
    ['BLOOMBERG_NEWS', 'PUBLISHER', `${FROZEN}; NO_ELIGIBLE_DOCUMENTED_ROUTE (licensed distribution only)`, '2026-09-12: bloomberg.com/feeds and /professional/products/data HTTP 403 anti-bot; no public feed documented — Terminal / B-PIPE / Enterprise licensing only'],
    ['CNBC_NEWS', 'PUBLISHER', `${FROZEN}; DOC_UNVERIFIED_FROM_THIS_ENVIRONMENT (cnbc.com/rss-feeds HTTP 403)`, '2026-09-12: cnbc.com/rss-feeds HTTP 403 and the top-news RSS HTTP 403 from this environment; the documented route could not be read here'],
    ['FT_NEWS', 'PUBLISHER', `${FROZEN}; TERMS_UNVERIFIED (headline feed reachable; article bodies paywalled)`, '2026-09-12: ft.com/rss/home -> 200 text/xml (redirects to rss/home/international, 1 item); ft.com/rss documentation page redirect loop; headlines / links only'],
    ['COINDESK_NEWS', 'PUBLISHER', `${FROZEN}; TERMS_UNVERIFIED (public RSS reachable)`, '2026-09-12: coindesk.com/arc/outboundfeeds/rss/ -> 200 application/xml, 25 items; the /rss documentation page answered HTTP 429 (security checkpoint) here'],
    ['THEBLOCK_NEWS', 'PUBLISHER', `${FROZEN}; TERMS_UNVERIFIED (public RSS reachable)`, '2026-09-12: theblock.co/rss.xml -> 200 text/xml, 20 items'],
    ['COINTELEGRAPH_NEWS', 'PUBLISHER', `${FROZEN}; TERMS_UNVERIFIED (public RSS reachable)`, '2026-09-12: cointelegraph.com/rss -> 200 application/xml, 30 items'],
    ['DECRYPT_NEWS', 'PUBLISHER', `${FROZEN}; TERMS_UNVERIFIED (public RSS reachable)`, '2026-09-12: decrypt.co/feed -> 200 application/xml, 55 items'],
    ['GOOGLE_NEWS_AGGREGATOR', 'AGGREGATOR', `${FROZEN}; AGGREGATOR_NOT_PUBLISHER_LICENSE; TERMS_UNVERIFIED (no documented consumer API for the RSS route)`, '2026-09-12: news.google.com/rss/search?q=bitcoin -> 200 application/xml (aggregated headlines; publisher identity is per item, transport is Google); the Publisher Center documentation covers publisher onboarding, not a consumer feed contract'],
  ]) rows.push(row({ id, group: 'PUBLISHER_NEWS', family, classification: 'NOT_PRESENT', module: null, compositionPath: 'not composed', enable: 'none', credentialEnv: [], paid: false, budgetGovernor: 'none', retentionTermsGate: 'publisher terms unverified', liveTransport: false, durableTruth: 'none', pointInTimeContract: 'none', replay: 'none', decisionAuthority: NONE, paperAuthority: NONE, paperDesiredState: 'OFF', blockerPolicy: 'DEGRADE', readinessBlocker: blocker, smokeEvidence: note }));
  for (const [id, family, credentialEnv, blocker, note] of [
    ['CLOUDFLARE_RADAR', 'INTERNET_RADAR', ['CLOUDFLARE_API_TOKEN'], 'NOT_IMPLEMENTED; CREDENTIAL_REQUIRED (API token; an unauthenticated request answers HTTP 400 code 9106); NO_CONSUMER_TIER (no reader for internet-radar observations exists)', '2026-09-12: developers.cloudflare.com/radar/get-started/first-request (200) documents an API token; api.cloudflare.com/client/v4/radar/bgp/timeseries without a token -> HTTP 400 {"code":9106,"message":"Missing X-Auth-Key, X-Auth-Email or Authorization headers"}'],
    ['NOAA_SWPC_SPACE_WEATHER', 'SPACE_WEATHER', [], 'NOT_IMPLEMENTED; NO_CONSUMER_TIER (experimental observation family; owner placement decision before code)', '2026-09-12: swpc.noaa.gov/content/data-access (200); services.swpc.noaa.gov/products/noaa-planetary-k-index.json -> 200 rows {time_tag, Kp, a_running, station_count}; noaa-scales.json -> 200 R / S / G scales with DateStamp + TimeStamp; no key'],
    ['RIPE_RIS_BGP', 'ROUTING', [], 'NOT_IMPLEMENTED; CONFIG_REQUIRED (monitored prefixes / ASNs are not configured); NO_CONSUMER_TIER', '2026-09-12: stat.ripe.net/docs/data-api (200); stat.ripe.net/data/routing-status/data.json?resource=1.1.1.0/24 -> 200 status ok (data_call_status supported); ris-live.ripe.net (200) documents the RIS Live WebSocket; no key'],
  ]) rows.push(row({ id, group: 'INFRASTRUCTURE', family, classification: 'NOT_PRESENT', module: null, compositionPath: 'not composed', enable: 'none', credentialEnv, paid: false, budgetGovernor: 'none', retentionTermsGate: 'public data (route documented)', liveTransport: false, durableTruth: 'none', pointInTimeContract: 'none', replay: 'none', decisionAuthority: NONE, paperAuthority: NONE, paperDesiredState: 'OFF', blockerPolicy: 'DEGRADE', readinessBlocker: blocker, smokeEvidence: note }));
  rows.push(row({ id: 'YOUTUBE_DATA_API', group: 'SOCIAL', family: 'SOCIAL_VIDEO', classification: 'NOT_PRESENT', module: null, compositionPath: 'not composed', enable: 'none', credentialEnv: ['YOUTUBE_API_KEY'], paid: false, budgetGovernor: 'none (documented default quota 10,000 units / day; search.list costs 100 units)', retentionTermsGate: 'YouTube API Services Terms review unresolved', liveTransport: false, durableTruth: 'none', pointInTimeContract: 'none', replay: 'none', decisionAuthority: NONE, paperAuthority: NONE, paperDesiredState: 'OFF', blockerPolicy: 'DEGRADE', readinessBlocker: 'NOT_IMPLEMENTED; CREDENTIAL_REQUIRED (API key); TERMS_REVIEW; CONFIG_REQUIRED (query scope); metadata / titles only — never transcripts or video analysis', smokeEvidence: '2026-09-12: developers.google.com/youtube/v3/docs/search/list (200) and getting-started (200): API key, default quota 10,000 units per day; no repository reference to YouTube existed before this row' }));
  // ---- doctrine-required senses NOT PRESENT (stated, never silently called complete) ------------------------------------------------
  for (const [id, note] of [['META_REALTIME_TRANSPORT', 'doctrine/SOCIAL.md lists Meta only as descriptors / fixture previews; no live Graph API transport exists (app review unresolved)'], ['TIKTOK_REALTIME_TRANSPORT', 'doctrine/SOCIAL.md: no authorized organic route; fixture-only foundation (rumor2/social-tiktok.js)'], ['FARCASTER_LIVE_TRANSPORT', 'doctrine/SOCIAL.md: access boundary + mapper only (NEYNAR_API_KEY); no live hub / webhook runtime composed (rumor2/social-farcaster-access.js declares liveTransport false)']]) rows.push(row({ id, group: 'SOCIAL', family: 'SOCIAL', classification: 'NOT_PRESENT', module: null, compositionPath: 'not composed', enable: 'none', credentialEnv: [], paid: false, budgetGovernor: 'none', retentionTermsGate: 'unresolved', liveTransport: false, durableTruth: 'none', pointInTimeContract: 'none', replay: 'none', decisionAuthority: NONE, paperAuthority: NONE, paperDesiredState: 'OFF', blockerPolicy: 'DEGRADE', readinessBlocker: 'EXTERNAL_ACCESS_BLOCKED', smokeEvidence: note }));
  const secrets = secretPresence(profile, env); const counts = Object.fromEntries(CLASSIFICATIONS.map((c) => [c, rows.filter((r) => r.classification === c).length]));
  return Object.freeze({ inventoryVersion: INVENTORY_VERSION, generatedTs: clock(), profile: profile.profileName, policyFile: profile.files.marketResearchPolicy, classifications: [...CLASSIFICATIONS], counts, rows, secretNamesPresent: Object.entries(secrets).filter(([, v]) => v).map(([k]) => k), law: 'derived from the registries at generation time; classification never implies edge or authority; secret VALUES never appear here' });
}
export const inventoryRow = (inv, id) => inv.rows.find((r) => r.id === id) ?? null;
