// SERPENT PAPER — the ONE sensor / readiness snapshot schema shared by the preflight CLI and the cockpit (/api/sensors).
// Every row says what a sense IS DOING NOW from durable status files (and, when running in-process, the live handles):
// name, state, last successful observation / settle clock, age, coverage state, blocker / reason, authority. It never colours
// a feed ACTIVE because its module exists: without a fresh status record the state is NOT_OBSERVED with the reason. No secret
// value, header, bearer fragment or credential material is ever read into this snapshot — only NAMES and presence booleans.
import { existsSync, readFileSync } from 'node:fs';
import path from 'node:path';
import { loadConfig, dataDir as dataDirOf } from '../lib/config.js';
import { readExecutionProjection } from '../state/execution-projection.js';
import { readControls } from '../state/controls.js';
import { dailyLockStatus } from '../state/locks.js';
import { marketResearchRootFromEnv, darkResearchRootOf } from '../market-lab/paths.js';
import { paidCallAuthorized } from '../market-lab/policy.js';
import { loadProfile, profileFileOf, RUNTIME_STATES, mergeOverlay } from './profile.js';
import { PRESS_SOURCES } from '../press/registry.js';
import { INFRA_SOURCES } from '../infra/registry.js';
import { loadRegistry, VERIFIED_MAPPINGS } from '../governance/registry.js';
import { tallyStatus } from '../governance/tally.js';
import { readJsonBounded as boundedJsonFile } from '../lib/jsonl.js';

export const SNAPSHOT_VERSION = 'serpent-sensor-snapshot-1';
export const SNAPSHOT_GROUPS = Object.freeze(['MARKET', 'OFFICIAL', 'SOCIAL', 'INFRASTRUCTURE', 'DARK_RESEARCH', 'SOCRATES', 'JUDGE', 'WATCH', 'PUBLISHER_NEWS']);
export const EXTRA_STATES = Object.freeze(['NOT_OBSERVED', 'DARK_CAPTURE_OPERATIONAL', 'DARK_CAPTURE_BLOCKED_EXTERNAL', 'DARK_CAPTURE_DEGRADED', 'DARK_CAPTURE_DISABLED_BY_POLICY', 'BLOCKED_NO_SAFE_L3_DATA_KEY', 'KEY_PRESENT_UNPROVEN']);
export const ROW_KEYS = Object.freeze(['id', 'name', 'group', 'state', 'desiredState', 'lastSuccessTs', 'ageMs', 'coverage', 'blocker', 'detail', 'authority']);
export const FRESH_MS = Object.freeze({ tape: 30_000, survey: 15 * 60_000, rumint: 60 * 60_000, gateway: 10 * 60_000, rumor2: 5 * 60_000, research: 5 * 60_000, judge: 15_000, dark: 30 * 60_000, press: 30 * 60_000, infraCadences: 3, video: 3 * 60 * 60_000 });
const MAX_JSON = 2 * 1024 * 1024;
export const readJsonBounded = (file) => { try { if (!existsSync(file)) return null; return boundedJsonFile(file, MAX_JSON); } catch { return null; } };
const present = (env, names) => (Array.isArray(names) ? names : [names]).filter(Boolean).every((n) => typeof env[n] === 'string' && env[n].length > 0);
const isState = (s) => RUNTIME_STATES.includes(s) || EXTRA_STATES.includes(s) || /^CONFIG_REQUIRED:[A-Z0-9_]+$/.test(s);
const R = (o) => { const r = {}; for (const k of ROW_KEYS) r[k] = o[k] === undefined ? null : o[k]; if (!isState(r.state)) throw new Error(`sensor row ${r.id}: state ${r.state}`); if (!SNAPSHOT_GROUPS.includes(r.group)) throw new Error(`sensor row ${r.id}: group`); return r; };
const age = (ts, now) => (Number.isSafeInteger(ts) ? Math.max(0, now - ts) : null);
const tsOf = (v) => { if (Number.isSafeInteger(v)) return v; if (typeof v === 'string') { const ms = Date.parse(v); return Number.isFinite(ms) ? ms : null; } return null; };
const freshOr = (ts, now, maxMs, active, stale = 'ACTIVE_DEGRADED') => (ts === null ? 'NOT_OBSERVED' : now - ts <= maxMs ? active : stale);
// A saved ACTIVE label is not proof that a stream is still delivering data.
// Require both an observation clock and a recent collector status publication.
const socialObservationState = (runtime, observationTs, statusTs, now) => {
  if ([observationTs, statusTs].some(ts => !Number.isSafeInteger(ts) || ts < 0 || ts > now)) return 'NOT_OBSERVED';
  if (now - observationTs > FRESH_MS.rumor2 || now - statusTs > FRESH_MS.rumor2 || runtime?.stream?.connected === false) return 'ACTIVE_DEGRADED';
  return 'ACTIVE';
};
const noSecrets = (s) => !/sk-ant|Bearer [A-Za-z0-9]|eyJ[A-Za-z0-9_-]{10,}|postgres(ql)?:\/\/[^\s"]+:[^\s"]+@|API-Key|API-Sign|x-api-key/i.test(s);

// the X governor law shared by the snapshot and the preflight (env NAMES only; never the runtime module): credential, then the
// three explicit budgets, then ACTIVE only from a live status record, else the explicit paid smoke is still owed
export const xGovernorState = (env, x = null) => !present(env, 'X_BEARER_TOKEN') ? 'CREDENTIAL_MISSING' : !present(env, ['RUMOR2_SOCIAL_X_MAX_DAILY_POST_READS', 'RUMOR2_SOCIAL_X_MAX_MONTHLY_POST_READS', 'RUMOR2_SOCIAL_X_MAX_ESTIMATED_DAILY_USD']) ? 'BUDGET_NOT_CONFIGURED' : x?.state === 'ACTIVE' ? 'ACTIVE' : 'READY_REQUIRES_EXPLICIT_PAID_SMOKE';
export function sensorSnapshot({ profile = loadProfile(), env = process.env, config = mergeOverlay(loadConfig(), profile.configOverlay), dataDir = dataDirOf(config), now = Date.now(), live = {}, darkStatus = null } = {}) {
  const g = profile.groups; const rows = []; const desired = (grp, id) => g[grp]?.[id]?.desiredState ?? 'OFF';
  const disabled = (grp, id) => desired(grp, id) === 'OFF';
  // ---- MARKET (core public observation) -------------------------------------------------------------------------------------
  const tape = readJsonBounded(path.join(dataDir, 'tape', 'status.json')); const tapeTs = tsOf(tape?.tsMs ?? tape?.ts);
  const coins = tape?.coins ? Object.values(tape.coins) : []; const synced = coins.filter((c) => c?.synced).length;
  rows.push(R({ id: 'TAPE', name: 'Kraken tape (public WS v2)', group: 'MARKET', state: tape === null ? 'NOT_OBSERVED' : tape.state === 'LIVE' && now - tapeTs <= FRESH_MS.tape ? 'ACTIVE' : tape.state === 'OFFLINE' ? 'BLOCKED_PROVIDER' : 'ACTIVE_DEGRADED', desiredState: desired('coreObservation', 'tape'), lastSuccessTs: tapeTs, ageMs: age(tapeTs, now), coverage: tape ? `${tape.state}; ${synced}/${coins.length} books synced` : 'NO_STATUS_FILE', blocker: tape === null ? 'no tape status yet (not started or never wrote)' : tape.state !== 'LIVE' ? `tape ${tape.state}` : now - tapeTs > FRESH_MS.tape ? 'status stale' : null, detail: tape?.universe ? `universe ${tape.universe.date ?? '—'}` : null, authority: 'FEED_ONLY' }));
  const survey = readJsonBounded(path.join(dataDir, 'survey', 'status.json')); const surveyTs = tsOf(survey?.tsMs ?? survey?.ts);
  rows.push(R({ id: 'WIDEEYE', name: 'Wide eye (full-universe survey)', group: 'MARKET', state: disabled('coreObservation', 'wideEye') || config.wideeye?.enabled === false ? 'DISABLED_BY_PAPER_POLICY' : freshOr(surveyTs, now, FRESH_MS.survey, 'ACTIVE'), desiredState: desired('coreObservation', 'wideEye'), lastSuccessTs: surveyTs, ageMs: age(surveyTs, now), coverage: survey ? `scanned ${survey.scanned ?? '—'}; catalog ${survey.catalog?.status ?? '—'}` : 'NO_STATUS_FILE', blocker: survey === null ? 'no survey status yet' : survey.catalog && survey.catalog.status !== 'ACCEPTED' ? `catalog ${survey.catalog.status}` : null, detail: survey?.catalog ? `catalog age ${survey.catalog.ageSec ?? '—'} s` : null, authority: 'NONE' }));
  const universe = readJsonBounded(path.join(dataDir, 'universe', 'current.json')); const uniTs = tsOf(universe?.selectedAt);
  rows.push(R({ id: 'UNIVERSE_EXPANSION', name: 'Deep observation set (universe expansion)', group: 'MARKET', state: config.universeExpansion?.enabled === false ? 'DISABLED_BY_PAPER_POLICY' : universe ? 'ACTIVE' : 'NOT_OBSERVED', desiredState: desired('coreObservation', 'universeExpansion'), lastSuccessTs: uniTs, ageMs: age(uniTs, now), coverage: universe ? `${(universe.pairs ?? []).length} pairs (${universe.date ?? '—'})` : 'NO_UNIVERSE_FILE', blocker: universe ? null : 'no universe selection yet', detail: universe?.source ?? null, authority: 'NONE' }));
  const rumint = readJsonBounded(path.join(dataDir, 'rumint', 'status.json')); const rumintTs = tsOf(rumint?.lastSuccessTs ?? rumint?.tsMs);
  rows.push(R({ id: 'RUMINT_STOCKTWITS_AGGREGATE', name: 'RUMINT legacy aggregate ear (StockTwits)', group: 'OFFICIAL', state: config.rumint?.enabled === false || disabled('rumorOfficial', 'rumintLegacy') ? 'DISABLED_BY_PAPER_POLICY' : rumint === null ? 'NOT_OBSERVED' : rumint.globalBackoffUntil ? 'ACTIVE_DEGRADED' : freshOr(rumintTs, now, FRESH_MS.rumint, 'ACTIVE'), desiredState: desired('rumorOfficial', 'rumintLegacy'), lastSuccessTs: rumintTs, ageMs: age(rumintTs, now), coverage: rumint ? `${rumint.symbolsReady ?? 0} ready / ${rumint.symbolsTracked ?? 0} tracked; ${rumint.status ?? '—'}` : 'NO_STATUS_FILE', blocker: rumint?.globalBackoffUntil ? 'provider backoff' : rumint === null ? 'no status yet' : null, detail: rumint?.initDetail ?? null, authority: 'NOMINATE_WARN_ONLY' }));
  // ---- INFRASTRUCTURE (gateway) ------------------------------------------------------------------------------------------------
  const matrix = readJsonBounded(path.join(dataDir, 'gateway', 'matrix.json')); const gwTs = tsOf(matrix?.ts); const gwOn = config.gateway?.enabled === true && (env.GATEWAY_ENABLED === undefined || env.GATEWAY_ENABLED === 'true');
  for (const [src, name] of [['kraken', 'Kraken status page'], ['krakenSystem', 'Kraken system status'], ['coinbase', 'Coinbase status page'], ['okx', 'OKX system status']]) {
    const on = gwOn && config.gateway?.sources?.[src] !== false;
    rows.push(R({ id: `GATEWAY_${src.toUpperCase()}`, name: `Gateway: ${name}`, group: 'INFRASTRUCTURE', state: !on ? 'DISABLED_BY_PAPER_POLICY' : freshOr(gwTs, now, FRESH_MS.gateway, 'ACTIVE'), desiredState: on ? 'ON' : 'OFF', lastSuccessTs: on ? gwTs : null, ageMs: on ? age(gwTs, now) : null, coverage: matrix ? `door matrix ${Object.keys(matrix.doors ?? {}).length} coins` : 'NO_MATRIX_FILE', blocker: !on ? 'gateway or source disabled' : matrix === null ? 'no gateway matrix yet' : null, detail: 'public read-only; never trading permission', authority: 'NONE' }));
  }
  // ---- INFRASTRUCTURE observation tier (infra/: NOAA / RIPE RIS / Cloudflare Radar) — from the collector's status file only ------
  const infra = readJsonBounded(path.join(dataDir, 'infra', 'status.json')); const infraOn = env.INFRA_OBS_ENABLED === 'true'; const infraSel = new Set(String(env.INFRA_SOURCES ?? '').split(',').map((x) => x.trim()).filter(Boolean));
  for (const src of INFRA_SOURCES) {
    const pr = g.infrastructure?.[src.id] ?? null; const desiredHere = pr?.desiredState ?? 'OFF'; const st = infra?.sources?.[src.id] ?? null; const okTs = tsOf(st?.lastSuccessTs); const freshMs = src.cadenceSec * 1000 * FRESH_MS.infraCadences;
    const gate = src.credentialEnv && !present(env, src.credentialEnv) ? 'BLOCKED_CREDENTIAL' : src.configEnv && !present(env, src.configEnv) ? `CONFIG_REQUIRED:${src.configEnv}` : src.id==='CLOUDFLARE_RADAR'&&!present(env,'INFRA_CLOUDFLARE_ASN')&&!present(env,'INFRA_CLOUDFLARE_PREFIX')&&env.INFRA_CLOUDFLARE_GLOBAL!=='true' ? 'CONFIG_REQUIRED:RADAR_SCOPE' : st?.state==='CONFIG_REQUIRED' ? 'CONFIG_REQUIRED:INFRA_SCOPE' : null;
    const state = desiredHere === 'OFF' || !infraOn || !infraSel.has(src.id) ? 'DISABLED_BY_PAPER_POLICY' : gate ? gate : infra === null || st === null ? 'NOT_OBSERVED' : st.state === 'IDLE' ? 'NOT_OBSERVED' : ['OBSERVED', 'EMPTY'].includes(st.state) ? freshOr(okTs, now, freshMs, 'ACTIVE') : okTs !== null && now - okTs <= freshMs ? 'ACTIVE_DEGRADED' : 'BLOCKED_PROVIDER';
    rows.push(R({ id: `INFRA_${src.id}`, name: `Infrastructure observation: ${src.name}${src.experimental ? ' (EXPERIMENTAL)' : ''}`, group: 'INFRASTRUCTURE', state, desiredState: desiredHere, lastSuccessTs: okTs, ageMs: age(okTs, now), coverage: st ? `${st.state}; ${st.coverage ?? '—'}; admitted ${st.counters?.admitted ?? 0} / requests ${st.counters?.requests ?? 0}` : infra ? 'NOT_IN_STATUS' : 'NO_STATUS_FILE', blocker: state === 'DISABLED_BY_PAPER_POLICY' ? (pr?.reason ?? (!infraOn ? 'INFRA_OBS_ENABLED not true' : 'not selected in INFRA_SOURCES')) : gate ? (src.credentialEnv && gate === 'BLOCKED_CREDENTIAL' ? `${src.credentialEnv} missing` : `${src.configEnv ?? 'RADAR_SCOPE'} requires a valid monitored scope`) : st && !['OBSERVED', 'EMPTY', 'IDLE'].includes(st.state) ? String(st.lastError ?? st.state).slice(0, 160) : null, detail: `${src.kind}; cadence ${src.cadenceSec}s; measurement recorded only from a parsed payload (a connected socket is never a value); experimental ${src.experimental ? 'yes' : 'no'}`, authority: 'NONE' }));
  }
  // ---- OFFICIAL (RUMOR2 ears) ---------------------------------------------------------------------------------------------------
  const r2 = readJsonBounded(path.join(dataDir, 'rumor2', 'status.json')); const r2Ts = tsOf(r2?.tsMs); const r2On = env.RUMOR2_ENABLED === 'true';
  const provs = Array.isArray(r2?.providers) ? r2.providers : []; const contact = present(env, 'SERPENT_HTTP_CONTACT');
  for (const [id, name, gate] of [['KRAKEN_OFFICIAL', 'Kraken official blog feed', null], ['SEC_OFFICIAL', 'SEC press releases', contact ? null : 'CONFIG_REQUIRED:SERPENT_HTTP_CONTACT'], ['CFTC_OFFICIAL', 'CFTC releases', null], ['EDGAR_OFFICIAL', 'SEC EDGAR submissions', env.RUMOR2_EDGAR_ENABLED !== 'true' ? 'DISABLED_BY_PAPER_POLICY' : !present(env, 'RUMOR2_EDGAR_CIKS') ? 'CONFIG_REQUIRED:EDGAR_WHITELIST' : !contact ? 'CONFIG_REQUIRED:SERPENT_HTTP_CONTACT' : null], ['OFAC_OFFICIAL', 'OFAC SDN list', env.RUMOR2_OFAC_ENABLED !== 'true' ? 'DISABLED_BY_PAPER_POLICY' : null]]) {
    const p = provs.find((x) => x?.provider === id) ?? null; const lastOk = p?.state === 'OBSERVED' ? tsOf(p.checkedTs) : null; const desiredHere = desired('rumorOfficial', id);
    const state = !r2On || desiredHere === 'OFF' ? 'DISABLED_BY_PAPER_POLICY' : gate ? gate : p === null ? 'NOT_OBSERVED' : p.state === 'OBSERVED' ? (now - lastOk <= FRESH_MS.rumor2 * 12 ? 'ACTIVE' : 'ACTIVE_DEGRADED') : p.state === 'NOT_QUERIED' ? 'ACTIVE_DEGRADED' : 'BLOCKED_PROVIDER';
    rows.push(R({ id, name, group: 'OFFICIAL', state, desiredState: desiredHere, lastSuccessTs: lastOk, ageMs: age(lastOk, now), coverage: p ? `${p.state}${r2?.lifecycle ? `; collector ${r2.lifecycle}` : ''}` : r2 ? 'NOT_IN_STATUS' : 'NO_STATUS_FILE', blocker: gate ?? (p && p.state !== 'OBSERVED' ? String(p.detail ?? p.state).slice(0, 160) : p === null && r2On ? 'no RUMOR2 status yet' : null), detail: r2 ? `durability ${r2.durabilityMode ?? '—'}; writer ${r2.writerAuthority?.state ?? r2.writerAuthority ?? '—'}` : null, authority: 'EVIDENCE_ONLY' }));
  }
  // ---- SOCIAL -----------------------------------------------------------------------------------------------------------------
  const social = r2?.social ?? null; const socialTs = tsOf(social?.stream?.lastEventTs ?? social?.lastSettleTs ?? social?.lastEventTs ?? null);
  const socialState = env.RUMOR2_SOCIAL_BLUESKY_ENABLED !== 'true' || disabled('social', 'BLUESKY_OFFICIAL') ? 'DISABLED_BY_PAPER_POLICY' : social === null ? 'NOT_OBSERVED' : social.state === 'ACTIVE' ? socialObservationState(social, socialTs, r2Ts, now) : social.state === 'WITHHELD' || social.state === 'STANDBY' ? 'ACTIVE_DEGRADED' : social.state === 'DARK' && social.enabled ? 'ACTIVE_DEGRADED' : 'NOT_OBSERVED';
  rows.push(R({ id: 'BLUESKY_OFFICIAL', name: 'Bluesky official Jetstream', group: 'SOCIAL', state: socialState, desiredState: desired('social', 'BLUESKY_OFFICIAL'), lastSuccessTs: socialTs, ageMs: age(socialTs, now), coverage: social ? `${social.state ?? '—'}; scope ${social.scope?.coverage?.state ?? social.scope?.mode ?? '—'}` : 'NO_STATUS', blocker: socialState === 'ACTIVE' ? null : social?.state === 'ACTIVE' ? 'fresh observation and collector status required; stream may be stale or disconnected' : social ? String(social.gateDetail ?? social.withholdReason ?? social.state).slice(0, 160) : 'no social status yet', detail: 'free public firehose; settle / writer-fence law', authority: 'NONE' }));
  const x = r2?.socialX ?? null; const xBearer = present(env, 'X_BEARER_TOKEN'); const xBudget = present(env, ['RUMOR2_SOCIAL_X_MAX_DAILY_POST_READS', 'RUMOR2_SOCIAL_X_MAX_MONTHLY_POST_READS', 'RUMOR2_SOCIAL_X_MAX_ESTIMATED_DAILY_USD']);
  const xGov = xGovernorState(env, x); void xBearer; void xBudget;
  const xTs = tsOf(x?.stream?.lastPostTs ?? x?.lastEventTs ?? null);
  const xState = desired('social', 'X_OFFICIAL') === 'OFF' ? 'DISABLED_BY_PAPER_POLICY' : xGov === 'CREDENTIAL_MISSING' ? 'BLOCKED_CREDENTIAL' : xGov === 'BUDGET_NOT_CONFIGURED' ? 'BLOCKED_BUDGET' : xGov === 'ACTIVE' ? socialObservationState(x, xTs, r2Ts, now) : 'BLOCKED_EXTERNAL_APPROVAL';
  rows.push(R({ id: 'X_OFFICIAL', name: 'X official filtered stream (PAID)', group: 'SOCIAL', state: xState, desiredState: desired('social', 'X_OFFICIAL'), lastSuccessTs: xTs, ageMs: age(xTs, now), coverage: x ? `${x.state ?? '—'}` : 'NOT_OPERATIONAL', blocker: xState === 'ACTIVE' ? null : xGov === 'ACTIVE' ? 'fresh post observation and collector status required; stream may be stale or disconnected' : xGov, detail: 'credential + explicit budgets + explicit paid smoke required; fresh post delivery and collector status prove activity', authority: 'NONE' }));
  const youtube = r2?.socialYouTube ?? null;
  const youtubeBudget = present(env, ['RUMOR2_SOCIAL_YOUTUBE_MAX_DAILY_QUOTA_UNITS', 'RUMOR2_SOCIAL_YOUTUBE_MAX_MONTHLY_QUOTA_UNITS']);
  const youtubeEnabled = env.RUMOR2_SOCIAL_YOUTUBE_ENABLED === 'true' && desired('social', 'YOUTUBE_OFFICIAL') !== 'OFF';
  const youtubeGate = !youtubeEnabled ? 'DISABLED_BY_PAPER_POLICY' : !present(env, 'YOUTUBE_API_KEY') ? 'CREDENTIAL_MISSING' : !youtubeBudget ? 'BUDGET_NOT_CONFIGURED' : youtube?.watchlist?.ok === false || !youtube?.watchlist ? 'WATCH_SCOPE_NOT_CONFIGURED' : 'CODE_COMPLETE_NO_COLLECTOR';
  const youtubeTs = tsOf(youtube?.lastEventTs ?? youtube?.lastReceiptTs ?? null);
  rows.push(R({ id: 'YOUTUBE_OFFICIAL', name: 'YouTube official search.list (read-only)', group: 'SOCIAL', state: youtubeGate === 'DISABLED_BY_PAPER_POLICY' ? 'DISABLED_BY_PAPER_POLICY' : youtubeGate === 'CREDENTIAL_MISSING' ? 'BLOCKED_CREDENTIAL' : youtubeGate === 'BUDGET_NOT_CONFIGURED' ? 'BLOCKED_BUDGET' : youtubeGate === 'WATCH_SCOPE_NOT_CONFIGURED' ? 'BLOCKED_EXTERNAL_APPROVAL' : 'NOT_OBSERVED', desiredState: desired('social', 'YOUTUBE_OFFICIAL'), lastSuccessTs: null, ageMs: null, coverage: youtube ? `${youtube.state ?? '—'}; no receipt asserted` : 'CODE_COMPLETE_NO_RECEIPT', blocker: youtubeGate === 'CODE_COMPLETE_NO_COLLECTOR' ? 'no collector/runtime composed; no receipt claimed' : youtubeGate, detail: 'search.list only; 100 quota units/request; explicit daily/monthly quota-unit caps and existing bounded social scope required before dispatch', authority: 'NONE' }));
  // SOCIAL VIDEO (video/: YouTube public metadata) — a separate observation tier; ACTIVE only from a fresh collector status record
  const vs = readJsonBounded(path.join(dataDir, 'video', 'status.json')); const vOn = env.SOCIAL_VIDEO_ENABLED === 'true'; const vOkTs = tsOf(vs?.lastSuccessTs); const vDesired = desired('social', 'YOUTUBE_DATA_API');
  const vGate = !present(env, 'YOUTUBE_API_KEY') ? 'BLOCKED_CREDENTIAL' : !present(env, 'SOCIAL_VIDEO_YOUTUBE_QUERIES') ? 'CONFIG_REQUIRED:SOCIAL_VIDEO_YOUTUBE_QUERIES' : !present(env, 'SOCIAL_VIDEO_YOUTUBE_MAX_DAILY_SEARCHES') ? 'BLOCKED_BUDGET' : null;
  const vState = vDesired === 'OFF' || !vOn ? 'DISABLED_BY_PAPER_POLICY' : vGate ? vGate : vs === null || vs.state === 'IDLE' ? 'NOT_OBSERVED' : ['CREDENTIAL_MISSING', 'CONFIG_REQUIRED', 'BUDGET_NOT_CONFIGURED', 'BUDGET_INVALID'].includes(vs.state) ? (vs.state === 'CREDENTIAL_MISSING' ? 'BLOCKED_CREDENTIAL' : vs.state === 'CONFIG_REQUIRED' ? 'CONFIG_REQUIRED:SOCIAL_VIDEO_YOUTUBE_QUERIES' : 'BLOCKED_BUDGET') : vs.state === 'CREDENTIAL_REFUSED' ? 'BLOCKED_CREDENTIAL' : vs.state === 'BUDGET_STOPPED' || vs.state === 'QUOTA_EXCEEDED' ? 'BLOCKED_BUDGET' : ['OBSERVED', 'EMPTY'].includes(vs.state) ? freshOr(vOkTs, now, FRESH_MS.video, 'ACTIVE') : vOkTs !== null && now - vOkTs <= FRESH_MS.video ? 'ACTIVE_DEGRADED' : 'BLOCKED_PROVIDER';
  rows.push(R({ id: 'YOUTUBE_DATA_API', name: 'YouTube public video metadata (Data API v3)', group: 'SOCIAL', state: vState, desiredState: vDesired, lastSuccessTs: vOkTs, ageMs: age(vOkTs, now), coverage: vs ? `${vs.state}; METADATA_ONLY; searches ${vs.quota?.searchCalls ?? 0} / ${vs.quota?.maxDailySearches ?? '—'} (${vs.quota?.accountingDay ?? '—'}); admitted ${vs.counters?.admitted ?? 0}` : 'NO_STATUS_FILE', blocker: vState === 'DISABLED_BY_PAPER_POLICY' ? (vDesired === 'OFF' ? (g.social.YOUTUBE_DATA_API?.reason ?? 'OFF') : 'SOCIAL_VIDEO_ENABLED not true') : vGate === 'BLOCKED_CREDENTIAL' ? 'YOUTUBE_API_KEY missing' : vGate === 'BLOCKED_BUDGET' ? 'SOCIAL_VIDEO_YOUTUBE_MAX_DAILY_SEARCHES not set (no default budget is ever read)' : vGate ? 'SOCIAL_VIDEO_YOUTUBE_QUERIES names no query' : vs && !['OBSERVED', 'EMPTY', 'IDLE'].includes(vs.state) ? String(vs.lastError ?? vs.state).slice(0, 160) : null, detail: 'separate social-video tier (video/); metadata only, never captions / transcripts; not a RUMOR-2 social provider (sealed registry); key sent only as a request header', authority: 'NONE' }));
  const fc = r2?.socialFarcaster;
  const fcTs = tsOf(fc?.lastSuccessTs); const fcGate = fc ? fc.gateReason ?? null : (!present(env,'NEYNAR_API_KEY') ? 'CREDENTIAL_MISSING' : 'CONFIG_OR_ACCESS_REVIEW_REQUIRED');
  rows.push(R({ id: 'FARCASTER_OFFICIAL', name: 'Farcaster / Neynar cast search', group: 'SOCIAL', desiredState: desired('social','FARCASTER_OFFICIAL'), state: disabled('social','FARCASTER_OFFICIAL') ? 'DISABLED_BY_PAPER_POLICY' : fc && fc.state!=='ACTIVE' ? 'BLOCKED_PROVIDER' : fcTs !== null && !fcGate ? freshOr(fcTs,now,600000,fc.lastError?'ACTIVE_DEGRADED':'ACTIVE') : fcGate === 'CREDENTIAL_MISSING' || fcGate === 'KEY_MISSING' ? 'BLOCKED_CREDENTIAL' : 'BLOCKED_EXTERNAL_APPROVAL', lastSuccessTs: fcTs, ageMs: age(fcTs,now), coverage: fc?.coverage ?? 'NOT_OBSERVED', blocker: fcGate, detail: 'Documented REST search; source-only social journal and research projection; explicit scoped access and request budget', authority: 'NONE' }));
  for (const [id,name,profileId,key] of [['REDDIT_OFFICIAL','Reddit current posts','REDDIT_OFFICIAL','REDDIT_CLIENT_ID'],['STOCKTWITS_OFFICIAL','StockTwits official current messages','STOCKTWITS_OFFICIAL','STOCKTWITS_STREAM_USER'],['META_FACEBOOK','Facebook public Pages','META_PUBLIC','META_APP_TOKEN'],['META_INSTAGRAM','Instagram hashtag media','META_PUBLIC','META_APP_TOKEN']]) {
    const st=r2?.socialCurrent?.sources?.[id], ts=tsOf(st?.lastSuccessTs);
    const state=disabled('social',profileId)?'DISABLED_BY_PAPER_POLICY':!present(env,key)?'BLOCKED_CREDENTIAL':r2?.socialCurrent?.state==='DARK'?'BLOCKED_PROVIDER':/BUDGET/.test(st?.state??'')?'BLOCKED_BUDGET':/CREDENTIAL/.test(st?.state??'')?'BLOCKED_CREDENTIAL':st?.state==='OBSERVED'?freshOr(ts,now,300000,'ACTIVE'):st?.state==='CONNECTED_NO_MATCH'?'NOT_OBSERVED':'BLOCKED_EXTERNAL_APPROVAL';
    rows.push(R({id,name,group:'SOCIAL',desiredState:desired('social',profileId),state,lastSuccessTs:ts,ageMs:age(ts,now),coverage:st?.coverage??'NOT_OBSERVED',blocker:['ACTIVE','NOT_OBSERVED'].includes(state)?null:st?.state??'CONFIG_OR_ACCESS_REVIEW_REQUIRED',detail:'Erasable current observations in owner cockpit; content and identities expire after five minutes; no permanent social archive or model input',authority:'NONE'}));
  }
  // META_PUBLIC is the sealed provider identity used by the preflight and
  // access registry; the route rows above remain useful detail, but the
  // aggregate must always be a real sensor row (never an undefined render).
  const metaFacebook = r2?.socialCurrent?.sources?.META_FACEBOOK ?? null;
  const metaInstagram = r2?.socialCurrent?.sources?.META_INSTAGRAM ?? null;
  const metaObserved = [metaFacebook, metaInstagram].filter((st) => st?.state === 'OBSERVED');
  const metaTs = Math.max(0, ...metaObserved.map((st) => tsOf(st.lastSuccessTs) ?? 0)) || null;
  const metaDesired = desired('social', 'META_PUBLIC');
  const metaState = metaDesired === 'OFF' ? 'DISABLED_BY_PAPER_POLICY'
    : !present(env, 'META_APP_TOKEN') ? 'BLOCKED_CREDENTIAL'
      : r2?.socialCurrent?.state === 'DARK' ? 'BLOCKED_PROVIDER'
        : metaObserved.length ? socialObservationState(null, metaTs, r2Ts, now)
          : metaFacebook || metaInstagram ? 'NOT_OBSERVED' : 'BLOCKED_EXTERNAL_APPROVAL';
  rows.push(R({ id: 'META_PUBLIC', name: 'Meta public Pages / Instagram', group: 'SOCIAL', desiredState: metaDesired, state: metaState, lastSuccessTs: metaTs, ageMs: age(metaTs, now), coverage: [metaFacebook, metaInstagram].filter(Boolean).map((st) => st.state ?? 'NOT_OBSERVED').join('/') || 'NOT_OBSERVED', blocker: metaState === 'ACTIVE' || metaState === 'NOT_OBSERVED' ? null : metaDesired === 'OFF' ? (g.social.META_PUBLIC?.reason ?? 'OFF') : metaState === 'BLOCKED_CREDENTIAL' ? 'META_APP_TOKEN missing' : 'route access / retention approval required', detail: 'Separate route-bound, read-only Meta observations; no scraper or durable social archive', authority: 'NONE' }));
  rows.push(R({id:'TIKTOK_PUBLIC',name:'TikTok',group:'SOCIAL',desiredState:desired('social','TIKTOK_PUBLIC'),state:'BLOCKED_TERMS',lastSuccessTs:null,ageMs:null,coverage:'NO_ELIGIBLE_PUBLIC_INTELLIGENCE_ROUTE',blocker:'Research API institutional eligibility is not established; own-account Display API does not satisfy the requested feed',detail:'No scrape or substituted route',authority:'NONE'}));
   // ---- PUBLISHER NEWS (press/: headline / link observation outside the frozen RUMOR-2 evidence core) -------------------------------
  const press = readJsonBounded(path.join(dataDir, 'press', 'status.json')); const pressOn = env.PRESS_ENABLED === 'true'; const pressSel = new Set(String(env.PRESS_SOURCES ?? '').split(',').map((x) => x.trim()).filter(Boolean));
  for (const src of PRESS_SOURCES) {
    const pr = g.publisherNews?.[src.id] ?? null; const desiredHere = pr?.desiredState ?? 'OFF'; const st = press?.sources?.[src.id] ?? null; const okTs = tsOf(st?.lastSuccessTs); const licensed = src.route === 'LICENSED_INTERFACE_REQUIRED';
    const state = licensed ? 'BLOCKED_EXTERNAL_APPROVAL' : desiredHere === 'OFF' || !pressOn || !pressSel.has(src.id) ? 'DISABLED_BY_PAPER_POLICY' : press === null || st === null ? 'NOT_OBSERVED' : st.state === 'IDLE' ? 'NOT_OBSERVED' : ['OBSERVED', 'NOT_MODIFIED', 'EMPTY_FEED'].includes(st.state) ? freshOr(okTs, now, FRESH_MS.press, 'ACTIVE') : okTs !== null && now - okTs <= FRESH_MS.press ? 'ACTIVE_DEGRADED' : 'BLOCKED_PROVIDER';
    rows.push(R({ id: `PRESS_${src.id}`, name: `Publisher headlines: ${src.name}`, group: 'PUBLISHER_NEWS', state, desiredState: desiredHere, lastSuccessTs: okTs, ageMs: age(okTs, now), coverage: licensed ? 'LICENSED_INTERFACE_REQUIRED (no route composed)' : st ? `${st.state}; ${st.coverage ?? 'HEADLINE_LINK_ONLY'}; admitted ${st.counters?.admitted ?? 0} / polls ${st.counters?.polls ?? 0}` : press ? 'NOT_IN_STATUS' : 'NO_STATUS_FILE', blocker: licensed ? String(src.prerequisite ?? 'licensed interface required').slice(0, 160) : state === 'DISABLED_BY_PAPER_POLICY' ? (pr?.reason ?? (!pressOn ? 'PRESS_ENABLED not true' : 'not selected in PRESS_SOURCES')) : st && !['OBSERVED', 'NOT_MODIFIED', 'EMPTY_FEED', 'IDLE'].includes(st.state) ? String(st.lastError ?? st.state).slice(0, 160) : null, detail: `${src.kind}; route ${src.route}; terms ${src.terms}; headline / link / publisher timestamp only, bodies never fetched; not a RUMOR-2 evidence provider`, authority: 'NONE' }));
  }
  // ---- MARKET RESEARCH providers (from the service status file) -----------------------------------------------------------------
  const root = marketResearchRootFromEnv(env, dataDir); const mr = readJsonBounded(path.join(root, 'status.json')); const mrTs = tsOf(mr?.nowTs); const policy = readJsonBounded(profileFileOf(profile, 'marketResearchPolicy'));
  const clients = mr?.owner?.clients ?? {}; const mrOn = env.MARKET_RESEARCH_ENABLED === 'true';
  for (const [id, pr] of Object.entries(g.marketResearch.providers)) {
    const pol = policy?.providers?.[id] ?? null; const c = clients[id] ?? null; const cred = pol?.credentialEnv ?? null; const keyPresent = cred ? present(env, cred) : true; const quotaBlocked = pol && pol.plan?.billing !== 'FREE' && !paidCallAuthorized(policy, id);
    let state; let blocker = null;
    if (!mrOn || !pol?.enabled || pr.desiredState === 'OFF') { state = 'DISABLED_BY_PAPER_POLICY'; blocker = pr.reason ?? (pol?.enabled === false ? 'disabled in the paper policy' : 'research service off'); }
    else if (cred && !keyPresent) { state = 'BLOCKED_CREDENTIAL'; blocker = `${cred} missing`; }
    else if (quotaBlocked) { state = 'BLOCKED_BUDGET'; blocker = 'plan / cost attestation required before any paid call'; }
    else if (mr === null) { state = 'NOT_OBSERVED'; blocker = 'no research status yet'; }
    else if (c === null) { state = 'NOT_OBSERVED'; blocker = 'client not reported'; }
    else state = c.runtime === 'ACTIVE' ? (c.failed > 0 && c.ok === 0 ? 'ACTIVE_DEGRADED' : 'ACTIVE') : c.runtime === 'BLOCKED' ? (c.lastFailure?.access === 'ENTITLEMENT_DENIED' ? 'BLOCKED_GEOGRAPHY' : 'BLOCKED_PROVIDER') : c.runtime === 'DEGRADED' || c.runtime === 'BACKOFF' ? 'ACTIVE_DEGRADED' : 'NOT_OBSERVED';
    if (state.startsWith('BLOCKED') && c?.lastFailure) blocker = `${c.lastFailure.kind ?? 'failure'}${c.lastFailure.access ? ` (${c.lastFailure.access})` : ''}`;
    rows.push(R({ id, name: `Market research: ${id}`, group: 'MARKET', state, desiredState: pr.desiredState, lastSuccessTs: state === 'ACTIVE' || state === 'ACTIVE_DEGRADED' ? mrTs : null, ageMs: state === 'ACTIVE' || state === 'ACTIVE_DEGRADED' ? age(mrTs, now) : null, coverage: c ? `${c.runtime}; ok ${c.ok ?? 0} / failed ${c.failed ?? 0}` : 'NO_CLIENT_STATUS', blocker, detail: pol ? `billing ${pol.plan?.billing ?? '—'}; caps ${pol.limits?.maxCallsPerDay ?? '—'}/day` : null, authority: 'EVIDENCE_ONLY' }));
  }
  // ---- DARK RESEARCH (Kraken Charts + L3): EDGE_CAPTURE only ----------------------------------------------------------------------
  const chartsOn = policy?.providers?.KRAKEN_DERIVATIVES?.enabled === true && policy?.providers?.KRAKEN_DERIVATIVES?.charts?.enabled === true; const l3On = policy?.providers?.KRAKEN_SPOT?.enabled === true && policy?.providers?.KRAKEN_SPOT?.l3?.enabled === true;
  const ds = darkStatus ?? readJsonBounded(path.join(darkResearchRootOf(root), 'edge-capture-status.json')); const dsTs = tsOf(ds?.lastSealTs ?? ds?.tsMs); const l3Keys = present(env, ['KRAKEN_L3_DATA_API_KEY', 'KRAKEN_L3_DATA_API_SECRET']);
  const runnerState = typeof ds?.state === 'string' && ds.state.startsWith('DARK_CAPTURE_') ? ds.state : null; // the runner's own verdict on its last segment
  const inFlight = ds !== null && (ds.segments ?? 0) === 0 && (ds.failures ?? 0) === 0 && !ds.charts; // started, nothing sealed or failed yet: no verdict exists
  const chartsState = !chartsOn ? 'DARK_CAPTURE_DISABLED_BY_POLICY' : ds === null || inFlight ? 'NOT_OBSERVED' : runnerState === 'DARK_CAPTURE_BLOCKED_EXTERNAL' || runnerState === 'DARK_CAPTURE_DISABLED_BY_POLICY' ? runnerState : ds.charts?.failures > 0 && (ds.charts?.calls ?? 0) === 0 ? 'DARK_CAPTURE_BLOCKED_EXTERNAL' : ds.charts?.failures > 0 || ds.capture === 'PARTIAL' ? 'DARK_CAPTURE_DEGRADED' : now - dsTs <= Math.max(FRESH_MS.dark, 2 * 1000 * (Number.isFinite(ds.segmentSeconds) ? ds.segmentSeconds : 3600)) ? 'DARK_CAPTURE_OPERATIONAL' : 'DARK_CAPTURE_DEGRADED'; // the runner publishes per sealed segment: fresh within two segment lengths
  rows.push(R({ id: 'KRAKEN_CHARTS_DARK', name: 'Kraken Futures Charts (dark capture)', group: 'DARK_RESEARCH', state: chartsState, desiredState: desired('darkEdgeCapture', 'krakenCharts'), lastSuccessTs: dsTs, ageMs: age(dsTs, now), coverage: ds?.charts ? `polls ${ds.charts.polls ?? 0}; calls ${ds.charts.calls ?? 0}; failures ${ds.charts.failures ?? 0}; capture ${ds.capture ?? '—'}` : chartsOn ? 'NO_CAPTURE_STATUS' : 'DISABLED', blocker: chartsState === 'NOT_OBSERVED' ? (inFlight && ds.running ? 'first segment in flight; no verdict until it seals' : 'no dark capture segment sealed yet') : chartsState.endsWith('BLOCKED_EXTERNAL') ? (ds?.lastError ? `${ds.lastError.code ?? 'failure'}: ${String(ds.lastError.message ?? '').slice(0, 120)}` : `charts ${ds?.charts?.lastFailureKind ?? 'failure'}`) : chartsState.endsWith('DEGRADED') ? 'partial acquisition / stale segment' : null, detail: 'EDGE_CAPTURE bundles only; zero Socrates / Judge / Watch / execution consumption; edge claim NOT_MADE', authority: 'NONE' }));
  const l3Verdict = ds?.l3?.verdict ?? null; const l3State = !l3On ? 'DARK_CAPTURE_DISABLED_BY_POLICY' : !l3Keys ? 'BLOCKED_NO_SAFE_L3_DATA_KEY' : l3Verdict === null ? 'KEY_PRESENT_UNPROVEN' : l3Verdict === 'SAFE_L3_DATA_KEY' ? (ds?.l3?.started ? (now - dsTs <= FRESH_MS.dark ? 'DARK_CAPTURE_OPERATIONAL' : 'DARK_CAPTURE_DEGRADED') : 'DARK_CAPTURE_DEGRADED') : 'BLOCKED_NO_SAFE_L3_DATA_KEY';
  rows.push(R({ id: 'KRAKEN_L3_DARK', name: 'Kraken L3 order-level (dark capture)', group: 'DARK_RESEARCH', state: l3State, desiredState: desired('darkEdgeCapture', 'krakenL3'), lastSuccessTs: l3State === 'DARK_CAPTURE_OPERATIONAL' ? dsTs : null, ageMs: l3State === 'DARK_CAPTURE_OPERATIONAL' ? age(dsTs, now) : null, coverage: ds?.l3 ? `verdict ${l3Verdict ?? '—'}; started ${ds.l3.started ? 'yes' : 'no'}; markets ${(ds.l3.markets ?? []).length}` : l3On ? 'NO_CAPTURE_STATUS' : 'DISABLED', blocker: l3State === 'BLOCKED_NO_SAFE_L3_DATA_KEY' ? (l3Keys ? `${l3Verdict}${ds?.l3?.blocker ? ` (${ds.l3.blocker})` : ''}` : 'CREDENTIAL_MISSING (dedicated data-only key; never an execution key)') : l3State === 'KEY_PRESENT_UNPROVEN' ? 'verdict requires the read-only permission probe (preflight --smoke or a capture segment)' : null, detail: 'dark-sense blocker only: never a PAPER readiness blocker', authority: 'NONE' }));
  // ---- SOCRATES ----------------------------------------------------------------------------------------------------------------
  const modelEnabled = policy?.model?.enabled === true; const modelKey = present(env, policy?.model?.credentialEnv ?? 'ANTHROPIC_API_KEY'); const modelBudget = (policy?.model?.maxEstimatedUsdPerCase ?? 0) > 0 && (policy?.model?.maxEstimatedUsdPerDay ?? 0) > 0;
  const cases = mr?.cases ?? null; const recent = Array.isArray(cases?.recent) ? cases.recent : []; const lastCase = recent.length ? tsOf(recent[recent.length - 1].finishedTs ?? recent[recent.length - 1].createdTs) : null;
  rows.push(R({ id: 'SOCRATES_CASE_RUNTIME', name: 'Socrates case runtime', group: 'SOCRATES', state: !mrOn ? 'DISABLED_BY_PAPER_POLICY' : mr === null ? 'NOT_OBSERVED' : mr.state === 'ACTIVE' ? 'ACTIVE' : 'ACTIVE_DEGRADED', desiredState: desired('socrates', 'caseRuntime'), lastSuccessTs: lastCase, ageMs: age(lastCase, now), coverage: cases ? `queued ${cases.queued ?? 0}; running ${cases.running ?? 0}; recent ${recent.length}` : 'NO_STATUS', blocker: mr === null && mrOn ? 'no research status yet' : mr && mr.state !== 'ACTIVE' ? `service ${mr.state}` : null, detail: 'sealed cases are the ONLY Socrates output the Judge reads (read-only, validated); a case without a model seals BUDGET_BLOCKED', authority: 'SEALED_CASE_INPUT_ONLY' }));
  rows.push(R({ id: 'SOCRATES_MODEL', name: 'Socrates model (interpretation only)', group: 'SOCRATES', state: !modelEnabled ? 'DISABLED_BY_PAPER_POLICY' : !modelKey ? 'BLOCKED_CREDENTIAL' : !modelBudget ? 'BLOCKED_BUDGET' : 'ACTIVE', desiredState: desired('socrates', 'model'), lastSuccessTs: null, ageMs: null, coverage: modelEnabled ? `USD caps per case ${policy?.model?.maxEstimatedUsdPerCase ?? 0} / day ${policy?.model?.maxEstimatedUsdPerDay ?? 0}` : 'model.enabled false in the paper policy', blocker: !modelEnabled ? 'MODEL_DISABLED_IN_POLICY (explicit USD caps + enable required; never inferred from a key)' : !modelKey ? `${policy?.model?.credentialEnv ?? 'ANTHROPIC_API_KEY'} missing` : !modelBudget ? 'BUDGET_NOT_CONFIGURED' : null, detail: 'output is interpretation, never source truth; schema-validated; fail-closed', authority: 'NONE' }));
  // ---- JUDGE / WATCH (the execution projection FILE, bound to the running composition when live) --------------------------------------
  const expected = live.judgeRun ? { accountId: live.judgeRun.accountId, runMode: live.judgeRun.mode } : null; const projFile = path.join(dataDir, 'execution', 'projection.json'); const proj = readExecutionProjection({ now, file: projFile, expected });
  const judgeOn = env.JUDGE_ENABLED === 'true'; const rawProj = readJsonBounded(path.join(dataDir, 'execution', 'projection.json')); const projTs = tsOf(rawProj?.ts);
  const paperMode = env.JUDGE_MODE === 'PAPER'; const dbUrl = present(env, 'DATABASE_URL');
  const judgeState = !judgeOn ? 'DISABLED_BY_PAPER_POLICY' : !paperMode ? 'BLOCKED_PROVIDER' : !dbUrl ? 'BLOCKED_CREDENTIAL' : proj === null ? 'NOT_OBSERVED' : proj.state === 'FRESH' ? (proj.accountKind === 'PAPER' ? 'ACTIVE' : 'BLOCKED_PROVIDER') : proj.state === 'STALE' ? 'ACTIVE_DEGRADED' : 'BLOCKED_PROVIDER';
  rows.push(R({ id: 'JUDGE', name: 'Judge (PAPER)', group: 'JUDGE', state: judgeState, desiredState: desired('judge', 'judge'), lastSuccessTs: projTs, ageMs: age(projTs, now), coverage: proj ? `${proj.state}; ${proj.accountKind ?? '—'} ${proj.runMode ?? '—'}; open ${rawProj?.positions?.length ?? 0}; pending ${rawProj?.pendingOrders?.length ?? 0}` : 'NO_PROJECTION', blocker: !judgeOn ? 'JUDGE_ENABLED false' : !paperMode ? `JUDGE_MODE ${env.JUDGE_MODE ?? 'unset'} is not PAPER (the paper profile forces PAPER)` : !dbUrl ? 'DATABASE_URL missing (PostgreSQL journal authority)' : proj === null ? 'no projection yet (composition not started or account uninitialized)' : proj.state === 'REJECTED' ? `projection rejected: ${proj.reason}` : proj.state === 'STALE' ? 'projection stale' : proj.accountKind !== 'PAPER' ? `account kind ${proj.accountKind}` : null, detail: `real money DISABLED; live orders DISABLED; allowPrivate ${env.JUDGE_ALLOW_PRIVATE ?? 'unset'}; allowOrders ${env.JUDGE_ALLOW_ORDERS ?? 'unset'}; restrictions ${(rawProj?.restrictions ?? []).join(',') || 'none'}`, authority: 'PAPER_SIMULATION_ONLY' }));
  const watch = rawProj?.watch ?? null; const openPositions = Array.isArray(rawProj?.positions) ? rawProj.positions : [];
  rows.push(R({ id: 'WATCH', name: 'The Watch (post-entry supervision)', group: 'WATCH', state: judgeState === 'ACTIVE' ? 'ACTIVE' : judgeState === 'ACTIVE_DEGRADED' ? 'ACTIVE_DEGRADED' : judgeState, desiredState: desired('watch', 'watch'), lastSuccessTs: projTs, ageMs: age(projTs, now), coverage: proj ? `${openPositions.length} supervised position(s)${watch && typeof watch === 'object' ? `; watch ${JSON.stringify(watch).slice(0, 80)}` : ''}` : 'NO_PROJECTION', blocker: judgeState === 'ACTIVE' ? null : 'follows the Judge composition', detail: openPositions.length ? openPositions.map((p) => `${p.pair} ${p.state} exit ${p.exit?.phase ?? p.exit?.reason ?? '—'}`).join(' · ').slice(0, 200) : 'flat', authority: 'PAPER_EXIT_INTENT_ONLY' }));
  const gov=readJsonBounded(path.join(dataDir,'governance','status.json'));
  const govRegistry=loadRegistry([...VERIFIED_MAPPINGS,...(Array.isArray(config.governance?.verifiedMappings)?config.governance.verifiedMappings:[])]);
  const govOn=config.governance?.enabled===true, tallyGate=tallyStatus(env,govRegistry), tallyTs=tsOf(gov?.providers?.tallyLastSuccessTs), tallyRaw=gov?.providers?.tally;
  const tallyState=!govOn?'DISABLED_BY_PAPER_POLICY':tallyGate==='UNAVAILABLE_MISSING_CREDENTIAL'?'BLOCKED_CREDENTIAL':tallyGate!=='READY_NOT_OBSERVED'?'CONFIG_REQUIRED:TALLY_GOVERNORS':!gov?'NOT_OBSERVED':['OBSERVED','EMPTY'].includes(tallyRaw)?freshOr(tallyTs,now,FRESH_MS.dark,gov.unpersistedPendingEvidence>0?'ACTIVE_DEGRADED':'ACTIVE'):tallyRaw==='READY_NOT_OBSERVED'?'NOT_OBSERVED':'BLOCKED_PROVIDER';
  rows.push(R({id:'GOVERNANCE_TALLY',name:'Tally governance (indexed)',group:'DARK_RESEARCH',state:tallyState,desiredState:govOn?'REQUEST':'OFF',lastSuccessTs:tallyTs,ageMs:age(tallyTs,now),coverage:gov?.providers?.tallyCoverage??'NOT_OBSERVED',blocker:tallyState==='ACTIVE'?null:tallyGate!=='READY_NOT_OBSERVED'?tallyGate:gov?.initState??tallyRaw??'no collected evidence yet',detail:'Verified governors only; indexed votes and execution states, provider clocks separate from knowledge clocks; current source journal and Memory reader',authority:'NONE'}));
  // ---- controls + persistence context (never a sense; shown beside the rows) ---------------------------------------------------------
  let controls = null; try { const c = readControls(); controls = { kill: Boolean(c?.kill?.active), cage: Boolean(c?.cage?.active) }; } catch { controls = null; }
  let locks = null; try { const l = dailyLockStatus(); locks = { level: l.level, strikesAllowed: l.strikes_allowed, sessionDate: l.session_date, simulated: l.simulated }; } catch { locks = null; }
  const persistence = live.persistence && typeof live.persistence.health === 'function' ? live.persistence.health() : null;
  const groups = Object.fromEntries(SNAPSHOT_GROUPS.map((gr) => [gr, rows.filter((r) => r.group === gr).map((r) => r.id)]));
  const counts = {}; for (const r of rows) counts[r.state] = (counts[r.state] ?? 0) + 1;
  const snap = { snapshotVersion: SNAPSHOT_VERSION, generatedTs: now, profile: profile.profileName, runtimeMode: profile.runtimeMode, authority: { realMoney: 'DISABLED', liveOrders: 'DISABLED', withdrawFunding: 'DISABLED', judgeMode: env.JUDGE_MODE ?? null, darkKrakenJudgeAuthority: 'NONE', darkKrakenSocratesAuthority: 'NONE' }, groups, rows, counts, controls, locks, persistence: persistence ? { status: persistence.status ?? null, databaseConfigured: persistence.databaseConfigured ?? Boolean(env.DATABASE_URL), durabilityRequired: persistence.durabilityRequired ?? null, permissionLock: persistence.permissionLock ?? null } : { status: null, databaseConfigured: dbUrl, durabilityRequired: null, permissionLock: null }, law: 'a sense is ACTIVE only from a fresh status record; NOT_OBSERVED / BLOCKED_* / DISABLED_BY_PAPER_POLICY otherwise; no secret value ever enters this snapshot' };
  const text = JSON.stringify(snap); if (!noSecrets(text)) throw new Error('sensor snapshot: a value-like secret reached the snapshot');
  return snap;
}
export const snapshotRow = (snap, id) => snap.rows.find((r) => r.id === id) ?? null;
